### ISSUE TITLE
Set render target as texture by name (DEF-2880)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3104]
Currently you can only assign render targets as textures to a specific numbered sampler. This is problematic if the things you are drawing have different number of samplers because of different materials. Or if they don't want to use the render target at all.

If it was possible to assign a texture in the render script by sampler name in addition of just a number, then the use of render targets would be substantially improved. The engine should obviously assign the render target to the correct sampler when drawing.

```
-- To assign render target to sampler name
render.enable_texture(hash("shadow_map"), shadow_map_render_target, render.BUFFER_COLOR_BIT)
render.draw(model_predicate)

-- To remove the assignment
render.disable_texture(hash("shadow_map"))
```

**Comment by Jhonnyg** [comment]
Closing in favour of this: https://github.com/defold/defold/issues/7440
