### ISSUE TITLE
Model getting wrong texture under certain orientations (DEF-3040)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3106]
*Description:*
From Ed2-issues: (LINK REMOVED)Repro case: (LINK REMOVED)It seems that there is some issue when using models with multiple textures. Under some situations the "wrong" texture is being used/set during runtime, see linked ed2-issue and video.

**Comment by AGulev** [comment]
hard to figure our without a repo case
seems outdated

**Comment by britzl** [comment]
> hard to figure our without a repo case seems outdated

Agree. Closing.
