### ISSUE TITLE
Signing app using both v1 and v2 (DEF-3952)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3121]
Description:
Would be great to sign APK using both v1 and v2

Use case:
It would make the process of building Google Instant Games faster.
Also, it increases the speed of APK installation:

{code:java}
For maximum compatibility, sign applications with all schemes, first with v1, then v2, and then v3. Android 7.0+ and newer devices install apps signed with v2+ schemes more quickly than those signed only with v1 scheme. Older Android platforms ignore v2+ signatures and thus need apps to contain v1 signatures.
{code}

Documentation: (LINK REMOVED)Library for signing on GoLang with  Apache-2.0 license (for example):
(LINK REMOVED)Example of using:
(LINK REMOVED)

**Comment by britzl** [comment]
We should use the AAB pipeline to generate an APK. This will solve the app signing issue. Issue: #4930

**Comment by AGulev** [comment]
Yes, you right. AAB flow works great!
