### ISSUE TITLE
Android Instant Games (DEF-3937)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3136]
Requires newer app signing: https://github.com/defold/defold/issues/3121

See branch/repo by @AGulev

**Comment by AGulev** [comment]
Hey  @britzl 
Here is repo: https://github.com/defold/extension-instantapp
and here is manual: https://github.com/defold/doc/pull/52

I think everything is ready for release. Of it's not perfect especially from docs side, but it works.
Feel free to release it. 
I'll continue support this feature, ofc.

**Comment by AGulev** [comment]
https://forum.defold.com/t/google-play-instant-support/66606/2
