### ISSUE TITLE
Rotation of Kinematic collision objects is not smooth (DEF-771)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3165]
STR:

1. Open Defold project "Bugs" (if you need it shared, ask Mikael Sker)
2. Start from DEF-771/main.collection

Notice that the graphics tilemap rotates smoothly, but that the physics shape does not (physics debug is on).
2016-01-14 13:04:20 (andreas.tadic)
This ought to be an easy fix, but estimated as 2 until we have a clear picture of any possible side-effects.

**Comment by AGulev** [comment]
it seems like something really outdated
