### ISSUE TITLE
Physics: Rotating a GO 180 over Y flips physics shape over X. (DEF-1117)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3166]
STR:

1. Create GO with physics. Offset the physics along Y axis.
2. Rotate the GO 180 degrees over Y (horizontal flip)

Notice how the physics will flip over the X axis.

There is a test case in the BUGS project.

2017-11-23 14:04:25 (Bjorn.Ritzl)
We (Samuel) encountered this issue on the offsite at Villa Sandudden. Quite annoying actually.

**Comment by JCash** [comment]
Fixed by https://github.com/defold/defold/pull/4368

**Comment by britzl** [comment]
https://defold.com/manuals/physics/#rotating-collision-shapes-in-2d-physics
