### ISSUE TITLE
Decouple physics timestep from engine timestep (DEF-3769)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3169]
Decoupling the physics timestep from the global game timestep lets us be more flexible in using actual frame duration timestep in the rest of the engine, which should work well for most cases that are otherwise hard to cater for using a global fixed timestep (variable refreshrate monitors, phone battery saving modes, missing desktop drivers etc.).

Design doc (ongoing):(LINK REMOVED)

**Comment by AGulev** [comment]
Related: https://github.com/defold/defold/issues/3168
