### ISSUE TITLE
GameObject scales do not apply to physics objects (DEF-521)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3189]
Why?

When scaling graphical objects it is usually desirable that any collision hulls attached to them should also scale.

What?

Apply scales from the game object transforms to collision hulls.

See -DEF-681- for further details.

Also reported on forum: [(LINK REMOVED)
2015-03-20 10:39:40 (linnea.leu)
Older then 2 months, closing this. Reopen if necessary 
2017-03-13 10:18:26 (M.Westerdahl)
Added a first test for physics scaling in Box2D and Bullet.
(LINK REMOVED)Also, some first notes from this test:
(LINK REMOVED)
2017-12-06 11:18:50 (M.Westerdahl)
In order to finish physics scaling, we want to subscribe to the changed transform events

**Comment by JCash** [comment]
Design document:
https://docs.google.com/document/d/1WAWHMh10w5fop3NJPMKwHBXm76kFwSvFs4axIdsGx88/edit?usp=sharing
