### ISSUE TITLE
Render script refactoring (DEF-3832)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3198]
Would be great to refactor our default render script to avoid memory allocations in update function.
This is not really optimisation, it's just for consistency between Defold idiology and code that we have inside the engine as default.

**Comment by AGulev** [comment]
@britzl 
I have nice render_script in my project that was polished by using with different projects, but it uses render_helper.lua module. What do you think if we add helper module together with default render script. 

This helper script contains 
action_to_mode(action, gui_mode)
world_to_mode(pos, gui_mode)
screen_to_gui(pos, gui_mode)

That helps to convert different coordinates to different gui modes (fit, zoom, stretch)

**Comment by britzl** [comment]
Interesting. Can you share our with me?

**Comment by AGulev** [comment]
maybe we should think about such improvements 

this topic pops up again here https://forum.defold.com/t/defold-popularity-discussion/67564/125
<img width="731" alt="image" src="https://user-images.githubusercontent.com/2209596/205435150-8f79849e-782d-4b5e-8716-04370071fafc.png">

**Comment by britzl** [comment]
Yes, absolutely. This should in my opinion be part of the camera API. The camera knows it's own view projection and should be able to calculate a screen to world translation based on it (it will need to get window dimensions though).
