### ISSUE TITLE
Add API to "un-cache" liveupdate resources for a collection proxy (DEF-3114)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3207]
Use-case: Your game uses liveupdate to download new levels as the player progresses. A player is at level 1000. This means all previous levels are still stored locally, which is wasteful. Over time the apps storage will just grow and grow as the player progresses through the levels.

In this example it would be nice to be able to delete the resources for level 1-500 for example when the player is so far ahead. If the player decides to go back and play level 1 again the resources could simply be downloaded with liveupdate once more.

Some API to un-cache a collectionproxy:s liveupdate resources, for example;

{code:java}
collectionproxy.delete_liveupdate_resource("#proxy_level1_500")
{code}

Naming pending :)

**Comment by AGulev** [comment]
dups of https://github.com/defold/defold/issues/4722
