### ISSUE TITLE
Add option to initialize with different OpenGL versions (DEF-3796)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3211]
[(LINK REMOVED)Since the last changes to our content pipeline to support higher shader models, due to the transpiling, we might want to look into supporting different OpenGL versions.

E.g. if we have a property "graphics.opengl" = ES2|ES3|3.1|4.1
or similar, we might open up the possibility for our users to do cool things in anticipation of our Vulkan support
2019-02-22 14:29:24 (jhonny.goransson)
+1 for this! instant renderdoc support :)

**Comment by Jhonnyg** [comment]
We kinda have this already, right? You can't request a specific version but you will always get the highest one available.

**Comment by britzl** [comment]
I think you are right @Jhonnyg . Is there any point in keeping this feature request around or can we close it?

**Comment by Jhonnyg** [comment]
No, there's no point keeping this. I'm closing it.
