### ISSUE TITLE
Multiple textures on sprites

### ISSUE THREAD

**Issue by britzl** [defold/defold#3233]
In order to do multiple passes with different shaders and/or tags we need to be able to add many material and texture pairs to a sprite or a spine.

*Use case:*
The dynamic light engine for Cohesion needs to be able to draw the same sprite with different shaders and textures to different render targets Currently this is solved by having multiple sprite components on each game object. This works "ok" with simple sprites (allthough syncing animations could be a problem), but with spines it means having two spine animations to keep in sync, and the extra overhead of having two spines to manage. It simply isn't a scalable workflow.
2016-05-30 12:47:19 (ingela.garneij)
Needed before Cohesion playtests (October?)
2016-09-21 12:10:22 (Sara.Cederberg)
[~sven.andersson] How does this relate to (LINK REMOVED)
2017-06-12 10:49:51 (Fredrik.Malmer)
Would like to add that this is also needed on models.
2017-09-14 16:57:18 (Fredrik.Malmer)
I would recommend taking a holistic view when designing this and also consider the following key missing related features:

* Overrides of material properties on the sprite/model/particle/gui (setting the sprite atlas today is just a special case of this).
* Default texture file assignments in materials
* Adding render state settings to materials

Doing this feature without considering these things would likely lead to a design and a file format that will need to be redone soon in the future.
2017-10-03 14:38:08 (Fredrik.Malmer)
Also to consider: Right now models can only take in one object with one material. This is very limiting. What we really need for models is to be able to contain several objects with different materials. In other words support for many materials per model, preferably through the use of material ids. See: DEF-2910

Any design needs to account for this very probable future.

**Comment by britzl** [comment]
Duplicate of https://github.com/defold/defold/issues/3322

**Comment by britzl** [comment]
We should simplify this task and not try to make the UV coordinates to match up for albedo and normal textures. It adds a bit of cost to track duplicate UVs but it will be much easier to implement. We should instead have multiple image dropdowns/selectors in the properties panel to select which image to use from each atlas.

**Comment by AGulev** [comment]
Multi-Texturing is the first step for implementation multy-page atlases that could help to save a lot of RAM and drawcalls in big Defold projects. Also it’s useful for a scalability of the big projects (they add content really fast). For now devs have to search for a tradeoff between RAM/draw calls/disk space (edited)

**Comment by JCash** [comment]
Created a design document that also proposes a solution for flipbook animations:
https://docs.google.com/document/d/1ftcv42FgudxjdNB6hnakhGXRDwmWs4RSf3_vFeKGUO0/edit?usp=sharing

**Comment by JCash** [comment]
Rename this task to deal with sprites specifically

Models + multiple materials has a ticket here: https://github.com/defold/defold/issues/3234

**Comment by Jhonnyg** [comment]
> Double check that the design (see doc above) will work with the new vertex attributes. How to match sampler with vertex attributes.

Not sure I understand the question, why match a sampler with a vertex attribute?

**Comment by britzl** [comment]
> > Double check that the design (see doc above) will work with the new vertex attributes. How to match sampler with vertex attributes.
> 
> Not sure I understand the question, why match a sampler with a vertex attribute?

Me neither. It was brought up by @JCash and @matgis during the morning meeting :-)

**Comment by JCash** [comment]
Added PR for first step of our design:
https://github.com/defold/defold/pull/8054
