### ISSUE TITLE
Multiple objects and materials in one model (DEF-2910)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3234]
Models imported today can only support one object per file. This is very limiting. It is desired to be able to import a model file with many models in it, each which can have different materials assigned, which should be able to be set, based on name/id, in the defold editor as well as through code.
2017-10-12 13:19:39 (andreas.tadic)
What effectively suggesting is really containing a scene within the scope of a model component.

To compare with what you'd have to do now is to create several gameobjects with one (or more) models each.

Instead, a solution would be to be able to support loading a model with many materials/meshes and contain this as a subtree within a model (like spine does with bones).

This is indeed a feature that we will want.
2017-10-12 16:45:14 (Fredrik.Malmer)
That was exactly what I was suggesting. That you access these "internal" game objects the same way you access the bones in a model, using the existing model.get_go(). That way you can parent stuff to them via code. Or animate them with go.animate and move them around. But from an editor perspective it should be contained within the one model component, which has the only difference that there are multiple material slots, one for each assigned material in the source file.

Preferably it should be possible, via code, to reparent things in the model so that one of the objects loaded in the model is moved out of it. Only runtime obviously.

Also, if there are empty dummy objects in the model scene they should also be imported as empty game objects. Very useful for attachment points.

**Comment by JCash** [comment]
The multiple model support in a single .gltf file was added in 1.6.1

The multiple material support is already in (in the engine, and editing is currently being worked on)
