### ISSUE TITLE
Support for motion paths in a Spine json (DEF-2536)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3241]
Description:
Currently Defold does not support the paths feature created in Spine.

Steps to reproduce:
Create a spine file with a motion path and create a spine scene. The movement around the path is not shown. (I can supply a spine json if needed)

Expected result:
The motion in the spine file should be around a path that is exported in the json file.

Actual result:
Nothing happens.

**Comment by AGulev** [comment]
Works fine in the new runtime https://forum.defold.com/t/official-spine-runtime-extension-beta-testing/70260
