### ISSUE TITLE
Weird behavior for go.animate() when spawning and deleting game objects (DEF-2748)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3252]
Description:
 Game object A contains a sprite, script and factory.
 Game object B contains a sprite and a script.

A animates (go.animate) the tint.y property of the sprite in init().
 When A is deleted it spawns an instance of game object B in it's final().
 B sets (go.set) the tint property of the sprite and it animates (go.animate) the tint.w property of the sprite in init().

The first time an instance of A is deleted the tint.w animation of B will not run. The go.set on B will work though.
 Subsequent create/delete cycles will work and the tint.w property of B will animate as expected.

If multiple instances of A are created and then deleted one by one only the first instance of B will animate properly. The rest of them will not animate.

If the go.set call on B is removed everything works as expected in all cases.

Steps to reproduce:
 Download and run the attached example. Left click to spawn A, right click to delete A.

Expected result:
 go.animate should work in all cases

Actual result:
 go.animate doesn't always work

From the forum: https://forum.defold.com/t/animate-tint-affecting-wrong-object-if-spawning-on-final-def-2748/8946

**Comment by AGulev** [comment]
I've tried example from the forum post and can't reproduce it in the latest defold (1.7.0)
