### ISSUE TITLE
go.animate() of sprite tint not working under certain circumstances (DEF-2095)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3253]
If you spawn several game objects using factory.create(), then immediately delete the first object and at the same time do go.animate() on sprite tint it will play the animations on all of the game objects but not change tint on the most recently created game object. Reported on the forum: https://forum.defold.com/t/go-animate-sprite-tint-bug-def-2095/2820

**Comment by britzl** [comment]
Sems related to #3252

**Comment by AGulev** [comment]
The same as https://github.com/defold/defold/issues/3252
I've tried example from the forum post and can't reproduce it in the latest Defold (1.7.0)
