### ISSUE TITLE
Spine3: Spine transform-constraints dont work in Defold (DEF-1908)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3291]
Yeah, like I said. Spine has transform constraints now, that can temporarily link one bones transform, rotation and scale to another bone. This is very useful. Can we have this work in Defold as well. Please?

2016-06-09 10:18:25 (ingela.garneij)
Defold does not have support for spine 3 yet

**Comment by AGulev** [comment]
Works fine in the new runtime https://forum.defold.com/t/official-spine-runtime-extension-beta-testing/70260
