### ISSUE TITLE
General profiler improvements (DEF-2724)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3298]
As described in the design doc;

- [x]  * Fix/sort time chart/slices in visual profiler so each entry is drawn in correct call order.
- [x]  * Send last N log lines to the web profiler.
- [ ]  * ... Or supply full log, we already have the option to store it to disk; could be exposed through a separate web profiler URL.

- [x]  * Add time/frame number to sample list in Web profiler.
- [ ]  * Add sort function to tables in Web profiler.
- [x]  * Add counter for vertice and triangle count to visual profiler?
- [ ]  * While we are at it; restyle web profiler to fit with Ed2 and Defold web styles?

**Comment by AGulev** [comment]
solved with remotery
