### ISSUE TITLE
Add object hierarchy view to profiler (DEF-2754)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3299]
Investigate if it's a good idea to do this, and if so, how to do it in a clear and easy to use fashion.

Apparently Unity seems to have a tool for this.

Forum:
(LINK REMOVED)
2019-02-15 23:01:55 (alexey.gulev)
It looks like you solved this issue? [~M.Westerdahl]

**Comment by AGulev** [comment]
solved (it is in old profiler)
