### ISSUE TITLE
Improved profiler (CPU/memory usage) (DEF-1058)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3300]
Expanded functionality for the profiler (including the web profiler):
-Memory usage. (How much allocated memory goes for the textures? etc)
-CPU usage. (How much of the CPU goes to physics calculations? etc)
-Self/Total times, Startup profiling (load), Script profiling (filename)
-Auto-update. For the web profiler, this can be done with: <meta http-equiv="refresh" content="5" >

Most critical atm is the lack of hardware insights - primarly CPU and memory usage. This is relevant and important for all Genesis projects.

CPU usage (with a breakdown):
-Total usage
-Rendering
-Scripts
-Physics
-VSync
-Garbage collector
-Other

Memory (with a breakdown):
-Total allocated
-Total available (Not counting "Wired" memory)
-Texture memory (available)
-Texture memory (allocated)

No workaround available. You can connect a device to a Mac and do profiling via XCode - which is a hassle (not very practical) and which doesn't really give you any proper hardware insights (no breakdowns - what is costing performance??). Also: not everyone will develop Defold games in Mac environments.

Over the long course the profiler needs additional improvements and features (info on the rendering and texturing types used (opaque, transparent)), number of animations and so on - but for now the above features described in this ticket are the most-wanted and most-useful ones - features that needs priority!
2016-05-10 13:13:51 (Martin.Dahlin)
I'm editing this ticket with a more extensive description (adding some).
2016-09-16 11:10:24 (Mattias.Hedberg)
Currently there is a split between 'static' and 'dynamic' textures.
It would be nice to keep that split when showing memory usage of textures.
Additionally If there would be possible to have 'static texture atlas', 'dynamic' and 'static texture'. A split between textures that are in atlases and that are not.

Even better would be if we could see a list of current textures in memory.
2017-03-21 11:13:06 (Mattias.Hedberg)
Being able to see size, depth, name and memory usage of all textures in memory is a dream of mine

As well as seeing what all other memory goes towards 
2017-03-28 16:43:30 (johan.flod)
I would like to see what images/atlases that are in memory at a given time on device. A list of the 10 largest atlases/images by size in kB. 
2017-04-18 14:32:00 (Mattias.Hedberg)
Would gladly take a peek at any design document you guys make up :)
2017-04-18 18:00:51 (andreas.tadic)
Also, please check DEF-2572 regarding notes on inconsistent report of loaded textures (gui vs not gui)
2017-04-25 16:59:30 (sven.andersson)
Design/Plan Document: (LINK REMOVED)

**Comment by AGulev** [comment]
It would be nice to make a task with action points out of it for the future improvements of the profiler

**Comment by AGulev** [comment]
I think this task is too abstract and outdated.
