### ISSUE TITLE
Get profiler values as a Lua table (DEF-1900)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3301]
It would be nice if it was possible to get the profiler values as a Lua table, to be used for other things (send diagnostics to server or display in own gui)

(LINK REMOVED)
2016-10-05 12:27:34 (Walid.Fayad)
We are interested on this in presto for tracking and sending diagnostics to server, so we'd like to be able to read this table (or at least as much of it as possible) in a non-debug environment.

**Comment by AGulev** [comment]
it's possible to do using this extension: https://github.com/defold/extension-profile-counters
maybe we can add the same or similar into the standard profiler lib, not sure if we need so

**Comment by britzl** [comment]
The extension is good enough. Closing.
