### ISSUE TITLE
Profiler : GUI.ActiveNodes missmatch (DEF-1285)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3302]
*What:*
The profiler value GUI.ActiveNodes, is not an accurate presentation. This since all active child elements to a disabled parent node, are included in the count.

*Expected behaviour:*
* When disabling a parent node, all child elements should also be considered disabled and not accounted for.

Repro:
* Klibb commit: 994905b
* Open view_pool.lua
* switch between disabling all cloned nodes or not.

**Comment by Temeez** [comment]
Did not find this issue when searching "GuiActiveNodes", which is how this entry is presented in the profiler. Spend a bit too long trying to figure out why the child nodes do not get disabled with their parent, when they apparently are. 🧱 🔨
