### ISSUE TITLE
dmengine_headless does not include extensions (DEF-1383)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3305]
I discovered that dmengine_headless doesn't include any extensions, most notably the recently introduced crash module. Since there really is no reason for dmengine_headless to not include extensions (at least not crash) I suggest that we add extensions to headless as well.
2019-02-15 20:40:10 (alexey.gulev)
[~Bjorn.Ritzl] is this still important now when we can build our own headless version of the engine?

**Comment by AGulev** [comment]
can't repo
