### ISSUE TITLE
Custom resource folder discrepancy bob/ed2 (DEF-3766)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3310]
Editor 2 allows custom_resources in game.project to point to a directory, and the tooltip says "If directories are specified, all files and directories in that directory are recursively included". While bundling however, the editor bails with an error if a directory is used.

!Screen Shot 2019-02-07 at 10.10.40.png!

**Comment by dapetcu21** [comment]
I can't repro this with a new project. Also, Interrogation used directories as custom_resources since forever and we had no issues in either editor nor bob. Maybe this is an old issue?

**Comment by britzl** [comment]
Yeah, let's close this one. Unable to reproduce.
