### ISSUE TITLE
Calling go.get on a sprite component property returns wrong data (DEF-3710)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3327]
Description:

Steps to reproduce:

1) Create a game object and attach a sprite and a script
 2) In the init function in the script, add:
   sprite.set_constant("#sprite", "tint", vmath.vector4(-1))
   *Alternatively*
   go.set("#sprite","tint",vmath.vector4(-1))
 3) In the update function in the script, add:
   local v = go.get("#sprite","tint")

Expected result:
 v = vmath.vector4(-1)

Actual result:
 v = vmath.vector4(1) (material default)

**Comment by K-Klear** [comment]
I just ran into this and found a workaround:

go.get("#sprite", "tint.x") returns the expected value.

**Comment by AGulev** [comment]
Can't reproduce issue in Defold 1.2.190
