### ISSUE TITLE
Add signature file to the DefoldSDK.zip (DEF-3704)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3329]
Sometimes, the download step seems to fail, but it doesn't manifest itself until later in the build process.

E.g. alongside of defoldsdk.zip, we could have a defoldsdk.sha256 which contains the checksum of defoldsdk.zip

This way, the Extender server can verify that the sdk has been downloaded properly

**Comment by ekharkunov** [comment]
Also created a https://github.com/defold/extender/issues/334 to implement verification on Extender side.
