### ISSUE TITLE
Tracking is added to glyph width (DEF-3621)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3330]
All font node have some trailing extra "space". On long string it isn't that noticible (because it is only a fraction of the whole lenght) but it is on single characters.

[~M.Westerdahl] Said on slack:

Probably not new. I think its because we count the tracking before adding the next glyph:
width += (int16_t) (g->m_Advance + tracking);
So, if you only have one character, youll get the added tracking at the end as well
2018-11-14 09:48:45 (Mattias.Hedberg)
Maybe this isn't the tracking, the node doesn't have tracking added on it (still 0).
2019-01-10 12:53:14 (Niklas.Westberg)
Looks to me like the difference is lack of kerning when the characters are rendered individually.
2019-01-10 13:31:33 (Mattias.Hedberg)
Preface: I know nothing about fonts

Isn't Kerning there to move the characters _closer_ together? If that is the case then why is the character _bigger_?
2019-01-10 13:32:45 (Mattias.Hedberg)
Look at "k" and the "visual guide" under it. The "k" extends a few extra pixels. This happens true for every character.
2019-01-10 13:50:20 (Mattias.Hedberg)
Thinking about it some extra I guess it can still be the Kerning.

So the solution is one of the following then
 * Extract the kerning data with fonttools or [(LINK REMOVED) * Use a monospaced font
 * [~Walid.Fayad]s idea of calulating the kerning by _"get the metrics of the first two letters together, diff that with the size of just one and then use the difference as the start offset for the next one"_
2019-01-11 13:31:13 (Niklas.Westberg)
Sounded to me like [~Walid.Fayad] could work around it. Are we satisfied with what's available then?
2019-01-11 13:39:20 (Walid.Fayad)
Let's wait until we are done with the font and see if the team is happy with the overall result. We can downprioritize to minor until then. I also don't know what the original use for this feature was, it could be intended for something else.

**Comment by AGulev** [comment]
outdated task
