### ISSUE TITLE
otf font fails with divide by 0 (DEF-2509)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3346]
Description:

When I try to create a .font file from an otf font I get a divide by 0 error and the font creation fails. The font can be previewed on my Mac.

Steps to reproduce:

UseGoogle's Noto Sans CJK JP (NotoSansCJKjp-Regular.otf) from[(LINK REMOVED)

Expected result:

The font should be created without an error

Actual result:

I get an error and the font is non-functioning

From the forum:[(LINK REMOVED)
2017-02-17 11:27:18 (mikael.saker)
Added Source Han Sans JP that causes the same error.

**Comment by britzl** [comment]
Trying with several different fonts (https://github.com/googlefonts/noto-cjk/blob/master/NotoSansCJKjp-Regular.otf and https://fonts.google.com/specimen/Noto+Sans+JP?query=noto+sans+) but no problems. The original issue is from 2017 and we rewrote the font importer since then. My guess is that we solved the problem.

**Comment by subsoap** [comment]
@britzl There was a font that I tried at some point somewhat recently that didn't work, it was for sure an otf, but I didn't report it because there was an issue already. So probably someone will report again eventually.

**Comment by britzl** [comment]
Hmm, ok, we'll reopen this issue if someone can present a font that doesn't work!
