### ISSUE TITLE
Text input using a non western keyboard is not working (DEF-3629)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3351]
*Description*: It should be possible to input Chinese, Korean and other non-western language characters using a keyboard

*Steps to reproduce*:

Install Chinese or Korean language

Set up key binding for text input

Switch to Chinese language and try to type on your keyboard

Notice that you get no input events when typing

*Expected result*: I should get input events with the action table containing the pressed key

*Actual result*: I do not get any input events

**Comment by britzl** [comment]
I believe we need to look at win32_window.c and the translateChar() function:

https://github.com/defold/defold/blob/dev/engine/glfw/lib/win32/win32_window.c#L615-L670

**Comment by evanlabs** [comment]
@britzl Any progress on supporting keyboard input for non-western characters?

**Comment by evanlabs** [comment]
@britzl There are a lot of new changes in glfw 3.x to support windows non-western text keyboard input. Does defold plan to upgrade glfw to version 3.x? Looking forward to supporting non-western language input, it will be a great experience for Asian developers.

**Comment by evanlabs** [comment]
I have not been able to successfully build the source code of defold on the Windows platform.
Of course, I'm very much looking forward to contributing to defold.

**Comment by evanlabs** [comment]
@britzl Is it possible to defold upgrade glfw to 3.x?

**Comment by evanlabs** [comment]
@britzl Sorry, just saw in the engine docs that defold uses a somewhat modified version of GLFW.

**Comment by evanlabs** [comment]
@britzl Is there any plan to move the message handling about WM_CHAR and WM_UNICHAR in GLFW 3.0 to GLFW used by Defold.
Maybe it can solve the problem that non-Western input methods cannot be used on the Windows.

**Comment by britzl** [comment]
@evanlabs I'm sorry for not responding to your questions! I saw the PR, great stuff!

Regarding GLFW3: We're not really happy with the Frankenstein's Monster of a GLFW version that we are using now, but it works and we're not in a position where we are ready to move to a newer version.
