### ISSUE TITLE
Render issue with BmFonts in bundled applications (DEF-3584)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3367]
Description:

A bundled application that renders text with a bmfont resource doesn't produce the correct output.

Expected result:

!Screen Shot 2018-10-31 at 15.13.05.png|width=217,height=116!

Actual result:

!Screen Shot 2018-10-31 at 15.13.23.png|width=218,height=119!

**Comment by AGulev** [comment]
this ticket doesn't make sense without screenshots. Do we have screenshots here?

**Comment by britzl** [comment]
Nope. Let's close it!
