### ISSUE TITLE
Run with debugger is slow on large projects

### ISSUE THREAD

**Issue by britzl** [defold/defold#3380]
Description: Run with debugger for a large game makes the startup time really really long.

I've done a little bit of testing regarding this issue. Delaying the code responsible for running the modbdebugger script to just before initializing the gameobjects did not yield any visible speedup. Delaying the attachment to first frame step did yield a significant speedup, but obviously doesn't break on init calls. A quick glance in instruments hinted that it's very lua heavy during the startup phase, which kinda makes sense.

The mobdebug script basically looks at every lua line being run to check wether it's a function call or a line and wether or not a breakpoint exists in the internal breakpoint tables for that specific line etc. In the presto case, around a half million calls into the debug hook is run which I guess would be somewhat responsible of the slowdown.. I don't really have a quick solution for this at the moment, but it might be worth to look more in detail of how the mobdebug script operates and maybe modify it to do more selective processing based on breakpoints, or maybe cache some of the work between runs.

**Comment by dri-richard** [comment]
I was just about to submit an issue for a similar-sounding problem but found this - perhaps you could advise on whether this has the same cause. I'll submit a new issue if not.

Our game's save function has quite a naive function that iterates over every tile, and builds a table containing data that requires saving. Normally this function executes very quickly, but on my development PC with the debugger attached, it takes about 3 seconds. Detaching the debugger removes the pause. This becomes problematic if I want auto-save active.

I've reproduced the behaviour in a simple script:
```
local function get_grid_key(tile_id)
	return tile_id.x .. ":" .. tile_id.y
end

local function do_array_loop()
	local out_data = {}
	
	for ix = 0, 100 do
		for iy = 0, 100 do
			local tile_id = vmath.vector3(ix, iy, 0)
			local grid_id = get_grid_key(tile_id)
			out_data[grid_id] = {}
		end
	end
end

function init(self)
	timer.delay(5, true, do_array_loop)
end
```

**Comment by britzl** [comment]
> I was just about to submit an issue for a similar-sounding problem but found this - perhaps you could advise on whether this has the same cause. I'll submit a new issue if not.

Yes this is the same issue. Running the debugger over a large number of lines of code will have a significant impact on code execution times.

As I wrote on the forum (or was it Discord) it should be possible to add mobdebug.off() before hitting the save function and mobdebug.on() again once done.

Side-note: I'd also look at the save game code and see if there's room for optimizations. Not only for the sake of running the debugger, but also to reduce the number of table creations which are slow and generate garbage if only used for a short time. Also to reduce memory fragmentation and hitches in the game as the memory is collected again.

**Comment by AGulev** [comment]
Why it's faster when run it using Visual Studio Code?

**Comment by britzl** [comment]
Investigate if it is possible to add a "Debug from First Frame" or "Debug after Init"

**Comment by AGulev** [comment]
At the moment I see that we have
```
local HOOKMASK = "lcr"
```

which means we hoo every Lua line/call/return which is extremely expensive.

But we can modify this behaviour by adding one more layer where we listen only Lua calls 
```
local  OUR_HOOKMASK = "c"
debug.sethook(lightweight_hook, OUR_HOOKMASK)
```
and in this hook we check if we are interested in current function call or not using 
```
local s = debug.getinfo(2,"SL")
--[[
{ --[[0x1121ed0a0]]
  short_src = "main/profiler.script",
  source = "@main/profiler.script",
  linedefined = 10,
  lastlinedefined = 15,
  what = "Lua",
  activelines = { --[[0x1121e4000]]
    11 = true,
    13 = true,
    14 = true,
    12 = true
  }
},
]]--
```

Using this info we will be able to check if we have a breakpoint on one of these lines. If so we set the default mobdebug hook:
```
debug.sethook(debug_hook, HOOKMASK)
```

and work the same way as mobdebug works until developer continue program execution. In this case we override hooks with our lightweight hook again:
```
debug.sethook(nil, HOOKMASK)
debug.sethook(our_ lightweight_hook, OUR_HOOKMASK)
```
