### ISSUE TITLE
Need alternative way to get CPU usage on Android 8+ devices (DEF-3497)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3385]
The `profiler.get_cpu_usage()` function is not working on Android 8 and above. Since Android 8 apps don't have permission to read `/proc/stat`. We need to figure out an alternative way to get the CPU usage for newer Android devices.

**Comment by AGulev** [comment]
https://developer.android.com/reference/android/os/HardwarePropertiesManager#getCpuUsages()
