### ISSUE TITLE
gui.pick_node() improvement (DEF-3480)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3394]
Description: The ability to use gui.pick_node() and return false if the node or ancestor node is disabled.

Either something like:

gui.pick_node(node, x, y, ignore_disabled)

or

gui.pick_enabled_node(node, x, y)

Discussed here: (LINK REMOVED)

**Comment by defoldino** [comment]
Context:
https://defold.com/ref/gui/#gui.is_enabled:node-[recursive]
https://github.com/defold/defold/issues/5887
