### ISSUE TITLE
Investigate custom vertex format (DEF-3447)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3403]
*Material vertex stream declaration*
 * Ability to configure what data and in what format should be pushed from the rendering pipeline to the shaders
 * Essentially defined Vertex Declarations - see how we define buffers for native extensions.

 * Should be defined per material (possibly shared resource definition file)
 * Should play well with Native Extension buffers (design, design..)
 * DEF-1053, DEF-1799 is one example of many use cases
 * Christian has ideas on this and will do a first pass of design suggestion

**Comment by AGulev** [comment]
related https://github.com/defold/defold/issues/3404

**Comment by AGulev** [comment]
related https://github.com/defold/defold/issues/5393

**Comment by britzl** [comment]
We need an investigation first!

**Comment by AGulev** [comment]
As I understand, this investigation is done and the next step is estimating the following task https://github.com/defold/defold/issues/7427 ?

**Comment by Jhonnyg** [comment]
Yes, I’m closing this issue now. We know what we want and how to do it
