### ISSUE TITLE
Geometry instancing for models (DEF-3446)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3405]
* *Geometry instancing for models* (low priority, see as an extension VBO implementation)

 * Fredriks suggestions for ES2.0 is pretty much what is done on the solutions Ive seen possible for ES2.0 but really seem a stretch / specific for Defold
 * We should use [EXT_draw_instanced|(LINK REMOVED) * Supported by all iPhones (we support)
 * Not investigated Android support (but likely well supported Id think?)
 * Core OpenGL from 3.1 (otherwise well supported extension)
 * More info [here|(LINK REMOVED) * Useful for trees, grass, rocks, general vegetation, buildings etc.

**Comment by AGulev** [comment]
Closed in favour of https://github.com/defold/defold/issues/4818
(some conversations started there)
