### ISSUE TITLE
Render order issue among gui nodes when one node has transparency (DEF-3428)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3414]
Expected behaviour
Re-ordering gui nodes should change the rendering order.

Actual behaviour
I have 2 gui nodes in the same container, one with alpha == 1 and the other with alpha < 1. No matter how I re-order them, the transparent node always renders in front of the other node. They can be made to behave using layers, but it feels that this should not be necessary.

Steps to reproduce
Makes 2 gui boxes, without textures, one with alpha < 1.

(LINK REMOVED)

**Comment by AGulev** [comment]
I can't reproduce this old issue

https://github.com/defold/defold/assets/2209596/7c4348b4-979f-47fc-aa5c-9c157c16d148
