### ISSUE TITLE
"add alpha" blend mode for particles (DEF-1570)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3418]
"add alpha" blend mode for particles would be useful in bright scenes.

Contact Sebastien Bellanger or Robin Brook for more details.

2016-01-20 10:04:27 (robin.brook)
example of "add alpha" or "blend add"

**Comment by AGulev** [comment]
hmm 
<img width="224" alt="image" src="https://user-images.githubusercontent.com/2209596/143675124-f7149119-890c-4b18-8086-a40deebb7c25.png">

**Comment by britzl** [comment]
Let's close this one!
