### ISSUE TITLE
Add ability to remove rig runtime with appmanifest (DEF-3420)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3423]
From ed2 issues: (LINK REMOVED)It should be possible to remove spine/model/rig systems via appmanifest. This issue is to investigate this and perhaps add a `rig_null` stub implementation to the SDK.

**Comment by britzl** [comment]
Spine moved to an extension.

**Comment by AGulev** [comment]
related to https://github.com/defold/defold/issues/6607
