### ISSUE TITLE
Variable DT does not work on high frame rates (DEF-3337)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3441]
Description:
There are a multitude of problems related to vertical sync on PC.
This specific lira only relates to how we calculate frame time.

In DEF-3146 we reverted from QueryPerformanceCounter since that returns irregular results and is not reliable across threads, but in doing so the resolution of the timer dropped so bad that it does not calculate "dt" when the frame rate is high (vsync is off).

We probably need to use QueryPerformaceCounter specifically in the main loop to get enough precision but if we are to do that we need to pin the thread to a specific thread.

(LINK REMOVED)

**Comment by britzl** [comment]
Let's broaden this and see if we can find a better solution for vsync issues on non-60hz screens

**Comment by britzl** [comment]
https://forum.defold.com/t/animation-speed-is-different-between-android-and-html5/67552/3?u=britzl

**Comment by gianmichelemariani** [comment]
Very much looking forward to this. With a simple sprite animation on a new M1 Pro with Promotion display, when vsync is on, the animation plays at what looks like half the speed. If I send the app to fullscreen and then back to windowed mode then it plays back at the speed I expect. 
With vsync off everything seems to be playing fine.
