### ISSUE TITLE
Moving window from/to retina display doesn't send window_resized message (DEF-2843)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3448]
Description:
When moving the window between a retina display and a non-retina display on os x it doesn't signal the game with a window_resized message, which can result in rendering/position bugs.

Steps to reproduce:
Enable high dpi in game.project
add print on render script window_resized message
move window between retina and non retina screen

Expected result:
window_resized message sent to render script, containing the new resolution

Actual result:
Nothing.

**Comment by AGulev** [comment]
related issue https://github.com/defold/defold/issues/3449

**Comment by dri-richard** [comment]
This seems to occur even without High DPI enabled, e.g. in the defold-input example

**Comment by dri-richard** [comment]
Will [migrating to GLFW3](https://github.com/defold/defold/issues/7970) possibly address this?

**Comment by britzl** [comment]
> Will [migrating to GLFW3](https://github.com/defold/defold/issues/7970) possibly address this?

Not sure, but GLFW3 brings with it a lot of changes so it is not unlikely that it will help!
