### ISSUE TITLE
HiDPI + moving window between screens can act up (DEF-2819)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3449]
Forum:
(LINK REMOVED)It seems that when bundling with the HiDPI setting, moving from a high dpi screen to a low dpi screen, it will reset the backbuffer to some weird size.

Unconfirmed on Win/Linux

2017-10-13 06:37:45 (Bjorn.Ritzl)
Related to DEF-2843

**Comment by AGulev** [comment]
duplicate of https://github.com/defold/defold/issues/3448
