### ISSUE TITLE
Add ability to add shader constants to gui + particlefx (DEF-3065)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3455]
It's currently not possible to set the gui or particlefx shader constants.

The issue is also complicated by the fact that we have a "go.set()" but no "gui.set()" functionality since it implies we can address sub components (i.e. the gui nodes). A gui scene also contains other nodes, such as particle effects, and fonts.

A fast way our might be to add gui.set_constant() which might check if the node is a particlefx node or not, and apply the material property accordingly

Forum:
(LINK REMOVED)

**Comment by Jhonnyg** [comment]
Closing in favor of https://github.com/defold/defold/issues/9005
