### ISSUE TITLE
Add ability to change collision object group and mask at run-time (DEF-2777)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3459]
Description:
It should be possible to change collision object group and mask at run-time.

Use case:
Sometimes it might be easier to change the group and/or mask at run-time than having multiple objects and enabling/disabling them based on current needs.

Business need:
Request on the forum. (LINK REMOVED)

**Comment by britzl** [comment]
https://forum.defold.com/t/2d-physics-requests/65662

**Comment by otsakir** [comment]
About the interface, access the new mask and group properties like we do for linear_velocity. 

For example: 
```
local mask = "walls"
go.set("body1#collisionobject","mask", mask)
assert( "walls" == go.get("body1#collisionobject", "mask")
```
Same for `group`.

Anything else i'm missing @britzl , @JCash ?

**Comment by britzl** [comment]
I'd like to weigh the pro's and con's of generic go.set/get vs dedicated physics.get_group/set_group etc.

The dedicated and specific functions expands the API but also is a bit easier to search for in an API reference for instance. I do not have a strong opinion here, but I'd still like for us to at least consider physics.get_group() and physics.get_mask().

**Comment by otsakir** [comment]
My two cents on the topic...

* physics.* API tends to have physics related and not necessary property-like methods.  77% of the methods (raycast, joint, gravity) may involve operations that deal with collisionobjects but it's not a get/set thing.
* generic api on 'go' already implements other properties like linear_dumping, angular_dumping, linear_dumping that in terms of UI are together with `group`, `mask`. So it makes sense to try to modify them using the generic 'go' property api.
* `mask` and `group` _are_ properties of the collisionobject and we're actually taking about getter/setter functionality. 

So, it seems to me that `go` api is a better fit according to existing conventions. On the other hand, a dedicated api works better inside the editor  with auto-completing methods etc.

**Comment by britzl** [comment]
> So, it seems to me that `go` api is a better fit according to existing conventions

Great analysis! I agree with you. Changing mask or groups at runtime is not going to be a very common operation so it makes sense to have it as go properties as opposed to dedicated functions!

**Comment by otsakir** [comment]
Quoting from discussion on discord:

> 
> Still looking into #3459 (change collision mask/group on the fly), the 3D aspect of it... 
> So, it seems that changing these properties directly is not the ordinary way to do things in bullet. See 
> https://pybullet.org/Bullet/phpBB3/viewtopic.php?t=8464 
> According to Coumans (current maintainer) it's better to remove the object from the world and re-insert it. 
> 
> Theoretically, the easiest way to do this is disable the co component, update mask/group in CollisionObject3D wrapper structure and re-enable it.  I see two ways of doing this:
> 
> 1. Let the user disable through msg.post("body#co", disable). Implement mask/group 3D getters/setters so that they only update the properties in CollisionObject3D, and let the user re-enable the collision object. In terms of Lua that would be sth like:
> 
> msg.post("body#co", "disable")
> physics.set_mask("body#co", "walls", true)
> msg.post(body#co", "enable")
> 
> 
> I don't expect this to work because msg.post() are async and physics.set_mask() is sync as far as i understand.
> 
> 2. Wrap disabling/enagling the co inside the implementation of mark/group getters/setters. For example, for SetMask3D():
> 
> SetEnabled3D(HWorld3D world, HCollisionObject3D collision_object, false);
> ((CollisionObject3D*)collision_object) -> m_CollisionMask = ...
> SetEnabled3D(HWorld3D world, HCollisionObject3D collision_object, false);
> 
> 
> In this case there is some sort of state of the collision object that we will loose. At least linear_velocity and angular_velocity are explicitly cleared in the process. Are we ok with this in terms of UX?
> 
> There is a third options, without touching the component's 'enabled' status:
> 
> 3. Utilize directly the bullet api for removing/re-adding  the collision object   in the 3dworld. That's a little  lower level stuff and may have some complication like re-implementing stuff like https://github.com/defold/defold/blob/dev/engine/physics/src/physics/physics_3d.cpp#L954 but also seems possible.

**Comment by otsakir** [comment]
Created test project. Two objects, zero gravity, one is thrown to the other. On the way, mask/groups were set on the fly and the collision result observed. For different scenarios switched between 2d/3d modes to verity that both backends work. 

Everything seems to work as expected.

[no-gravity.zip](https://github.com/defold/defold/files/7379022/no-gravity.zip)
