### ISSUE TITLE
Hot reload of label (file) doesn't work (DEF-2897)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3467]
Description:

Hot reload of .label file seems to print random memory contents instead of the newly specified text.

**Steps to reproduce:**

Create foo.label, add to game object in main collection. Build/launch. Edit foo.label text, Reload Resource.

**Expected result:**

The text is updated appropriately.

**Actual result:**

The text is not updated

**Comment by britzl** [comment]
I'm not able to reproduce any random label content, but the label actually doesn't reload in the running app (macOS).

**Comment by britzl** [comment]
I see the label text update if I make some other change to the collection and then reload.

**Comment by AGulev** [comment]
I think it's about updating label component as a separate file (not embedded into collection), but I'm not sure

**Comment by britzl** [comment]
Yes, exactly the reason. You can hot reload a label component that is added in-line to a game object.
