### ISSUE TITLE
Scaled label is offset when building (DEF-2694)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3472]
Description:
The position in the editor does not correspond to the position in the game.

Steps to reproduce:
* Create a new project.
* In the main collection, create a new game object.
* Set its position to 640, 340.
* Set its rotation to 45 degrees around Z.
* Add a label component to your game object.
* Set its position to 100, 100.
* Set its rotation to 45 degrees around Z.
* Set its scale to 10, 20, 1.
* Build and run the game.

Expected result:
The position of the label appears in the same position as in the editor.

Actual result:
The position of the label is wrong.

**Comment by AGulev** [comment]
Do we have a repo-case? Isn't it  https://github.com/defold/defold/issues/3315 ?

**Comment by britzl** [comment]
Indeed it is! I verified that this is now working.
