### ISSUE TITLE
Flipbook animation "moves" relative to the sprite position (DEF-3166)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3482]
Setup:
War battles tutorial (720x720 resolution)
Sprites.atlas should contain the player-down and rocket animations (see attached picture)
Place character in the middle (360,360)
Fire a rocket (with no motion, i.e. it stays in place)
Watch the rocket "move" when flipbook switches frames
2018-03-08 09:15:22 (M.Westerdahl)
The two small screenshot show the (unmoving) rocket have its pixels show up slightly offset from each other (see the nose of the rocket relative to the character)

We suspect it to be UV related, since if you make the player-down animation only one image, all the rocket images will be rotated the same way in the atlas, and the problem goes away.

**Comment by AGulev** [comment]
can't reproduce
[War battles tutorial.zip](https://github.com/defold/defold/files/14541864/War.battles.tutorial.zip)
