### ISSUE TITLE
Distance field font smoothing doesn't respect view and projection scaling (DEF-2963)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3485]
Currently the font smoothing is based on world xy scaling, which is problematic when placing labels in a 3D world. If they are billboarded to face the camera the smoothing will be incorrect when the camera spins around the the xy-plane scale becomes small.

So it needs to account for the view transform, which should be fairly easy.

Similar problem is that if the smoothing scale doesn't account for a different projection. It just assumes that one world unit is onepixel on screen. But using an orthographic projection with a different size than the game project size or using a perspective camera, where scale also is influenced by the depth of the text, will cause the smoothing to be incorrect.

The projection scaling may be better to handle in the vertex shader, so it can be scaled per vertex and handle text at an angle to the camera.

The view transform needs to be applied when calculating the smoothing on the cpu.

**Comment by AGulev** [comment]
related https://github.com/defold/editor2-issues/issues/1834

forum topic:
https://forum.defold.com/t/what-to-do-about-scaled-down-df-fonts-losing-color/13808/5?u=agulev

**Comment by Sublustris** [comment]
It seems that i have same problem.  DF fonts, are always blurry (and even semitransparent in thin fonts). So, i cant use them in real projects.
It looks like this: (at the right is a DF Font, at left - Bitmap font) Both font dont use scaling.

![Снимок](https://user-images.githubusercontent.com/43444545/121858449-add7d380-cd07-11eb-8637-790a0810f030.PNG)

font settings:
![Снимок](https://user-images.githubusercontent.com/43444545/121858624-dd86db80-cd07-11eb-99e9-682e6a728cdd.PNG)

**Comment by AGulev** [comment]
merged with https://github.com/defold/defold/issues/5876
