### ISSUE TITLE
Windows installer (DEF-1424)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3495]
**Problem**:

The current download is a zip containing all the files for Defold. We've seen examples where users managed to copy only parts of the package to their "Program Files" dir on windows.

**Solution**:

Create a Windows installer.

**Comment by britzl** [comment]
Wix seems to be a reasonable open source MSI installer solution.

**Comment by britzl** [comment]
After spending some time investigating different options I've come to the conclusion that it will take a fair amount of time to create a solution that integrates with our CI and generates an MSI for Defold Windows builds.

We will not pursue this further until there is a large demand for this among our Windows users.

**Comment by subsoap** [comment]
I feel that many users will be mostly happy to use the Steam version if they want an installer.

**Comment by britzl** [comment]
> I feel that many users will be mostly happy to use the Steam version if they want an installer.

True!

**Comment by britzl** [comment]
> We will not pursue this further until there is a large demand for this among our Windows users.

Closing
