### ISSUE TITLE
Refactor collection and gameobject factory loading and creation (DEF-2808)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3530]
* Split loading and creation to separate functions and move those into component space as engine is designed otherwise. That is, let the resource scope (res_collectionfactory / res_factory) handle loading of the resources and component scope handle (comp_collectionfactory, comp_factory) handle creation etc.
 * Note that code for loading and creation is duplicated in some places:
 ** *CollectionSpawnFromDescInternal*

 ** *ResCollectionCreate*

 * This is a (likely) post-task to ability to dynamically load/unload resources for a specific factory (DEF-2760)
2017-07-07 10:22:50 (andreas.tadic)
Preferably done after DEF-2760

**Comment by AGulev** [comment]
>This is a (likely) post-task to ability to dynamically load/unload resources for a specific factory (DEF-2760)
2017-07-07 10:22:50 (andreas.tadic)

Hmmm, but we already have "Load dynamically" option for Factories...

**Comment by britzl** [comment]
Yeah, it's a really old issue. I wonder if it's still relevant at all?

@JCash ?

**Comment by JCash** [comment]
Currently, I'm not sure what this is referring to.
I think we'll create a new ticket if something comes up.
