### ISSUE TITLE
Skeleton transforms not same as in Maya when exported with OpenCollada (DEF-3106)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3531]
From Strangequest.

Some Maya files exported with opencollada from Maya will not behave as expected when imported in Defold.
2018-03-29 18:53:15 (sven.andersson)
Confirmed with Strangequest that the suggested workaround* worked for them.

* Add at least one keyframe for all bones. This makes them all appear in the "posed" position.

**Comment by AGulev** [comment]
we are not going to improve collada importeg. Use gltf/glb instead
