### ISSUE TITLE
Load engine JS file as resource on HTML5 (DEF-1934)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3534]
BBS believe they are having problems with a CORS bug in WebKit; (LINK REMOVED)In King Bling this is circumvented by downloading (and executing) a JS file through an ajax request.

We should maybe explore something similar in our HTML5 template, or directly in dmloader.js.

A bonus would be if we could do this in the same step where we load game archives, thus including engine download in the progressbar.
2016-06-20 15:29:42 (Fredrik.Malmer)
Solution we did in the defold canvas wrapper:

{code}
<head>
...
<script>
function load_engine() {
	var head = document.getElementsByTagName("head")[0];
	var script = document.createElement("script");
	script.type = "text/javascript";
	script.crossOrigin = "anonymous";
	script.src = "<%= defoldEngineScript %>";
	head.appendChild(script);
}
load_engine();
</script>
{code}

**Comment by aglitchman** [comment]
Fixed in #5211?

**Comment by britzl** [comment]
Yep, thanks!
