### ISSUE TITLE
Add support for symlinks inside frameworks for iOS (DEF-3263)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3536]
https://github.com/defold/editor2-issues/issues/1693

**Comment by britzl** [comment]
It doesn't look like this is a thing anymore. I tried building a project with a dependency on AppsFlyer using the new extender with Cocoapods support and the project built without any issues. Also, if you look at later versions of AppsFlyerFramework it doesn't look like there are any symlinks:

https://github.com/AppsFlyerSDK/AppsFlyerFramework/tree/master/AppsFlyerLib.xcframework/ios-arm64_armv7/AppsFlyerLib.framework

**Comment by AGulev** [comment]
@britzl it seems like appsflyer doesn't have symlink in their framework anymore
so, it's ok to close it anyways
