### ISSUE TITLE
Add support for regular javascript files in Native Extensions (DEF-2816)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3537]
If you just wish to bundle regular javascript files with the engine, there's the option "--pre-js" that Emscripten uses. Unity supports this by picking up files with the suffix: .jspre

(LINK REMOVED)--pre-js
https://kripken.github.io/emscripten-site/docs/tools_reference/emcc.html

**Comment by britzl** [comment]
What is the use case for this @AGulev ?

**Comment by AGulev** [comment]
@britzl I don't remember to be honest.

**Comment by britzl** [comment]
Closing.
