### ISSUE TITLE
Only color buffer can be used as texture from render target (DEF-2699)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3547]
Description:
We only support color buffer as texture (graphics_opengl.cpp#GetRenderTargetTexture), probably because it's the only one represented as a Texture (the others are uint buffer handles). The calling code is render_script.cpp#RenderScript_EnableTexture

Steps to reproduce:
(LINK REMOVED)

**Comment by subsoap** [comment]
This is needed for SSAO (depth buffer)
