### ISSUE TITLE
Translate world position to local coordinate space (DEF-3173)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3561]
From meeting with Presto:

It would be quite useful to have a go.* function that takes a world position and a game object and returns the specified position translated to the coordinate system of the provided game object.

Useful when animating a parented game object to the position of another game object.

**Comment by ekharkunov** [comment]
@britzl Is it any design document needed here? Or I can try to implement task without it?

**Comment by ekharkunov** [comment]
@britzl Kind reminder =)

**Comment by britzl** [comment]
Sorry for the delay. We have talked about it a bit internally. It is a relatively old feature request and we are uncertain how much use this kind of functionality will get.



> @britzl Is it any design document needed here? Or I can try to implement task without it?

I don't think we need a design document, but I think it is good if we at least discuss how it will work before you start. What is the function name? What are the arguments?

There might also be some overlap in functionality with `go.set_parent()` when `keep_world_transform` is true?

**Comment by ekharkunov** [comment]
Some thoughts after investigation:
1. There are transform matrix: world transform and instance transform.
2. When we call `set_parent` we update either instance transform (if keep_world_transform) or world transform https://github.com/defold/defold/blob/dev/engine/gameobject/src/gameobject/gameobject.cpp#L2246-L2276
3. To implement necessary functionality we need to use world transform (if I understood correctly)

Function name and arguments:
`go.to_local_position(url, world_position)`
where
`url` - `string, hash, url` - url of the game object instance which coordinate system we want to translate to
`world_position` - `vector3` - world position which we want to translate to game object coordinate system
Returns:
`vector3` - translated position


How it should be implemented:
1. Standard check for go instance existence
2. Get instance world transform
3. Use passed vector3 and world transform for calculation.
4. Return calculated position.

**Comment by AGulev** [comment]
It sounds good for me, we have something similar for GUI with https://defold.com/ref/stable/gui/#gui.screen_to_local:node-screen_position

**Comment by AGulev** [comment]
@matgis also suggested having something like `go.to_local_matrix(url, world_matrix)` to be able to convert rotation and scale as well

**Comment by AGulev** [comment]
I think for now it would be enough to go with 
```
go.world_to_local_position() -- most frequently used
go.world_to_local_transform() -- maybe used for getting scale and rotation with some exceptions, but still
```
