### ISSUE TITLE
Get and set absolute gui node position (DEF-3168)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3563]
From discussions with the Presto team:

There should be a gui.get_absolute_position() and gui.set_absolute_position() that gives and sets the nodes position relative to the root of the gui scene. This can be achieved already by working your way up the hierarchy through gui.get_parent() and accumulating positions, but it makes sense for the engine to provide this functionality.

**Comment by AGulev** [comment]
isn't it `gui.get/set_screen_position`?

**Comment by britzl** [comment]
Yes indeed!
