### ISSUE TITLE
Make libraries from each component (DEF-3113)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3574]
In order to be able to strip more unused code from the engine, we need to make each component a separate library.

e.g. libcomp_collection_proxy.a could contain:
    comp_collection_proxy.cpp
    res_collection_proxy.cpp
    script_collection_proxy.cpp

The scripts could be split out as well at a later stage for an even finer granularity.

**Comment by britzl** [comment]
What exactly would we be able to strip out from the engine with this change @JCash ?

**Comment by JCash** [comment]
We could strip out any unused component/resource/script type.
We'll do it on a case by case basis.
