### ISSUE TITLE
Allowing raising GUI limit above 1024 (DEF-3015)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3587]
From forums; (LINK REMOVED)And Github issue; (LINK REMOVED)Investigate if it is possible to increase the limit.

**Comment by d954mas** [comment]
For some complex ui. Like minimaps 1024 is too small value.

**Comment by dmi7ry** [comment]
Any news?

**Comment by britzl** [comment]
@dmi7ry no news yet I'm afraid.The issue has quite a few votes so it is likely to end up in the roadmap for 2021 though.
