### ISSUE TITLE
Split out more sub libraries from engine (DEF-3000)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3594]
In order to easier replace older functionality, we need to look into "libifying" some of our sub systems. Or at least rename the symbols so that they won't collide "outside"

E.g.:

axtls + SSDP > libHttp
lib crypto funcs > libcrypto
lib stb_image > libstbimage ?

etc

**Comment by JCash** [comment]
For inherently internal code that may collide with outside code, we will namespace the code.
It's not very convenient, but it will get the job done. (We've already done this with a few libraries)

**Comment by AGulev** [comment]
I'm closing it in favor of https://github.com/defold/defold/issues/6607 (we have more examples and measurements there)
