### ISSUE TITLE
Implement: Animation clip support (DEF-2251)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3600]
Support for animation clips. For Collada, see reference:
Section 5-14, animation_clip
(LINK REMOVED)Note that we have so far implemented the actual import of the animation clip data and we have support for it throughout the pipeline.
What is needed is for the actual sampling to be done and create separate anims within an animset.

2017-11-13 11:39:18 (Fredrik.Malmer)
How it looks in our sample export (OpenCOLLADA Maya plugin):

{code:xml}
<library_animation_clips>
    <animation_clip id="flower_open_to_active" start="0.04166667" end="2.375">
      <instance_animation url="#joint_root_l_pin.translateX__joint_root_l_pin-flower_open_to_activeSource"/>
      <instance_animation url="#joint_root_l_pin.translateY__joint_root_l_pin-flower_open_to_activeSource"/>
      <instance_animation url="#joint_root_l_pin.translateZ__joint_root_l_pin-flower_open_to_activeSource"/>
      ...
{code}

**Comment by AGulev** [comment]
it feels like it's something we are not going to support for collada
@britzl what do you think?

**Comment by britzl** [comment]
Closing it!
