### ISSUE TITLE
Ability to set frame ranges in animation sets for models (DEF-2990)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3602]
If you could set frame ranges on animation set entries (which need to be nameable DEF-2903) you could store many animations in the same file, not having to make many exports of the same content with different frame ranges in the file.

Would simplify the export-import pipeline a lot. Would also improve the support for 3d software that don't support the frame range tags.

**Comment by AGulev** [comment]
Now gltf supports a few animations in the same model. Can we consider this task is done? @britzl

**Comment by britzl** [comment]
Yes!
