### ISSUE TITLE
Create DM_DECLARE_RESOURCE_PROVIDER macro (DEF-2974)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3604]
We can clean up a lot of code, and also remove it, from the resource.cpp, if we modularize the file providers in a similar fashion to DM_DECLARE_EXTENSION.
In particular, the HTTP file provider is unnecessary on HTML5 and that's a fair amount of code to remove from that platform.

Goals:
* smaller build size for HTML5
* cleaner code in the resource.cpp

**Comment by britzl** [comment]
How does this relate to the work we did on resource extensions? @JCash ?

**Comment by JCash** [comment]
In my recent work on the resource system for the LiveUpdate, I think this should be done as a regular mount implementation.
I'm not sure what needs to be done, but to me it feels like it should be fairly straightforward to move it into a separate library to make it easy to exclude.

**Comment by JCash** [comment]
We're currently happy with our resource extension api's.
