### ISSUE TITLE
Create DM_DECLARE_COMPONENT macro (DEF-2973)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3606]
In an effort to reduce build size, and also keep the component code cleaner, we should introduce a new macro that registers the gameobject component in a similar fashion to DM_DECLARE_EXTENSION.

This will allow users that doesn't use models or tilemaps to exclude those libraries.

**Comment by britzl** [comment]
We now have DM_DECLARE_COMPONENT_TYPE.

@JCash what about use of this for existing components? Still planned?

**Comment by AGulev** [comment]
This macro used for gui and spine components. I think the issue may be closed
