### ISSUE TITLE
Set names to model animations in animation set (DEF-2903)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3611]
Currently the animation names used in a model animation set is the name of the file. This makes for terrible scalability, since you can't (in a clean way) use the same code to handle multiple model's playback animations, unless you name all your animation model files the same, but put them in different folders, which in itself doesn't really work.

*What is needed is a way to set the name of animations in the animation set.*

This will also have the benefit of making it possible to easily try out different animations for the same name. Like testing different walk cycles without changing code or renaming a lot of files.

Also makes it possible to use the same animations on several animation names.

2017-10-11 10:36:38 (Sara.Cederberg)
(LINK REMOVED)

**Comment by AGulev** [comment]
outdated
