### ISSUE TITLE
Transform-only gui node (DEF-2864)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3618]
Description:
A gui node that does no rendering, but only does transform. Should still contain color and alpha in order to make children inherit them. But it should not have any texture, size, blendmode, 9-slicing or clipping.

Use case:
To help with building hierarchies in the UI, and you don't want the batch to break because you need to put things in a container.

**Comment by britzl** [comment]
Also gui.new_transform_node()

**Comment by AGulev** [comment]
https://github.com/defold/defold/issues/5816

**Comment by AGulev** [comment]
duplicate
