### ISSUE TITLE
Async sys.load_resource (DEF-2670)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3637]
Description:
Right now we can use `sys.load_resource()` to load resources from the game archive. This blocks the main thread. We would like to have a way to do that in async way and receive a message/callback upon completion.

Use case:
Loading a lot of images in one gui screen at the same time slows down the animations.

Business need:
Better user experience.

**Comment by britzl** [comment]
Add callback for async load: `sys.load_resource(filename, [callback])`

**Comment by Jhonnyg** [comment]
This has been fixed by #8416
