### ISSUE TITLE
DESIGN: Decompress compressed resources by type (DEF-2652)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3646]
Currently, only compressed (zlib) or uncompressed resources are supported by the run-time and build pipeline. We should instead of just "compressed or uncompressed" support type of compression, like WebP or other alternatives so that all decompression of resources use the same codepath and implementation in order to utilise async decompression (when loading collections asynchronously).

**Comment by JCash** [comment]
We support LZ4 for our assets in our archives.
And, while I do think the idea would have been good in the long run, we've just now removed WebP from our engine, and we currently have no need for this feature.
