### ISSUE TITLE
Improve speed of texture packer (DEF-2700)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3652]
The texture packer is slow when many small images are used. Perhaps there are some quick wins that can be applied to the texture packer code to increase the speed?

The texture packer will gradually increase the size of the texture it tries to pack the images within by repeatedly increasing either max width or max height of the texture. The minimum width is also changed, but the minimum height stays the same (16). Perhaps this has a negative impact?

Interactive spreadsheet to show how the min and max values change based on area of images and number of iterations: (LINK REMOVED)

**Comment by AGulev** [comment]
Algorithm 75% faster  in 1.4.5
