### ISSUE TITLE
Name output resources in build to avoid name collisions (DEF-2330)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3663]
Currently you get resource name collisions if you have "test.atlas" and "test.tilesource" in the same folder (generates "test.texturec"), or if you have "hero.model" and "hero.spinemodel" in the same folder (generates "hero.rigscenec").

Suggests adding further information to resource names to:

1. Facilitate debugging (see what file is the source).
2. Avoid name conflicts.

For example:

my_stuff.atlas   ----> my_stuff.atlas.texturec
my_stuff.tilesource ----> my_stuff.tilesource.texturec
2017-01-11 14:17:39 (Sara.Cederberg)
Ragnar: Great point, I think this should be fixed in both Editor1 and Editor2. It should be trivial to fix. In Editor1, we can't just rely on .replaceExt (or whatever the name is), but possibly extend it to include the previous extension when the extension changes. Similar solution for Editor2.

**Comment by AGulev** [comment]
https://forum.defold.com/search?q=Conflicting%20output%20resource

**Comment by AGulev** [comment]
What do you think about this solution? https://github.com/defold/defold/compare/issue-3663-conflicting-output-resource

**Comment by britzl** [comment]
That seems like a nice and simple solution to the problem!
