### ISSUE TITLE
Enable/Disable particle fx component (DEF-2267)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3664]
Description:
The ParticleFX component is one of the few remaining components that cannot be disabled by posting a "disable" message to it. For API consistency and for several use cases it should be possible to do so.

Use case:
Temporarily disabling a game object containing a sprite and particle fx would hide the sprite but not the particle fx which might look weird.
When resetting a level you might wish to disable all game objects and then re-enable them at a later time. If particle fx are left visible it will look weird.

Business need:
No team at King has requested this, but users on our forum:
(LINK REMOVED)
2017-01-11 14:07:31 (Sara.Cederberg)
Needs design, specifically:
* Does disable mean no update and no render? Check with sprite component and running animations, should probably be the same.
* Can you affect a disabled particlefx through messages? Probably yes.

**Comment by paweljarosz** [comment]
I think enable/disable particlefx should stop generating and hide ("remove" visually) all generated particles. So no udpate and no render.
With play and stop messages/functions we can stop generating, but can't remove already generated particles, that will be deleted only after their lifetime is over.

**Comment by subsoap** [comment]
IMO there should be a separate function to clear all ParticleFX, or allow ParticleFX to get group IDs which can then be cleared by group.

**Comment by AGulev** [comment]
@britzl isn't it done by your fix a while ago?

**Comment by AGulev** [comment]
I mean this one https://github.com/defold/defold/pull/6772

**Comment by britzl** [comment]
Closed by #6772
