### ISSUE TITLE
Pivot for sprites (DEF-651)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3666]
* Current workaround is to create an intermediary child game object and use that as a pivot
* Local vec3 translation
* Offsets scaling and rotation
* Dynamic property, get/set/animate
* Should not affect vertex data generation as batched sprite vertex data is still highly dynamic
* Design how the pivot should be edited in the editor needs to be done, things to consider:
  * Manipulator support
  * Visuals in scene view/outline
  * Selectable in the scene view
  * Selectable in the outline

Take in to consideration doing https://github.com/defold/defold/issues/3629 as a sub-task as automatic sprite cropping will need to modify the pivot (invisible to the user).

**Comment by Dragosha** [comment]
Also sprite's pivot needs in case when we want to use sprites in 2.5D persprective scene. Becase the engine makes render order (in view matrix) based on one point in sprite center. In game like zelda and other engines for this case used sprite pivot seted to the sprite bottom.
Video for example. Left the tree and the stone are sprites, the right tree is a mesh quad with shifted vertecies (a pivot in bottom of quad).
https://user-images.githubusercontent.com/842807/177780855-04a7f9d3-ef1e-43e3-8a33-e5280e4cddaf.mp4

or very simple example:
https://user-images.githubusercontent.com/842807/177784335-379630c0-90c3-40ca-8131-5f0424c67a16.mp4
If we could set a pivot to the floor sprite, it would solve the problem of sorting objects in the renderer.

---
Beyond that the sprite pivot (for example setted in atlas) is useful for setup a game object that changing his conent in runtime. Dress uping of doll where each sprite should has point to attach in right place. It's another case.

**Comment by AGulev** [comment]
related https://github.com/defold/defold/issues/5172

**Comment by rigo128** [comment]
Use case: skin system. If I want to change weapon sprites dynamically, I need to have all sprites with the same pivot point.
![ingameWeapon_knife_5](https://github.com/defold/defold/assets/851731/1153e398-9bf0-4e09-8b5c-7e9d03c01009)
![ingameWeapon_knife_6](https://github.com/defold/defold/assets/851731/15da0a8f-e892-49d5-9b0c-f1b974d2c3fb)

**Comment by JCash** [comment]
In our latest design meeting, we decided to adopt the approach of setting a pivot for an image in the atlas:
* TexturePacker already supports pivots (we need to add it to our exporter)
* A default value would be the middle of the image (e.g. Pivot=(64x64) for an image of size 128x128)
* The pivot is offset only, and should be easy to apply for each case (sprite or gui)
* Any render batch sorting would still be done using the sprite position.

**Comment by Dragosha** [comment]
Overall the solution looks good. But I wonder how to edit the pivot in the editor, just as 2 new fields x-offset, y-offset in sprite properties? I would like to see some visual marker on the sprite in the atlas. If it could be moved visually that would be totally cool, but just showing the pivot depending on the offset coordinates is nice too.

**Comment by rigo128** [comment]
Use case: pivots for particles.

**Comment by britzl** [comment]
> Use case: pivots for particles.

This feature request is for sprites only. Pivot for particles should be a separate request.
