### ISSUE TITLE
gui.set_texture() is not enough to set (most) textures (DEF-2206)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3673]
In the common case, an atlas is bound as texture to a gui scene. To set a specific image to a gui node, the user has to do the following:

In editor: Select "atlas/image" in the dropdown.

In script:

gui.set_texture(node, "atlas")
gui.play_flipbook(node, "image")

A nicer interface would be:

gui.set_texture(node, "atlas/image")   ...corresponding to the editor UI.

Note that a dynamic texture *can* be created with a colliding name. That is already possible and may not be a compatibility issue?

**Comment by britzl** [comment]
Possibly `gui.set_texture(node, "atlas", "image")`

**Comment by Jhonnyg** [comment]
Perhaps close this? It doesn't feel relevant
