### ISSUE TITLE
On iOS and Android, launching with client dev application, the project display settings are ignored (DEF-1197)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3681]
On iOS (same issue on Android), launching with client dev application, the project width and height settings are not used since we have hard-coded the app not to change resolution (ios_window.m).
This causes the app to use the wrong resolution if it doesn't happen to be 960x640 or vice versa.
Tested this with prior versions of the engine to confirm, and the problem is there too (of course).
This affects all graphical window settings such as filtering etc.

**Comment by AGulev** [comment]
we don't have client dev application animore
