### ISSUE TITLE
bob should accept keystore files as well as .pem and .pk8 files when bundling Android apps (DEF-1373)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3690]
This is a request from Presto. The FF build pipeline assumes a keystore file, and with that in mind it would be nice to not have to maintain both a keystore file and a .pem and .pk8 file.

As a short term solution the Pyfold build scripts could be made to convert a keystore into a pem and pk8 using the following steps: (LINK REMOVED)

**Comment by AGulev** [comment]
Solved in 1.2.173-1.2.174
