### ISSUE TITLE
When using a tile source as collision shape, then collision group used is unclear (DEF-1012)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3693]
STR:

1. Create a GO with a tile map.
2. Add a collisionobject and set a tile map as shape.

Notice that it is still possible to type a collision group name for the new collisionobject, although the entered value is meaninglessthe groups are instead read from the tile source.

Suggestion: when selecting a shape that provides collision groups, replace the Group widget with a static text reading "Groups defined in Collision Shape" or similar. (A more fancy presentation of all groups that come with the shape would be even nicer.)

Furthermore, the presentation of Tile Sources effectively hides the fact that it shows collision groups in the Outline view. It needs to be much clearer.

**Comment by AGulev** [comment]
fixed by https://github.com/defold/defold/pull/8951
