### ISSUE TITLE
Camera component for orthographic projections (DEF-2987)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3716]
The component should have exposed properties for width and height as a minimum. Features for locking the width/height to the width/height of the screen or to "fit" the aspect ratio on the screen are desirable, but can be achieved by a script component if width and height are exposed.
2018-05-04 10:41:49 (Bjorn.Ritzl)
Reduced prio. We have RenderCam.

**Comment by AGulev** [comment]
isn
t it done by https://github.com/defold/defold/pull/6829 ?

**Comment by britzl** [comment]
Closed by #6829
