### ISSUE TITLE
Camera properties should be properties that are available via go.get/set (DEF-2985)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3718]
All camera properties should be accessible via go.get/set or a new camera module.

Camera properties should be the ones in the ui (fov, etc). but also it should be able to access the view and projection matrices and their inverted versions directly. From any game object and the render script.
2018-05-04 10:43:06 (Bjorn.Ritzl)
Reduced prio. We have RenderCam.

**Comment by AGulev** [comment]
What exactly properties we wanna see for camera? 
<img width="337" alt="image" src="https://user-images.githubusercontent.com/2209596/147886095-16c1cfbf-b9f3-4b7c-95b8-01c9abf0ba50.png">

Is it enough to add these 5 as MVP and then create new tasks for some other properties?

- float `aspect_ratio`
- float `fov`
- float `near_z`
- float `far_z`
- bool `auto_aspect_ratio`

**Comment by britzl** [comment]
> Is it enough to add these 5 as MVP and then create new tasks for some other properties?

Yes I believe it is!

**Comment by AGulev** [comment]
hmm, I din't know about this message https://defold.com/ref/stable/camera/#set_camera

**Comment by britzl** [comment]
Me neither!
