### ISSUE TITLE
Capture mouse position outside of the window (Windows) (DEF-1996)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3749]
Support capturing mouse position even when mouse is outside of the window (Windows).

Should this be a setting?

If appropriate, we could implement events similar to "WM_MOUSELEAVE" + "ENTER" to help users with different window sizes etc.

(LINK REMOVED)

**Comment by AGulev** [comment]
https://github.com/user-attachments/assets/6ce114b3-a7bc-4b84-9f35-473c2e7c8595

isn't it the same on windows?

**Comment by AGulev** [comment]
I've tested. It works the same way on windows as well (1.9.3)
