### ISSUE TITLE
Tile Map cell order in save data is not deterministic (DEF-2884)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3756]
Editor 1 counterpart to DEFEDIT-1135.

Originally reported here:
(LINK REMOVED)Tile map cells are not saved in deterministic order, due to being stored in a HashMap. Possible quick-fix would be to use the ordered TreeMap instead.

**Comment by AGulev** [comment]
Is it for editor 1? it's been fixed for the editor 2
https://github.com/defold/defold/pull/1779
