### ISSUE TITLE
Floating point render targets are clamped in windows (DEF-2943)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3763]
Description:

Fp16 render targets are clamped on Windows. This is because the target shouldprobably not be created with the RGBA internal format but with RGBA16F_EXT as defined in EXT_color_buffer_half_float.

This extension also includes the R16F_EXT format which should be used for luminance render targets, and RG16F_EXT which should be used for luminance+alpha.

This bug prevents us from running the game properly on Windows.

**Comment by abadonna** [comment]
Is it possible to create float render targets in defold now?

**Comment by britzl** [comment]
> Is it possible to create float render targets in defold now?

Not entirely sure to be honest :-) @JCash and @Jhonnyg ?

**Comment by Jhonnyg** [comment]
This doesn't seem relevant any more.
