### ISSUE TITLE
Fetch library will fail if previous library zip is corrupted (DEF-3151)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3764]
*Description:*
From Ed2 issues: (LINK REMOVED)If a library zip download manages to end up corrupted (in {{.internal}}folder), we will fail/throw an exception on the next "library fetch" ({{com.dynamo.bob.Project.resolveLibUrls}}) since we can't read the zip.

We need to handle this better, for example we could log the error, delete the zip and try to redownload it.

**Comment by AGulev** [comment]
close as copy of https://github.com/defold/defold/issues/7933
