### ISSUE TITLE
Add support for iOS launch image "storyboards" (DEF-2995)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3771]
*Description:*
Xcode (and iOS) now support a new way to supply launch images in the format of {{*.storyboard}} files.

Storyboard launch screens can decrease the bundle size by using a single "icon"/image and solid background colors for multiple resolutions/devices.

*Business need:*
Keeping the app bundle size down, by not having static images for different resolutions.
2017-11-13 14:06:44 (sven.andersson)
Did some short investigation, some notes:

- Corona supports compiled storyboards ( (LINK REMOVED)- NativeScript (cross platform app development) also support storyboards)
 (LINK REMOVED)- Xcode comes with a command line tool {{ibtool}} that should be able to "compile" {{.storyboard}} into {{.storyboardc}}, there is also an unofficial Python port; (LINK REMOVED)An initial step for Defold would be to support compiled storyboard files, since this should be a new entry in the {{Info.plist}}. A second step would be for us to support either compiling storyboard files in Bob.jar or through our cloud service.

**Comment by JCash** [comment]
The basic idea here is to simply support adding a prebuilt storyboard to the bundling.
The main reason is that it allows for bundling on non-osx platforms.
Also, the app start is so quick, that a story board with any real content is just going to flicker past, before showing the in game title screen.
