### ISSUE TITLE
Tangent space vectors on sprites and models (DEF-1799)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3772]
In order to do normal mapping we need to have tangent, bitangent and normal vectors for sprites and spines passed to the shader. Otherwise we can't do any rotational movement.

These vectors should probably be transformed with the transpose of the inverse model matrix: ( M ^-1^ ) ^T^

This feature could be combined with adding support for vertex colors and other custom per vertex data. In the end these vectors also needs to be when importing mesh.
2016-04-28 13:48:24 (ingela.garneij)
Need to design how to change the vertex format first
2016-05-30 12:47:42 (ingela.garneij)
Needed before Cohesion playtests (October?)
2016-11-03 11:14:00 (linus.cumselius)
On the topic of normal mapping without tangent space (if that is more likable than adding two more vectors to the vertex format..), see (LINK REMOVED)It is quite possible to recreate tangent space from the slopes in screen space by using ddx, ddy and the surface normal (in screen space of course). You can rotate anything from model space into screen space by using the 3x3 part of the MVP matrix for the current batch (a m33 operation). If you are using tangent space globally, you would instead transform the ddx,ddy vectors into the same space as your surface normal was in (i.e going back from the MVP into MV or simply go directly back into model space using the transposed view+projection matrix or whatever suits your needs).

The actual evaluation of the tangents are done by normalizing the vectors returned from ddx, dyy (after transforming the normalized ddx,ddy vectors into normal vector space) and then using the cross product to get the tangent, then crossing again to get the cotangent, then signing the direction along the normal direction (so the space stays rotationally invariant).

Of course, the tangent space that is generated this way will be somewhat less correct than the one generated from real tangent space vectors from the actual model, because ddx and ddy in screen space work in blocks of 2x2 pixels. This cause blockiness when used on high frequency surfaces (high resolution meshes) but could of course be handled gracefully with a descent "level of detail" (LOD) system in place.
2016-11-04 09:17:30 (linus.cumselius)
After discussion yesterday with [~patrik.nordlander] I said I would think about some solution to the problem you have with not being able to get the correct rotation at each pixel for the normal mapped objects when they are in a single batch.
Well, when using a static normal map on all objects of the same type (without breaking the batch between objects) you would need to calculate each objects individual rotation of the static normal map directly in the fragment shader. This can be done by deducing the direction of the uv direction for each new pixel on the scan line using ddx/ddy (again). You will then have the direction of the rotated uv space in screen space coordinates so you could go to tangent space from there.
2016-11-04 15:46:52 (patrik.nordlander)
We managed to calculate the tangent and bitangent in the fragment shader using dFdx and dFdy, but turns out it's not supported in OpenGL ES 2.0, så we're back on square one.
2017-07-14 15:02:29 (Sara.Cederberg)
from DEF-2764

Fredrik Malmer

Description:
Read tangent space vectors from models and make then available in the vertex shaders. 
There should also be a way to make defold itself generate tangent space vectors.
The vectors should be in the same space as the normal, ie. world-space.

Use case:
Normal mapping and similar effects.

**Comment by Jhonnyg** [comment]
We have support for tangent vectors for models, and if it is needed for sprites we should open a separate ticket.
