### ISSUE TITLE
Bob requires auth and email options even for public repos (DEF-3266)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3779]
You still need to pass in bogus --auth and --email values to the resolve command even though it's a public repo. If auth and email is omitted it will result in a 400 Bad Request.

(LINK REMOVED)
2018-05-02 12:29:49 (Erik.Angelin)
-Related? [(LINK REMOVED)Turns out we could appease bob by just passing email/auth = "" :)

**Comment by britzl** [comment]
Check if email and auth aren't set and then ignore setting the auth headers:

https://github.com/defold/defold/blob/dev/com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/Project.java#L1163-L1166

**Comment by subsoap** [comment]
auth and e-mail can be set in two places right? Does that matter? In the dependency link itself, and when running bob.

```
bob --archive clean resolve build --build-report-html "build-report-${platform}.html" --texture-compression true --variant "release"  --platform "${platform}" -e a@a.com -u fake_token
```

**Comment by britzl** [comment]
When you set it in the URL itself it is parsed as BasicAuth which is treated as a different case in the code: 

https://github.com/defold/defold/blob/dev/com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/Project.java#L1160-L1163

**Comment by britzl** [comment]
Fixed in this commit: https://github.com/defold/defold/commit/9a60fb13d965e7d1fb2bff4ecb0f9b5c18b399c2
