### ISSUE TITLE
gui.pick_node option to allow use of absolute node space coordinates (DEF-2729)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3792]
Description:

gui.pick_node generally scales the values sent to it to account for differences in the scaling of the project window size and the actual window size. This is generally correct, but when a gui scene has the "Adjust reference" set to "Disabled" there is a use case where this should not happen.

If simply picking on the screen it is fine as it is. But one of the big reasons you want to have adjust reference set to disabled is that you want to do something else/special with it. It could be using a different kind of projection. it could be integrating gui in the world with a 3D perspective camera. etc. In those cases you really want to coordinate you pick on to 100% correspond to the actual coordinates of the gui nodes. But if the window is resized this correspondence breaks apart.

Workaround used in blossom 2: We do the inverse of the transformation done by defold prior to passing the values to pick node.

The culprit is this first line in PickNode (gui.cpp):
{code:java}Vector4 scale((float) scene->m_Context->m_PhysicalWidth / (float) scene->m_Context->m_DefaultProjectWidth, (float) scene->m_Context->m_PhysicalHeight / (float) scene->m_Context->m_DefaultProjectHeight, 1, 1);
{code}

Since both the pick on screen scenario and the absolute coordinate scenario are valid use cases it seems like the best approach is maybe to allow passing in an optional argument to the function that disables the coordinate transform, or adding a second pick_node_absolute function.
2017-06-21 15:40:43 (Fredrik.Malmer)
Fix used in blossom 2:

{code}
local p = screen_to_world(action.screen_x, action.screen_y)
p.x = p.x / (window_size.x / project_size.x)
p.y = p.y / (window_size.y / project_size.y)
{code}

**Comment by AGulev** [comment]
outdated
