### ISSUE TITLE
Add support for object animations for models (DEF-2236)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3793]
We currently only support bone animations, but this is mainly a legacy restriction from spine (as far as I know), and we should add support for animating 3D objects/meshes in models.

**Comment by Jhonnyg** [comment]
The description doesn't make any sense to me, what does spine have to do with models?

**Comment by britzl** [comment]
> what does spine have to do with models

Wasn't this because previously Spine and Model shared dmRig or something like that?

**Comment by Jhonnyg** [comment]
Ah right, yeah that might be true. But what exactly does "object animations" mean? 🤔

**Comment by britzl** [comment]
> Ah right, yeah that might be true. But what exactly does "object animations" mean? 🤔

No idea. Let's close this.
