### ISSUE TITLE
Librig model code cleanup  (DEF-2305)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3797]
Description:
* librig should be split into _private.h/cpp as there are a lot of exposed internal structures etc in rig.h
* comp_spine.h and comp_model.h are exposing *modelcomponet and *modelworld which are only used in *model_script to get game object. They should be moved to the cpp file and an interface should be added to deal with the instances they are used in the *model_script file. This could lead to some implementation design as the gamesystem is involved in how the *model component is retreived (see for example LuaModelComp_GetGO).
* librig components (spine, model) should use the new CompRenderConstants interface instead of their own separate implementation of constant set/get/rehash
* The conditional rehash of render constants is executed in the Comp*Update callback for spine and models, but in the CompSpriteUpdate for sprites. Why is this different (the sprite code was implemented before either model or spine!). Investigate what the reason is and unify code-pattern if appropriate.

**Comment by britzl** [comment]
Spine moved to extension.

**Comment by Jhonnyg** [comment]
Too vague, closing.
