### ISSUE TITLE
Platform and Architecture engine naming conventions cleanup (DEF-2294)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3802]
We have confusing naming conventions on platform and/or architecture in the engine. We should clean this up so there is no confusion and we have a good hierarchy of platform and sub-arch's. Example: win32 whereas it's windows, not specifically win32.

We need to go through all supported platforms and architectures and decide on a common conventsion.

**Comment by AGulev** [comment]
I'm closing this task, we can open a new one when we decide what exactly we wanna do
