### ISSUE TITLE
Unify string representation of floats in userdata objects (vector3 etc) (DEF-1169)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3810]
Consider this:

local a = vmath.vector3(0, 0, math.pi)
pprint(a)

DEBUG:SCRIPT: vmath.vector3(0, 0, 3.1415927410126)

And the following:

print("vector is: " .. a)

DEBUG:SCRIPT: vector is: [0.000000, 0.000000, 3.141593]

Notice that the float numbers are printed differently. It would be nice if they were given the same representation in all cases.

**Comment by britzl** [comment]
Something is broken with string concatenation: https://forum.defold.com/t/position-and-vector-values-no-longer-displayed-when-debugging/69751/2

**Comment by sohamroy19** [comment]
Your PR should fix this, I think.
