### ISSUE TITLE
Build report doesn't show uncompressed size for texture assets (DEF-1910)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3814]
Textures compressed using webp will not show their uncompressed size in the size report file, giving them a ratio of 1 in all cases. The uncmpressed size should be the raw size when loaded.

**Comment by JCash** [comment]
Just wanted to note that although we've updated to Basis Universal and also fixed the size representations (compressed, transcoded) in the web profiler, this issue in the report is still there.

**Comment by AGulev** [comment]
is it still true? 
<img width="347" alt="image" src="https://github.com/defold/defold/assets/2209596/07054500-668b-49b0-b73f-e5c027733134">
