### ISSUE TITLE
CLONE - 3D performance: Unbatched indexed drawing of 3D models (DEFEDIT-1279)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3829]
Drawing of models that have indexed buffers that are not batched, and fully processed by the GPU.

*Why?*
* According to our profiling, the CPU and bandwidth cost of processing all the vertices of a high poly model on the CPU and sending a fresh copy to the GPU every frame is orders of magnitude higher than getting a few extra draw calls.
* There are many effects that are next to impossible to do if the vertices arrive to the vertex shader pre-transformed to world space. Sometimes you want them to arrive in object-space, and then transform them yourself to world space, after applying some object space effect.

*Requirements:*
* Apart from just adding support for unbatched indexed drawing itself, the world transform matrix must be passed to the vertex shader, rather than just passing identity as now. It also makes sense to introduce a combined worldviewproj matrix.

* If something is batched or not should be controllable by the programmer. It shouldn't be automatic. Preferably in the material, as well as on individual objects. If both are not possible, then the material setting is preferred.

**Comment by Jhonnyg** [comment]
This isn't needed anymore right?

**Comment by Jhonnyg** [comment]
Yeah I’m killing this.
