### ISSUE TITLE
Delete or anonymise user info in Sentry (DEFEDIT-1280)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3830]
Background:

With the EU laws regarding data protection starting May 25th 2018 we need to remove all user information if a Defold user requests to have his/hers Defold account deleted.

[(LINK REMOVED)Steps taken or to be taken overall within Defold: [(LINK REMOVED)Issue:

The current sentry set up includes paths that can include user information. If a Defold user chooses to delete his/hers account we need to make sure that this information is either deleted or anonymised.

**Comment by AGulev** [comment]
I don't see any user's info in sentry and we don't have accounts anymore (dashboard or anything), should we close it? @britzl

**Comment by britzl** [comment]
> should we close it?

Yes
