### ISSUE TITLE
Unchanged files are saved because data stored in strings is not sanitized (DEFEDIT-1197)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3832]
Includes but probably not limited to:
* The "load_dynamically" property on Factories.
* Vector properties since we now write spaces after comma separators.
2017-10-26 19:30:53 (Mats.Gisselson)
(LINK REMOVED)

**Comment by AGulev** [comment]
@britzl  it seems like the same issue as @matgis is working on? or something already solved?
