### ISSUE TITLE
Add Show Recent Files dialog

### ISSUE THREAD

**Issue by britzl** [defold/defold#3855]
Suggested by King employee at induction in Stockholm, April 2019.

like IDEA ctrl/command+E

!Screenshot 2019-04-12 at 07.31.41.png!

**Comment by AGulev** [comment]
<img width="670" alt="image" src="https://user-images.githubusercontent.com/2209596/187922882-5bc20fef-7b7a-4ea8-b513-c31ce84638b4.png">

**Comment by britzl** [comment]
Also: Reopen the most recently closed file
