### ISSUE TITLE
Clojure data visualisation (DEFEDIT-1562)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3877]
I have wanted a good tool for visually exploring Clojure data structures several times now when developing and debugging. I searched the internets but to no avail. There is but one tool - REBL, which I don't particularly like. The result display capabilities of ProtoREPL look nice but are Atom only. I want something that is not tied to any one editor.

Perhaps make one ourselves? Could use [~vladislav.protsenko]s [(LINK REMOVED)
2019-02-20 15:18:47 (vladislav.protsenko)
I've thought about this tool for a few months, by the way, here are some ideas I've collected so far. Didn't try to estimate if any of those ideas are good or bad for such tool though, so it's more of a kitchen sink:

Clojure repl gui:

pops up small popup windows (like postit notes/devcards) that are always on top, easily closable and don't steal focus when created/shown
possible usages and options:
- put inside some code that is executed repeatedly → watch for updates (example: fps profile inside update loop, realtime server request log)
- make it call some code repeatedly and watch results (example: check if fn call produces expected values for inputs (maybe using spec), write fn, reload it and see instantly if it works)
- datafy + nav
- act as breakpoint (subrepl?) that allows to inspect state at point of eval
- sayid-like instrumentation that is IDE-agnostic
- fancy data visualization: trees, charts etc
- data viz allows easy selecting/copying of data
- programmable: can close from code editor
- by default uses only one popup to reduce popup spam, can create multiple by specifying their ids that are just data
- nicely handle atoms (show that it's an atom, show it's contents) and other derefable things (async?).

Notes and ideas:
- make dynamic var to enable/disable visualizations so it can be kept in code without affecting production
- investigate cljs support
- maybe group by ns? Autoswitch groups by current ns?
- maps and sets should be sorted (not everything can be sorted together, like keywords and vectors): [(LINK REMOVED)- watch may show diffs on changes
- prepl integration
- extensible: allow display customization by some id (namespaced keyword? meta?)
- may display meta
- mdoc: render doc as markdown

Problems:
- text view is better to copy parts of result

Food for thought:
- [(LINK REMOVED)- "The hand is much slower than the eye. Licklider described spending hours plotting graphs and seconds understanding them"
- [(LINK REMOVED)- [(LINK REMOVED)- keep in code (a-la devcards) vs stick to repl (a-la temporary evals)
- [(LINK REMOVED)
2019-02-20 15:23:03 (vladislav.protsenko)
Also have a name for it: REVL (read eval visualize loop, pronounced _reveal_)

**Comment by vlaaad** [comment]
Oh hey, I made this tool after all: [vlaaad.github.io/reveal/](https://vlaaad.github.io/reveal/). Not sure why this is a task for Defold though... Maybe safe to close?

**Comment by britzl** [comment]
Yes, close it!
