### ISSUE TITLE
StackOverflowError: Unknown | When editing minified file (DEFEDIT-1501)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3892]
[(LINK REMOVED)
2018-10-29 14:58:20 (Mattias.Hedberg)
the `level_bot.lua` gives the error

put the requires on its own lines in `fixed_level_bot.lua` and defold didn't give me the error anymore
2018-10-29 15:00:03 (Mattias.Hedberg)
I tried to edit about 5 files that had been minified the same way and this was the only file that gave me the error.

**Comment by AGulev** [comment]
it's not enough info, but it looks like this issuse: https://github.com/defold/defold/issues/8815 (more info there)
