### ISSUE TITLE
Some error that keeps poping up when editing code (DEFEDIT-1399)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3903]
[(LINK REMOVED)
2018-05-30 16:53:32 (Erik.Angelin)
> This is one of the files that did it, have been more than this one but it is the only one I remember giving it for sure. Will keep an eye out for it.

> Mattias
 
 
----
 
2018-06-01 15:11:10 (Mattias.Hedberg)
(LINK REMOVED)

**Comment by AGulev** [comment]
no info
