### ISSUE TITLE
Editor 2 does not handle "inherit alpha" correctly (DEFEDIT-1435)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3904]
Presto team is having some problems with render order in a gui scene with a spine model and two text nodes attached to a bone.

*Updated issue:*

The "Inherit alpha" option is not handled correctly in Editor 2.
 *Example 1*: When childing a label to a box node, where the box node has 0 alpha, and the label has "inherit alpha" and alpha set to 1. Result: In the GUI preview the label will be displayed with full alpha, but correctly in runtime (build&launch).
 *Example 2*: Same setup as in example 1, but inside a template. Result: The error is in both the GUI preview and runtime.

See attached minimal repro case:*inherit_alpha_bug.zip*

*Original issue:*

-It appears to occur only when bundling (ie using bob), build and launch from Ed2 seems to work fine.-

-The GUI scene has both layouts and layers. According to- [~Mattias.Hedberg] -and- [~Heather.McGrath] -it seems like the label is rendered behind the spine (see attached images).-
2018-09-05 17:26:30 (Mattias.Hedberg)
In the past we have had problems when parenting nodes to spines. The nodes you parent can take the render order posision of the bone, and it appreas that the bones render order is decided by the name of the bone.

 

Not sure if related or not.

 

(and the pngs names are reveresed)
2018-09-07 11:01:04 (sven.andersson)
Investigated original issue, managed to do a minimal repro case and narrowed it down to how Ed2 handles "inherit alpha" in GUI. Attached project and assigning to ed2-team.

**Comment by britzl** [comment]
Same as #6034

**Comment by d954mas** [comment]
Example 1 yes.
Not sure about example 2, not see it in my projects.

**Comment by britzl** [comment]
Duplicate of https://github.com/defold/defold/issues/6304
