### ISSUE TITLE
Can not download project "Time test" in editor 2 (DEFEDIT-1410)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3918]
Description:
Trying to import "Time test" in editor results in never-ending download progress in Editor2.

Steps to reproduce:
Start Editor 2
Select Import Project
Select "Timer test" project
Click "Import"
Stuck in "Downloading" forever

Expected result:
Expected the download to complete and open the project

Actual result:
Stuck in "Downloading", not even cancelling the download works, it just disables the cancel-button. Have to quit the editor to get out of it

Project is here: (LINK REMOVED)Have added [~Mats.Gisselson] and [~Erik.Angelin] as members to the project.

**Comment by AGulev** [comment]
@britzl we don't have access to this project anymore, I think I can cloase it as outdated
