### ISSUE TITLE
Built in browser for .md no longer renders images/resources in hidden directories (DEFEDIT-1331)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3929]
2018-03-19 13:02:06 (Erik.Angelin)
Broken by DEFEDIT-1326.
2018-03-19 14:05:09 (Erik.Angelin)
PR for utf-8 encoding.
(LINK REMOVED)Resolving resources in hidden directories needs more thought.
2018-03-19 14:08:28 (Erik.Angelin)
fix for utf-8 merged

**Comment by AGulev** [comment]
not sure what is this about
