### ISSUE TITLE
Preview of embedded/imported components in collections (DEFEDIT-819)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3945]
Description:
I would like the ability to in the editor preview how a collection proxy would look inside the collection, I would also like the option to preview an imported gui in a collection.

Use case:
QoL, when building collections right now there is a lot of guessing going on.

2017-01-11 14:23:41 (Sara.Cederberg)
Ragnar. Both of these things work in Editor2, but you probably need more control over what is displayed when. Suggestions on how that should work? :)
2017-01-11 15:43:31 (Sara.Cederberg)
[~Mattias.Hedberg] Could you expand on how you'd like this functionality to work?
2017-01-11 16:48:26 (Mattias.Hedberg)
[~Sara.Glaser]
Preface: Not sure how it works in Editor 2, and this is only an example.

The user should be able to hide everything in the outline, having something selected and pressing the hotkey to hide should hide that item and all its children. The editor should remember which objects are hidden when a user opens the file the next time, important for big and complex scenes.

The ability to hide/show things is important when showing collection proxies because without it a scene will get cluttered fast.

A (for instance) collection proxy should be expandable to show its children, the children should be greyed out both in the outline and in the properties to indicate that they can not be changed. If a user dubble clicks a proxy in the outline that proxy should open.

Other than this the collection proxy should behave and look as if the user had used "Add Collection From File", the above behaviours should be the same for guis and such.

**Comment by AGulev** [comment]
I think it's done with 
<img width="233" alt="image" src="https://user-images.githubusercontent.com/2209596/185921009-706c391d-09ba-4c00-b1be-30576a17c532.png">
