### ISSUE TITLE
TileSource scene views broken after deleting a CollisionObject resource (DEFEDIT-1281)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3950]
Steps to reproduce:
# Create a TileSource.
# Create a CollisionObject resource.
# Delete the CollisionObject resource.
# Open the TileSource in the Scene View.

The TileSource complains about not being able to find the CollisionObject, even though it was never referenced from the TileSource.

**Comment by AGulev** [comment]
I'm not sure how to test it, it's not enough info

**Comment by AGulev** [comment]
I can't reproduce it
