### ISSUE TITLE
Word completion (DEFEDIT-1103)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3971]
Support auto-complete using words found in the current buffer.

**Comment by vlaaad** [comment]
Note: this should be possible to do in the future with a custom language server once we release LSP and implement code completion capabilities.

**Comment by AGulev** [comment]
related to  https://github.com/defold/defold/issues/7699 ?

**Comment by britzl** [comment]
> related to #7699 ?

Yes. Closing.
