### ISSUE TITLE
Set texture_size_recip uniform for font shaders (DEFEDIT-1110)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3972]
(LINK REMOVED)
2017-08-18 10:11:47 (Ragnar.Dahlen)
(LINK REMOVED)
2017-08-18 11:07:38 (Mats.Gisselson)
Reviewed! Don't we need to do this also for Label and Gui Text rendering?

**Comment by Jhonnyg** [comment]
Don't think this is that applicable anymore?
