### ISSUE TITLE
IllegalArgumentException when building collection proxy with empty collection field  (DEFEDIT-979)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3974]
(LINK REMOVED)Our all time favourite :)  "No implementation of method: :proj-path of protocol: #'editor.resource/Resource found for class: nil"

**Comment by AGulev** [comment]
outdated 
![CleanShot 2024-05-20 at 19 15 04@2x](https://github.com/defold/defold/assets/2209596/0985d824-a4d4-4ce8-9db8-08d542e78d3f)
