### ISSUE TITLE
Pack/unpack libjnidispatch same way as other native libs (DEFEDIT-1045)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3975]
We currently rely on JNA unpacking libjnidispatch to a temporary location and using it from there. We should pac/unpack it as we do with other native libs to avoid issues with security (anti-virus warnings, SELinux etc)

Seems like adding logic for packing libjnidispatch in pack.clj and then setting jna.library.boot.path should do it. See:

(LINK REMOVED)

**Comment by AGulev** [comment]
we don't use this lib anymore
