### ISSUE TITLE
Update references to gui resources in templates from external scenes (DEFEDIT-1034)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3987]
When a gui resource such as a Texture or Font is renamed, we should update all references to it from gui scenes that use it as a template. Currently we do this for all references inside the Template scene, but we could do this recursively for external scenes that use the template as well.
2017-06-16 09:37:38 (Mats.Gisselson)
A work-in-progress branch with failing tests for this feature exists here:
(LINK REMOVED)

**Comment by AGulev** [comment]
@matgis I think you mentioned that you have fixed it in 1.9.6 if I understand this issue right

**Comment by matgis** [comment]
Ah, yes! Should be fixed in 1.9.6!
