### ISSUE TITLE
[SENTRY] File not found when building project (DEFEDIT-922)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3991]
(LINK REMOVED)Could be the colon? Disk space? Generic error?
2017-06-05 11:04:36 (Erik.Angelin)
Tried provoking this on Ubuntu. Colon is not a problem. The exception is FileNotFoundException with the message "Permissão negada", Permission denied. Looks like the user doesn't have access to the build directory? (io/output-stream "/no-no") gives same exception.

**Comment by AGulev** [comment]
outdated
