### ISSUE TITLE
Adding a component to a game object inside a referenced collection replaces existing component (DEFEDIT-527)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3995]
h5. Steps to reproduce
# Create a collection file.
# Add a game object to the collection file.
# Add a component to the game object.
# Reference the collection file from another collection
# In the referencing collection, add a new component to the game object in the referenced collection file.

h5. Observed result
The new component replaces the existing component from the referenced collection.

h5. Expected result
The new component is placed alongside the existing component from the referenced collection.

**Comment by AGulev** [comment]
can't reproduce
