### ISSUE TITLE
Form view issues (DEFEDIT-610)

### ISSUE THREAD

**Issue by britzl** [defold/defold#4007]
* Align field labels with "the first line of text in the companion control" or some-such
* Extract things in common with properties_view
* Some way to push up/display errors like in properties_view
* resize table columns to fit data (for instance in texture profiles (LINK REMOVED)
2016-11-29 09:26:40 (Erik.Angelin)
Also:
(LINK REMOVED)(LINK REMOVED)(LINK REMOVED)

**Comment by AGulev** [comment]
outdated
