### ISSUE TITLE
NPE Collision map without alpha channel (DEFEDIT-805)

### ISSUE THREAD

**Issue by britzl** [defold/defold#4011]
(LINK REMOVED)(LINK REMOVED)
2017-02-22 15:37:53 (Erik.Angelin)
Probably fixed as part of DEFEDIT-802
2017-02-23 13:59:00 (Erik.Angelin)
 [^test.rar] 
2017-02-23 14:48:27 (Erik.Angelin)
Problem is that collision image tiles128.png doesn't have an alpha channel we can use for calculating convex hulls. Either make that an error or treat the whole image as alpha=1?

**Comment by AGulev** [comment]
can't reproduce
