### ISSUE TITLE
Exceptions from g/node-value in defhandler functions not properly handled (DEFEDIT-832)

### ISSUE THREAD

**Issue by britzl** [defold/defold#4017]
Several sentry issues come from exceptions being thrown in defhandler/enabled? where we do g/node-value on something that throws an exception - where should this be handled?

(LINK REMOVED)(LINK REMOVED)(LINK REMOVED)(LINK REMOVED)(LINK REMOVED)

**Comment by AGulev** [comment]
not enough info
