### ISSUE TITLE
otf font fails with divide by 0 (bug in Editor 1 as well) (DEFEDIT-822)

### ISSUE THREAD

**Issue by britzl** [defold/defold#4018]
Description:

When I try to create a .font file from an otf font I get a divide by 0 error and the font creation fails. The font can be previewed on my Mac.

Steps to reproduce:

UseGoogle's Noto Sans CJK JP (NotoSansCJKjp-Regular.otf) from[(LINK REMOVED)

Expected result:

The font should be created without an error

Actual result:

I get an error and the font is non-functioning

From the forum:[(LINK REMOVED)

**Comment by AGulev** [comment]
can't reproduce
