### ISSUE TITLE
Improve Resolve Conflicts user experience (DEFEDIT-812)

### ISSUE THREAD

**Issue by britzl** [defold/defold#4019]
When syncing, the Resolve Conflicts stage is rather bare-bones. Even if we intend to overhaul the sync process in the future, we might want to make a few improvements in the interim.
 * Add buttons similar to the View Diff, Stage and Unstage buttons from the Push stage. The user should never have to discover a possible course of action by right-clicking.
 * Add icons and info to show the type of conflict to the unresolved list ("deleted by them", "deleted by you", etc.).
 * Add icons and info to show how a conflict was resolved to the resoved list ("theirs", "mine").

**Comment by AGulev** [comment]
outdated
