### ISSUE TITLE
Editor tab state not refreshed after dragged files are merged (DEFEDIT-760)

### ISSUE THREAD

**Issue by britzl** [defold/defold#4024]
h5. Steps to reproduce
# Open a project that contains a `main` directory with a `main.script` in it.
# Open `main.script` in the editor.
# Create another `main` folder elsewhere in the project and add another `main.script` to it.
# Open the newly created `main.script` in the editor.
# Drag the newly created `main` folder to the root of the project.
# Choose *Overwrite Files* in the dialog that appears. This will overwrite the original `main.script` with your newly created `main.script`.

h5. Expected result
The tab for the dragged `main.script` file is closed. The tab for the original `main.script` file now contains the code from the dragged `main.script`.

h5. Observed result
None of that happens. The user has to to close and reopen the tabs to see the changes.

**Comment by AGulev** [comment]
Can't reproduce. Both open files stay opened, yes, but with the same updated content
