### ISSUE TITLE
Respect default texture filter settings in game.project when converting material textures into samplers (DEFEDIT-709)

### ISSUE THREAD

**Issue by britzl** [defold/defold#4026]
The old editor supports both textures and samplers inside material files. Textures are simply names of texture slots, whereas samplers also contain filtering and wrap settings.

Since textures don't specify a filtering mode, there is a setting in {{game.project}} that affects how textures are filtered by the engine.

In the new editor, we convert textures into samplers when loading the project. This means the sampler settings are effectively saved to the material files, and these materials are no longer affected by the {{game.project}} setting.

We do not currently respect the {{game.project}} setting at all when converting textures to samplers - the new samplers will all use linear filtering.

h5. Things to consider:
* Blossom does not specify the {{game.project}} setting. It might be uncommon?
* We could make the sampler filter settings optional and not specify it for new samplers.
** Should the engine be responsible for using the {{game.project}} setting in this case?
*** We might already have to deal with this if bundled resources use textures instead of samplers.
** Other alternative is to have the editors inject the {{game.project}} setting when building.
*** Need to do this in the old editor as well.

**Comment by AGulev** [comment]
outdated
