### ISSUE TITLE
Clicking outside of tree-view items "opens" the selected item (DEFEDIT-532)

### ISSUE THREAD

**Issue by britzl** [defold/defold#4039]
This is because of how javafx and (bind-double-click view ...) works. It seems like the logic for responding to input events is quite hidden in javafx and there is no clear solution to this issue. Even tieing the double-click to the items yielded the same erroneous behaviour due to there being "empty" items all over the place.

**Comment by AGulev** [comment]
not sure I understand what is this about

**Comment by britzl** [comment]
Closing.
