### ISSUE TITLE
Show error reason if an error occurs during sync (DEFEDIT-604)

### ISSUE THREAD

**Issue by britzl** [defold/defold#4040]
h5. Steps to reproduce
# Use the git command line to place your working directory in a detached HEAD state. You can do this by checking out a previous commit: {{git checkout HEAD^}}
# Open the Sync dialog and press the Pull button.

h5. Observed result
An error dialog appears, but there is no information about what went wrong.

h5. Expected result
The error dialog contains information about what went wrong.
2016-11-24 10:34:43 (Mats.Gisselson)
Also seen by [~Erik.Angelin] and [~sofia.hedlund]

**Comment by AGulev** [comment]
outdated
