### ISSUE TITLE
Enable reaction when changing camera projection (DEFEDIT-372)

### ISSUE THREAD

**Issue by britzl** [defold/defold#4045]
As no mouse-moved events are dispatched when changing camera projection (for example by zooming) we fail to detect some changes to the view of a scene. For example, some objects may gain/loose mouse-over focus but we don't detect and visualise that properly.

**Comment by AGulev** [comment]
not sure I understand what is this about

**Comment by britzl** [comment]
> not sure I understand what is this about

Me neither :-) It's labeled "editor" which makes it more confusing. Closing it.
