### ISSUE TITLE
Assert when quitting in the middle of Sync conflict resolution (DEFEDIT-582)

### ISSUE THREAD

**Issue by britzl** [defold/defold#4047]
h5. Steps to reproduce
# Push some changes to a `.script` file onto the server from another clone of your game repo.
# Use the editor to make a change to the same `.script` file, manufacturing a conflict.
# Choose *Synchronize...* from the File menu and proceed to the Conflict Resolution stage.
# Resolve the conflict by choosing *Use Mine* from the file context menu.
# Quit the editor without dismissing the Sync dialog.

h5. Expected result
The application should quit without errors.

h5. Observed result
The following error appears in an alert:
{code}
{:cause
 "Assert failed: The following resources were changed but never loaded before: /main/main.script\n(empty? unknown-changed)",
 :via
 [{:type java.lang.AssertionError,
   :message
   "Assert failed: The following resources were changed but never loaded before: /main/main.script\n(empty? unknown-changed)",
   :at
   [editor.defold_project$handle_resource_changes$fn__30047 invoke "defold_project.clj" 499]}],
 :trace
 [[editor.defold_project$handle_resource_changes$fn__30047 invoke "defold_project.clj" 499]
  [clojure.lang.AFn applyToHelper "AFn.java" 152]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.core$apply invokeStatic "core.clj" 646]
  [clojure.core$with_bindings_STAR_ invokeStatic "core.clj" 1881]
  [clojure.core$with_bindings_STAR_ doInvoke "core.clj" 1881]
  [clojure.lang.RestFn invoke "RestFn.java" 425]
  [editor.defold_project$handle_resource_changes invokeStatic "defold_project.clj" 424]
  [editor.defold_project$handle_resource_changes invoke "defold_project.clj" 423]
  [editor.defold_project.ProjectResourceListener handle_changes "defold_project.clj" 655]
  [editor.workspace$resource_sync_BANG_ invokeStatic "workspace.clj" 248]
  [editor.workspace$resource_sync_BANG_ invoke "workspace.clj" 207]
  [editor.workspace$resource_sync_BANG_ invokeStatic "workspace.clj" 213]
  [editor.workspace$resource_sync_BANG_ invoke "workspace.clj" 207]
  [editor.workspace$resource_sync_BANG_ invokeStatic "workspace.clj" 209]
  [editor.workspace$resource_sync_BANG_ invoke "workspace.clj" 207]
  [editor.changes_view$eval32699$fnk32701_positional__32704 invoke "changes_view.clj" 94]
  [editor.changes_view$eval32699$fnk32701__32715$fn__32716 invoke "changes_view.clj" 87]
  [editor.changes_view$eval32699$fnk32701__32715 invoke "changes_view.clj" 87]
  [clojure.lang.AFn applyToHelper "AFn.java" 154]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 29]
  [clojure.lang.RestFn invoke "RestFn.java" 408]
  [editor.handler$invoke_fnk invokeStatic "handler.clj" 46]
  [editor.handler$invoke_fnk invoke "handler.clj" 43]
  [editor.handler$run invokeStatic "handler.clj" 65]
  [editor.handler$run invoke "handler.clj" 64]
  [editor.ui$make_menu_item$fn__27353 invoke "ui.clj" 779]
  [editor.ui$make_menu_command$reify__27340 handle "ui.clj" 734]
  [com.sun.javafx.event.CompositeEventHandler dispatchBubblingEvent "CompositeEventHandler.java" 86]
  [com.sun.javafx.event.EventHandlerManager dispatchBubblingEvent "EventHandlerManager.java" 238]
  [com.sun.javafx.event.EventHandlerManager dispatchBubblingEvent "EventHandlerManager.java" 191]
  [com.sun.javafx.event.BasicEventDispatcher dispatchEvent "BasicEventDispatcher.java" 58]
  [com.sun.javafx.event.EventDispatchChainImpl dispatchEvent "EventDispatchChainImpl.java" 114]
  [com.sun.javafx.event.EventUtil fireEventImpl "EventUtil.java" 74]
  [com.sun.javafx.event.EventUtil fireEvent "EventUtil.java" 49]
  [javafx.event.Event fireEvent "Event.java" 198]
  [javafx.scene.control.MenuItem fire "MenuItem.java" 462]
  [com.sun.javafx.scene.control.GlobalMenuAdapter lambda$bindMenuItemProperties$20 "GlobalMenuAdapter.java" 153]
  [com.sun.javafx.event.CompositeEventHandler dispatchBubblingEvent "CompositeEventHandler.java" 86]
  [com.sun.javafx.event.EventHandlerManager dispatchBubblingEvent "EventHandlerManager.java" 238]
  [com.sun.javafx.event.EventHandlerManager dispatchBubblingEvent "EventHandlerManager.java" 191]
  [com.sun.javafx.event.BasicEventDispatcher dispatchEvent "BasicEventDispatcher.java" 58]
  [com.sun.javafx.event.EventDispatchChainImpl dispatchEvent "EventDispatchChainImpl.java" 114]
  [com.sun.javafx.event.EventUtil fireEventImpl "EventUtil.java" 74]
  [com.sun.javafx.event.EventUtil fireEvent "EventUtil.java" 54]
  [javafx.event.Event fireEvent "Event.java" 198]
  [javafx.scene.control.MenuItem fire "MenuItem.java" 462]
  [com.sun.javafx.tk.quantum.GlassSystemMenu$1 action "GlassSystemMenu.java" 238]]}
{code}

**Comment by AGulev** [comment]
outdated. we can't synchronize in the editor anymore
