### ISSUE TITLE
Refactor gui nodes to minimise dependencies (DEFEDIT-341)

### ISSUE THREAD

**Issue by britzl** [defold/defold#4060]
The goal would be to cut the amount of dependencies when using layouts and templates in combination. A brief idea is to rather than let an internal property (visible-layout) dictate whats emitted from a scene, instead form explicit connections to avoid unnecessary computations.

**Comment by matgis** [comment]
The proposed change was made irrelevant by #9884.

**Comment by AGulev** [comment]
Close this issue then?
