### ISSUE TITLE
Template chain with missing layouts (DEFEDIT-322)

### ISSUE THREAD

**Issue by britzl** [defold/defold#4061]
When:
* there is a chain of gui templates
* the sub-most scene and super-most scene chair a layout
* the in-between scenes do not have this layout
then, the sub-most layout will not be used in the super-most. This can probably be fixed, but there is a bigger issue here. If it was used, and the layout was introduced in the in-between scene, the overrides in the super-most would be lost. This requires a lot of thinking, right now I can't see a good fix for this problem.

**Comment by AGulev** [comment]
@matgis maybe this one is also related to your latest fix

**Comment by matgis** [comment]
I believe this should be fixed in 1.9.6, yes!
