### ISSUE TITLE
Split off scroll bar from minimap view in code editor (DEFEDIT-1594)

### ISSUE THREAD

**Issue by britzl** [defold/defold#4074]
Both VSCode and Sublime Text now have the vertical scroll bar as a separate area from the minimap. This might be better when interacting with the different elements.

We probably want to do the same for the horizontal scroll bar if we decide to do this.

**Comment by AGulev** [comment]
nor sure what is this about ? 
<img width="119" alt="image" src="https://user-images.githubusercontent.com/2209596/205435386-bfe1684f-9395-4dc7-9524-7b7a59caacd1.png">

**Comment by britzl** [comment]
No idea. Close it!
