### ISSUE TITLE
Run arbitrary collection (DEFEDIT-1219)

### ISSUE THREAD

**Issue by britzl** [defold/defold#4084]
2017-11-10 16:36:29 (Ragnar.Dahlen)
Liten fredags-feature. Gjorde den delvis för att titta på sätt att bygga med vissa förändrade värden i game.project, kommer att behövas till debuggingen:

[(LINK REMOVED) 
2017-11-13 11:52:43 (Erik.Angelin)
Don't merge yet, possible cache issue (LINK REMOVED)

**Comment by AGulev** [comment]
outdated
