### ISSUE TITLE
Make scroll bar thumbs easier to grab (DEFEDIT-700)

### ISSUE THREAD

**Issue by britzl** [defold/defold#4092]
Is it possible to set a min height for scroll bar thumbs? In long lists, the thumb can become tiny and difficult to grab.

![scroll-thumb-tiny](https://user-images.githubusercontent.com/2209596/65377113-4b73af80-dca8-11e9-8f86-ac3602cdec72.png)

**Comment by AGulev** [comment]
<img width="89" alt="image" src="https://user-images.githubusercontent.com/2209596/205435337-e6c1040a-b954-4789-87a7-bac62968b487.png">
