### ISSUE TITLE
Loading resources is slow if engine is restarted via editor

### ISSUE THREAD

**Issue by britzl** [defold/defold#4116]
If I press Cmd+B while the game is already running, it takes forever to restart and any subsequent collection load also takes a long time. If I close the engine, then Cmd+B it’s fine.

After some digging I found that loading resources via the network is unjustifiably slow (60MB/s in Interrogation and 10MB/s for the attached repro case) and CPU-bottlenecked (dmengine uses 100% CPU).

Repro-case on forum: https://forum.defold.com/t/loading-resources-is-slow-if-engine-is-restarted-via-editor/53361

**Comment by AGulev** [comment]
We load all resources sync one by one.

<img width="1675" alt="image" src="https://user-images.githubusercontent.com/2209596/184187596-1687dddf-f3fb-4140-9a3e-d9d5fa4e207c.png">


<img width="1663" alt="image" src="https://user-images.githubusercontent.com/2209596/184188123-da1798ec-985f-4240-8cd0-0d6bc6df749b.png">


Xcode Instruments (Time Profiler) snapshot:
[ResourceLoading.trace.zip](https://github.com/defold/defold/files/9310283/ResourceLoading.trace.zip)

**Comment by britzl** [comment]
First investigation step should be to serve the files using a normal local python server to verify if the speed is equally slow as when served from the editor.

**Comment by britzl** [comment]
We need to investigate all potential sources of problems. Cache misses each time? Slow connection? Single vs multi threaded downloads? And so on.

**Comment by Jhonnyg** [comment]
From my investigation:

The engine is rebooted from the editor by passing a reboot message together with a http path where the data should be read from, and when I load something like 1.5gb on my mac I get:
First run: ~0.88s (loading from file)
Reboot: ~2.5s (loading from editors http server)

If I use a local python server instead (python3 -m http.server):
First run: ~0.88s (same as before)
Reboot: ~1s (loading from python server)

I don't know how the details regarding the editor, but it seems the http server we use there is quite a bit slower.
