### ISSUE TITLE
Setting linear velocity and angular velocity of a kinematic body

### ISSUE THREAD

**Issue by andsveking** [defold/defold#4170]
**Is your feature request related to a problem? Please describe (REQUIRED):**
Yes, when dynamic bodies collide with kinematic bodies, forces don’t work as they should when “teleporting” kinematic objects using set_position().

**Describe the solution you'd like (REQUIRED):**
An API so I can change velocity via Lua for collision objects of kinematic type.

**Describe alternatives you've considered (REQUIRED):**
n/a

**Additional context (OPTIONAL):**
Feature request from forums: https://forum.defold.com/t/setting-linear-velocity-and-angular-velocity-of-a-kinematic-body/53948

**Comment by AGulev** [comment]
One more request:

> I can’t set the linear velocity to a physic body? How to make a proper jump in this case?

https://forum.defold.com/t/zoom-be-my-new-game/64864

**Comment by britzl** [comment]
https://forum.defold.com/t/2d-physics-requests/65662

**Comment by britzl** [comment]
Released in 1.2.171
