### ISSUE TITLE
Update Emscripten version at least to v1.38.17 or newer.

### ISSUE THREAD

**Issue by AGulev** [defold/defold#4179]
**Task (REQUIRED):**

Update Emscripten version at least to v1.38.17 or newer.

v1.38.17: 11/07/2018
--------------------
- Minify wasm import and export names. This decreases JS and wasm size by
  minifying the identifiers where JS calls into wasm or vice versa, which
  are not minifiable by closure or other JS-only tools. This happens in
  -O3, -Os and above. See #7431

**Expected outcome (REQUIRED):**

It could help to reduce build size.

https://github.com/emscripten-core/emscripten/pull/7431

“Turns out this is pretty useful, if you have lots of imports or exports. On BananaBread there are lots of GL calls, and we save 10% of JS size and 1% of wasm size. On Bullet we wrap classes for JS, which means calls to lots of functions, and we save 16% of JS size and 8% of wasm size. Much more than I expected!”

**Comment by britzl** [comment]
Solved by PR https://github.com/defold/defold/pull/4805
