### ISSUE TITLE
[LOW PRIO] Single build pipeline

### ISSUE THREAD

**Issue by britzl** [defold/defold#4201]
STEP 1
* Implement iOS bundling
  * Port the tests
* Investigate headless editor 
  * Same command line arguments as bob.jar
    * Maybe reconsider some of the arguments now that we have a chance
  * Bundle with Java

STEP 2
* Implement Android bundling

STEP 3
* Implement bundling for the rest of the platforms

Input from pkeod on Slack:

> It would be nice if eventually stuff like per target / texture profile compression stuff could be optionally cached somewhere
> 
> so when we make bundles the process could check to see if there is a proper cached version to use instead of redoing it
> would save on bundle time since a lot of the time there are no platform specific texture changes when making new bundles

PR: #4377

**Comment by AGulev** [comment]
do we really want (still?)

**Comment by britzl** [comment]
No it is an unrealistic goal at the moment. We can make sure to share more code though.
