### ISSUE TITLE
Auto-save

### ISSUE THREAD

**Issue by britzl** [defold/defold#4220]
https://forum.defold.com/t/autosave/55979

Investigate.

Saving happens on background thread but does getting git status block?

**Comment by jbskaggs42** [comment]
I support and look forard to a autosave feature at least a backup save that can be loaded on power loss etc.  WHICH is a big deal in the Mid West of USA.
So I up vote this

**Comment by britzl** [comment]
Duplicate https://github.com/defold/defold/issues/7930
