### ISSUE TITLE
[MEDIUM PRIO] Improve mobile dev app and add bundling option from within the editor

### ISSUE THREAD

**Issue by britzl** [defold/defold#4307]
**Is your feature request related to a problem? Please describe (REQUIRED):**
There is repeated confusion from our users when they download the mobile dev app (dmengine.apk) from d.defold.com and expect it to contain the native extensions they have defined in game.project. They also expect things such as a custom AndroidManifest.xml file to be used.

**Describe the solution you'd like (REQUIRED):**
The default mobile dev app should contain a very visible warning that it does not use any native extensions or customizations.

The Project -> Sign iOS App option should be removed and replaced with a "Bundle Dev App" or possibly "Bundle Dev App->Android" and "Bundle Dev App->iOS" option that will bundle an empty dev app containing the native extensions and other customizations that the user has made.

We will regardless of this at some point soon have to remove the "Sign iOS App..." as we are deprecating the dashboard.

**Describe alternatives you've considered (REQUIRED):**
We could settle for only adding the warning and skip the "Bundle Dev App" option. There is already a warning in the manual, but it doesn't seem sufficient.

**Comment by AGulev** [comment]
Closed in favor of https://github.com/defold/defold/issues/6389
