### ISSUE TITLE
Update the AdMob extension

### ISSUE THREAD

**Issue by britzl** [defold/defold#4395]

**Comment by Dragosha** [comment]
Which quartal for this NE in the roadmap 2021?
I'ld like to use it.

**Comment by britzl** [comment]
> Which quartal for this NE in the roadmap 2021?

Probably late Q2.

**Comment by Dragosha** [comment]
> Probably late Q2.

Thanks!

**Comment by AGulev** [comment]
ToDo to track the progress:
- [ ] skeleton of `Defold Lua -> cpp -(JNI)-> Java` communication
- [ ] skeleton of `Java -> cpp -(queue)-> Defold Lua` communication
- [ ] Initialization of the sdk Android
- [ ] Show Interstitial ADS Android
- [ ] Show Rewarded ADS Android
- [ ] Interstitial enums 
- [ ] Interstitial callbacks Android
- [ ] Rewarded enums
- [ ] Rewarded callbacks Android
- [ ] Banners Android
- [ ] `is_ad-type_loaded` method
- [ ] Show Interstitial ADS iOS
- [ ] Show Rewarded ADS iOS
- [ ] Show Banner ADS iOS
- [ ] Initialize SDK on load automatically depends on parameter in `game.project` (make it by dafult?)
- [ ] Add new TODOs for AdMob ADS Mediation

**Comment by AGulev** [comment]
The new version of extension is available here https://github.com/defold/extension-admob/tree/new-admob

**Comment by realstudent** [comment]
Be cool if final release you also backport to 179 version. If .....

**Comment by AGulev** [comment]
[New implementation of AdMob SDK from scratch released](https://github.com/defold/extension-admob/releases/tag/2.0.0)
