### ISSUE TITLE
Crash on iOS when coming back from lock screen

### ISSUE THREAD

**Issue by britzl** [defold/defold#4674]
https://github.com/defold/defold/issues/5045

**Comment by britzl** [comment]
https://forum.defold.com/t/ios-crash-on-app-focus-gain-in-dmgraphics-clear-dmgraphics-context-unsigned-int-unsigned-char-unsigned-char-unsigned-char-unsigned-char-float-unsigned-int/64609

**Comment by britzl** [comment]
https://forum.defold.com/t/defold-1-2-164-has-been-released/63982/18?u=dragosha

**Comment by AGulev** [comment]
https://forum.defold.com/t/defold-1-2-164-has-been-released/63982/24?u=agulev
