### ISSUE TITLE
Add texture readback for Vulkan

### ISSUE THREAD

**Issue by jhonnyking** [defold/defold#4688]
This is currently being used in the recorder library, which is more or less deprecated by now in favour of the community extension. It's not exactly a high prio right now I think.

**Comment by jhonnyking** [comment]
This is only used for the internal recorder functionality. I suggest we wait with this until it’s requested.

**Comment by britzl** [comment]
I agree!

**Comment by subsoap** [comment]
Recorder function is cool but shouldn't be a part of the core engine.
