### ISSUE TITLE
Add option to let ray casts return all objects along the ray

### ISSUE THREAD

**Issue by britzl** [defold/defold#4710]
https://forum.defold.com/t/physics-raycast-must-return-all-objects-along-the-ray/62933/8?u=britzl

**Comment by JCash** [comment]
Current design:
https://docs.google.com/document/d/1OccJiFl2GhtLZNXj9H2Fj9_UeJUHpbr6mH1Sa_hvPS4/edit?usp=sharing

**Comment by JCash** [comment]
Test project:
[issue-3710-raycast-results.tar.gz](https://github.com/defold/defold/files/4721610/issue-3710-raycast-results.tar.gz)
