### ISSUE TITLE
SSL error on shutdown

### ISSUE THREAD

**Issue by britzl** [defold/defold#4721]
**Describe the bug (REQUIRED)**
An assert is triggered in mbedTLS when the application is shut down while there is an active HTTP request.

**To Reproduce (REQUIRED)**
1. Make an HTTPS request
2. Shut down the application before the request has finished
3. Notice `Assertion failed: address.m_family == DOMAIN_IPV4, file ..\src\dlib\socket.cpp`

**Expected behavior (REQUIRED)**
No error should be reported on shutdown

**Defold version (REQUIRED):**
  - 1.2.166

**Platforms (REQUIRED):**
 - Platforms: Reproduced on Windows
 - OS: Windows 10

Not sure if it happens on other platforms

**Additional context (OPTIONAL):**
https://forum.defold.com/t/problem-with-playfab-requests/63642/6?u=britzl

**Comment by Taure** [comment]
I think the issue here is that the socket is closed before the one listening is closed. Not sure why it only happens on windows.

But I have seen kind off same behaviour on Android/iOS when they kill the application and close socket. But some part is still trying to access the socket that is closed.

**Comment by britzl** [comment]
I wonder if we can make a graceful shutdown of the open socket when the game is closed?

**Comment by Taure** [comment]
Not sure how the semantic is what part of the game that owns things and what is in engine. If I can get some direction to some network code I can have a look.

**Comment by britzl** [comment]
> If I can get some direction to some network code I can have a look.

Sure, the http client is here: https://github.com/defold/defold/blob/dev/engine/dlib/src/dlib/http_client.h

**Comment by AGulev** [comment]
hmm, i think this issue solved for a long time ago, no?
I close it, pls open a new one if you repo it
