### ISSUE TITLE
Cleanup of unused live update resources

### ISSUE THREAD

**Issue by britzl** [defold/defold#4722]
**Is your feature request related to a problem? Please describe (REQUIRED):**
When using live update to modify the manifest you can end up with previously downloaded and now unused files. There is no way to clean up these unused files.

**Describe the solution you'd like (REQUIRED):**
When updating the manifest there needs to be a system in place which deletes downloaded and stored resources that are not included in the new manifest.

**Describe alternatives you've considered (REQUIRED):**
There is no workaround.

**Additional context (OPTIONAL):**
https://forum.defold.com/t/live-update-delete-resource/64667?u=britzl

**Comment by AGulev** [comment]
https://github.com/defold/defold/issues/3207

https://github.com/defold/defold/issues/4657

**Comment by ekharkunov-ms** [comment]
I guess these issue can be closed after 1.5.0 release.

**Comment by AGulev** [comment]
@britzl and this one also outdated
