### ISSUE TITLE
Android Billing 3.0

### ISSUE THREAD

**Issue by britzl** [defold/defold#4731]
Add support for the latest billing/IAP API on Android

**Comment by britzl** [comment]
https://android-developers.googleblog.com/2020/06/meet-google-play-billing-library.html

**Comment by AGulev** [comment]
> Starting August 2, 2021, all new apps must use Billing Library version 3 or newer. By November 1, 2021, all updates to existing apps must use Billing Library version 3 or newer.

:|

**Comment by britzl** [comment]
First release of Billing 3.0: https://github.com/defold/extension-iap/releases/tag/2.0.0
