### ISSUE TITLE
Add Lua function to define custom profiler scopes and counts

### ISSUE THREAD

**Issue by britzl** [defold/defold#4738]

**Comment by aglitchman** [comment]
Also, please add C++ APIs for native extensions. You can just expose your dmProfile headers. Currently, I use [microprofile](https://github.com/jonasmr/microprofile) to measure the functions execution time of the C++ part of [my early game prototype](https://twitter.com/aglitchman/status/1290320039531499521?s=20).

And it will be awesome to keep profiler in the Release build of the engine. I suppose that it doesn't add much overhead.
