### ISSUE TITLE
The bundled character set is different from Editor/bob

### ISSUE THREAD

**Issue by JCash** [defold/defold#4744]
https://forum.defold.com/t/font-glyphs-missing-when-bundling-with-bob-show-up-when-bundling-with-editor/64806

"...t uses ~ instead of https://www.compart.com/en/unicode/U+2022 "

**Comment by AGulev** [comment]
I think it is fixed by @britzl 
<img width="580" alt="image" src="https://github.com/defold/defold/assets/2209596/03c5b582-2d2d-40a5-98ca-dbcb04604e2b">
