### ISSUE TITLE
Defold is not open source, so it shouldn't refer to itself as open source

### ISSUE THREAD

**Issue by EIREXE** [defold/defold#4792]
Hello, first of all let me know if this is not the right place to open this issue.

Defold has, since today, referred to itself as open source, this is incorrect. As per the OSI's [definition of open source software](https://opensource.org/osd) this software is not open source, due to the clause disallowing commercialization of a "Game Engine Product" based on the engine's code.

The OSI's OSD definition is widely accepted by all the software industry, this includes companies like Microsoft who use the term "source available" for software that has the source code available but disallows certain uses that the OSD requires, Epic Games who don't use the term Open Source for their engine, despite the source code being available to anyone and many other parties. This isn't a matter of the term being confusing.

Also, keep in mind a software cannot be partially open source, a software either is or isn't, there's no gray scales, only black and white.

I believe using the term open source for defold is confusing and might be damaging to the Open Source and Free Software movements, so I kindly request a change be made, either to the license or to the wording used.

Greetings.

**Comment by britzl** [comment]
Thank you for the feedback. We are sorry for misrepresenting the license under which we make the source code available. Defold is a free and open game engine with a permissive license. We invite the community to contribute to the source code here on GitHub.

We have updated our webpage to reflect this and we have tweeted an update: https://twitter.com/defold/status/1262744466311360517

**Comment by EIREXE** [comment]
> 
> 
> Thank you for the feedback. We are sorry for misrepresenting the license under which we make the source code available. Defold is a free and open game engine with a permissive license. We invite the community to contribute to the source code here on GitHub.
> 
> We have updated our webpage to reflect this and we have tweeted an update: https://twitter.com/defold/status/1262744466311360517

Thank you for clarifying the wording.
