### ISSUE TITLE
License issue/question

### ISSUE THREAD

**Issue by leonidboykov** [defold/defold#4795]
Hello guys, thanks for your awesome work!

I'm totally fine with your open source license (unrelated to #4792), but I want to ask a question about it.

As far as I can see you've added a few paragraphs to Apache License.

```markdown
“Game Engine Product” shall mean software used for video game development. This
includes both the content authoring software and the software used to show the
created content.

<...>

a) You do not sell or otherwise commercialise the Work or Derivative Works as a
Game Engine Product; and
```

while statement 9 contains

```markdown
9. Accepting Warranty or Additional Liability. While redistributing the Work or
Derivative Works thereof, You may choose to offer, and **charge a fee** for,
acceptance of support, warranty, indemnity, or other liability obligations
and/or rights consistent with this License.
```

Does _commercialize_ mean "sell", or any "fee" is prohibited?

Maybe, It would be suitable to distribute code under a GPL-like license as [Qt does](https://doc.qt.io/qt-5/lgpl.html)? Everybody knows that you can't sell GPL licensed code without contributing back.

Disclaimer: I'm not a lawyer.

**Comment by britzl** [comment]
Let me double-check with the lawyers regarding this and get back to you.

**Comment by gondur** [comment]
Hello I agree on leonidboykov concerns: the "non commercial" restrictions breaks down the "permissive" license, because normally permissive license are not restrictive in use or are incompatible with all other FOSS licenses. This license with this clause is sadly incompatible with FOSS licenses (no code exchange), with linux repos, and not as advertised a permissive license (compare here with other permissive licenses https://en.m.wikipedia.org/wiki/Permissive_software_license )

And if you REALLY want a a non commercial license I would suggest using an established on as the CC - SA-NC https://creativecommons.org/licenses/by-nc-sa/2.0/ as this one is already tested.

But anyway - thank you for making the source code available this is a win anyway! :)

**Comment by gondur** [comment]
PS: making an engine AGPL / GPLv3 is normally strict enough to prevent commercialization from competitors without giving back, maybe you can consider also dual licensing GPLv3 & this license (fixed of conflicting clauses)

**Comment by britzl** [comment]
We really appreciate your feedback and we will do our best to address your concerns and amend/clarify the license if possible. If will get back to you soon.

**Comment by britzl** [comment]
We're still working on clarification. Sorry to keep you waiting!

**Comment by gondur** [comment]
> 
> 
> We're still working on clarification. Sorry to keep you waiting!

what is your line of thinking in this license adaption process? Maybe involve the community here already early on in this brainstorming, to catch challenges/problems early also :)

**Comment by britzl** [comment]
There is a very very clear requirement from the founders of the Defold Foundation that the Defold engine+editor can under no circumstances be commercialised in any shape or form. This is set as one of the foundation objectives and if we were to change the license to allow for commercialisation of the engine+editor the foundation would be dissolved according to Swedish law.

What we want to do is to clarify any ambiguity in the license and make it perfectly clear what Game Engine Product means. And clear up any other kind of confusion like the initial question raised in this ticket.

Also note that we no longer use the word "permissive", "open source" or "free" when we describe Defold:

* "Free" -> Defold is free to use as in no upfront fees, no royalties, no licensing costs.
* "Open Source" -> The Defold source code is available.
* "Permissive" -> The Defold license is from a game developers perspective a "developer-friendly" license. This means that:
  * Game developers can commercialise their games any way they want
  * Game developers can modify the Defold engine and editor source code if they want to. And they don't have to share the changes and they can sell Defold games made using a modified engine.

**Comment by gondur** [comment]
thanks for explanation, this restriction makes it hard.

Very good, these three wording changes are good and appropriate and correct from my perspective. :)

The trickiest part is the commercialization:
The Non-commercial term only applies to the engine itself - and but a game coming out of it can be commerzialized. This is not reflected by any existing standard license - here you will need own clauses or own written license

As alternative to your major rewritte of permissive license (not good fit), maybe a better starting point would be take the **CC BY-NC** ( which allows use, adaption, sharing BUT not selling in general) and add some addtional clause/grant which allows the selling of an "Engine Product" -> this engine product would be than also licensed under your "**_CC BY-NC with product selling grant_**" license but which should be no serious problem for such a developer.  
https://creativecommons.org/licenses/by-nc/4.0/
https://creativecommons.org/licenses/by-nc/4.0/legalcode

But be aware, that with this restriction & license the DEFOLD engine will be problematic to share source code with FOSS source code projects - MIT/BSD permissive licensed projects might share in direction of the DEFOLD engine (but not way around) & copyleft will not exchange in no direction.

**Comment by britzl** [comment]
> As alternative to your major rewritte of permissive license (not good fit)

What do you mean by this? 

> maybe a better starting point would be take the CC BY-NC 
> and add some addtional clause/grant

Wouldn't this also result in a non-standard license? And what would be the difference from the non-standard license we have today (Apache 2.0 + non-commercialisation)?

> But be aware, that with this restriction & license the DEFOLD engine will be problematic to share source code with FOSS source code projects - MIT/BSD permissive licensed projects might share in direction of the DEFOLD engine

Yes we know, and it is not optimal. I would personally have preferred a straight MIT/Apache 2.0 license. But it either staying closed source as we have been for the last couple of years or with source available with a non-standard license as we are today. And I'd opt for source available always.

**Comment by gondur** [comment]
> 
> 
> > As alternative to your major rewritte of permissive license (not good fit)
> 
> What do you mean by this?

I mean, you choose a Apache license as base which is more permissive than what you have in mind - you try to add the restriction NC clause on top, selfwritten - but NC is a tricky term. My suggestion is starting with a best fitting, slightly overfitting license (CC BY-NC) which has already the NC term - and then easing it with a clause which you would like to allow -> the selling the products.

I think the advantages are: the CC BY-SA is much more new than the Apache, adapted for law domains beyond the US american one and went through many iterations (v4) already and include the NC term in a tested way.  (Ok, for the Apache speaks, it is an specific software license, the CC licenses are general)

> > maybe a better starting point would be take the CC BY-NC
> > and add some addtional clause/grant
> 
> Wouldn't this also result in a non-standard license? And what would be the difference from the non-standard license we have today (Apache 2.0 + non-commercialisation)?

yes, it would - but I'm not aware of any fitting standard license fitting for your case. Have you asked to OSI for help?

 > > But be aware, that with this restriction & license the DEFOLD engine will be problematic to share source code with FOSS source code projects - MIT/BSD permissive licensed projects might share in direction of the DEFOLD engine
> 
> Yes we know, and it is not optimal. I would personally have preferred a straight MIT/Apache 2.0 license. But it either staying closed source as we have been for the last couple of years or with source available with a non-standard license as we are today. And I'd opt for source available always.

yes, that would have been optimal... but what you can offer is already great :)

**Comment by leonidboykov** [comment]
Thanks for your clarification, I have a better understanding of what you meant with a custom license for now.

FYI, Aseprite (pixel art editor) is distributed with a custom [EULA](https://github.com/aseprite/aseprite/blob/master/EULA.txt).

From their FAQ

> ### If Aseprite source code is available, how is that you are selling it?
> Aseprite started being open source since its very beginning in 2001, and we were happy with that until August 2016. Now you can still download its source code, compile it, and use it for your personal purposes. You can make commercial art/assets with it too. The only restriction in Aseprite EULA is that you cannot redistribute Aseprite to third parties.
>
> ### Can I redistribute Aseprite?
> No. From August 2016 you cannot redistribute compiled versions of Aseprite. We have replaced the General Public License (GPLv2) with the new Aseprite EULA. The only way to redistribute Aseprite is with an special educational license.
>
> Anyway this does not restrict most users: You can still compile the source code, and use the program to create your assets for commercial games. You can also make contributions to Aseprite or modify its source code for your personal purposes.

Wouldn't it be a solution for Defold licensing?

**Comment by AGulev** [comment]
Defold has this page with explanations what you can and what you can't do
https://defold.com/license/
<img width="1164" alt="image" src="https://user-images.githubusercontent.com/2209596/83328320-7b854080-a282-11ea-9043-89b864c3b42a.png">

**Comment by britzl** [comment]
I wanted to give you an update and say that we haven't forgotten about this! I'm sorry that clarifications to the license have been delayed. We are working with our lawyers to see what can be done to clarify/change the license while staying in line with the Defold Foundation objectives (which we can't change).

**Comment by MetalMaxMX** [comment]
So. How is the process of this particular topic going about so far? Any updates?

**Comment by MetalMaxMX** [comment]
Bump. 

I wonder if it wouldn't be possible to dual-license this to something with an AGPLv3 license or a GPLv3 with linking-exception. It would certainly deter commercial usage by quite a bit

**Comment by britzl** [comment]
> Bump.

Sorry for the very very slow response to this issue! We've worked with our lawyers to evaluate the statutes and objectives of the foundation which were set when the foundation was created in 2020. The result of this investigation is that we have concluded that it is almost impossible to change the statutes of a Swedish foundation once it is created. The chances are extremely slim and the costs are high, regardless of the outcome.

What does this mean in practice?

* We can't remove the statute saying that the foundation must ensure that the Defold product (editor and tools) is not commercialised by a third-party.
   * I have so far not heard any loud objections to this. Defold users can release their games and monetize them any way they want.
* We will continue to enforce the non-commercialization through the software license.
   * Can we change to another license? Probably. Is it worth it? Probably not.

I do realize that this is not the answer some people were hoping for, but it is what it is.

**Comment by MetalMaxMX** [comment]
> The license is fine the way it is. You can't sell or commercialize the engine itself.
> 
> If Defold gets within 10 miles of any of the viral copyleft stuff it's Buh Bye...

I understand that for your needs and purposes you wouldn't mind the license itself. But this particular one does impedes the fact that one wouldn't be able to get this program in most software distro repositories out there, I am also very aware that most games made with Defold aren't probably going to be released under most licenses other than leaving as is by their users, but in the cases where one does wants to start an open-source project with Defold, it becomes more difficult to argue the use of an engine that does not respects all four software freedoms. 

Though, regardless of our views on the matter. It was already settled by britzl that changing the license was probably going to become a very difficult if not outright not-possible endeavor due to the statute of the Swedish foundation, which is governed by, well, Swedish law. I personally think is a bit of a shame but is what it is, and if their users are happy that way, I cannot offer much in argument either. Perhaps in some other future this topic can be tackled once more but that ultimately depends on the will of both the community and the devs anyway
