### ISSUE TITLE
Client Side Decorations on Linux

### ISSUE THREAD

**Issue by megatux** [defold/defold#4796]
Unless you disable GTK CSD, the UI becomes unusable. Clicks don't respond where they are activated. This is a common issue with Java (and others) GTK bindings, don't remember if this is related to the use of a compositor on X11.

I'm on elementaryOS, latest. Should be affecting other distros.

**Workaround:**

Start the app with the env. var to disable it:

> GTK_CSD=0 ./Defold

At least, we should document this, to avoid loosing new users.

**Comment by britzl** [comment]
Thank you for the report! This is documented in the Linux FAQ: 

https://defold.com/manuals/linux/#faq

Source: https://github.com/defold/doc/blob/master/docs/en/shared/linux-faq.md

Do you have a suggestion how to highlight it more? On the Download page?

**Comment by megatux** [comment]
Oh, I see, thx. I should have look into faq before submitting.
Is this issue only affecting ElementaryOs?
Feel free to close this issue

**Comment by britzl** [comment]
@megatux Not sure if it only affects ElementaryOS. Perhaps others as well.

I wonder if we could always set GTK_CSD=0 when launching on Linux. Or would this cause problems for other distributions?
