### ISSUE TITLE
Ubuntu's openjdk-11-jdk cannot run Editor2

### ISSUE THREAD

**Issue by mtnygard** [defold/defold#4799]
**Describe the bug (REQUIRED)**
`editor/README.md` states support for JDK 8 and JDK 11. However, using Ubuntu 18.04's default package repositories to install openjdk-11-jdk results in an error from ld.so during startup.

**To Reproduce (REQUIRED)**
1. Start with a clean Ubuntu installation (VM is acceptable)
2. Perform the setup process from `README.md`
3. Build the engine per instructions in `README.md`
4. Install JDK 11 by running `sudo apt install -y openjdk-11-jdk openjdk-11-jdk-headless`
5. Start the editor with `lein run`
5. Observe the error in the log below. The editor window does not appear and the process aborts.

**Expected behavior (REQUIRED)**
The editor should run.

**Defold version (REQUIRED):**
- As of commit 28e5eb63504 on dev

**Platforms (REQUIRED):**
 - Platforms: Linux
 - OS: Ubuntu 18.04
 - Device: Windows

**Logs (OPTIONAL):**
This is the tail end of the output from stdout/stderr:

```
2020-05-19 18:57:48.594 DEBUG default    com.defold.libs.ResourceUnpacker - unpacking '/home/mtnygard/work/defold/editor/resources/_unpack/x86_64-win32/bin/OpenAL32.dll' to 'tmp/unpack/x86_64-win32/bin/OpenAL32.dll'
2020-05-19 18:57:48.595 DEBUG default    com.defold.libs.ResourceUnpacker - unpacking '/home/mtnygard/work/defold/editor/resources/_unpack/x86_64-win32/bin/luajit-64.exe' to 'tmp/unpack/x86_64-win32/bin/luajit-64.exe'
2020-05-19 18:57:48.602 INFO  default    com.defold.libs.ResourceUnpacker - defold.unpack.path=/home/mtnygard/work/defold/editor/tmp/unpack
Inconsistency detected by ld.so: dl-lookup.c: 111: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!
```

**Workaround (OPTIONAL):**

To work around, purge the Ubuntu OpenJDK package: `sudo apt purge openjdk-11-jdk openjdk-11-jdk-headless openjdk-11-jre openjdk-11-jre-headless`

Install the OpenJDK 11 from AdoptOpenJDK, per the [instructions](https://adoptopenjdk.net/installation.html?variant=openjdk11&jvmVariant=hotspot#linux-pkg)

**Comment by vlaaad** [comment]
Hmm, I remember having these problems with ubuntu's distribution of OpenJDK, but not with the official one [here](https://jdk.java.net/archive/) — can you try that?

**Comment by mtnygard** [comment]
I can confirm that the Oracle-supplied OpenJDK 11 *does not* have the error.

**Comment by mtnygard** [comment]
If I may suggest, this is probably best handled as a documentation change. I've seen other people reporting similar problems with JOGL and Ubuntu's OpenJDK. Perhaps a warning in the Linux setup instructions would suffice.

**Comment by britzl** [comment]
@mtnygard would you mind preparing a PR with the change to the instructions? Or write a suggestion here?

**Comment by AGulev** [comment]
close as outdated
