### ISSUE TITLE
Update to emscripten 1.39

### ISSUE THREAD

**Issue by JCash** [defold/defold#4803]
We need to make it simpler to both bundle and the emscripten sdk.

Update with a package/build script for the sdk.
Update with install instructions

The big risk here is jumping to a major version without thorough vetting, but I'm confident we can all test the binary before releasing.

check list:

* [ ] package script - Darwin
* [ ] package script - Linux
* [ ] build.yml
* [ ] Extender server

**Comment by britzl** [comment]
Also refer to https://github.com/defold/defold/issues/4179

**Comment by JCash** [comment]
As in #4719 we see a size increase of about ~200kb in `js-web`, we also see a slight decrease in `wasm-web` at around -72kb.

```
EMSCRIPTEN 1.39.16

5653654 js-web/dmengine.js
5327794 js-web/dmengine_headless.js
5102687 js-web/dmengine_release.js

 316290 wasm-web/dmengine.js
2657334 wasm-web/dmengine.wasm
 208267 wasm-web/dmengine_headless.js
2546741 wasm-web/dmengine_headless.wasm
 316292 wasm-web/dmengine_release.js
2297759 wasm-web/dmengine_release.wasm

release wasm: 316292 + 2297759 = 2614051

EMSCRIPTEN 1.38.12

5474077 js-web/dmengine.js
5104304 js-web/dmengine_headless.js
4926604 js-web/dmengine_release.js

 354093 wasm-web/dmengine.js
2698482 wasm-web/dmengine.wasm
 227921 wasm-web/dmengine_headless.js
2574901 wasm-web/dmengine_headless.wasm
 353966 wasm-web/dmengine_release.js
2332974 wasm-web/dmengine_release.wasm

release wasm: 353966 + 2332974 = 2686940
```

GIven these numbers I see no reason to not go a head.

**Comment by britzl** [comment]
The decrease for wasm-web is welcome and likely what would be used the most, but it's a shame that js-web grew. Does the changelog give any hints as to why this would happen? Is it some size vs performance tradeoff?

**Comment by JCash** [comment]
Related PR:
https://github.com/defold/extender/pull/162

**Comment by JCash** [comment]
Current values using -O3:
```
Emscripten 1.38.12

4936683 dmengine_release.js
 353966 dmengine_release.wasm.js
2340041 dmengine_release.wasm

Emscripten 1.39.16

7741568 ./js-web/dmengine_release.js
 244489 ./wasm-web/dmengine_release.js
2098267 ./wasm-web/dmengine_release.wasm
```

**Comment by JCash** [comment]
Added issue for JS size increase here:
https://github.com/emscripten-core/emscripten/issues/11273
