### ISSUE TITLE
Make package_win32_sdk.sh detect the currently installed version of MSVC

### ISSUE THREAD

**Issue by subsoap** [defold/defold#4806]
**Is your feature request related to a problem? Please describe (REQUIRED):**

Currently when installing VS the version may be higher than is mentioned in the docs. Users need to manually modify package_win32_sdk.sh to bump up the version to whatever they have.

**Describe the solution you'd like (REQUIRED):**
The script should check the /c/Program Files (x86)/Microsoft Visual Studio/2019/Community/ folder for versions and pick the newest one listed there to use.

**Describe alternatives you've considered (REQUIRED):**
Without this users must edit the .sh themselves.

**Comment by subsoap** [comment]
build.py hard codes the version number for MSVC too so it should be able to detect the version if any within the packages folder? and pick the latest one from there?

**Comment by britzl** [comment]
@JCash please provide some input!

**Comment by subsoap** [comment]
It's not a huge priority but it does require people to know to edit the .py files to set the correct version numbers. 

Because currently build.py assumes to be downloading this file from a HTTP server it can't just see the files in a directory and pick the proper/latest one.

**Comment by britzl** [comment]
It would be a nice modification to `build.py` to check if `--package-path` is a URL or a file location and take appropriate action.

**Comment by JCash** [comment]
Yes, @subsoap and I discussed this feature, and while _we_ previously only needed to update this script very rarely, the actual install of MSVS is a moving target, and this feature would help newcomers settling in.

And yes, the "--package-path" fix would be another beneficial fix.

**Comment by JCash** [comment]
Nowadays, we have auto detect scripts for locally installed sdks for macos, ios, windows, linux. (See `sdk.py`)
It means that the `install_sdk` step is not necessary for building the engine, if you have Visual Studio, XCode or clang (linux) installed.

This is work in progress, but we aim to support this workflow for all platforms.
