### ISSUE TITLE
[proposal] Flutter plugin binding C++ native code using dart:ffi

### ISSUE THREAD

**Issue by iapicca** [defold/defold#4807]
**DESCRIPTION**
[Flutter](https://flutter.dev/) is a fast growing framework written in [dart](https://dart.dev/)
(recently has reached[ more stars on react native on github](https://www.reddit.com/r/FlutterDev/comments/eks1tm/flutter_now_has_more_github_stars_than_react/));
making `defold` avalable for flutter would appeal a great number of developers!

**SOLUTION**
Thanks to [dart:ffi](https://flutter.dev/docs/development/platform-integration/c-interop) should be relatively easy to use a C++ artifact inside flutter

**ALTERNATIVE**
...ignoring this feature request, I guess.

**NOTE**
the competition is not intimidating 
[flame](https://flame-engine.org/), [spritewidget](https://github.com/spritewidget/spritewidget), [unity](https://pub.dev/packages/flutter_unity_widget)
`defold` would be THE choice to go for

**Comment by fourscience** [comment]
Maybe it would be a better idea to not fully opt in for dart ffi yet, you can use the embedder to wrap around flutter, or have the same dart binding first as they have for skia :)

**Comment by britzl** [comment]
What does it mean to "make Defold available for Flutter"? What do you envision someone would be able to do if this was supported?

**Comment by iapicca** [comment]
closing as not anymore relevant
