### ISSUE TITLE
Pack more than one uniform per buffer

### ISSUE THREAD

**Issue by jhonnyking** [defold/defold#4816]
**Task (REQUIRED):**
Currently we create one uniform buffer per uniform which is a waste of performance. The vulkan spec states that 256 bytes per buffer is the minimum size req, which means we can pack most uniforms into one or two buffers when generating the shader messages. 

**Expected outcome (REQUIRED):**
This will reduce the number of descriptors needed for buffer updates, as well as reduce the uniform scratch buffer size needed in runtime.

**Comment by Jhonnyg** [comment]
Fixed-ish by implementing support for #8083
