### ISSUE TITLE
Update to new Win32 sdk package for engine build

### ISSUE THREAD

**Issue by JCash** [defold/defold#4822]
Use the same package as the extender.
This will make sure that when users use our latest version of `package_win32_sdk.sh` it should work with minimal effort.

**Comment by AGulev** [comment]
As I see it's done:
https://github.com/defold/defold/commit/68c2c2c2566fd6dc7517d5b6cc725b87aec3a19e
https://github.com/defold/extender/blob/983f9972e41b15b3afe62450b401905723e9b015/server/docker-base/Dockerfile#L158C29-L158C40
