### ISSUE TITLE
No editor menu access in tiling manager such as bspwm

### ISSUE THREAD

**Issue by 1xch** [defold/defold#4824]
**Describe the bug (REQUIRED)**
No access to menus in the editor

**To Reproduce (REQUIRED)**
1. Start editor
2. Attempt to use any top bar menu options
3. Unable to click on any menu options
4. Only see menu by holding mouse button down 

**Expected behavior (REQUIRED)**
I would expect normal access to menu options

**Defold version (REQUIRED):**
  - Version [e.g. 1.2.155]

**Platforms (REQUIRED):**
 - Platforms: [e.g. iOS, Android, Windows, macOS, Linux, HTML5]
Linux
 - OS: [e.g. iOS8.1, Windows 10, High Sierra]
 Ubuntu 19.10

I suspect this is an issue from the tiling manager I am using (bspwm), there are indications elsewhere this can happen, but no solutions. I can get some access to menus if I float the window and then move the mouse outside the editor program window slighty -- but it is suboptimal. The editor doesn't interact properly in more minimal environment like a tiling manager, this may or may not be a bug depending on your perspective. Some guidance on solving this to use the editor fully would be appreciated.

[reddit](https://www.reddit.com/r/bspwm/comments/goqlp3/no_menus_wankery_with_java_application/)

**Comment by britzl** [comment]
I have very little experience with Linux (and I don't really know what a tiling manager is) :-)

@vlaaad do you have any input?

**Comment by lincore81** [comment]
I have the same issue in i3wm, but since the editor provides keyboard shortcuts for most menu items and using a tiling wm on linux is already ridiculously niche, I think it's fine until a super geeky Linux God descends from the heavens to fix it :)

**Comment by Gaarco** [comment]
This is a [JavaFX bug](https://bugs.openjdk.java.net/browse/JDK-8251240) apparently.
There is a possible workaround in the comments at that link: adding `-Djdk.gtk.version=2` to the jvm args works on my machine with EndeavourOS and i3, and doesn't seem to introduce other problems.

**Comment by vlaaad** [comment]
IIRC idk.gtk.version does introduce an issue with drag-and-drop, I don't quite remember what breaks though

**Comment by AGulev** [comment]
> This is a [JavaFX bug](https://bugs.openjdk.java.net/browse/JDK-8251240) apparently. There is a possible workaround in the comments at that link: adding `-Djdk.gtk.version=2` to the jvm args works on my machine with EndeavourOS and i3, and doesn't seem to introduce other problems.

it was fixed in javafx 22 according to https://bugs.openjdk.java.net/browse/JDK-8251240
