### ISSUE TITLE
Releasing Defold Engine on Flathub/Snap Store

### ISSUE THREAD

**Issue by yir0n** [defold/defold#4825]
I love Defold and I believe releasing it in Flathub or Snap Store would be a great step in facilitating it's development in Linux. It would help greatly mitigating errors across Distros as well as make it easier to install and use it. I know it's not exactly difficult right now, but even for it's targeted Distro, Ubuntu, being able to install it from the Snap Store of even Gnome Software after integrating with Flatpak is very appealing for beginners in Linux and people that just are not power users (possibly artists, game designers, etc).

**Comment by subsoap** [comment]
Are there reps from Flathub/Snap Store who can assist with setup?

**Comment by subsoap** [comment]
https://github.com/flathub/flathub/wiki/App-Submission

https://snapcraft.io/docs/releasing-to-the-snap-store

**Comment by JCash** [comment]
This is not something that we will do ourselves, as the install process is already easy.
Once the editor is downloaded, it will keep itself updated. Thus, no need for a package manager.

Also, the added support burden is not to be ignored.
