### ISSUE TITLE
Adding or removing tiles from a tilemap does not update the collision shape

### ISSUE THREAD

**Issue by britzl** [defold/defold#4829]
**Describe the bug (REQUIRED)**

**To Reproduce (REQUIRED)**
1. Create a tilemap
2. Use it as a collision shape
3. Add/remove tiles
4. Notice that collision shape doesn't update

See https://forum.defold.com/t/tilemap-collisions-are-not-removed-changed-when-set-tile-is-used/64610/6?u=britzl for potential reason for this problem.

**Expected behavior (REQUIRED)**
The tilemap collision shape should update when a tile is added/removed

**Defold version (REQUIRED):**
1.2.169

**Platforms (REQUIRED):**
 All

**Minimal repro case project (OPTIONAL):**
https://forum.defold.com/t/tilemap-collisions-are-not-removed-changed-when-set-tile-is-used/64610?u=britzl

**Additional context (OPTIONAL):**
https://forum.defold.com/t/tilemap-collisions-are-not-removed-changed-when-set-tile-is-used/64610?u=britzl

**Comment by JCash** [comment]
The repro case:
https://forum.defold.com/uploads/default/original/3X/b/3/b3c01710ed2df62912d8b2d5653392a41c8b35db.zip

Looking into it, both tilemap.set_tile() result in calls to b2GridShape.
I'm thinking it's the different between a static and kinematic body, and it needs to recalculate its proxy,

**Comment by AGulev** [comment]
[SetTileCollisions.zip](https://github.com/defold/defold/files/14584198/SetTileCollisions.zip)
I can't reproduce it
