### ISSUE TITLE
Make a user config key bindings file that can swap editor shortcuts to custom user keys

### ISSUE THREAD

**Issue by subsoap** [defold/defold#4832]
**Is your feature request related to a problem? Please describe (REQUIRED):**
People want to be able to customize shortcuts.

**Describe the solution you'd like (REQUIRED):**
Allow the user to define a file which lists changes to builtin shortcut keys.

**Comment by AGulev** [comment]
I think @britzl added such an option?  https://defold.com/manuals/editor-keyboard-shortcuts/#customizing-shortcuts
