### ISSUE TITLE
Sound threading

### ISSUE THREAD

**Issue by subsoap** [defold/defold#4838]
**Is your feature request related to a problem? Please describe (REQUIRED):**
Audio playback can become distorted when loading assets or doing high CPU scripts. This requires gamedevs to aggressively mute all audio when for example loading new resources to avoid the user experiencing glitchy sounds. If the user's computer is on the slower end, glitchy audio can still be often heard through normal gameplay, this can often happen on older CPUs or older HDDs since the audio playback is interrupted by the game sim. Making audio play on its own thread would likely solve these.

**Describe the solution you'd like (REQUIRED):**
- Make sound playback on its own thread
Plus via @dapetcu21 these should be considered (and be their own issues)
https://github.com/defold/defold/issues/4837
-  making sure that even after threaded playback implementation, two sounds started in the same frame start simultaneously and sync-up sample-to-sample.
- queueing audio for gapless playback after another sound instance finishes
- being able to query song duration
- being able to query playhead position on a sound instance

https://github.com/defold/defold/blob/869a87718757bdb7bfd6ed078047fa7bfb451de9/engine/sound/README.md

**Comment by JCash** [comment]
Thanks for the proposal!

Re: "two sounds started in the same frame start simultaneously and sync-up sample-to-sample."
Is this an actual issue currently? Knowing the code, I would not have thought so.

**Comment by subsoap** [comment]
@dapetcu21 has had experience of it being unreliable afaik.

**Comment by dapetcu21** [comment]
No it isn't an an issue now. I checked. I'm just worried it might become after the threading refactor.
