### ISSUE TITLE
Make the editor stop checking for updates so often (or at least don't log it)

### ISSUE THREAD

**Issue by subsoap** [defold/defold#4840]
**Is your feature request related to a problem? Please describe (REQUIRED):**
The editor checks for updates every minute while it is open. It also logs these checks to a log file. If someone leaves the editor open it wastes bandwidth (which may matter for some users) and creates large files with 

```
2020-05-24 22:19:55.610 12637484 [Timer-0] INFO  editor.updater - {:line 283, :message "Checking for updates", :url "https://d.defold.com/editor2/channels/editor-alpha/update-v3.json"}
2020-05-24 22:19:55.953 12637827 [Timer-0] INFO  editor.updater - {:line 290, :message "No update found"}
```

**Describe the solution you'd like (REQUIRED):**
Make the editor check for updates on launch, and maybe once an hour instead of once a minute.

**Comment by britzl** [comment]
A new value in the editor preferences perhaps?

**Comment by Alfagun74** [comment]
@britzl no. Please dont make this overcomplicated. 
Once a minute is simply just too much. Just change the hardcoded value to 15, 30 or 60 minutes.
Abolutely noone benefits from that value being configurable.

**Comment by subsoap** [comment]
This line

https://github.com/defold/defold/blob/dev/editor/src/clj/editor/updater.clj#L347
60000 needs to be changed to 3600000 for  the editor to only check once per hour after the first initial fast update check.

**Comment by subsoap** [comment]
https://github.com/defold/defold/pull/5317

**Comment by britzl** [comment]
Well, yes, I agree that every minute is too much :-)

**Comment by JCash** [comment]
I think 60 minutes is fine.
If there's an urgent change that the user wants, then the user can just restart the editor, which is required anyways.

**Comment by JCash** [comment]
PR workflow note: just linking the issue with a hashtag doesn't seem to work very well in terms of actually closing the issue anymore (also, It had to be prefixed "fixes #<number>" etc).
The new preferred way is to use the "Linked Pull Requests" on the right side, which seems to work for us now.

**Comment by britzl** [comment]
> just linking the issue with a hashtag doesn't seem to work very well in terms of actually closing the issue anymore (also, It had to be prefixed "fixes #" etc)

Yeah, this is a bit strange. Sometimes it works though. Full list of keywords when referencing an issue from a PR: https://docs.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords#about-issue-references

**Comment by subsoap** [comment]
Comments from normal users /PR submitters do not work either

**Comment by subsoap** [comment]
https://github.com/defold/defold/pull/5321#pullrequestreview-526116041
