### ISSUE TITLE
Fix the unpack situation for the editor

### ISSUE THREAD

**Issue by subsoap** [defold/defold#4841]
**Is your feature request related to a problem? Please describe (REQUIRED):**
New version unpacks are still left over after updates. It's fine to do for the last 2-3 versions, but older versions should not require manual deletion.

**Describe the solution you'd like (REQUIRED):**
Let the user define how many older versions to keep. Have it default to maybe 2 older versions. Have an option to never delete older versions when updating for those who do want to hoard.

**Describe alternatives you've considered (REQUIRED):**
The alternative is to manually delete the old, unneeded unpacks.

**Comment by subsoap** [comment]
Was this already fixed in a recent version?

**Comment by britzl** [comment]
I don't think so. I thought we already cleaned up old installs. :-)

**Comment by subsoap** [comment]
I just deleted a few older versions from the folder a few days ago from the folder but it might have been much older versions. When updating to the last version I didn't notice left over files so I'll close this for now.
