### ISSUE TITLE
Add links in the editor menu to support Defold

### ISSUE THREAD

**Issue by subsoap** [defold/defold#4844]
**Is your feature request related to a problem? Please describe (REQUIRED):**

This should be added in the editor to encourage supporting. It doesn't need to be a nag, it just needs to be present in the menus.

```
Help ->
...
Search Issues
----
  Donate ->
    Defold Foundation -> https://defold.com/donate/
    Sponsor on Github -> https://github.com/sponsors/defold
    Support on Patreon -> https://www.patreon.com/defold/
    One Time Donations -> Paypal...
  About

```
**Describe the solution you'd like (REQUIRED):**
Add the related links to the editor's menus.

The only thing that needs to be edited is 
/editor/src/clj/editor/app_view.clj

The paypal link should go to https://defold.com/donate/paypal/ and not directly to paypal's service, then that page can forward to the paypal service. So this would be needed to setup too. It's much easier to update the site than the editor if the link ever needs to be updated. Also I noticed that the paypal button goes to a Swedish language store, may be better to make it English language store as a default or just not set the language field? Not sure.

Another option is making the paypal link direct to https://defold.com/community-donations/ since that has a button there, but the store language is still a potential issue.

If this is acceptable I'll take care of the first version of these changes.

**Comment by subsoap** [comment]
Another issue I noticed is on here https://defold.com/community-donations/ it's not good to use Patreon's embed code because it will often break and people will randomly not see the button, so making a static link is better.

**Comment by britzl** [comment]
@subsoap Great suggestions. The Patreon button on the website has been replaced with a static one.

I think we'll go for a single Donate menu item which links to the site.
