### ISSUE TITLE
Run While Iconified error

### ISSUE THREAD

**Issue by GreenArrow18** [defold/defold#4845]
Steps to reproduce:

1. Start any project (or an empty clean proj)
2. Check ‘Run While Iconified’ in project settings
3. Run the app: Project/Build
4. Minimize the app window

I am getting the following error continously:
`
ERROR:SCRIPT: /builtins/render/default.render_script:81: argument #1 contains one or more values which are not numbers: vmath.matrix4(inf, 0, 0, nan, 0, inf, 0, nan, 0, 0, -1, -0, 0, 0, 0, 1)
stack traceback:
	[C]: in function 'set_projection'
	/builtins/render/default.render_script:81: in function </builtins/render/default.render_script:57>
`

5. Restore the window, and the errors will be gone… until you minimize the window again.

Tested on: Defold 1.2.169, Windows 10

**Comment by subsoap** [comment]
Posted a workaround https://forum.defold.com/t/run-while-iconified-error/65340/4?u=pkeod
