### ISSUE TITLE
Editor exception when opening an atlas or collection (jogamp.opengl.es1.GLES1Impl)

### ISSUE THREAD

**Issue by topazas** [defold/defold#4851]
### Expected behaviour
Editor is visible ?

### Actual behaviour
Error message.

### Steps to reproduce
Double click main.atlas on a new mobile project
<hr/>

<table>
<tr><td>Build time</td><td>2020-05-26T07:18:13.818208</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>2770594b5f0415dcd08dd1a83d9f3bfdf1f8a5cc</td></tr>
<tr><td>Defold engine sha</td><td>4ebe7a1d548eae2398717ed46f9d7d1b103d5503</td></tr>
<tr><td>Defold version</td><td>1.2.169</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"58b260234f264e3487f1b6efd4044d68"'>58b260234f264e3487f1b6efd4044d68</a></td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) UHD Graphics 630 (CFL GT2)</td></tr>
<tr><td>GPU Driver</td><td>OpenGL ES-CM 1.1 Mesa 20.0.4</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.4.0-31-generic</td></tr>
<table>

**Comment by eangelin** [comment]
class jogamp.opengl.es1.GLES1Impl cannot be cast to class com.jogamp.opengl.GL2ES2 (jogamp.opengl.es1.GLES1Impl and com.jogamp.opengl.GL2ES2 are in unnamed module of loader 'app')

**Comment by eangelin** [comment]
See also https://github.com/defold/editor2-issues/issues/2959

**Comment by britzl** [comment]
So what is the deal here? Is the solution this one:

```
$ export MESA_GL_VERSION_OVERRIDE=3.1
$ ./Defold
```

As mentioned in the Linux FAQ: https://defold.com/manuals/linux/#faq

**Comment by britzl** [comment]
> Does not help

Did you get it working? Which version did you try?

You can try running with software rendering:

```bash
$ LIBGL_ALWAYS_SOFTWARE=1 ./Defold
```

**Comment by rehhouari** [comment]
> > Does not help
> 
> Did you get it working? Which version did you try?
> 
> You can try running with software rendering:
> 
> ```shell
> $ LIBGL_ALWAYS_SOFTWARE=1 ./Defold
> ```

This is the only solution that works! tried all other fixes out there, same issue.

OS: Ubunut 20.04
Drivers: Latest from [oibaf's PPA](https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers)
```
OpenGL version string: 4.6 (Compatibility Profile) Mesa 21.2.0-devel (git-fefd853 2021-05-07 focal-oibaf-ppa)
```

In the [FAQ](https://defold.com/manuals/linux/) it's under "my drivers are outdated" which is not the case here, i think?
Could be that my device which have a an `Intel UHD Graphics 605` Integrated GPU & `Intel Celeron N4000 (2) @ 2.100GHz` CPU which is unsupported?

**Comment by britzl** [comment]
Happy to hear you got it working. Software rendering will not be as performant though, but at least you are able to use the editor now.
