### ISSUE TITLE
Editor crashed when I want to change tab.

### ISSUE THREAD

**Issue by Ushiosan23** [defold/defold#4852]
### Expected behaviour
Change between editor tabs.

### Actual behaviour
When I try to change tab while the file is saving, the editor crashed.

### Steps to reproduce
- Write anything in one file and save changes
- Change to another tab in less than 3 seconds

<hr/>

<table>
<tr><td>Build time</td><td>2020-05-26T07:18:40.400730</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>2770594b5f0415dcd08dd1a83d9f3bfdf1f8a5cc</td></tr>
<tr><td>Defold engine sha</td><td>4ebe7a1d548eae2398717ed46f9d7d1b103d5503</td></tr>
<tr><td>Defold version</td><td>1.2.169</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"c0dc49315aa84a59bec282005fdb9203"'>c0dc49315aa84a59bec282005fdb9203</a></td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 520</td></tr>
<tr><td>GPU Driver</td><td>4.4.0 - Build 20.19.15.4390</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
javafx.scene.control.skin.TabPaneSkin in stopDrag at line 2216

**Comment by subsoap** [comment]
> javafx.scene.control.skin.TabPaneSkin in stopDrag at line 2216

Why does it only impact having a drop down open while clicking the open files panel and not any other panel?

**Comment by subsoap** [comment]
Is this issue related?

https://bugs.openjdk.java.net/browse/JDK-8237372

It says it is fixed in FX14, apparently 14.0.2.1 was released last month. Maybe possible to use this version now?

**Comment by subsoap** [comment]
Java friend says "should work with Zulu JDK14 and OpenJFX 14"

**Comment by subsoap** [comment]
For Science I tested 

https://www.azul.com/downloads/zulu-community/?os=windows&architecture=x86-64-bit&package=jdk-fx

With the FX version I got

```
java.lang.reflect.InaccessibleObjectException: Unable to make field java.lang.Runnable javafx.scene.control.skin.MenuBarSkin.firstMenuRunnable accessible: module javafx.controls does not "opens javafx.scene.control.skin" to unnamed module @77751d80
```

When trying to use it, probably because of conflict with bundled FX version?

With non FX version I still get the same dropdown error, but overall the editor feels much more snappy so when that update can happen it should be a nice instant improvement the whole community will enjoy!!!

Now I'm trying to replace the JavaFX version bundled in the Defold.jar with one from https://gluonhq.com/products/javafx/ ...

**Comment by bobdaduck** [comment]
Have this exception happen to me all the time, feels very unprofessional

**Comment by subsoap** [comment]
It's apparently fixed in the latest JavaFX version so it just needs to be updated / tested.

**Comment by britzl** [comment]
The fix is being tested in this branch: https://github.com/defold/defold/tree/DEFEDIT-javafx-15

My preliminary testing shows everything to be working as expected.
