### ISSUE TITLE
Detect connected gamepad type

### ISSUE THREAD

**Issue by rsaienz** [defold/defold#4856]
There should be some way to obtain the name, as in the file default.gamepads, of the controller related to the gamepad-connected event.

This is needed if a button icon (or a text) has to be shown on screen; indeed different types of gamepads give different names to their buttons.

**Comment by JCash** [comment]
Before anyone starts with this, let me see if I cannot merge this info back from our private branch into public dev.

**Comment by JCash** [comment]
The actual Lua table is contructed in `comp_script.cpp`, in `CompScriptOnInput`.
