### ISSUE TITLE
Editor doesn't start on Kubuntu

### ISSUE THREAD

**Issue by alpha6** [defold/defold#4867]
**Describe the bug (REQUIRED)**
Editor doesn't start on Kubuntu 18.04

**To Reproduce (REQUIRED)**
1. Download and unpack distributive
2. chmod +x ./Defold
3. ./Defold
INFO:TOOLS: Launcher version 4ebe7a1d548eae2398717ed46f9d7d1b103d5503
DEBUG:TOOLS: arg 0: ./packages/jdk11.0.1/bin/java
DEBUG:TOOLS: arg 1: -cp
DEBUG:TOOLS: arg 2: ./packages/defold-c5b4b2e62b3147e6ddb7c120d38c764374fef741.jar
DEBUG:TOOLS: arg 3: -Dfile.encoding=UTF-8
DEBUG:TOOLS: arg 4: -Djna.nosys=true
DEBUG:TOOLS: arg 5: -Ddefold.launcherpath=./Defold
DEBUG:TOOLS: arg 6: -Ddefold.resourcespath=.
DEBUG:TOOLS: arg 7: -Ddefold.version=1.2.169
DEBUG:TOOLS: arg 8: -Ddefold.editor.sha1=c5b4b2e62b3147e6ddb7c120d38c764374fef741
DEBUG:TOOLS: arg 9: -Ddefold.engine.sha1=4ebe7a1d548eae2398717ed46f9d7d1b103d5503
DEBUG:TOOLS: arg 10: -Ddefold.buildtime=2020-05-31T07:49:01.074147
DEBUG:TOOLS: arg 11: -Ddefold.channel=editor-alpha
DEBUG:TOOLS: arg 12: -Djava.net.preferIPv4Stack=true
DEBUG:TOOLS: arg 13: -Dsun.net.client.defaultConnectTimeout=30000
DEBUG:TOOLS: arg 14: -Dsun.net.client.defaultReadTimeout=30000
DEBUG:TOOLS: arg 15: -Djogl.texture.notexrect=true
DEBUG:TOOLS: arg 16: -Dglass.accessible.force=false
DEBUG:TOOLS: arg 17: --illegal-access=warn
DEBUG:TOOLS: arg 18: --add-opens=java.base/java.lang=ALL-UNNAMED
DEBUG:TOOLS: arg 19: --add-opens=java.desktop/sun.awt=ALL-UNNAMED
DEBUG:TOOLS: arg 20: --add-opens=java.desktop/sun.java2d.opengl=ALL-UNNAMED
DEBUG:TOOLS: arg 21: --add-opens=java.xml/com.sun.org.apache.xerces.internal.jaxp=ALL-UNNAMED
DEBUG:TOOLS: arg 22: -Xmx8589934592
DEBUG:TOOLS: arg 23: com.defold.editor.Main
DEBUG:TOOLS: arg 24: (null)
FATAL:TOOLS: Failed to launch application:

**Defold version (REQUIRED):**
  - Version 1.2.169

**Platforms (REQUIRED):**
 - Platforms: Linux
 - OS: Kubuntu 18.04

**Comment by britzl** [comment]
> FATAL:TOOLS: Failed to launch application:

Is there a stack trace or any additional information shown after this line?

**Comment by vlaaad** [comment]
Error in your own launcher happens because you use JDK from the package manager, which always gives me these errors. You should use `java` from our shipped JDK (which is the same as `11.0.1` OpenJDK that can be downloaded from [here](https://jdk.java.net/archive/)).

**Comment by alpha6** [comment]
Thank you for the advice. I've look at the shipped jdk and found that java binary lost executable flag.

```
chmod +x ./packages/jdk11.0.1/bin/java
```
resolved my problem

**Comment by britzl** [comment]
Oh, we should be able to make sure the executable flag is set.

**Comment by vlaaad** [comment]
But it does now, isn't it? The thing is, there is no concept of permissions in archive format, there are extra bits that archivers usually — but not always — use to preserve executable flags. Maybe Kubuntu's default archiver does not used these extra bits to mark files as executable? Marking `Defold` as executable shouldn't be needed either...

**Comment by vlaaad** [comment]
Checked on Ubuntu that latest Defold release is unarchived with correct executable flags on `Defold` and `java` files. 

@alpha6 do you have similar problems when extracting other archives with executable files on Kubuntu?

**Comment by alpha6** [comment]
It's a problem with mc, I suppose.

I extracted package with default GUI archiver (Ark) and have no problems with executable flags.
Then I checked mc and all flags were lost.
