### ISSUE TITLE
Colorslide tutorial on macOS crashes

### ISSUE THREAD

**Issue by paulhargreaves** [defold/defold#4895]
**Describe the bug (REQUIRED)**
In the tutorial:

```
Unfortunately there is an instant error. The console says:

ERROR:GAMEOBJECT: The collection 'default' could not be created since there is 
already a socket with the same name.
WARNING:RESOURCE: Unable to create resource: /main/level_1/level_1.collectionc
ERROR:GAMESYS: The collection /main/level_1/level_1.collectionc could not be loaded.
```

But on MacOS what actually happens is:
```
ERROR:GAMEOBJECT: The collection 'default' could not be created since there is already a socket with the same name.
INFO:CRASH: Successfully wrote Crashdump to file: /Users/paulhargreaves/Library/Application Support/Defold/_crash
ERROR:CRASH: CALL STACK:

# 0 pc   0x137405fd MetadataUtilities _sigtramp+29
# 1 pc      0x24d9e dmengine _ZN12dmGameObject23UnloadPropertyResourcesEPN10dmResource16SResourceFactoryER7dmArrayIPvE+14
# 2 pc      0x2af50 dmengine _ZN12dmGameObjectL16AcquireResourcesEPKcPN10dmResource16SResourceFactoryEPNS_8RegisterEPN15dmGameObjectDDF14CollectionDescES1_PPNS_16CollectionHandleE+1840
# 3 pc      0x2a790 dmengine _ZN12dmGameObject19ResCollectionCreateERKN10dmResource20ResourceCreateParamsE+48
# 4 pc      0x33029 dmengine _ZN10dmResource3GetEPNS_16SResourceFactoryEPKcPPv+2137
# 5 pc      0x3f775 dmengine _ZN12dmGameSystem28CompCollectionProxyOnMessageERKN12dmGameObject24ComponentOnMessageParamsE+597
# 6 pc      0x1cd7c dmengine _ZN12dmGameObject24DispatchMessagesFunctionEPN9dmMessage7MessageEPv+1820
# 7 pc     0x1ebc85 dmengine _ZN9dmMessage16InternalDispatchEyPFvPNS_7MessageEPvES2_b+693
# 8 pc      0x22ab3 dmengine _ZN12dmGameObjectL16DispatchMessagesEPNS_10CollectionEPyj+195
# 9 pc      0x1baa2 dmengine _ZN12dmGameObject4InitEPNS_16CollectionHandleE+322
#10 pc       0x4296 dmengine _ZN8dmEngine4InitEPNS_6EngineEiPPc+7990
#11 pc       0x5bc5 dmengine _ZN8dmEngine6LaunchEiPPcPFvPNS_6EngineEPvES6_S4_+133
#12 pc       0x601f dmengine _Z11engine_mainiPPc+143
```

This also triggers MacOS to pop up a Defold quit unexpectedly window with Report... tab, and on a subsequent launches there is a new warning:
`The last time you opened Defold, it unexpectedly quit while reopening windows. Do you want to try to reopen its windows again?`

**Expected behaviour (REQUIRED)**
Either change the tutorial so that it properly reflects what happens, or fix whatever causes the crash so that it doesn't crash.

**Defold version (REQUIRED):**
  - Version 1.2.169

**Platforms (REQUIRED):**
 - Platforms: MacOS
 - OS: 10.15.6
 - Device: MacOS

**To Reproduce (REQUIRED)**
Launch the tutorial and run through to the step with the socket default change.

**Comment by britzl** [comment]
@paulhargreaves can you please share a zip of the project in the current state where it crashes?

The problem seems to come from the fact that two collections have been given the same id. If you open a collection and click on the root of the collection in the outline there's an id/name field in the properties panel. It defaults to "default". You can not have collections loaded (using collection proxies or as bootstrap collection) at the same time if they have the same id.

**Comment by paulhargreaves** [comment]
[Colorslide tutorial.zip](https://github.com/defold/defold/files/4756545/Colorslide.tutorial.zip)
Yes, I agree it's the double 'default'. That's what the tutorial is explaining, but the way the engine handles it is different to how the tutorial describes, and seems that at least on MacOS that it's crashing, rather than just failing to run properly.
