### ISSUE TITLE
Beta (possibly) broke Windows NE builds

### ISSUE THREAD

**Issue by dapetcu21** [defold/defold#4903]
**Describe the bug (REQUIRED)**
I got this build error from a work colleague. ~Will verify later tonight (I'm now on macOS and I don't want to reboot to Windows just yet).~

*Update: I tried a Windows bundle on macOS with `6e6a4befb9406944cc9874b230510a438e071515` and it worked just fine. ~Maybe the extender server was mid-deploy or something? I'll close this if I can't repro while building from the editor in Windows.~*

*Update 2: I asked him to try again and the editor build still fails for him on Windows with `6e6a4befb9406944cc9874b230510a438e071515`.*

*Update 3: I can repro as well on Windows. I can bundle just fine, I just can't run a DefOS project from the editor.*

Since that error is in an include way before DefOS gets to do anything (it just includes DefoldSDK), I suspect it's not something to do with DefOS, but I might be wrong.

![QAsUVDm](https://user-images.githubusercontent.com/428060/84419970-091d4480-ac22-11ea-8f45-d5ee22fea226.png)
**To Reproduce (REQUIRED)**
Build this project? Maybe??? https://github.com/dapetcu21/crit-boilerplate

**Expected behavior (REQUIRED)**
Not crash.

**Defold version (REQUIRED):**
beta `c01806afb`, also `6e6a4befb9406944cc9874b230510a438e071515`

**Platforms (REQUIRED):**
 - Platforms: Windows
 - OS: Win10
 - Device: A computer

**Comment by JCash** [comment]
Hmm, strange. The file does exist, but I guess something is wrong with the include paths.
Can you get access to the user's log.txt? It should output the failing command line.

**Comment by dapetcu21** [comment]
Here's the log:
```
clang++ -target x86_64-pc-win32-msvc -m64 -g -gcodeview -DDLIB_LOG_DOMAIN="DEFOS" -DDM_PLATFORM_WINDOWS -DLUA_BYTECODE_ENABLE_64 -D_CRT_SECURE_NO_WARNINGS -D_WINSOCK_DEPRECATED_NO_WARNINGS -D__STDC_LIMIT_MACROS -DWINVER=0x0600 -DWIN32  -O2 -Wall -Werror=format -fvisibility=hidden  -isystem /opt/platformsdk/Win32/MicrosoftVisualStudio2019/VC/Tools/MSVC/14.25.28610//atlmfc/include -isystem /opt/platformsdk/Win32/WindowsKits/10//Include/10.0.18362.0/ucrt -isystem /opt/platformsdk/Win32/WindowsKits/10//Include/10.0.18362.0/winrt -isystem /opt/platformsdk/Win32/WindowsKits/10//Include/10.0.18362.0/um -isystem /opt/platformsdk/Win32/WindowsKits/10//Include/10.0.18362.0/shared  -Iupload/defos/include/ -Iupload/  -I/var/extender/sdk/6e6a4befb9406944cc9874b230510a438e071515/defoldsdk//include -I/var/extender/sdk/6e6a4befb9406944cc9874b230510a438e071515/defoldsdk//sdk/include  upload/defos/src/defos.cpp -c -o build/defos.cpp_0.o
In file included from upload/defos/src/defos.cpp:8:
In file included from /var/extender/sdk/6e6a4befb9406944cc9874b230510a438e071515/defoldsdk//include/dmsdk/sdk.h:33:
In file included from /var/extender/sdk/6e6a4befb9406944cc9874b230510a438e071515/defoldsdk//include/dmsdk/graphics/graphics_native.h:37:
In file included from /opt/platformsdk/Win32/WindowsKits/10//Include/10.0.18362.0/um/Windows.h:171:
In file included from /opt/platformsdk/Win32/WindowsKits/10//Include/10.0.18362.0/shared/windef.h:24:
In file included from /opt/platformsdk/Win32/WindowsKits/10//Include/10.0.18362.0/shared/minwindef.h:182:
In file included from /opt/platformsdk/Win32/WindowsKits/10//Include/10.0.18362.0/um/winnt.h:105:
/opt/platformsdk/Win32/WindowsKits/10//Include/10.0.18362.0/shared/kernelspecs.h:36:10: fatal error: 'DriverSpecs.h' file not found
#include "DriverSpecs.h"
         ^~~~~~~~~~~~~~~
1 error generated.
```

**Comment by dapetcu21** [comment]
Nevermind. I was building using build.defold.com instead of build-stage.defold.com. I keep making this mistake. Building with a version of bob that doesn't exist on the extender server should be an error. I'll open another issue for this.

**Comment by JCash** [comment]
I found the logs in the release server logs.

Does it work if you use the https://build-stage.defold.com server instead?

**Comment by JCash** [comment]
Yes, it's annoying and error prone, and we don't want to spend time on those things.
I'll try to come up with something.
