### ISSUE TITLE
Failed to connect to debugger

### ISSUE THREAD

**Issue by JustAPotota** [defold/defold#4904]
### Expected behaviour
Building and starting my game with the debugger attached
### Actual behaviour
My game doesn't start and I get an error pop-up:
![error](https://user-images.githubusercontent.com/43710172/84420956-73ad9080-abe0-11ea-8a68-1ec9db59f79d.png)
### Steps to reproduce
Select `Debug > Start / Attach` from the top menu
### Additional notes
The console gives the following output when following the steps above:
```
INFO:DLIB: Log server started on port 53596
WARNING:DLIB: No IP found for local hostname Mac-mini.local. Fallbacks to localhost
INFO:ENGINE: Engine service started on port 53609
INFO:ENGINE: Defold Engine 1.2.170 (6e6a4be)
INFO:ENGINE: Loading data from: build/default
INFO:ENGINE: Initialised sound device 'default'

DEBUG:SCRIPT: Listening for debugger on 0.0.0.0
```
<hr/>

<table>
<tr><td>Build time</td><td>2020-06-11T15:55:59.343152</td></tr>
<tr><td>Defold channel</td><td>beta</td></tr>
<tr><td>Defold editor sha</td><td>6e6a4befb9406944cc9874b230510a438e071515</td></tr>
<tr><td>Defold engine sha</td><td>6e6a4befb9406944cc9874b230510a438e071515</td></tr>
<tr><td>Defold version</td><td>1.2.170</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"c72377b1ada747388f135b99556713f9"'>c72377b1ada747388f135b99556713f9</a></td></tr>
<tr><td>GPU</td><td>Intel HD Graphics 4000 OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-12.4.7</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.14.2</td></tr>
<table>

**Comment by britzl** [comment]
Some questions:

* Does this happen for all projects, even an empty one?
* Are you using any extensions or app manifest?
* What kind of network are you connected to? A normal home network? Any VPN active?
* Any antivirus software or something that might prevent the connection?

**Comment by JustAPotota** [comment]
> Does this happen for all projects, even an empty one?

I get the same error on a freshly downloaded empty project

> Are you using any extensions or app manifest?

Extensions:
* https://github.com/britzl/defold-orthographic/archive/2.9.2.zip
* https://github.com/britzl/monarch/archive/3.0.2.zip
* https://github.com/britzl/defold-input/archive/2.5.1.zip
* https://github.com/britzl/defold-metrics/archive/master.zip
* https://github.com/subsoap/defstring/archive/master.zip
* https://github.com/subsoap/defos/archive/v2.4.0.zip
* https://github.com/rgrams/rendercam/archive/v1.0.2.zip

No custom app manifest

> What kind of network are you connected to? A normal home network? Any VPN active?

Just my home network via Ethernet, no VPNs.

> Any antivirus software or something that might prevent the connection?

The only program that I can think of that might cause this is [Folding@home](https://foldingathome.org/), but messing around with its settings didn't fix the issue.

------

Something I forgot to mention in my first post is that building the game and *then* attaching the debugger pops up a different error:
![another error](https://user-images.githubusercontent.com/43710172/84517356-cd6f9280-ac94-11ea-9f02-f6affad51534.png)
Full text: `Server returned HTTP response code: 400 for URL: http://127.0.0.1:56802/post/@system/run_script`

It also prints the following in the console:
```
ERROR:ENGINE: Too large message
WARNING:DLIB: Unsupported status code: 400
```

**Comment by hapass** [comment]
I actually was never able to start/attach on my mac also :) I always do build instead.

**Comment by britzl** [comment]
@JustAPotota do you always get the "Too large message" error?

@JCash any idea what could be causing this?

**Comment by JustAPotota** [comment]
The "Too large message" error happens every time I try to attach a debugger to a running game in 1.2.170. I went back and tried some earlier versions from Github (163-169) and all of them gave the same error when starting with the debugger, but attaching it after building works just fine.

**Comment by dapetcu21** [comment]
This sounds like two different issues. I've been getting the "Too large" message as well on 1.2.170, but starting the game with the debugger already attached seems to work.

**Comment by polycursegames** [comment]
> I actually was never able to start/attach on my mac also :) I always do build instead.

Same here.

**Comment by britzl** [comment]
This is being fixed. It should actually work in the latest editor if I'm not mistaken.

**Comment by polycursegames** [comment]
> This is being fixed. It should actually work in the latest editor if I'm not mistaken.

Still an issue, for me at least.

<img width="1040" alt="Screen Shot 2020-07-21 at 5 23 13 PM" src="https://user-images.githubusercontent.com/46680191/88108540-098cf180-cb77-11ea-85a4-eaccdeb12dab.png">

**Comment by britzl** [comment]
Thanks. We'll look into it.

**Comment by JustAPotota** [comment]
Can confirm that both issues still occur on the latest version
![Screen Shot 2020-07-22 at 4 16 09 PM](https://user-images.githubusercontent.com/43710172/88229619-aa8eb180-cc36-11ea-9603-fd3e62a502e7.png)

**Comment by britzl** [comment]
@JustAPotota are you still experiencing problems with the debugger? We've done changes to our socket connection code which I'm hoping has solved this issue, at least from 1.2.174.

**Comment by JustAPotota** [comment]
Yes, both issues seem to have been fixed in the latest beta. Strange thing is, launching the game with the debugger now also works on 1.2.171. I don't remember changing anything on my system that would affect it.

**Comment by britzl** [comment]
That is good to hear! Thanks.
