### ISSUE TITLE
Display profiles change value

### ISSUE THREAD

**Issue by Snyrch** [defold/defold#4906]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2020-06-12T07:52:29.687304</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>0bca0e3b159cb482c0956befa872c259ede800bd</td></tr>
<tr><td>Defold engine sha</td><td>4ebe7a1d548eae2398717ed46f9d7d1b103d5503</td></tr>
<tr><td>Defold version</td><td>1.2.169</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"3a115859c2b542da97b03dfb5ca25abb"'>3a115859c2b542da97b03dfb5ca25abb</a></td></tr>
<tr><td>GPU</td><td>Intel(R) UHD Graphics 630</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 - Build 26.20.100.7463</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
class java.lang.NullPointerException 
com.sun.javafx.scene.control.behavior.TableViewBehaviorBase in activate at line 898

**Comment by britzl** [comment]
This has been solved thanks to a JavaFX update
