### ISSUE TITLE
Colorslide tutorial missing step to add 'SELECT LEVEL'

### ISSUE THREAD

**Issue by paulhargreaves** [defold/defold#4914]
**Describe the bug (REQUIRED)**
README.md misses the step to add 'SELECT LEVEL'.

**To Reproduce (REQUIRED)**
1. Run through README.md steps until 'The level selection screen'
2. Notice the image after 'Repeat the above steps' has text with 'SELECT LEVEL' on it, but looking above and below there is no steps to do this.

**Expected behavior (REQUIRED)**
Add the steps required. Not exactly difficult to figure out (add a text node) but still would be nice for the README to be complete.

**Defold version (REQUIRED):**
  - Version 1.2.169

**Platforms (REQUIRED):**
 - Platforms: NA - it's the tutorial, but running on Mac
 - OS: 10.15.5
 - Device: Mac

**Minimal repro case project (OPTIONAL):**
[Colorslide tutorial.zip](https://github.com/defold/defold/files/4777028/Colorslide.tutorial.zip)

**Screenshots (OPTIONAL):**
<img width="903" alt="image" src="https://user-images.githubusercontent.com/1288695/84601494-67dbfb80-ae78-11ea-8e1c-96b15a6c4ec9.png">

**Comment by britzl** [comment]
Thanks. Updated the readme: https://github.com/defold/tutorial-colorslide/commit/7cf60ca342d77bf9fb8483a2b5e3c0b2df7245fd
