### ISSUE TITLE
Chinese localization of the editor interface

### ISSUE THREAD

**Issue by txj-mssl** [defold/defold#4915]
I'm interested in defold.
My English is not good, but I want to try to localize the editor interface in Chinese. What should I do? Is there a simple way to do it?
Can my get some help?

**Comment by txj-mssl** [comment]
Translate the editor interface into Chinese

**Comment by britzl** [comment]
The editor is not set up for easy localization yet I'm afraid.

**Comment by txj-mssl** [comment]
Godot 4.0 has Po files that can be easily translated into Chinese

**Comment by dougen** [comment]
Most of the manuals have been translated into Chinese, and I think translate the API into Chinese is more useful than the editor interface. 
我觉得编辑器界面的中文化远远没有中文文档那么重要。

**Comment by britzl** [comment]
We would like to offer translations of both the editor and the API documentation. I'll spend some time investigating how to make this happen.

**Comment by CocosGames** [comment]
The Editor doesn't speak much. The manuals are on me. The API... I'll think about it.

**Comment by CocosGames** [comment]
![image](https://user-images.githubusercontent.com/42052366/107872124-db8c4780-6ee2-11eb-925a-08a3279b66fd.png)

How about this.

**Comment by txj-mssl** [comment]
Engine developer, what's the latest news on this issue? You've been studying for a long time.

**Comment by txj-mssl** [comment]
@britzl

**Comment by txj-mssl** [comment]
I think you forgot about it.

**Comment by CocosGames** [comment]
> I think you forgot about it.

API's here: https://github.com/CocosGames/DefoldAPI_zh_CN
It's half-finished, I don't have time to finish it, fork it and continue if you like.

**Comment by subsoap** [comment]
Defold editor still has a lot of localization strings baked in the source. These all need to be externalized to a single file. Anyone could work on this to make it happen. Then translations of the editor can relatively easily be contributed.

**Comment by britzl** [comment]
Duplicate of https://github.com/defold/defold/issues/5453
