### ISSUE TITLE
Obtaining contact area ellipse radii on touch screen tap events

### ISSUE THREAD

**Issue by TillCity** [defold/defold#4923]
**The Problem**
There are times when it isn't just enough to know that a user has tapped a point on the screen but also _how_ the point was tapped.  In a different environment (HTML5 + JS) I track normalized contact area ellipse radii to keep track of how the user is probably feeling - check out [this article](https://bura.brunel.ac.uk/bitstream/2438/7189/2/Fulltext.pdf) for some background on how this can be done.

**The Solution**
The ability to report contact ellipse radii as part of the touch/tap event has been part of the HTML5 spec for a while now and is well implemented by browsers such as Chrome and Safari.  However, the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/Touch) still label this as experimental technology

On mobile devices these browsers use the APIs provided for the purpose by their respective host platforms

1. **Android**: [https://developer.android.com/reference/android/view/MotionEvent](https://developer.android.com/reference/android/view/MotionEvent)
2. **iOS**:  [ https://developer.apple.com/documentation/uikit/uitouch](https://developer.apple.com/documentation/uikit/uitouch)

**Alternatives:**
This is useful supplemental information for assessing user mood.  Other user generated metrics - e.g. the jerkiness of their device movements (first derivative of the acceleration) - also help in such assessment

**Context:**
While  I am sure that there are games where such information could be put to good use I am not primarily a games developer.  In a different context I have used this to tailor the information presented to the user to their current mood (assessment)

**Comment by britzl** [comment]
Thank you for the feature request. We're hesitant to add anything to the engine core that doesn't have an immediate use for game developers. How could this put to use in a game?

**Comment by britzl** [comment]
No additional information provided. Closing.
