### ISSUE TITLE
Raycast doesn't detect collision object that it starts inside of

### ISSUE THREAD

**Issue by JustAPotota** [defold/defold#4933]
**Describe the bug (REQUIRED)**
When creating a raycast via `physics.raycast()`, it won't detect a collision object that it starts inside of.

**To Reproduce (REQUIRED)**
1. Set up a collection with a game object
2. Create a collision object and attach it to the game object
3. Attach a script to the game object that spawns a raycast whose start point is inside of the collision object
4. Run game

**Expected behavior (REQUIRED)**
`physics.raycast()` should detect an intersection with the collision object

**Defold version (REQUIRED):**
![Screen Shot 2020-06-18 at 3 00 57 PM](https://user-images.githubusercontent.com/43710172/85066419-8aba2880-b174-11ea-9958-d0ef32fb5b0c.png)

**Platforms (REQUIRED):**
Only tested on MacOS 10.14.2, likely gives the same result on other platforms

**Minimal repro case project (OPTIONAL):**
[Raycast Test.zip](https://github.com/defold/defold/files/4800946/Raycast.Test.zip)
Use arrow keys to move the ray around

**Screenshots (OPTIONAL):**
Raycast goes through the collision object and detects it, all is well
![Screen Shot 2020-06-18 at 3 05 51 PM](https://user-images.githubusercontent.com/43710172/85066888-61e66300-b175-11ea-880c-446644de27cd.png)

The start point of the raycast is inside the collision object and doesn't detect it
![Screen Shot 2020-06-18 at 3 06 02 PM](https://user-images.githubusercontent.com/43710172/85066938-7591c980-b175-11ea-953f-dba272ee59e4.png)

The end point of the raycast is inside the collision object and detects it
![Screen Shot 2020-06-18 at 3 06 11 PM](https://user-images.githubusercontent.com/43710172/85066980-89d5c680-b175-11ea-88ac-0b99801c1cef.png)

**Comment by JCash** [comment]
This is a limitation of Box2D, and not something that we will add support for.

https://box2d.org/documentation/classb2_world.html#aa9955d94a254253997daaf16ce77bab6

"b2World::RayCast(): Ray-cast the world for all fixtures in the path of the ray. Your callback controls whether you get the closest point, any point, or n-points. The ray-cast ignores shapes that contain the starting point. "

**Comment by britzl** [comment]
Added a note about this limitation to the Physics manual: https://defold.com/manuals/physics/#ray-casts
