### ISSUE TITLE
SetLinearVelocity for box2d

### ISSUE THREAD

**Issue by AGulev** [defold/defold#4940]
**Is your feature request related to a problem? Please describe (REQUIRED):**

>I can’t set the linear velocity to a physic body? How to make a proper jump in this case?

https://forum.defold.com/t/zoom-be-my-new-game/64864

**Describe the solution you'd like (REQUIRED):**
Possibility to set Linear Velocity

**Comment by JCash** [comment]
Don't forget about the 3D counter part.
Setting these types of properties should be possible to do for both versions.

**Comment by AGulev** [comment]
duplicate https://github.com/defold/defold/issues/4170
