### ISSUE TITLE
The 9-slicing on GUI box node doesn't seem to work at all

### ISSUE THREAD

**Issue by hapass** [defold/defold#4951]
**Describe the bug**
The 9-slicing on GUI box node doesn't seem to work at all.

**To Reproduce**
1. Add GUI box node to the scene.
2. Assign texture to it.
3. Add 9 slicing params to it.
4. Scale the node.

Actual behavior (not nine sliced scaled image on top, nine sliced scaled image on bottom, original non scaled image on the right):

<img width="1251" alt="Screen Shot 2020-06-22 at 17 59 59" src="https://user-images.githubusercontent.com/23015779/85304944-0558b000-b4b5-11ea-87a9-cfc540189586.png">

**Expected behavior**
I expected the rendered scene to look like this (not nine sliced scaled image on top, nine sliced scaled image on bottom, original non scaled image on the right):

<img width="1268" alt="Screen Shot 2020-06-22 at 18 11 04" src="https://user-images.githubusercontent.com/23015779/85305041-2b7e5000-b4b5-11ea-844e-a235d6c1fd53.png">

**Defold version**
At least version **1.2.163** (this is the earliest version I could easily check it on)

<img width="486" alt="Screen Shot 2020-06-22 at 18 07 05" src="https://user-images.githubusercontent.com/23015779/85304395-5fa54100-b4b4-11ea-9c5b-c801b2e6bc83.png">

**Platforms**
I checked it on macOS, but I suspect from the code, that the issue will be with all platforms. It is also displayed wrongly in editor.

**Minimal repro case project**
[side_scroller_tutorial.zip](https://github.com/defold/defold/files/4814056/side_scroller_tutorial.zip)

**Additional context**
The expected image is rendered with my changes to the engine.

**Comment by AGulev** [comment]
Maybe I'm wrong but we by design use size (not scale) for 9-slice. It's useful when you want to have 9-slice and scale at the same time.
<img width="1204" alt="image" src="https://user-images.githubusercontent.com/2209596/85318919-14455f80-b4c1-11ea-99ba-48a2834c86d5.png">

**Comment by hapass** [comment]
@AGulev Thanks! I was sure I missed something, because otherwise it would never have worked :D

**Comment by britzl** [comment]
@AGulev is correct. You typically set the size, not the scale. The question is what should happen when scaling? I think the existing solution is correct where the whole node is scaled. So closing this issue is correct.
