### ISSUE TITLE
Cannot open Builtins scripts or Extensions scrips with external code editors.

### ISSUE THREAD

**Issue by piXelicidio** [defold/defold#4964]
If I have a external code editor set in settings, when I try to open a script inside Builtin or inside a Extension the editor opens a blank document.

1. Go to Settings and set any external editor (Tested with Atom and Win7 notepad)
2. Open Builtins folder from any project.
3. Look for any script and double-click.

It should open with the external editor or at least with the internal editor.

Version [e.g. 1.2.170]

 - Platforms: tested on Windows 7.

Similar to https://github.com/defold/defold/issues/4015 ... internal editor gets completely disabled, in order to open these scripts I need to remove the external editor temporally.

**Comment by britzl** [comment]
I guess the problem is that both builtins.zip and the extensions exist as zip files on disk (in the .internal) folder of your project. We read the files inside the zipfile in the editor but actually never unpack it.

**Comment by webskydavid** [comment]
I noticed it also, even by opening it with the build in code editor it opens the external editor
<img width="374" alt="image" src="https://github.com/defold/defold/assets/4489798/3607e64b-a927-4928-a677-e04b6434e7b4">
