### ISSUE TITLE
Implement Blockly for building Lua Scripts/logic/etc (Or any visual scripting)

### ISSUE THREAD

**Issue by Silver-Streak** [defold/defold#4980]
**Is your feature request related to a problem? Please describe (REQUIRED):**
I recently discovered Defold, and believe the content pipeline around adding assets/setting up scenes to easily be one of the most sensical/easiest I've seen in engines. However, not currently having a visual scripting solution is somewhat of a roadblock for me from an ease-of-use/learning standpoint.

After many years of being in DevOps, I find myself not wanting to have to directly deal with typed code anymore. (This is 100% on me, I know 😄 )

While I understand programming logic just fine, and still know a decent amount of Javascript and C#, directly dealing with syntax and manually remembering all of my variables and such just seems to slow me down. (As an example, while I had previously worked through some application backend design through JS/C# in the past, I found using something like Microsoft PowerAutomate/Flow way faster to iterate on from a "I understand what this is doing from a glance" standpoint). 

Likewise, Defold not currently having a Visual Scripting solution has similarly slowed down my ability to adopt it. While I realize this is really a "me" issue, I also think this could be impactful for people new to code in general, including the base concepts of programming logic. 

**Describe the solution you'd like (REQUIRED):**
In a perfect world, I'd love to see a full Unreal Blueprints style flow designer, or Playmaker FSM designer, for scripting, however I think a much more realistic alternative would be implementing Blockly into the editor for building Lua scripts.  https://developers.google.com/blockly/guides/get-started/web 
https://github.com/google/blockly

Blockly supports Lua directly, is apache 2.0 licensed, can be embedded into offline apps, and seems like it would enable a relatively simple visual scripting solution for Defold out of the box. 

It's also a visual interface that a lot of students are used to that could help them start learning Defold, as it is similar in style to Scratch (and in some cases schools use Blockly directly in their programming classes for young students).

Because it directly translates to Lua, users could switch back and forth between the visual view and the actual code view relatively easily, and for users wanting to learn to code more directly it could be used as a bridge and learning tool.

**Describe alternatives you've considered (REQUIRED):**
A "perfect world" solution would be a Hybrid between Blueprints flow designer for more "advanced" scripts, and GameMaker Studios drag and drop for more "standard" behaviors or actions (or having prebuilt flow scripts for those style of behaviors). However this seems unrealistic because of a few reasons: It becomes an entire separate set of interface items to maintain, covering all "standard" items could be very difficult due to different parts of the community having different demands, and has to be built from the ground up.

Another option would be instating a Playmaker style FSM solution, which is less complex then abstracting to something like GMS, but still requires defining a set of common actions/behaviors and maintaining that separately. Similarly, it would need to be built from the ground up.

**Additional context (OPTIONAL):**
Some demos of Blockly can be seen here: 

https://blockly-demo.appspot.com/static/demos/code/index.html <-- Directly play with some basic blocks and see it directly translate to code with 1 click.

https://blockly.games/ <-- Some very basic games that are used to teach using Blockly/programming logic.

**Comment by britzl** [comment]
This is interesting, but it would probably mean a huge investment to get this to a functioning state, especially with a full editor integration. If anything it should be maintained as a separate tool with additional plugins to expose the Defold API as custom blocks.

One problem which I don't see a solution for is how to deal with asynchronous code and callbacks. Like reacting to when an animation has completed. But maybe that is possible to achieve?

**Comment by JCash** [comment]
Yeah, I'd also think that support burden of the visual scripting would be huge.
And, let's not forget that "visual scripting" is programming as well, just done in a more generic way, thus producing bigger and (dare I say it?) less efficient code.

Also, I'd like to remind you of the Defold way of doing things in smaller modular ways.
We'd like to give users the opportunity to build solutions themselves, especially when the "how to buld?" is ambiguous. For example, for it to be effective, we probably wouldn't want it at the very  granular level that Blockly seems to do it, but rather piece together bigger blocks or behaviors.
That's more like something of BluePrint.

To be frank, writing Lua code in our engine, isn't that big of a hurdle.
Writing an if statement doesn't take that long.

But, as @britzl mentions, you should be able to do something "offline", by creating your own standalone tool.

**Comment by Silver-Streak** [comment]
> Yeah, I'd also think that support burden of the visual scripting would be huge.
> And, let's not forget that "visual scripting" is programming as well, just done in a more generic way, thus producing bigger and (dare I say it?) less efficient code.
> 
> Also, I'd like to remind you of the Defold way of doing things in smaller modular ways.
> We'd like to give users the opportunity to build solutions themselves, especially when the "how to buld?" is ambiguous. For example, for it to be effective, we probably wouldn't want it at the very granular level that Blockly seems to do it, but rather piece together bigger blocks or behaviors.
> That's more like something of BluePrint.
> 
> To be frank, writing Lua code in our engine, isn't that big of a hurdle.
> Writing an if statement doesn't take that long.
> 
> But, as @britzl mentions, you should be able to do something "offline", by creating your own standalone tool.

Thank you both, @JCash @britzl for taking a look at this.  

From when I did a quick look at Google's docs around it, it seemed like you would just have to connect Defold's API bindings into it, and then you could just point it at any Lua scripts as an alternate way to view/build them (basically another tab in the script editor that you can swap back and forth between the normal code and blockly view), rather than necessarily having to build large scripts separate from the normal workflow. It's very likely I missed some key parts of complexity from my quick review.

While I agree Defold's scripting with Lua is definitely simpler than something like C++ on UE4, I still hope to one day see a blueprints alternative available for Defold, even something more basic like Blockly, just from a usecase of speeding up prototyping and/or teaching newer people the scripting language.

Regardless, even if it's not something to be implemented today, thanks again for your time reviewing this.

**Comment by SBalex-state** [comment]
when will it be?when will it be? I can't wait for this update! this is a very good solution for learning game programming on the excellent and capable Lua engine!

**Comment by Silver-Streak** [comment]
@SBalex-state Unless something has changed, per the responses above, this is not something that is going to be implemented for Defold.

**Comment by subsoap** [comment]
It could be but most likely would need to be a well developed user contribution.

**Comment by britzl** [comment]
The Defold Foundation will not invest in any kind of visual/nocode/block based way of creating Defold games.
