### ISSUE TITLE
Manjaro open .go file issue

### ISSUE THREAD

**Issue by SashaVanzuriak** [defold/defold#4985]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2020-06-22T08:56:23.746851</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>5791ee6d96b87e50eee5acd70abaa4026fefef28</td></tr>
<tr><td>Defold engine sha</td><td>5791ee6d96b87e50eee5acd70abaa4026fefef28</td></tr>
<tr><td>Defold version</td><td>1.2.170</td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) HD Graphics 520 (SKL GT2)</td></tr>
<tr><td>GPU Driver</td><td>OpenGL ES-CM 1.1 Mesa 20.0.7</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.4.44-1-MANJARO</td></tr>
<table>
java.lang.ClassCastException: class jogamp.opengl.es1.GLES1Impl cannot be cast to class com.jogamp.opengl.GL2ES2 (jogamp.opengl.es1.GLES1Impl and com.jogamp.opengl.GL2ES2 are in unnamed module of loader 'app')

**Comment by SashaVanzuriak** [comment]
Fix issue this issue with `$ export MESA_GL_VERSION_OVERRIDE=2.1`

**Comment by britzl** [comment]
@SashaVanzuriak ok, so using `export MESA_GL_VERSION_OVERRIDE=2.1` solved the problem for you?

**Comment by SashaVanzuriak** [comment]
@britzl yes
