### ISSUE TITLE
DMEngine crashed while switching collections

### ISSUE THREAD

**Issue by TillCity** [defold/defold#4989]
### It goes without saying I am only doing this after having extensively tested in the IDE

<hr/>

<table>
<tr><td>Build time</td><td>2020-06-29T13:41:32.698594</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>59d19a981dba32421a462d108158f1e33cdfe694</td></tr>
<tr><td>Defold engine sha</td><td>5791ee6d96b87e50eee5acd70abaa4026fefef28</td></tr>
<tr><td>Defold version</td><td>1.2.170</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"860c670c01eb4f50b79b488650eb41a2"'>860c670c01eb4f50b79b488650eb41a2</a></td></tr>
<tr><td>GPU</td><td>Intel(R) UHD Graphics 630</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 - Build 26.20.100.7263</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
Ok, so this happens when you build with your phone set as target and having a dmengine running?

What if you bundle and install the apk? Same problem?

**Comment by TillCity** [comment]
I hadn't rebooted the phone in a while.  After I rebooted I could use the phone as a target - albeit with a huge delay for each collection switch - hide one, show another.  When I try to install a debug APK the app promptly shuts down.  As I said, I had not tried an APK in a while since I was busy building the other app screen - user settings, leaderboard, splash screen etc.  I am going to try reconstructing the app one additional collection at a time till I get to the point where this is happening again.

**Comment by britzl** [comment]
What does the log say when the installed APK crashes?
 https://defold.com/manuals/debugging-game-and-system-logs/#android

**Comment by TillCity** [comment]
I rebuild a new APK, installed it, cleaned out logcat and then ran the app again.  Here is the logcat output for Defold

`07-04 07:28:39.997 11143 11163 W defold  : WARNING:CRASH: Number of modules exceeds capacity
07-04 07:28:39.999 11143 11163 I defold  : INFO:DLIB: Log server started on port 38937
07-04 07:28:40.039 11143 11163 I defold  : INFO:ENGINE: Engine service started on port 8001
07-04 07:28:40.040 11143 11163 I defold  : INFO:ENGINE: Defold Engine 1.2.170 (5791ee6)
07-04 07:28:40.045 11143 11163 I defold  : INFO:ENGINE: Loading data from: dmanif:game.dmanifest
07-04 07:28:40.147 11143 11163 I defold  : INFO:ENGINE: Initialised sound device 'default'
07-04 07:28:40.147 11143 11163 I defold  :
07-04 07:28:40.255 11143 11163 E defold  : ERROR:SCRIPT: scripts/main.script:2: module 'scripts.statics' not found:
07-04 07:28:40.255 11143 11163 E defold  :      no file 'scripts.statics'
07-04 07:28:40.255 11143 11163 E defold  : stack traceback:
07-04 07:28:40.255 11143 11163 E defold  :      [C]: in function 'require'
07-04 07:28:40.255 11143 11163 E defold  :      scripts/main.script:2: in main chunk
07-04 07:28:40.255 11143 11163 W defold  : WARNING:RESOURCE: Unable to create resource: /scripts/main.scriptc
07-04 07:28:40.255 11143 11163 W defold  : WARNING:RESOURCE: Unable to create resource: /collections/main_generated_0.goc
07-04 07:28:40.255 11143 11163 E defold  : ERROR:GAMEOBJECT: Could not instantiate game object from prototype /collections/main_generated_0.goc.
07-04 07:28:40.255 11143 11163 W defold  : WARNING:RESOURCE: Unable to create resource: /collections/main.collectionc`

I noted the message regarding "number of modules".  It isn't clear to me what precisely constitutes a module in Defold.  However, I retried after increasing most of the "Max" settings in _game.project_ from 128 to 192 but with precisely the same result.

I have 7 collections +  the "main" collection which has 7 collection proxies.  In addition I use two GUIs and the image resources in the project have a raw size of 4.6 Mb.  I opened the APK in 7 zip and found that the game.arcd file is over 60Mb.

**Comment by TillCity** [comment]
I should also mention that I am using the DefSave and AdMob extensions.

**Comment by britzl** [comment]
Well, this error makes it clear that you have some issue loading a Lua module:

    ERROR:SCRIPT: scripts/main.script:2: module 'scripts.statics'

Can you share main.script here? How does the require line for "scripts.statics" look?

**Comment by TillCity** [comment]
One of the more annoying "features" of Lua is that it does not require a line terminating character.  This is contrary to pretty much every other respectable programming language out there.  During a typical working day I switch between (at least) PHP, Java, Dart, and Javascript.  Now with Defold and Lua I often end up with one of two situations

1. I terminate my Lua code lines with a semicolon out of sheer habit
2. I switch to another language and forget the semicolon.

I stripped out all the semicolons in my Defold/Lua code and tried the APK again.  I haven't altered any of my other code in any way.  So is the semicolon at the root of the crash that I encountered?

However, this time round it worked though I still see the following

`07-06 08:10:08.808 24268 24292 W defold  : WARNING:CRASH: Number of modules exceeds capacity
07-06 08:10:08.811 24268 24292 I defold  : INFO:DLIB: Log server started on port 55462
07-06 08:10:08.854 24268 24292 I defold  : INFO:ENGINE: Engine service started on port 8001
07-06 08:10:08.854 24268 24292 I defold  : INFO:ENGINE: Defold Engine 1.2.170 (5791ee6)
07-06 08:10:08.863 24268 24292 I defold  : INFO:ENGINE: Loading data from: dmanif:game.dmanifest
07-06 08:10:09.080 24268 24292 I defold  : INFO:ENGINE: Initialised sound device 'default'
07-06 08:10:09.080 24268 24292 I defold  :
07-06 08:10:09.204 24268 24292 D defold  : DEBUG:SCRIPT: DefSave: Loaded file 'state' is empty
07-06 08:10:09.204 24268 24292 D defold  : DEBUG:SCRIPT: DefSave: Successfully set the file 'state' to its default state
07-06 08:10:10.083 24268 24292 I defold  : INFO:DLIB: SSDP: Started on address 192.168.178.44
07-06 08:10:10.175 24268 24292 E defold  : ERROR:PROFILER: Could not open /proc/stat`

The one line that I find rather worrisome here is the first one - _WARNING:CRASH: Number of modules exceeds capac

**Comment by britzl** [comment]
> WARNING:CRASH: Number of modules exceeds capacity

This is not really a problem. It just tells you that if a crash happens the crash data will not include all modules. This is really not a problem as the most important thing about a crash isn't the modules but rather the stack trace, and that is unaffected by the warning.

https://github.com/defold/defold/blob/dev/engine/crash/src/load_addrs_proc_smap.cpp#L83

**Comment by TillCity** [comment]
Thank you. So can you confirm that the semicolon(s) were at the root of the issue that I ran into?

**Comment by TillCity** [comment]
I think I haven't been too clear - with the semicolons removed everything worked

**Comment by JCash** [comment]
Separate note: I just now removed the confusing warning about "WARNING:CRASH: Number of modules exceeds capacity" from the code. It only caused trouble for our users.

**Comment by JCash** [comment]
> I think I haven't been too clear - with the semicolons removed everything worked

Ok, and how did your `require` look when it had a semicolon?

**Comment by TillCity** [comment]
`require "scripts.statics;`

I should mention that other than this I had my code peppered with ;s in lots of places - inadvertently as I switch programming languages during the course of a working day.  For instance

`local foo;`

`local function bar*()
    local rand = math.random(10);
    if (condition) then

   else

   end;
  
end`

etc.  I just did a global search-replace with Notepad++ for everything in my `scripts` folder - I sitll probably have a few lingering semicolons in my `gui-scripts` folder - rebuild, deployed the APK on my Android device and it worked.  Between my last post here yesterday and the test today I have not changed any other code.  So decisive change was the semicolon removal.
