### ISSUE TITLE
A separate parameter in game.project for handling display cutout

### ISSUE THREAD

**Issue by AGulev** [defold/defold#4991]
**Is your feature request related to a problem? Please describe (REQUIRED):**
Currently, we use the Immersive Mode parameter for showings hiding cutout. But sometimes users want to control these parameters separately.

**Describe the solution you'd like (REQUIRED):**
 It would be nice to add one more flag for that.

**Describe alternatives you've considered (REQUIRED):**
For now, a user doesn't have the possibility to use these options separately.

**Additional context (OPTIONAL):**
https://forum.defold.com/t/defold-1-2-170-has-been-released/65631/7?u=agulev

**Comment by SkaterDad** [comment]
Does anyone know a workaround for this, short of reverting to an older version of Defold?

**Comment by britzl** [comment]
@SkaterDad I've added this to the planned work for 1.2.173 (we're working on 1.2.172 now).

**Comment by SkaterDad** [comment]
> @SkaterDad I've added this to the planned work for 1.2.173 (we're working on 1.2.172 now).

Thanks for the update!  I've been trying to make something work via native extension in the meantime.  Had no luck changing the view parameter at runtime, but I'll be able to query the cutout height on game init().

**Comment by AGulev** [comment]
@SkaterDad it's in the current beta, you can test.
