### ISSUE TITLE
[SUGGESTION] Let us choose code editor font

### ISSUE THREAD

**Issue by horatiohafnaugels** [defold/defold#4996]
I understand Source Code Pro is pretty popular on Linux systems, but here on Windows there's a bunch of coders that would rather use Consolas instead. So, let us set the font we want to use in the code editor. No need of fancy dialogs, just a text field like the one we use to set external editor will suffice.

Thanks.

**Comment by horatiohafnaugels** [comment]
I may add that's not just a taste issue: on Windows some fonts (like Consolas) have been optimized specifically to look better with OS's font hinting algorithms. This may not be obvious to Mac users, especially if equipped with retina screens, but the ability to set the code font on Windows can make the difference between working comfortably or getting eye strain at the end of the day.

**Comment by britzl** [comment]
Please see this forum post for an update on this: https://forum.defold.com/t/experiments-with-editor-styling-using-javafx-css/67021

**Comment by horatiohafnaugels** [comment]
Thank you very much.
I look forward to being able to change code editor's font which, if I understand correctly, will come with a later update.

**Comment by britzl** [comment]
> if I understand correctly, will come with a later update

Correct!

**Comment by horatiohafnaugels** [comment]
Downloaded and tested 1.2.180 right now. It works.
Thank you again.
