### ISSUE TITLE
[SUGGESTION] Use fixed width font when editing assets opened with the "Open As / Text" menu item

### ISSUE THREAD

**Issue by horatiohafnaugels** [defold/defold#4997]
I love the idea of editing asset files as text, but doing this with a variabile width font feels awkward.
Please consider using the same font used by code editor instead.

Thanks.

**Comment by AGulev** [comment]
@matgis as I understand we can close this one after you nerged https://github.com/defold/defold/pull/9162 ?

**Comment by matgis** [comment]
Yep!
