### ISSUE TITLE
Using window.set_listener with NE that changes your window makes the NE switch script context

### ISSUE THREAD

**Issue by Jerakin** [defold/defold#5000]
Long title for a strange issue

If you call `window.set_listener` in a .script and then in a .gui_script call `defos.set_window_size` (or another NE that changes the window somehow). The GuiScript Instance will change to Script instance.

The reverse happen if you in .gui_script call `window.set_listener` and in your .script call `defos.set_window_size`. The Script Instance will change to GuiScript instance.

Repro
[script_instance.zip](https://github.com/defold/editor2-issues/files/3217544/script_instance.zip)

**Comment by JCash** [comment]
What does `diags` come from?
Does it do any Lua callbacks internally?

**Comment by Jerakin** [comment]
I am not sure if #5023 fixed it (your comment indicate that it doesn't?) but I get this on 1.2.170

```
DEBUG:SCRIPT: Before	GuiScript: 0x020d45baa8a0
DEBUG:SCRIPT: After	Script: 0x020d45baa1f0
```
