### ISSUE TITLE
Avoid creating redundant component type worlds

### ISSUE THREAD

**Issue by JCash** [defold/defold#5003]
Both when it comes to creating and deleting worlds, these take up resources.
Both wrt memory, but also graphics, and time.

To avoid creating a world of a certain component type, we need to know when creating the component type what number of instances it might have.

E.g. **m_HasInstances** (bool)

With such a boolean, we can skip the creation of the world entirely

**Comment by AGulev** [comment]
@JCash  Is it related to https://github.com/defold/defold/issues/5843 ? If so we can close this ticket then?

**Comment by britzl** [comment]
Yes I believe we can close it!
