### ISSUE TITLE
Android crash (ares_get_android_server_list)

### ISSUE THREAD

**Issue by AGulev** [defold/defold#5004]
**Describe the bug (REQUIRED)**
```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> com.potatojam.onet_paradise.match_two_tiles <<<

backtrace:
  #00  pc 00000000003338b6  /system/lib/libart.so (art::Thread::~Thread()+205)
  #00  pc 0000000000340291  /system/lib/libart.so (art::ThreadList::Unregister(art::Thread*)+1528)
  #00  pc 00000000003184df  /system/lib/libart.so (art::Runtime::DetachCurrentThread()+234)
  #00  pc 000000000023beb3  /system/lib/libart.so (art::JII::DetachCurrentThread(_JavaVM*)+42)
  #00  pc 00000000001d7bcc  /data/app/com.potatojam.onet_paradise.match_two_tiles-1/lib/arm/libOnetParadise.so (ares_get_android_server_list)
```
<img width="673" alt="image" src="https://user-images.githubusercontent.com/2209596/87183474-7d610b80-c2e6-11ea-9bd4-a61ec3fe1cdb.png">

**To Reproduce (REQUIRED)**
Unfortunately I don't know how to reproduce this issue, I see this crash in Google Console.

**Expected behavior (REQUIRED)**

**Defold version (REQUIRED):**
  - Version 1.2.169

**Platforms (REQUIRED):**
 - Platforms: Android
 - OS: Android 6.0 and Android 7.0
 - Devices:
Samsung Galaxy Grand Prime Plus
BQru BQ-4072 Strike Mini
Samsung Galaxy On5
BQS-5020
Huawei 荣耀畅享7 Plus
BQru BQ-5594 Strike Power Max

**Additional context (OPTIONAL):**

**Comment by britzl** [comment]
Related? https://github.com/meganz/sdk/pull/1799

**Comment by sergiohs84** [comment]
Unfortunately, FYI, our tentative fix didn't solve the issue. We keep seeing the same crash on Google Console :-1: 
Looking forward to new ideas / approaches. Cheers

**Comment by britzl** [comment]
@sergiohs84 thank you for confirming that it didn't help in your case. We haven't investigated this further.
