### ISSUE TITLE
Add a short nag on the splash screen asking people to help pay for build server costs

### ISSUE THREAD

**Issue by subsoap** [defold/defold#5005]
There needs to be more in editor promotion of supporting Defold since there are probably many Defold users who would be willing to support the project financially but have not had enough prompting yet. The launch screen would be a good candidate for this. People like numbers going up, so include a % toward the goal on the launch screen and update that % with new editor versions as it increases in whole number.

The goal text here is good.

https://github.com/sponsors/defold

Here's a possible way the splash could be modified.

![2020-07-11-13_22_50-](https://user-images.githubusercontent.com/409170/87233320-16d9fd00-c37b-11ea-83ae-e400e8121bbe.jpg)

**Comment by polycursegames** [comment]
Please don't start pushing ads (even if they are internal support ads). People that want to support will support and don't need a constant reminder. This is something that has a place on the Defold website, but not the application.

**Comment by subsoap** [comment]
@polycursegames Are you a sponsor? When will you decide to support? Until the goals are met, they need to be promoted. Defold does not have unlimited free money, they need your support.

**Comment by polycursegames** [comment]
@subsoap Sponsor or not (this is a rude comment/question to push, many people sponsor development anonymously and want it to stay that way), this is a slippery slope when you start placing ads in an open source project, and sets the precedent of what's to come, adware. I feel there are far better places to put an ad, for example the website and or forums.

**Comment by subsoap** [comment]
@polycursegames It's not like this is a "third party ad" this kind of thing which is encouraging the support of the very infrastructure the editor uses when making builds that use native extensions. Many people may not even realize the costs of running this service, they need to be more directly informed and encouraged to support, because direct prompts like these are what encourage people to actually support. Especially seeing the number go up as new builds are released until the goal is met, it would be very encouraging for everyone. These costs add up as a burden, they need to be paid for by the community, if everyone chips in then it can be met more quickly and ease the burden on the foundation.

It's also not unusual. Many open source / source available projects encourage users to support on their splash popups and most people don't have a problem with it. And these other services don't have as much of a service cost beyond bandwidth, which the foundation also pays for and is likely very costly. The current goal is just the single build server costs.

The precedent has already been set. The current splash already promotes games made with Defold. It can promote helping with the foundation's costs related to the Defold service too. This is all part of a healthy tool and healthy community.

Being direct like this is how I am. You should be proud to publicly sponsor. If you are unable to I can understand, make good games, make money, and then sponsor!

**Comment by britzl** [comment]
Thank you both for your input and for the initial suggestion. We may explore in-editor prompts in the future as I think it can serve as a reminder that there are options for developers wanting to support the work of the Defold Foundation.

**Comment by britzl** [comment]
Another option which is less intrusive than a popup would be a bob and editor build log entry along the lines of:

"Completed build using the public Defold build server. If you wish to support the Defold Foundation and help keep the servers running the please join as a monthly sponsor: https://github.com/sponsors/defold"

**Comment by britzl** [comment]
We will not be pushing for this from within the editor.
