### ISSUE TITLE
Timer issue

### ISSUE THREAD

**Issue by xxxKfkxxx** [defold/defold#5006]
Hello
I have this issue:
```
ERROR:SCRIPT: attempt to index global 'timer' (a function value)
```

I have worked for some months and suddenly got this issue, I worked offline and didn't install any updates or something

I have Defold version 1.2.169 and my OS is Ubuntu 20.04

Here is my log:
[log.txt](https://github.com/defold/defold/files/4908536/log.txt)

I tried to work online and I tried to change build server to foobar.com as Bitzl advised on Def forum

**Comment by britzl** [comment]
It seems like somewhere in your code you have actually replaced the global timer.* table with a function. This is a programming error. Look for something like

timer = function() end

Where you assign a function to a variable named "timer" without declaring it as "local".

**Comment by xxxKfkxxx** [comment]
Ohh, sory yes. I found that

**Comment by xxxKfkxxx** [comment]
Ohh sorry, you are right. I found that I named other function 'timer'. But I did it some days ago and idk why before all was right)
