### ISSUE TITLE
iOS Custom entitlements not merging or overwriting Ad hoc Profile entitlements 

### ISSUE THREAD

**Issue by animonger** [defold/defold#5017]
Defold 1.2.164
### Expected behaviour
iOS Custom [entitlements](https://defold.com/manuals/project-settings/#entitlements): If specified, can override wildcard entitlements defined in the supplied provisioning profile (.entitlements, .xcent, .plist).

### Actual behaviour
iOS Custom entitlements will not merge or completely overwrite the Ad hoc Provision entitlements. No change to entitlements in embedded.mobileprovision from entitlements in AdHoc Provision, wildcard values are still wildcard “*”.
See this [forum post](https://forum.defold.com/t/how-to-properly-add-ios-entitlements-to-an-app/64605/5?u=animonger) for more detail.

### Steps to reproduce
* Create a bare bones Defold project with the mobile game template.
* On the Apple Developer website, create an iCloud Container ID and an App ID with the following Capabilities:

* [x] Game Center
   * [x] iOS
   * [x] macOS 
* [x] iCloud
   * [x] Include CloudKit support (requires Xcode 6)

* Enable iCloud Container ID
* Create Ad hoc Provisioning Profile with the App ID that has iCloud Capabilities.
* Create a custom.entitlements file with the values to replace the wildcard values in the downloaded Ad hoc Provisioning Profile.

Point to custom.entitlements file in Defold game.project Custom entitlements settings.

Bundle iOS Application settings:
Sign application: [x]
Code signing identity: Distribution
Provision profile: AdHoc
Architectures: [x] 32-bit, [x] 64-bit
Variant: Release

<hr/>

<table>
<tr><td>Build time</td><td>2020-01-23T17:25:00.524437</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>70cc8d7d712dd866fd12a3a43297045ca7b27cb3</td></tr>
<tr><td>Defold engine sha</td><td>2be2687cbb670c2dbe9cf2e99577bc3338561778</td></tr>
<tr><td>Defold version</td><td>1.2.164</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce 9600M GT OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 NVIDIA-10.0.52 310.90.10.05b46</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.11.6</td></tr>
<table>

**Comment by JCash** [comment]
I've been looking into this now, and it seems to work for me (afact):
Note that the entitlements end up in two places:
the `embedded.mobileprovision` and also the app's code signature.

From the [Apple doc](https://developer.apple.com/library/archive/technotes/tn2415/_index.html):
```
Entitlement Destinations

This section provides a review of the locations that entitlements reside. Entitlements end up in two different places within an app:

    The app's signature. See Inspect the entitlements of a built app for more information.

    The app's embedded provisioning profile. See Inspecting a profile's entitlements for more information. 

```

From [Inspect the entitlements of a built app](https://developer.apple.com/library/archive/technotes/tn2415/_index.html#//apple_ref/doc/uid/DTS40016427-CH1-APPENTITLEMENTS):

> $ codesign -d --ent :- /path/to/the.app

From [Inspecting a profile's entitlements](https://developer.apple.com/library/archive/technotes/tn2415/_index.html#//apple_ref/doc/uid/DTS40016427-CH1-PROFILESENTITLEMENTS):

> $ security cms -D -i /path/to/iOSTeamProfile.mobileprovision


Given our option of `ios.override_entitlements = 1`, this should work for you. Tested with 1.2.171.

(We have some things we'd like to fir for the `ios.override_entitlements = 0` case, but that's another issue)

@animonger  Could you please reverify this issue?

**Comment by britzl** [comment]
Great investigation @JCash . We should probably explain this better in the iOS manual.

**Comment by animonger** [comment]
Thanks for the info, @JCash . I won't be able to reverify this until tomorrow but I will post my results then.

**Comment by JCash** [comment]
Any news on this one?

**Comment by animonger** [comment]
Ok, I finally had a chance to retest this.
I upgraded to Defold 1.2.171 then bundled a bare bones iOS Application within the Defold IDE using an Ad hoc Provisioning Profile with the App ID that has iCloud Capabilities and got the following errors:

Using this custom entitlements file, FulliCloud.entitlements:
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<key>Entitlements</key>
<dict>
	<key>com.apple.developer.ubiquity-container-identifiers</key>
	<array>
		<string>iCloud.com.new.test.id</string>
	</array>
	<key>application-identifier</key>
		<string>NDTNF46YVT.com.new.test.id</string>
	<key>keychain-access-groups</key>
	<array>
		<string>NDTNF46YVT.com.new.test.id</string>
	</array>
	<key>get-task-allow</key>
		<false/>
	<key>com.apple.developer.team-identifier</key>
		<string>NDTNF46YVT</string>
	<key>com.apple.developer.ubiquity-kvstore-identifier</key>
		<string>NDTNF46YVT.com.new.test.id</string>
	<key>com.apple.developer.icloud-services</key>
		<string>CloudDocuments</string>
	<key>com.apple.developer.icloud-container-environment</key>
	<array>
		<string>Production</string>
		<string>Development</string>
	</array>
	<key>com.apple.developer.icloud-container-identifiers</key>
	<array>
		<string>iCloud.com.new.test.id</string>
	</array>
	<key>com.apple.developer.icloud-container-development-container-identifiers</key>
	<array>
		<string>iCloud.com.new.test.id</string>
	</array>
</dict>
</plist>`

Set the following settings in the game.project:
override_entitlements = 1
entitlements = /FulliCloud.entitlements

I got these Build Errors
Unknown source
/var/folders/wr/37b7w66x6rs7tf0z52cf_gfm0000gn/T/entitlement16475708249256353125.xcent: unrecognized blob type (accepting blindly)
/var/folders/wr/37b7w66x6rs7tf0z52cf_gfm0000gn/T/entitlement16475708249256353125.xcent: invalid length in entitlement blob

Then I noticed that you posted the override setting like `ios.override_entitlements = 1` above.
So I changed the setting in the game.project:
ios.override_entitlements = 1
entitlements = /FulliCloud.entitlements

Build Errors
Unknown source
java.io.IOException: Invalid custom iOS entitlements key 'Entitlements.com..apple..developer..ubiquity-container-identifiers'.

Then I changed the game.project file by removing the override and pointing to a partial entitlements file.
game.project:
entitlements = /iCloud.entitlements

iCloud.entiltements:
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Entitlements</key>
	<key>keychain-access-groups</key>
	<array>
		<string>NDTNF46YVT.com.new.test.id</string>
	</array>
	<key>com.apple.developer.ubiquity-kvstore-identifier</key>
		<string>NDTNF46YVT.com.new.test.id</string>	
	<key>com.apple.developer.icloud-services</key>
	<array>
		<string>CloudDocuments</string>
	</array>
</dict>
</plist>
`

And got this error:
Build Errors
Unknown source
java.io.IOException: Invalid custom iOS entitlements key 'Entitlements.keychain-access-groups'.

**Comment by animonger** [comment]
@JCash, did you see my above post?

**Comment by britzl** [comment]
I'm looking into this as well. First test:

```
[ios]
bundle_identifier = com.defold.entitlements
override_entitlements = 1
entitlements = /Custom_entitlements_test-overrides.plist
```

After successfully bundling the application I check the entitlements like @JCash suggested above:

```
codesign -d --ent :- build/default/Test.app 
```

The entitlements shown from the command shows that the entitlements of the application is identical to the entitlements in Custom_entitlements_test-overrides.plist

Conclusion: Using ios.override_entitlements and ios.entitlements works as expected.

**Comment by britzl** [comment]
Ok, now on to the second case:

```
[ios]
bundle_identifier = com.defold.entitlements
override_entitlements = 0
entitlements = /Custom_entitlements_test-overrides.plist
```

When bundling with this setting I got the same problem as @animonger:

```
SEVERE: No such key found in provisions profile entitlements 'Entitlements.get-task-allow'. 
```

The clue to why this happens is in the key name, in the example above `Entitlements.get-task-allow`. The key should be `get-task-allow` without the preceding `Entitlements.`. The reason this happens is that the file I tested with looks like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Entitlements</key>
	<dict>
		<key>get-task-allow</key>
		<false/>
	</dict>
</dict>
</plist>
```

When in fact it should be:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>get-task-allow</key>
	<false/>
</dict>
</plist>
```

(Note that the `Entitlements` key and dict has been removed and the keys are immediately in the root of the plist file)

This means that we are inconsistent in the way we expect the Custom Entitlements file to be structured:

1. When `override_entitlements = 1` we expect the provided entitlements to be a .plist file with an `Entitlements` key and a `<dict>` holding all of the entitlements
2. When `override_entitlements = 0` we expect the provided entitlements to be a .plist file **without** an `Entitlements` key and instead the entitlements should be in the root dict of the plist file.

**Comment by britzl** [comment]
We can obviously keep it this way and make sure to document it, BUT I would prefer to fix it and make it consistent. I think we should look at fixing the case when `override_entitlements = 0` and make this compatible both with the case when there is a `Entitlements` key and when there is none.

**Comment by JCash** [comment]
Good investigation!
I agree that we should keep it in the same format. Which one is the standard format?

**Comment by britzl** [comment]
I think we should handle both. The entitlements we send to codesign is expected to be in the format with an `<Entitlements>` key:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Entitlements</key>
	<dict>
		...
	</dict>
</dict>
</plist>
```

I'll submit a PR that accepts both styles when merging (to be backward compatible).
