### ISSUE TITLE
Save font issue in gui

### ISSUE THREAD

**Issue by SashaVanzuriak** [defold/defold#5018]
### Expected behaviour
Save font via Ctrl+S 
### Actual behaviour
No changes, "start" sign in file title
### Steps to reproduce
Change font (size or other property) and press Ctrl+S
<hr/>

<table>
<tr><td>Build time</td><td>2020-07-14T14:36:37.691977</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>3061bed6e880b423d87a33bcf55d6e920c3afa74</td></tr>
<tr><td>Defold engine sha</td><td>5791ee6d96b87e50eee5acd70abaa4026fefef28</td></tr>
<tr><td>Defold version</td><td>1.2.170</td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) HD Graphics 520 (SKL GT2)</td></tr>
<tr><td>GPU Driver</td><td>2.1 Mesa 20.0.7</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.4.44-1-MANJARO</td></tr>
<table>

**Comment by nevinbaiju** [comment]
Yes, I also had this issue in Ubuntu 18.04.

**Comment by britzl** [comment]
> No changes, "start" sign in file title

Can you explain what you mean by this?

**Comment by SashaVanzuriak** [comment]
It's star sign, sorry typo

![image](https://user-images.githubusercontent.com/48361492/87795948-67f16180-c851-11ea-867e-c2d05ebc66a7.png)

**Comment by AGulev** [comment]
Just to make sure.
If some process is working on background (bindling, for example) ou can't save files.
Are you sure you don't building or bundling at this moment?

**Comment by SashaVanzuriak** [comment]
@AGulev 
No, I save files and doesn't working on background.

**Comment by britzl** [comment]
@SashaVanzuriak are you still using Defold? Did you find a solution to the problem you had?

**Comment by britzl** [comment]
This is a file in builtins. It is not possible to make a change and save it. You need to copy the file from the read-only builtins folder to your project. Closing.
