### ISSUE TITLE
Full DVORAK support

### ISSUE THREAD

**Issue by lewislepton** [defold/defold#5021]
DVORAK support is 'kind of' in Defold. I can type things & name things. but shortcuts are pretty picky.
when trying say, a new object, or even quitting Defold, it doesn't work.
but if I click on a menu, then do the shortcut, it works

so yeah, full DVORAK support would be great

im trying to think of something to add. but thats about it

**Comment by subsoap** [comment]
The editor needs user config file support for shortcuts, then a DVORAK shortcut template can be made and shared.

The editor could check to see if the user config file for shortcuts exists and if it does prefer the shortcuts listed there, and if some are missing use the existing internal shortcut list.

**Comment by lewislepton** [comment]
oh cool. good to know.
how can this accessed, or is this a 'it will appear in the next update'?
just wondering more thanks anything

thanks again

**Comment by britzl** [comment]
@lewislepton it is not something we have planned to fix any time soon I'm afraid.

**Comment by lewislepton** [comment]
@britzl - that is fair enough. thanks for getting back 😘

**Comment by subsoap** [comment]
@lewislepton 

The default binds are listed in 

/editor/src/clj/editor/keymap.clj

If you can get the editor to build you could experiment with externalizing these... if you want to learn some Clojure. This is what someone will need to do eventually. 😊

Or if you can get the editor to build you can just change them in this file to what you want, but that would be hard coded to your build.

**Comment by lewislepton** [comment]
@subsoap awesome - thanks a bunch.
aye, im not too sure. but I may take a look if I can, since its Clojure I have have not touched before

thanks again x

**Comment by britzl** [comment]
@lewislepton Thanks to a community contribution we now have configurable keybindings. Have a look here: https://defold.com/manuals/editor/#customizing-shortcuts
