### ISSUE TITLE
Error when running tccutil reset Camera (I think)

### ISSUE THREAD

**Issue by Jerakin** [defold/defold#5024]
Popup indicates that it had something to do with git log, but I didn't do anything with that.

Had defold/extension-camera opened and ran `tccutil reset Camera` in a terminal (from `~`) 

<hr/>

<table>
<tr><td>Build time</td><td>2020-07-14T14:35:31.376974</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>3061bed6e880b423d87a33bcf55d6e920c3afa74</td></tr>
<tr><td>Defold engine sha</td><td>5791ee6d96b87e50eee5acd70abaa4026fefef28</td></tr>
<tr><td>Defold version</td><td>1.2.170</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"9d2f26395fc34bc484c17ec42db7b219"'>9d2f26395fc34bc484c17ec42db7b219</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 560 OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-3.9.15</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.15.5</td></tr>
<table>

**Comment by britzl** [comment]
Can you reproduce this 100%?

**Comment by Jerakin** [comment]
Tried a few things now and can not reproduce it at all (which I kind of expected as I find it hard to image how they are connected). So if the error doesn't say much or not enough to go on I think we can close it.
