### ISSUE TITLE
Investigate implication of new security measures for the HTML5 Gamepad API

### ISSUE THREAD

**Issue by britzl** [defold/defold#5026]
**Task (REQUIRED):**
Mozilla is working with Google Chrome to improve security and privacy for the Gamepad API. We need to understand if the changes has any impact on Defold games and if so what we need to do.

----

As part of Mozilla’s ongoing commitment to improve the privacy and security of the web platform, over the next few months we will be making some changes to how the Gamepad_API works.

Here are the important dates to keep in mind:

* 25 of August 2020 (Firefox 81 Beta/Developer Edition):
    .getGamepads() method will only return game pads if called in a “secure context” (e.g., https://).

* 22 of September 2020 (Firefox 82 Beta/Developer Edition):
    Switch to requiring a permission policy for third-party contexts/iframes.

We are collaborating on making these changes with folks from the Chrome team and other browser vendors. We will update this post with links to their announcements as they become available.

https://hacks.mozilla.org/2020/07/securing-gamepad-api/

**Expected outcome (REQUIRED):**
Either no action is needed or we need to create one or more tasks to deal with the outcome of the investigation.

**Comment by subsoap** [comment]
https is a requirement to exist on the net at this point.

I imagine for embeds they will want to display a permission dialog to ask users if they wish to allow their gamepads to be fetched, otherwise on direct pages there will be no permissions. This would likely be done through https://developer.mozilla.org/en-US/docs/Web/API/Permissions/query to check if permission has been granted

This must be related to reducing the ability for super cookies to finger print unique computers.

**Comment by subsoap** [comment]
This is printing in Chrome now

> getGamepad will now require a Permission Policy. Please update your application accordingly. For more information see https://github.com/w3c/gamepad/pull/112

**Comment by subsoap** [comment]
Gamepad permission has now been added to itch.io iframe. ✨

Could add to the documentation about gamepads that the gamepad permission is required for the HTML5 target when using iframes.

**Comment by britzl** [comment]
> Could add to the documentation about gamepads that the gamepad permission is required for the HTML5 target when using iframes.

Good point. I've added docs here:

* https://defold.com/manuals/input-gamepads/#gamepads-in-html5
* https://defold.com/manuals/html5/#known-issues-and-limitations
