### ISSUE TITLE
Error when i click in "Curve Editor"

### ISSUE THREAD

**Issue by victordf** [defold/defold#5028]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2020-07-20T08:43:46.542372</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>a98007b48691529b59fb099fc369d81518059d00</td></tr>
<tr><td>Defold engine sha</td><td>29b8e598b0bce19b274327c5d9711f78b3bd0c22</td></tr>
<tr><td>Defold version</td><td>1.2.171</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"23eb586451154cb6937efb1186d0d3af"'>23eb586451154cb6937efb1186d0d3af</a></td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) HD Graphics 5500 (BDW GT2)</td></tr>
<tr><td>GPU Driver</td><td>OpenGL ES-CM 1.1 Mesa 20.2.0-devel (git-0ef168d 2020-07-18 bionic-oibaf-ppa)</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.3.0-62-generic</td></tr>
<table>

**Comment by h3ar** [comment]
[try this](https://defold.com/manuals/linux/#q-why-does-the-defold-editor-crash-when-i-try-to-create-a-new-project-or-open-an-existing-one)
linux mint 20 my machine: (3.1 didn't help). from cli:
```
MESA_GL_VERSION_OVERRIDE=2.1 `./Defold`
```

**Comment by britzl** [comment]
As @h3ar pointed out it should be possible to set the MESA_GL_VERSION_OVERRIDE env variable before starting Defold to avoid the problem. @victordf please confirm if this solves the problem for you.

**Comment by britzl** [comment]
Tracked here: https://github.com/defold/defold/issues/4851. Closing.
