### ISSUE TITLE
Panel resizing is very slow since update.

### ISSUE THREAD

**Issue by Mrisq** [defold/defold#5031]
**Describe the bug (REQUIRED)**
Resizing the panels in the editor takes a long time: about 10-12 seconds from click-drag to response. I hadn't noticed this before my most recent update to 1.2.171, but it is possible that I skipped an update.
Also, this isn't affecting the resizing of areas within panels, e.g. between outline and properties.
Could this be related to the recent changes to the panel resize handle in this update?

**To Reproduce (REQUIRED)**
1. Click and drag on any panel resize handle in the editor.
2. Release 
3. Wait 10 seconds as nothing happens
3. Panel will catch up to the cursor position

**Expected behavior (REQUIRED)**
Quick response.

**Defold version (REQUIRED):**
  - Version 1.2.171

**Platforms (REQUIRED):**
 - Windows 10 64b

**Minimal repro case project (OPTIONAL):**
Occurs in any project. I even tried it with a new empty project.

**Comment by aglitchman** [comment]
**Windows 10 x64, version 2004.**

Everything is OK, take a look at the screencast: https://imgur.com/a/rlHaOmb

**Comment by britzl** [comment]
@Mrisq does your computer have both a dedicated graphics card and an integrated one?

**Comment by Mrisq** [comment]
It has both, yes.

**Comment by AGulev** [comment]
not enough information.
can't reproduce
