### ISSUE TITLE
Docs position management feature request

### ISSUE THREAD

**Issue by viniciushedler** [defold/defold#5032]
I was creating a level select gui screen and some text wasn't been shown. It took some time, but I noticed it was because I created the button before the text, and so the text was rendered under the button. I solved this by changing the files order from

level select
----> level name
----> button

to 

level select
----> button
----> level name 

but this was really hard to do. I couldn't just change files order, i had to place them in other file and then replace them in their original file in the order I wanted.

This is just one example of why it should be possible to reorganize files in Defold. Defold is great, but this is a really basic feature that I miss a lot.

**Comment by britzl** [comment]
If it is a button with a text on it it makes more sense to put the text node as a child of the box the node, like in this example: https://defold.com/examples/gui/button/

PS You mention files, but I'm assuming you mean the nodes in the Outline view when you edit a GUI component file right? And in that case you can actually rearrange them using Alt+Up/Down, as described here: https://defold.com/manuals/gui/#draw-order

**Comment by viniciushedler** [comment]
Thanks, that's what I was looking for!!!
