### ISSUE TITLE
Problem using the same live update content on two PCs

### ISSUE THREAD

**Issue by britzl** [defold/defold#5033]
**Describe the bug (REQUIRED)**
It seems like there is a problem downloading and using a manifest built on one machine in a build made on another machine (but with the exact same source code).

**To Reproduce (REQUIRED)**

* Build the project (APK) on PC1 and upload LiveUpdate to the Internet.
* The APK is working fine, as expected.
* Build APK for the same project on PC2, but this time without LiveUpdate.
* The APK built on PC2 does not work (because it does not like the LiveUpdate manifest).

**Expected behavior (REQUIRED)**
The manifest should load and missing resource should be able to be downloaded.

**Defold version (REQUIRED):**
  - Version 1.2.170

**Platforms (REQUIRED):**
 - Platforms: Android, likely others (all)

**Additional context (OPTIONAL):**
https://forum.defold.com/t/liveupdate-strange-behavior/65802/6

**Comment by JCash** [comment]
So far, I haven't been able to reproduce this issue.
The project I used was this:
[issue-5033.zip](https://github.com/defold/defold/files/4959896/issue-5033.zip)
