### ISSUE TITLE
Implement ASTC texture compression

### ISSUE THREAD

**Issue by britzl** [defold/defold#5037]
**Is your feature request related to a problem? Please describe (REQUIRED):**
We currently do not support ASTC compression. https://www.khronos.org/opengl/wiki/ASTC_Texture_Compression

**Describe the solution you'd like (REQUIRED):**
The pipeline should support ASTC, the run-time should be able to decompress it and it should be configured using the texture profiles system.

**Comment by JCash** [comment]
Related issue: https://github.com/defold/defold/issues/3375

**Comment by britzl** [comment]
Closed via https://github.com/defold/defold/pull/5509
