### ISSUE TITLE
Cannot load custom resources without file extension

### ISSUE THREAD

**Issue by smarthall** [defold/defold#5040]
**Describe the bug (REQUIRED)**
Trying to load a custom resource which has no file extension (such as `assets/words`) fails in the engine when launched from the editor using the build command.

**To Reproduce (REQUIRED)**

1. Created a new blank project
2. Added a folder in the project root named assets
3. Create a file named words in the folder with some text content
4. Add assets/words to custom_resources in the game.project file
5. Create a new script
6. Add a game object and the script to the collection
7. Add the following lines to the init function of the script and build the project

```
local test, error = sys.load_resource("/assets/words")
print(test)
print(error)
```

**Expected behavior (REQUIRED)**
Expected the output to contain the contents of the file, followed by a `nil` representing no error.

**Defold version (REQUIRED):**
  - Version 1.2.171
  - Editor SHA1: `7a64a72ca0d10f1583edab5b4317499cdc8c64e5`
  - Engine SHA1: `29b8e598b0bce19b274327c5d9711f78b3bd0c22`

**Platforms (REQUIRED):**
 - Platforms: Linux
 - OS: Fedora 32
 - Device: Desktop

**Minimal repro case project (OPTIONAL):**
[Resource.zip](https://github.com/defold/defold/files/4975459/Resource.zip)

**Logs (OPTIONAL):**
```
INFO:DLIB: Log server started on port 35383
INFO:ENGINE: Engine service started on port 42225
INFO:ENGINE: Defold Engine 1.2.171 (29b8e59)
INFO:ENGINE: Loading data from: build/default
INFO:ENGINE: Initialised sound device 'default'

DEBUG:SCRIPT: nil
DEBUG:SCRIPT: Failed to load resource: /assets/words (-3)
INFO:DLIB: SSDP: Started on address 192.168.40.63
INFO:DLIB: SSDP: Started on address 192.168.122.1
INFO:DLIB: SSDP: Done on address 192.168.40.63
INFO:DLIB: SSDP: Done on address 192.168.122.1
```

**Workaround (OPTIONAL):**
Name all custom_resource with a file extension.

You can also test the project by bundling and running it, which appears to not trigger the bug.

**Comment by JCash** [comment]
This works in bob.jar.
However, in the editor, an extra "." is added and the final name will be "/assets/words."
