### ISSUE TITLE
Scene graph inspection API for debug, test and tools

### ISSUE THREAD

**Issue by britzl** [defold/defold#5041]
**Is your feature request related to a problem? Please describe (REQUIRED):**
Having access to the entire scene graph from a Lua API or dmSDK would allow for some very powerful tools to be created. It could also be a useful debugging tool and something that could be added to the webprofiler. Finally it would also be very useful in scenarios where you want to create automated testing where you need to query the position and availability of game objects or GUI nodes.

**Describe the solution you'd like (REQUIRED):**
I would like to see an API where developers can iterate the scene graph (and GUI node graph), query for properties (transform, id, script properties etc) (read-only!) possibly also listing which components exist on a game object.

**Comment by AGulev** [comment]
@britzl I think this one is done, isn't it?

**Comment by britzl** [comment]
Indeed it is!
