### ISSUE TITLE
Strange underline text in 1.2.171?

### ISSUE THREAD

**Issue by slater** [defold/defold#5042]
In the side scroller tutorial (and maybe elsewhere?), there's a "build and run" link that is underlined, except the underline looks a bit wonky?

1. Load Defold 1.2.171
2. Open from tutorials -> Side scroller tutorial
3. See linked "build and run" in the readme.md

**Expected behavior (REQUIRED)**
No wonky underline. See screenshot.

**Defold version (REQUIRED):**
  - Version [e.g. 1.2.171]

**Platforms (REQUIRED):**
 - Platforms: MacOS Catalina 10.15.5

<img width="857" alt="Screen Shot 2020-07-26 at 09 07 57" src="https://user-images.githubusercontent.com/8721/88483865-82959b80-cf1f-11ea-8716-b7d9645abb5b.png">

**Comment by britzl** [comment]
I'm not sure why it renders with that initial little hook in the link. But the link should work though and it should trigger a build of the project. Can you confirm that it builds the project?

The Defold markdown viewer supports a number of different special links that will trigger actions in the editor. This particular one is:

```
[build and run](defold://build)
```

**Comment by slater** [comment]
For sure, this is purely a cosmetic issue - the links work fine, the project builds

**Comment by britzl** [comment]
We won't spend time investigating and trying to solve this. The problem will hopefully resolve itself if/when we update the dependencies used when rendering markdown in the editor.
