### ISSUE TITLE
Crash on iOS

### ISSUE THREAD

**Issue by AGulev** [defold/defold#5045]
I got the following message after rejected app review:

_Guideline 2.1 - Performance - App Completeness

We were unable to review your app as it crashed on launch. We have attached detailed crash logs to help troubleshoot this issue._

Unfortunately, I can't symbolicate their crash logs because of this issue.

But we were able to reproduce one crash (I hope it's the same) on one of the devices by following steps:

Open game
Wait while the screen will be blocked by OS
Unblock screen
I got a crash log:

![image](https://user-images.githubusercontent.com/2209596/74085460-64bfa180-4a79-11ea-9ed4-f396f95901ba.png)

**Comment by JCash** [comment]
@AGulev Do you have any other clues/info about your app setup?
What extensions are you using?
Do you have many textures/how large are they?
Do you use a custom render script? What does it look like?

**Comment by AGulev** [comment]
I'm not sure, but it looks like [this](https://github.com/defold/defold/issues/5279) issue is related, but on Android.

**Comment by AGulev** [comment]
outdated
