### ISSUE TITLE
Trying to open project without folder with '.render' files crash the editor

### ISSUE THREAD

**Issue by Dragosha** [defold/defold#5055]
I've copy one my project without .render and renderscript files. An editor just closing when selected this project. Adding an origin render folder solved the issue.

Editor log:
[log.txt](https://github.com/defold/defold/files/4994754/log.txt)

<hr/>

<table>
<tr><td>Build time</td><td>2020-07-25T06:13:26.934742</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>7a64a72ca0d10f1583edab5b4317499cdc8c64e5</td></tr>
<tr><td>Defold engine sha</td><td>29b8e598b0bce19b274327c5d9711f78b3bd0c22</td></tr>
<tr><td>Defold version</td><td>1.2.171</td></tr>
<tr><td>GPU</td><td>GeForce GTX 1060 6GB/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 442.23</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by AGulev** [comment]
Can't reproduce. Feel free to reopen if you'll be able to reproduce it (with a reproduction project.)
