### ISSUE TITLE
iOS: Black bars since 1.2.171

### ISSUE THREAD

**Issue by marconett** [defold/defold#5056]
**Describe the bug (REQUIRED)**
There are black bars around my app on iOS:

![Simulator Screen Shot - iPhone 11 - 2020-07-29 at 19 41 24](https://user-images.githubusercontent.com/3315507/88834692-7f770580-d1d4-11ea-8133-2fd29b127e9e.png)

**To Reproduce (REQUIRED)**
1. `git clone https://github.com/defold/template-mobile`
2. Build for iOS

**Expected behavior (REQUIRED)**
No black bars.

**Defold version (REQUIRED):**
  - 1.2.171

**Platforms (REQUIRED):**
 - Platforms: iOS
 - Device: iPhone XS

**Additional context (OPTIONAL):**
I know there are a bunch of forum posts about this exact problem, but I suspect this might be a bug related to #3771.

I based my game on https://github.com/defold/template-mobile and never had problems with this before. A build of my game from 3 months ago (not sure which Defold version) does not show those problems. But if I build the exact same code (same git commit) with 1.2.171, I get black bars. In fact, you now get black bars with the official mobile template as well.

**Comment by marconett** [comment]
It really seems to be a bug with 1.2.171.

Building my game with 1.2.170, I do not have black bars. Although building `template-mobile` with 1.2.170, I still get the bars (no idea why).

**Comment by britzl** [comment]
In 1.2.171 we introduced support for iOS Storyboards (https://forum.defold.com/t/defold-1-2-171-has-been-released/65837) and deprecated the use of launch images (Apple stopped recommending the use of launch images quite some time ago). I am guessing that you have a custom Info.plist file which doesn't include the default storyboard?

**Comment by marconett** [comment]
You're right, I had a custom Info.plist. Removing that fixes my issue.

Sorry. I had no idea the file was even there, so I didn't even think about looking at it as the source of the problem.
