### ISSUE TITLE
Add iOS 14 support

### ISSUE THREAD

**Issue by britzl** [defold/defold#5057]
[iOS 14](https://developer.apple.com/ios/) will require a few changes:

* User privacy changes
  * On iOS 14, apps will be required to ask users for permission to track them across apps and websites owned by other companies. Later this year, the App Store will help users understand apps’ privacy practices, and you’ll need to enter your privacy practice details into App Store Connect for display on your product page.    
* Use Xcode 12 beta and these resources to build your apps for iOS 14.

**Comment by britzl** [comment]
Release date mid-September based on release date of previous iOS versions

**Comment by britzl** [comment]
There's an Apple event on the 15th of September. At first it was thought to be the time when iOS 14 was announced: https://arstechnica.com/gadgets/2020/09/apples-next-event-is-on-september-15/

But it may be that it's only the announcement of a new Apple Watch: https://www.bloomberg.com/news/articles/2020-09-08/apple-to-hold-online-launch-event-on-sept-15

**Comment by britzl** [comment]
Release of iOS 14 is today, the 16th of September.

**Comment by JCash** [comment]
Also https://github.com/defold/extender/pull/175
