### ISSUE TITLE
Add a timer.finish(handle, cancel)

### ISSUE THREAD

**Issue by subsoap** [defold/defold#5066]
**Is your feature request related to a problem? Please describe (REQUIRED):**
Sometimes you may want to cancel the timer from counting down but still run any callback it may have inside of it.

**Describe the solution you'd like (REQUIRED):**
Add ```timer.finish(handle, cancel)``` which would effectively set its time left to 0 and call its callback function. Maybe include a cancel bool to finish and cancel to disable any repeating timers while still running the callback.

**Describe alternatives you've considered (REQUIRED):**
Alternative would be to include callback code in multiple places and call it in the second place if there is need to cancel a timer.

**Comment by britzl** [comment]
Could also be an option to timer.cancel()
