### ISSUE TITLE
Publishing HTML5 gives error "both async and sync fetching of the wasm failed"

### ISSUE THREAD

**Issue by trojanfoe** [defold/defold#5072]
**Describe the bug (REQUIRED)**

Sample game "Linker sample game" when published to HTML5 fails to load.

**To Reproduce (REQUIRED)**

1. Create new project based on sample "Linker sample game".
2. Bundle to HTML5.
3. Load game index.html.
4. observe nothing happening past load screen.
5. See error "both async and sync fetching of the wasm failed" in the browser JS console.

**Expected behavior (REQUIRED)**

Game works.

**Defold version (REQUIRED):**
  - Version [e.g. 1.2.155]

Version 1.2.171

**Platforms (REQUIRED):**
 - Platforms: [e.g. iOS, Android, Windows, macOS, Linux, HTML5]
 - OS: [e.g. iOS8.1, Windows 10, High Sierra]

Windows 10 2004.
Google Chrome 84.0.4147.105.

**Minimal repro case project (OPTIONAL):**
Please attach a minimal project where the bug is reproduced. This will greatly help the person trying to investigate and fix the bug.

See "Linker sample game"

**Logs (OPTIONAL):**
Please provide relevant logs from engine, editor or build server. Learn where the logs are stored [here](https://defold.com/manuals/getting-help/#log-files).

failed to asynchronously prepare wasm: RuntimeError: abort(both async and sync fetching of the wasm failed). Build with -s ASSERTIONS=1 for more info.

**Workaround (OPTIONAL):**
If there is a workaround, please describe it here.

None.

**Screenshots (OPTIONAL):**

**Additional context (OPTIONAL):**

**Comment by britzl** [comment]
How do you "Load game index.html"? Are you uploading the files to a web server somewhere or are you running a local server?

**Comment by trojanfoe** [comment]
I am just double-clicking on the file in the file system.  Do I need to run a local server?

**Comment by britzl** [comment]
Yes, you need to host the files form a web server. Browsers nowadays do not allow pages to load additional content (in this case wasm files and game assets) from local disk.

Mentioned here: https://defold.com/manuals/html5/#faq

**Comment by trojanfoe** [comment]
Yup confirmed.  python -m http.server works lovely.

Sorry to waste your time.

n00b out...
