### ISSUE TITLE
Animations are played at incorrect speed when Editor is launched and used on a 144Hz monitor.

### ISSUE THREAD

**Issue by FylmTM** [defold/defold#5075]
**Describe the bug (REQUIRED)**

I have 3-monitor setup:
Main one - 144Hz
Secondary 1 - 144Hz
Secondary 2 - 60Hz

When I launch and use Defold editor on my main monitor all animations that I play from atlas are played at much faster rate than they should be.

When I move Defold editor to secondary monitor that is 60Hz animations are playing at expected speed.

**To Reproduce (REQUIRED)**

1. Create new project from "Movement tutorial"
2. Open `assets/sprites.atlas`
3. Click on `spaceship` animation in Outline
4. Click `View -> Play` 
5. Observe animation

**Expected behavior (REQUIRED)**

When I play animation in Defold editor it should play at configured FPS, regardless of what monitor I use.

**Defold version (REQUIRED):**
  - Version 1.2.171

**Platforms (REQUIRED):**
 - Platforms: Windows
 - OS: Windows 10
 - Device: N/A

**Minimal repro case project (OPTIONAL):**

"Movement tutorial" project with spaceship animation can be used.

**Logs (OPTIONAL):**

N/A

**Workaround (OPTIONAL):**

N/A

**Screenshots (OPTIONAL):**

Here are video recordings: https://drive.google.com/drive/folders/19oKY_s_Wc-a6H3Zb4d8raSerdfBxUwbU?usp=sharing

**Additional context (OPTIONAL):**

N/A

**Comment by JCash** [comment]
Is launching on the display required to invoke the issue, or is it enough to move the editor to that display?

**Comment by britzl** [comment]
https://github.com/defold/defold/blob/dev/editor/src/clj/editor/scene.clj#L1116

From Mats: I think we could just pipe in the delta-time from this ui/->timer callback and it should work. Not sure why it is so important that it be deterministic. Perhaps stuff like particle sim breaks down if the delta time varies too much or something?

https://github.com/defold/defold/blob/dev/editor/src/clj/editor/app_view.clj#L1461

Although it seems the tick-fn is only called with the elapsed time, so we'd have to add the delta as an argument to all tick-fns: 

https://github.com/defold/defold/blob/dev/editor/src/clj/editor/ui.clj#L1923

**Comment by K-Klear** [comment]
I can confirm this is not a multi-display issue, though it seems you're already on top of this. It happens exactly as described on my single-monitor setup. I've timed it (poorly) and the results are close enough to 2.4 times faster in editor than they are in game or after switching to 60hz mode.

Cheers!

**Comment by zarkua** [comment]
confirmed. I had tons of animations in my game and it took me some time to get what I had in mind.

**Comment by matgis** [comment]
We could pass the delta-time from the `ui/->timer` to the `tick-fn` all the way down to `scene/update-updatables` and use a non-deterministic timestep.

**Comment by britzl** [comment]
Closed via #7570
