### ISSUE TITLE
GUI text shadow offsets text position

### ISSUE THREAD

**Issue by totebo** [defold/defold#5077]
**Describe the bug (REQUIRED)**
Without shadow:
![6d85eb401ff83fda18dfedfa2d19d37dcf417fa2_2_466x998](https://user-images.githubusercontent.com/4493302/89288401-80cd8580-d64d-11ea-928d-721305337dc8.png)

With shadow:
![ee01eeec80bde64e6a4772c2462bef185c3e4189_2_468x1000](https://user-images.githubusercontent.com/4493302/89288417-862ad000-d64d-11ea-85b9-bf1932e731a8.jpg)

**To Reproduce (REQUIRED)**
1. Use a font with a shadow. 

**Expected behavior (REQUIRED)**
Shadows shouldn't affect the text position.

**Defold version (REQUIRED):**
v1.2.170

**Platforms (REQUIRED):**
iOS, Android, macOS (at least)

**Additional context (OPTIONAL):**
Forum post: https://forum.defold.com/t/gui-text-shadow-offsets-text-position/64797

**Comment by britzl** [comment]
Is this only in the editor or also in the build?

**Comment by totebo** [comment]
Both.
