### ISSUE TITLE
Unable to open *.atlas or *.collection [RESOLVED]

### ISSUE THREAD

**Issue by BearHeathen** [defold/defold#5086]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2020-07-25T06:12:57.931558</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>7a64a72ca0d10f1583edab5b4317499cdc8c64e5</td></tr>
<tr><td>Defold engine sha</td><td>29b8e598b0bce19b274327c5d9711f78b3bd0c22</td></tr>
<tr><td>Defold version</td><td>1.2.171</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"be8dd44f20364f60a74e1a7284a127e3"'>be8dd44f20364f60a74e1a7284a127e3</a></td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) Iris(R) Plus Graphics (ICL GT2)</td></tr>
<tr><td>GPU Driver</td><td>OpenGL ES-CM 1.1 Mesa 20.1.3</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.7.9-1-MANJARO</td></tr>
<table>

**Comment by britzl** [comment]
class jogamp.opengl.es1.GLES1Impl cannot be cast to class com.jogamp.opengl.GL2ES2 (jogamp.opengl.es1.GLES1Impl and com.jogamp.opengl.GL2ES2 are in unnamed module of loader 'app')

**Comment by britzl** [comment]
@BearHeathen please try this: https://defold.com/manuals/linux/#q-why-does-the-defold-editor-crash-when-i-try-to-create-a-new-project-or-open-an-existing-one

**Comment by BearHeathen** [comment]
Worked like a charm! Many thanks!
