### ISSUE TITLE
go.set equivalent in gui namespace

### ISSUE THREAD

**Issue by Alfagun74** [defold/defold#5090]
**Is your feature request related to a problem? Please describe (REQUIRED):**
I'm always frustrated when i want to change a specific property on my gui node like the alpha value of the color

I firstly have to get the current color of the node, store it, change it and set it again:
```
color = gui.get_color(node);
color.w = 0.5
gui.set_color(node, color)
```
instead of just using this (similar to go namespace)
`gui.set(node, "color.w", 0.5)`

**Describe the solution you'd like (REQUIRED):**
I want a gui.set() equivalent to go.set()

**Describe alternatives you've considered (REQUIRED):**
Of course you could just implement something like gui.set_alpha(), but the color property is not the only case where you could use the generic set. (think of scale.x, size.y, rotation.z etc.)

Animations already are able to set gui properties directly. For instance i can animate the specific color.w value of my node.
So a workaround maybe would be to set the values by animating them but that is disgusting and i feel ashamed for even thinking about this so-called "alternative"

**Comment by britzl** [comment]
Thank you for the feature request. This would definitely be an improvement!

**Comment by Insality** [comment]
Ping this topic, this will be super useful for me!

Currently I playing with animation library, and implementing the animation cursor required me to re-calculate the each property individually

There is no way now to do it without additional get_[position|rotation|scale] call with vector allocate

**Comment by JCash** [comment]
We'll limit the scope of this task to only support the property names specified by `gui.PROP_*` (See gui_script..cpp)

**Comment by Alfagun74** [comment]
definitely took a minute
