### ISSUE TITLE
Mouse 4 and Mouse 5 throwing exceptions in Editor

### ISSUE THREAD

**Issue by Alfagun74** [defold/defold#5091]
**Describe the bug (REQUIRED)**
Whenever i press Mouse 4 or Mouse 5 in the Editor i get a window saying:

java.lang.IllegalArgumentException: No matching clause: FORWARD
or
java.lang.IllegalArgumentException: No matching clause: BACK

I have my Microphone Mute Button set to Mouse 4 so its quite frustrating.

**To Reproduce (REQUIRED)**
1. Fire up a Project
2. Press Mouse 4 or Mouse 5 Button
3. See error

**Expected behavior (REQUIRED)**
To put it simply: Nothing should happen.
If the keys are not bound there shouldn't be an exception

**Defold version (REQUIRED):**
  - Version 1.2.171

**Platforms (REQUIRED):**
 - Platforms: Windows
 - OS: Windows 10

**Screenshots (OPTIONAL):**
![image](https://user-images.githubusercontent.com/22225051/89799343-a5ce6680-db2d-11ea-9995-d70460c6219a.png)

**Additional context (OPTIONAL):**
<hr>
<table>
<tr><td>Build time</td><td>2020-08-10T10:25:52.880657</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>ec66fdda665b28467177b20254c4e946b7e59e59</td></tr>
<tr><td>Defold engine sha</td><td>29b8e598b0bce19b274327c5d9711f78b3bd0c22</td></tr>
<tr><td>Defold version</td><td>1.2.171</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"0dd6607a35f94a7aa88a5bcf2a940e55"'>0dd6607a35f94a7aa88a5bcf2a940e55</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 1080 Ti/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 451.67</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by alcorrius** [comment]
I guess it would be the easiest first issue. I have mapped MouseButton/BACK and MouseButton/FORWARD to nil so there will be no exception with Mouse 4/5 click. Tested on Windows 10. I can prepare pull request.

**Comment by britzl** [comment]
Yes, please prepare a PR that we can review!

**Comment by britzl** [comment]
Closed by https://github.com/defold/defold/pull/5654
