### ISSUE TITLE
Referencing the gui you are working on, in a template node crashes the engine

### ISSUE THREAD

**Issue by Alfagun74** [defold/defold#5092]
**Describe the bug (REQUIRED)**
I started working on guis and misclicked when selecting a template for my template node. 
So i accidentally selected the gui that i am creating the template in. 
The engine crashed because i created some kind of template-inception.

**To Reproduce (REQUIRED)**
1. Create a GUI File
2. Create a Template Node in that GUI
3. Select the GUI File you created in the Template List
4. See "Defold is not answering"

**Expected behavior (REQUIRED)**
It should not be posssible to open the GUI you're in as a template it doesnt make any sense if you dont want to produce the human centipede movie in defold.

**Defold version (REQUIRED):**
- 1.2.171

**Platforms (REQUIRED):**
 - Platforms: Windows
 - OS: Windows 10

**Comment by AGulev** [comment]
we have newer issue in one of the projects: https://github.com/defold/defold/issues/8014
