### ISSUE TITLE
WebGL warnings in console are confusing

### ISSUE THREAD

**Issue by aglitchman** [defold/defold#5094]
**Describe the bug**
I know that new Defold devs often ask if it is an error or what?...

So, these two warnings in a browser console are annoying and confusing:

Chrome:
```
WebGL: INVALID_ENUM: getParameter: invalid parameter name
WebGL: INVALID_ENUM: getParameter: invalid parameter name
```

Firefox:
```
WebGL warning: getParameter: pname: Invalid enum value MAX_ELEMENTS_VERTICES
WebGL warning: getParameter: pname: Invalid enum value MAX_ELEMENTS_INDICES
```

Safari: https://forum.defold.com/t/invalid-enum-errors-html5-test-builds/64042

**Defold version:**
  - 1.2.171 and 1.2.172 BETA

**Platforms:**
 - Platforms: HTML5
 - Browsers: Chrome (all Chromium-based - Opera, Edge, etc), Firefox, Safari.

**Workaround:**
MAX_ELEMENTS_VERTICES and MAX_ELEMENTS_INDICES are only available in WebGL 2.0 context. Defold uses WebGL 1.0 context. 

So, there are two ways:
1. Enable WebGL 2 to get rid of these warnings.

https://emscripten.org/docs/porting/multimedia_and_graphics/OpenGL-support.html:
> To target WebGL 2, pass the linker flag `-s MAX_WEBGL_VERSION=2`. Specifying this flag enables (and defaults to, unless otherwise specified at context creation time) the creation of WebGL 2 contexts at runtime, but it is still possible to create WebGL 1 contexts, so applications can choose whether to require WebGL 2 or whether to support a fallback to WebGL 1.

If a browser doesn't support WebGL 2 then Emscripten will fallback to WebGL 1, look at https://github.com/emscripten-core/emscripten/blob/6cf6d45e52ee9f67d25049166c540d54b8f69501/src/library_browser.js#L321

2. [Avoid getting these parameters in HTML5 builds.](https://github.com/defold/defold/blob/f79b45eae9189f00daa075eec503aec66b5a39cc/engine/graphics/src/opengl/graphics_opengl.cpp#L913)

**Comment by britzl** [comment]
We're passing MAX_WEBGL_VERSION=2 nowadays:

https://github.com/defold/defold/blob/dev/build_tools/waf_dynamo.py#L452
