### ISSUE TITLE
Defold shows an Error Dialog after the creation of any script

### ISSUE THREAD

**Issue by juliovivian** [defold/defold#5095]
### Steps to reproduce Simply create any script

<hr/>

<table>
<tr><td>Build time</td><td>2020-07-25T06:12:57.931558</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>7a64a72ca0d10f1583edab5b4317499cdc8c64e5</td></tr>
<tr><td>Defold engine sha</td><td>29b8e598b0bce19b274327c5d9711f78b3bd0c22</td></tr>
<tr><td>Defold version</td><td>1.2.171</td></tr>
<tr><td>GPU</td><td>Mesa DRI Intel(R) HD Graphics 400 (Braswell) </td></tr>
<tr><td>GPU Driver</td><td>3.0 Mesa 18.3.6</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux (Debian Buster)</td></tr>
<tr><td>OS version</td><td>4.19.0-9-amd64</td></tr>
<table>

**Comment by JCash** [comment]
Please provide the editor log as well, since it most likely contains relevant info.

**Comment by britzl** [comment]
Closing due to lack of information.
