### ISSUE TITLE
html5 progress bar excludes engine

### ISSUE THREAD

**Issue by GreenArrow18** [defold/defold#5096]
**Describe the bug (REQUIRED)**
Progress bar does not show the loading progress of the engine itself. It only shows loading progress of the app archive bundle. 

**To Reproduce (REQUIRED)**
1. Open Chrome developer console
2. Select a 3G network preset to simulate a slow connection
3. Load the app's page
4. Note that the progress bar does not appear until after the engine has been fully loaded (which may take some time)
5. Progress bar will show loading status of the app archive folder only

**Expected behavior (REQUIRED)**
Progress bar should ideally include the loading progress of the engine itself.

**Defold version (REQUIRED):**
  - 1.2.172

**Platforms (REQUIRED):**
 - Platforms: HTML5
 - OS: Windows 10
 - Browser: Google Chrome

**Additional context (OPTIONAL):**
For html5 builds, the engine takes up a significant portion of the entire download. So e.g. if you app size is 2MB, and the wasm engine is also 2MB, say it takes 60sec to load everything: for the initial 30sec (50% of the total time) there is no visual indicator of what’s happening. For first time visitors, it would appear as if the page is stuck or not doing anything, unless you wait long enough.

In some instances, the engine size may be even bigger than the app size itself, so I think it's very important to show some progress while the engine is being downloaded.

Also related: If engine loading can be included in the progress bar, then perhaps other scripts in the page can also be optionally  included? e.g. Facebook SDK

**Comment by aglitchman** [comment]
I see that the issue is going to be fixed soon. I want to add a few notes just to save @britzl's time :) 

1. To manually init WASM use [Module.instantiateWasm](https://emscripten.org/docs/api_reference/module.html#Module.instantiateWasm). An example is [here](https://github.com/emscripten-core/emscripten/blob/2bca083cbbd5a4133db61fbd74d04f7feecfa907/tests/manual_wasm_instantiate.html#L170).
2. To asynchronously load JS:
```js
function load_script_async(src) {
    var xhr = new XMLHttpRequest();
    var tag = document.createElement("script");
    xhr.open("GET", src, true);
    xhr.onload = function (e) {
        if (xhr.readyState === 4) {
            if (xhr.status === 200) {
                tag.text = xhr.response;
                document.head.appendChild(tag);
            } else {
                // console.error("ASYNC: Error loading script", src, xhr.response);
            }
        }
    };
    xhr.onprogress = function (e) {
        if (e.total > 0) {
            // Progress.updateProgress((e.loaded / e.total) * 100);
        }
    };
    xhr.onerror = function (evt) {
        // console.error("Error loading script", evt);
    };
    xhr.send();
}

function load_engine() {
    if (Module["isWASMSupported"]) {
        load_script_async("{{exe-name}}_wasm.js");
    } else {
        load_script_async("{{exe-name}}_asmjs.js");
    }
}
```
3. It's hard to predict the gzipped size of WASM and JS files, so you can split the progress like this:
- Asm.js: 50% JS, 50% assets.
- Wasm: 10% JS, 40% WASM, 50% assets.
