### ISSUE TITLE
Opening a collection file gives error java.lang.ClassCastException

### ISSUE THREAD

**Issue by lostcaus3** [defold/defold#5099]
### Expected behaviour
Should open main.collection file

### Actual behaviour
gives error as follows
java.lang.ClassCastException: class jogamp.opengl.es1.GLES1Impl cannot be cast to class com.jogamp.opengl.GL2ES2 (jogamp.opengl.es1.GLES1Impl and com.jogamp.opengl.GL2ES2 are in unnamed module of loader 'app')

### Steps to reproduce
double click on main.collection on ubuntu(20.04)
<hr/>

<table>
<tr><td>Build time</td><td>2020-08-10T10:25:19.474180</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>ec66fdda665b28467177b20254c4e946b7e59e59</td></tr>
<tr><td>Defold engine sha</td><td>29b8e598b0bce19b274327c5d9711f78b3bd0c22</td></tr>
<tr><td>Defold version</td><td>1.2.171</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"3dfe81828fb440e5bddf5a0a1bfb4ebe"'>3dfe81828fb440e5bddf5a0a1bfb4ebe</a></td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) HD Graphics 620 (KBL GT2)</td></tr>
<tr><td>GPU Driver</td><td>OpenGL ES-CM 1.1 Mesa 20.0.8</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.4.0-42-generic</td></tr>
<table>

**Comment by britzl** [comment]
class jogamp.opengl.es1.GLES1Impl cannot be cast to class com.jogamp.opengl.GL2ES2 (jogamp.opengl.es1.GLES1Impl and com.jogamp.opengl.GL2ES2 are in unnamed module of loader 'app')

@lostcaus3 please give this a try: https://defold.com/manuals/linux/#q-why-does-the-defold-editor-crash-when-i-try-to-create-a-new-project-or-open-an-existing-one

**Comment by britzl** [comment]
No user feedback. Closing.
