### ISSUE TITLE
SVG Support

### ISSUE THREAD

**Issue by Alfagun74** [defold/defold#5104]
**Is your feature request related to a problem? Please describe (REQUIRED):**
I'm always frustrated when im required to convert my .svg files to non vector-formats For the use in Defold.
I would like Defold to support .svg Format.
Vector graphics are great for scaling purposes and i would totally expect it in a cross-platform engine.

**Describe the solution you'd like (REQUIRED):**
Build in SVG Support.

**Comment by britzl** [comment]
What exactly are you requesting? SVG support at the import stage in the editor/build pipeline or actual runtime support? 

For editor/build pipeline: You could obviously convert it before importing it like you are already doing. Having it as a part of the asset pipeline would obviously be better but it is not something we have planned.

For runtime support: It should be possible to create an extension to load an SVG at runtime and convert it to a texture.

**Comment by JCash** [comment]
We will not support .SVG in the runtime, so the best you can hope for is automatically converting them to rasterized images when we bake the atlases.

**Comment by Alfagun74** [comment]
I guess ill request the Proposal @JCash had then.

**Comment by britzl** [comment]
We have decided to not support SVG when importing/baking to an atlas. SVG images should be converted to the correct sized PNG before adding to an atlas, OR be supported through a native extension.
