### ISSUE TITLE
Updated extension-firebase-analytics

### ISSUE THREAD

**Issue by britzl** [defold/defold#5110]
**Task (REQUIRED):**
The Firebase Analytics extension (https://github.com/defold/extension-firebase-analytics) needs to be updated to more recent versions of both the Android and iOS SDKs

**Expected outcome (REQUIRED):**
The extension should use more recent versions of the SDKs.

**Comment by AGulev** [comment]
Done. https://github.com/defold/extension-firebase-analytics/releases/tag/1.4.0
