### ISSUE TITLE
java.lang.AssertionError: Assert failed: (and root (.isDirectory root))

### ISSUE THREAD

**Issue by Ragetto** [defold/defold#5132]
### Actual behaviour
Error displayed when reading the walking astronaut tutorial
java.lang.AssertionError: Assert failed: (and root (.isDirectory root))

### Steps to reproduce
Didn't manage to reproduce it

<hr/>

<table>
<tr><td>Build time</td><td>2020-08-27T04:44:14.453565</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>96c820fb9fb9c3d6ddec975e5e1dde4762b0228d</td></tr>
<tr><td>Defold engine sha</td><td>dedf1ed10d96c92df6e361f5494531c79af4c1cf</td></tr>
<tr><td>Defold version</td><td>1.2.172</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"fc624de67f10475bbad9fa3e17715798"'>fc624de67f10475bbad9fa3e17715798</a></td></tr>
<tr><td>GPU</td><td>Intel(R) UHD Graphics 620</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 - Build 27.20.100.7989</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
This happens infrequently according to crash reports. Please let us know if it happens again and if you can tie it to something you did.

**Comment by britzl** [comment]
No new info. Closing.
