### ISSUE TITLE
Crash when using hashes? Not sure

### ISSUE THREAD

**Issue by subsoap** [defold/defold#5133]
```
INFO:CRASH: Successfully wrote Crashdump to file: C:\Users\subso\AppData\Roaming\Defold/_crash
ERROR:CRASH: CALL STACK:

 0 0x7FF70DF17A70 _snscanf_s <unknown>:0
 1 0x869A70 alcCreateContext <unknown>:0
 2 0x7FFECDB9F400 UnhandledExceptionFilter <unknown>:0
 3 0x7FFED0782F80 memset <unknown>:0
 4 0x7FFED076C5C0 __C_specific_handler <unknown>:0
 5 0x7FFED07810B0 __chkstk <unknown>:0
 6 0x7FFED0749E70 RtlRaiseException <unknown>:0
 7 0x7FFED077FE10 KiUserExceptionDispatcher <unknown>:0
 8 0x7FF70DE80000 Ordinal0 <unknown>:0
 9 0x7FF70DEA0580 snprintf <unknown>:0
10 0x7FF70DF01BB0 _snprintf <unknown>:0
11 0x7FF70DF17A70 _snscanf_s <unknown>:0
12 0x7FF70DF44F50 dmHashReverseSafe64 <unknown>:0
13 0x7FF70DF44F50 dmHashReverseSafe64 <unknown>:0
14 0x7FF70DF44F50 dmHashReverseSafe64 <unknown>:0
15 0x7FF70DF44F50 dmHashReverseSafe64 <unknown>:0
16 0x7FF70E009310 Particle_Hash <unknown>:0
17 0x7FF70DF44F50 dmHashReverseSafe64 <unknown>:0
18 0x7FF70DF44F50 dmHashReverseSafe64 <unknown>:0
19 0x7FF70DEF4510 sprintf <unknown>:0
20 0x7FF70DF44F50 dmHashReverseSafe64 <unknown>:0
21 0x7FF70DF44F50 dmHashReverseSafe64 <unknown>:0
22 0x7FF70DEF4510 sprintf <unknown>:0
23 0x7FF70E17BD90 LZ4MaxCompressedSize <unknown>:0
24 0x7FFECFE57BC0 BaseThreadInitThunk <unknown>:0
25 0x7FFED074CE30 RtlUserThreadStart <unknown>:0

INFO:CRASH: Successfully wrote MiniDump to file: C:\Users\subso\AppData\Roaming\Defold/_crash.dmp
```

Project has a variety of NEs but I was not doing anything related to them when the crash happened. The crash happened when related to grabbing random items from a table.

This zip has crash dump, dmengine.pdb and exe
[x86-win32.zip](https://github.com/defold/defold/files/5147544/x86-win32.zip)

<hr/>

<table>
<tr><td>Build time</td><td>2020-08-27T04:44:14.453565</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>96c820fb9fb9c3d6ddec975e5e1dde4762b0228d</td></tr>
<tr><td>Defold engine sha</td><td>dedf1ed10d96c92df6e361f5494531c79af4c1cf</td></tr>
<tr><td>Defold version</td><td>1.2.172</td></tr>
<tr><td>GPU</td><td>GeForce GTX 1060 6GB/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 446.14</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by subsoap** [comment]
I can get it to happen reliably.  Going to try to make a min project where it happens.

**Comment by subsoap** [comment]
Doesn't crash in mini project with the same JSON file. Seems to be related to this code too quickly, still investigating 

```
		if steamworks then
			local rng = math.random(0,100)
			if rng >= 95 then
				self.true_text = steamworks.friends_get_persona_name()
				self.true_text = self.true_text:gsub('%W%p', '')
				self.true_text = self.true_text:gsub([[\n]], '')
				self.true_text = self.true_text:gsub([[/]], [[//]])
				self.true_text = self.true_text:gsub([[\]], [[\\]])
				self.true_text = self.true_text:sub(1, 20)
				if self.true_text == "" or self.true_text == " " then
					self.true_text = random_prefix(self) .. " " .. random_suffix(self)
				end
			else
				self.true_text = random_prefix(self) .. " " .. random_suffix(self)
			end
		else
			self.true_text = random_prefix(self) .. " " .. random_suffix(self)
		end
```

**Comment by subsoap** [comment]
This does not crash, so I'd guess it's related to the Steamworks persona name needing to be cached instead of attempting to get it every time / trying to get it when Steam isn't actually running.

```
function on_input(self, action_id, action)
	if action.released then
		for i=1, 100 do
			local rng = math.random(0,100)
			if rng >= 95 then
				self.true_text = ""
				self.true_text = self.true_text:gsub('%W%p', '')
				self.true_text = self.true_text:gsub([[\n]], '')
				self.true_text = self.true_text:gsub([[/]], [[//]])
				self.true_text = self.true_text:gsub([[\]], [[\\]])
				self.true_text = self.true_text:sub(1, 20)
				if self.true_text == "" or self.true_text == " " then
					local prefix = self.lists.prefix[math.random(#self.lists.prefix)]
					local suffix = self.lists.suffix[math.random(#self.lists.suffix)]

					self.true_text = prefix .. " " .. suffix
				end
			else
				local prefix = self.lists.prefix[math.random(#self.lists.prefix)]
				local suffix = self.lists.suffix[math.random(#self.lists.suffix)]

				self.true_text = prefix .. " " .. suffix
			end

			
			print(self.true_text)
		end
	end
end
```

What is weird though is that in the main project if the prefix / suffix list is short enough it never crashes either only when it's made longer that it crashes so this may still be related to something in the engine I don't know.

**Comment by subsoap** [comment]
Crash is 100% caused by trying to get Steam name when Steam is not actually running so this is probably not a real problem. I'll close.

steamworks.friends_get_persona_name() = crash when Steam is not running

**Comment by britzl** [comment]
Hmm, shouldn't we fix this in the Steamworks extension though?

**Comment by subsoap** [comment]
Yes, though it might not be worth the time just knowing about it may be enough. My mistake here was not checking first in this code if Steam was running, other places we do and don't have problems. It is a pitfall.
