### ISSUE TITLE
Add Defold to Steam

### ISSUE THREAD

**Issue by subsoap** [defold/defold#5134]
I've asked for this a bunch of times but there is no issue for it so thumbs up this issue if you want to see this.

Just being on Steam would dramatically increase organic visibility through the usage of the tool and friends list of people who use it. This discovery will help to get more people to try Defold, grow the community, and result in more sponsors.

The sooner it's done, the better chance for the long term results.

**Comment by subsoap** [comment]
This has happened!

https://store.steampowered.com/app/1365760/

**Comment by britzl** [comment]
Thank you for your amazing help throughout the process @subsoap !
