### ISSUE TITLE
Add a sponsor nag to the about popup

### ISSUE THREAD

**Issue by subsoap** [defold/defold#5135]
Something simple like this. People have reasons to look at the about, so it can be a good unobtrusive place to put the reminder for people to eventually support. I'd link directly to the Github sponsor page since it's the only place you get 100% of community donations, other places take a cut afaik.

![2020-08-30-23_05_38-About](https://user-images.githubusercontent.com/409170/91688796-ae580280-eb17-11ea-9e58-971b8d39f622.png)

**Comment by britzl** [comment]
Fixed in commit https://github.com/defold/defold/commit/7b08eb44afbc9d757d9c29d7801f6d5956e09bc9
