### ISSUE TITLE
Crash related to GUI particlefx somehow

### ISSUE THREAD

**Issue by subsoap** [defold/defold#5158]
Windows 10

This printed in console

```
Assertion failed: i < Size(), file D:\a\defold\defold\tmp\dynamo_home\sdk\include\dmsdk/dlib/array.h, line 429
```

Crash
[crash.zip](https://github.com/defold/defold/files/5172251/crash.zip)

Symbols
[build.zip](https://github.com/defold/defold/files/5172247/build.zip)

Doing this to the GUI particlefx in question made the crash stop happening
```
gui.stop_particlefx()
gui.delete_node()
```

Here is the pfx in question if it matters
[achi_unlocked_fx.zip](https://github.com/defold/defold/files/5172280/achi_unlocked_fx.zip)

To add, it is probably related to creating / playing / deleting the same pfx in quick succession in GUI somehow. Don't have a small reproducible at the moment.

**Comment by subsoap** [comment]
It's very likely this was related to Steamworks again. In this case... I accidentally had put steamworks.final() in update and now this crash doesn't happen anymore... There is still the build and symbols to confirm but I think that's it. I'll make an issue on Steamworks extension with some ideas. :P

**Comment by subsoap** [comment]
@JCash Could you look at the symbols to confirm if it's for sure Steamworks or related to particles? We're still getting this even when Steamworks shouldn't be causing it and don't have a 100% reliable way to get the ```Assertion failed: i < Size(), file D:\a\defold\defold\tmp\dynamo_home\sdk\include\dmsdk/dlib/array.h, line 429``` to happen.

**Comment by JCash** [comment]
The `_crash` callstack looks broken, the C function `snprintf` does not call into Defold engine (`dmHashReverseSafe64()`):
```
 1 0x549A70 alcCreateContext <unknown>:0
 2 0x7FF93EDFF400 UnhandledExceptionFilter <unknown>:0
 3 0x7FF941342F80 memset <unknown>:0
 4 0x7FF94132C5C0 __C_specific_handler <unknown>:0
 5 0x7FF9413410B0 __chkstk <unknown>:0
 6 0x7FF941309E70 RtlRaiseException <unknown>:0
 7 0x7FF94133FE10 KiUserExceptionDispatcher <unknown>:0
 8 0x7FF725399CB0 dmHashReverseSafe64 <unknown>:0
 9 0x7FF7253869B0 _snscanf_s <unknown>:0
10 0x7FF725496C50 DecryptXTeaCTR <unknown>:0
11 0x7FF725496C50 DecryptXTeaCTR <unknown>:0
12 0x7FF725399CB0 dmHashReverseSafe64 <unknown>:0
13 0x7FF725310580 snprintf <unknown>:0
14 0x7FF725370AF0 _snprintf <unknown>:0
15 0x7FF725399CB0 dmHashReverseSafe64 <unknown>:0
16 0x7FF725496C50 DecryptXTeaCTR <unknown>:0
17 0x7FF725496C50 DecryptXTeaCTR <unknown>:0
18 0x7FF725399CB0 dmHashReverseSafe64 <unknown>:0
19 0x7FF725399CB0 dmHashReverseSafe64 <unknown>:0
20 0x7FF725399CB0 dmHashReverseSafe64 <unknown>:0
21 0x7FF725399CB0 dmHashReverseSafe64 <unknown>:0
22 0x7FF725399CB0 dmHashReverseSafe64 <unknown>:0
23 0x7FF725364240 sprintf <unknown>:0
24 0x7FF7255C0520 LZ4MaxCompressedSize <unknown>:0
25 0x7FF93F677BC0 BaseThreadInitThunk <unknown>:0
26 0x7FF94130CE30 RtlUserThreadStart <unknown>:0
```

Also, the I'm not sure the dump is created with the exactly same engine as you sent, since Visual Studio won't load it.
The exe in the build.zip you sent has the checksum:
```bash
crash/users/pkeod $ md5 FaerieSolitaireDire.exe
MD5 (FaerieSolitaireDire.exe) = 2719cd2f89906bbc8551875ed3de2fc0
```

What is the checksum of your file? (`C:\Program Files (x86)\Steam\steamapps\common\Faerie Solitaire Dire\FaerieSolitaireDire.exe`)

**Comment by subsoap** [comment]
[sample_2.zip](https://github.com/defold/defold/files/5186675/sample_2.zip)

I might have sent the wrong files, here is another sample.

Also already do not have those old exes anymore so can't send/get info.

**Comment by subsoap** [comment]
Hmm actually those look like they are wrong too.  I will have to get a new example project. Currently we are pretty sure it's related to Steamworks and not Defold itself - probably, but it could be some kind of interaction with the current Steamworks version and loading a lot of resources while unlocking achievements.

**Comment by subsoap** [comment]
[depot_556531_4886930854038776318_FaerieSolitaireDire.exe.zip](https://github.com/defold/defold/files/5186732/depot_556531_4886930854038776318_FaerieSolitaireDire.exe.zip)
[depot_556531_3387709900303531716_FaerieSolitaireDire.exe.zip](https://github.com/defold/defold/files/5186733/depot_556531_3387709900303531716_FaerieSolitaireDire.exe.zip)
[depot_556531_51729830469874982_FaerieSolitaireDire.exe.zip](https://github.com/defold/defold/files/5186734/depot_556531_51729830469874982_FaerieSolitaireDire.exe.zip)
[depot_556531_264003973903251716_FaerieSolitaireDire.exe.zip](https://github.com/defold/defold/files/5186737/depot_556531_264003973903251716_FaerieSolitaireDire.exe.zip)

These are the last exes I have, one of them right?
