### ISSUE TITLE
Pipe bob output to a tab in the editor when bundling from the editor

### ISSUE THREAD

**Issue by subsoap** [defold/defold#5159]
**Is your feature request related to a problem? Please describe (REQUIRED):**
Only seeing a "working" symbol while bundling is good to know it's working but not as helpful as it could be.
There are situations when bob prints out more accurate errors when bundling than the editor reports.
Seeing bob output would also give an actual % completion.

**Describe the solution you'd like (REQUIRED):**
Either add the bob output as it comes in into the console or add another tab for bob

**Describe alternatives you've considered (REQUIRED):**
You can always bundle with bob directly but sometimes you want to use the editor and big projects take a while

**Comment by britzl** [comment]
Fixed in 1.3.6
