### ISSUE TITLE
Let texture compression with bob use more CPU

### ISSUE THREAD

**Issue by subsoap** [defold/defold#5160]
**Is your feature request related to a problem? Please describe (REQUIRED):**
bob does not use as much CPU as it could, let us let bob use more

**Describe the solution you'd like (REQUIRED):**
Let bob use as much CPU as we want to let it use. A big project takes 40m+ with only 20% CPU used on pic related CPU (with other stuff happening on the computer still).

![cpu](https://user-images.githubusercontent.com/409170/92201216-d48be400-ee30-11ea-8b7f-20843fc498f9.png)

Would it be possible to make the texture compression GPU accelerated?

Caching unique texture hash / platform for textures would help with this to lower bundle time on big project (which is the main problem).

**Comment by britzl** [comment]
We will change the way we do texture compression soon and probably transition to use https://github.com/BinomialLLC/basis_universal. It's still in the planning stage but work will commence probably in October.

**Comment by aglitchman** [comment]
*Offtopic* It'd be great if you could also add S3TC compression. 😇

**Comment by britzl** [comment]
BasisU uses a threadpool per texture.

> Caching unique texture hash / platform for textures would help with this to lower bundle time on big project (which is the main problem).

https://github.com/defold/defold/issues/5906
