### ISSUE TITLE
java.lang.NullPointerException: Unknown

### ISSUE THREAD

**Issue by donnttryinfagainnice** [defold/defold#5166]
Every time I attempt to input bindings when I click the input box and then press the key I want to be an input and then this box pops up. I've reinstalled twice and it has not helped.
![CHOOSE ME](https://user-images.githubusercontent.com/70781371/92289720-5a7b5e00-ef09-11ea-91a2-13075e696a49.png)

Many Thanks

**Comment by britzl** [comment]
You closed the issue yourself. May I ask how you solved the problem?

**Comment by donnttryinfagainnice** [comment]
Hey 

I didn’t solve it exactly I just wasn’t adding the input bindings correctly.

The problem did not occur when I did it the correct way. 

Thanks
