### ISSUE TITLE
VirtualBox with Window 10 cannot run defold games

### ISSUE THREAD

**Issue by vbif1** [defold/defold#5170]
**Describe the bug (REQUIRED)**
I have a mac with VirtualBox and Window 10 inside it (Graphics controller: VBoxSvga + 3d acceleration). Defold editor run correctly, but when you build game it asserts and freeze forever (Even on empty projects). I have tried other options for graphic controller in VirtualBox and it gives me event worse results like crash. 

**To Reproduce (REQUIRED)**
1. Have a setup like in Describe section
2. Open any template project from defold menu
3. Press Ctrl + B
4. See error in console 

**Expected behavior (REQUIRED)**
Game runs correctly

**Defold version (REQUIRED):**
  - Version 1.2.172

**Platforms (REQUIRED):**
 - MacOS 10.15.4, VirualBox 6.1.12, Windows10 1709

**Logs (OPTIONAL):**
INFO:DLIB: Log server started on port 49862
INFO:ENGINE: Engine service started on port 49863
INFO:ENGINE: Defold Engine 1.2.172 (dedf1ed)
INFO:ENGINE: Loading data from: build/default
INFO:ENGINE: Initialised sound device 'default'

ERROR:GRAPHICS: dmGraphics::OpenGLSetTexture(2363): gl error 1281: invalid value

Assertion failed: 0, file ..\src\opengl\graphics_opengl.cpp, line 2363

**Comment by britzl** [comment]
Not sure what's wrong really. It works when using Parallels. @JCash ?

**Comment by vbif1** [comment]
Have some experiments with ubuntu under VirtualBox. And I have a similar assert\crash when running OS with 3d accelerations: 
```
ERROR:GRAPHICS: OpenGLSetTexture(2363): gl error 1281: invalid value

dmengine: ../src/opengl/graphics_opengl.cpp:2363: void dmGraphics::OpenGLSetTexture(dmGraphics::HTexture, const dmGraphics::TextureParams &): Assertion `0' failed.
INFO:CRASH: Successfully wrote Crashdump to file: /home/vbif/.Defold/_crash
```
And this issue disapear when 3d acceleration disabled. Editor in all variants works fine, even the shadertoy example render "space bitmap" in collection view of editor.

**Comment by JCash** [comment]
I'm not at all sure what is going on here.
Unfortunately, I've only had bad experiences with VirtualBox in the past.
I suggest you debug the engine and try to see if you can come up with a setting that works.

**Comment by britzl** [comment]
Closing until we know if there's an actual issue here. We will not investigate this.
