### ISSUE TITLE
Timeout is ignored for DNS lookups

### ISSUE THREAD

**Issue by subsoap** [defold/defold#5176]
When there is no Internet connection the timeout seconds are ignored, and instead 60 seconds of time is used. Instead the timeout time should be used when there is no Internet connection.

Example

```	
	http.request("https://www.google.com/", "GET", function(self, id, response)
		pprint(response)
	end, nil, nil, {timeout = 1})
```	
Run this with no Internet connection (tested on Windows 10) instead of timing out after 1 second, it takes 60 seconds to time out.
```
ERROR:SCRIPT: Unable to create HTTP connection to 'https://www.google.com/'. No route to host?
WARNING:DLIB: Profiler Message.Dispatch @__http_worker_1 took 60.021 seconds
DEBUG:SCRIPT: 
{ --[[000001CE1F3CA9F0]]
  status = 0,
  response = "",
  headers = { } --[[000001CE1F3CAA80]]
}
```

**Comment by britzl** [comment]
I think there are two time-outs at play under the hood. The first is the DNS lookup timeout and the second is the actual sending and receiving of data. I believe it is only the second timeout that is affected by the setting to http.request().

**Comment by britzl** [comment]
Here's the timeout coming from Lua: https://github.com/defold/defold/blob/dev/engine/script/src/script_http.cpp#L186

Which ends up in the HTTP client here: https://github.com/defold/defold/blob/dev/engine/dlib/src/dlib/http_client.cpp#L307

And used here: https://github.com/defold/defold/blob/dev/engine/dlib/src/dlib/http_client.cpp#L1009

In the connection pool: https://github.com/defold/defold/blob/dev/engine/dlib/src/dlib/connection_pool.cpp#L333

BUT the timeout is not passed along to the DNS lookup: https://github.com/defold/defold/blob/dev/engine/dlib/src/dlib/connection_pool.cpp#L350

And for IPv6: https://github.com/defold/defold/blob/dev/engine/dlib/src/dlib/connection_pool.cpp#L357

And the DNS lookup has a timeout of 30 seconds: https://github.com/defold/defold/blob/dev/engine/dlib/src/dlib/dns.cpp#L322

30 (IPv4) + 30 (IPv6) = 60 seconds!

**Comment by subsoap** [comment]
What would be the plan to solve this? Lower the timeouts of those or use the same timeout? Or use a faster way to see if there is even an Internet connection to short circuit early?

**Comment by britzl** [comment]
Well, I wonder why we don't use the same timeout as provided from http.request(). @JCash ?

**Comment by britzl** [comment]
You could also create your own connectivity check (sys.get_connectivity only works on mobile). Untested:


	local function check_connectivity(url, timeout, cb)
		local connected = false

		local handle = timer.delay(timeout, false, function(self, handle, time_elapsed)
			cb(self, connected)
		end)

		http.request(url, "GET", function(self, id, response)
			-- may need to be refined
			connected = response.status >= 200 and response.status < 400
			timer.cancel(handle)
			cb(self, connected)
		end, nil, nil, { timeout = timeout })
	end


	check_connectivity("https://yourserver.com", 30, function(self, connected)
		print("connected: " .. connected)
	end)

**Comment by subsoap** [comment]
My use case right now is for desktop versions which are sensitive to the timeout - if no net connection is shown cached data is used, and if the wait is 1 minute long there's a good chance the cached data won't even be seen by people offline since they will skip right past it in most cases. 

But it is also not a priority at all and only a nice thing to have.

**Comment by JCash** [comment]
> Well, I wonder why we don't use the same timeout as provided from http.request(). @JCash ?

I thought we did.
