### ISSUE TITLE
Defold should pick the best GPU

### ISSUE THREAD

**Issue by subsoap** [defold/defold#5185]
We had a user report that our games were not working on their computer

![err](https://user-images.githubusercontent.com/409170/92684809-2a5a0380-f2eb-11ea-9c99-a908a261e9e4.png)

The user eventually figured out how to solve this

> Fix the problem with your games using the NVIDIA control panel. In the 3D configuration it forces the program to run with the NVIDIA processor. The application used the integrated graphics of the board.
> 
> For your record, this device is a DELL XPS i5 M480 2.67 GHz, 8 GB RAM.  Video: Geforce GT 420M with Windows 7 Home premium SP1 (old laptop).
> 
> Had the same problem with ASUS TUF Gaming FX504 laptop, GPU NVIDIA.

![Faerie config](https://user-images.githubusercontent.com/409170/92684892-655c3700-f2eb-11ea-97f9-d173bf2e120a.jpg)

The thing to get this to work right seems to be GLFW_USE_HYBRID_HPG

https://github.com/glfw/glfw/issues/1545

**Comment by aglitchman** [comment]
Besides that, his integrated GPU should run your game -- [the CPU is compatible with Shader Model 4, along with DirectX 10.1 and OpenGL 2.1 APIs.](http://www.cpu-world.com/CPUs/Core_i5/Intel-Core%20i5%20Mobile%20I5-480M.html) + [wikichip](https://en.wikichip.org/wiki/intel/hd_graphics_(ironlake))

**Comment by subsoap** [comment]
[glinfo.txt](https://github.com/defold/defold/files/5212117/glinfo.txt)

Here's the glinfo I asked him to send first.

**Comment by aglitchman** [comment]
GLFW_USE_HYBRID_HPG was introduced in GLFW 3. Defold uses GLFW 2 and it doesn't have this flag, but it's very easy to implement - [see these lines](https://github.com/glfw/glfw/blob/05dd2fa2986c37e7aee3cba917b1d02a3a189390/src/win32_init.c#L42).

**Comment by JCash** [comment]
There is this branch building now, and perhaps you can download that exe and let your user test (I don't have two gpu's unfortunately)

**Comment by subsoap** [comment]
I don't either but I can probably get someone with one to test, possibly same guy as original issue. Looking at the code, it looks like it should work!

**Comment by AGulev** [comment]
hmm, it seems like the issue is still reproducable (only for amd GPUs maybe?) https://forum.defold.com/t/problem-running-defold-error-dmgraphics-openglflip-1275-gl-error-1280/68902/10

**Comment by defoldino** [comment]
I came to add that in HTML5 computer (Windows 10) with a game made in Defold 1.9.6, and a rtx 3050, the game improved quite a lot when changing Chrome or the whole System preferred graphics processor (the graphic card), so most likely is because of this.

![Image](https://github.com/user-attachments/assets/9fcdac65-cf31-4b16-b8fb-5a588ad50e07)
