### ISSUE TITLE
Solve issue with broken live update index

### ISSUE THREAD

**Issue by britzl** [defold/defold#5186]
**Describe the bug (REQUIRED)**
User report: "Liveupdate index is broken after exception in 90% of times (memory mapped files?). The game is require reinstall to fix that."

**To Reproduce (REQUIRED)**
Waiting for repro steps

**Expected behavior (REQUIRED)**
The liveupdate should fail gracefully and allow the user to retry. If live update fails mid-way the game should not become broken.

**Defold version (REQUIRED):**
  - Version 1.2.172

**Platforms (REQUIRED):**
 - Android, iOS

**Comment by britzl** [comment]
We want to move away from the liveupdate index and instead store as files on disk. We should add a migration step to write out files from the index and then remove the index. And if the index is broken it should be removed.

**Comment by AGulev** [comment]
outdated?

**Comment by AGulev** [comment]
@britzl I think this is outdated issue
