### ISSUE TITLE
Add ability to mount and load resources from zip archives

### ISSUE THREAD

**Issue by britzl** [defold/defold#5189]
**Is your feature request related to a problem? Please describe (REQUIRED):**
From user: "I think Defold should extend resource API to mount zip archives with liveupdate content to resource system and use missing resources directly from the mounted zip."

**Describe the solution you'd like (REQUIRED):**
Investigate if it makes sense to allow the resource system to mount zip archives and access its content without unzipping.

**Describe alternatives you've considered (REQUIRED):**
The alternative is of course to download files one by one instead of as an archive.

**Comment by britzl** [comment]
This will likely solve or help avoid https://github.com/defold/defold/issues/5186

**Comment by JCash** [comment]
Fixed in 1.2.175 Beta
