### ISSUE TITLE
Headless builds on Linux still require libOpenAL etc

### ISSUE THREAD

**Issue by britzl** [defold/defold#5190]
**Describe the bug (REQUIRED)**
Headless builds on Linux are in fact not headless. You still need libOpenAL, libX11, libGL etc

**To Reproduce (REQUIRED)**
Run dmengine_headless on Linux in a non-windowed environment such as TravisCI. Notice that you need to install the libraries.

**Expected behavior (REQUIRED)**
libOpenAL, libGL etc should not be required in headless builds

**Defold version (REQUIRED):**
  - V1.2.172

**Platforms (REQUIRED):**
 - Linux

**Comment by JCash** [comment]
Extender fix:
https://github.com/defold/extender/pull/173
