### ISSUE TITLE
Android App Bundles copy assets to the wrong directory in the aab file

### ISSUE THREAD

**Issue by britzl** [defold/defold#5191]
**Describe the bug (REQUIRED)**
From user: "Create extension with res\android\assets\file_in_assets.txt. Bundle it as apk and you can find this file in assets directory of apk. But if you bundle it as aab you can find this file in base\assets\assets directory of aab."

**To Reproduce (REQUIRED)**
* Create extension with res\android\assets\file_in_assets.txt
* Bundle as APK and you can find this file in assets directory of apk
* Bundle it as AAB you can find this file in base\assets\assets directory

**Expected behavior (REQUIRED)**
There should not be duplicate assets/assets folder

**Defold version (REQUIRED):**
  - 1.2.172

**Comment by britzl** [comment]
Let's take the following folder structure for a Defold project:

```
project
+-game.project
+-extension
| +-ext.manifest
| +-res
|   +-android
|     +-assets
|       +-a.txt
+-bundle_resources
  +-android
    +-b.txt
	+-assets
	  +-c.txt
```

This will with Defold 1.2.172 generate the following APK:

```
project.apk
+-AndroidManifest.xml
+- ...
+-b.txt
+-assets
  +-a.txt
  +-c.txt
```

Note the b.txt file which is in the root of the apk. This and other files in the root of the APK can be read with Class.getResource().

The AAB format is defined like this: https://developer.android.com/guide/app-bundle. Files that should go in the root of the generated APK should be put in the root/ folder. The current AAB pipeline does not support this. And has been reported in this bug the assets/ folder is copied to the assets/ folder, resulting in assets/assets/.

**Comment by Filazapovich** [comment]
Also we have extension with .so libraries. These files are loaded by extension at runtime. To put files in proper dirs of apk (`lib\armeabi-v7a` and `lib\arm64-v8a`) we made extension with next folder structure:
```
project
+-game.project
+-extension
| +-ext.manifest
| +-res
|   +-arm64-android
|     +-lib
|       +-arm64-v8a
|        +-libcrypt-lib.so 
|   +-armv7-android
|     +-lib
|       +-armeabi-v7a
|         +- libcrypt-lib.so
```

But for AAB they take in wrong location

**Comment by britzl** [comment]
@Filazapovich Ah, I see. I'll look into this as well.

**Comment by britzl** [comment]
@Filazapovich why can't you put the `libcrypt-lib.so` file in the `extension/armv7-android /lib/` folder?

**Comment by Filazapovich** [comment]
> @Filazapovich why can't you put the `libcrypt-lib.so` file in the `extension/lib/armv7-android/` folder?

Because content of this folders is not copied to lib dir of apk on Defold 1.2.167

**Comment by britzl** [comment]
Ah, got it!

**Comment by britzl** [comment]
I've updated the PR to handle the libs as well. It will get merged today to the beta.

**Comment by Filazapovich** [comment]
```
ERROR: unspecified:-1: 'com.dynamo.bob.CompileExceptionError: Failed creating Android Application Bundle'

Exception in thread "main" com.dynamo.bob.CompileExceptionError: Failed creating Android Application Bundle
        at com.dynamo.bob.bundle.AndroidBundler.createCompileExceptionError(AndroidBundler.java:128)
        at com.dynamo.bob.bundle.AndroidBundler.createBundle(AndroidBundler.java:591)
        at com.dynamo.bob.bundle.AndroidBundler.createAAB(AndroidBundler.java:682)
        at com.dynamo.bob.bundle.AndroidBundler.bundleApplication(AndroidBundler.java:790)
        at com.dynamo.bob.Project.bundle(Project.java:593)
        at com.dynamo.bob.Project.doBuild(Project.java:892)
        at com.dynamo.bob.Project.build(Project.java:442)
        at com.dynamo.bob.Bob.main(Bob.java:621)
Caused by: java.io.IOException: [BT:0.14.0] Error: File 'root/lib/arm64-v8a/libcrypt-lib.so' uses reserved file or directory name 'lib'.
com.android.tools.build.bundletool.model.exceptions.BundleFileTypesException$FileUsesReservedNameException: File 'root/lib/arm64-v8a/libcrypt-lib.so' uses reserved file or directory name 'lib'.
```
As i see there is wrong target dir for libs. Must be `base/lib` instead of 'root/lib'.

**Comment by britzl** [comment]
Oh, and is this with a folder structure like was mentioned above? This one:

```
project
+-game.project
+-extension
| +-ext.manifest
| +-res
|   +-arm64-android
|     +-lib
|       +-arm64-v8a
|        +-libcrypt-lib.so 
|   +-armv7-android
|     +-lib
|       +-armeabi-v7a
|         +- libcrypt-lib.so
```

**Comment by Filazapovich** [comment]
> Oh, and is this with a folder structure like was mentioned above? This one: .......
Yes
