### ISSUE TITLE
gui.animate doesn't run when duration is zero.

### ISSUE THREAD

**Issue by aglitchman** [defold/defold#5198]
**Describe the bug**
`gui.animate` doesn't set a value and doesn't fire `callback_function` when `duration` is 0.

**To Reproduce**
Run the project. You should see in the log:
```
DEBUG:SCRIPT: go - init
DEBUG:SCRIPT: gui - init
DEBUG:SCRIPT: go - complete_test (duration 0)
DEBUG:SCRIPT: go - complete_test (duration 0.001)
DEBUG:SCRIPT: gui - complete_test (duration 0.001)
```

**Expected behavior**
`go.animate` and `gui.animate` should have the same behavior. `gui.animate` with zero duration should complete the animation (set the target value) and fire the callback. To sum up, the log should also have this line:
```
DEBUG:SCRIPT: gui - complete_test (duration 0)
```

**Defold version:**
 - Version 1.2.172

**Platforms:**
 - Platforms: ALL

**Minimal repro case project:**
Here - [animnode_test.zip](https://github.com/defold/defold/files/5212525/animnode_test.zip)

**Comment by britzl** [comment]
This makes sense. (and it should be a fairly quick fix)

**Comment by britzl** [comment]
The problem is also affected by the `delay` value. If `duration` AND `delay` are both set to 0 the callback is invoked.
