### ISSUE TITLE
When the engine is vanilla the "Generate debug symbols" checkbox in the editor does nothing

### ISSUE THREAD

**Issue by subsoap** [defold/defold#5199]
**Describe the bug (REQUIRED)**
No .pdb is included when checkbox is checked when engine is vanilla

**To Reproduce (REQUIRED)**

- Make blank project
- Check include debug symbols
- Bundle for Windows
- No .pdb included

**Expected behavior (REQUIRED)**
.pdb is included even when engine is vanilla

**Defold version (REQUIRED):**
  - Version [e.g. 1.2.172]

**Comment by subsoap** [comment]
Workaround is to just enable any of these checkboxes https://britzl.github.io/manifestation/

I think the vanilla pdb is somewhere but a quick look I couldn't find it

**Comment by subsoap** [comment]
Right vanilla pdb is here https://d.defold.com/stable/

**Comment by britzl** [comment]
Not sure how to best do this. We don't want to package the vanilla debug symbols with bob as it would increase the size of bob quite significantly. We could download them from GitHub or d.defold.com or perhaps output in the log/console where they can be downloaded?

@JCash any thoughts?

**Comment by JCash** [comment]
We don't want to ship these big files.
They're instead available at http://d.defold.com

**Comment by JCash** [comment]
But sure, the UX isn't great. We could either download them, or disable the option if there are no extensions (confusing).
