### ISSUE TITLE
Cannot update dependencies nor the engine itself

### ISSUE THREAD

**Issue by mikson60** [defold/defold#5203]
**Describe the bug (REQUIRED)**
Cannot Update the engine nor are any dependencies loaded. I updated Defold engine by uninstalling and reinstalling. This of course worked. But in the earlier version and also in the new version whenever I open a project, which has a dependency (defold-input asset), I get an error:
![image](https://user-images.githubusercontent.com/10653357/93148783-66cb9c00-f6fd-11ea-8852-b5be38edab4c.png)

**To Reproduce (REQUIRED)**
1. Create new project
2. Add [Defold input asset ](https://defold.com/assets/defoldinput/) as dependency
3. Fetch libraries OR restart project.
4. Does not update.

**Expected behavior (REQUIRED)**
Should fetch the library

**Defold version (REQUIRED):**
  - Version 1.2.173

**Platforms (REQUIRED):**
 - Platforms: Editor
 - OS: Windows 10

**Comment by JustAPotota** [comment]
`https://defold.com/assets/defoldinput/#` is not a valid library URL. Use `https://github.com/britzl/defold-input/archive/master.zip`.

**Comment by mikson60** [comment]
Of course! Thank you!

I was not able to update the engine with the previous version though (no idea what it was. Maybe I could get it from some logs). Some other guy had an issue with updating the engine as well (pressing the Update seemed to do something that took less than a second and then did nothing). But since I updated manually it is not a problem anymore.
