### ISSUE TITLE
GUI Editor Crashes

### ISSUE THREAD

**Issue by ultimateprogramer** [defold/defold#5208]
```
java.lang.ClassCastException: class jogamp.opengl.es1.GLES1Impl cannot be cast to class com.jogamp.opengl.GL2ES2 (jogamp.opengl.es1.GLES1Impl and com.jogamp.opengl.GL2ES2 are in unnamed module of loader 'app')
```

I am on Ubuntu 20.04

### Expected behaviour
* Should open the collection or Game Object editor

### Actual behaviour
* Collection or Game Object editor does not show up, this error shows up

### Steps to reproduce
* Open up a project
* Open up a Game Object Editor / Collection Editor

Update: See it also for Particle Editor, Atlas Editor, Tilemap editor.

<hr/>

<table>
<tr><td>Build time</td><td>2020-09-14T07:44:37.175974</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>0fc7ca5e7fe9fb66f5d692c4f015b313d875d884</td></tr>
<tr><td>Defold engine sha</td><td>fe2b689302e79b7cf8c0bc7d934f23587b268c8a</td></tr>
<tr><td>Defold version</td><td>1.2.173</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"56ab30af72494461b18bef8d818b2617"'>56ab30af72494461b18bef8d818b2617</a></td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) HD Graphics 620 (KBL GT2)</td></tr>
<tr><td>GPU Driver</td><td>OpenGL ES-CM 1.1 Mesa 20.0.8</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.4.0-47-generic</td></tr>
<table>

**Comment by britzl** [comment]
Please try: https://defold.com/manuals/linux/#q-why-does-the-defold-editor-crash-when-i-try-to-create-a-new-project-or-open-an-existing-one

**Comment by ultimateprogramer** [comment]
@britzl that seems to have solved the problem
