### ISSUE TITLE
Repeated local builds from the editor without closing the game will result in an error

### ISSUE THREAD

**Issue by britzl** [defold/defold#5215]
**Describe the bug (REQUIRED)**
When you build and run from the editor repeatedly without closing the game between each session will result in an error.

**To Reproduce (REQUIRED)**
1. Build your game once using Project->Build
2. Do not close the game window
3. Build your game a second time using Project->Build
4. Do not close the game window
5. Build your game a third time using Project->Build
6. Notice the error popup

**Expected behavior (REQUIRED)**
It should be possible to build your game any number of times without having to close the game window between each build.

**Defold version (REQUIRED):**
  - Version 1.2.173

**Platforms (REQUIRED):**
 - Platforms: macOS but probably also Windows and Linux

**Workaround (OPTIONAL):**
Close the game before building

**Additional context (OPTIONAL):**
https://forum.defold.com/t/testing-locally-fails-third-build-onwards-with-v1-2-173/66313

**Comment by JCash** [comment]
The offending checkin is a merge from the Switch repo (`b330bd078`).
I'll bisect those changes too.

**Comment by JCash** [comment]
Tracked it to commit `a22b85b59` in which I rewrote the app flow to be suitable for all platforms.
In this flow, the engine service is created when the engine is created, and as such it may get a new port which the editor only queries the first time.
