### ISSUE TITLE
does not work collision normal i press debug and crash

### ISSUE THREAD

**Issue by ElpidoforosGkikas** [defold/defold#5218]
### Expected behaviour
collision with platform on it 
### Actual behaviour
collision 40-50 pixel away
### Steps to reproduce
i press debug and crash
<hr/>

<table>
<tr><td>Build time</td><td>2020-09-14T07:44:58.278073</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>0fc7ca5e7fe9fb66f5d692c4f015b313d875d884</td></tr>
<tr><td>Defold engine sha</td><td>fe2b689302e79b7cf8c0bc7d934f23587b268c8a</td></tr>
<tr><td>Defold version</td><td>1.2.173</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"17ec7771a85044a999dc9d50e6136a10"'>17ec7771a85044a999dc9d50e6136a10</a></td></tr>
<tr><td>GPU</td><td>Intel(R) UHD Graphics 630</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 - Build 26.20.100.8141</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by ElpidoforosGkikas** [comment]
[editor2.2020-09-19.log](https://github.com/defold/defold/files/5249995/editor2.2020-09-19.log)

**Comment by ElpidoforosGkikas** [comment]
Game not work as before does collision about 50-20 pixel away like counts the borders of sprite or something because sprite is bigger and box of collision smaller. And instead go more up or down collide 50 - 20 pixel away of box collider and i press debug and crash. thanks

**Comment by ElpidoforosGkikas** [comment]
After change collision to half dimension was working normal but collision was smaller of sprite. before collision with edges of sprite was ok now this change. Also I have mention sprite from object has scal 2,2,1 thanks

**Comment by britzl** [comment]
I believe this was solved by using a uniform scale (2,2,2) on the object.

**Comment by ElpidoforosGkikas** [comment]
Yes it solved with uniform thanks

Στάλθηκε από την Αλληλογραφία<https://go.microsoft.com/fwlink/?LinkId=550986> για Windows 10

Από: Björn Ritzl<mailto:notifications@github.com>
Αποστολή: Κυριακή, 20 Σεπτεμβρίου 2020 11:16 μμ
Προς: defold/defold<mailto:defold@noreply.github.com>
Κοιν.: Elpidoforos Gkikas<mailto:elpidoforos@windowslive.com>; State change<mailto:state_change@noreply.github.com>
Θέμα: Re: [defold/defold] does not work collision normal i press debug and crash (#5218)


I believe this was solved by using a uniform scale (2,2,2) on the object.
