### ISSUE TITLE
java.net.SocketTimeoutException: connect timed out

### ISSUE THREAD

**Issue by Name23games** [defold/defold#5226]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2020-09-14T07:44:58.278073</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>0fc7ca5e7fe9fb66f5d692c4f015b313d875d884</td></tr>
<tr><td>Defold engine sha</td><td>fe2b689302e79b7cf8c0bc7d934f23587b268c8a</td></tr>
<tr><td>Defold version</td><td>1.2.173</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"110fe71be4bc4e368f1eed8d4b338058"'>110fe71be4bc4e368f1eed8d4b338058</a></td></tr>
<tr><td>GPU</td><td>Intel(R) UHD Graphics 630</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 - Build 26.20.100.7926</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
Could it be that this happens when you have done Project->Build three times with the game running in the background?

Reported here: https://github.com/defold/defold/issues/5215

**Comment by smnbldwn** [comment]
I am using Defold to teach students about game development. Some of them are experiencing this issue too when attempting to preview projects.

**Comment by britzl** [comment]
> I am using Defold to teach students about game development.

Cool! Can you share more information? We love to hear how Defold is used in educational purposes.

> Some of them are experiencing this issue too when attempting to preview projects.

You mean when they do Project->Build? If this is the case we recommend that you update to Defold 1.2.174 which has solved the problem.

**Comment by smnbldwn** [comment]
Thank you. I am teaching A level computer science in the UK. We are using Defold to practise game development skills in preparation for the programming project. Games fit the criteria well and Defold is quite lightweight and widely compatible both for development and target platforms. Lua is also a useful extra language to learn as it is powerful but not widely known to students in the 16-18 bracket. Thank you for the tip about upgrading...

**Comment by britzl** [comment]
Thank you for sharing how you use Defold. Lua is indeed a very useful language and it is widely used in the games industry. Good luck!
