### ISSUE TITLE
full screen problem

### ISSUE THREAD

**Issue by Name23games** [defold/defold#5235]
### starting my game with fullscreen option on
<hr/>

<table>
<tr><td>Build time</td><td>2020-09-22T09:44:16.169382</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>79f8292650bce98503a70bcf901c221d04d6d26d</td></tr>
<tr><td>Defold engine sha</td><td>fe2b689302e79b7cf8c0bc7d934f23587b268c8a</td></tr>
<tr><td>Defold version</td><td>1.2.173</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"9f590405b341447788bdbb73b0893c5c"'>9f590405b341447788bdbb73b0893c5c</a></td></tr>
<tr><td>GPU</td><td>Intel(R) UHD Graphics 630</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 - Build 26.20.100.7926</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
Does this happen when you do Project->Build as well as Debug->Attach?

**Comment by britzl** [comment]
Not enough information. Closing.
