### ISSUE TITLE
Ability to scale (or set other properties) of collisionobject shapes at runtime

### ISSUE THREAD

**Issue by Epitaph128** [defold/defold#5239]
**Is your feature request related to a problem? Please describe (REQUIRED):**
Yes, there's no way to efficiently utilize the data structures of Box2D to range check objects at variable ranges without a means to scale a collisionobject.

**Describe the solution you'd like (REQUIRED):**
Some way to scale a collisionobject shape at runtime

**Describe alternatives you've considered (REQUIRED):**
Setting the collisionobject to the max planned supported size, and then checking the range of all objects within that range to see if it meets the range requirement.

**Additional context (OPTIONAL):**
N/A

**Comment by JCash** [comment]
> scale a collisionobject.

You can scale a collision object.
Set the `physics.allow_dynamic_transforms` in your game project settings.

**Comment by JCash** [comment]
Since we already have this feature, I'll close this for now. Please feel free to reopen if this isn't what you wanted.
