### ISSUE TITLE
The game preview just crashed the moment it had opened.

### ISSUE THREAD

**Issue by NitroGamer23** [defold/defold#5243]
Build time | 2020-09-22T09:44:16.169382
-- | --
Defold channel | editor-alpha
Defold editor sha | 79f8292
Defold engine sha | fe2b689
Defold version | 1.2.173
Error | 5418e9ab47d644b087793699bc40f03c
GPU | Intel(R) HD Graphics 520
GPU Driver | 4.5.0 - Build 26.20.100.8142
Java version | 11.0.1+13
OS arch | amd64
OS name | Windows 10
OS version | 10.0

**Comment by britzl** [comment]
Probably this: https://github.com/defold/defold/issues/5215

**Comment by britzl** [comment]
Issue #5215 has been fixed. Closing.
