### ISSUE TITLE
After closing app using `exit` msg and open again see just black screen.

### ISSUE THREAD

**Issue by AGulev** [defold/defold#5249]
**Describe the bug (REQUIRED)**
If I close a game using `exit` mesage and open the game again I see just a black screen.

**To Reproduce (REQUIRED)**
1. Create exit button with the following code on it:
```
  if action_id == BACK_KEY and action.released then
    print("Time to exit!")
    msg.post("@system:", "exit", {code = 0})
  end
```
2. Run this app on Android
3. Tap exit button
4. Open the app again
5. black screen here

**Expected behavior (REQUIRED)**
App opens without any problems

**Defold version (REQUIRED):**
  - Defold 1.2.174 
Editor SHA: 5d8d6d6ed04e9d6ed8c577e558f6ad767e2e3735
Engine SHA: 5d8d6d6ed04e9d6ed8c577e558f6ad767e2e3735

**Platforms (REQUIRED):**
 - Platforms: Android
 - OS: 10
 - Device: Samsung s10e, Samsung s20, Huawei P20 Pro

(I can't reproduce this issue on Xiaomi Redmi Note 4 with Android 6)

**Minimal repro case project (OPTIONAL):**
https://github.com/AGulev/DefVideoAds
(Exit on Back button)

**Logs (OPTIONAL):**
[log.log](https://github.com/defold/defold/files/5300914/log.log)

**Comment by JCash** [comment]
The issue isn't really with the Back button, but that the exit message doesn't shut down the app all the way.
So, when the app is brought back to focus, it's from a half destroyed state. Hence the black screen.

**Comment by AGulev** [comment]
Yes, this time it's not about back btn for sure.
