### ISSUE TITLE
Errors and warnings should be developer-friendly

### ISSUE THREAD

**Issue by aglitchman** [defold/defold#5252]
**Task:**
Defold engine errors and warnings are not obvious at all. For example:
- `WARNING:RENDER: Out of text-render buffer` - It means that you should increase `graphics.max_characters`.
- `ERROR:PHYSICS: Physics world buffer full, world could not be created.` - It means that you can try to increase `physics.world_count` or load fewer collections via proxies.

I do think that errors and warnings should be developer-friendly as much as possible.

There are a lot of messages. We can slowly start doing pull-requests. Before that, let's discuss the structure of the messages. For example:
- Before: `WARNING:RENDER: Out of text-render buffer` 
- After:
    - `WARNING:RENDER: Out of text-render buffer. Increase graphics.max_characters (ref: https://defold.com/manuals/project-settings/).` 
    - or `WARNING:RENDER: Out of text-render buffer. It's limited by graphics.max_characters (ref: https://defold.com/manuals/project-settings/).`.

Something like that.

**Expected outcome:**
Fewer questions from newcomers 👍

**Comment by britzl** [comment]
This is a great suggestion! We should be even more explicit and say that the value exists in game.project and link to the correct section in the manual:

Increase graphics.max_characters in game.project (refer to https://defold.com/manuals/project-settings/#max-characters)

**Comment by britzl** [comment]
It's also possible to link to and open project files:

```
Increase graphics.max_characters in [game.project](defold://open?path=/game.project)
```
