### ISSUE TITLE
error

### ISSUE THREAD

**Issue by stone-age-jazz** [defold/defold#5266]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2020-10-07T09:43:44.031350</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>18e7da2c4eea5d37a154d3bde088e161fc49186e</td></tr>
<tr><td>Defold engine sha</td><td>8f3e864464062e1b35c207521dc65dfd77899cdf</td></tr>
<tr><td>Defold version</td><td>1.2.174</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"acf49622d95b471097b1bdfaf540ba17"'>acf49622d95b471097b1bdfaf540ba17</a></td></tr>
<tr><td>GPU</td><td>Intel Iris OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-14.7.8</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.15.7</td></tr>
<table>

**Comment by britzl** [comment]
Hi! Are you able to reproduce the crash?

**Comment by stone-age-jazz** [comment]
Hi! I don't think so. I just downloaded the engine and I was playing around with it. All I know is that I was trying to delete an Input action field.

**Comment by britzl** [comment]
Closing until we have a solid repro case
