### ISSUE TITLE
HTTP response 204 No Content should not crash http client if a Content-Length header is included

### ISSUE THREAD

**Issue by britzl** [defold/defold#5271]
**Describe the bug (REQUIRED)**
The spec for 204 No Content states that no Content-Length header should be sent. The Defold http client is strict about this and will assert if a Content-Length header is included.

**To Reproduce (REQUIRED)**
1. Make a HTTP request to a resource which returns 204 No Content and a Conten-Length header
2. Observe crash

**Expected behavior (REQUIRED)**
The HTTP client should not crash (but perhaps log a warning)

**Defold version (REQUIRED):**
  - 1.2.174

**Platforms (REQUIRED):**
 - Platforms: All

**Additional context (OPTIONAL):**
Forum thread: https://forum.defold.com/t/application-crashes-on-http-request/66587

**Comment by BetaSoftCologne** [comment]
If no one is on this, I'd like to take this as my first issue.

**Comment by britzl** [comment]
The user solved it by returning a 200 OK instead :-)

Please go ahead @BetaSoftCologne !

We have a #sourceode channel on Slack and Source Code category on the forum: https://forum.defold.com/c/source-code

And you can of course as questions here as well!

**Comment by britzl** [comment]
I'd be happy to send you a Defold t-shirt as a reward for fixing this!

**Comment by SpencerWF** [comment]
No promises given my skills, but I wouldn't mind having a look to see if I can fix this issue.

**Comment by otsakir** [comment]
hey @SpencerWF, are you still on it?

**Comment by otsakir** [comment]
hey @britzl , do i still get a t-shirt ?   :-D

**Comment by britzl** [comment]
@otsakir sure, why not! I see that you are have also started looking into a sound related issue 👍 

Please email me (bjorn@defold.se) your t-shirt size and address and I'll send something your way!

Thanks!
