### ISSUE TITLE
CocoaPod dependency resolution

### ISSUE THREAD

**Issue by britzl** [defold/defold#5276]
**Describe the bug (REQUIRED)**
We need to be able to resolve conflicts and duplicate iOS frameworks one the build server. Example:

https://forum.defold.com/t/admob-and-firebase-analytics-extensions-solved/63986/27

**Comment by AGulev** [comment]
I think it should be done together with support of `*.xcframework` because a lot of cocoaPods use it already.

**Comment by AGulev** [comment]
https://github.com/defold/editor2-issues/issues/2894
