### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by stone-age-jazz** [defold/defold#5280]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2020-10-07T09:43:44.031350</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>18e7da2c4eea5d37a154d3bde088e161fc49186e</td></tr>
<tr><td>Defold engine sha</td><td>8f3e864464062e1b35c207521dc65dfd77899cdf</td></tr>
<tr><td>Defold version</td><td>1.2.174</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"3852df9406834b2693b73f654e2c884b"'>3852df9406834b2693b73f654e2c884b</a></td></tr>
<tr><td>GPU</td><td>Intel Iris OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-14.7.8</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.15.7</td></tr>
<table>

**Comment by britzl** [comment]
Can you describe what you did when the error happened? Can you reproduce the problem?

**Comment by stone-age-jazz** [comment]
> Can you describe what you did when the error happened? Can you reproduce the problem?

I'm sorry, I'm still very new to Defold. I wish I could be of more help.
What I remember happened, is that I deleted some images from the file system and then I pressed on the Game Objects inside the editor. So the error probably occurred because Defold could not find the images either in the Atlas or in the file system.

**Comment by britzl** [comment]
Ok, thanks. If it happens again and you have some clear steps to reproduce then please reopen the issue.
