### ISSUE TITLE
iOS: Defold HTTP API usage results in request for permission to connect to local network

### ISSUE THREAD

**Issue by marconett** [defold/defold#5287]
**Describe the bug**
When trying to use the internal HTTP API (https://defold.com/ref/http/) in a project on iOS, there's a popup that asks the user for permission to access the local network: "app would like to find and connect to devices on your local network" (example: https://i.redd.it/jqgbfblvwi651.jpg).
This happens, even if the HTTP server I'm trying to access is publicly (as in: not on my local network) available.

Could this have something to do with the way Defold internally handles dns resolution?

**To Reproduce**
- `http.request("https://www.google.com", "GET", function() end)` on an iOS 14 device (not sure about Simulator).

**Expected behavior**
Local network access is not really needed, so there should be no popup.

**Defold version:** 1.2.174

**Platforms:**
I believe this issue is iOS 14 only.

**Comment by marconett** [comment]
I tested it with an IP address so there would be no DNS resolution needed, but the popup is still there.
Curiously, the popup only shows up on the second http request and not the first one (could repo this behavior with both domain and IP).

**Comment by marconett** [comment]
Maybe we have something similar to the behavior described here: https://stackoverflow.com/a/64367835

**Comment by britzl** [comment]
Does this also happen in a release build? Debug builds run a small web server and SSDP discovery on the network for connection and discoverability in the editor. This is not done in release builds.

**Comment by marconett** [comment]
Yes, I only tried release builds.

**Comment by britzl** [comment]
There is also sys.get_connectivity() and sys.set_connectivity_hot() which does a network connectivity check but I don't believe any of the code is running until called through those functions.

**Comment by britzl** [comment]
Ah, I should have read the issue better. So you get the popup as soon as you call http.request()?

**Comment by britzl** [comment]
Another discussion about the issue: https://developer.apple.com/forums/thread/654243

**Comment by marconett** [comment]
> Ah, I should have read the issue better. So you get the popup as soon as you call http.request()?

Yes.

**Comment by marconett** [comment]
> Another discussion about the issue: https://developer.apple.com/forums/thread/654243

I saw that and assumed something similar with dns, but I tested it with http requests to an IP and the issue is still there.

**Comment by marconett** [comment]
Now that I'm looking at this again, I noticed that if I deny access using the popup, I am not able to do any HTTP requests.

**Comment by britzl** [comment]
There's a pretty long list of reasons this dialog might trigger:

https://developer.apple.com/forums/thread/663874

**Comment by britzl** [comment]
And a good FAQ on local network privacy: https://developer.apple.com/forums/thread/663858

**Comment by marconett** [comment]
The problem does not occur when I turn of WiFi and use my mobile data service.

**Comment by britzl** [comment]
Yeah, not sure what the solution is really...

"In our app, we get it just because we send a request to the DNS server of the local network (the one advertise by the wifi router with DHCP) to resolve a domain name." (from https://developer.apple.com/forums/thread/654243)

We do have a dns_null.cpp implementation. I wonder what would happen if this was used as a test? Would it still trigger? @JCash any ideas?

**Comment by JCash** [comment]
I don't have any better ideas @britzl .
We currently do not have a good way of disabling the cares library and its dns lookups.
We could add a setting for it, and put it in a branch for you to test.

**Comment by marconett** [comment]
Are you certain that this really is a DNS issue?
I'd be happy in helping to test this, though I'm currently not setup to build the engine.

**Comment by marconett** [comment]
To test the DNS theory further, I set my iPhones DNS server to Googles public DNS server (8.8.8.8). Before that, it was my local routers IP.

With the public DNS server, the popup does not show up. So it almost certainly really is a problem with dns resolution.

To work around this, maybe it's possible to add an option to disable defold looking for a default dns server and always set the fallback dns servers defined here (https://github.com/defold/defold/blob/b330bd078b0788d886b8a9e86f49681ce544e1e1/engine/dlib/src/dlib/dns.cpp#L46)?
Alternatively, maybe completely forgo looking for a system default dns resolver and always use the fallback servers on iOS for a quick fix?

**Comment by JCash** [comment]
Good news is that I can reproduce it locally as well, so I should be able to pinpoint the code that causes the popup.

**Comment by JCash** [comment]
Also, I get it without calling `http.request`, it seems to happen when the ssdp sends the a message ("Failed to send announce message"). Using wifi+debug.

I'll try setting the default dns as you suggested.

**Comment by marconett** [comment]
Could you reproduce my results?
