### ISSUE TITLE
No API ref for *.set_constant and *.reset_constant

### ISSUE THREAD

**Issue by Insality** [defold/defold#5298]
**Describe the bug (REQUIRED)**
The documentation on `*.set_constant` and `*.reset_constant` (spine, sprite) are absent

**To Reproduce (REQUIRED)**
https://defold.com/ref/stable/sprite/
https://defold.com/ref/beta/sprite/

Or is it expected? Possible are other several API stuff are disappeared too?

**Comment by britzl** [comment]
It is expected. They are deprecated in favor of go.set() BUT we are missing a go.reset() (see: https://github.com/defold/defold/issues/5294).
