### ISSUE TITLE
error in Ubuntu 20.04

### ISSUE THREAD

**Issue by brett03112** [defold/defold#5302]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2020-10-07T09:42:48.531234</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>18e7da2c4eea5d37a154d3bde088e161fc49186e</td></tr>
<tr><td>Defold engine sha</td><td>8f3e864464062e1b35c207521dc65dfd77899cdf</td></tr>
<tr><td>Defold version</td><td>1.2.174</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"1f0ff6f3b37445dcb3e48453f207dc9e"'>1f0ff6f3b37445dcb3e48453f207dc9e</a></td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.4.0-52-generic</td></tr>
<table>

**Comment by britzl** [comment]
Does this happen at startup or while running the editor?

It seems like it could be related to this:

https://defold.com/manuals/linux/#q-why-does-the-defold-editor-crash-when-i-try-to-create-a-new-project-or-open-an-existing-one

**Comment by britzl** [comment]
No new info from user. Closing.
