### ISSUE TITLE
Crash on Arch

### ISSUE THREAD

**Issue by UNIcodeX** [defold/defold#5310]
### Expected behaviour
open a file for editing

### Actual behaviour
crash with error `java.lang.ClassCastException: Unknown`

### Steps to reproduce
Open "Side Scroller Tutorial" => main => main.go for editing

<hr/>

<table>
<tr><td>Build time</td><td>2020-10-07T09:10:37.764057</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>8f3e864464062e1b35c207521dc65dfd77899cdf</td></tr>
<tr><td>Defold engine sha</td><td>8f3e864464062e1b35c207521dc65dfd77899cdf</td></tr>
<tr><td>Defold version</td><td>1.2.174</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"5b959be708574a4a9991414acc2bca0f"'>5b959be708574a4a9991414acc2bca0f</a></td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) HD Graphics 520 (SKL GT2)</td></tr>
<tr><td>GPU Driver</td><td>OpenGL ES-CM 1.1 Mesa 20.2.1</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.9.1-arch1-1</td></tr>
<table>

```
Kernel: 5.9.1-arch1-1 
Uptime: 2 days, 21 hours, 57 mins 
Packages: 1207 (pacman), 8 (brew) 
Shell: zsh 5.8 
Resolution: 1920x1080, 1920x1080 
DE: Plasma 5.20.1 
WM: KWin 
CPU: Intel i5-6200U (4) @ 2.800GHz 
GPU: Intel Skylake GT2 [HD Graphics 520] 
Memory: 6116MiB / 15739MiB 
```

**Comment by britzl** [comment]
Could you please try this: https://defold.com/manuals/linux/#q-why-does-the-defold-editor-crash-when-i-try-to-create-a-new-project-or-open-an-existing-one

**Comment by UNIcodeX** [comment]
Setting it to 2.1 worked. Thank you.

**Comment by UNIcodeX** [comment]
Setting `export MESA_GL_VERSION_OVERRIDE=2.1` fixed the issue. Thanks!
