### ISSUE TITLE
Failed to connect to debugger (OSX el capitan)

### ISSUE THREAD

**Issue by MatteoDeSantis** [defold/defold#5311]
### Expected behaviour
Start / Attach Debug
### Actual behaviour
clojure.lang.ExceptionInfo: Failed to connect to debugger on localhost:8172
### Steps to reproduce
Run debug > start/attach
<hr/>

<table>
<tr><td>Build time</td><td>2020-10-07T09:43:44.031350</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>18e7da2c4eea5d37a154d3bde088e161fc49186e</td></tr>
<tr><td>Defold engine sha</td><td>8f3e864464062e1b35c207521dc65dfd77899cdf</td></tr>
<tr><td>Defold version</td><td>1.2.174</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"52745bd7fb61410e94ccb7d5b79ab8eb"'>52745bd7fb61410e94ccb7d5b79ab8eb</a></td></tr>
<tr><td>GPU</td><td>Intel HD Graphics 4000 OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-10.14.74</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.11.6</td></tr>
<table>

**Comment by britzl** [comment]
Does it happen all the time or intermittently?

**Comment by britzl** [comment]
No new info. Closing.
