### ISSUE TITLE
Performance regression when rendering text

### ISSUE THREAD

**Issue by dapetcu21** [defold/defold#5313]
**Describe the bug (REQUIRED)**
I noticed that the fix for [this issue](https://github.com/defold/defold/issues/4901) was reverted in [this commit](https://github.com/defold/defold/commit/6fc9dc26fce06c3c85986ed671c134061cd61e73). This severely impacts text rendering performance, especially in Domains of Dusk, which is very text-heavy. I'm curious: Was the fix breaking something else?

This is on an Intel i7 8700, with the built-in iGPU (UHD 630). No other text apart from the one visible on screen is being rendered:
<img width="1072" alt="Screenshot 2020-11-05 at 12 02 01" src="https://user-images.githubusercontent.com/428060/98228456-48498a80-1f61-11eb-8086-d6c7c8801bdb.png">

**To Reproduce (REQUIRED)**
1. Render text nodes

**Expected behavior (REQUIRED)**
Text shouldn't be so resource-intensive.

**Defold version (REQUIRED):**
  - 1.2.174

**Platforms (REQUIRED):**
 - Platforms: macOS
 - OS: 10.15.7

**Comment by JCash** [comment]
Yes, it caused text to disappear in certain cases, so we need a better optimization here.
Unfortunately, I didn't manage to create a repro case myself, so it'll be a bit trickier to make sure we don't break anything again.

**Comment by JCash** [comment]
@dapetcu21 Feel free to test this PR to see if it helps with the issue (it should, since it's a variant of the previous "fix")

**Comment by dapetcu21** [comment]
Yay! Thanks very much for this fix! ❤️ I'll be sure to check it out sometime this week.

**Comment by JCash** [comment]
FYI: It is in the beta now.

**Comment by dapetcu21** [comment]
I'm actually seeing worse performance on this last commit (7ms in DrawRenderList vs 4.7ms). Maybe hashing the vertex data is actually taking more time than sending it to the GPU?

1.2.179 (5209b50):
<img width="1072" alt="1 2 179 (5209b50)" src="https://user-images.githubusercontent.com/428060/109017376-c7ed9780-76bf-11eb-9c0d-eda4725f939b.png">

1.2.180 (9ace43d):
<img width="1072" alt="1 2 180 (9ace43d)" src="https://user-images.githubusercontent.com/428060/109017403-cfad3c00-76bf-11eb-82ab-7b010ea0d848.png">

**Comment by dapetcu21** [comment]
Should I try this benchmark on the iGPU (the one I used in the original post)? Do you think that would help you?

**Comment by JCash** [comment]
Nah, I figure I just had a too small data set to notice it :(
I think to make this really speed up, I need to go for the other optimization as well, to actually detect if the submitted text entries was actually changed. It's a bit more fiddly, but must be doable.

**Comment by JCash** [comment]
@dapetcu21  An interesting fact now that I'm looking into further optimizing this function.
Looking into how large each character is (6 vertices == 672 bytes), and the `FontVertexBuffer` in your report, the character count is pretty significant:
`47792640/672 = 71120`

Since the screen isn't showing all these characters, I guess these are items in other gui nodes?
Since the nodes aren't showing, are they simply outside of the screen bounds?

**Comment by dapetcu21** [comment]
I checked. We don't have offscreen nodes (or at least they're disabled). Unless RichText does something I'm not aware of, what you see is what you get.

Anyway, that number is pretty suspicious. With a clean map I get 60 characters on screen (which doesn't correspond to all the text in the menu buttons up top), and with a 70-character tooltip added on top I get 905 characters, which is definitely wrong.

<img width="1072" alt="Screenshot 2021-02-25 at 19 05 47" src="https://user-images.githubusercontent.com/428060/109189452-b1693e00-779c-11eb-9272-74ac54be8962.png">

<img width="1072" alt="Screenshot 2021-02-25 at 19 05 53" src="https://user-images.githubusercontent.com/428060/109189472-b6c68880-779c-11eb-99e0-d9358dd26fc8.png">

I invited you to the repo if you want to investigate yourself:
https://github.com/critique-gaming/domains-of-dusk/invitations

**Comment by dapetcu21** [comment]
Put this in `_env/env.lua` to skip char creation:
```
return {
  window_width = 1920 / 2,
  skip_character_creation = true,
  -- no_events = true,
}
```

**Comment by JCash** [comment]
@dapetcu21 I've made good progress in locating the issue, and I'm about to prepare a fix.
I'd like to test your project now to make sure it works as expected, but I'm afraid the invitation expired :/

**Comment by dapetcu21** [comment]
Oh! Sorry. I sent you the invite again.
https://github.com/critique-gaming/domains-of-dusk/invitations

**Comment by JCash** [comment]
@dapetcu21 There's a new beta to try out for you:
http://d.defold.com/beta/

**Comment by dapetcu21** [comment]
I'll try it when I get home :)

**Comment by dapetcu21** [comment]
This is much more reasonable. 3.5k characters on the screen (much more feasible number) and 1.4ms in DrawRenderList. GG! 👍 

<img width="1072" alt="Screenshot 2021-02-26 at 23 36 30" src="https://user-images.githubusercontent.com/428060/109357776-75f96d00-788b-11eb-893b-8ca2457c718a.png">
