### ISSUE TITLE
java.lang.IllegalArgumentException: No matching clause: 404

### ISSUE THREAD

**Issue by Quietpartner** [defold/defold#5331]
### Expected behaviour
open platformer game template
### Actual behaviour
java.lang.IllegalArgumentException: No matching clause: 404
### Steps to reproduce
Just open platformer game template
<hr/>

<table>
<tr><td>Build time</td><td>2020-11-12T09:33:33.915272</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>d5448e018b4ab9ab3356f45d3e1eca310c9449f6</td></tr>
<tr><td>Defold engine sha</td><td>e41438cca6cc1550d4a0131b8fc3858c2a4097f1</td></tr>
<tr><td>Defold version</td><td>1.2.175</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"aaf75b4b0f344a2d9e8c1ef8489a041f"'>aaf75b4b0f344a2d9e8c1ef8489a041f</a></td></tr>
<tr><td>GPU</td><td>Intel Iris OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-10.14.74</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.11.6</td></tr>
<table>

**Comment by britzl** [comment]
Hi! Based on the reported stack trace it looks like there was a problem creating a new project from the editor welcome screen. Was it a one time thing or does it happen all the time? What kind of project were you trying to create?

**Comment by Quietpartner** [comment]
Hello. Yes, it happens every time I choose a new project from the platformer template on the welcome screen.

**Comment by britzl** [comment]
Thank you @Quietpartner. It turns out that GitHub has changed the name of the formerly known "master" branch to now be called "main" in all new repositories. There should be a new Editor version available in about 20 minutes which refers to the correct URL for the platformer template.
