### ISSUE TITLE
I found this probem when i tried to use visual studio code as the custom editor

### ISSUE THREAD

**Issue by Mvcart** [defold/defold#5344]
I found this probem when i tried to use visual studio code as the custom editor. Someone knows gow to fix it ? Error message (sorry, it's in portuguese):

```
clojure.lang.ExceptionInfo: handler ':open-as' in context ':global' failed at ':run' with message 'Cannot run program "code" (in directory "C:\Users\User\OneDrive\Documentos\apps do defold\space invaders turbinadasso"): CreateProcess error=2, O sistema não pode encontrar o arquivo especificado' java.io.IOException: Cannot run program "code" (in directory "C:\Users\User\OneDrive\Documentos\apps do defold\space invaders turbinadasso"): CreateProcess error=2, O sistema não pode encontrar o arquivo especificado java.io.IOException: CreateProcess error=2, O sistema não pode encontrar o arquivo especificado   
```

### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2020-11-12T09:33:11.248649</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>d5448e018b4ab9ab3356f45d3e1eca310c9449f6</td></tr>
<tr><td>Defold engine sha</td><td>e41438cca6cc1550d4a0131b8fc3858c2a4097f1</td></tr>
<tr><td>Defold version</td><td>1.2.175</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"5f61e5a0cd8e44d9bf287018d34f424b"'>5f61e5a0cd8e44d9bf287018d34f424b</a></td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 530</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 - Build 27.20.100.8853</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
What did you put in the Custom Editor field in the Preferences view?

**Comment by britzl** [comment]
No new info from user. Closing.
