### ISSUE TITLE
Some ParticleFX Emitter properties cannot be set

### ISSUE THREAD

**Issue by totebo** [defold/defold#5346]
**Describe the bug (REQUIRED)**
When a new emitter is created, some properties are not set and cannot be set/used.

**To Reproduce (REQUIRED)**

1. Create a ParticleFX.
2. Create a new emitter.
3. Try to change Initial Stretch or Initial Angular Velocity.

https://youtu.be/2_hBJeA9fho

**Expected behavior (REQUIRED)**
All properties should be usable.

**Defold version (REQUIRED):**
v1.2.174

**Platforms (REQUIRED):**
macOS.

**Comment by vlaaad** [comment]
Fixed in #7355
