### ISSUE TITLE
If a collection is set instead of a gui script inside of a gui then this happens Assertion failed: lua_isfunction(L, -1), file ..\src\gui.cpp, line 1714

### ISSUE THREAD

**Issue by subsoap** [defold/defold#5352]
**Describe the bug (REQUIRED)**
Assertion failed: lua_isfunction(L, -1), file ..\src\gui.cpp, line 1714

**To Reproduce (REQUIRED)**
![2020-11-19 21_21_49-Window](https://user-images.githubusercontent.com/409170/99762402-46c5a980-2aad-11eb-965a-9ba9e16f1b30.png)

**Expected behavior (REQUIRED)**
Give a clear message in the editor to select the correct file type

**Defold version (REQUIRED):**
1.2.175

**Comment by britzl** [comment]
Wow. I thought that file picker dialog was limited to only show .gui_script files?

**Comment by subsoap** [comment]
It is actually so this might not be a problem.

![2020-11-20 01_46_14-Select Resource](https://user-images.githubusercontent.com/409170/99785590-32e06e80-2ad2-11eb-9975-829f727c08c4.png)

The reason I had this happen is I used the editor script of Monarch on a collection instead of a gui and it set this situation up.

**Comment by britzl** [comment]
I see. Well, you can mess up your game content in a multitude of ways if you do it using an external tool or some 3rd party solution such as an editor script. In this instance I think it's best to make sure the Editor Script for Monarch checks the file and ignores it if it is of the wrong type.

**Comment by britzl** [comment]
We will not fix this in the editor or pipeline at the moment.
