### ISSUE TITLE
Expose common JNI helper functions in the Defold SDK

### ISSUE THREAD

**Issue by britzl** [defold/defold#5353]
**Is your feature request related to a problem? Please describe (REQUIRED):**
Almost any Android extension which interfaces with Java using JNI has the same set of helper functions to get a class loader and create class instances and references to member functions:

* https://github.com/defold/extension-iap/blob/master/extension-iap/src/iap_android.cpp#L411-L415
* https://github.com/defold/extension-facebook/blob/master/facebook/src/facebook_android.cpp#L463-L470
* https://github.com/defold/extension-gpgs/blob/master/gpgs/src/gpgs_jni.h

**Describe the solution you'd like (REQUIRED):**
This functionality should be offered through the Defold SDK. It will reduce code size and remove some of the burden of working with JNI.

**Comment by AGulev** [comment]
@britzl isn't it done here  https://github.com/defold/defold/pull/6082/files ?

**Comment by britzl** [comment]
Indeed! We can close this issue.
