### ISSUE TITLE
Move and externalise encryption key

### ISSUE THREAD

**Issue by britzl** [defold/defold#5355]
**Task (REQUIRED):**
The encryption key is stored in ArchiveBuilder.java. Make it configurable and move it to a GitHub secret (and rotate it)

**Expected outcome (REQUIRED):**
The encryption key should change over time. Perhaps also allow the developer to chose a key.

https://forum.defold.com/t/unfold-wip-defold-modding-tool/66855/9?u=britzl

**Comment by subsoap** [comment]
Allowing the dev to choose the key and changing the base key over time would be best. Maybe have it be an appmanifest field.

Ideally what should change is how it is stored / accessed in memory over time just to make older tools break for newer builds. But realistically if *any* massively popular core audience game is made with Defold and it uses the base encryption features tools will be updated quickly to unpack anything new.

**Comment by dapetcu21** [comment]
Hi!

I'm not sure rotating the key is such a great idea with respect to the incremental game patching Steam, Apple and Nintendo employ. If the key changes without the developer knowing and they release an update to the game, it will be huge (the full size of the game). On Switch, where the base game and the patch file must be both installed, this will effectively double the space requirements.

I, personally, don't care much for obfuscating my assets (bad actors will be bad actors anyway) and I would not like it to be changed without my consent, especially on my existent projects.

Having keys explicitly changeable per-project should be enough for people that care about this aspect.

Maybe another idea would be to auto-generate a new key every time a new project gets templated from the editor.

**Comment by britzl** [comment]
> Having keys explicitly changeable per-project should be enough for people that care about this aspect.

I think this would be the way to go on this. Let the developer decide if and when to change key.

**Comment by aglitchman** [comment]
I want to bump this issue. A simple option like "project.encryption_key = your_key" in the `game.project` file should be enough.

**Comment by AGulev** [comment]
but game.project is easily available for the end user.
I thought maybe it should be an option in a--manifest and compiled in the engine binary?

**Comment by aglitchman** [comment]
> but game.project is easily available for the end user.

Yes. But Defold already removes dependencies list from the resulting `game.projectc`. It can do that for the encryption key, too.

**Comment by subsoap** [comment]
User setting in the game.project for bundle time use then discarded would be convenient, but the key still has to be baked into the bundle somehow in a way that is not super easily extracted through automated means. If it can be possible to make it so an all in one key finder tool is not trivial to make that would be good, but if not then it's hard to justify the effort. Of course you still can't defeat dedicated people, every Fortnite bundle encryption key is published publicly fast, but still good to make suits happy / make it non-trivial for less skilled people / make it require human work to get each key.

**Comment by britzl** [comment]
> I want to bump this issue.

Ok. I will look into it!

**Comment by britzl** [comment]
Here's the PR for having the encryption key in game.project: https://github.com/defold/defold/pull/6004

I'm not entirely sure that it is helpful to put the encryption key in game.project and use it while building the archive and then later at runtime when files in the archive are decrypted. The key would have to sit there in game.projectc in clear-text for anyone to read.

For it to be at all useful I think it needs to be included in the binary somehow. And this implies building the engine using the build server. The encryption key would be put in a generated cpp file and included in the build.
