### ISSUE TITLE
Android 7.0 and 7.1 crashes on starting DefoldActivity (java.lang.ClassCastException)

### ISSUE THREAD

**Issue by SkaterDad** [defold/defold#5356]
**Describe the bug (REQUIRED)**
I've been seeing runtime crashes in my Google Play Console.  It appears the game crashes on startup, when launching the DefoldActivity (`com.dynamo.android.DefoldActivity.onCreate`). I have not seen this personally on my own devices, since they are newer.

**Expected behavior (REQUIRED)**
No crashes.

**Defold version (REQUIRED):**
  - Version 1.2.174

**Platforms (REQUIRED):**
 - Platforms: Android
 - OS: Android 7.0 (SDK24), Android 7.1 (SDK25)
 - Device: Samsung Galaxy S6, Samsung Galaxy A8 (2016), Samsung Galaxy Tab A, Motorolla G4 Plus,  Misc Xiaomi and Huawei devices.

**Logs (OPTIONAL):**

This is the stacktrace Google provides.  Hopefully it's enough of a clue?

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{dev.skaterdad.applespider/com.dynamo.android.DefoldActivity}: java.lang.ClassCastException: 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2927)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2988)
  at android.app.ActivityThread.-wrap14 (ActivityThread.java)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1631)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6682)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1520)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1410)
Caused by: java.lang.ClassCastException: 
  at android.app.NativeActivity.onCreate (NativeActivity.java:164)
  at com.dynamo.android.DefoldActivity.onCreate (DefoldActivity.java:217)
  at android.app.Activity.performCreate (Activity.java:6942)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1126)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2880)

```

**Comment by britzl** [comment]
I know you have experimented with Play Instant. Is this a trace from a Play Instant version of your game or from the normal installable apk?

**Comment by SkaterDad** [comment]
The version code in all of the crash reports is from the Instant version.

There are odd things in this data, though.  It lists ~10 devices, but claims only one user is impacted.

Full disclosure, I do not have any real installs from devices this old.  The installs are all Android 9, 10, and 11 as of now.  Instant gives me a lot more visibility, so that's most of the traffic.

**Comment by britzl** [comment]
I'm honestly not sure why it fails. Search results seem to indicate problems in the onCreate() metjod of the Activity where setContentView() is not called before trying to access View components. But this is not the case with the DefoldActivity as it does no such thing.

**Comment by SkaterDad** [comment]
It is pretty weird.  the only casting I see in the onCreate method is here:
https://github.com/defold/defold/blob/24c754790726a2a2644659f9386130f0dda46f37/engine/glfw/java/com/dynamo/android/DefoldActivity.java#L221

Android docs imply those functions and classes have existing since nearly the beginning, so it's not an SDK compat issue.

Traffic has really picked up in southeast Asia, so I'm starting to see hundreds of these crashes per day.  Still isolated to Android 7 and 7.1, and low end devices for the most part.

I'll try upgrading to 1.2.176 this weekend.  Hopefully something randomly fixes this. Could be an incorrect stack trace.

**Comment by AGulev** [comment]
Hey, How it's going with Defold 1.2.176?

**Comment by SkaterDad** [comment]
> Hey, How it's going with Defold 1.2.176?

I sent the 1.2.176 update to production yesterday, so am still waiting for Google to review it.

I've had some other random crashes due to library conflicts, so it is very hard to say what is causing all of this.  I was using the latest GPGS, which uses AndroidX, but then discovered the Unity Ads SDK still uses the Android Support libs.

My latest production build reverted back to android support for GPGS, so I'm really hoping this fixes all of my issues.

The error logs and stack traces on Android are so random and misleading sometimes.

Have you noticed errors that only show up on your Instant builds?

**Comment by AGulev** [comment]
My instant builds are pretty old for all games but I'm going to update some of them in the next month.

**Comment by SkaterDad** [comment]
After my 1.2.176 release is in production for a day or two, I'll update this thread.

I could not replicate the input issue you reported in #5358 with my own game or devices.

**Comment by britzl** [comment]
Let us know how it goes with the latest version. I may be able to assist with some debugging on an Android 7 device if we have one laying around.

**Comment by SkaterDad** [comment]
Quick update:  Google _finally_ published my update with Defold 1.2.177, and Jetifier-enabled build.

I'll keep an eye on the crash reports and will update here.

**Comment by SkaterDad** [comment]
I'm going to close this issue. 

My latest release with 1.2.177, and Jetifier build, has not seen this crash even once after 3 days.  For comparison, I was seeing this  ClassCastException crash hundreds of times per day before.  Technically, I still see it hundreds of times, thanks to people not running the latest update.

I guess we can attribute this crash to library incompatibilities and Java runtime quirks.

**Comment by britzl** [comment]
Thanks. This is good to know!
