### ISSUE TITLE
Error when creating a new project

### ISSUE THREAD

**Issue by AmateurPotion** [defold/defold#5373]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2020-11-12T09:33:11.248649</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>d5448e018b4ab9ab3356f45d3e1eca310c9449f6</td></tr>
<tr><td>Defold engine sha</td><td>e41438cca6cc1550d4a0131b8fc3858c2a4097f1</td></tr>
<tr><td>Defold version</td><td>1.2.175</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"4b981a1e59864b0bba3d92f758f40a94"'>4b981a1e59864b0bba3d92f758f40a94</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 1650/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 451.67</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
@AmateurPotion which project/tutorial are you trying to open from the Welcome screen?

**Comment by AmateurPotion** [comment]
![캡처](https://user-images.githubusercontent.com/47741752/100628504-9f2d5e80-336b-11eb-8fcf-3261cae3a082.PNG)

**Comment by britzl** [comment]
Could you please click on Update Available bottom left to download and apply the latest editor update. I believe the update will fix the broken link.
