### ISSUE TITLE
Expanding variables/constants to fields in the Properties pane

### ISSUE THREAD

**Issue by andersand** [defold/defold#5380]
**Is your feature request related to a problem? Please describe (REQUIRED):**
Say you have multiple sprites that all have 8 animation groups for walking, 8 for shooting, etc. The property Fps you enter was ok when you tested at first, but later you change your mind and want to change the Fps for all animation groups. Now you have to manually edit every animation group's Fps property.

**Describe the solution you'd like (REQUIRED):**
I would want to be able to refer to a constant in the Fps (and any other property text field) eg. using variable expansion syntax like ${globals.SpriteAniFps} or similar.

**Describe alternatives you've considered (REQUIRED):**
Alternatively being able to bulk edit properties visually by selecting them in the Outline pane, could also work perhaps. 
Being able to duplicate items in the Outline view would also be helpful UX, to allow reusing egg. an animation groups properties  as a template for next to add.

**Additional context (OPTIONAL):**
This feature request is about ux and development speed.

**Comment by AGulev** [comment]
fixed by https://github.com/defold/defold/pull/8837
