### ISSUE TITLE
Engine build fails on macOS due to missing toolchain binaries

### ISSUE THREAD

**Issue by dapetcu21** [defold/defold#5382]
**Describe the bug (REQUIRED)**
If the install guide is followed by the letter, at the `build_engine` step, the build fails with a "Missing dsymutil" error. This happens because [this commit](https://github.com/defold/defold/commit/5f3595362f4cd29c8424ca63b791a5fc12fb303c) added `--exclude=${_name}/usr/bin` to [`./scripts/package/package_xcode_and_sdks.sh`](https://github.com/defold/defold/blame/7c741edef4a30dd2ee890834e71251458a8421b6/scripts/package/package_xcode_and_sdks.sh#L93).

Manually copying the binaries into the Xcode toolchain archive or `tmp/dynamo_home/ext/SDKs` makes the engine build successfully.

**To Reproduce (REQUIRED)**
```
./scripts/build.py --platform=x86_64-darwin shell
./scripts/package/package_xcode_and_sdks.sh
./scripts/build.py --platform=x86_64-darwin install_ext --package-path http://localhost:6611
./scripts/build.py --platform=x86_64-darwin build_engine
```

**Expected behavior (REQUIRED)**
It should find the toolchain binaries

**Defold version (REQUIRED):**
  - Latest `dev` branch (7c741edef4a30dd2ee890834e71251458a8421b6)

**Platforms (REQUIRED):**
 - Platforms: macOS 11.0, Xcode 12.0

**Workaround (OPTIONAL):**
```
cp -a /Applications/Xcode_12_0.app/Contents/Developer/Toolchains/XCodeDefault.xctoolchain/usr/bin tmp/dynamo_home/ext/SDKs/XcodeDefault12.0.xctoolchain/usr/bin
cp -a /Applications/Xcode_12_0.app/Contents/Developer/Toolchains/XCodeDefault.xctoolchain/usr/lib/*.dylib tmp/dynamo_home/ext/SDKs/XcodeDefault12.0.xctoolchain/usr/lib
```

**Comment by JCash** [comment]
Yes, it's an issue that the package script currently only produces the slim version of the package (for linux builds)
The "full" version is needed when building on macOS.

**Comment by dapetcu21** [comment]
Should this still be kept open? Merging #5379 fixed this, but a slim package should still be created for Linux builds. Do we open a new issue or keep this one around for this purpose?

**Comment by JCash** [comment]
A fix is coming in https://github.com/defold/defold/pull/5426
