### ISSUE TITLE
Support for compound operators in lua

### ISSUE THREAD

**Issue by andersand** [defold/defold#5384]
**Is your feature request related to a problem? Please describe (REQUIRED):**
The lack of common programming language operators known as compound operators makes writing lua scripts tedious, eg. where each time you would write simply 
**self.myvariable += self.something** 
you now have to write 
self.myvariable = self.myvariable + self.something 

This is a problem in readability and slows down development speed and violates a coder's principle known as DRY. I'm sure you are familiar with. This feature request would make it more fun a less tedious to work with lua in defold. 

**Describe the solution you'd like (REQUIRED):**
Compound operators can be added to the lua interpreter by applying lua power patch (supports Lua 5.4 which I believe is used by Defold?)
The patch can be found here [LuaPowerPatches](http://lua-users.org/wiki/LuaPowerPatches) and i believe it also details how to build a lua version with the patch applied.

**Describe alternatives you've considered (REQUIRED):**
None that I can think of, as the lua interpreter library is probably internalized into defold.exe rather than referemnced in my OS (in which case I could just do it myself).

**Additional context (OPTIONAL):**

**Comment by britzl** [comment]
Defold uses LuaJIT 2.1 which has the same language features as Lua 5.1.

**Comment by britzl** [comment]
We will not make any changes to the version of Lua we bundle with the engine. Closing.
