### ISSUE TITLE
Material constants as attributes of vertices

### ISSUE THREAD

**Issue by aglitchman** [defold/defold#5393]
**Is your feature request related to a problem? Please describe (REQUIRED):**
_The idea is described [in the forum post](https://forum.defold.com/t/setting-alpha-of-objects-without-adding-lots-of-drawcalls/28149/3)._

Defold generates vertex buffers every frame to batch the draw of sprites and meshes/models with materials of the “World” vertex space. The different values of uniform constants break these batches.

**Describe the solution you'd like (REQUIRED):**
It will be useful to introduce a new type of material constants that Defold adds as attributes of vertices. As a result, the engine will generate a bit more per-vertex data to draw sprites. But the different alpha or tint values are not going to break batches anymore!

**Describe alternatives you've considered (REQUIRED):**
I prepare different sprites for each alpha or tint value. This is very expensive in texture space.

**Comment by AGulev** [comment]
it also should be represented in Sprite component in the editor as `tint` field to make it easier for customisation

**Comment by britzl** [comment]
Researched in https://github.com/defold/defold/issues/3403#issuecomment-1357363052

**Comment by britzl** [comment]
We will create new issues which will cover this usecase once we are finished with the design in #3403 .

**Comment by aglitchman** [comment]
It was an incredibly important feature request which would have been given a huge performance boost to all 2D Defold games.

I'm looking forward to https://github.com/defold/defold/issues/3403 and will follow the issue 🙌🏻

**Comment by britzl** [comment]
@aglitchman the new system we're planning will be flexible and solve the kind of problems you bring up.

@Jhonnyg will be able to give more info. And we will share the design document once it is done.
