### ISSUE TITLE
Add the API lookup features of Zeal / Dash directly to the editor

### ISSUE THREAD

**Issue by subsoap** [defold/defold#5395]
I use Zeal so often that I think it would be useful for many others to have the docset directly part of the editor in some way. Wishlist feature.

![2020-12-09 14_37_59-Window](https://user-images.githubusercontent.com/409170/101697173-2d6ca900-3a2c-11eb-811b-8a478c3a6953.png)

https://github.com/zealdocs/zeal/

**Comment by AGulev** [comment]
@vlaaad added this feature https://x.com/v1aaad/status/1707363085881680181?s=20
it's not the same, but maybe it's enough?

**Comment by britzl** [comment]
I think it is enough. Let's close.
