### ISSUE TITLE
Update Editor progress bar doesn't work on launch screen

### ISSUE THREAD

**Issue by AGulev** [defold/defold#5408]
**Describe the bug (REQUIRED)**
Update Editor progress bar doesn't work on launch screen
<img width="999" alt="image" src="https://user-images.githubusercontent.com/2209596/102369869-bb143f80-3fbc-11eb-8103-ceb3ffca2b6c.png">

**To Reproduce (REQUIRED)**
Tap update Editor in launch screen

**Expected behavior (REQUIRED)**
It should work

**Defold version (REQUIRED):**
1.2.177

**Platforms (REQUIRED):**
 - Platforms:  macOS
 - OS: MacOs Catalina

**Comment by britzl** [comment]
Ah, this is probably caused by recent changes to the editor stylesheets.

**Comment by aglitchman** [comment]
On Windows, it's exactly the same bug. And it has been around for a very very long time. The progress of loading the editor goes like this:
- click on Update Available
- we see an empty progress bar
- the progress bar becomes 50% (no animation, just 50% at once)
- the update is complete.

There is no real loading progress.
