### ISSUE TITLE
Out of memory error in emscripten builds

### ISSUE THREAD

**Issue by dapetcu21** [defold/defold#5411]
**Describe the bug (REQUIRED)**
We have a medium-sized project with rather large assets that we have to also ship on HTML5. 

About 70% of the time when loading a certain scene, it crashes with an out of memory error in `_emscripten_resize_heap`. Adjusting the heap size in `game.project` or playing with it directly from `custom_heap_size` in `index.html` does not make a difference.

I also remember seeing this in Interrogation when I tried compiling it for HTML5 some time ago, but I didn't give it much thought (even though that game runs on iOS devices with 1GB of RAM).

<img width="1043" alt="Screenshot 2020-12-17 at 00 48 09" src="https://user-images.githubusercontent.com/428060/102415832-89719780-4001-11eb-8f20-8ab67704639c.png">

**To Reproduce (REQUIRED)**
It reproduces about 70% of the time in my projects, but I don't know how to / don't have the time to make a minimal repro case.

**Expected behavior (REQUIRED)**
A clear and concise description of what you expected to happen. Not a crash. Or at last a crash when setting the heap size consistently too low.

**Defold version (REQUIRED):**
  - Some recent alpha build: 92371cedbb8d55997ee92619af40ee4d973abe3c

**Platforms (REQUIRED):**
 - Platforms: HTML5
 - OS: macOS latest Safari, Chrome (on Safari the crashes seem to happen more often)

**Comment by aglitchman** [comment]
I agree. Setting a custom heap size for HTML5 build does nothing.

**Comment by AGulev** [comment]
I just checked, and yes, it doesn't work ( 
It's a critical bug actually (

**Comment by subsoap** [comment]
Try to edit dmloader.js and where it says Module["TOTAL_MEMORY"] = params["custom_heap_size"]; add a line below it

```
Module["wasmMemory"] = params["custom_heap_size"];
```

**Comment by AGulev** [comment]
https://github.com/emscripten-core/emscripten/blob/9c58ccb2cc55b5c9c2bd24ce962d4b1e924fb009/src/settings.js#L152

**Comment by aglitchman** [comment]
I mentioned [the problem in Slack a few months ago](https://defold.slack.com/archives/C110FQT2Q/p1598709932069300). I wish I weren't so lazy to make an issue about it!

So, a heap size for WASM can't be set in runtime starting from Emscripten 1.39. You should set it as a build argument, i.e. "-s INITIAL_MEMORY=268435456" (or TOTAL_MEMORY=268435456, which is a deprecated name of that variable).

**Comment by aglitchman** [comment]
Maybe the best solution is to add build option `-s ALLOW_MEMORY_GROWTH=1` (it adds [a little overhead](https://emscripten.org/docs/optimizing/Optimizing-Code.html#memory-growth)). So, Defold Heap Size will have a different meaning. It will be the initial memory size for HTML5 build, not total.

**Comment by britzl** [comment]
I agree. This is something we need to look into!

**Comment by dapetcu21** [comment]
> So, heap size for WASM can't be set in runtime starting from Emscripten 1.39. You should set it as a build argument, i.e. "-s INITIAL_MEMORY=1073741824" (or TOTAL_MEMORY=1073741824, which is a deprecated name of that variable).

I'm not sure that's 100% true. I managed to get it working on both WASM and ASM.js, with a simple
`Module.INITIAL_MEMORY = some_value`. 

The trick is that `Module.runApp()` is too late for that call. It needs to happen before loading the wasm/asm.js JS files, since that value is read when the script loads. Calling that any time before `EngineLoader.load()` works like a charm.

**Comment by aglitchman** [comment]
Oh. Could you please double-check the allocated amount of memory? Check the value of `Module.HEAP8.length` in Chrome console.

**Comment by dapetcu21** [comment]
> Oh. Could you please double-check the allocated amount of memory? Check the value of `Module.HEAP8.length` in Chrome console.

Yup. It works. It's the correct value. Not sure what version the bob.jar I have though. Give me 10 mins for the CI to finish because there I'm using the latest alpha straight from the dev branch (irresponsible, I know, but I needed some unreleased fixes).

**Comment by dapetcu21** [comment]
False alarm, I guess. It doesn't work on the latest emscripten (though it does on older engines).

**Comment by AGulev** [comment]
@dapetcu21  I think @aglitchman solved it in 1.2.179? Could you check it in your project pls?

**Comment by dapetcu21** [comment]
Will check as soon as CI is done.

**Comment by dapetcu21** [comment]
Yup. Confirmed it works under Defold v1.2.178 (af6a29, stable branch). The smaller initial memory fix that landed in the 1.2.179 beta is not relevant for me, since I need more memory not less.
