### ISSUE TITLE
Improve launching on desktop (DEF-3442)

### ISSUE THREAD

**Issue by subsoap** [defold/defold#5419]
Right now even if your main collection is empty the game hangs on a blank white screen (at least on windows) for a few moments

![2017-10-07 18_22_27-defold editor 2 0 - project](https://user-images.githubusercontent.com/409170/31313082-9a9fe7a8-ab8c-11e7-83cc-ba5962110ea8.png)

A black screen instead would be better, what would be best is if we had some control over what is displayed at this point such as an image over a solid color, and making the window appear to hang (windows wait cursor icon shows instead of normal cursor) is also bad because along with the white window it gives a bad first impression.

![fmksr](https://user-images.githubusercontent.com/409170/31313093-015332b6-ab8d-11e7-8392-425299af7e4a.gif)

If, in the bundle process, you could hex edit the binary so that the default "GLFW Window" text is the game project title text that would also be useful. Or just edit the source/binary for GLFW so that this text is not displayed (no text) or displays something more useful such as "Loading..."

**Comment by britzl** [comment]
@subsoap is this still a problem?

**Comment by gianmichelemariani** [comment]
This is something I've seen on iOS as well, were you get the image from the storyboard and it flashes black before setting the clear color.

**Comment by britzl** [comment]
What's also noticed on Windows is that the window seems to open, then close and then open again in very rapid succession.

The reason the window is closed and opened again is because we decide that the context has to be recreated:

https://github.com/defold/defold/blob/dev/engine/glfw/lib/win32/win32_window.c#L1460-L1484

**Comment by britzl** [comment]
This process of recreating the window that happens in glfw is not done on glfw3: https://github.com/glfw/glfw/blob/master/src/win32_window.c#L1385
