### ISSUE TITLE
Undo Keymapping not correct on german keyboard

### ISSUE THREAD

**Issue by epiehl** [defold/defold#5421]
### Expected behaviour
cmd + z should trigger undo action in editor.

### Actual behaviour
Menu item "Edit" at the top flashes, but the undo is not happening. Using cmd + y works perfecty

### Steps to reproduce
I guess use german keyboard layout and english os language.

<hr/>

<table>
<tr><td>Build time</td><td>2020-12-18T20:29:09.347449</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>15990df1280c63c1744849d6456237c6411f593e</td></tr>
<tr><td>Defold engine sha</td><td>f7778a8f59ef2a8dda5d445f471368e8bd1cb1ac</td></tr>
<tr><td>Defold version</td><td>1.2.177</td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 5300M OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-3.10.18</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.15.7</td></tr>
<table>

**Comment by beldenfox** [comment]
This was due to a bug in JavaFX. The bug has been fixed with pull request openjdk/jfx#425.

**Comment by AGulev** [comment]
Fixed in 1.6.4
