### ISSUE TITLE
Allow override of default scripts / GUI scripts / Lua modules

### ISSUE THREAD

**Issue by subsoap** [defold/defold#5430]
Using a similar setup as the new editor CSS features. Allow us to put a default .script / .gui_script / .lua in this folder to be used as the template. Often people want to include some comments at the top with information. In the case of Lua modules 9 times out of 10 I do something like below initially and having a template with it would be nice. I would also make my .script / .gui_script files not have any of the comments in the base ones.

```
local M = {}

return M
```

**Comment by vlaaad** [comment]
Same as #6694

**Comment by AGulev** [comment]
Closed as duplicate of https://github.com/defold/defold/issues/6694
