### ISSUE TITLE
Runtime atlas merging

### ISSUE THREAD

**Issue by subsoap** [defold/defold#5435]
**Is your feature request related to a problem? Please describe (REQUIRED):**
Often in big and complex games we want to reduce draw calls while also lowering active memory footprint. These two goals are at odds with each other as to reduce drawcalls we want to have everything on a single atlas if possible. But with games of certain designs with expansive assets possible the required total atlas size can be too big to be reasonable.

**Describe the solution you'd like (REQUIRED):**
Add a new type of atlas called a "merged atlas" in this file the user can add normal atlases to them. 

These merged atlases take texture information from the normal atlases and stream them in and out automatically as needed by their use in the game. 

Devs should be able to specify when to load/unload specific atlas sets as well / force some to always be loaded. To keep it simple the original texture space could be used and the extra atlases streamed in could simply be loaded into the total chunk space of the merged atlas. 

Since normal atlases are packed pretty efficiently there should not be too much lost space and it would make it so the entire atlas does not need major changes when loading/other chunk space. 

Chunk space could be in power of 2 segments, and the merged atlas could be able to automatically expand / be preset to a max size (like 4096). Then devs could focus putting assets into smaller atlases in smaller atlas sizes like 256 or 512. Doing it this way would also simplify the UV changes.

This way we can keep assets generally in smaller atlases, but have the ability to bring multiple atlases into a merge atlas at any time as they are needed to reduce total drawcalls.

![merged_atlas_example](https://user-images.githubusercontent.com/409170/103228185-0267cd80-48e5-11eb-8598-406c6bed0fa0.jpg)

Above is a visual idea of how this could be done dynamically to fill a 4096 merged atlas.

When sprites or nodes use textures from a merged atlas it should async load them in a similar way as font glyphs are loaded/unloaded. The sprites/nodes/spine could have 2 references if the first reference is for a merged atlas then a second must be assigned for the target normal atlas that way there are no breaking changes in code, the references in code for playing animations would be the same as before.

**Describe alternatives you've considered (REQUIRED):**
The only real solution is to accept higher drawcalls while using multiple atlases, which is less efficient. In some games where it's necessary to stack stuff in z space we can see drawcalls go from 40 to 300 depending on how we manually put assets together in the same atlases or not without any other things which break draw calls going on.

**Additional context (OPTIONAL):**
As hardware advances this will be less necessary for complex games but for now it would still be useful especially with mobile releases.

**Comment by britzl** [comment]
We need to break this down into multiple subtasks. We want to add more APIs to create and manipulate textures.

**Comment by britzl** [comment]
Covered by https://github.com/defold/defold/issues/5948
