### ISSUE TITLE
Missed docs for DM_HEADLESS, DM_DEBUG and DM_RELEASE

### ISSUE THREAD

**Issue by AGulev** [defold/defold#5438]
**Is your feature request related to a problem? Please describe (REQUIRED):**
It woulds be nice to have info about these defines in documentation

**Comment by AGulev** [comment]
Hmm, also I'm not sure if DM_DEBUG works. I tested in my extension and `defined(DM_DEBUG)` always is false

**Comment by JCash** [comment]
I agree it is a good request, I'll look into it.

`DM_DEBUG` is defined in the [debug.appmanifest](https://github.com/defold/defold/blob/dev/share/extender/variants/debug.appmanifest) in the sdk and should be used automatically if you're using the debug variant.

Check your log.txt to see the command lines. Isn't it there?

**Comment by AGulev** [comment]
hmm, yes, you right, I see it in log.
```
clang++ -c -arch x86_64 -target x86_64-apple-darwin19 -isysroot /opt/platformsdk/MacOSX10.15.sdk/ -m64 -O2 -g -stdlib=libc++ -mmacosx-version-min=10.7 -DDLIB_LOG_DOMAIN="DEFOS" -DDM_PLATFORM_OSX -DLUA_BYTECODE_ENABLE_64 -DDM_DEBUG  -fno-exceptions -fvisibility=hidden  -Iupload/defos/include/ -Iupload/ -Iupload/devposandsize/include   -I/var/extender/sdk/f7778a8f59ef2a8dda5d445f471368e8bd1cb1ac/defoldsdk//include -I/var/extender/sdk/f7778a8f59ef2a8dda5d445f471368e8bd1cb1ac/defoldsdk//sdk/include  upload/defos/src/defos_linux.cpp -obuild/defos_linux.cpp_4.o
```

but it's when I make a bundle. When I build (Cmd+B) I don't have log and check it like
```
    #if defined(DM_DEBUG)
        dmLogInfo("lala");
    #endif
```
