### ISSUE TITLE
While following the side scrolling tutorial (while the game was running) I just click on the Assets pane main folder holding Shift.

### ISSUE THREAD

**Issue by wootr0p** [defold/defold#5443]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2020-12-18T20:28:49.967999</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>15990df1280c63c1744849d6456237c6411f593e</td></tr>
<tr><td>Defold engine sha</td><td>f7778a8f59ef2a8dda5d445f471368e8bd1cb1ac</td></tr>
<tr><td>Defold version</td><td>1.2.177</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"0834890f240b41deb4d28ec7798eb393"'>0834890f240b41deb4d28ec7798eb393</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon(TM) RX Vega 10 Graphics</td></tr>
<tr><td>GPU Driver</td><td>4.5.13587 Compatibility Profile Context 19.40.54.01 26.20.14054.1001</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by wootr0p** [comment]
Sorry but I'm unable to clarify or reproduce again the error.

**Comment by britzl** [comment]
`class java.lang.IndexOutOfBoundsException com.sun.javafx.scene.control.ReadOnlyUnbackedObservableList.subList`

Thanks. Let us know if you find a repro case!
