### ISSUE TITLE
Java exception in code editor while hitting extra mouse buttons

### ISSUE THREAD

**Issue by alxgb** [defold/defold#5449]
### Expected behaviour
Not receiving an error would be enough, honestly didn't really expect anything to happen, I just hit my mouse button accidentally

### Actual behaviour
I receive an error. I guess you can see it on Sentry, but it's
`java.lang.IllegalArgumentException: No matching clause: FORWARD`

### Steps to reproduce
Clicking on my mouse's m4/m5 buttons (bottom left, g4/g5 as per Logitech). That's it.
I use a Logitech G502. In some applications, like browsers, these buttons do cause forward and backward events.

In VSCode they move you through tabs, but it'd just be nice to not get an error if that functionality is too much!

<hr/>

<table>
<tr><td>Build time</td><td>2020-12-29T20:30:19.122767</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>15990df1280c63c1744849d6456237c6411f593e</td></tr>
<tr><td>Defold engine sha</td><td>f7778a8f59ef2a8dda5d445f471368e8bd1cb1ac</td></tr>
<tr><td>Defold version</td><td>1.2.177</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"ad3e19ab0089447abba553dfb4b4ef09"'>ad3e19ab0089447abba553dfb4b4ef09</a></td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by otsakir** [comment]
There is already an old issue about extra mouse buttons 4/5 bug:

https://github.com/defold/defold/issues/5091

Is this a duplicate?

**Comment by alxgb** [comment]
Definitely is! Admittedly I just clicked the report button in the editor and didn't think it through too much, my bad.

Closing this one

**Comment by alxgb** [comment]
Duplicate of #5091
