### ISSUE TITLE
letters from another language are not displayed in runtime and build

### ISSUE THREAD

**Issue by xxxKfkxxx** [defold/defold#5459]
I wanted to localize my game and added new font with non english characters, I checked "All Chars" box
These letters displayed in editor in gui text node, but not displayed in runtime and build. Instead of each letter there is "~"

<hr/>

<table>
<tr><td>Build time</td><td>2021-01-11T13:29:33.638310</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>15c3fb12f092d565bb8d549a961e91ff78f97528</td></tr>
<tr><td>Defold engine sha</td><td>af6a29c2a1e2545e2d033790089c606ac9f0bb7a</td></tr>
<tr><td>Defold version</td><td>1.2.178</td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) UHD Graphics (CML GT2)</td></tr>
<tr><td>GPU Driver</td><td>2.1 Mesa 20.0.8</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.4.0-58-generic</td></tr>
<table>

**Comment by subsoap** [comment]
Could you upload a minimal example project with the font you are using set up without the glyphs displaying properly and upload here in a zip?

**Comment by xxxKfkxxx** [comment]
Oh, sorry, it is my mistake.
I tried to change font in system_font.font. When I created a new font and added there my font, all became normal
