### ISSUE TITLE
An error occurred while I forgot Defold was running.

### ISSUE THREAD

**Issue by bryanrieger** [defold/defold#5467]
clojure.lang.ExceptionInfo: handler ':sort-lines' in context ':code-view' failed at ':enabled?' with message 'class clojure.lang.MapEntry cannot be cast to class editor.code.data.CursorRange (clojure.lang.MapEntry and editor.code.data.CursorRange are in unnamed module of loader 'app')'
java.lang.ClassCastException: class clojure.lang.MapEntry cannot be cast to class editor.code.data.CursorRange (clojure.lang.MapEntry and editor.code.data.CursorRange are in unnamed module of loader 'app')

### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2021-01-11T13:30:10.989782</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>15c3fb12f092d565bb8d549a961e91ff78f97528</td></tr>
<tr><td>Defold engine sha</td><td>af6a29c2a1e2545e2d033790089c606ac9f0bb7a</td></tr>
<tr><td>Defold version</td><td>1.2.178</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"c2a56411ebec4d1dba57c58f76110741"'>c2a56411ebec4d1dba57c58f76110741</a></td></tr>
<tr><td>GPU</td><td>Intel(R) Iris(TM) Plus Graphics OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-14.7.11</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.15.7</td></tr>
<table>

**Comment by AGulev** [comment]
should be solved in newer defodl editor
