### ISSUE TITLE
Sometimes on Windows it appears that ghost sounds sometimes happen / causes engine to lag/ not close properly

### ISSUE THREAD

**Issue by subsoap** [defold/defold#5479]
**Describe the bug (REQUIRED)**

At some point the sound buffer is filling up with sounds not making any audio

```
ERROR:GAMESYS: A sound could not be played since the sound buffer is full (32). Message 'play_sound' sent from main:/_audio/_play_proxy#audio_play_proxy to main:/_audio/_sfx#hand_start.
ERROR:GAMESYS: A sound could not be played since the sound buffer is full (32). Message 'play_sound' sent from main:/_audio/_play_proxy#audio_play_proxy to main:/_audio/_sfx#button_click.
```

When closing
```
INFO:SOUND: Waiting for OpenAL device to complete
ERROR:SOUND: Still buffers in OpenAL. Bailing.
INFO:SOUND: Waiting for OpenAL device to complete
ERROR:SOUND: Still buffers in OpenAL. Bailing.
INFO:SOUND: Waiting for OpenAL device to complete
ERROR:SOUND: Still buffers in OpenAL. Bailing.
INFO:SOUND: Waiting for OpenAL device to complete
ERROR:SOUND: Still buffers in OpenAL. Bailing.
INFO:SOUND: Waiting for OpenAL device to complete
ERROR:SOUND: Still buffers in OpenAL. Bailing.
INFO:SOUND: Waiting for OpenAL device to complete
ERROR:SOUND: Still buffers in OpenAL. Bailing.
INFO:SOUND: Waiting for OpenAL device to complete
ERROR:SOUND: Still buffers in OpenAL. Bailing.
INFO:SOUND: Waiting for OpenAL device to complete
ERROR:SOUND: Still buffers in OpenAL. Bailing.
INFO:SOUND: Waiting for OpenAL device to complete
ERROR:SOUND: Still buffers in OpenAL. Bailing.
```

![2021-01-16 17_39_20-Window](https://user-images.githubusercontent.com/409170/104828784-cd82d280-5821-11eb-9451-52a5a958cdc8.png)

When I go to close the engine in this situation it hangs and I have to force close it.

**To Reproduce (REQUIRED)**
Not sure how to reproduce at the moment. Things that happen are copy of engine running for a while. Might be replaced to Windows being suspended. Maybe we have a bad sound that's playing and causing it possibly (maybe making buffers to fill and OpenAL complaining.)

**Expected behavior (REQUIRED)**

**Defold version (REQUIRED):**
1.2.178

**Platforms (REQUIRED):**
Windows 10

**Comment by subsoap** [comment]
I think the likely cause is switching audio devices. I have a bluetooth headset I sometimes use and I realize this happens around the time I turn off the bluetooth headset and go back to speakers. So some kind of strange interaction there possibly. Will do more testing.

**Comment by paweljarosz** [comment]
Looks like a duplicate of: https://github.com/defold/editor2-issues/issues/2818, but I have a case more similar to this one (switching or unplugging BT headphones)

**Comment by subsoap** [comment]
Yeah this is a dupe. At least we know why it's happening now!
