### ISSUE TITLE
Stucked on new project

### ISSUE THREAD

**Issue by CocosGames** [defold/defold#5484]
### Expected behaviour
Open up and load new project templates.
### Actual behaviour
Stucked and error.
### Steps to reproduce
Open Defold and click new project.
<hr/>

<table>
<tr><td>Build time</td><td>2021-01-16T10:47:07.405749</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>3d2d4932d02dabc7e57fd25fac275b0a6dc59158</td></tr>
<tr><td>Defold engine sha</td><td>af6a29c2a1e2545e2d033790089c606ac9f0bb7a</td></tr>
<tr><td>Defold version</td><td>1.2.178</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"f1642099f5664b889db82442771fbb4c"'>f1642099f5664b889db82442771fbb4c</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon VII</td></tr>
<tr><td>GPU Driver</td><td>4.5.13559 Compatibility Profile Context 26.20.12028.2</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
```
class java.net.SocketTimeoutException
Read timed out
```

Does this happen for all project templates or a single one? The editor will make a connection to GitHub to download the code for the template.

You can also find the templates here: https://github.com/defold?q=template-&type=&language=

**Comment by CocosGames** [comment]
I removed and reinstalled Defold, the problem solved.

info table:

<table>
<tr><td>Build time</td><td>2021-01-11T09:05:23.046859</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>af6a29c2a1e2545e2d033790089c606ac9f0bb7a</td></tr>
<tr><td>Defold engine sha</td><td>af6a29c2a1e2545e2d033790089c606ac9f0bb7a</td></tr>
<tr><td>Defold version</td><td>1.2.178</td></tr>
<tr><td>GPU</td><td>AMD Radeon VII</td></tr>
<tr><td>GPU Driver</td><td>4.5.13559 Compatibility Profile Context 26.20.12028.2</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
> I removed and reinstalled Defold, the problem solved.

Strange! But happy to hear the problem was resolved!
