### ISSUE TITLE
GUI doesn't start in Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by DinoMah** [defold/defold#5507]
DESCRIPTION
It just shows the splash screen continuously, here the error running the program from console:
`com.jogamp.opengl.GLException: Graphics configuration failed [direct caps, eglGetConfig/chooser and fixed-caps(1-3)] at jogamp.opengl.egl.EGLGraphicsConfigurationFactory.chooseGraphicsConfigurationStatic(EGLGraphicsConfigurationFactory.java:317) at jogamp.opengl.egl.EGLDrawableFactory.evalConfig(EGLDrawableFactory.java:1060) at jogamp.opengl.egl.EGLDrawableFactory.createMutableSurfaceImpl(EGLDrawableFactory.java:1072) at jogamp.opengl.egl.EGLDrawableFactory.createMutableSurfaceImpl(EGLDrawableFactory.java:88) at jogamp.opengl.GLDrawableFactoryImpl.createOffscreenDrawable(GLDrawableFactoryImpl.java:432) at jogamp.opengl.GLDrawableFactoryImpl.createOffscreenAutoDrawable(GLDrawableFactoryImpl.java:373) at editor.gl$unchecked_offscreen_drawable.invokeStatic(gl.clj:51) at editor.gl$init_info_BANG_.invokeStatic(gl.clj:106) at editor.gl$info.invokeStatic(gl.clj:120) at editor.gl$gl_support_error.invokeStatic(gl.clj:122) at editor.boot$main.invokeStatic(boot.clj:111) at editor.boot$main.invoke(boot.clj:107) at clojure.lang.Var.invoke(Var.java:388) at editor.bootloader$main.invokeStatic(bootloader.clj:65) at editor.bootloader$main.invoke(bootloader.clj:59) at clojure.lang.Var.invoke(Var.java:384) at org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl.invoke(ClojureRuntimeShimImpl.java:109) at org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl.invoke(ClojureRuntimeShimImpl.java:102) at com.defold.editor.EditorApplication.run(EditorApplication.java:38) at com.defold.editor.Start.lambda$kickLoading$0(Start.java:62) at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428) at java.base/java.security.AccessController.doPrivileged(Native Method) at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427) at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96) at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277) at java.base/java.lang.Thread.run(Thread.java:834) 2021-01-28 12:37:31.890 ERROR default com.defold.editor.Start - failed to open editor com.jogamp.opengl.GLException: Graphics configuration failed [direct caps, eglGetConfig/chooser and fixed-caps(1-3)] at jogamp.opengl.egl.EGLGraphicsConfigurationFactory.chooseGraphicsConfigurationStatic(EGLGraphicsConfigurationFactory.java:317) at jogamp.opengl.egl.EGLDrawableFactory.evalConfig(EGLDrawableFactory.java:1060) at jogamp.opengl.egl.EGLDrawableFactory.createMutableSurfaceImpl(EGLDrawableFactory.java:1072) at jogamp.opengl.egl.EGLDrawableFactory.createMutableSurfaceImpl(EGLDrawableFactory.java:88) at jogamp.opengl.GLDrawableFactoryImpl.createOffscreenDrawable(GLDrawableFactoryImpl.java:432) at jogamp.opengl.GLDrawableFactoryImpl.createOffscreenAutoDrawable(GLDrawableFactoryImpl.java:373) at editor.gl$unchecked_offscreen_drawable.invokeStatic(gl.clj:51) at editor.gl$init_info_BANG_.invokeStatic(gl.clj:106) at editor.gl$info.invokeStatic(gl.clj:120) at editor.gl$gl_support_error.invokeStatic(gl.clj:122) at editor.boot$main.invokeStatic(boot.clj:111) at editor.boot$main.invoke(boot.clj:107) at clojure.lang.Var.invoke(Var.java:388) at editor.bootloader$main.invokeStatic(bootloader.clj:65) at editor.bootloader$main.invoke(bootloader.clj:59) at clojure.lang.Var.invoke(Var.java:384) at org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl.invoke(ClojureRuntimeShimImpl.java:109) at org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl.invoke(ClojureRuntimeShimImpl.java:102) at com.defold.editor.EditorApplication.run(EditorApplication.java:38) at com.defold.editor.Start.lambda$kickLoading$0(Start.java:62) at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428) at java.base/java.security.AccessController.doPrivileged(Native Method) at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427) at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96) at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277) at java.base/java.lang.Thread.run(Thread.java:834) `

TO REPRODUCE
Just open Defold in Ubuntu 24.04

EXPECTED BEHAVIOR
Open the editor to start the project

DEFOLD VERSION
1.2.178

PLATFORMS
- Linux (Ubuntu 24.04)

**Comment by britzl** [comment]
@DinoMah could you please try this: https://defold.com/manuals/linux/#q-why-does-the-defold-editor-crash-when-i-try-to-create-a-new-project-or-open-an-existing-one

**Comment by UltraBurstXD** [comment]
Same thing here... Tried link above, didn't work.

**Comment by bjconlan** [comment]
I can confirm that I saw a similar issue (Defold 1.2.180) and directions provided by @britzl do resolve the issue, specifically running the application via `MESA_GL_VERSION_OVERRIDE=2.1 ./Defold`
