### ISSUE TITLE
Can't create new project from GameDistribution template. It throws error

### ISSUE THREAD

**Issue by DanMorEx** [defold/defold#5508]
### Expected behaviour
Create a new project from template

### Actual behaviour
Can't create new project from template. It throws error

### Steps to reproduce
Start Defold -> New Project -> From Template -> GameDistribution Game

<hr/>

<table>
<tr><td>Build time</td><td>2021-01-21T11:58:21.335092</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>6a2045f58d54c0cad54994021954856dd1425178</td></tr>
<tr><td>Defold engine sha</td><td>af6a29c2a1e2545e2d033790089c606ac9f0bb7a</td></tr>
<tr><td>Defold version</td><td>1.2.178</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"eaeaf6c5a0a14fd996dcf53d5058e903"'>eaeaf6c5a0a14fd996dcf53d5058e903</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 1050/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 460.89</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
@DanMorEx thank you for pointing this out! GitHub has changed name of the default main branch from `master` to `main` and the editor config didn't take this into account.

A new editor version is building now and an update will be available in half an hour or so.
