### ISSUE TITLE
java.util.concurrent.ExecutionException: java.lang.AssertionError: Assert failed: (not (g/error? bytecode))

### ISSUE THREAD

**Issue by R5dwMg** [defold/defold#5510]
### Expected behaviour
Display syntax error on console

### Actual behaviour
Prompted exception
java.util.concurrent.ExecutionException: java.lang.AssertionError: Assert failed: (not (g/error? bytecode))
java.lang.AssertionError: Assert failed: (not (g/error? bytecode))

### Steps to reproduce
Accidentally made syntax error on script
go.property(name, value)("id", message.id)

The whole script :
```
function on_message(self, message_id, message, sender)
	-- Add message-handling code here
	-- Learn more: https://defold.com/manuals/message-passing/
	-- Remove this function if not needed
	if message_id == hash("collision_response") then
		print("hotspot hit " )
	elseif message_id == hash("set_id") then
		print("set id")
		go.property(name, value)("id", message.id)
	end
end
```

<hr/>

<table>
<tr><td>Build time</td><td>2021-01-20T12:20:03.977340</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>9dd4cc8e89bf83dd22f2528153573b5cb3b45c11</td></tr>
<tr><td>Defold engine sha</td><td>af6a29c2a1e2545e2d033790089c606ac9f0bb7a</td></tr>
<tr><td>Defold version</td><td>1.2.178</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"b3d8e2cd4c4249e4b6425e68fc3c3730"'>b3d8e2cd4c4249e4b6425e68fc3c3730</a></td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 530</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 - Build 26.20.100.8142</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by AGulev** [comment]
can't reproduce in 1.8.0
