### ISSUE TITLE
Removing multiple files breaks the UI/UX

### ISSUE THREAD

**Issue by Jerakin** [defold/defold#5515]
**Describe the bug (REQUIRED)**
Deleting many files hides the buttons

**To Reproduce (REQUIRED)**
1. Select a lot of files and delete them

**Expected behavior (REQUIRED)**
A List of files that is readable and have buttons visible

**Defold version (REQUIRED):**
  - Version 1.2.178

**Platforms (REQUIRED):**
 - Platforms: Windows

**Workaround (OPTIONAL):**
Use the keyboard to change buttons to accept

**Screenshots (OPTIONAL):**
![2021-01-31 16_16_20-Window](https://user-images.githubusercontent.com/5273682/106388733-2df83f00-63e0-11eb-856b-bf711644fbd6.png)

**Comment by AGulev** [comment]
it seems like this issue solved in the following PR: https://github.com/defold/defold/pull/5657
