### ISSUE TITLE
Particle fx does not start using play/space bar in editor, when selecting emitter

### ISSUE THREAD

**Issue by amitanubha** [defold/defold#5526]
### Expected behaviour
Show live particle preview in editor
### Actual behaviour
Nothing happens
### Steps to reproduce
I am using an old pack from someone to see particles and I can't seem to run in editor, though works when I debug or actual play
<hr/>

<table>
<tr><td>Build time</td><td>2021-02-01T12:52:12.101903</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>6ce404156136f291c4f2c33a72b28f7bd923eb5e</td></tr>
<tr><td>Defold engine sha</td><td>af6a29c2a1e2545e2d033790089c606ac9f0bb7a</td></tr>
<tr><td>Defold version</td><td>1.2.178</td></tr>
<tr><td>GPU</td
[kenney_particle_pack_defold-master.zip](https://github.com/defold/defold/files/5925406/kenney_particle_pack_defold-master.zip)
><td>AMD Radeon Pro 5300M OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-3.10.19</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.15.7</td></tr>
<table>

**Comment by britzl** [comment]
> I am using an old pack from someone to see particles

What do you mean by this?

Does it work if you create a new particle fx?

**Comment by britzl** [comment]
No new info from user. Closing.
