### ISSUE TITLE
Asset/Bundle Locking feature on the Editor

### ISSUE THREAD

**Issue by RiadOkba** [defold/defold#5528]
**Is your feature request related to a problem? Please describe (REQUIRED):**
I want to hire freelancers to finish my game. But I'm afraid of exposing my code to others. 
I have developed my platformer game as modular as possible (sort of template) so I can use it in my future projects. I have used lua modules to implement the key elements of my game: Animation, AI, Game Logic... 
Now I need help to finish some tedious tasks that takes huge amount of time (UI, Sounds, Level Design...). I need to hire freelancers for help, and i need to share with them my full project so they can work efficiently.

**Describe the solution you'd like (REQUIRED):**
I want the editor to give me the right to: 
1- Lock some part of my assets (in my case mainly lua modules and scripts), 
            a- the text of locked files would be encrypted and CAN'T be read from the editor or from Notepad++ or any other app...
            b- my locked files CAN'T be copy/paste or reused with another project
2- Lock the bundle feature (the freelancer won't be able to generate any executable of sort)

However, the engine would still be able to run them (Ctrl+Shift+B), the freelancer can create new GO and be able to refer to the locked files as normal.

**Describe alternatives you've considered (REQUIRED):**
I wanted to use my pc as a server, the freelancer can use his laptop to connect through an app and work on it. I will remove the right of transferring data... Still, I can't monitor what he's doing and he can read my code.

**Additional context (OPTIONAL):**
N/A

**Comment by britzl** [comment]
I understand your concern but this sort of thing is usually part of a subcontractor agreement where the contractor/freelancer enters into a legally binding with you. If you are still concerned about contractors stealing or copying your work then perhaps find more professional contractors with higher credibility and more at stake if they should decide to steal from you.

If that's not possible then my recommendation would be that you find a way to share only enough of your project to let the developer do the work he/she is hired to do.

Locking content like you suggest is not something we will add support for in Defold I'm afraid.

**Comment by RiadOkba** [comment]
Hello Björn,

Thanks a lot for the suggestions and the detailed answer.

Regards
Riad Okba

Le ven. 5 févr. 2021 à 15:18, Björn Ritzl <notifications@github.com> a
écrit :
