### ISSUE TITLE
Ubuntu 20.04: Crash when opening Roids Sample Game main.collection

### ISSUE THREAD

**Issue by jarrellmark** [defold/defold#5535]
### Expected behaviour

Do not crash or show error message.

### Actual behaviour

Displays error message:

```
java.lang.ClassCastException: class jogamp.opengl.es1.GLES1Impl cannot be cast to class com.jogamp.opengl.GL2ES2 (jogamp.opengl.es1.GLES1Impl and com.jogamp.opengl.GL2ES2 are in unnamed module of loader 'app')
```

### Steps to reproduce

1. Open Defold editor from Steam
2. Create new instance of Roids Sample Game project
3. Open project
4. Double click on the left, Assets -> main -> main.collection

Error pops up. `main.collection` file is not viewable or editable. It's blank.

<hr/>

<table>
<tr><td>Build time</td><td>2021-02-01T12:51:27.527828</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>6ce404156136f291c4f2c33a72b28f7bd923eb5e</td></tr>
<tr><td>Defold engine sha</td><td>af6a29c2a1e2545e2d033790089c606ac9f0bb7a</td></tr>
<tr><td>Defold version</td><td>1.2.178</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"5170942d6b8e4fddb186c4bf4913dea4"'>5170942d6b8e4fddb186c4bf4913dea4</a></td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) HD Graphics 5500 (BDW GT2)</td></tr>
<tr><td>GPU Driver</td><td>OpenGL ES-CM 1.1 Mesa 20.3.3 - kisak-mesa PPA</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.8.0-36-generic</td></tr>
<table>

**Comment by jarrellmark** [comment]
Solved by starting Defold like this:

`MESA_GL_VERSION_OVERRIDE=2.1 ./Defold`

For steam Defold can be found here: `~/.steam/steam/steamapps/common/Defold`

`~` means `/home/USERNAME`

**Comment by britzl** [comment]
@jarrellmark I saw that you closed and reopened the issue. Can you confirm that adding MESA_GL_VERSION_OVERRIDE worked for you?

**Comment by jarrellmark** [comment]
Hi @britzl yeah that did work for me. Re-opened the ticket in case someone wants to make this work around not necessary. Feel free to close the ticket though.

**Comment by britzl** [comment]
Thanks! I'm closing this issue as it is a duplicate. We're tracking the problem here: https://github.com/defold/defold/issues/4851
