### ISSUE TITLE
Text metrics operations for labels should be synchronous

### ISSUE THREAD

**Issue by britzl** [defold/defold#5556]
Setting the text of a label using label.set_text() and then immediately calling label.get_text_metrics() will return the metrics for the text that was on the text before the call to label.set_text().

Discussed here: https://forum.defold.com/t/label-get-text-metrics-returns-old-metrics-right-after-setting-text/17644

**Comment by AGulev** [comment]
outdated because of `resource.get_text_metrics(font, "The quick brown fox\n jumps over the lazy dog")`
