### ISSUE TITLE
Custom resources not worked. When project have multiple *.project files

### ISSUE THREAD

**Issue by d954mas** [defold/defold#5557]
Custom resources not worked. When project have multiple *.project files

I use multiple .project file.
1)game.project is base
2)debug_game.project for dev build
3)release_game.project for prod build
4)test_game.project for running tests

All worked ok before i add custom resources.
1)i add custom resources only in game.project. custom_resources = assets/levels/json
2)Try bundle or build html
3)I get message /assets/levels/json/1.json
	Conflicting output resource 'build/default/assets/levels/json/1.json‘ generated by the following input files: [assets/levels/json/1.json, assets/levels/json/2.json, assets/levels/json/3.json, assets/levels/json/4.json, assets/levels/json/5.json, assets/levels/json/6.json, assets/levels/json/7.json, assets/levels/json/8.json] <-> [assets/levels/json/1.json, assets/levels/json/2.json, assets/levels/json/3.json, assets/levels/json/4.json, assets/levels/json/5.json, assets/levels/json/6.json, assets/levels/json/7.json, assets/levels/json/8.json]

3.1)If i add folder that not exist. I get that error.
Conflicting output resource 'build/default/assets/levels/json/sss‘ generated by the following input files: [assets/levels/json/sss] <-> [assets/levels/json/sss]

4)Moving that project files from root to another folder not helped.

5)I rename them from *.project to *.project_settings.
Now it helped.

<hr/>

<table>
<tr><td>Build time</td><td>2021-02-08T09:09:39.603768</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>9892f06543413f700997f15be240cd8078ba4803</td></tr>
<tr><td>Defold engine sha</td><td>5209b50cf4bf8e925cb4c32fd0bde6c53fc85a66</td></tr>
<tr><td>Defold version</td><td>1.2.179</td></tr>
<tr><td>GPU</td><td>GeForce GTX 1070 Ti/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 461.40</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by d954mas** [comment]
https://forum.defold.com/t/conflicting-output-resource-error-solved/50089/8

**Comment by JCash** [comment]
There may only be one `.project` file in a project.

>5)I rename them from *.project to *.project_settings.
Now it helped.

So it's working now?

**Comment by d954mas** [comment]
Yes it working. When I rename. 

But it also worked, with multiple project files, before I add custom resources)) 
Also error message is not helped) 

Maybe add some error or warning when there are multiple project files?

**Comment by d954mas** [comment]
From Bob doc
    --settings <arg>                 a path to a game project settings file. more than one occurrance are allowed. the settings files are applied left to right.

Maybe add some warning, to user. That such files, can't be named as .project.  When I read, i think that I need create settings1.project

**Comment by d954mas** [comment]
I do not think, that Bob should worked with multiple files. It is ok, that. .project is single file.

I think that error should be more correct.
Something like, can't build there are more then one project file.

That error not helped understand the problem)
Conflicting output resource 'build/default/assets/levels/json/sss‘ generated by the following input files: [assets/levels/json/sss] <-> [assets/levels/json/sss]

**Comment by britzl** [comment]
I'm unable to reproduce this problem with the latest version of Defold. @d954mas can you please describe the minimal steps required to reproduce this problem (or share a minimal project)?

**Comment by d954mas** [comment]
[isssue5557.zip](https://github.com/defold/defold/files/6611656/isssue5557.zip)
1)Build from editor worked.
2)Bundle show error.
/assets/levels/1.json
	Conflicting output resource 'build/default/assets/levels/1.json‘ generated by the following input files: [assets/levels/1.json] <-> [assets/levels/1.json]

3)if remove custom resources it build
4)if rename assets/debug.project to if rename assets/debug.lib_project it build.

**Comment by d954mas** [comment]
1.2.182 1a2776dac6a868eed1a35e41acb0c71a7e17948f

**Comment by britzl** [comment]
Issue #5859 will fail builds if there's more than one project file.
