### ISSUE TITLE
Tilemap not visible in the editor

### ISSUE THREAD

**Issue by RiadOkba** [defold/defold#5558]
**Describe the bug (REQUIRED)**
The Tilemap is not visible in the editor. It is visible when running the game though (ctrl+alt+b), but not in the editor!
It was working before the update 1.2.180

**To Reproduce (REQUIRED)**
1. Installed an update today (13-02-2021)
2. Re-start defold 
3. Open my level collections: Tilemap not visible (it was before the update)
4. Open the tilemap in question: not visible
5. Running the game: the tilemap visible!

**Expected behavior (REQUIRED)**
To show the tilemap :)

**Defold version (REQUIRED):**
  - Version 1.2.180

**Platforms (REQUIRED):**

**Minimal repro case project (OPTIONAL):**

**Logs (OPTIONAL):**
enclosed

**Workaround (OPTIONAL):**
Nope

**Screenshots (OPTIONAL):**
Enclosed

**Additional context (OPTIONAL):**
It was working just fine in the old version...
[editor2.2021-02-13.zip](https://github.com/defold/defold/files/5975418/editor2.2021-02-13.zip)
![3](https://user-images.githubusercontent.com/67765342/107846989-591f5d00-6de8-11eb-9258-29429d6eed8f.JPG)
![4](https://user-images.githubusercontent.com/67765342/107846995-5c1a4d80-6de8-11eb-8716-66c4ee839652.JPG)

**Comment by britzl** [comment]
Could you please share your project or a minimal repro case for this? You can send it to bjorn@defold.se

**Comment by RiadOkba** [comment]
Hello

I will do it as soon as possible... Right now I moved to a previous version
and I'm working on it.

Regards
Riad Okba

Le sam. 13 févr. 2021 à 11:48, Björn Ritzl <notifications@github.com> a
écrit :

**Comment by RiadOkba** [comment]
I have reinstalled the update following the same steps I did before... and
the tilemap was visible.

Maybe I didn't restart my project... I'm not sure. Anyway it's working now.

Thanks a lot and sorry for the false alarm.

Regards
Riad Okba
