### ISSUE TITLE
Crash in headless build

### ISSUE THREAD

**Issue by Vbif** [defold/defold#5560]
**Describe the bug (REQUIRED)**
I'm trying to create test that will load all level from my game. It works perfect when run under editor, but crash under headless build.

[_crash.zip](https://github.com/defold/defold/files/5976102/_crash.zip)

**Expected behavior (REQUIRED)**
Success run or more verbose error

**Defold version (REQUIRED):**
  - 1.2.179 (5209b50)

**Platforms (REQUIRED):**
 - macOS

**Logs:**
```
INFO:DLIB: Log server started on port 55139
WARNING:DLIB: No IP found for local hostname 00008390-h. Fallbacks to localhost
INFO:ENGINE: Target listening with name: 00008390-h - ::1 - Darwin
INFO:ENGINE: Engine service started on port 8001
INFO:ENGINE: Defold Engine 1.2.179 (5209b50)
INFO:ENGINE: Loading data from: build/default
INFO:ENGINE: Initialised sound device 'default'
DEBUG:SCRIPT: Load level 1
INFO:DLIB: SSDP: Started on address 192.168.88.208
DEBUG:SCRIPT: Load level 2
INFO:CRASH: Successfully wrote Crashdump to file: /Users/vbif/Library/Application Support/Defold/_crash
ERROR:CRASH: CALL STACK:

# 0 pc   0x137595fd MetadataUtilities _sigtramp+29


./../ci/sh/execute_tests.sh: line 2:  6502 Segmentation fault: 11  ./../ci/cache/dmengine_headless --config=bootstrap.main_collection=/test/test.collectionc
```

**Comment by Vbif** [comment]
Some update: I tried this scripts on linux and it runs correctly. Maybe it's macOS related problem?

**Comment by JCash** [comment]
Hi @Vbif!
Would it be possible for you to create a small repro case project for us to test with?

**Comment by Vbif** [comment]
I can send you whole project ( + scripts) to direct messages on forum. Is this you https://forum.defold.com/u/mathias_westerdahl/summary ?

**Comment by britzl** [comment]
@Vbif Yes that is Mathias, but better to send it via email to mathias@defold.se

**Comment by JCash** [comment]
Hi @Vbif !
Thanks for the test project!
So far, it seems to work without crashing for me on my computer.
I will keep thinking about it to see if I can figure out a way to find why my version works and yours doesn't.

However, I should point out that since you are using native extensions, you won't get the same result by downloading `dmengine_headless` from our prebuilt binaries.

Instead, I recomment you build the headless engine yourself, by specifying `--variant headless` to bob.jar.
That way you'll get the same extensions in the headless version as in the game.

**Comment by Vbif** [comment]
I have hackintosh with Catalina 10.15.4 (19E287), this maybe a problem, but its work really well in all program that I use.

Yes, i should use my own version of engine, this is good advice. Current situation is fragile and test can be broken by some new extension that I add to game.

**Comment by JCash** [comment]
>I have hackintosh with Catalina 10.15.4 (19E287), this maybe a problem, but its work really well in all program that I use.
I don't have any experience with this type of setup, but I don't think it's the cause for the crash.

**Comment by britzl** [comment]
@Vbif have you managed to run the project with a headless version built using bob?

**Comment by vbif1** [comment]
In this particular case native extension could be removed, they are not used in game itself, only in in-game editor. I tested on vanilla engine + game without NE and it have the same behaviour - crush in headless.

**Comment by JCash** [comment]
If you have `lldb` (a C++ debugger), installed, you can try running:

> $ lldb some/path/to/dmengine_headless
> lldb$ run

That might give a lot better callstack.

**Comment by Vbif** [comment]
```
(lldb) target create "../ci/cache/dmengine_headless"
Current executable set to '/Volumes/Work/projects/sola-spaco-2/ci/cache/dmengine_headless' (x86_64).
(lldb) run
Process 17211 launched: '/Volumes/Work/projects/sola-spaco-2/ci/cache/dmengine_headless' (x86_64)
INFO:DLIB: Log server started on port 56970
WARNING:DLIB: No IP found for local hostname p-00008390-h. Fallbacks to localhost
INFO:ENGINE: Target listening with name: p-00008390-h - ::1 - Darwin
INFO:ENGINE: Engine service started on port 8001
INFO:ENGINE: Defold Engine 1.2.179 (5209b50)
INFO:ENGINE: Loading data from: build/default
INFO:ENGINE: Initialised sound device 'default'
DEBUG:SCRIPT: Load level 1
INFO:DLIB: SSDP: Started on address 192.168.88.208
DEBUG:SCRIPT: Load level 2
Process 17211 stopped
* thread #1, name = 'engine_main', queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x1060b8b80)
    frame #0: 0x00007fff6864b9a9 libsystem_platform.dylib`_platform_memmove$VARIANT$Haswell + 169
libsystem_platform.dylib`_platform_memmove$VARIANT$Haswell:
->  0x7fff6864b9a9 <+169>: movq   (%rsi), %rcx
    0x7fff6864b9ac <+172>: movq   (%rsi,%rdx), %r8
    0x7fff6864b9b0 <+176>: movq   %rcx, (%rdi)
    0x7fff6864b9b3 <+179>: movq   %r8, (%rdi,%rdx)
Target 0: (dmengine_headless) stopped.
(lldb) bt
* thread #1, name = 'engine_main', queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x1060b8b80)
  * frame #0: 0x00007fff6864b9a9 libsystem_platform.dylib`_platform_memmove$VARIANT$Haswell + 169
    frame #1: 0x00000001002acea3 dmengine_headless`dmGraphics::NullDrawElements(dmGraphics::Context*, dmGraphics::PrimitiveType, unsigned int, unsigned int, dmGraphics::Type, unsigned long) + 435
    frame #2: 0x000000010010c29f dmengine_headless`dmRender::Draw(dmRender::RenderContext*, dmRender::Predicate*, dmRender::NamedConstantBuffer*) + 1359
    frame #3: 0x000000010010ba14 dmengine_headless`dmRender::DrawRenderList(dmRender::RenderContext*, dmRender::Predicate*, dmRender::NamedConstantBuffer*) + 2516
    frame #4: 0x000000010011089b dmengine_headless`dmRender::ParseCommands(dmRender::RenderContext*, dmRender::Command*, unsigned int) + 731
    frame #5: 0x00000001001152da dmengine_headless`dmRender::UpdateRenderScriptInstance(dmRender::RenderScriptInstance*, float) + 170
    frame #6: 0x0000000100004df4 dmengine_headless`dmEngine::Step(dmEngine::Engine*) + 1108
    frame #7: 0x0000000100005fea dmengine_headless`dmEngineUpdate(dmEngine::Engine*) + 26
    frame #8: 0x000000010000621d dmengine_headless`dmEngine::RunLoop(dmEngine::RunLoopParams const*) + 109
    frame #9: 0x0000000100006182 dmengine_headless`engine_main(int, char**) + 98
    frame #10: 0x0000000100001c14 dmengine_headless`start + 52

```

**Comment by JCash** [comment]
That callstack is very interesting.
is it possible for you to share a repro case with us?

**Comment by Vbif** [comment]
Already shared =) But you cannot reproduce the problem
https://github.com/defold/defold/issues/5560#issuecomment-780449380

I'm still think that this is a hackintosh related problem. I have switched to real mac and this issue dissapear. Maybe just close it =)

**Comment by AGulev** [comment]
can't repo
