### ISSUE TITLE
Android keystore password must be able to handle non alphanumeric characters

### ISSUE THREAD

**Issue by britzl** [defold/defold#5563]
**Describe the bug (REQUIRED)**
The Android bundle process fails if the keystore password contains certain non alphanumeric characters.

**To Reproduce (REQUIRED)**
1. Generate a keystore with a password containing non-alphanumeric characters such as @
2. Bundle

**Expected behavior (REQUIRED)**
The bundle should work even if the keystore password contains non-alphanumeric characters

**Defold version (REQUIRED):**
  - 1.2.179

**Platforms (REQUIRED):**
 - Platforms: Desktop

**Additional context (OPTIONAL):**
https://forum.defold.com/t/running-into-problems-when-trying-to-bundle-mobile-game/67538/5?u=britzl

**Comment by britzl** [comment]
I'm unable to reproduce the error reported by the user.

**Comment by britzl** [comment]
@UltraBurstXD are you using Linux? I think you are based on the console output from the forum thread.

**Comment by UltraBurstXD** [comment]
Yes, I'm using Ubuntu 20.10.

**Comment by britzl** [comment]
@UltraBurstXD I've made a change to how the keystore password is used. The password is no longer loaded by bob and passed on to the Android bundletool. Instead the bundletool loads the password file directly. Would you mind testing this again on your machine? Here's a link to a version of bob.jar with the fix included:

https://d.defold.com/archive/alpha/5ee43a404ff2e7c23ea0dd4fc36615d376aea1e8/bob/bob.jar
