### ISSUE TITLE
Crash when debug

### ISSUE THREAD

**Issue by ufgo** [defold/defold#5565]
ERROR:CRASH: CALL STACK:

 0 0x7FF686B4EA70 snprintf <unknown>:0
 1 0x7FF686B64A20 _snscanf_s <unknown>:0
 2 0x7FF686B929D0 dmHashReverseErase64 <unknown>:0
 3 0x7FF686B929D0 dmHashReverseErase64 <unknown>:0
 4 0x7FF686B929D0 dmHashReverseErase64 <unknown>:0
 5 0x7FF686B64A20 _snscanf_s <unknown>:0
 6 0x7FF686C9A960 LZ4MaxCompressedSize <unknown>:0
 7 0x7FF686B929D0 dmHashReverseErase64 <unknown>:0
 8 0x7FF686C33B50 Particle_Hash <unknown>:0
 9 0x7FF686B929D0 dmHashReverseErase64 <unknown>:0
10 0x7FF686B929D0 dmHashReverseErase64 <unknown>:0
11 0x7FF686B929D0 dmHashReverseErase64 <unknown>:0
12 0x7FF686B929D0 dmHashReverseErase64 <unknown>:0
13 0x7FF686B41120 sprintf <unknown>:0
14 0x7FF686C9A960 LZ4MaxCompressedSize <unknown>:0
15 0x7FFEEA487C10 BaseThreadInitThunk <unknown>:0
16 0x7FFEEBA0D4B0 RtlUserThreadStart <unknown>:0

[_crash.zip](https://github.com/defold/defold/files/5980220/_crash.zip)

**Comment by JCash** [comment]
HI @ufgo !

Unfortunately, that callstack looks broken (e.g. `sprintf` doesn't call our `dmHashReverseErase64` function).

Thatnks for sending the _crash.dmp, however, to use it, we need to know which engine version you used (so we can download it and its pdb from d.defold.com). If you are using custom built engine with native extensions, we need the engine and .pdb that you built, in order to debug using the .dmp file.

**Comment by britzl** [comment]
@ufgo can you provide the additional information we requested?

**Comment by ufgo** [comment]
> @ufgo can you provide the additional information we requested?

I don't know what else I can add. Sometimes this error pops up during debugging

**Comment by ufgo** [comment]
> HI @ufgo !
> 
> Unfortunately, that callstack looks broken (e.g. `sprintf` doesn't call our `dmHashReverseErase64` function).
> 
> Thatnks for sending the _crash.dmp, however, to use it, we need to know which engine version you used (so we can download it and its pdb from d.defold.com). If you are using custom built engine with native extensions, we need the engine and .pdb that you built, in order to debug using the .dmp file.

1.2.179

**Comment by ufgo** [comment]
> @ufgo check the comment from @JCash
> 
> > we need to know which engine version you used
> 
> Thanks, 1.2.179
> 
> > If you are using custom built engine with native extensions
> 
> Are you using any extensions in your project?
> 
> 

Admob, defsave, gpgs, defos, druid, monarch

**Comment by JCash** [comment]
> Admob, defsave, gpgs, defos, druid, monarch

Thanks @ufgo !
Since you're using native extensions, and we build a custom engine for you (on our build server), I'd very much like to get the `dmengine.exe` and the `dmengine.pdb` from your build folder.
If I get them together with the next `_crash.dmp` I should be able to debug this locally.

**Comment by britzl** [comment]
No new info from user. Closing.
