### ISSUE TITLE
Add support for code folding

### ISSUE THREAD

**Issue by RiadOkba** [defold/defold#5570]
**Is your feature request related to a problem? Please describe (REQUIRED):**
I have written a very long scripts and lua modules. I have to go through my code to upgrade it or change it which is tedious and time consuming.

**Describe the solution you'd like (REQUIRED):**
Just like Notepad++ I'd like to have a plus/dash sign next to a function or segment of code (if/while...), where I can show and hide the segment of code

**Describe alternatives you've considered (REQUIRED):**
1- using a search is useful but only when you remember the name of your variable and the data you are looking for... It doesn't help for the clarity too
2- Using Notepad++. Of course... going back and forth between Defold editor and the notepad++ is not worth it

**Additional context (OPTIONAL):**
![5](https://user-images.githubusercontent.com/67765342/108050970-9b47d900-704a-11eb-9202-738c249cb5c0.JPG)
![6](https://user-images.githubusercontent.com/67765342/108050982-9daa3300-704a-11eb-87f1-5b39f586f514.JPG)
![7](https://user-images.githubusercontent.com/67765342/108050987-9f73f680-704a-11eb-80d4-cfe102edad5b.JPG)

**Comment by Trevortni** [comment]
I would like to add my support for code folding. It can really help cut down visual noise and frame the current problem while you're staring at a half complete algorithm trying to figure out what to do next, as well as bringing distant bits of code closer together while you're trying to harmonize them.

**Comment by AGulev** [comment]
closed in favor of newer and planned https://github.com/defold/defold/issues/6207
