### ISSUE TITLE
Linux X86_64 bundles not building.

### ISSUE THREAD

**Issue by dlannan** [defold/defold#5573]
**Describe the bug (REQUIRED)**
When building a bundle with latest Defold editor for Linux X86_64 I get an error.
```Status 404: Failed to download http://d.defold.com/archive/5209b50cf4bf8e925cb4c32fd0bde6c53fc85a66/engine/x86_64-linux/```

**To Reproduce (REQUIRED)**
1. Load in a sample project and build a bundle for Linux X86_64

**Expected behavior (REQUIRED)**
A bundle should be created.

**Defold version (REQUIRED):**
  - Version 1.2.179
  - Editor SHA1: 492c3531153c849388976cfbdc058fc6f66cbd22
  - Engine SHA1: 5209b50cf4bf8e925cb4c32fd0bde6c53fc85a66

**Platforms (REQUIRED):**
 - Platforms: Linux
 - OS: Debian 10
 - Device: Desktop PC

**Comment by britzl** [comment]
@dlannan Could you please try unchecking "Generate debug symbols"? 

The issue should be fixed in this PR: https://github.com/defold/defold/pull/5548 which will be included in 1.2.180. Sorry for the inconvenience.

**Comment by dlannan** [comment]
Awesome. Thanks!
