### ISSUE TITLE
Set some projects subdirs as IGNORED for editor search

### ISSUE THREAD

**Issue by realstudent** [defold/defold#5575]
**Is your feature request related to a problem? Please describe (REQUIRED):**
I consolidate in game project folder not only Defold stuff (folders with collections, scripts, atlases etc) but also all related stuff like Krita folders, reference images, localizations text files etc. This allow to me has one Github entry for each project dont separate documents or art. But problem - editor make search in all folders when we apple some operations, for example - adding new sprite to atlas dialog suggest too much image entries from art output folder or reference folders. But i need only list of entries from project/images .... Yes i always checking what i do ... but mistakes occured (

**Describe the solution you'd like (REQUIRED):**
I wish have control under visiability of folders for Defold editor. For example - add some folders to ignore list (documentation, art references).

**Comment by britzl** [comment]
We should expand this feature and allow the user to define a list of folders that should be ignored:

* In the editor (when searching and perhaps also in the Assets panel)
* By bob and the editor when building
   *  If a folder contains .go files (as in the Go programming language) this will trip up the build process
