### ISSUE TITLE
Script properties are reset to their default values

### ISSUE THREAD

**Issue by astrochili** [defold/defold#5583]
**Describe the bug (REQUIRED)**
Sometimes script properties are reset to their default values. Presumably when using an external code editor.

**To Reproduce (REQUIRED)**
It started when I cleared the Custom Editor field in Preferences, while still editing scripts in VSCode. It's not stable, I don't know how to reproduce it.

**Expected behavior (REQUIRED)**
Script properties are not reset.

**Defold version (REQUIRED):**
  - Version 1.2.175
  - Editor SHA eb31ede76a85f9e7dd669c001f4b5d0aa4e2787a

**Platforms (REQUIRED):**
 - Platforms: macOS
 - OS: Mojave 10.14.6
 - Device: Macbook Air (Mid 2012)

**Additional context (OPTIONAL):**
https://forum.defold.com/t/go-property-resetting-to-default/48551/6
https://forum.defold.com/t/resource-properties-in-1-2-163/63292/36

**Comment by Dragosha** [comment]
similars: 
https://github.com/defold/defold/issues/5237
https://github.com/defold/defold/issues/5205
