### ISSUE TITLE
Crash when debugging with custom shader & render script - 1.2.179

### ISSUE THREAD

**Issue by SkaterDad** [defold/defold#5594]
**Describe the bug (REQUIRED)**
When using Project -> Build, the game crashes.

The project has a custom shader and render script.  Was experimenting with post-processing effects from ShaderToy.  I found this project attached to a forum post about 3D stuff and have been modifying it.

I do not see this crash when debugging my primary game project that only uses built-in shaders and the rendercam render_script.

**To Reproduce (REQUIRED)**
1. Run the game
2. Move the mouse around a lot.
3. Watch it crash randomly.  Sometimes you have to launch the game multiple times before this happens.

**Expected behavior (REQUIRED)**
No crashes, or at least useful error message.

**Defold version (REQUIRED):**

* Defold 1.2.179
* rendercam (local copy)
* defold-gyro 1.1 (not applicable to platform i'm debugging on and seeing crashes)

**Platforms (REQUIRED):**
Windows 10

**Minimal repro case project (OPTIONAL):**

Small example project with all of the build folders and crash dumps.

[mesh2.zip](https://github.com/defold/defold/files/6040613/mesh2.zip)

**Logs (OPTIONAL):**
Please provide relevant logs from engine, editor or build server. Learn where the logs are stored [here](https://defold.com/manuals/getting-help/#log-files).

```
 0 0x7FF7AA46AC60 _snscanf_s <unknown>:0
 1 0x7FF7AA46AC60 _snscanf_s <unknown>:0
 2 0x7FF7AA58A8B0 DecryptXTeaCTR <unknown>:0
 3 0x7FF7AA498C10 dmHashReverseErase64 <unknown>:0
 4 0x7FF7AA498C10 dmHashReverseErase64 <unknown>:0
 5 0x7FF7AA498C10 dmHashReverseErase64 <unknown>:0
 6 0x7FF7AA498C10 dmHashReverseErase64 <unknown>:0
 7 0x7FF7AA4473C0 sprintf <unknown>:0
 8 0x7FF7AA5AEF10 LZ4MaxCompressedSize <unknown>:0
 9 0x7FFC4A297C10 BaseThreadInitThunk <unknown>:0
10 0x7FFC4A3ED700 RtlUserThreadStart <unknown>:0
```

**Comment by JCash** [comment]
>defold-gyro 1.1 (not applicable to platform i'm debugging on and seeing crashes)

Since you are using native extensions, we build a custom engine for you.
It would be helpful if you provide the dmengine.exe and dmengine.pdb (generated when you selec "with debug symbols"), as well as the `_crash.dmp`

**Comment by SkaterDad** [comment]
The crash dump and engine exe are in the zip file.  Not sure about the pdb file my phone won't open the zip.

I will try to repro this without the native extension this evening to simplify the debugging.

**Comment by SkaterDad** [comment]
I removed the native extension and still get the crash.

Here are the dumps and project.

[_crash.zip](https://github.com/defold/defold/files/6046058/_crash.zip)
[project.zip](https://github.com/defold/defold/files/6046062/project.zip)

**Comment by JCash** [comment]
Thanks for the minimal repro!
I couldn't reproduce the crash unfortunately.

The `_crash.dmp` says the exception occurs in ntdll.dll!RtlUserThreadStart
Not sure I've seen that before, And unfortunately, that doesn't give me much more to go on.

Not much I can do until we figure out something new :/

**Comment by SkaterDad** [comment]
Tried in 1.2.182 and it crashed within a few seconds.  Do you think I should try 1.2.183 Beta?

```
ERROR:CRASH: CALL STACK:

 0 0x7FF64629A490 dmRender::Draw D:\a\defold\defold\engine\render\src\render\render.cpp:656
 1 0x7FF64629AC00 dmRender::DrawRenderList D:\a\defold\defold\engine\render\src\render\render.cpp:608
 2 0x7FF6462B1DE0 dmRender::ParseCommands D:\a\defold\defold\engine\render\src\render\render_command.cpp:169
 3 0x7FF6462A4BB0 dmRender::UpdateRenderScriptInstance D:\a\defold\defold\engine\render\src\render\render_script.cpp:2930
 4 0x7FF646112470 dmEngine::Step D:\a\defold\defold\engine\engine\src\engine.cpp:1525
 5 0x7FF6461136A0 dmEngineUpdate D:\a\defold\defold\engine\engine\src\engine.cpp:1953
 6 0x7FF646113740 dmEngine::RunLoop D:\a\defold\defold\engine\engine\src\engine_loop.cpp:69
 7 0x7FF64610C3B0 engine_main D:\a\defold\defold\engine\engine\src\engine_main.cpp:127
 8 0x7FF6464B8734 __scrt_common_main_seh d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
 9 0x7FFF528E7020 BaseThreadInitThunk <unknown>:0
10 0x7FFF53602630 RtlUserThreadStart <unknown>:0
```
[_crash.zip](https://github.com/defold/defold/files/6516143/_crash.zip)

**Comment by britzl** [comment]
Thanks. That's a good looking call stack at least.

Line 656: https://github.com/defold/defold/blob/1.2.182/engine/render/src/render/render.cpp#L656

@JCash any idea?

**Comment by JCash** [comment]
No real idea yet, other than that the arguments might be "old" values or something. But it's perhaps a good insight in how to reproduce the issue.

**Comment by Jhonnyg** [comment]
This issue is a bit too old to do anything about now as these areas have changed significantly. Please open the issue again if it persists.
