### ISSUE TITLE
Download Python 2.7 version of pip

### ISSUE THREAD

**Issue by beldenfox** [defold/defold#5601]
**Describe the bug (REQUIRED)**
As of February 2021 the default version of pip that easy_install pulls down no longer supports Python 2 and throws syntax errors related to f-strings. The setup scripts need to pull down a version of pip that works with Python 2.7.

**To Reproduce (REQUIRED)**
Go through the build setup steps. Failure will occur at this point:
`python2 ./scripts/build.py install_ext`

**Expected behavior (REQUIRED)**
No syntax errors from pip.

**Defold version (REQUIRED):**
  Tested using 1.2.180 but will affect earlier versions.

**Platforms (REQUIRED):**
 Any development platform that only supports Python 2.7 e.g. Macs.

**Workaround (OPTIONAL):**
Edit `build.py` to request the most recent version of pip that supports Python 2.7. Change this:
`run.env_command(self._form_env(), ['python', '-m', 'easy_install', '-q', '-d', join(self.ext, 'lib', 'python'), 'pip'])`
to this:
`run.env_command(self._form_env(), ['python', '-m', 'easy_install', '-q', '-d', join(self.ext, 'lib', 'python'), 'pip==20.3.4'])`

**Comment by subsoap** [comment]
Related https://github.com/defold/defold/issues/5454

**Comment by beldenfox** [comment]
Commit 6d2a58b changed the pip version to 19.3.1. The last version of pip compatible with Python 2.7 is 20.3.4. If the earlier version is sufficient this issue can be closed.
