### ISSUE TITLE
Live Update: load missing resources with resource.store_archive()

### ISSUE THREAD

**Issue by aglitchman** [defold/defold#5602]
Currently, `resource.store_archive()` requires a valid manifest inside provided .zip file and requires restarting the game. It will be great to use it to load missing resources and without restarting the game.

More info: https://forum.defold.com/t/use-live-update-to-improve-load-speed-of-html5-game/67686/2

**Comment by JCash** [comment]
I agree!
I don't think this should be a big change.

**Comment by JCash** [comment]
This task is now obsolete with the new preferred way of using live update.
