### ISSUE TITLE
Live Update: be able to disable creation of temporary files (.arcd/.arci)

### ISSUE THREAD

**Issue by aglitchman** [defold/defold#5603]
It's not always necessary to store loaded resources in the Live Update temporary files. For example, when you run your games on the HTML5 platform, all web browsers already store loaded files in their cache.

More info: https://forum.defold.com/t/use-live-update-to-improve-load-speed-of-html5-game/67686/2

**Comment by JCash** [comment]
The current solution is generic, and works on all platforms.
This sounds like this is something that would only work on HTML5?

Also, I think this issue came about due to the #5602 issue.
If you could use the .zip file directly, you wouldn't have the need for this fix anymore.

**Comment by aglitchman** [comment]
> The current solution is generic, and works on all platforms.
> This sounds like this is something that would only work on HTML5?

Yes, it's a generic solution and it assumes that you use Live Update to upgrade your game in production and/or to cache loaded resources. In my case, I don't want to cache anything, because the game loads its resources from an URL on each launch.


> Also, I think this issue came about due to the #5602 issue.
> If you could use the .zip file directly, you wouldn't have the need for this fix anymore.

Only if the #5602 issue will allow us to switch off resources caching.
