### ISSUE TITLE
[Vulkan] No way out from build-in full screen

### ISSUE THREAD

**Issue by selimanac** [defold/defold#5606]
**Describe the bug (REQUIRED)**
When using Vulkan, there is no way out from build-in(from `game.project`) full screen option. There were same problem before for GL but it was fixed and it is possible to use ESC to quit. But it is not working when using Vulkan so we have to hard reset.

**To Reproduce (REQUIRED)**
1. Set Vulkan extension 
2. Set display.fullscreen = 1
3. Build

**Defold version (REQUIRED):**
  - 1.2.180

**Platforms (REQUIRED):**
 - Platforms: macOS
 - OS: 10.15.7

**Comment by Jhonnyg** [comment]
Fixed.
