### ISSUE TITLE
Add bundle ios in windows.

### ISSUE THREAD

**Issue by d954mas** [defold/defold#5619]
Bob can build ios in windows.

But no such menu in editor.

https://forum.defold.com/t/vote-on-your-favourite-issues-for-2021/66978/10

**Comment by d954mas** [comment]
Not sure, that it is realy worked on windows) 
https://forum.defold.com/t/bob-build-ios-on-windows/67709

**Comment by AGulev** [comment]
related https://github.com/defold/defold/issues/3735

**Comment by AGulev** [comment]
related https://github.com/defold/defold/issues/3331

**Comment by AGulev** [comment]
closed as duplicate of https://github.com/defold/defold/issues/3331 (better explained there)
