### ISSUE TITLE
Color picker on Linux is opening behind Editor and causes it to freeze and loose the focus

### ISSUE THREAD

**Issue by nebspacefarer** [defold/defold#5620]
**Describe the bug**
On Linux Debian the editor (1.2.179) color picker takes the focus when opened but appears behind the editor window and therefore freezes the editor completely.
Clicking multiple times on the Editor after that can causes a desktop environment crash and before that, doesn't allow to focus the editor anymore.

**To Reproduce**
1. Open a project on Defold on Linux Debian
2. Select a node with a color property (such as a GUI Box)
3. Open the color picker via "Custom color..." context menu option.

**Expected behavior**
The color picker should open on top of the editor to avoid it to be frozen in the process.

**Defold version:**
  - Version 1.2.179, Channel editor-alpha

**Platforms:**
 - Platforms: Linux
 - OS: Debian Bullseye 11
 - Desktop Environment: Cinnamon

**Minimal repro case project:**
Easily reproducible with any project and a node with a Color property.

**Logs:**
Only error displaying when opening the color picker is this:
`(java:4169): Gdk-WARNING **: 22:00:10.990: XSetErrorHandler() called with a GDK error trap pushed. Don't do that`
However I suspect it is unrelated.

**Workaround:**
Unfocus the Editor either by Alt+Tab or by clicking on another window and focusing the Editor window shows the color picker on top and allows to unfreeze the Editor and uses the color picker without issue.
The typical definitive fix should be to make the color picker open on top of the Editor as it seems to only be a focus issue.

**Comment by britzl** [comment]
Fixed in JavaFX update 18-ea+6
