### ISSUE TITLE
Diff highlights entire file as modified

### ISSUE THREAD

**Issue by JustAPotota** [defold/defold#5626]
**Describe the bug (REQUIRED)**
The diff view highlights the entire file as modified, instead of only the modified lines. Additions and removals work as expected.

**To Reproduce (REQUIRED)**
Look at the diff of a file with modified lines.

**Expected behavior (REQUIRED)**
Only the lines that have been modified should be highlighted.

**Defold version (REQUIRED):**
1.2.179

**Platforms (REQUIRED):**
Only tested on Linux

**Screenshots (OPTIONAL):**
1.2.179:
![2021-03-06_19-00](https://user-images.githubusercontent.com/43710172/110225894-9d7eb400-7ee1-11eb-9c9c-5ec07d60c8e6.png)
1.2.177 (how it _should_ look):
![2021-03-06_19-01](https://user-images.githubusercontent.com/43710172/110225901-a96a7600-7ee1-11eb-8936-561070d0655c.png)

**Additional context (OPTIONAL):**
This issue popped up in 1.2.178 and is probably related to the styling changes made in that version.

**Comment by JCash** [comment]
Could it it be whitespace changes in the file? E.g. "\n" versus "\r\n" ? (Unix vs Windows)

**Comment by JustAPotota** [comment]
I checked in a hex editor and the whitespaces are the same. Also, 1.2.180 has the same issue.

**Comment by JustAPotota** [comment]
No clue when this was fixed, but I just noticed it's working in the latest 1.2.192 alpha:
![2022-02-13_13-34](https://user-images.githubusercontent.com/43710172/153771618-80d1be27-f38f-46bf-9a14-3da4dc7e83a0.png)
