### ISSUE TITLE
Add a Use AndroidX checkbox in the Android section of game.project

### ISSUE THREAD

**Issue by britzl** [defold/defold#5629]
**Is your feature request related to a problem? Please describe (REQUIRED):**
Enabling AndroidX for a project currently requires an app manifest. It would be a lot simpler if this was an option in game.project instead.

**Describe the solution you'd like (REQUIRED):**
Add an option to "Use AndroidX" in the Android section of game.project

**Describe alternatives you've considered (REQUIRED):**
You can still use an app manifest

**Comment by AGulev** [comment]
maybe it's possible/easier to have similar ui for app manifestator tool as we have for LiveUpdateSettings?

**Comment by britzl** [comment]
We have decided to make AndroidX the default value instead. You can switch back to support lib through application manifest.
