### ISSUE TITLE
Update d.defold.com template with defold.com css

### ISSUE THREAD

**Issue by JCash** [defold/defold#5635]
* The current formatting of d.defold.com is very hard to read and find your way.
* We also want editor links
* I also want to quickly find bob.jar (I use this page a _lot_)

**Comment by JCash** [comment]
<img width="1249" alt="Screenshot 2021-03-11 at 12 52 20" src="https://user-images.githubusercontent.com/1349334/110785175-eb414680-826a-11eb-916e-c120c9eaaf60.png">
<img width="608" alt="Screenshot 2021-03-11 at 12 52 10" src="https://user-images.githubusercontent.com/1349334/110785184-eed4cd80-826a-11eb-8f84-a77be6491877.png">

Previous look:
https://d.defold.com/stable/

**Comment by subsoap** [comment]
Adding small SVG icons next to the labels for the OS may look nicer.

**Comment by JCash** [comment]
Probably.
Unfortunately I have no time left for this.
I'll let someone else help out with the next improvements.
