### ISSUE TITLE
Add a detection for WebGL to the HTML5 template 

### ISSUE THREAD

**Issue by subsoap** [defold/defold#5637]
Currently if WebGL is not supported the player has no guidance in the default template.  Instead the engine_template.html should include some JS to detect if WebGL is supported and show text explaining that WebGL is not supported, they need to use a browser which supports WebGL.

https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/By_example/Detect_WebGL

https://stackoverflow.com/questions/54401577/check-if-webgl2-is-supported-and-enabled-in-clients-browser

**Comment by britzl** [comment]
We actually already do some of this but should surface it better to the user:

https://github.com/defold/defold/blob/dev/com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/bundle/resources/jsweb/dmloader.js#L674-L707
