### ISSUE TITLE
Basis Universal: BPTC (BC7) for WebGL

### ISSUE THREAD

**Issue by aglitchman** [defold/defold#5639]
**Is your feature request related to a problem? Please describe (REQUIRED):**
RGBA encoded into BC3 hasn't the best quality. Luckily, Chrome and Firefox support BPTC (BC7) -
- https://bugs.chromium.org/p/chromium/issues/detail?id=1013369
- https://developer.mozilla.org/en-US/docs/Web/API/EXT_texture_compression_bptc

**Describe the solution you'd like (REQUIRED):**
Defold can check the [`EXT_texture_compression_bptc`](https://www.khronos.org/registry/webgl/extensions/EXT_texture_compression_bptc/) extension and use it in HTML5 builds.

**Comment by aglitchman** [comment]
I'm not sure but I think that the fix is simple, i.e. just add `EXT_texture_compression_bptc` to this **if** - https://github.com/defold/defold/blob/cacd5fe112c5b19fe25ab2727f18222e25bdec01/engine/graphics/src/opengl/graphics_opengl.cpp#L955

**Comment by aglitchman** [comment]
Take a look at the demo project:
* Sources - https://github.com/aglitchman/defold-basis-quality-test
* Web build - https://aglitchman.github.io/defold-basis-quality-test/index.html

BC3:
![image](https://user-images.githubusercontent.com/193258/110997395-63545d00-838e-11eb-8349-d95eb6e1685b.png)

**Comment by AGulev** [comment]
wow it seems like BC3 unusable for 2d at all (
maybe it makes sense to use RGBA instead?

**Comment by aglitchman** [comment]
For some images, BC3 does its job well. I wish that we could be able to control how the Basis decoder selects a target texture format.

**Comment by JCash** [comment]
>  I wish that we could be able to control how the Basis decoder selects a target texture format.

My initial hope was that separate control shouldn't be necessary?
If the list of formats to try is properly sorted, we shouldn't have to rearrange the list?

For instance in this [list](https://github.com/defold/defold/blob/dev/engine/graphics/src/graphics.cpp#L254-L260), we choose
```cpp
        if (IsFormatRGBA(format))
        {
            TEST_AND_RETURN(dmGraphics::TEXTURE_FORMAT_RGBA_BC7);
            TEST_AND_RETURN(dmGraphics::TEXTURE_FORMAT_RGBA_BC3);
            TEST_AND_RETURN(dmGraphics::TEXTURE_FORMAT_RGBA_ASTC_4x4);
            TEST_AND_RETURN(dmGraphics::TEXTURE_FORMAT_RGBA_ETC2);
            TEST_AND_RETURN(dmGraphics::TEXTURE_FORMAT_RGBA_PVRTC_4BPPV1);
            TEST_AND_RETURN(format);
            return dmGraphics::TEXTURE_FORMAT_RGBA;
        }
```

The first problem here is that the BC7 wasn't found.
The second problem is that is tests BC3 before the other formats. And they might be better (e.g. Astc, ETC2)

Also, I played around with the idea that if the format was explicitly set by the developer, we should try that first:

```cpp
        if (IsFormatRGBA(format))
        {
            if (format != dmGraphics::TEXTURE_FORMAT_RGBA) {
                TEST_AND_RETURN(format);
            }
                
            ... the others ...
            return dmGraphics::TEXTURE_FORMAT_RGBA;
        }
```

That way we should be able to control it from the texture profile, and still fallback on the other formats if the developer set it as RGBA.

What do yo think?

**Comment by aglitchman** [comment]
> The first problem here is that the BC7 wasn't found.
> The second problem is that is tests BC3 before the other formats. And they might be better (e.g. Astc, ETC2)

In fact, the quality of BC3 is very low for any 2D images. It has three color channels (565) with 8 bits of alpha. I think that it should be removed [from the list](https://github.com/defold/defold/blob/dev/engine/graphics/src/graphics.cpp#L254-L260).

At the same time, BC3 suits well for the non-opaque 3D models - leaves, plants. Personally, I don't plan to use it in my games, but who knows!

**Comment by AGulev** [comment]
yeah, we have many complaints in chat about it. I agree that it would be better turn off BC3 (for now at least, before better solution of control it)

**Comment by JCash** [comment]
The PR adds support for BC7 on WebGL, and I've also removed support for BC3 as a fallback for the RGBA transcoding.
