### ISSUE TITLE
Create buffer resources at runtime

### ISSUE THREAD

**Issue by dapetcu21** [defold/defold#5648]
**Is your feature request related to a problem? Please describe (REQUIRED):**
I have the following use-case: I want to create, at runtime, an arbitrary number of mesh components each with their own different mesh buffer. As it is right now, I can't (not sanely at least, see workaround), since buffer resources can only be declared at design time, so they are of a fixed number.

**Describe the solution you'd like (REQUIRED):**
Two functions:
`resource.create_buffer(buffer)`: Given a buffer, creates a buffer resource and returns a hash handle to it that can be plugged into game object and component properties. The newly created resource will have a reference count of 1 and can be `release()`-d after being attached to a property.
`resource.release(resource_hash)` Decrements the reference count of a resource.

**Describe alternatives you've considered (REQUIRED):**
Using a script to generate 100 `.json` files, a really long dummy script filled with `go.property()` declarations and a really long `.go` file to make the associations. This way I could make a pool of empty buffer resources.

**Additional context (OPTIONAL):**
Not really relevant, but we're trying to do a sort of 3D tilemap and putting together the pieces inside a single buffer to render the mesh in one go seems like the thing to do.

![xNDUrGM](https://user-images.githubusercontent.com/428060/111009428-46268b00-839c-11eb-82ef-22ff30879d5c.png)
![AQwKfxb](https://user-images.githubusercontent.com/428060/111009430-4888e500-839c-11eb-850e-be47ad16bca6.png)

**Comment by aglitchman** [comment]
+1 💯 
Would love to have this feature!

Because I have to create a lot of empty meshes with unique empty buffers to be able to create a chunked world:
![image](https://user-images.githubusercontent.com/193258/111031874-c5f33a80-841a-11eb-84df-4e8e7b19b9df.png)

**Comment by d954mas** [comment]
+1
![2021-12-16_12-35-38](https://user-images.githubusercontent.com/2655263/146346151-913b3b34-3281-4882-8aac-293e168ea799.png)

**Comment by Jhonnyg** [comment]
Started working on this, it will most likely be released in 1.4.2 👍
