### ISSUE TITLE
Error with `<queries>` when build extension

### ISSUE THREAD

**Issue by AGulev** [defold/defold#5652]
**Describe the bug (REQUIRED)**
When I try to build [this](https://github.com/defold/extension-admob/tree/new-admob) extension, I get the following error:
```
Line 24: unexpected element <queries> found in <manifest>.
```

It appears because old version of gradle doesn't know about new `<queries>` manifest element and can't merge it. 
https://stackoverflow.com/questions/62969917/how-to-fix-unexpected-element-queries-found-in-manifest-error

**To Reproduce (REQUIRED)**
Build extension

**Expected behavior (REQUIRED)**
[This](https://github.com/defold/extension-admob/tree/new-admob) plugin should build just fine.

**Defold version (REQUIRED):**
  - Version [e.g. 1.2.180]

**Platforms (REQUIRED):**
 - Platforms: Build for Android
 - OS: MacOs

**Minimal repro case project (OPTIONAL):**
[project](https://github.com/defold/extension-admob/tree/new-admob)

**Comment by filosov** [comment]
@AGulev Do you try building with the latest extender version? When I make changes for dx->d8 migration I also check building extension with Admob 7.4.0+ version (where <queries> first time appear). Everything was fine.

**Comment by AGulev** [comment]
yes I do
https://github.com/defold/extension-admob/blob/b8f95aa673c798121f2887bb4caf324da2e61977/admob/manifests/android/build.gradle#L3

**Comment by AGulev** [comment]
Ah, sorry, extendER (I read it as extension)
It works with `https://build-stage.defold.com` Thank you! Looking forward to release!
