### ISSUE TITLE
1.2.179 Bundle Android application fails

### ISSUE THREAD

**Issue by ghpxi** [defold/defold#5661]
Cannot bundle Android application
The error is `Status 404: Failed to download http://d.defold.com/archive/5209b50cf4bf8e925cb4c32fd0bde6c53fc85a66/engine/arm64-android/`

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Project -> Bundle -> Android Application'
2. Click on 'Create Bundle'
3. See build errors

**Defold version:**
  - Version 1.2.179

**Platforms:**
 - Platforms: Linux
 - OS: Arch Linux

**Comment by britzl** [comment]
This has been fixed in 1.2.180. Try to uncheck the "Generate debug symbols" checkbox in the Bundle dialog.

**Comment by ghpxi** [comment]
thank you a lot, it works fine.
