### ISSUE TITLE
[Vulkan] VK_ERROR_INITIALIZATION_FAILED

### ISSUE THREAD

**Issue by selimanac** [defold/defold#5674]
**Describe the bug (REQUIRED)**
Probably my fault somewhere on fragment shader but it is not possible to understand from this error message.

```cpp
[mvk-error] VK_ERROR_INITIALIZATION_FAILED: Render pipeline compile failed (Error code 1):
Link failed: fragment input user(locn1) was not found in vertex shader outputs.
ERROR:GRAPHICS: Vulkan Error (../src/vulkan/graphics_vulkan.cpp:1336) VK_ERROR_INITIALIZATION_FAILED
Assertion failed: (0), function GetOrCreatePipeline, file ../src/vulkan/graphics_vulkan.cpp, line 1336.
```

**Defold version (REQUIRED):**

![Screen Shot 2021-03-21 at 20 57 37](https://user-images.githubusercontent.com/1324635/111915607-31c34c00-8a88-11eb-8a3e-0907faf4b2b5.png)

**Platforms (REQUIRED):**
 - Platforms: macOS
 - OS: 10.15.7 

**Logs (OPTIONAL):**
[_crash -vulkan.zip](https://github.com/defold/defold/files/6178029/_crash.-vulkan.zip)

**Comment by selimanac** [comment]
Happens because I forgot to remove `varying highp vec4 var_position;`  from fragment shaders. It is not available on vertex shaders.  It would be nice to have a friendly error message.

**Comment by britzl** [comment]
Yeah, I agree about the error message. Is there something to be done to improve this @Jhonnyg ?

**Comment by selimanac** [comment]
We had a small conversation before about Vulkan error messages. I believe this is a generic problem(not only for this error) related to Vulkan which @Jhonnyg  be aware of.
