### ISSUE TITLE
Add a checkbox to not open the resulting folder when finished bundling

### ISSUE THREAD

**Issue by subsoap** [defold/defold#5684]
Sometimes we need to rebundle from the editor over and over and it's annoying to have the same folder open constantly. A checkbox to open the resulting folder when bundling would be nice.

Adding an option to play a sound / show a toast in the editor settings when bundling finishes would also be useful.

**Comment by britzl** [comment]
> Sometimes we need to rebundle from the editor over and over and it's annoying to have the same folder open constantly. A checkbox to open the resulting folder when bundling would be nice.

Oh yes, I totally agree. It annoys me as well :-)
