### ISSUE TITLE
Add option to open a project from within the editor

### ISSUE THREAD

**Issue by ternence-li** [defold/defold#5689]
hi guys,
The Editor must quit  to open another project?
thank you.

**Comment by britzl** [comment]
Related: https://github.com/defold/defold/issues/5653

**Comment by ternenceltc** [comment]
I find some info at here :  https://gamefromscratch.com/defold-engine-tutorial-series-getting-started/

**Comment by britzl** [comment]
MVP: Make sure it is possible to launch multiple editors from application icon

Next: Launch another Welcome Screen from within the editor and the same JVM

**Comment by vlaaad** [comment]
The editor update with the feature should be available shortly.
