### ISSUE TITLE
User types as shader constant

### ISSUE THREAD

**Issue by ghpxi** [defold/defold#5697]
**Is your feature request related to a problem? Please describe (REQUIRED):**
Currently, it's hard to pass a matrix to the shader. The workaround is to pass it using 4 vectors and combine them in the shader. It's not intuitive, and I wondered why I could not pass my own matrix when this code already has the ability to pass matrix for projection/view — the same with float. When I need to pass a single float, the only option is to pass it via vector4.

**Describe the solution you'd like (REQUIRED):**
The current User type can be named Vector4 and you can add more types like this for matrices and numbers. The solution can be introduced without breaking compatibility with previous versions.

**Comment by Jhonnyg** [comment]
Fixed via #6878 - note, we have only added support for matrix4's in this PR and not for all types, if it's absolutely necessary and someone requests it again we could look into it again, but having mat4s with array support should be able to solve these types of issues anyway.
