### ISSUE TITLE
Local require() overriding detection

### ISSUE THREAD

**Issue by astrochili** [defold/defold#5703]
**Describe the bug (REQUIRED)**
[TypeScriptToLua](https://github.com/TypeScriptToLua/TypeScriptToLua/blob/849f630d8199edc8b5742c98f9756b7d60aa66f9/src/transpilation/bundle.ts#L18) overrides `require()` function locally to read modules in the local var `___modules`. The problem is that Defold doesn't recognise this overriding and output the errors when I try to build a project. When I renamed `require()` to `require_()` everything works fine.

**To Reproduce (REQUIRED)**
Include [this file](https://github.com/astrochili/defold-require-overriding-repo-case/blob/master/modules/lldebugger.lua) to the game project and try to build.

**Expected behavior (REQUIRED)**
Defold and bob detect local `require()` correctly and don't stop building with the lua file generated by TypeScriptToLua.

**Defold version (REQUIRED):**
  - Version 1.2.179

**Platforms (REQUIRED):**
 - Platforms: macOS
 - OS: Mojave
 - Device: Macbook Air 2012

**Minimal repro case project (OPTIONAL):**
https://github.com/astrochili/defold-require-overriding-repo-case

**Logs (OPTIONAL):**
![Screenshot 2021-03-30 at 19 28 46](https://user-images.githubusercontent.com/4752473/113023499-5c9b5780-918e-11eb-97f1-46f44d6b0a2d.png)

**Workaround (OPTIONAL):**
Rename `require()` to `require_()` manually everytime after converting by TypeScriptToLua.

**Additional context (OPTIONAL):**
It's important because I found the way to debug Defold projects in VSCode by [Local Lua Debugger](https://github.com/tomblind/local-lua-debugger-vscode) and want to share the instruction on the forum. But I can't do it right now because it requires manual renaming in the sources generated by TypeScriptToLua.

**Comment by astrochili** [comment]
May be we need for the ignore list in the project settings? Where we can place paths to ignore by the detector?

**Comment by britzl** [comment]
> May be we need for the ignore list in the project settings?

We actually do have plans to add a project file/folder ignore list as a new feature of the editor and build tools. It might actually be added in the next release depending on the progress of a few other tasks.

**Comment by britzl** [comment]
And we have discussed that we should not treat missing require() files as errors and simply warn about them instead.

**Comment by astrochili** [comment]
> And we have discussed that we should not treat missing require() files as errors and simply warn about them instead.
> 
> 
> 
> Covered here: https://github.com/defold/defold/issues/5649

That would be great! 🙏

**Comment by britzl** [comment]
> And we have discussed that we should not treat missing require() files as errors and simply warn about them instead.

We've backed away from this as a missing file should be treated as an error and not just a warning. We will however add a whitelist of the standard Lua libraries so that you can do:

```
local string = require "string"
local socket = require "socket"
```

PR: https://github.com/defold/defold/pull/5861

**Comment by astrochili** [comment]
No longer relevant after https://github.com/astrochili/defold-vscode-guide/commit/eabade6015beb0b85fb54a41c3b3088597ea5f13, can be closed.
