### ISSUE TITLE
Android AAR custom assets are missing in APK

### ISSUE THREAD

**Issue by alexeyfeskov** [defold/defold#5710]
**Describe the bug (REQUIRED)**
Custom assets inside AAR added to build.gradle, are missing in APK

**To Reproduce (REQUIRED)**
1. Download and install [Defold Editor 1.2.181-beta](http://d.defold.com/beta/), set build server to https://build-stage.defold.com
2. Create project from "Native Extension" template
3. Add `/myextension/manifests/android/build.gradle`
```
repositories {
  mavenCentral()
}

dependencies {
  implementation 'androidx.annotation:annotation:1.0.0'
  implementation 'com.facebook.android:audience-network-sdk:6.3.0'
}
```
4. Add native_extension.appmanifest and enable jetifier
5. Bundle and unpack APK
6. Observe `assets/audience_network.dex` is missing in APK (but present in [source AAR](https://repo1.maven.org/maven2/com/facebook/android/audience-network-sdk/6.3.0/) com.facebook.android:audience-network-sdk:6.3.0)
![screenshot-missing-asset](https://github.com/alexeyfeskov/defold-maxsdk/blob/reproduce-missing-asset/example/screenshot-missing-asset.png?raw=true)

**Expected behavior (REQUIRED)**
All assets from AAR are including in APK

**Defold version (REQUIRED):**
Version 1.2.181-beta SHA1: `008648932d9429a1385dabdfd34b435a15eb2a20`

**Platforms (REQUIRED):**
 - Platforms: Android only

**Minimal repro case project (OPTIONAL):**
[reproduce-missing-asset.zip](https://github.com/defold/defold/files/6250051/reproduce-missing-asset.zip) or [same code on github](https://github.com/alexeyfeskov/defold-maxsdk/tree/bug-aab-assets)

**Workaround (OPTIONAL):**
Manually add custom assets to [native extension resources](https://defold.com/manuals/extensions/#project-layout).
In my case - copy `audience-network-sdk-6.3.0.aar/assets/audience_network.dex` to `myextension/res/android/assets/audience_network.dex`.

**Additional context (OPTIONAL):**
Without this file I've got
```
Can't load Audience Network Dex. Please, check that audience_network.dex is inside of assets folder.
java.io.FileNotFoundException: audience_network.dex
```
while trying to initialize Facebook Ads.

**Comment by 546342** [comment]
Hello.
Sorry for posting in the old thread. I have the same problem with AppsFlyer SDK. But I’m not sure if this is really wrong behaviour.

I have these dependencies in my build.gradle file:

```
implementation 'com.appsflyer:af-android-sdk:6.2.3'
implementation 'com.android.installreferrer:installreferrer:2.2'
```

The AppsFlyer doc says that result apk must contain two important files: `a-` and `b-` (in path `com/appsflyer/internal`). But after building game with bob they are not.

Source files are located in this path: `af-android-sdk-6.2.3.aar/classes.jar/com/appsflyer/internal/a-` and `af-android-sdk-6.2.3.aar/classes.jar/com/appsflyer/internal/b-`.

Current workaround is to put files in `res` extension directory. But maybe it should work automatically?
Thanks

**Comment by britzl** [comment]
> The AppsFlyer doc says that result apk must contain two important files: `a-` and `b-` (in path `com/appsflyer/internal`). But after building game with bob they are not.

How do you know they are not part of the final dex file? Have you run `dexdump` to verify that they are not there?

If they are indeed not included I think what you need to do is to specify these extra packages (com.appsflyer.internal) in your ext.manifest file, like we do for the Facebook extension:

https://github.com/defold/extension-facebook/blob/master/facebook/ext.manifest#L6

**Comment by britzl** [comment]
BTW, @546342 do you have an AppsFlyer extension in a public repo?

**Comment by 546342** [comment]
Björn, thanks for the replies.

>How do you know they are not part of the final dex file? Have you run dexdump to verify that they are not there?

I checked it in android studio. They are not there. 
Anyway AF docs say they should be physical files:  

>If you are using Android SDK V5 and above, make sure that in the APK file, in addition to the classes.dex and resources files, you also have folder com > appsflyer > internal with files a- and b- inside.  

> If they are indeed not included I think what you need to do is to specify these extra packages (com.appsflyer.internal) in your ext.manifest file, like we do for the Facebook extension:

Unfortunately adding com.appsflyer.internal in manifest does not help.

> do you have an AppsFlyer extension in a public repo?

Yes, there is fork of Alexey's repository with my small changes:
https://github.com/546342/DefAppsFlyer

**Comment by britzl** [comment]
Ah, I see. Ok, so we need to modify or Android bundler to ensure these files are also included. I'll take a look next week.

**Comment by britzl** [comment]
> I'll take a look next week.

I've been struggling to understand how the Android Gradle Plugin (which we only use to resolve gradle dependencies) handles classes.jar archives containing other things than *.class files.

The Android Gradle plugin source is here: https://android.googlesource.com/platform/tools/build/+/refs/heads/master/gradle/src/main/groovy/com/android/build/gradle

**Comment by britzl** [comment]
The AppsFlyer setup instructions:

"If you are using Android SDK V5 and above, make sure that in the APK file, in addition to the classes.dex and resources files, you also have folder com > appsflyer > internal with files a- and b- inside. 
Note: Before SDK 5.3.0, file names are a. and b.

Check that you have the required files by opening your APK in Android Studio. See the following screenshot for reference.

If those files are missing, the SDK can't make network requests to our server, and you need to contact your CSM or support. "

https://support.appsflyer.com/hc/en-us/articles/207032126-Android-SDK-integration-for-developers#integration-missing-resource-files

But how do they get included? Is it done by the Android Gradle Plugin?

**Comment by britzl** [comment]
Posted question to the AppsFlyer Android SDK on GH: https://github.com/AppsFlyerSDK/appsflyer-android-sdk/issues/25

**Comment by britzl** [comment]
@546342 I'm still struggling to understand how the files are copied. We're not able to make any progress until we know. If you do know how AndroidStudio includes the files when bundling then please add info here!

**Comment by britzl** [comment]
No additional information has been provided. Closing.
