### ISSUE TITLE
Throws Error: "Fclojure.lang.ExceptionInfo: Failed to connect to debugger on localhost:8172" despite firewall access enabled

### ISSUE THREAD

**Issue by rohanharikr** [defold/defold#5718]
### Steps to reproduce
1. Debug menu - Start/Attach
2. Error is thrown

<hr/>

<table>
<tr><td>Build time</td><td>2021-04-03T16:12:25.921062</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>c89efe0dcac970ec71f153f0d4ed0c89fee55059</td></tr>
<tr><td>Defold engine sha</td><td>f34b08dc12af1101ae62c6e880b6373a03206174</td></tr>
<tr><td>Defold version</td><td>1.2.180</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"971019527bf5400bacbe5edee69956a6"'>971019527bf5400bacbe5edee69956a6</a></td></tr>
<tr><td>GPU</td><td>Intel(R) Iris(TM) Graphics 550</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-16.0.49</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.16</td></tr>
<table>

**Comment by britzl** [comment]
```
editor.debugging.mobdebug$connect_BANG_$fn__43073.invoke.class clojure.lang.ExceptionInfo: Failed to connect to debugger on localhost:8172
    at editor.debugging.mobdebug$connect_BANG_$fn.invoke(mobdebug.clj:339)
    at clojure.lang.AFn.run(AFn.java:22)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.lang.Thread.run(Thread.java:834)
```

**Comment by britzl** [comment]
Does this happen for all projects? All the time? What if you try Debug->Start/Attach while the game is running?

**Comment by rohanharikr** [comment]
**Does this happen for all projects? All the time?** 
Yes, this seems to be the case. Tried with three different projects.
```
INFO:DLIB: Log server started on port 64312
WARNING:DLIB: No IP found for local hostname Rahuls-MacBook-Pro.local. Fallbacks to localhost
INFO:ENGINE: Target listening with name: Rahuls-MacBook-Pro.local - ::1 - Darwin
INFO:ENGINE: Engine service started on port 64326
INFO:ENGINE: Defold Engine 1.2.180 (f34b08d)
INFO:ENGINE: Loading data from: build/default
INFO:ENGINE: Initialised sound device 'default'
DEBUG:SCRIPT: Listening for debugger on 0.0.0.0
```

**What if you try Debug->Start/Attach while the game is running?**
This works fine. On building game:
```
INFO:DLIB: Log server started on port 64336
WARNING:DLIB: No IP found for local hostname Rahuls-MacBook-Pro.local. Fallbacks to localhost
INFO:ENGINE: Target listening with name: Rahuls-MacBook-Pro.local - ::1 - Darwin
INFO:ENGINE: Engine service started on port 64337
INFO:ENGINE: Defold Engine 1.2.180 (f34b08d)
INFO:ENGINE: Loading data from: build/default
INFO:ENGINE: Initialised sound device 'default'
INFO:DLIB: SSDP: Started on address 10.0.0.7
```
After attaching debugger:
```
...
DEBUG:SCRIPT: Listening for debugger on 0.0.0.0
DEBUG:SCRIPT: Debugger connected from 127.0.0.1
```

**Comment by britzl** [comment]
Ok, so connecting the debugger after the game has started works. Interesting.

**Comment by dri-richard** [comment]
I'm also hitting this. If I try to attach to a running, bundled Android APK or Windows EXE , I get the "failed to connect to debugger message". I have to use the Android version as a development app, or create and run a new Windows build, for it to succeed. This is with 1.2.184.
