### ISSUE TITLE
gltf Loader in editor

### ISSUE THREAD

**Issue by dlannan** [defold/defold#5719]
A 3D resource loader using the gltf model format. 
Load in meshes, images (textures), shaders (if in gltf or pbr for default) and possibly scene features like Cameras, Lights and meta data. 

I have built a simple gltf only loader (no glb support and limited gltf features) here for reference:
https://github.com/dlannan/defold-tools

Other ideas I have tested are using tinygltf (works well and may be easier to integrate in the editor):
https://github.com/syoyo/tinygltf

Why glTF:
- A large amount of support for new and modern art pipelines. 
- Has material systems supporting complex material types (like pbr)
- Has extension systems for embedding custom shaders
- Is a very well supported 3D format for Web delivery (threejs and babylon etc)
- Has support for mesh compression like draco. 
- Is (imho) an easier format to integrate into applications - almost as easy as obj :)

**Comment by JCash** [comment]
Since we now have gltf support in Defold, I think we'll close this and let users add feature requests for any missing features one by one, to make sure we focus on the most needed features first.
