### ISSUE TITLE
Suggestion: allow dynamic transforms by default

### ISSUE THREAD

**Issue by Reubend** [defold/defold#5728]
**Is your feature request related to a problem? Please describe (REQUIRED):**
I was frustrated debugging a physics issue with an object which changes size dynamically. Eventually, I realized that its collision object wasn't scaling with it. After 30 minutes of Googling this issue, I realized that Defold already has the ability to handle this properly, but it's disabled by default. While I don't fully understand the performance impact of this, I think that it makes much more sense to enable this by default, because I can see from past threads on the forums that many other people are having this same issue.

**Describe the solution you'd like (REQUIRED):**
I think that unless the performance impact is large, the default setting for "Allow Dynamic Transforms" should be enabled. 

**Describe alternatives you've considered (REQUIRED):**
I considered using a kinematic object instead of a dynamic one, but I want my object to be affected by gravity, and to bounce of other objects. But I still want to scale it. I can use a workaround of deleting and recreating the collision object, but this keeps my code much more clean. 

This is of course, just my suggestion. And if the performance impact is too high, then it no longer makes sense. The documentation says quite clearly that you can't control the position/rotation/scale of a dynamic object, but what makes it confusing it that you *can* control the scale of an object, but its collision object won't change by default, and there's no warning/error. So a lot of people get confused when they see the physics of the object, and have to spend time debugging.

**Comment by JCash** [comment]
I do like the idea.
At the time I added the feature, I chose not to however, in order to respect old games that _might_ start to behave differently from when they first launched.

However, I think I've changed my mind and by considering it a "bug fix", it makes sense to update this to "true" by default.

**Comment by britzl** [comment]
> However, I think I've changed my mind and by considering it a "bug fix", it makes sense to update this to "true" by default.

Added this to the 2021 roadmap and tagged it as a "good first issue". Let's see if anyone picks it up!

**Comment by subsoap** [comment]
https://github.com/defold/defold/search?q=allow_dynamic_transforms

Looks as simple as setting to 0s to 1s in two of these files? Then change text saying default is true.

Unless you mean forcing it always enabled?

**Comment by Reubend** [comment]
Just made this PR to change it :)
https://github.com/defold/defold/pull/5743
