### ISSUE TITLE
bob --settings  way to add dependecies instead of replace it

### ISSUE THREAD

**Issue by d954mas** [defold/defold#5733]
**Is your feature request related to a problem? Please describe (REQUIRED):**
1)I am using bob to make builds for different web platforms(poki, itch io,game distribution,yandex games).
2)Every target can use it own sdk.
3)I make settings files to every target.
4)But i need to copy-paste dependecies in every file. I can't add new dependency in settings file. I can only replace dependencies string.

**Describe the solution you'd like (REQUIRED):**
A way to add new dependency.
May be something like
[project]
`__add dependencies = ,https://github.com/GameDistribution/gd-defold/archive/main.zip`

**Describe alternatives you've considered (REQUIRED):**
For now i copy-paste dependencies from game.project to settings file

**Additional context (OPTIONAL):**

**Comment by britzl** [comment]
We're adding suport for multi line dependencies. This will make it easier to add additional game.project settings.

https://github.com/defold/defold/issues/3841

**Comment by d954mas** [comment]
Awesome. Thanks👍
