### ISSUE TITLE
RenderDoc support

### ISSUE THREAD

**Issue by aglitchman** [defold/defold#5746]
**Describe the bug (REQUIRED)**
I can't debug [my block-building engine](https://twitter.com/aglitchman/status/1307402753745055746?s=20) on the latest Defold 1.2.181 to find a source of weird OpenGL issues and/or to test new dmBuffer's content version behaviour.

Defold 1.2.181 creates the OpenGL 3.1 context. [RenderDoc only supports the core profile of OpenGL - from 3.2 up to 4.6 inclusive. ](https://renderdoc.org/docs/behind_scenes/opengl_support.html#:~:text=RenderDoc%20only%20supports%20the%20core,will%20generally%20not%20be%20supported.)

The argument `--renderdoc` does nothing.

**Expected behavior (REQUIRED)**
I should be able to capture frames (screenshot is from Defold 1.2.180):
![image](https://user-images.githubusercontent.com/193258/114855203-5d6af500-9dee-11eb-85d8-409e903ce2b7.png)

**Defold version (REQUIRED):**
 - Version 1.2.181

**Platforms (REQUIRED):**
 - Platforms: Windows
 - OS: Windows 10

**Comment by JCash** [comment]
Hmm. good point.
We need a better way to detect which OpenGL version to choose.
E.g. choose the highest possible version (and core profile), (e.g. like the one you have) and then fallback to something lower.

The "--renderdoc" flag is for our Vulkan backend, to enable the validation layers.

**Comment by aglitchman** [comment]
I tested Defold 1.2.182 BETA, and RenderDoc supports it:
![image](https://user-images.githubusercontent.com/193258/115283582-3a28a880-a154-11eb-82ca-4538be584e49.png)


The issue can be closed. Thanks!
