### ISSUE TITLE
Buffer handle could equal zero

### ISSUE THREAD

**Issue by aglitchman** [defold/defold#5748]
**Describe the bug (REQUIRED)**
I caught a rare case when the handle of the new buffer equals zero. 

**To Reproduce (REQUIRED)**
Create/destroy a lot of buffers (more than 65535, i.e. 16 bit) to increase the global version counter and to eventually get the buffer handle = 0.

**Expected behavior (REQUIRED)**
You should be able to use the created buffer. But you can't, because its handle is zero and you can't even destroy it.

**Defold version (REQUIRED):**
 - Version 1.2.181

**Platforms (REQUIRED):**
 - Platforms: any

**Minimal repro case project (OPTIONAL):**
https://github.com/aglitchman/defold-buffer-version-test

Run the project. You should get two errors before the app would have crashed:
```
ERROR:EXT: Handle of the buffer is ZERO!
FATAL:EXT: Can't get stream 'position': result 3, buffer handle 0.
```

The error is printed by this line: https://github.com/aglitchman/defold-buffer-version-test/blob/main/ext/src/ext.cpp#L38

**Screenshots (OPTIONAL):**
![image](https://user-images.githubusercontent.com/193258/114880982-4090ea80-9e0b-11eb-914e-99d58e38b8ea.png)

**Comment by aglitchman** [comment]
The error is present on Defold 1.2.182 BETA :innocent:

**Comment by JCash** [comment]
Yeah, I'm looking at it now :)
