### ISSUE TITLE
Editor keeps freezing

### ISSUE THREAD

**Issue by agentsnufflebuns** [defold/defold#5755]
**Describe the bug (REQUIRED)**
The editor freezes whenever i try to open and atlas file or change any properties within the atlas file including animation groups, FPS etc. Editor is also freezing when opening collection files. scripts also take a while to load but much faster then the others

**To Reproduce (REQUIRED)**
Steps to reproduce the behaviour:
 1.Click on atlas file
 2. editor not responding
 3. 50 seconds later
 4. opens atlas
 5.change anything and the editor starts not responding

**Expected behaviour (REQUIRED)**
I do not expect the editor to be this slow on a
[Desktop game.zip](https://github.com/defold/defold/files/6330429/Desktop.game.zip)
 gaming PC with all requirements met.

**Defold version (REQUIRED):**
  - I download through steam I believe it is the latest version  

**Platforms (REQUIRED):**
Windows 10

**Additional context (OPTIONAL):**
I have attached my game, pretty early stages so it should be to big

**Comment by britzl** [comment]
Could you please include a log file from the editor as well?

https://defold.com/manuals/editor/#editor-logs

**Comment by britzl** [comment]
Fixed by #5898
