### ISSUE TITLE
When delete sampler with texture the texture stays in collection

### ISSUE THREAD

**Issue by ufgo** [defold/defold#5760]
When delete sampler with texture the texture statys in collection.

1. Create material
2. Add sampler "lut" (or any other name)
3. Add lut16.png (or any) texture to test
4. Build
5. Delete lut16.png 
6. Delete sampler "lut" 
7. Build and see error "/main/main.collection you must specify a texture"

Defold version: 1.2.181

Platforms:
Windows10
![java_IgiTa2mM5k](https://user-images.githubusercontent.com/21050233/115384271-aa890580-a1f8-11eb-8c15-2c00116b8a02.png)
![notepad++_efGexF8EhW](https://user-images.githubusercontent.com/21050233/115384274-ab219c00-a1f8-11eb-8a1c-a28836da95af.png)
![java_vaMXSd3q2g](https://user-images.githubusercontent.com/21050233/115384279-abba3280-a1f8-11eb-8c3a-385b381c7f14.png)
![java_6J0RI9bnLl](https://user-images.githubusercontent.com/21050233/115384280-ac52c900-a1f8-11eb-8951-e0d976a1d0ea.png)

**Comment by britzl** [comment]
> 5\. Delete lut16.png

This is when you delete lut16.png from within the editor right?

**Comment by ufgo** [comment]
> > 5. Delete lut16.png
> 
> This is when you delete lut16.png from within the editor right?

Yes

**Comment by AGulev** [comment]
Should be fixed by https://github.com/defold/defold/pull/8186
