### ISSUE TITLE
Project with models doesn't build for HTML5 from IDE

### ISSUE THREAD

**Issue by aglitchman** [defold/defold#5765]
**Describe the bug (REQUIRED)**
I can't build a project with models for HTML5 from IDE. `bob.jar` builds it successfully.

**To Reproduce (REQUIRED)**
1. Create a new project from the "basic 3D" project template.
2. Click "Project" - "Build HTML5"
3. Get error in the log: `No proto message class mapping for .rigscenec`

![image](https://user-images.githubusercontent.com/193258/115853469-e0fd9500-a431-11eb-9a89-762148a31306.png)

**Defold version (REQUIRED):**
  - Version 1.2.182 **BETA**

![image](https://user-images.githubusercontent.com/193258/115853606-08ecf880-a432-11eb-8461-315f4a39c07e.png)

**Platforms (REQUIRED):**
 - Platforms: HTML5
 - OS: Windows 10 (host)

**Comment by JCash** [comment]
Fixed in latest beta
