### ISSUE TITLE
Crash when launching in fullscreen

### ISSUE THREAD

**Issue by greay** [defold/defold#5781]
**Describe the bug (REQUIRED)**
Simple test game crashes when launching in fullscreen

**To Reproduce (REQUIRED)**
1. Build & run the project (CMD-B)
2. Crash

**Expected behavior (REQUIRED)**
It should not crash

**Defold version (REQUIRED):**
  - Version 1.2.181

**Platforms (REQUIRED):**
 - Platforms: macOS
 - OS: macOS 11.2.3

**Minimal repro case project (OPTIONAL):**
[Fullscreen crash.zip](https://github.com/defold/defold/files/6383150/Fullscreen.crash.zip)

**Logs (OPTIONAL):**
Please provide relevant logs from engine, editor or build server. Learn where the logs are stored [here](https://defold.com/manuals/getting-help/#log-files).

[dmengine_2021-04-27-013956_dantalion.crash.zip](https://github.com/defold/defold/files/6383157/dmengine_2021-04-27-013956_dantalion.crash.zip)

**Workaround (OPTIONAL):**
Don't use fullscreen :'(

**Additional notes:**
Starting by attaching the debugger does not help.

**Comment by britzl** [comment]
Thank you for the bug report!

> Don't use fullscreen :'(

A workaround is to use DefOS and toggle fullscreen that way instead:

https://github.com/subsoap/defos

```
function init(self)
    defos.set_fullscreen(true)
end
```

**Comment by AGulev** [comment]
works fine in Defold 1.7.0
