### ISSUE TITLE
gui.animate doesn't set value if duration = 0 and delay > 0

### ISSUE THREAD

**Issue by aglitchman** [defold/defold#5791]
**Describe the bug (REQUIRED)**
`gui.animate` doesn't set target value if duration = 0 and delay > 0.

**To Reproduce (REQUIRED)**
I attached a re-pro project.

**Expected behavior (REQUIRED)**
`gui.animate` should behave as `go.animate`.

**Defold version (REQUIRED):**
  - Version 1.2.181/1.2.182

**Platforms (REQUIRED):**
 - Platforms: Any

[gui_animate_bug1.zip](https://github.com/defold/defold/files/6420576/gui_animate_bug1.zip)

**Comment by JCash** [comment]
Tbh, I think we should discuss if this is a bug or not.
Does it work if delay == 0 ?

The requested behavior is already available when using a `timer`callback.

**Comment by aglitchman** [comment]
Could you please run the example project? It contains two identical animations but they are implemented via `go.animate` and `gui.animate`. You'll see the difference. `go.animate` runs it as it should be. I believe that `gui.animate` should do the same.

**Comment by britzl** [comment]
I think I fixed something similar a while ago... hmm, no, related but not the same:

https://github.com/defold/defold/issues/5198

It is kind of a weird situation with running animations with a 0 duration, but it should be handled I think. I would categorise this as a bug.
