### ISSUE TITLE
Editor Locking up when moving assets in the main window. 

### ISSUE THREAD

**Issue by jaykyburz** [defold/defold#5806]
**Describe the bug (REQUIRED)**
When manipulating a sprite in the editor, the entire desktop becomes unresponsive and slow requiring reboot of system. 

**To Reproduce (REQUIRED)**
Add something like a sprire to the main.collection in an empty scene. 

**Expected behavior (REQUIRED)**
For it not to lock up the system.

**Defold version (REQUIRED):**
1.1.181

**Platforms (REQUIRED):**
Operating System: Kubuntu 19.10
KDE Plasma Version: 5.16.5
KDE Frameworks Version: 5.62.0
Qt Version: 5.12.4
Kernel Version: 5.3.0-64-generic
OS Type: 64-bit
Processors: 16 × AMD Ryzen 7 2700 Eight-Core Processor
Memory: 15.6 GiB of RAM

**Comment by britzl** [comment]
Does this happen all the time?

**Comment by jaykyburz** [comment]
Happened twice before I gave up trying. I'm completely new to Defold so really have no idea how to start debugging the problem or providing more information.

**Comment by britzl** [comment]
My guess is that it is driver related. One thing you could try is to force the editor to use software rendering (not optimal but might be a good test):

https://defold.com/manuals/linux/#q-my-opengl-drivers-are-outdated-can-i-still-use-defold

There may also be clues in the editor log: https://defold.com/manuals/editor/#editor-logs

**Comment by britzl** [comment]
No new info from user. Closing.
