### ISSUE TITLE
Monarch animated transition > Graphical glitch when showing more than 1 screen at the same time

### ISSUE THREAD

**Issue by Ragetto** [defold/defold#5808]
**Describe the bug (REQUIRED)**
Graphical glitch when having 2 screens "shown" from the loader, one of them having a fade-in transition.
=> several bugs, actually (depending on the modifications that are made/tested), please check the link right below:

Everything is detailed here (description, screenshots, videos etc.)
https://forum.defold.com/t/monarch-animated-transition-graphical-glitch/68383/2

NOTE : part of the issue seems to be fixed with the dev-flicker branches (https://github.com/britzl/monarch/tree/dev-flicker), but a new popup transition issue occurs (also mentioned in the link above).

**To Reproduce (REQUIRED)**
1. Build
2. Watch

**Expected behavior (REQUIRED)**
Ideal solution:
1/ The initial glitch no longer exists (meaning that everything is working as intended)

Acceptable solution:
2/ The glitch still exists... but it's possible to have a workaround consisting in creating a "parallel" transition for the background (without generating new glitches, cf the popup) => cf Britzl's solution

**Defold version (REQUIRED):**
1.2.181

**Platforms (REQUIRED):**
 - OS: Windows 10 (editor)

**Minimal repro case project (OPTIONAL):**
Here is a link to a public repository (the project should be clean enough since this is just a test project):
https://github.com/Ragetto/20210509_defold_monarch_transition_issue
_A few useless / temporary / commented stuff there and there, but nothing important, the project is almost empty.

**Comment by britzl** [comment]
Should be reported in github.com/britzl/monarch
