### ISSUE TITLE
Make bob merge generated files from collections

### ISSUE THREAD

**Issue by JCash** [defold/defold#5809]
Bob doesn't merge the generated files based on content hash, which results in a very high file count.

https://forum.defold.com/t/error-messages-not-showing-on-some-configurations/68387?u=mathias_westerdahl

An example project had ~40000 unique files, whereas the editor produced ~300 files.

**Comment by AGulev** [comment]
it's important to take into account this case with atlases https://github.com/defold/defold/issues/4218
because even if atlases are identical we still wanna have them as separate files because we can change buffers.

**Comment by AGulev** [comment]
it's valid for all resources can be changed in runtime (meshes, something else?)
