### ISSUE TITLE
In editor some GUI node sorting isn't possible with alt+down

### ISSUE THREAD

**Issue by subsoap** [defold/defold#5811]
Alt+down on Windows maybe happens on other OS as well.

![2021-05-10 15_18_46-move nodes - Defold Editor 2 0](https://user-images.githubusercontent.com/409170/117731474-0b29b380-b1a3-11eb-9f7d-64e3aca2fee5.png)

[cannot_sort_nodes.zip](https://github.com/defold/defold/files/6455273/cannot_sort_nodes.zip)

Select sorta_works_1 with your cursor and then press Alt+Down Arrow Key and it does not sort down as expected.

![2021-05-10 14_59_22-About](https://user-images.githubusercontent.com/409170/117731567-344a4400-b1a3-11eb-89eb-ec3445e5c9fd.png)

**Comment by vlaaad** [comment]
It's interesting that Alt+Up works..

**Comment by AGulev** [comment]
Alt+down works as well in 50% of cases )

**Comment by vlaaad** [comment]
Should be fixed, check for updates :)
