### ISSUE TITLE
JVM crash when running project on new linux machine

### ISSUE THREAD

**Issue by otsakir** [defold/defold#5819]
**Describe the bug (REQUIRED)**
When i try to run a built project, either through the editor or from console,  there is a JVM crash. I'm experiencing this issue on my new linux laptop. On the old one, things work fine. So, there is probably something wrong with the setup  there.

**To Reproduce (REQUIRED)**
1. Start the editor. 
2. Create a new project from a tutorial. Both side-scroller and walking astronaut crash.
3. Press F5 to build and run the app. 
4. The app window is shown and it crushes.

**Expected behavior (REQUIRED)**
No crush.

**Defold version (REQUIRED):**
1.2.182

**Platforms (REQUIRED):**
 - Platforms: Linux
 - Ubuntu 21.0.4
 - Device: Lenovo ideapad gaming

**Minimal repro case project (OPTIONAL):**
Any project that renders stuff fails. Notably, an empty project (that does not render anything) doesn't crush. 

**Logs (OPTIONAL):**
[hs_err_truncated.log](https://github.com/defold/defold/files/6501141/hs_err_truncated.log)

**Additional context (OPTIONAL):**
Smells like incompatibility between jvm graphics implementation and OGL drivers to me. I'd be tempted to use a later jvm version if i could build the engine against it.

##### OpenGL info
```
nando@cheetah:~/bin/Defold$ glxinfo | grep Open
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GTX 1650/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 460.73.01
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6.0 NVIDIA 460.73.01
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 460.73.01
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:
```

**Comment by britzl** [comment]
I believe this is the same issue: https://github.com/defold/defold/issues/5599

Suggested solution (or rather workaround): https://defold.com/manuals/linux/#q-the-defold-editor-crashes-when-opening-a-collection-or-game-object-and-the-crash-refers-to-libffiso

**Comment by britzl** [comment]
Additional discussions here: https://github.com/defold/defold/issues/5342

**Comment by otsakir** [comment]
Hmm, maybe. 

As we speak, i just completed defold dev setup on the new machine and built the engine from scratch. I also built a game from the console  using the new engine bundle. It doesn't crush :-/

Note, i used  jdk  `OpenJDK Runtime Environment 18.9 (build 11+28)` and  not  `JRE version: OpenJDK Runtime Environment (11.0.1+13) (build 11.0.1+13)` which is bundled with the defold editor.

I'll try to check with older jdks and see if it has anything to do with the jvm.

**Comment by otsakir** [comment]
Yup, it's is solved by running with older libffi. I installed `libffi7` package and ran with 

`export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libffi.so.7  && ./Defold`

So, what's the verdict. Any ideas why did  it work with the custom defold build ? Maybe it was kind-of linked against the libffi  already present in the system (i.e. 8) ?

**Comment by britzl** [comment]
> So, what's the verdict? Any ideas why it work with the custom defold build ? Maybe it was kind-of linked against the libffi already present in the system (i.e. 8) ?

I wish I knew. I'd really like to engage a Linux and Java expert to get some help solving this and similar issues (like the MESA_GL_OVERRIDE thing). From a Defold Foundation standpoint we'd probably be able to fund this kind of work as a separate small development project.

**Comment by otsakir** [comment]
ok

The issue is solved but we could keep it open for a week or two in case something comes up.
