### ISSUE TITLE
Color picker doesn't return focus to IDE

### ISSUE THREAD

**Issue by aglitchman** [defold/defold#5823]
**Describe the bug (REQUIRED)**
(this bug was described before in the old issues tracker - https://github.com/defold/editor2-issues/issues/2915)

![](https://user-images.githubusercontent.com/13905665/74661065-4dcf2c80-51a8-11ea-9a11-ca4df02b2fb1.gif)

**Expected behavior (REQUIRED)**
Color picker shouldn't switch focus to another random app.

**Defold version (REQUIRED):**
  - Version: All

**Platforms (REQUIRED):**
 - Platforms: Windows

**Comment by britzl** [comment]
Could be related: https://github.com/defold/defold/issues/5620

**Comment by alcorrius** [comment]
seems like JavaFX bug [JDK-8260024](https://bugs.openjdk.java.net/browse/JDK-8260024)

**Comment by britzl** [comment]
Fixed with recent JavaFX update to 18-ea+6
