### ISSUE TITLE
Reversed Sounds

### ISSUE THREAD

**Issue by ZaTimou** [defold/defold#5829]
There really isn't a problem, it's more like I'd think it would be more convenient. The feature I'd like to see (it's really more of an addition) is a wider range to the speed parameter under a sound (say, -1). That way, we wouldn't have to take that specific sound to some sound editor and make a reversed version for every sound we wanted to reverse. This would save space, especially if you're an indie developer with a low-end PC.

Of course, this is just in my opinion. It's completely up to you guys to do something about it.

**Comment by britzl** [comment]
Thank you for the feature request. We'll review it next time we plan work on the sound system!

**Comment by britzl** [comment]
Closing in favour of the sound cursor feature: https://github.com/defold/defold/issues/3293
