### ISSUE TITLE
steam defold bug

### ISSUE THREAD

**Issue by txj-mssl** [defold/defold#5841]
Caton, it's stuck
a newer version of defold is available
It seems that there is no one to maintain it. It hasn't been updated for a long time

**Comment by britzl** [comment]
> a newer version of defold is available

Is the existing editor version that you install from Steam not detecting the update and applying it?

> It hasn't been updated for a long time

There is no point in updating the Steam version each release as long as the version that is there automatically updates. There is only ever a need to update the Steam version if the Defold editor launcher is updated, but this happens VERY rarely.

**Comment by subsoap** [comment]
Check that your firewall is not blocking Steam.

**Comment by txj-mssl** [comment]
yes

**Comment by subsoap** [comment]
Are you sure firewall is not blocking Defold? Most of the time this has come up it was the issue.

What OS are you on?

**Comment by subsoap** [comment]
Also what is the quality of your net connection? 

Try downloading an older version of the editor from http://d.defold.com/stable/ and see if it is able to auto-update to latest for you or if it does not.

**Comment by britzl** [comment]
Old and no questions were answered. Closing.
