### ISSUE TITLE
Image property of TileSource is impossible to modify

### ISSUE THREAD

**Issue by princecorwinofamber** [defold/defold#5855]
### Expected behaviour

Image property would be modified

### Actual behaviour

A popup dialog with the message "java.lang.NoClassDefFoundError: Could not initialize class com.dynamo.bob.TexcLibrary" appears

### Steps to reproduce

1) Create an empty project
2) Move a PNG file to the project directory
3) Click main -> New -> TileSource
4) Change "Image" property to the PNG file

<hr/>

<table>
<tr><td>Build time</td><td>2021-06-03T14:12:54.730938</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>d6f017f3deaee89c27612e047a30bd862d3fbb7a</td></tr>
<tr><td>Defold engine sha</td><td>f77b7f655a0ba68462f6c33604bed7000018735f</td></tr>
<tr><td>Defold version</td><td>1.2.183</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"e1bd3c5f4f2a46db914e39a8c818734f"'>e1bd3c5f4f2a46db914e39a8c818734f</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 1050 Ti/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 NVIDIA 384.130</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>4.10.0-38-generic</td></tr>
<table>

**Comment by britzl** [comment]
I believe this is the same issue: https://github.com/defold/defold/issues/5025

**Comment by britzl** [comment]
This issue may be resolved by using the correct libffi version:

https://defold.com/manuals/linux/#q-the-defold-editor-crashes-when-opening-a-collection-or-game-object-and-the-crash-refers-to-libffiso

**Comment by princecorwinofamber** [comment]
I have tried to modify the archive packages/defold-d6f017f3deaee89c27612e047a30bd862d3fbb7a.jar : I have relocated file /lib/libtexc_shared.so into /linux-x86-64/libtexc_shared.so (these two paths are inside of the jar archive, not in the file system).

Now, the error Defold Editor outputs is java.lang.UnsatisfiedLinkError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /tmp/jna--215580457/jna16491792569343627835.tmp).

I have GLIBC 2.23. Is it possible to run Defold Editor with it?

**Comment by JCash** [comment]
We build using Ubuntu 18.04, which gives you an idea of which glibc is supported/required.

What OS/version are you running?

I'm not sure what's the best way to support a newer GLIBC version on your machine, but perhaps installing a newer GCC might help. I'm not sure if that will cause other issues though.

**Comment by princecorwinofamber** [comment]
I have ubuntu 16.04.1 (actually I have linux mint), but it always gets identified as ubuntu 16.04.1.
I have tried to download an older version of Defold Editor (from here https://d.defold.com/stable/), but unfortunately all versions except the last two have broken links (for example, this one https://d.defold.com/archive/editor-alpha/5295afb3878441fb12f497df8831148525dcfb10/editor-alpha/editor2/Defold-x86_64-linux.zip ).

**Comment by princecorwinofamber** [comment]
Actually, I have read on the Defold Forum that 32bit versions of the editor have existed some time ago, but I was not able to find any download links for them

**Comment by britzl** [comment]
> Actually, I have read on the Defold Forum that 32bit versions of the editor have existed some time ago, but I was not able to find any download links for them

No, those version have been deprecated for quite some time and will not work with the Defold build servers etc (which you need if you are building a project with native extensions)
