### ISSUE TITLE
Getting a certficate exception when trying to build android apk

### ISSUE THREAD

**Issue by ahamed730** [defold/defold#5860]
### Actual behaviour
recieving error-
java.security.PrivilegedActionException: Unknown
javax.net.ssl.SSLHandshakeException: No subject alternative DNS name matching github-releases.githubusercontent.com found.
java.security.cert.CertificateException: No subject alternative DNS name matching github-releases.githubusercontent.com found.
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2021-06-03T14:13:12.122778</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>d6f017f3deaee89c27612e047a30bd862d3fbb7a</td></tr>
<tr><td>Defold engine sha</td><td>f77b7f655a0ba68462f6c33604bed7000018735f</td></tr>
<tr><td>Defold version</td><td>1.2.183</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"428e55b20aca4e57ab90b3deaa30c120"'>428e55b20aca4e57ab90b3deaa30c120</a></td></tr>
<tr><td>GPU</td><td>Intel(R) UHD Graphics 620</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 - Build 23.20.16.4973</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
Are you still experiencing the same problem? There was a massive DNS service outage yesterday affecting websites such as GitHub.

**Comment by britzl** [comment]
No reply from user. Closing.
