### ISSUE TITLE
HTML5: Make the Defold banner coloured in the browser's console.

### ISSUE THREAD

**Issue by aglitchman** [defold/defold#5867]
**Is your feature request related to a problem? Please describe (REQUIRED):**
Defold outputs this line and only in the debug builds:
```
INFO:ENGINE: Defold Engine 1.2.180 (f34b08d)
```

**Describe the solution you'd like (REQUIRED):**
I would like to see this line in the release builds, because it acts as a banner for curious developers. For example, look at that tweet where a developer opened a browser's console and found that a game uses Defold: https://twitter.com/OneFlagStudio/status/1364571256427843584?s=20

Also, I would like to see the link to **defold.com** at the end of this line because a browser makes it clickable. And get rid of "INFO:ENGINE:", and the unnecessary line "Running".

**Additional context (OPTIONAL):**
Look at those HTML5 game engines ads:
* https://pixijs.io/examples/#/demos-basic/container.js
* https://phaser.io/examples/v3/view/actions/grid-align

![image](https://user-images.githubusercontent.com/193258/121669647-34e13d80-cab5-11eb-9f69-4f22e4c9a3e1.png)
![image](https://user-images.githubusercontent.com/193258/121669662-37439780-cab5-11eb-922e-deb5bd15b9cf.png)
![image](https://user-images.githubusercontent.com/193258/121669190-bd131300-cab4-11eb-823c-5985c9ccc7c5.png)

**Comment by britzl** [comment]
Good suggestion!

PixiJS: https://github.com/pixijs/pixijs/blob/dev/packages/utils/src/browser/hello.ts

**Comment by JCash** [comment]
The "INFO:" part comes from our logging system, we won't change that. Those lines are also not present at all in a release build.

Simply printing our a special header on HTML5 builds is of course very doable, so I vote for that route.

**Comment by subsoap** [comment]
I feel people should be able opt out of it in the game.project

``` 
console.log("%c %c %c Made with Defold | Learn more at Defold.com %c %c %c", "background: #db1b02", "background: #f72105", "color: #fff; background: #ff361c;", "background: #f72105", "background: #db1b02", "background: #ffffff")
```

**Comment by subsoap** [comment]
![Uploading 2021-06-12 16_46_37-Window.png…]()

**Comment by aglitchman** [comment]
It looks great! Thanks!
