### ISSUE TITLE
Build on a variety of Linux distributions

### ISSUE THREAD

**Issue by bkmgit** [defold/defold#5868]
**Is your feature request related to a problem? Please describe (REQUIRED):**
Current linux install instructions are only for Ubuntu/Debian. 

**Describe the solution you'd like (REQUIRED):**
It would be good to have a linux build system that supports a variety of distributions and does not hard code a dependency on clang for Ubuntu

**Describe alternatives you've considered (REQUIRED):**
Update the build system. [Godot](https://docs.godotengine.org/en/latest/development/compiling/compiling_for_linuxbsd.html) builds on a variety of linux distrbutions, so it should be possible to implement something that can be easily maintained.

**Comment by britzl** [comment]
Do you have any experience of your own building on different Linux variants? What are some pitfalls to look out for?

**Comment by britzl** [comment]
Currently out of scope for us. If someone from the community would like to help out with this then please reopen!
