### ISSUE TITLE
Add native function json.encode(table) as a counterpart to json.decode(str)

### ISSUE THREAD

**Issue by Grify** [defold/defold#5879]
**Is your feature request related to a problem? Please describe (REQUIRED):**
I would like a way to encode lua tables to JSON in the same way that defold already supports decoding them with json.decode()

**Describe the solution you'd like (REQUIRED):**
Implementation to Defold of a native `json.encode(table) --> str` function that converts lua tables to stringified JSON, in the reverse of how `json.decode(str)` already works

**Describe alternatives you've considered (REQUIRED):**
A manual implementation, and native extension seem like overkill for this feature when the decode counterpart already exists

**Comment by britzl** [comment]
How do we encode userdata?

**Comment by britzl** [comment]
Extension or engine core?

**Comment by Grify** [comment]
> Extension or engine core?

I'm not sure if I'm allowed to comment on this process of filter, but if I am I'm just gonna say that it makes sense to add it to the json library?

**Comment by Sublustris** [comment]
> 
> 
> How do we encode userdata?

i think it will be ok  to simply show an exception. And let devs to convert unsupported types in strings by they own.

**Comment by JCash** [comment]
Another question that is relevant, is if the json.decode+encode should live in its own extension.
I believe far from everyone needs a json module, and this feels like a good thing to have as an extension.

**Comment by britzl** [comment]
> Another question that is relevant, is if the json.decode+encode should live in its own extension.
> I believe far from everyone needs a json module, and this feels like a good thing to have as an extension.

True, but I think it is a common enough usecase to perhaps warrant it's existence in the engine core.

Not everyone needs to make http requests either, but we keep that in the engine because it's is a common enough usecase.

**Comment by JCash** [comment]
>Not everyone needs to make http requests either, but we keep that in the engine because it's is a common enough usecase.

Well, that can be questioned as well.
I think each of those functionalities should have the option to be nulled out.

**Comment by britzl** [comment]
> I think each of those functionalities should have the option to be nulled out.

Yes, I like this!

> If we were to add http requests today, it would most certainly be inside an extension (e.g. the websocket extension)

Oh, I don't know. Maybe. But having an option to replace it with a null implementation is a good middle ground I think!

**Comment by britzl** [comment]
One thing to consider is how to encode an empty table. Should it result in an empty list `[]` or an empty `{}`? Could be an option to json.encode() or we leave it to the user to handle manually.

**Comment by Grify** [comment]
> 

I would say an empty JSON Object ( " {} " ) makes most sense because the intent of the user is explicitly to encode to JSON. That or maybe an exception, as encoding an empty table to JSON probably isn't the intended functionality of any such implementation.
