### ISSUE TITLE
Add Google Stadia for Defold

### ISSUE THREAD

**Issue by Prismisho** [defold/defold#5880]

**Comment by britzl** [comment]
It is not very likely that we will focus on Google Stadia without direct developer need, and I don't believe we will be approved as a tools developer without very strong reason.

Are you an approved Google stadia developer with a game that you want to release? If so, please reach out to your stadia representative and request Defold support for Stadia.

**Comment by AGulev** [comment]
https://blog.google/products/stadia/message-on-stadia-streaming-strategy/
