### ISSUE TITLE
Update copyright dates

### ISSUE THREAD

**Issue by subsoap** [defold/defold#5883]
https://github.com/defold/defold/blob/1ae302ec33d4514408c04ad3ae5d3c1efe2057bd/editor/bundle-resources/Info.plist

https://github.com/defold/defold/blob/1ae302ec33d4514408c04ad3ae5d3c1efe2057bd/editor/resources/about.fxml

These say 

2009-2020

They should say

2009-2021

**Comment by britzl** [comment]
Thank you for noticing!

**Comment by subsoap** [comment]
Seems the initial splash still has the old date.

**Comment by britzl** [comment]
> Seems the initial splash still has the old date.

Ah. Fixed: https://github.com/defold/defold/commit/db55f3faa6347a66d60715dddd9663687d54ceed
