### ISSUE TITLE
Functions for using screen positions in GUI component gui.set_screen_pos()

### ISSUE THREAD

**Issue by AGulev** [defold/defold#5886]
**Is your feature request related to a problem? Please describe (REQUIRED):**
For manipulations between game world and gui or between different gui components the engine should have API to convert cordinates using some universal cordinates system. 
At the moment we use screen coordinates as such universal coordinates we may use for conversion. 

**Describe the solution you'd like (REQUIRED):**
The engine has functions to get screen cordinates, but there are no functions in gui to use them.
I think the engine should have :
`gui.set_screen_pos()`
and
`local pos = gui.convert_screen_pos_to_node_pos(node, screen_pos)` (it's hard to find clear and short name here, pls suggest your variants).

**Describe alternatives you've considered (REQUIRED):**
I implemented these functions in the native extension, but I think it should be part of the gui.* API.
https://github.com/AGulev/set_screen_position

**Comment by AGulev** [comment]
https://github.com/defold/defold/blob/b240830f87dca44c5af242afa531cb7a50160908/engine/gui/src/gui.cpp#L4254-L4312

**Comment by Sublustris** [comment]
Very useful feature. Sometime it is very frustrated when you need to synchronize positions of nodes in several GUIs

**Comment by AGulev** [comment]
Design: https://docs.google.com/document/d/1kQZi7BOKdWcNsnkA1_hzkjLUPmhl64wvLANuEE6tzU8/edit#heading=h.umz08cc31mce
