### ISSUE TITLE
gui.is_enabled() parameter to check if some nodes in hierarchy disabled.

### ISSUE THREAD

**Issue by AGulev** [defold/defold#5887]
**Is your feature request related to a problem? Please describe (REQUIRED):**
When we do `gui.pick_node()`on button we need to check if this button enabled using `gui.is_enabled()`.

In complicated GUI it's possible that some parent node is off, in this case we have to check whole hierarhy of nodes in loop which is not so efficient. It's a pretty frequent case and it would be nice if it will be covered out of the box.

**Describe the solution you'd like (REQUIRED):**
Although a node with disabled parent behaves the same way as disabled node, I'm still not sure we can change `gui.is_enabled()` behaviour without back compatability.

I think it should be a separate argument for  `gui.is_enabled()` function, like this:

`local is_enabled = gui.is_enabled(node)` - check if the node itself disabled, as it's now

`local is_enabled = gui.is_enabled(node, true)` - check if node itself or any parent node is disabled.

**Describe alternatives you've considered (REQUIRED):**
Iterate all the parents in Lua:
https://github.com/Insality/druid/blob/63a6af3faa643d13119c5f35085b601c4543d4e0/druid/helper.lua#L160

**Comment by AGulev** [comment]
https://github.com/defold/defold/blob/b240830f87dca44c5af242afa531cb7a50160908/engine/gui/src/gui.cpp#L1485-L1496


https://github.com/defold/defold/blob/b240830f87dca44c5af242afa531cb7a50160908/engine/gui/src/gui.cpp#L4143-L4147

**Comment by AGulev** [comment]
@britzl here is a small draft how it looks like https://github.com/defold/defold/pull/5892

Before we thought about implementation of this functionality as part of pick_node function (don't pick node if it's disabled) but it feels wrong. Picking of the node just a function that check and return node we have in some point, it shouldn't take functionality for checking if node is enabled or not.
At the same time we have `is_enabled()` function that does it. So, for me it looks logical to have `recursive` option here. 
As result if we wanna check the value for the node itself we call `gui.is_enabled(node)` - it returns the value from the structure and `gui.is_enabled(node, true)` - if node logicly active on the screen.

What do you think?

**Comment by britzl** [comment]
> What do you think?

I like the idea and it will probably be quite useful under certain circumstances
