### ISSUE TITLE
Notebook cpu high temperature

### ISSUE THREAD

**Issue by SalavatR** [defold/defold#5893]
If if build defold project tepmerature changes from 65C to 90-95 C
If i run 3-4 projects on unity at the same time, i don't have any problems

OS Windows 10
HP OMEN i7-9750H, NVIDIA 1660TI

**Comment by britzl** [comment]
Are you only talking about the CPU usage when building a project? Or also when working on a project in the editor or when the editor is idle? Or when running a Defold game?

**Comment by SalavatR** [comment]
usually when running game, but sometimes working just in editor too

**Comment by SalavatR** [comment]
Moved to linux, in editor everythink works fine, but when i run game temperature becomes high

**Comment by britzl** [comment]
Well, the game renders at 60fps and depending on the content and what you do each frame it might actually be quite taxing for your CPU. You can use the Defold profiler to get some insights into where the engine spends most of its time.

**Comment by britzl** [comment]
We have spent a significant amount of effort to make sure that the engine itself is performant and not wasting CPU cycles. This has been measured in the past on actual Defold projects at King and Defold performed much better than games made using other engines.

If you are seeing high cpu usage while running the game then please check your Lua code. Are you running a lot of code every frame? Use the profiler to figure out where you spend your time.

Closing.
