### ISSUE TITLE
Textures of some atlases are not visible runtime/build on Windows 64, but visible in editor

### ISSUE THREAD

**Issue by paweljarosz** [defold/defold#5899]
Related Forum thread with more details and experiments: 
[https://forum.defold.com/t/texture-of-gui-node-invisible-in-runtime-build-but-visible-in-editor/68665/21](https://forum.defold.com/t/texture-of-gui-node-invisible-in-runtime-build-but-visible-in-editor/68665/)

**Describe the bug (REQUIRED)**
Some of the atlases are not visible in Windows builds and bundles, but are visible in HTML5 for example and when launched in RenderDoc (capture attached in forum thread). Sometimes using one atlas helps, sometimes not. Sometimes even creating a new atlas is not helping. On my laptop (DELL Latitude 5510, Intel Core i5-10210U, 16GB RAM, integrated Intel graphics card, Windows 10 x64) some of the sprites/GUI nodes are not visible)

**To Reproduce (REQUIRED)**
1. On Windows machine create an atlas and us it as a texture in sprite or GUI. It should be visible in Editor
2. Build in Editor or bundle Windows application.
3. See if sprite/GUI node is visible (sadly I see no pattern here, sometimes it is visible, sometimes it is not).

Reproduction example for GUI node attached in forum thread.

**Expected behavior (REQUIRED)**
Sprites and GUI nodes should be visible in Editor build or bundled runtime.

**Defold version (REQUIRED):**
  - 1.2.183
  Editor: db55f3faa6347a66d60715dddd9663687d54ceed
  Engine: f77b7f655a0ba68462f6c33604bed7000018735f

**Platforms (REQUIRED):**
 - Windows 10 64 bit

**Minimal repro case project (OPTIONAL):**
Reproduction example for GUI node attached in forum thread.

**Logs (OPTIONAL):**
-

**Workaround (OPTIONAL):**
Moving images to one atlases helps.

**Screenshots (OPTIONAL):**
Attached in the forum thread.

**Additional context (OPTIONAL):**
-

**Comment by aglitchman** [comment]
I just stumbled across this issue. Did you solve it by installing the newest video drivers? https://forum.defold.com/t/sprite-game-object-is-not-rendering/69198/40?u=aglitchman

**Comment by AGulev** [comment]
yes, this is driver related issue: https://forum.defold.com/t/help-i-dont-underand-it-anymore-solved-update-intel/77858/11?u=agulev

The solution is using https://www.intel.com/content/www/us/en/support/detect.html

**Comment by AGulev** [comment]
not sure if we should spend a lot of time trying to workaround driver issues.
closing it for now
