### ISSUE TITLE
Curve editor error Parrot linux Gnu

### ISSUE THREAD

**Issue by ghost** [defold/defold#5901]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2021-06-24T09:00:57.830039</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>ef34758568134f34f57c1ccc997be39c7f57c595</td></tr>
<tr><td>Defold engine sha</td><td>f77b7f655a0ba68462f6c33604bed7000018735f</td></tr>
<tr><td>Defold version</td><td>1.2.183</td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) HD Graphics 620 (KBL GT2)</td></tr>
<tr><td>GPU Driver</td><td>OpenGL ES-CM 1.1 Mesa 20.3.4</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.10.0-6parrot1-amd64</td></tr>
<table>

**Comment by britzl** [comment]
What kind of error did you get? For some reason I'm not able to see any stacktrace or similar...

**Comment by AGulev** [comment]
not enough info
