### ISSUE TITLE
HTML5 initial stretch canvas size is not accurate

### ISSUE THREAD

**Issue by subsoap** [defold/defold#5902]
When stretch is selected the initial canvas size is not accurate and only becomes accurate after resizing the window.

In my case, I added this to our main script's init

```
        html5.run("document.getElementById('canvas').width = window.innerWidth;")
        html5.run("document.getElementById('canvas').height = window.innerHeight;")
```

I read the code and don't quite understand why the initial size is not being set right but at least in our project it's the case. The initial size is being set to the project's window size.

**Comment by britzl** [comment]
Interesting. I'm a bit surprised that we haven't discovered this until now. Do you recognise this @AGulev ?

**Comment by AGulev** [comment]
@subsoap could you please share screenshot what you mean? I use `stretch ` in all my projects and it works fine (I assume), so I just don't get the issue. Everything looks fine for me:
with button and logo:
<img width="1520" alt="image" src="https://user-images.githubusercontent.com/2209596/123689508-95150500-d853-11eb-9902-19a1c9405350.png">

without button and logo :
<img width="1544" alt="image" src="https://user-images.githubusercontent.com/2209596/123689680-c8579400-d853-11eb-9e4b-bacc9eb4755f.png">

**Comment by subsoap** [comment]
@AGulev Maybe it's a unique case with my setup. I did make sure I was using the vanilla template and CSS when I reported this. Could be an interaction with a DefOS function. But I don't know. When I printed the values to the console they should be correct, not sure why the canvas was not being set the initial size.

![2021-06-25 12_37_22-Window](https://user-images.githubusercontent.com/409170/123719818-583b1500-d837-11eb-88f6-7bc6e58e8c35.png)
![2021-06-25 12_37_35-Window](https://user-images.githubusercontent.com/409170/123719821-5a04d880-d837-11eb-82ec-754ab383b18b.png)
![2021-06-25 13_00_31-DevTools - localhost_57355_html5_index html](https://user-images.githubusercontent.com/409170/123719826-5d985f80-d837-11eb-9ecd-d0886cff41e2.png)
![2021-06-25 13_00_41-DevTools - localhost_57355_html5_index html](https://user-images.githubusercontent.com/409170/123719827-5d985f80-d837-11eb-9610-98191b0c2631.png)

**Comment by AGulev** [comment]
It seems like it is something specific with your setup. If you attach a repo-case I'll take a look.

**Comment by subsoap** [comment]
It was my fault. I had a defos.set_view_size which was not blocked on HTML5 builds.
