### ISSUE TITLE
Cache service for compressed textures and other assets

### ISSUE THREAD

**Issue by britzl** [defold/defold#5906]
**Is your feature request related to a problem? Please describe (REQUIRED):**
Texture compression takes a very long time on projects with a lot of textures and high texture compression settings. Speeding up this step would result in a big productivity boost in general and for big teams in particular.

Note: Fonts can also take a bit of time to generate, and in the future there might be other assets that might take a long time to create.

**Describe the solution you'd like (REQUIRED):**
We should look into some kind of cache service. The service should store and return compressed textures (and possibly other kinds of assets as well). The assets should be stored by resource hash, resource settings (such as compression settings) and Defold version.

We need to figure out how access to the service should be handled. Should we use HTTP and some REST API? Or should it be file based and run directly against resources on disk (possibly on a network mounted shared cache storage)?

Perhaps look at Unity Accelerator for inspiration (but let's not over-engineer this!): https://docs.unity3d.com/Manual/UnityAccelerator.html

**Describe alternatives you've considered (REQUIRED):**
There's really no current workaround to this problem besides decreasing compression settings or ignoring compression completely.

**Comment by JCash** [comment]
If the path to the asset cache is a file path, then load/store files (atomically)
If the path is an url, then upload/download files
