### ISSUE TITLE
In the GUI editor, a child node cannot be pushed all the way down.

### ISSUE THREAD

**Issue by megalanthus** [defold/defold#5908]
### Expected behaviour
The node can be lowered to the very bottom.

### Actual behaviour
![image](https://user-images.githubusercontent.com/66716124/123760196-d1e00b00-d8ea-11eb-913b-8216cf0a85e1.png)

### Steps to reproduce
1. Create GUI.
2. Create a node.
3. Create 3 child nodes in it.
4. Try to move the child node to the bottom.
<hr/>

<table>
<tr><td>Build time</td><td>2021-06-15T09:14:31.286908</td></tr>
<tr><td>Defold channel</td><td>beta</td></tr>
<tr><td>Defold editor sha</td><td>1f5712609c345f870b691a85d611d4825d22a718</td></tr>
<tr><td>Defold engine sha</td><td>1f5712609c345f870b691a85d611d4825d22a718</td></tr>
<tr><td>Defold version</td><td>1.2.184</td></tr>
<tr><td>GPU</td><td>GeForce GTX 1060 3GB/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 456.71</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by AGulev** [comment]
https://github.com/defold/defold/pull/6625
