### ISSUE TITLE
Mouse y coordinates (action.screen_y) is inaccurate (larger) by 1 pixel

### ISSUE THREAD

**Issue by mosmetro** [defold/defold#5918]
Run attached project and see.
I expect y coords in range [0, 179], just like x in range - [0, 319].
Instead, y is in range [1, 180].
![Screen Shot 2021-07-03 at 18 53 08](https://user-images.githubusercontent.com/15055212/124360260-73d85e00-dc31-11eb-8ee5-d64e76624f4f.png)
[mouse_test.zip](https://github.com/defold/defold/files/6758686/mouse_test.zip)
This is macOS 10.15.7, Defold 1.2.184

**Comment by AGulev** [comment]
I tested it on windows and see the same result
it seems like for heigh coordinate space started from 1 not from 0

Windows:
<img width="436" alt="image" src="https://github.com/defold/defold/assets/2209596/3f79d494-a7f9-498e-9045-89eaeefa7da5">

<img width="453" alt="Screenshot 2023-11-03 at 13 10 57" src="https://github.com/defold/defold/assets/2209596/f5780fe8-016c-4c3e-a8ba-de7704fad2cd">

<img width="456" alt="image" src="https://github.com/defold/defold/assets/2209596/3b06187a-19c1-402b-9e1c-627a3d2ea1a9">


Macos:
<img width="401" alt="image" src="https://github.com/defold/defold/assets/2209596/cc92e106-4e17-4359-bead-3a50b7bb378e">

<img width="399" alt="image" src="https://github.com/defold/defold/assets/2209596/7126d34e-2203-4376-97fe-f053ba4ec5eb">

<img width="398" alt="image" src="https://github.com/defold/defold/assets/2209596/b3275dba-6b02-4b19-81f6-0138c517b656">
