### ISSUE TITLE
HTML5 build issue

### ISSUE THREAD

**Issue by PaperjetStudios** [defold/defold#5923]
**Describe the bug (REQUIRED)**

**To Reproduce (REQUIRED)**
1. Go to 'Project > Build HTML5 or Project > Bundle > HTML5 Application (any option)'
2. Click on The above'
4. See error - "Unknown Source > Resource 'assets/app_icons/icon_180.png' is not created'

**Expected behavior (REQUIRED)**
I expect an html5 application to be built

**Defold version (REQUIRED):**
  - Version [e.g. 1.2.184]

**Platforms (REQUIRED):**
 - Platforms: HTML5
 - OS: Big Sur (running editor on)
 - Device MacBook Pro (15-inch, 2017)

**Minimal repro case project (OPTIONAL):**
It only happens on my project, so I think I'm doing something wrong

**Logs (OPTIONAL):**
Unknown Source > Resource 'assets/app_icons/icon_180.png' is not created

Is there any quick fix for this?

**Comment by PaperjetStudios** [comment]
Sorry I think I fixed it. Apologies for this.

**Comment by britzl** [comment]
I believe the error was linked to the app icons for the Android target, which is strange since you built for HTML5.

How did you resolve the issue?
