### ISSUE TITLE
Failed to build game

### ISSUE THREAD

**Issue by Nekotato1412** [defold/defold#5924]
### Expected behaviour
As per the proxy manual I expected to be able to add a collection proxy to the main bootstrap collection.
### Actual behaviour
The following error occurs:
java.lang.AssertionError: Assert failed: Cycle detected on node type editor.collection/CollectionNode and output :build-targets
(not (contains? (:in-production evaluation-context) [node-id label]))
### Steps to reproduce
- Add a rendercam object
- Add an object containing a tilemap and another object inside with a sprite
- Add another object containing a sound component and a GUI object
- Make the GUI Object load the sound on startup
- Add another object containing a script and a collection proxy
- Build
<hr/>

<table>
<tr><td>Build time</td><td>2021-06-30T22:06:56.613889</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>fe9d9d4b439ce1472a329b444bae3cc003e52e2e</td></tr>
<tr><td>Defold engine sha</td><td>1f5712609c345f870b691a85d611d4825d22a718</td></tr>
<tr><td>Defold version</td><td>1.2.184</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"d10841ceddaf451db606dcd54a22b4f3"'>d10841ceddaf451db606dcd54a22b4f3</a></td></tr>
<tr><td>GPU</td><td>AMD ARUBA (DRM 2.50.0 / 5.4.0-77-generic, LLVM 11.0.0)</td></tr>
<tr><td>GPU Driver</td><td>3.1 Mesa 20.2.6</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.4.0-77-generic</td></tr>
<table>

**Comment by britzl** [comment]
I believe the error refers to some kind of cyclic dependency. Which collection does the collection proxy reference?

**Comment by Nekotato1412** [comment]
> I believe the error refers to some kind of cyclic dependency. Which collection does the collection proxy reference?

The collection it references is a collection located in a folder called levels and the collection's name itself is level_1.collection. Level 1.collection contains a tilemap and several game objects containing scripts for management of the game logic.

**Comment by britzl** [comment]
Ok, I see. I thought maybe the proxy referenced the main collection somehow. Can you share the project?

**Comment by Nekotato1412** [comment]
> Ok, I see. I thought maybe the proxy referenced the main collection somehow. Can you share the project?

Here it is. [
[Lukas Heroic Adventure.zip](https://github.com/defold/defold/files/6793096/Lukas.Heroic.Adventure.zip)
](url)

**Comment by britzl** [comment]
Found the problem:

`player.collection` contains `manager.collection` which has a collection proxy called `next` which references the `level1.collection`

And here is the problem:

`level1.collection` contains `player.collection` which creates a dependency loop.

You need to restructure your design to break this cycle.
