### ISSUE TITLE
Texture manipulation API

### ISSUE THREAD

**Issue by britzl** [defold/defold#5948]
A generic API to create and manipulate textures. Get UVs of images in an atlas. Create textures at runtime. Get texture data at runtime.

* https://github.com/defold/defold/issues/5435
* https://github.com/defold/defold/issues/3237

**Comment by jalhund** [comment]
This will be a wonderful thing to make mods easier to implement in the game

**Comment by dsmolyakov-ms** [comment]
Just in case, I will clarify that it would be desirable that the atlas generation functionality does not interfere with caching the resulting atlas, so that it can then simply be read without generation.

**Comment by britzl** [comment]
User wishlist:

* We give the API a list of pictures (paths to files with pictures).
* Specify the maximum size of the atlas.
* At the output, the API gives a list of the resulting atlases along with lists of textures, so that it is clear which texture is in which atlas.
* It is possible to add an image to an existing atlas. Here are the possible options:
   * or we simply add the image to the atlas (to the list of atlases), and if it does not fit, a new atlas is immediately returned with a description of the location of the textures;
   * or make a function that will let you know if a particular picture will fit in a particular atlas (or you need to create a new one) and make an add function (with the possible return of an add error).
* Resolve the issue with compression:
   * compress each time it is added to the atlas (preferably)
   * or let it be done manually when all the pictures are added (but then think about how to deal with adding textures to the atlas loaded from the cache).
* It is possible to save the atlas to the cache, read it from there and then add new pictures.
* Ability to delete the atlas cache (in case it is no longer needed).
* Getting a list of atlas textures (one way or another, we need to know which atlas contains which texture in order to compare these lists with others).

**Comment by jalhund** [comment]
>Function to check if an image will fit in the atlas?

I think that it's better way because user expects adding texture to specific atlas. If he add texture to atlas and it's appears in new atlas, it's strange. There can be some error handling: if there are no free space, then impossible to add
In any case it's new atlas, so user can't switch added textures without problems because he will need to change atlas too. Therefore, he will need to write his own code anyway to handle this behavior.

>Manual function call to compress when all images are added

I prefer this way because I'm afraid of performance problems if a large number of custom textures are loaded from modifications (for example, more than 50)

**Comment by dsmolyakov-ms** [comment]
> Manual function call to compress when all images are added

If this option is selected, then adding a texture to an already compressed atlas should still cause the texture to be automatically compressed. Because an important part of the functionality is adding textures to a previously created atlas.

**Comment by AGulev** [comment]
>If this option is selected, then adding a texture to an already compressed atlas should still cause the texture to be automatically compressed. Because an important part of the functionality is adding textures to a previously created atlas.

It shouldn't be a problem to implement if you get some data as a buffer from encoded atlas and put it into anoher encoded atlas. But everething is much more complicated if you wanna have an encoder in the runtime.

**Comment by britzl** [comment]
[Update existing texture at runtime](https://github.com/defold/defold/issues/7123) - DONE
[Runtime texture creation](https://github.com/defold/defold/issues/7153) - DONE
[Update existing atlas at runtime](https://github.com/defold/defold/issues/7164) - DONE
[Runtime Atlas Creation](https://github.com/defold/defold/issues/7192) - DONE
[Update compressed texture at runtime](https://github.com/defold/defold/pull/7206) - IN PROGRESS
