### ISSUE TITLE
Use sys.save() and sys.load() without a file

### ISSUE THREAD

**Issue by britzl** [defold/defold#5951]
**Is your feature request related to a problem? Please describe (REQUIRED):**
The sys.save() and sys.load() functions both write or read from a file. There may be situations when the developer wishes to do additional operations on the data before it is written to disk, for instance add some kind of encryption to prevent cheating or to store the data using some cloud service.

**Describe the solution you'd like (REQUIRED):**
Either an option to sys.save() and sys.load() to read/write to memory instead of file:

```
local data = { foo = "bar" }

-- OPTION 1
-- no filename = save to memory/string
local serialized_data = sys.save(nil, data)
-- no filename and string as second argument = load from string
local data = sys.load(nil, serialized_data)


-- OPTION 2
-- with options table indicating mode of operations
local serialized_data = sys.save(nil, data, { tostring = true })
local data = sys.load(serialized_data, { fromstring = true })


-- OPTION 3
-- new functions
local serialized_data = sys.saves(data) -- or maybe sys.save_to_string(data)
local data = sys.loads(data) -- or sys.load_from_string(data)
```

**Describe alternatives you've considered (REQUIRED):**
It would be possible to save to disk first and then do additional operations

**Comment by subsoap** [comment]
Sometimes we may want to load a file saved with sys.save() that is included in the bundle too.

**Comment by AGulev** [comment]
this issue solved as https://github.com/defold/defold/issues/6049
