### ISSUE TITLE
Enlarge Close Panel Button

### ISSUE THREAD

**Issue by PsychotropicDog** [defold/defold#5956]
**Is your feature request related to a problem? Please describe (REQUIRED):**
Trying to close a window in 1440p and the X button is tiny. The only thing that highlights is the white of the X which is hard to see, as it goes from pale almost white to slightly brighter almost white.

**Describe the solution you'd like (REQUIRED):**
Most programs have a button that highlights when rolled over, and is larger then the symbol representing what it does {minimize, expand, close}. Some x highlight the X button in red which would also help.

**Describe alternatives you've considered (REQUIRED):**
using a different engine
bitch about it

**Additional context (OPTIONAL):**

**Comment by AGulev** [comment]
not enough info
