### ISSUE TITLE
sys.open_url() with _blank on HTML5 should return false if popup is blocked

### ISSUE THREAD

**Issue by subsoap** [defold/defold#5957]
Current behavior changes the location of the current window if popup can't be made on HTML5, it should instead return false. The current behavior can break certain setups, such as if a game is in an iframe and it links to a domain which does not allow embeds. In this case, I'd prefer if it changes the top location instead, but that still should not be the default behavior.

https://github.com/defold/defold/blob/1ae302ec33d4514408c04ad3ae5d3c1efe2057bd/engine/dlib/src/dlib/js/library_sys.js#L68

Monkey patch to deal with this for my situation until it's fixed in code

```
SYS_INFO = sys.get_sys_info()
SYS_HTML5 = "HTML5"

function is_html5()
    if SYS_INFO.system_name == SYS_HTML5 then
        return true 
    end
    return false 
end

if is_html5() then
    sys.open_url = function(url, attributes)
        attributes = attributes or {target = "_self"}
        if html5.run('window.open(\"' .. url .. '\" , \"' .. attributes.target .. '\")') == "null" then
            attributes.target = "_top"
            if html5.run('window.open(\"' .. url .. '\" , \"' .. attributes.target .. '\")') == "null" then
                return false
            end
        else
            return true
        end
    end
end

function init(self)
    sys.open_url("https://www.defold.com/")
end
```

**Comment by britzl** [comment]
I'm actually leaning towards introducing a breaking change here. It is crazy that we fall back to changing the window.location if sys.open_url() fails. We do not give the developer a chance to decide on a course of action.

**Comment by AGulev** [comment]
related https://github.com/defold/defold/issues/5549
