### ISSUE TITLE
build

### ISSUE THREAD

**Issue by kouba06** [defold/defold#5960]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2021-07-29T20:48:50.037370</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>0a8d3e879724132afb18d47e0040c2034be07504</td></tr>
<tr><td>Defold engine sha</td><td>0a8d3e879724132afb18d47e0040c2034be07504</td></tr>
<tr><td>Defold version</td><td>1.2.185</td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 520</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 - Build 22.20.16.4836</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
No stack trace from Sentry. Closing.
