### ISSUE TITLE
Editor 1.2.185 crashes on Ubuntu 20.10

### ISSUE THREAD

**Issue by cnaize** [defold/defold#5968]
**Describe the bug (REQUIRED)**
Editor 1.2.185 crashes on Ubuntu 20.10

**To Reproduce (REQUIRED)**
1. I loads my own project into editor (worked on previous versions)
2. Run debug or bundle
3. Editor crashes

**Expected behavior (REQUIRED)**
I expect that my project will be run.

**Defold version (REQUIRED):**
  - Version 1.2.185

**Platforms (REQUIRED):**
 - OS: Ubuntu 20.10

**Logs (OPTIONAL):**
[Crash dump](https://pastebin.com/gVZER5d4)

Thanks

**Comment by britzl** [comment]
Ok, the crash seems related to font creation and compression (com.dynamo.bob.TexcLibrary.TEXC_CompressBuffer). Did the same work in 1.2.184?

**Comment by cnaize** [comment]
I don't know, but everything is ok on Mac OS. I moved there while the bug is not fixed.

**Comment by cnaize** [comment]
@britzl where I can find version 1.2.184?
I don't see versions below 1.2.185 here https://d.defold.com/stable/

**Comment by britzl** [comment]
> where I can find version 1.2.184

Releases are also available on GitHub: https://github.com/defold/defold/releases

**Comment by cnaize** [comment]
I checked. On 1.2.184 doesn't work too.
Maybe I need to update some package?

**Comment by britzl** [comment]
My guess is that it might be an FFI issue, since it crashes when trying to interact with the TexcLibrary. Try this:

https://defold.com/manuals/linux/#q-the-defold-editor-crashes-when-opening-a-collection-or-game-object-and-the-crash-refers-to-libffiso

**Comment by AGulev** [comment]
not enough info + outdated
