### ISSUE TITLE
High Latency on Tile Map Editor

### ISSUE THREAD

**Issue by mcfarlanedev** [defold/defold#5978]
**Describe the bug**
When navigating the Tilemap Editor on **Linux (Pop!OS 20.04 LTS)**, there appears to be some latency when hovering over active tile. The tile source image that was used was from the Defold War Battles Tutorial (512x512)

**To Reproduce**
1. Create a new Tile Source 
2. Assign the tile source an image
3. Create a new Tile Map
4. Assign the tile map's source from Step 2
5. Select layer1 to place tiles on the map
6. Proceed to select tiles from the source (using spacebar), moving the mouse highlights the issue

**Expected behavior**
I would expect the editor to have 0 latency when interacting with the tilemap editor. 

**Defold version**
 - Version 1.2.185

**Platforms**
 - OS: Linux - Pop!OS 20.04 LTS
 - PC Specs: 
    - CPU: AMD Ryzen 3700x, 
    - GPU: Radeon VII 
    - RAM: 2x8gb 3200mhz GSkill Flare X

**Screenshots (OPTIONAL):**
![Peek_2021-08-08_00-12](https://user-images.githubusercontent.com/12474833/128634519-541dd09e-b62f-4d75-bf72-7edc50444eee.gif)

**Additional context (OPTIONAL):**
Map source: 
![map](https://user-images.githubusercontent.com/12474833/128634740-f7acf185-371a-4a5c-98da-25a81029eb2e.png)

**Comment by AGulev** [comment]
it seems like the issue related to https://github.com/defold/defold/pull/7451
