### ISSUE TITLE
Pre-built dmengine.apk does not install on Android 11

### ISSUE THREAD

**Issue by britzl** [defold/defold#5979]
**Describe the bug (REQUIRED)**
The pre-built dmengine.apk provided from d.defold.com and github.com does not install on Android 11. The following is seen in the adb log:

`No signature found in package of version 2 or newer for package com.defold.dmengine`

**To Reproduce (REQUIRED)**
1. Download dmengine.apk
2. Install on Android 11 device
3. Notice the "app not installed" error

**Expected behavior (REQUIRED)**
It should install

**Defold version (REQUIRED):**
  - Version 1.2.185

**Platforms (REQUIRED):**
 - Platforms: Android
 - OS: 11
 - Device: All

**Workaround (OPTIONAL):**
Bundle an empty project from the editor or bob.jar and use it instead

**Additional context (OPTIONAL):**
https://forum.defold.com/t/dmengine-wont-install-on-android-11/69041

**Comment by CocosGames** [comment]
I got it.
Solution: (choose one)
1, set targetSdkVersion < 30 in Manifest;
2, using V2 signature.

**Comment by britzl** [comment]
We have decided to change how the dev app is built. Previously it was built using arcane python scripts in build_tools/waf_dynamo.py. We will now set up a separate Defold project with the required files and build that using bob as part of the release process.

**Comment by strflw** [comment]
Is there a user-fix after over a month now??
Clearly i can neither fix dmengine.apk signing and also cant change its manifest.

**Comment by strflw** [comment]
Found a solution, just in case someone else looks for it:
Build the app once as debug version and install it manually (using adb e.g)
Once its installed and runnign defold Editor will recognize your device via USB and via Wifi.

**Comment by britzl** [comment]
> Is there a user-fix after over a month now??

The dmengine.apk app has moved here: https://github.com/defold/dev-app

Bundle it using Defold or bob.jar and install it. Or, like you discovered, take any Defold app and bundle in debug mode.
