### ISSUE TITLE
IDE: Assets should be sorted in the natural order

### ISSUE THREAD

**Issue by aglitchman** [defold/defold#5981]
**Describe the bug**
Defold IDE has a different sorting order in the Outline and Assets panels. Outline Panel has the natural order. Assets has the lexicographical order (I don't know how to name it right).

I do think the sort order should be the same in both panels, and it should be the natural order.

By the way, popular apps like VS Code, Windows Explorer have the natural order.

**Actual behavior**
- 1.go
- 10.go
- 11.go
- 2.go
- 3.go
- 4.go
- 5.go
- 6.go
- 7.go
- 8.go
- 9.go

**Expected behavior**
- 1.go
- 2.go
- 3.go
- 4.go
- 5.go
- 6.go
- 7.go
- 8.go
- 9.go
- 10.go
- 11.go

**Defold version:**
  - Version: All

**Platforms:**
 - Platforms: Windows

![image](https://user-images.githubusercontent.com/193258/128705812-38d8e3d9-d926-4e7b-8e84-f56de838b38c.png)
![image](https://user-images.githubusercontent.com/193258/128705852-5a072477-9382-4996-8477-916ead5a1036.png)

**Comment by notbadgun** [comment]
It happens in many places ((((
1. ![image](https://user-images.githubusercontent.com/13905665/128712736-3a23793a-2ef4-453e-aa4d-cb248d83c92f.png)
2. ![image](https://user-images.githubusercontent.com/13905665/128713078-a1bee35f-2589-40cc-bc0b-b8f8b203edd1.png)

**Comment by vlaaad** [comment]
Fixed, check for updates and feel free to reopen if you find another place that needs natural sorting!
