### ISSUE TITLE
IDE: Assets/Outline line spacing should be tighter by default 

### ISSUE THREAD

**Issue by aglitchman** [defold/defold#5982]
**Is your feature request related to a problem? Please describe (REQUIRED):**
I use Defold IDE daily, and I'm frustrated about the default line spacing in the Assets and Outline panels. I'm sure that the spacing should be tighter to let us scroll lesser.

Let's discuss?...

The comparison of Unity vs VS Code vs Defold IDE:
![image](https://user-images.githubusercontent.com/193258/128708293-13786b13-4c0d-465a-b73f-47990773a86d.png)

**Describe the solution you'd like (REQUIRED):**
https://forum.defold.com/t/experiments-with-editor-styling-using-javafx-css/67021/5?u=aglitchman

**Comment by britzl** [comment]
I agree! As a user you can obviously change this yourself using a custom stylesheet, but I think this is something that would benefit everyone.

It should be this file that needs changing:

https://github.com/defold/defold/blob/dev/editor/styling/stylesheets/components/_tree-view.scss#L13

My guess, without testing, is that it would impact the Outline as well (which is fine by me!).
