### ISSUE TITLE
Defold 1.2.185 crash on Windows 10

### ISSUE THREAD

**Issue by cnaize** [defold/defold#5985]
**Describe the bug (REQUIRED)**
Engine crash on Windows 10

**To Reproduce (REQUIRED)**
1. I run my project
2. Intro with music has been played
3. On next screen the game has been crashed (next track is not played)

Without music everything is working well.

**Expected behavior (REQUIRED)**
Everything but not crash

**Defold version (REQUIRED):**
  - Version 1.2.185

**Platforms (REQUIRED):**
 - Platforms: Windows
 - OS: Windows 10

**Logs (OPTIONAL):**
ERROR:CRASH: CALL STACK:

ERROR:CRASH:  0 0x7FF703A69300 dmCrash::GenerateCallstack D:\a\defold\defold\engine\crash\src\backtrace_win32.cpp:142

ERROR:CRASH:  1 0x7FF703DC21D4 _seh_filter_exe /tmp/job4745236272883254517/minkernel/crts/ucrt/src/appcrt/misc/exception_filter.cpp:219

ERROR:CRASH:  2 0x7FF703E1505C `__scrt_common_main_seh'::`1'::filt$0 d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:304

ERROR:CRASH:  3 0x7FF703D8B490 __C_specific_handler d:\agent\_work\4\s\src\vctools\crt\vcruntime\src\eh\riscchandler.cpp:290

ERROR:CRASH:  4 0x7FF9A9C13490 __chkstk <unknown>:0

ERROR:CRASH:  5 0x7FF9A9B735F0 RtlWalkFrameChain <unknown>:0

ERROR:CRASH:  6 0x7FF9A9C122F0 KiUserExceptionDispatcher <unknown>:0

ERROR:CRASH:  7 0x7FF703A6D270 maybe_start_packet D:\a\defold\defold\engine\sound\src\stb_vorbis\stb_vorbis.c:1444

ERROR:CRASH:  8 0x7FF703A720F0 vorbis_decode_initial D:\a\defold\defold\engine\sound\src\stb_vorbis\stb_vorbis.c:3148

ERROR:CRASH:  9 0x7FF703A73280 vorbis_pump_first_frame D:\a\defold\defold\engine\sound\src\stb_vorbis\stb_vorbis.c:3524

ERROR:CRASH: 10 0x7FF703A39090 dmSoundCodec::StbVorbisResetStream D:\a\defold\defold\engine\sound\src\decoders\decoder_stb_vorbis.cpp:88

ERROR:CRASH: 11 0x7FF703A524E0 dmSound::Stop D:\a\defold\defold\engine\sound\src\sound.cpp:772

ERROR:CRASH: 12 0x7FF703C291F0 dmGameSystem::CompSoundUpdate D:\a\defold\defold\engine\gamesys\src\gamesys\components\comp_sound.cpp:203

ERROR:CRASH: 13 0x7FF703AB4EE0 dmGameObject::Update D:\a\defold\defold\engine\gameobject\src\gameobject\gameobject.cpp:2423

ERROR:CRASH: 14 0x7FF703AD7990 dmEngine::Step D:\a\defold\defold\engine\engine\src\engine.cpp:1513

ERROR:CRASH: 15 0x7FF703AD49D0 dmEngineUpdate D:\a\defold\defold\engine\engine\src\engine.cpp:1973

ERROR:CRASH: 16 0x7FF703AD9E80 dmEngine::RunLoop D:\a\defold\defold\engine\engine\src\engine_loop.cpp:69

ERROR:CRASH: 17 0x7FF703A4F8F0 engine_main D:\a\defold\defold\engine\engine\src\engine_main.cpp:127

ERROR:CRASH: 18 0x7FF703D8B044 __scrt_common_main_seh d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288

ERROR:CRASH: 19 0x7FF9A9837E80 BaseThreadInitThunk <unknown>:0

ERROR:CRASH: 20 0x7FF9A9BD7AB0 RtlUserThreadStart <unknown>:0

Crach dump is here:
[_crash.txt](https://github.com/defold/defold/files/6976005/_crash.txt)
**NOTE: remove ".txt" extension at the end***

**Workaround (OPTIONAL):**
Didn't find.

**Comment by cnaize** [comment]
For more info:
My `play_music` function looks like this:
```
local function play_music(self, name, callback)
	...
	sound.stop("#music")
	local buff, err = sys.load_resource("/assets/audio/music/" .. name .. ".ogg")
	if buff then
		local path = go.get("#music", "sound")
		resource.set_sound(path, buff)
		sound.play("#music", nil, callback)
	end
end
```

**Comment by britzl** [comment]
@cnaize thanks. Some additional questions:

1. Does it matter which .ogg file you are using?
2. Does the same ogg file work if it is added to a sound component in the editor?
3. What have you assigned initially to the sound component before changing resource with resource.set_sound()?

**Comment by cnaize** [comment]
@britzl hi
1. No (but I've converted all my sounds the same way)
2. Don't undertand
3. Initially assigned "intro" music, which played first (the same sound as used in first screen)

To add more details I did more tries and looks like:
1. The problem is non constant (sometimes it work)
2. To reproduce better to use different sounds (play the same sound multiple times works in some cases)
3. Looks like sound resource loads incorrect

**Comment by britzl** [comment]
> 2\. Don't undertand

What if you create a sound component in the editor and then assign the ogg file to the component and play it from a script? Does the same ogg file work this way as opposed to when you load it with sys.load_resource() + resource.set_sound() + sound.play()?

https://defold.com/manuals/sound/#creating-a-sound-component

Can you perhaps share a minimal project where this problem can be reproduces?

**Comment by cnaize** [comment]
@britzl

I made the experiment:
1. I've created many sound components instead of one
2. I stop last sound component and after this immediately play next sound component
3. The game crashes

But on Android and MacOS all the ways works fine.

**Comment by britzl** [comment]
> I made the experiment

Do you still have the experiment/sample project that you could share? It's helpful to have the exact same setup as you when we verify and fix an issue.

**Comment by cnaize** [comment]
Yes, if I use the sound as initial, it plays ok. It plays ok on first screen, then on the next screen I can stop the sound component with the sound and play the same sound from another sound component. It works.
But if I use different sounds on first screen and second screen, the sound on the second screen crash the app.

**Comment by britzl** [comment]
> Do you still have the experiment/sample project that you could share?

Could you please zip the project and upload it as an attachment to this issue? We really don't want to spend unnecessary time trying to reproduce a small sample project in order to verify the problem and a fix only to find out that we didn't get the setup exactly right.

**Comment by cnaize** [comment]
Sorry, but this is production ready game with publisher, I can't open source it because it will be published really soon.
The only think that stops the publishing process is this bug.
I know that you charge me nothing, but could you please try to understand that's going on by crash report and my comments?
Anyway, if my setup in wrong I don't think that the engine should crash.

**Comment by britzl** [comment]
No no, I'm not asking you to share the source code of your game. We want to find a minimal project that shows the problem.

If I don't know how to reproduce the problem I would be guessing and wasting a lot of time trying to reproduce the problem. We are happy to help fix bugs, but we need your help finding a way to reproduce the problem first.

For instance you write that "But if I use different sounds on first screen and second screen, the sound on the second screen crash the app."

What is a screen in this case? A collection proxy?

Either describe the **exact** steps I need to take to reproduce it, like below or a small project (not your big project) where the problem happens:

* Create an empty project
* Create a game object in the bootstrap collection
* Create three (?) sound components by right-clicking the game object and selecting Add Component->Sound
* Assign three different .ogg files to the three sound components
* Create a script file and attach it to the game object with the sound component
* Add the following to the script:

```
script content
```

* Build and run on Windows
* Notice the crash

**Comment by cnaize** [comment]
Oh! I think I found the bug.

The problem was in the names of the sound files, they have had unrecognized symbols.
After renaming all the sound files the problem has gone.

I think you may close the issue.

**Comment by britzl** [comment]
I'm happy to hear that you figured out the problem!
