### ISSUE TITLE
Tilemap and tilesource errors in Linux

### ISSUE THREAD

**Issue by john-cheesman** [defold/defold#5987]
### Expected behaviour
Opening a tilemap or tilesource file should launch the expected editor.
### Actual behaviour
An error is displayed and the editor window is blank:
`java.lang.ClassCastException: class jogamp.opengl.es1.GLES1Impl cannot be cast to class com.jogamp.opengl.GL2ES2 (jogamp.opengl.es1.GLES1Impl and com.jogamp.opengl.GL2ES2 are in unnamed module of loader 'app')`
### Steps to reproduce
Try opening a tilemap or tilesource file in the Linux build.
<hr/>

<table>
<tr><td>Build time</td><td>2021-08-02T14:29:43.966790</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>0a8d3e879724132afb18d47e0040c2034be07504</td></tr>
<tr><td>Defold engine sha</td><td>0a8d3e879724132afb18d47e0040c2034be07504</td></tr>
<tr><td>Defold version</td><td>1.2.185</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"c207046fea79413cb1a02328fc89b113"'>c207046fea79413cb1a02328fc89b113</a></td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) HD Graphics 5500 (BDW GT2)</td></tr>
<tr><td>GPU Driver</td><td>OpenGL ES-CM 1.1 Mesa 21.1.6</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.13.9-arch1-1</td></tr>
<table>

**Comment by britzl** [comment]
@john-cheesman I believe you may have come across this issue:

https://defold.com/manuals/linux/#q-the-defold-editor-crashes-when-opening-a-collection-or-game-object-and-the-crash-refers-to-comjogampopengl

**Comment by john-cheesman** [comment]
That's fixed it, thanks :+1:
