### ISSUE TITLE
IDE: Display quick help if no files are opened

### ISSUE THREAD

**Issue by aglitchman** [defold/defold#5990]
**Is your feature request related to a problem? Please describe (REQUIRED):**
I like a quick help page that VS Code shows when there are no files opened. Defold IDE can display the same quick help to be not so empty and help new users navigate.

See the example below (I copy-pasted it from the VS Code).

**Describe the solution you'd like (REQUIRED):**
![image](https://user-images.githubusercontent.com/193258/129361274-63b7a0d9-fc24-40e7-81b7-09a80dbac68b.png)

**Comment by quangson91** [comment]
@aglitchman @britzl @matgis  I have just created a PR: https://github.com/defold/defold/pull/8085

Could you guy take a look?
I just want to get some suggestion to improve the quick-help-page.

Thanks!
