### ISSUE TITLE
Improve Colour Picker

### ISSUE THREAD

**Issue by BinaryMoon** [defold/defold#5999]
**Is your feature request related to a problem? Please describe (REQUIRED):**
I'm frustrated by the colour picker(s) in the editor. Mostly in the gui editor. I want to use hexadecimal colours, but to do this I have to click the colour field, then custom colour, then web, then paste the colour I want to use.

**Describe the solution you'd like (REQUIRED):**
I think there should be two changes.
1. I would like to be able to paste hex colours into the colour field directly.
2. I would suggest removing the popup colour palette and going straight to the custom colours dialogue. I suspect that, apart from maybe white and black, that colour palette is of little use to most people. My guess is most people will colour pick in photoshop/ similar and want to paste the colour into the editor.

**Describe alternatives you've considered (REQUIRED):**
none

**Additional context (OPTIONAL):**
As an aside, there is also a colour setting in the game.project file for setting a clear colour. This is lower priority since you don't need to ochange it often, but it uses a non-standard format of colour values being beteen 0 and 1, which took somoe working out. I can use rgb or hex, but I had to calculate the 0-1 settings.

**Comment by cloudziq** [comment]
would be nice to have ability to copy current node colour item as for pasting to `gui.set_color(vmath.vector3(r,g,b,a))` (for example).
Now it needs a manual conversion from `0 - 255` to `0 - 1` for each color channel

**Comment by britzl** [comment]
Duplicate https://github.com/defold/defold/issues/6693
