### ISSUE TITLE
Random crashes - I'm thinking maybe texture / memory related?

### ISSUE THREAD

**Issue by nebreywas** [defold/defold#6008]
### Expected behaviour
run game in editor and no crash

### Actual behaviour
run game in editor and it's sometimes crashes

### Steps to reproduce
load code, run game...

<hr/>

<table>
<tr><td>Build time</td><td>2021-08-24T08:35:09.620408</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>1238ae4c78250fac5830b149a6bf3cd4bb42899e</td></tr>
<tr><td>Defold engine sha</td><td>1f748d5b0a84e8b5c58bf747e4c48d153ef77a52</td></tr>
<tr><td>Defold version</td><td>1.2.186</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"04af875dc93b475fbb82d5f5587a5935"'>04af875dc93b475fbb82d5f5587a5935</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 460 OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-4.5.14</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.16</td></tr>
<table>

**Comment by britzl** [comment]
Old. No data in Sentry.
