### ISSUE TITLE
java.lang.NullPointerException: Unknown

### ISSUE THREAD

**Issue by nebreywas** [defold/defold#6009]
### Expected behaviour
expect it to just run

### Actual behaviour
java.lang.NullPointerException: Unknown

### Steps to reproduce
load code run game -- doesn't always trigger 
<hr/>

<table>
<tr><td>Build time</td><td>2021-08-24T08:35:09.620408</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>1238ae4c78250fac5830b149a6bf3cd4bb42899e</td></tr>
<tr><td>Defold engine sha</td><td>1f748d5b0a84e8b5c58bf747e4c48d153ef77a52</td></tr>
<tr><td>Defold version</td><td>1.2.186</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"eb64d9fd04bb4b439cc59431d244d5d9"'>eb64d9fd04bb4b439cc59431d244d5d9</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 460 OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-4.5.14</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.16</td></tr>
<table>

**Comment by britzl** [comment]
No additional information provided. Closing.
