### ISSUE TITLE
Our android-repack.sh script needs updating after moving to sdk version 30

### ISSUE THREAD

**Issue by JCash** [defold/defold#6019]
The repack "works" without errors, but when trying to load the apk, it fails with this output:

>Installing com.example.todo
adb: failed to install bundle_android/Issue-5350-android-reboot-issue/Issue-5350-android-reboot-issue.repack.apk: Failure [-124: Failed parse during installPackageLI: Targeting R+ (version 30 and above) requires the resources.arsc of installed APKs to be stored uncompressed and aligned on a 4-byte boundary]

**Comment by AGulev** [comment]
hmmm
it seems like this issue fixed
I can't reproduce it
