### ISSUE TITLE
Touch inputs can accumulate causing action table to exceed 2K message size

### ISSUE THREAD

**Issue by dri-richard** [defold/defold#6028]
**Describe the bug**
In certain circumstances, the action table passed to on_input can have more than 5 touch events (I've seen up to 11). It's common to pass this table to other components in a message, and this bug can cause the table to exceed the 2K maximum payload size.
This was first noticed when trying to reproduce a bug caused by the device going to sleep/locking and then being woken, but is more easily reproduced by deploying a project to a debug build. In both cases it seems that input is registered, not consumed by the game, and not then cleared by the engine.

**To Reproduce**
1. Download the defold-input project
2. Set cursor_and_gesture.collection as the main collection in Bootstrap settings.
3. Bundle for iOS
4. Install and run (the display will be blank)
5. Set the iOS device as the target device in the editor
6. Start quickly & repeatedly tapping the iOS device screen
7. Build to the device.

Errors will be seen in the console, and running pprint on the action table will show more than 5 elements in action.touch
```
ERROR:SCRIPT: /in/cursor.script:127: buffer (78 bytes) too small for table, exceeded at value (string) for element #4
stack traceback:
  [C]:-1: in function post
  /in/cursor.script:127: in function trigger_event
  /in/cursor.script:216: in function </in/cursor.script:141>
```
**Expected behavior**
The console window should show no errors

**Defold version:**
1.2.185

**Platforms:**
 - Platforms: iOS
 - OS: iOS 14.7.1
 - Device: iPhone SE 2

**Workaround:**
Potentially calling msg.post through pcall or detecting that there are too many touch actions and removing some of them.

**Comment by britzl** [comment]
Closing for now as I don't see what to improve on.
