### ISSUE TITLE
Debugging is not working on Mac BigSur

### ISSUE THREAD

**Issue by EvoTeamDevelop** [defold/defold#6029]
### Expected behaviour
Application will be build with attached debugging

### Actual behaviour
<img width="545" alt="Screenshot 2021-09-04 at 22 56 43" src="https://user-images.githubusercontent.com/89959159/132106585-5234ff0a-021d-4a44-a050-2a55c4e25d03.png">

### Steps to reproduce
1. Install dmengine on Android.
2. Using the same WiFi select Android as Target.
3. Build the application with Debug.

<hr/>

<table>
<tr><td>Build time</td><td>2021-08-24T08:35:09.620408</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>1238ae4c78250fac5830b149a6bf3cd4bb42899e</td></tr>
<tr><td>Defold engine sha</td><td>1f748d5b0a84e8b5c58bf747e4c48d153ef77a52</td></tr>
<tr><td>Defold version</td><td>1.2.186</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"b98fc1485a9f43af91310c47bdded8b3"'>b98fc1485a9f43af91310c47bdded8b3</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 5300M OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-4.6.20</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.16</td></tr>
<table>

**Comment by britzl** [comment]
@EvoTeamDevelop does the debugger work if you first start the game and then select Debug->Attach from the menu?

**Comment by EvoTeamDevelop** [comment]
Yes, it is possible!

**Comment by britzl** [comment]
This has been fixed in PR: https://github.com/defold/defold/pull/6031

It will be available as an editor update soon.
