### ISSUE TITLE
Defold Crashes (Not responding) when opening .bmp file from the assets pane

### ISSUE THREAD

**Issue by medooox3** [defold/defold#6035]
**Describe the bug (REQUIRED)**
Editor Crashes (Not responding) when opening .bmp file from the assets pane.

**To Reproduce (REQUIRED)**
1. Create new Empty project.
2. from the assets pane -> builtins -> assets -> images -> logo -> logo_blue_1024.bmp
3. Double click the logo_blue_1024.bmp
4. The editor freezes completely (Not responding) 

**Expected behavior (REQUIRED)**
The .bmp file should open in external photo viewer program

**Defold version (REQUIRED):**
  - Version 1.2.186
  - Channel: editor-alpha

**Platforms (REQUIRED):**
 - Platforms: Windows
 - OS: Windows 10

**Screenshots (OPTIONAL):**

![dwm_3BRQZKFpVx](https://user-images.githubusercontent.com/11200173/132528457-d58e82a0-97b9-4aee-a1ab-a63614d3e07a.png)

**Comment by AGulev** [comment]
It opens now as text. Not perfect, but it doesn't hang anymore 
(I think it's fine, we don't support `bmp` in atlases or anywhere)
