### ISSUE TITLE
Switching external editor ⇔ Defold editor

### ISSUE THREAD

**Issue by jeangit** [defold/defold#6041]
**Description**
I’m using neovim as external editor.

I’d like to use internal editor of Defold when it’s time to debug.

In the « Assets » tab, i’ve tried to right click on a script file, and « open as code » but it is still opened in neovim.

The only way is to erase the configuration of the external editor.

**Solution i'd like**
An option for quick swap between external/internal editor, without losing external editor parameters.

**Alternative solution**
_open as code_ contextual menu opens the file in the Defold editor.

**Comment by AGulev** [comment]
the issue fixed in 1.9.1
