### ISSUE TITLE
Multi-page atlases

### ISSUE THREAD

**Issue by AGulev** [defold/defold#6044]
**Task (REQUIRED):**

Sometimes it's impossible to put everything in one atlas, even if it's a pretty big 4096x4096 atlas.
In such cases using of a couple atlases break batching and increase draw calls count.

In some cases it also affects RAM when it's possible to use 5-6 1024x1024 atlases but use 2 4096x4096 atlases instead.

That would be nice to have multi-page atlases where a dev can choose what size of page he is ready to use for an atlas and the editor shows how many pages it takes (runtime draws images from these atlases in one srawcall as it's one atlas)

For example:

https://phaser.io/tutorials/advanced-rendering-tutorial/part2

**Expected outcome (REQUIRED):**

This would be a huge draw calls saver especially for big projects.
Also it could help to save some memory.

**Comment by britzl** [comment]
See PR for current state. @Jhonnyg to also research a solution using cubemaps instead.
