### ISSUE TITLE
Automatically add extra Android packages when calling AAPT

### ISSUE THREAD

**Issue by britzl** [defold/defold#6047]
**Is your feature request related to a problem? Please describe (REQUIRED):**
Android extension creators usually need to specify extra packages to pass into the Android AAPT tool while building to ensure all resources are included. The Android Gradle plugin most likely figures out which packages to add. The Defold build process should be able to do the same.

**Describe the solution you'd like (REQUIRED):**
The Defold build pipeline should automatically figure out which extra packages to pass into the AAPT build step.

**Describe alternatives you've considered (REQUIRED):**
Continue to manually define it per extension.

**Additional context (OPTIONAL):**

**Comment by AGulev** [comment]
As I understand, all the AARs that have `res` folder should be included using `--extra-packages this.aar.package.name` or even for all AARs.
