### ISSUE TITLE
Include build time measurements in the build report

### ISSUE THREAD

**Issue by britzl** [defold/defold#6048]
**Is your feature request related to a problem? Please describe (REQUIRED):**
The build process is currently a bit of black box with no real indication of what steps take the most time.

**Describe the solution you'd like (REQUIRED):**
The build report should include timings of the various build steps in the build report

**Describe alternatives you've considered (REQUIRED):**
-

**Comment by AGulev** [comment]
It will be useful to take a look why building with bob.jar using just a `--variant debug build` takes much longer than build in the editor (in a small project: 10s vs 1s for incremental build in a small project, and 20-25s vs 11s for the firs build)
