### ISSUE TITLE
Expose Lua tables serialization/deserialization functions from sys.save/sys.load

### ISSUE THREAD

**Issue by aglitchman** [defold/defold#6049]
**Is your feature request related to a problem? Please describe (REQUIRED):**
JSON can't represent Lua tables as is, and it's hard to maintain JSON-safe Lua tables.

I know few cases when developers had problems with game data saving in their HTML5 games because DefSave internally does that via JSON on the HTML5 platform. Yes, it is the issue of DefSave. But it could be fixed only if Defold provided such API.

**Describe the solution you'd like (REQUIRED):**
`sys.save` and `sys.load` functions handle Lua tables + Defold userdata types. I would like to have the same built-in functions that can serialize the Lua table to **variable** and deserialize it. 

The names can be `sys.stringify_table` and `sys.parse_table` (I'm not good in function naming 😄 ). 

Also, it's a good idea to expose `dmCrypt::Base64Encode` as a Lua function to convert Lua strings with binary data to ASCII format.

**Describe alternatives you've considered (REQUIRED):**
I made the native extension "[SaveTable](https://github.com/aglitchman/defold-savetable)" that uses [private Defold C++ API plus Base64 encoding](https://github.com/aglitchman/defold-savetable/blob/main/savetable/src/main.cpp) to help developers to use DefSave for HTML5 without the need to reimplement the structure of savedata tables to be JSON-safe.

**Comment by britzl** [comment]
This is a great feature request which I've actually considered myself! Saving a data blob in a database, serialising and sending state over a network connection etc

> The names can be `sys.stringify_table` and `sys.parse_table`

`sys.serialize(t)` and `sys.deserialize(s)` are good names I think.

> Also, it's a good idea to expose `dmCrypt::Base64Encode` as a Lua function to convert Lua strings with binary data to ASCII format.

We have some exposed crypto and encoding functions in https://github.com/defold/extension-crypt

**Comment by aglitchman** [comment]
> `sys.serialize(t)` and `sys.deserialize(s)` are good names I think.

Yes, I like it! Nice!

> We have some exposed crypto and encoding functions in https://github.com/defold/extension-crypt

Oh, thanks! I completely forgot about this extension.
