### ISSUE TITLE
Setting same buffer to a mesh component makes it stop rendering

### ISSUE THREAD

**Issue by JCash** [defold/defold#6055]
> ..If you spawn a mesh, then try to set the same buffer that is already set on it, it stops rendering. I’ll validate this tomorrow and open an issue about it.

```go.set("#mesh", "vertices", go.get("#mesh", "vertices))```

https://forum.defold.com/t/mesh-component/65137/80

**Comment by dapetcu21** [comment]
@britzl Sorry I managed to be a bit sick this week and didn't get to this. I wanted to do this now, but I upgraded my laptop to Monterey and the editor crashes on me now. I'll check to see if I can remote into my computer at work that's still on Big Sur.

**Comment by dapetcu21** [comment]
Hmm... I couldn't get it to repro here either. I'll try reproing it again in our project and see if I can maybe isolate it to something simpler.

**Comment by dapetcu21** [comment]
Here's a reprocase with the exact game object that's giving me troubles in-game:
[Archive.zip](https://github.com/defold/defold/files/7478006/Archive.zip)
