### ISSUE TITLE
Build fails on Linux Mint 20.02

### ISSUE THREAD

**Issue by smnbldwn** [defold/defold#6056]
I have just downloaded Defold and am trying the first tutorial (Sidescroller)

When I choose build Sidescroller tutorial project (unmodified by me)

The build is unsuccessful and it throw an error

Sidescroller

<hr/>

<table>
<tr><td>Build time</td><td>2021-09-09T20:26:36.042514</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>71d178069a8fa37a4a52d3b44b98bd7596197e4e</td></tr>
<tr><td>Defold engine sha</td><td>1f748d5b0a84e8b5c58bf747e4c48d153ef77a52</td></tr>
<tr><td>Defold version</td><td>1.2.186</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"6622214d041d452bbcdccb347c8415ee"'>6622214d041d452bbcdccb347c8415ee</a></td></tr>
<tr><td>GPU</td><td>Mesa DRI Intel(R) 965GM (CL)</td></tr>
<tr><td>GPU Driver</td><td>OpenGL ES-CM 1.1 Mesa 21.0.3</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.4.0-84-generic</td></tr>
<table>

**Comment by britzl** [comment]
`class java.lang.ClassCastException`

I'm not getting a proper exception in Sentry... But seeing as this is on Linux with the Mesa GPU driver I'd try either overriding Mesa version:

https://defold.com/manuals/linux/#q-the-defold-editor-crashes-when-opening-a-collection-or-game-object-and-the-crash-refers-to-comjogampopengl

Or switching to software rendering:

https://defold.com/manuals/linux/#q-my-opengl-drivers-are-outdated-can-i-still-use-defold

**Comment by AGulev** [comment]
no action from reporter
