### ISSUE TITLE
Editor crash when adding image for tilesource collision

### ISSUE THREAD

**Issue by jeangit** [defold/defold#6057]
### Expected behaviour
The editor doesn't crash and collision mask is generated.

### Actual behaviour
The editor crash and collision mask isn't generated.

I get this error:

```
clojure.lang.ExceptionInfo: handler ':quit' in context ':global' failed at ':run' with message 'Caught exception during read: '
javax.imageio.IIOException: Caught exception during read: 
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
```

### Steps to reproduce
Just add the file provided as a collision mask.

This PNG has been generated by ImageMagic's `convert` command.

If you load this file and export it as PNG with Gimp, Defold does not crash with the new file.
And the collision mask is generated too.

So it's a problem with PNG generated with ImageMagick. At least.

<hr/>
<table>
<tr><td>Build time</td><td>2021-09-09T20:26:36.042514</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>71d178069a8fa37a4a52d3b44b98bd7596197e4e</td></tr>
<tr><td>Defold engine sha</td><td>1f748d5b0a84e8b5c58bf747e4c48d153ef77a52</td></tr>
<tr><td>Defold version</td><td>1.2.186</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"d25bdba64c9c402b8923b36ce03327b6"'>d25bdba64c9c402b8923b36ce03327b6</a></td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce MX130/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 470.57.02</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.10.55-1-lts</td></tr>
<table>

![mask2](https://user-images.githubusercontent.com/7419045/133660436-a1666f4b-3a98-4e9b-a0c1-bbbc9073885a.png)

**Comment by britzl** [comment]
Thank you for the report. We've had some issues with indexed PNGs in the past and it is likely that this is the same kind of issue.

**Comment by AGulev** [comment]
works fine in 1.8.0
