### ISSUE TITLE
error on exit

### ISSUE THREAD

**Issue by aftgcc** [defold/defold#6064]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2021-01-16T10:47:07.405749</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>3d2d4932d02dabc7e57fd25fac275b0a6dc59158</td></tr>
<tr><td>Defold engine sha</td><td>af6a29c2a1e2545e2d033790089c606ac9f0bb7a</td></tr>
<tr><td>Defold version</td><td>1.2.178</td></tr>
<tr><td>GPU</td><td>AMD Radeon HD 6700 Series</td></tr>
<tr><td>GPU Driver</td><td>4.5.13399 Compatibility Profile Context 15.201.1151.1008</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
@aftgcc could you please describe the error you got? I'm not seeing any strack trace or similar in this report.

**Comment by aftgcc** [comment]
I tried to exit program, but could not do that, no way. It forced me to send report, but it did not helped. Then i just killed process...
No idea whai it was, i just changed some settings in project settings file.
Now it works correctly. And allow me to exit program, if i want

**Comment by britzl** [comment]
> Now it works correctly. And allow me to exit program, if i want

Ok, if you do figure out what was wrong then please let us know!
