### ISSUE TITLE
The editor is laggy on my system.

### ISSUE THREAD

**Issue by jjszaniszlo** [defold/defold#6065]
**Describe the bug (REQUIRED)**
The entire application runs very slow.  It uses 100% cpu despite only scrolling down the game.project file.

**To Reproduce (REQUIRED)**
1. Open Application
2. See that it runs very slow.

**Expected behavior (REQUIRED)**
1. Open Application
2. See that it runs smoothly.

**Defold version (REQUIRED):**
  - Version 1.2.187

**Platforms (REQUIRED):**
 - Platforms: Linux (Kernal: 5.14.2-1-MANJARO)
 - OS: Manjaro
 - Device: Computer
 - CPU: AMD Ryzen 9 5950x
 - GPU: AMD Radeon RX 6900 XT (Running bleeding edge mesa-git drivers)
 - MEMORY: 32GB

**Screenshots (OPTIONAL):**

![defold_laggy_issue_gif4](https://user-images.githubusercontent.com/40372435/134473950-d91cfa92-18ae-4510-b578-db5abb4c2a98.gif)

**Comment by jjszaniszlo** [comment]
Update: here are profiler measurements from just moving around in the main collection space. 

[Profiler Data.zip](https://github.com/defold/defold/files/7219385/Profiler.Data.zip)

**Comment by AGulev** [comment]
I think this issue fixed in the latest versions
if not feel free to open a new ticket
