### ISSUE TITLE
Defold engine v1.2.180 crashes on Android 7.1.2

### ISSUE THREAD

**Issue by Apetzu** [defold/defold#6071]
### Background:
I have a little bit rare setup in here. I have pretty old tablet, Asus Nexus 7 (2012 model), that I rooted and installed a custom ROM to it, [AOSP 7.1.2](https://forum.xda-developers.com/t/rom-nzh54d-2021-08-05-asus-nexus-7-2012-wifi-3g-f2fs-ext4-android-7-x-aosp.3467514/) (it's a pure Android 7.1.2 ROM that was unofficially ported to Nexus 7). It has been working really great for me so far but I found out that some Defold engine versions don't work on it. I understand that Defold might not primarily support these kind of OSes or devices but I think it's good to report this crash anyway. Maybe this problem exist in other Nougat devices too, who knows.

### Bug description:
If I open any Defold game or mobile development app (dmengine) that is build with Defold version 1.2.180 or greater, the app just crashes immediately after the launch. It really doesn't show anything else than a blank screen for a split second and then crashes. Version 1.2.179 or less works without any problems or crashes.

I tested multiple dmengine versions (1.2.178, 1.2.179, 1.2.180, 1.2.181, 1.2.187) and confirmed that 1.2.180 is the version when it starts to crash. I also checked adb logcat for all of these and attached all the logs to this post. Logs begin from the dmengine "Start proc" and ends to "_Process 3735 exited due to signal (11)_" (if there was a crash) or to "_handleCommand (main thread): APP_CMD_GAINED_FOCUS_" (if it worked fine).

End of the 1.2.180 log file had these lines:
```
09-27 19:55:02.441   507   557 W InputDispatcher: channel 'aed5010 com.defold.dmengine/com.dynamo.android.DefoldActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
09-27 19:55:02.441   507   557 E InputDispatcher: channel 'aed5010 com.defold.dmengine/com.dynamo.android.DefoldActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
09-27 19:55:02.442   507   549 E Sensors : HAL:ERR Full data packet was not read
09-27 19:55:02.442   507  1363 I ActivityManager: Process com.defold.dmengine (pid 3612) has died
09-27 19:55:02.442   507  1363 D ActivityManager: cleanUpApplicationRecord -- 3612
09-27 19:55:02.443   507  1363 W ActivityManager: Force removing ActivityRecord{67a599 u0 com.defold.dmengine/com.dynamo.android.DefoldActivity t9}: app died, no saved state
09-27 19:55:02.443   507  1373 I WindowManager: WIN DEATH: Window{aed5010 u0 com.defold.dmengine/com.dynamo.android.DefoldActivity}
09-27 19:55:02.443   507  1373 W InputDispatcher: Attempted to unregister already unregistered input channel 'aed5010 com.defold.dmengine/com.dynamo.android.DefoldActivity (server)'
09-27 19:55:02.522   188   188 I Zygote  : Process 3612 exited due to signal (11)
```

I also tested older (made before 1.2.180) and newer (made after 1.2.180) builds of my Defold game that I've been developing. The results were the same.

### Info:
Defold version: 1.2.180 (or greater)
Platform: Android 7.1.2, with AOSP 7.1.2 ROM
Device: Asus Nexus 7 (2012)

dmengine logs:
[Log for v1.2.178](https://github.com/defold/defold/files/7238641/1.2.178.txt)
[Log for v1.2.179](https://github.com/defold/defold/files/7238646/1.2.179.txt)
[Log for v1.2.180](https://github.com/defold/defold/files/7238647/1.2.180.txt)
[Log for v1.2.181](https://github.com/defold/defold/files/7238648/1.2.181.txt)
[Log for v1.2.187](https://github.com/defold/defold/files/7238649/1.2.187.txt)

**Comment by britzl** [comment]
1.2.180 was a pretty disruptive version with big changes, one being the introduction of OpenGL ES 3.0 with a fallback.

https://forum.defold.com/t/defold-1-2-180-has-been-released/67743

I wonder if this is related?

**Comment by britzl** [comment]
Old issue. Closing. Re-open if applicable to Defold 1.3.6 or later.
