### ISSUE TITLE
Add JNI thread attacher to Defold SDK

### ISSUE THREAD

**Issue by britzl** [defold/defold#6081]
**Is your feature request related to a problem? Please describe (REQUIRED):**
It is important to detach a thread from the JNI to not leak any resources or lock up the system. Using a ThreadAttacher struct with a constructor to attach a thread to the JNI and a destructor to detach the thread would guarantee that the thread is detached.

**Describe the solution you'd like (REQUIRED):**
The Defold SDK should provide a thread attach/detach mechanism to help extension creators detach from the JNI properly

**Comment by AGulev** [comment]
Should we also add logic for loading classes like this https://github.com/defold/extension-admob/blob/5bf76e22dc09309b2559d30f9914b827f18ee373/extension-admob/src/admob_jni.h#L26 ?

**Comment by JCash** [comment]
I think the class loading idea is very good too, but it requires more care to get proper and nice.
I propose we do that as a second task, since the RAII thing is currently the more important part, and also easy to do.

**Comment by JCash** [comment]
Another note with the class loading issue, is that we want a clear cut use case for it.
What are the problems that we are trying to solve?
E.g. when looking at the android jni class loading api, there are stuff like "Ljava/lang/ClassType" that we cannot map to C++ anyways, which is probably why they have that string-style approach.
