### ISSUE TITLE
DEFOLD INPUT => Cursor should teleport to mouse position when clicking anywhere (super important)

### ISSUE THREAD

**Issue by Ragetto** [defold/defold#6084]
https://forum.defold.com/t/rendercam-defold-input-weird-cursor-position-when-scrolling/69387/7
_"This is something the cursor script should support. Please create a ticket in GitHub!"_ (Britzl)

This feature completion is definitely something anyone working on a mobile game would (absolutely) need :) . . .

---------------------------------------------------------

**Is your feature request related to a problem? Please describe (REQUIRED):**
Defold Input extension (by Britzl?) => Currently the cursor can't teleport where the user clicks, which is a huge problem for mobile games (since there is no draggable cursor on mobile, we need to move it instantly where the user taps the screen)

When passing the "mouse position" to the cursor from the "if pressed" input, nothing happens.

---------------------------------------------------------

**Describe the solution you'd like (REQUIRED):**
It should be possible to pass the "mouse position" message from the "if pressed" input (or any other solution).

So the cursor would instantly teleport to the object and would make the extension useful for mobile game developers.

---------------------------------------------------------

**Additional context (OPTIONAL):**
Here is the minimal version of my current project:
https://github.com/Ragetto/20211002_-PUBLIC-_defold_input_cursor

**Comment by britzl** [comment]
You've created the issue in the wrong repository! The issue should be created in the defold-input repo as it relates to that utility module and not the Defold game engine.

https://github.com/britzl/defold-input/issues
