### ISSUE TITLE
Variable DT As Independent Option

### ISSUE THREAD

**Issue by 11clock** [defold/defold#6094]
**Is your feature request related to a problem? Please describe (REQUIRED):**
Currently dt being constant or variable depends on whether vsync is on or off, as well as if your game's framerate is uncapped. This means that you cannot have variable dt in a game that uses vsync or a capped framerate, which will result in your game physically slowing down if its framerate is low or experiences lag.

**Describe the solution you'd like (REQUIRED):**
Make variable dt a separate, independent option from vsync and frame cap. With this option checked, dt will be based on time since the last frame (variable) regardless of what vsync and frame cap are set to. That way you can have a game that both uses vsync (to avoid tearing issues) or capped framerate, and maintains its speed when under stress by increasing delta time appropriately.

**Describe alternatives you've considered (REQUIRED):**
Another possibility is introducing two separate update loops, one variable and one fixed. Of course this would require major revisions to the core of the engine.

**Comment by britzl** [comment]
Please help us test! https://forum.defold.com/t/game-physics-time-steps-beta-testing/70539
