### ISSUE TITLE
Liveupdate problem during upgrade when game built with different engine version

### ISSUE THREAD

**Issue by alexandrecurtelin** [defold/defold#6103]
1. Build app that uses liveupdate, using Defold `1.2.182`
2. Install app on device and download the liveupdate
3. Build app using Defold `1.2.185`
4. Install app on device as an update (don't clear data before installing it).
5. App crashes at opening with following stack trace:

```
INFO:ENGINE: Loading data from: dmanif:game.dmanifest
 INFO:LIVEUPDATE: Found /data/user/0/com.mygame/files/liveupdate.ref
 INFO:LIVEUPDATE: Found zip archive reference to /data/user/0/com.mygame/files/archive.zip
 ERROR:RESOURCE: Failed to parse Manifest data (2)
```

**Comment by AGulev** [comment]
should work using new live update flow
