### ISSUE TITLE
dt = 1 if GPU VSync is turned off and FPS is ultra high

### ISSUE THREAD

**Issue by aglitchman** [defold/defold#6107]
**Describe the bug + How to Reproduce**
I like to develop games with Defold with the following settings:
![image](https://user-images.githubusercontent.com/193258/137756184-fea5b2d8-1f99-4b86-9559-c1a965e3d37e.png)

The combination enables "variable dt" mode.

I found that the engine **sets the "dt" variable equals to 1** if:
1. A user turned off VSync for all applications, i.e.
![image](https://user-images.githubusercontent.com/193258/137760122-b287a7ed-95e5-4df5-97cd-580461322451.png)
2. Game's FPS is more than 1000.

The result is that everything animated/moved according to the dt=1, i.e. animations end almost instantly. Take a look at the video _(green-coloured text is FPS)_:

https://user-images.githubusercontent.com/193258/137761885-13af3a89-eca0-487b-9ea3-513c4376d4e2.mp4

**Expected behavior (REQUIRED)**
The game should be able to run well under any conditions and user system/GPU settings.

**Defold version (REQUIRED):**
  - Version: 1.2.188

**Platforms (REQUIRED):**
 - Platforms: Windows
 - GPU: Radeon 6600 XT

**Minimal repro case project (OPTIONAL):**
[issue_vsync_off_high_dt.zip](https://github.com/defold/defold/files/7366398/issue_vsync_off_high_dt.zip)

**Logs (OPTIONAL):**
![image](https://user-images.githubusercontent.com/193258/137760671-23f1e16c-213c-4b4a-a1ee-d0753a7bfc6a.png)

**Comment by subsoap** [comment]
Due to this, we are forced to calculate our own dt in scripts based on time differences of socket.gettime() between updates where it's crucial to be based on real world time and not what is reported when this breaks.

**Comment by britzl** [comment]
Please help us test!

https://forum.defold.com/t/game-physics-time-steps-beta-testing/70539
