### ISSUE TITLE
Possibility to set particle pivot point in emitter.

### ISSUE THREAD

**Issue by AGulev** [defold/defold#6126]
**Is your feature request related to a problem? Please describe (REQUIRED):**
It will be useful to have pivot point for sprite (particle) in emitter

**Describe the solution you'd like (REQUIRED):**
![image](https://user-images.githubusercontent.com/2209596/138465775-dec56231-e375-419a-8c61-19da3e3fa414.png)
or vector3 option
here:
![image](https://user-images.githubusercontent.com/2209596/138465802-e9cf1363-54b7-451c-951d-e46ca02309bb.png)
(for `Animation` sprite)

**Describe alternatives you've considered (REQUIRED):**
using of many sprite duplicates with a lot of alpha

**Additional context (OPTIONAL):**

https://user-images.githubusercontent.com/2209596/138465981-7e591954-1a31-4899-ac4c-ec3ab9f071d8.mp4

**Comment by JCash** [comment]
The current solution has a backwards compatibility issue that needs to be fixed.
