### ISSUE TITLE
Problem when I add module to my project

### ISSUE THREAD

**Issue by JerryMacNow** [defold/defold#6128]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2021-10-18T16:55:27.814954</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>055196fdf29694c06a1000e26217167ac249ba3f</td></tr>
<tr><td>Defold engine sha</td><td>6bfeea3b13d7b8920483ea2cba9c181a8650b84d</td></tr>
<tr><td>Defold version</td><td>1.2.188</td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 5500</td></tr>
<tr><td>GPU Driver</td><td>4.4.0 - Build 20.19.15.5063</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
No additional information provided. Closing.
