### ISSUE TITLE
Discrepancy between editor/bob when creating tilemap texture

### ISSUE THREAD

**Issue by JCash** [defold/defold#6134]
Forum post:
https://forum.defold.com/t/tilemaps-html5-tiles-transparent-background-replaced-by-black-background/69527

**Comment by AGulev** [comment]
is this issue outdated? 
<img width="1275" alt="image" src="https://github.com/defold/defold/assets/2209596/fdbf16af-610d-41a9-a929-9966eb39c3be">

I can't reproduce it in 1.6.2

**Comment by AGulev** [comment]
@britzl can you repo it?

**Comment by britzl** [comment]
Most likely outdated yes.
