### ISSUE TITLE
The macOS build window title has wrong encoding

### ISSUE THREAD

**Issue by astrochili** [defold/defold#6138]
**To Reproduce:**
1. Set the project name with Cyrillic symbols "День Кота"
2. Build for macOS
3. Look at the window title

**Expected behavior**
The title is "День Кота"

  - Defold 1.2.186
  - macOS Big Sur 11.5.2

**Screenshots (OPTIONAL):**
![aa50d4029351ccba21869f1dfde68f53e6a170bc](https://user-images.githubusercontent.com/4752473/138936604-c3167f73-316e-4798-95c6-693d3a272978.png)

**Additional context (OPTIONAL):**
`NSISOLatin1StringEncoding` [here](https://github.com/defold/defold/blob/dev/engine/glfw/lib/cocoa/cocoa_window.m#L817-L818) definitely does not allow non-Latin characters to pass.
What if we try `NSUTF8StringEncoding ` there?

**Comment by britzl** [comment]
Yep, NSUTF8StringEncoding works!

![Screenshot 2021-11-03 at 23 27 42](https://user-images.githubusercontent.com/1300688/140207386-461c304f-1d0f-48f4-b5d1-dc1da06d3c29.png)
