### ISSUE TITLE
The file '/defold-spine/assets/spine.material' could not be found.

### ISSUE THREAD

**Issue by Prog-Maker** [defold/defold#6139]
Defold ver. 1.2.188 
dowload sample runner but - not build with error 
/hero/hero.go The file '/defold-spine/assets/spine.material' could not be found.
And I wanted to follow the tutorial - Runner - but I can't find a point Spine Scene

**Comment by britzl** [comment]
I've updated the sample to include the Spine extension:

https://github.com/defold/sample-runner/commit/814d8a5596bc080f49e8da621619eeb6a946ca40
