### ISSUE TITLE
Black screen on Android when launching the game after posting "exit 0".

### ISSUE THREAD

**Issue by astrochili** [defold/defold#6141]
The game displays a black screen when started after exit with `msg.post("@system:", "exit", { code = 0 })`

**To Reproduce (REQUIRED)**
Reproduced only on Honor 20 Pro. Few other devices are fine.

1. Call `msg.post("@system:", "exit", { code = 0 })` in `on_input(...)` with BACK key.
2. Open the app again.

**Expected behavior (REQUIRED)**
The game starts.

**Defold version (REQUIRED):**
  - Defold 1.2.186

**Platforms (REQUIRED):**
 - Platforms: Android
 - OS: Android 10
 - Device: Honor 20 Pro

**Logs (OPTIONAL):**
[logs.txt](https://github.com/defold/defold/files/7428796/logs.txt)

**Workaround (OPTIONAL):**
Use `os.exit(0)`, works perfectly.

**Comment by astrochili** [comment]
I'm back. If I wait 30 seconds, then the application starts without a black screen in normal mode.

**Comment by AGulev** [comment]
hmm, it's interesting. Can you try turn on "Show ALL ANR" option in Developer settings and check if you have an ANR when shut down the app?

Also it would be nice if you can send us a minimal repo case of the issue. We will try it on all our phones if we can reproduce it.

**Comment by britzl** [comment]
@astrochili We've made some changes to Android shutdown code in 1.2.189. We believe that these changes have solved the problem you're experiencing. Please let us know if 1.2.189 solved the issue for you.

**Comment by astrochili** [comment]
Thanks guys, the update really fixes this bug.
