### ISSUE TITLE
I would appreciate if we can have a Terminal tab in the editor beside the console

### ISSUE THREAD

**Issue by LimitlessDonald** [defold/defold#6143]
**Is your feature request related to a problem? Please describe (REQUIRED):**
Not necessarily a problem, but I am building a game and working with git is a bit inconvenient , it would be great to have a terminal tab(Command line for Windows) in the editor so I can quickly run git commands or any commands for that matter . 

**Describe the solution you'd like (REQUIRED):**
It actually quite self explanatory from above

**Describe alternatives you've considered (REQUIRED):**
I currently use terminal , but switching back and forth from terminal back to Defold just to run a small git command can be cumbersome 

**Additional context (OPTIONAL):**
Already described

Thanks for this awesome software guys !!

**Comment by LimitlessDonald** [comment]
@JCash , just wanted to check in if there is any progress on this. Thanks for your awesome work guys !

**Comment by britzl** [comment]
@LimitlessDonald no progress has been made on this yet.

**Comment by LimitlessDonald** [comment]
Ok, thanks @britzl

**Comment by britzl** [comment]
This is outside the scope of features the editor is supposed to solve. We will not implement a built-in terminal in the editor.
