### ISSUE TITLE
Filter for console in the Editor

### ISSUE THREAD

**Issue by AGulev** [defold/defold#6145]
**Is your feature request related to a problem? Please describe (REQUIRED):**
Big projects usually have a lot of logs. 
It would be useful to have not only search for console but also filter, to  show only need entries if filter activated (has a value in it)

**Comment by dri-richard** [comment]
It would be great to have toggles for each logging level/type, e.g. INFO / DEBUG:SCRIPT / WARNING.

Sometimes I want to see everything, sometimes I only want to see errors.

The configuration of these would ideally persist to disk.

**Comment by matgis** [comment]
Somewhat related: https://github.com/defold/defold/issues/7536
