### ISSUE TITLE
Checking character in font file

### ISSUE THREAD

**Issue by kornyushin** [defold/defold#6157]
**Is your feature request related to a problem? Please describe (REQUIRED):**
Some fonts do not support all characters (for example, extended Latin or Cyrillic) and some characters are not displayed in the text

**Describe the solution you'd like (REQUIRED):**
Would like to be able to check for the presence of a character in a font

**Comment by britzl** [comment]
Perhaps one of these APIs (now that we have `resource.get_font_metrics()`):

```
-- get all glyphs in a font (list of unicode characters?)
resource.get_font_glyphs(font)

-- check if font has all the glyphs to present in the text
resource.has_font_glyphs(font, text)
```

**Comment by AGulev** [comment]
```
-- check if font has all the glyphs to present in the text
resource.has_font_glyphs(font, text)
```
maybe it should return unsupported glyph? Something like:

```
local supproted, unsupportenglyphs = resource.has_font_glyphs(font, text) -- false, {"D","R","K"}
```
or something like that?

**Comment by britzl** [comment]
Yes, maybe. The question is what the purpose of this function is? @kornyushin what are you going to use this function for?

**Comment by kornyushin** [comment]
My task is: I have list of words and need to show only words with supported characters. If it hard to add this feature , I'll try to find another way for solve it.

**Comment by britzl** [comment]
If you have control over the list of words then maybe you could remove words with characters not supported by your font? Or get a better font! :-)

**Comment by kornyushin** [comment]
yes, it's good solution for latin languages, but big problem for Japaneze, Korean or Chinese, which contains 1 mln words and thousand of hieroglyphs )

**Comment by kornyushin** [comment]
I found solution for my case. Split text to characters , and use set_text for label, after that check `label.get_text_metrics("#label")).width` 
If symbol missing width = 0
So you can set priority for this feature to low or postpone it

**Comment by britzl** [comment]
@kornyushin ok, good to hear. I'm closing this feature request then!
