### ISSUE TITLE
Editor's java crashes on Monterey.

### ISSUE THREAD

**Issue by dapetcu21** [defold/defold#6162]
It's really hard to pinpoint when Java crashes, since it tends to crash when trying to do just about anything or just by waiting. It's not always a reliable crash, but it will definitely crash in about 30 seconds of use.

Here's a bunch of crash logs:

[defold_crashes.zip](https://github.com/defold/defold/files/7469328/defold_crashes.zip)

Editor 1.2.188 a2b39b036f5870688356cc9492763e9f31ab8053
Engine 1.2.188  6bfeea3b13d7b8920483ea2cba9c181a8650b84d

macOS 12.0.1
Intel MacBook Pro (13-inch, 2017, Four Thunderbolt 3 Ports)
Intel Iris Plus Graphics 650

**Comment by dapetcu21** [comment]
Possibly related to #6152?

**Comment by dapetcu21** [comment]
I tried replacing the bundled Java with this: https://github.com/JetBrains/JetBrainsRuntime

Unfortunately it now crashes with `*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'` which was a warning before, seemingly originating in jogl?:

```
2021-11-05 10:18:37.988 Defold[69589:1948577] WARNING: NSWindow drag regions should only be invalidated on the Main Thread! This will throw an exception in the future. Called from (
	0   AppKit                              0x00007ff81cc75df0 -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 352
	1   AppKit                              0x00007ff81cc61a56 -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1287
	2   AppKit                              0x00007ff81cc61549 -[NSWindow initWithContentRect:styleMask:backing:defer:] + 42
	3   libnativewindow_macosx.jnilib       0x0000000138a113fe Java_jogamp_nativewindow_macosx_OSXUtil_CreateNSWindow0 + 398
	4   ???                                 0x000000010a263950 0x0 + 4465244496
)
```

**Comment by dapetcu21** [comment]
Referencing  #5281 here

**Comment by thejustinwalsh** [comment]
Is there a project attached that causes the crash? I am on Monterey 12.0.1 on an M1 Macbook Air, and have had a project open for several days without a crash.

**Comment by dapetcu21** [comment]
It crashes for me on most projects usually within 1-2 minutes. I have an Intel Macbook though. The most reliable way to repro is to close a running game.

**Comment by thejustinwalsh** [comment]
> It crashes for me on most projects usually within 1-2 minutes (including new projects). I have an Intel Macbook though. The most reliable way to repro is to close a running game.

Oh, I missed that part about running on a real intel chip. Ironic that intel emulation mode on an M1 works without issue.

**Comment by britzl** [comment]
@dapetcu21 would you mind trying this editor: http://d.defold.com/archive/editor-dev/dba38d19bbab0d9e2431dcad1f174b2d04cbdb4e/editor-dev/editor2/Defold-x86_64-darwin.dmg

**Comment by britzl** [comment]
Closed via https://github.com/defold/defold/pull/6194
