### ISSUE TITLE
Pre-/post-build hooks for editor

### ISSUE THREAD

**Issue by ekharkunov-ms** [defold/defold#6164]
**Is your feature request related to a problem? Please describe (REQUIRED):**
In our project we have pre-built step with resource generation (export configs from sheets, localization, atlases, etc.). So we start shell script before project building to generate some assets/configs/etc. It would be cool if we can start shell script with asset generation from editor hook script.

**Describe the solution you'd like (REQUIRED):**
Present pre-/post- build hooks where we can generate all necessary assets before building and do some cleanup after building.

**Describe alternatives you've considered (REQUIRED):**

**Additional context (OPTIONAL):**
Here is a sample project where **custom.sh** generate **main/test.lua** with test function in **_on_build_started_** hook. But editor can't build project because **main/test.lua** doesn't exist.
[sample-project.zip](https://github.com/defold/defold/files/7473414/sample-project.zip)

**Comment by JCash** [comment]
Note for the one picking up this issue: I don't think we need to add new build hooks, but rather fix the issue with the current one. `on_build_started` and `on_build_finished` should the the two steps that wraps the build process.
