### ISSUE TITLE
The comma symbol has different position in the editor build and the bundle 

### ISSUE THREAD

**Issue by astrochili** [defold/defold#6169]
**Describe the bug (REQUIRED)**
Some fonts renders some symbols renders incorrectly in the bob or bundle build but correctly in the editor build. It does not depend on characters, language or texture compression. This causes the comma to sometimes clump with the previous character.

**To Reproduce (REQUIRED)**
1. Use [Balsamiq](https://fonts.google.com/specimen/Balsamiq+Sans) regular font with 15th size in your gui.
2. Build in the Editor.
3. Bundle in the Editor or build with Bob.
4. Look at the comma and find the difference.

**Expected behavior (REQUIRED)**
The comma symbol position is the same as in the Editor build.

**Defold version (REQUIRED):**
1.2.188

**Platforms (REQUIRED):**
MacOS 11.5.2, iOS 15.
Not tested on the other platforms.

**Minimal repro case project (OPTIONAL):**
[repro-comma-bug.zip](https://github.com/defold/defold/files/7492023/repro-comma-bug.zip)

**Workaround (OPTIONAL):**
Increase the size of the font to 2x and then scale the labels to x0.5.

**Screenshots (OPTIONAL):**
Try to overlay these two screenshots and it becomes clear that it is the comma shifting inside its container:

![Screenshot 2021-11-07 at 12 29 14](https://user-images.githubusercontent.com/4752473/140639747-af9a9ed3-6720-4eb3-8b97-d4687322c159.png)
![Screenshot 2021-11-07 at 12 29 39](https://user-images.githubusercontent.com/4752473/140639749-51bcb141-1b0d-4ca9-b120-e246e2aaa63c.png)

**Comment by britzl** [comment]
We need to migrate the editor font compiler to use the same code path as in bob.

**Comment by AGulev** [comment]
fixed in 1.4.4 
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/2209596/227776064-f3960f11-04f8-463c-84b6-d55960b2b5fa.png">
