### ISSUE TITLE
Make math.random developer-friendly

### ISSUE THREAD

**Issue by aglitchman** [defold/defold#6170]
**Is your feature request related to a problem? Please describe (REQUIRED):**
Randomness and initialization of `math.random` is the most popular question in the Defold chat in Telegram. 
Every time newcomers get the answers like:
1. Call [`math.random` three times](http://lua-users.org/wiki/MathLibraryTutorial) after `math.randomseed` to get real random values (on Windows at least). It sounds like black magic 😄 
2. Use https://github.com/selimanac/defold-random or https://github.com/indiesoftby/defold-splitmix64
etc.

I do think that Defold's `math.random` should be developer-friendly out of the box. 

**Describe the solution you'd like (REQUIRED):**
Substitute Lua's `math.random` + `math.randomseed` with any simple PRNG (xoroshiro128+, [splitmix64](https://github.com/indiesoftby/defold-splitmix64/blob/main/splitmix64/src/main.cpp), there are lots!) to make it cross-platform and to not rely on weird OS implementations.

**Comment by astrochili** [comment]
Don't forget to add the spice `os.clock() * 1000000` to the to `math.randomseed()` before calling `math.random()` 3 times 😉

**Comment by britzl** [comment]
Yes, this could be improved upon for sure! We want a PRNG that is small and fast. Which would you recommend?

**Comment by dri-richard** [comment]
A couple of things that make a PRNG dev-friendly from my pov:
1. Allow the seed (or state) to be both settable and gettable so that I can store it in saved data (e.g. to prevent users getting better items in a treasure chest by constantly reloading their game)
2. Allow multiple instances of a PRNG to be created so that I can have multiple sequences of random numbers that don't affect each other. Can be simulated with requirement (1) by saving the current seed and restoring it after use.

**Comment by subsoap** [comment]
We're using PCG in our projects now ( https://github.com/selimanac/defold-random this one)

Values are from win32 builds zipped

2.06 MB (2,168,513 bytes) without PCG (no other NEs)
1.97 MB (2,072,926 bytes) with PCG ??? lol, there must be some other optimizations the NE version gets
1.98 MB (2,079,257 bytes) with DefOS only
1.98 MB (2,081,662 bytes) with PCG + DefOS

So this version of PCG adds ~2,405 bytes on win32 zipped

**Comment by aglitchman** [comment]
> Yes, this could be improved upon for sure! We want a PRNG that is small and fast. Which would you recommend?

To be honest, I don't know. It should be simple just to ensure that `math.random` is simple to use, and it works without a triple time function call to initialize it.

The https://www.pcg-random.org/ page has a great comparison table.

**Comment by AGulev** [comment]
related https://github.com/defold/defold/issues/3753
