### ISSUE TITLE
I tried to make it go from game.collection to main menu collection with a proxy and this happened

### ISSUE THREAD

**Issue by Nekele4** [defold/defold#6173]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2021-10-18T16:55:27.814954</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>055196fdf29694c06a1000e26217167ac249ba3f</td></tr>
<tr><td>Defold engine sha</td><td>6bfeea3b13d7b8920483ea2cba9c181a8650b84d</td></tr>
<tr><td>Defold version</td><td>1.2.188</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"fadde66dafdf4e56bf4d7de13ee950e9"'>fadde66dafdf4e56bf4d7de13ee950e9</a></td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce RTX 2060 SUPER/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 466.77</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
```
internal.node$mark_in_production.invokeStatic.class java.lang.AssertionError: Assert failed: Cycle detected on node type editor.collection/CollectionNode and output :build-targets
(not (contains? (:in-production evaluation-context) [node-id label]))
    at internal.node$mark_in_production.invokeStatic(node.clj:1320)
```

You have your game collection referencing the menu collection through a collection proxy and vice versa. This will not work as you create a dependency loop/cycle.

The recommendation is to have a loader/main collection with proxies to both the game and menu and let this loader collection handle loading and unloading of the collections. See: https://defold.com/examples/collection/proxy/
