### ISSUE TITLE
SberBox: ANR when remote connected

### ISSUE THREAD

**Issue by Lampogolovii** [defold/defold#6174]
Description:
Empty application crashes with ANR when remote got connected to the SberBox device.

Remote:
<img width="350" alt="Screenshot 2021-11-10 at 15 22 33" src="https://user-images.githubusercontent.com/23137022/141112710-1387308c-4803-4e1f-9901-43503ff94a72.jpg">

ANR:
<img width="350" alt="Screenshot 2021-11-10 at 15 22 33" src="https://user-images.githubusercontent.com/23137022/141112730-cf927e87-cf26-4f83-8658-a8bfd8b869e7.jpg">

How to Reproduce:
1. Disconnect SberBox from any energy source (IMPORTANT: from this and until 5th step don't use SberBox remote)
2. Connect SberBox to computer
3. Upload to SberBox via adb empty application
4. Run empty application via adb 
5. Press any button on SberBox remote 
6. App crashes with ANR

Log: [log_crash_1110_1.txt](https://github.com/defold/defold/files/7512661/log_crash_1110_1.txt)
I'm using Defold 1.2.186

Workaround:
If remote is connected before application started (just press any buttons after SberBox loaded) - then everything works fine.

**Comment by AGulev** [comment]
my logs 
[logcat.txt](https://github.com/defold/defold/files/8082111/logcat.txt)
[pidcat.txt](https://github.com/defold/defold/files/8082113/pidcat.txt)

**Comment by AGulev** [comment]
The most important part in your log is 
```
11-10 15:02:37.307  3246  3476 I ActivityManager: Config changes=60 {1.0 ?mcc?mnc [ru_RU] ldltr sw540dp w960dp h516dp 320dpi lrg long land television -touch -keyb/v/h dpad/v winConfig={ mBounds=Rect(0, 0 - 0, 0) mAppBounds=Rect(0, 0 - 1920, 1080) mWindowingMode=fullscreen mActivityType=undefined} s.5}
11-10 15:02:37.321  3246  3476 I ActivityManager: Override config changes=60 {1.0 ?mcc?mnc [ru_RU] ldltr sw540dp w960dp h516dp 320dpi lrg long land television -touch -keyb/v/h dpad/v winConfig={ mBounds=Rect(0, 0 - 1920, 1080) mAppBounds=Rect(0, 0 - 1920, 1080) mWindowingMode=fullscreen mActivityType=undefined} s.5} for displayId=0
```

 it's so easy to miss that part.

This lines mean that config changed and Android OS has a handling mechanism for that https://developer.android.com/guide/topics/resources/runtime-changes

But when such a change occurs, Android restarts the running Activity except the config changes specified as manually handled by developer in `AndroidManifest.xml` [android:configChanges](https://developer.android.com/guide/topics/manifest/activity-element#config)

So in this particular case it was 

>"navigation" | The navigation type (trackball/dpad) has changed. (This should never normally happen.)

We are going to fix that in the engine, but you can fix that in your game yourself. Just open `AndroidManifest.xml` find `android:configChanges="keyboardHidden|orientation|screenSize"`
and replace with
`android:configChanges="keyboardHidden|orientation|screenSize|navigation"`

That will fix your problem.

Thank you for the report!
