### ISSUE TITLE
Add new `MyExtAppCreate` and `MyExtAppDestroy` Extension lifecycle functions

### ISSUE THREAD

**Issue by AGulev** [defold/defold#6177]
**Is your feature request related to a problem? Please describe (REQUIRED):**
In some cases we need hooks to create things once during the whole app lifecycle. It would be nice to have such hooks to avoid using static scope for such variables (for example message queue and mutex)

**Describe alternatives you've considered (REQUIRED):**
For now it's possible to use static scope for such variables.

**Comment by JCash** [comment]
While it would possible to add these functions, we haven't had the real need for it internally.
Currently, we use the regular C++ global scope constructors/destructors to handle these scenarios, and they work well enough.

Also, given how the OS may shutdown the app without fully calling the shutdown procedures, we cannot guarantuee that a function such as MyExtAppDestroy will be called, which would having such an api quite awkward to support.

As such, we'll close this ticket for now.
