### ISSUE TITLE
An option to hide iOS home indicator 

### ISSUE THREAD

**Issue by romanTrufanov** [defold/defold#6184]
**Problem**

hi Defold Team! 
 
we want to hide home indicator for some iOS devices
![image](https://user-images.githubusercontent.com/79691083/141784089-aa859d25-f4ad-468a-9d3e-6270d5faff62.png)

cause we have issues with some game UI elements to show

**Solution**

solution is - override the method **prefersHomeIndicatorAutoHidden** for **UIViewController**
here is the guide - https://medium.com/the-traveled-ios-developers-guide/iphone-x-dealing-with-home-indicator-2e8e47f5647f

it would be really nice to have it as a flag for **game.project**

**Comment by AGulev** [comment]
@romanTrufanov Did you check how it works? Some game where it's implemented?
<img width="740" alt="image" src="https://user-images.githubusercontent.com/2209596/143478273-a6deafe9-f94c-4c11-9106-e556d6f16021.png">

I tried to implement it and I see that iOS shows indicator after every tap/swipe or any interaction. Accordint to blogpost you sent:
>Typically you don’t want to hide the home indicator unless you’ve got a passive viewing experience (i.e. videos, photo slideshow, etc.).

**Comment by AGulev** [comment]
Won't fix.
It fits only for passive content.

**Comment by gianmichelemariani** [comment]
As much as I agree about the functionality, so not having controls near it, I would say that it does ruin the experience from a visual point of view. There's so much work done in creating minimalistic and clean experiences that the home indicator always visible tends to ruin.
