### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by drmar** [defold/defold#6188]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2021-11-16T09:35:58.342639</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>a6a6ecc2e67cd37a883391186b428d2acef0967e</td></tr>
<tr><td>Defold engine sha</td><td>8894457f85514465165401c664f5ba79a7730804</td></tr>
<tr><td>Defold version</td><td>1.2.189</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"517dd11a5a9343b1ba7628347976d0fe"'>517dd11a5a9343b1ba7628347976d0fe</a></td></tr>
<tr><td>GPU</td><td>Apple M1</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 76.1</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.16</td></tr>
<table>

**Comment by drmar** [comment]
I believe the error occurred when I added to a game object a factory.

**Comment by britzl** [comment]
```
internal.node$mark_in_production.invokeStatic.class java.lang.AssertionError: Assert failed: Cycle detected on node type editor.factory/FactoryNode and output :build-targets
(not (contains? (:in-production evaluation-context) [node-id label]))
    at internal.node$mark_in_production.invokeStatic(node.clj:1320)
```

"Cycle detected on node" - This means that the game object you added has a reference to the factory itself, causing an infinite loop or circular dependency.

You need to make sure the game object you create with the factory doesn't reference the factory.
