### ISSUE TITLE
Mipmaps generation and default option for mipmaps in texture profile

### ISSUE THREAD

**Issue by JCash** [defold/defold#6191]
Building atlases take up a large amount of time.
Step one is to gather some metrics:

Here is the atlas of extension-spine. It contains 40 images, and results in a 1kx1k texture.
```
AtlasBuilder.build assets/spineboy/spineboy.atlas
AtlasUtil.generateTextureSet took 116 ms
  of which loadImages took 80 ms for 40 images
  of which meta data took 0 ms
AtlasBuilder.build took 584 ms
  of which generateTextureSet took 116 ms
  of which generate took 459 ms
compress = false
 ```
 
The actual atlas packing (the rectangles) takes 116-80=36ms.
 
In my own experiments using a bin packer (C++), the whole atlas ends up the same size (1kx1k) but takes ~40ms, from start to finish, including the IO of reading the images, and writing the output.

So, it's not unfair to expect a faster build here when the time difference is an order of magnitude larger.

Sorting by time, the next step would be to look at the `TextureGenerator.generate`
Step three is to look at the IO here for the `AtlasUtil.loadImages`

**Comment by JCash** [comment]
A [PR](https://github.com/defold/defold/pull/6192) for 3)

**Comment by JCash** [comment]
Today, in the editor, when changing the animation properties, the entire atlas is regenerated for no good reason.
To avoid this, the atlas outputs should be separated further:

* layout
* animation data
* texture

Note: The layout is dependent on the image in two ways: 1) the size and 2) the hull of the texels

The editor should be able to recalculate either the layout or the animation data separately.
And the texture should only be regenerated is the layout changes

**Comment by britzl** [comment]
Time boxed investigation!

**Comment by AGulev** [comment]
@JCash 
We spend most of the time for TEXC_Create 10% + TEXC_Encode 90%
and it's not like we can change a lot about it. 
For `TEXC_Create` it is `ABGR8888ToRGBA8888` function
for `TEXC_Encode ` it is basis encoding


>The built in texture profiles generates mipmaps by default. perhaps we should skip that?

Should we change `default.texture_profile` in `builtins`?

**Comment by AGulev** [comment]
Also BasisU 1.16 released https://github.com/BinomialLLC/basis_universal/releases/tag/1.16
it supports OpenCL, interesting if it helps with uastc, not only ecs1s https://www.khronos.org/news/permalink/binomials-gpu-texture-interchange-encoder-now-supports-opencl-v1.2-on-osx-windows-linux

**Comment by AGulev** [comment]
We are done with everything which isn't related to the mipmaps, so I renamed the task. 

We need to decide if we want turn mipmaps off by default and if we want to take a look into some other lib for mipmaps generation
