### ISSUE TITLE
Reduce size of Lua code resources (LuaJit bytecode)

### ISSUE THREAD

**Issue by AGulev** [defold/defold#6193]
**Task (REQUIRED):**
We include 2 versions of luajit bytecode in bundle, but it seems that the difference between them just a few bytes.
It would be nice to reduce size of luajit bytecode to be able reduce lua resources build size twice and also be able to use lua data tables instead of json.

https://github.com/LuaJIT/LuaJIT/issues/725

**Expected outcome (REQUIRED):**
According to @ekharkunov-ms parsing of 1mb json (using cjson lib) is 8 times slower that using of the same data in lua-data table, but for now it twice as bigger.

**Comment by JCash** [comment]
Hmm, the more I think about it I'm wondering how much space it really takes.
Sure, for an unpacked data, it's twice as much, but in the archive, I believe we compress the data (LZ4) (unless the vanilla Lua override is specified).
As for the actual runtime memory consumption, I think it's less of an issue? The focus here is on the bundle size, right?

**Comment by AGulev** [comment]
@JCash it's a good question. @ekharkunov-ms how did you compare sizes?

**Comment by ekharkunov-ms** [comment]
@JCash @AGulev I took result size from build report (--build-report-html). I compared luac vs json. I didn't measure memory consumption in runtime because I got two similiar lua table. I think when we parse json we get some garbage which will be collected later by GC.

**Comment by britzl** [comment]
Here's the results from a sample Lua file containing configuration data:

* Original: 2.3MB
* Uncompressed bytecode 32+64bit: 5.64MB
* Compressed bytecode 32+64bit: 1.04MB
* Uncompressed bytecode 64bit: 2.81MB
* Compressed bytecode 64bit: 0.53MB

Here's another with from a Lua module containing generated network code (nakama.lua from heeroiclabs/nakama.lua):

* Original: 188kb
* Uncompressed bytecode 32+64bit: 168kb
* Compressed bytecode 32+64bit: 27kb
* Uncompressed bytecode 64bit: 84kb
* Compressed bytecode 64bit: 14.96kb

**Comment by AGulev** [comment]
>Original: 2.3MB

Could you please convert it to json and compare?

**Comment by britzl** [comment]
> Could you please convert it to json and compare?

Original JSON: 2.1MB
Compressed JSON: 0.56MB

**Comment by britzl** [comment]
I'm currently working on a solution where a delta between 32 and 64 bit bytecode is generated and stored. The delta is then applied to the bytecode if needed. Some examples of numbers:

| file                                  | original | delta   | ratio    |
|---------------------------------------|----------|---------|----------|
| builtins/render/default.render_script | 3796     | 562     | 0,148051 |
| main/main.script                      | 504      | 24      | 0,047619 |
| builtins/scripts/socket.lua           | 3167     | 510     | 0,161036 |
| bigfile.lua                           | 2947853  | 1402617 | 0,475810 |
| builtins/scripts/debugger.lua         | 562      | 40      | 0,071174 |
| builtins/scripts/mobdebug.lua         | 49275    | 7088    | 0,143846 |
| builtins/scripts/edn.lua              | 4080     | 508     | 0,124510 |

As can be seen the delta becomes surprisingly big for large files.

**Comment by britzl** [comment]
As an MVP I suggest that we proceed with my simple delta approach and use default compression.
