### ISSUE TITLE
Add go.get("#sprite", "current_animation") getter

### ISSUE THREAD

**Issue by Insality** [defold/defold#6203]
**Is your feature request related to a problem? Please describe (REQUIRED):**
There is no any way to get current animation from GO sprite label. If I make layout in go collection files and I need for some reason get image from sprite (to clone in with particles for example), I can't make it.

**Describe the solution you'd like (REQUIRED):**
Add getter for current animation

**Describe alternatives you've considered (REQUIRED):**
For now current solution is to make the data with duplicated name of sprites of every GO in collection

**Comment by AGulev** [comment]
I think this feature would be useful for level design.
But I would prefer `animation_id` instead of `current_animation `
Also it should be get-only property instead of set we use `sprite.play_flipbook()` and specify much more parameters.

@JCash @britzl what do you think?

**Comment by britzl** [comment]
@AGulev Exposing this as a read only property would probably work.
