### ISSUE TITLE
Error when trying to change stretch values of a new particle emitter

### ISSUE THREAD

**Issue by Sayuris1** [defold/defold#6224]
**Describe the bug (REQUIRED)**
If we add a new particle emitter by using add emitter button, we can't change stretch values and angular velocity from the editor.
We get that error: `java.lang.NullPointerException: Unknown`

**To Reproduce (REQUIRED)**
1. Create a particlefx
2. Add new emitter
3. Try to change stretch values of the new emitter

**Defold version (REQUIRED):**
 Defold 1.2.189 Steam

**Platforms (REQUIRED):**
 Editor

**Screenshots (OPTIONAL):**
![Capture](https://user-images.githubusercontent.com/56207443/144084676-39408495-3f41-40ec-825a-a80a4a9f4f52.PNG)

**Comment by d954mas** [comment]
UP!!!
Version 1.3.3

Very annoying.

No properties in file. Adding properties to file fixed it.


 properties {
    key: EMITTER_KEY_PARTICLE_STRETCH_FACTOR_X
    points {
      x: 0.0
      y: 0.0
      t_x: 1.0
      t_y: 0.0
    }
    spread: 0.0
  }
