### ISSUE TITLE
Can't login to forum.defold.com

### ISSUE THREAD

**Issue by ainonovo** [defold/defold#6231]
I apologize for writing here - but I no longer see ways to contact you.

Yesterday I registered with the help of github - mail on google

but today I can not go to the site. Even with login, it offers to register.

And the email is already busy.

New registrations are not allowed from your IP address. Primary email is not allowed.

**please help me**

**Comment by britzl** [comment]
Which username and email did you register with? It might be better to discuss this in an email to bjorn@defold.se

**Comment by ainonovo** [comment]
ainonovo

***@***.***

пт, 3 дек. 2021 г., 22:50 Björn Ritzl ***@***.***>:

**Comment by ainonovo** [comment]
And i create post about
Aes 128-256 crypt

пт, 3 дек. 2021 г., 22:50 Björn Ritzl ***@***.***>:

**Comment by ainonovo** [comment]
Please check you email

**Comment by ainonovo** [comment]
![1](https://user-images.githubusercontent.com/24792249/144721028-1e4eaeda-e883-4011-9d03-598da20a3d4f.png)
![2](https://user-images.githubusercontent.com/24792249/144721034-021db640-2db9-49dd-9b01-f4ba20589e39.png)
![3](https://user-images.githubusercontent.com/24792249/144721037-be8a53f0-e760-4acf-a9a1-ca62239864c8.png)
![4](https://user-images.githubusercontent.com/24792249/144721041-e1b7846e-0504-417d-ad19-12fabbf4d55e.png)

**Comment by britzl** [comment]
@ainonovo it seems like your email got blocked by the forums software somehow. Could you please try again?

**Comment by ainonovo** [comment]
Thank you very much. Everything works )))
