### ISSUE TITLE
Raw gamepad input: dpad and triggers don't work at all

### ISSUE THREAD

**Issue by Lampogolovii** [defold/defold#6232]
I use raw gamepad input. And this method doesn't send input of dpad-buttons (left-pad) or triggers.
 
**To Reproduce**
1. Connect gamepad (I have Xbox Wireless Controller)
2. Log every button and axis (action.gamepad_axis and action.gamepad_buttons)
3. Press d-pad button or trigger-button (trigger is axis actually)
4. There is no any changes in the log.
5. Theres is no way to detect d-pad buttons using Raw gamepad input

**Expected behavior**
1. I'd like to have d-pad buttons in action.gamepad_buttons table 
2. Triggers in action.gamepad_axis 

**Defold version**
I've checked 1.2.186 -- 1.2.189

**Platforms**
- I've tested on MacOS, Android
- I've tested with Xbox Wireless Controller, Sber virtual gamepad

**Minimal repro case project**
You can find my test project here. Just run it, connect gamepad and press any d-pad button
[rawgamepad_input.zip](https://github.com/defold/defold/files/7653623/rawgamepad_input.zip)

**Workaround**
Interesting fact, that standard input via input_binding with "Lpad down" works fine!
<img width="235" alt="Screenshot 2021-12-04 at 11 47 15" src="https://user-images.githubusercontent.com/23137022/144703517-af9ceac3-8bba-4ddb-b773-d704244312b0.png">
So, in this case I have input notification with "pad_down" action_id. But Raw input remains silent. [Video](https://youtu.be/xaXZkOndmIs)

My XBox controller is not damaged or something. I've tested it with online gamepad tester. [Video](https://youtu.be/yFM890aYKR4)

**Comment by britzl** [comment]
I noticed that you are not logging action.gamepad_hats. In my tests I get values in this table when pressing the d-pad on the gamepads I've tested with. The action.gamepad_hats table contains one value per "hat" as a bitmask:

```
#define GLFW_HAT_CENTERED       0
#define GLFW_HAT_UP             1
#define GLFW_HAT_RIGHT          2
#define GLFW_HAT_DOWN           4
#define GLFW_HAT_LEFT           8
```

Example: A value of 12 means DOWN+LEFT.

Note: The data we provide for a raw gamepad is a Lua table representation this GamepadPacket:

https://github.com/defold/defold/blob/dev/engine/hid/src/dmsdk/hid/hid.h#L474-L481

We do no translation of any kind to the data, we just return it in a Lua table structure:

https://github.com/defold/defold/blob/dev/engine/gameobject/src/gameobject/comp_script.cpp#L469-L509

**Comment by Lampogolovii** [comment]
Wow! I totally missed that gamepad_hats table! Sorry for that. Thanks for your help!
