### ISSUE TITLE
Error adding new game object in tutorial

### ISSUE THREAD

**Issue by ulaulaman** [defold/defold#6234]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2021-10-18T08:40:15.071173</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>6bfeea3b13d7b8920483ea2cba9c181a8650b84d</td></tr>
<tr><td>Defold engine sha</td><td>6bfeea3b13d7b8920483ea2cba9c181a8650b84d</td></tr>
<tr><td>Defold version</td><td>1.2.188</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"e83a98e4cc434b02ae44da990177ccda"'>e83a98e4cc434b02ae44da990177ccda</a></td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) UHD Graphics 620 (KBL GT2)</td></tr>
<tr><td>GPU Driver</td><td>OpenGL ES-CM 1.1 Mesa 21.0.3</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.11.0-41-generic</td></tr>
<table>

**Comment by britzl** [comment]
@ulaulaman can you reproduce the problem? Sentry didn't provide any useful crash information.

**Comment by britzl** [comment]
No additional information provided by user. Closing.
