### ISSUE TITLE
critical rendering issue with 1.2.189

### ISSUE THREAD

**Issue by rsaienz** [defold/defold#6246]
It seems to me that 1.2.189 has various critical rendering issues.

I see it particularly with particles but the same issue is also present for sprites! All the particles disappear at once for many frames and then they are drawn again only for one frame. The game has never shown anything similar before I updated to 1.2.189. No error / warning reported in the console.

I may guess something related to extension-spine that corrupts the data sent to the GPU? A spinemodel is present when I see the rendering issue...

**To Reproduce (REQUIRED)**
NA

**Expected behavior (REQUIRED)**
The particles and the sprites should be rendered in each frame

**Defold version (REQUIRED):**
  - 1.2.189

**Platforms (REQUIRED):**
 - Platforms: Android and macOS

**Comment by subsoap** [comment]
You should try to make a minimal example to reproduce the issue.

**Comment by ainonovo** [comment]
Please help me https://github.com/defold/defold/issues/6231

**Comment by rsaienz** [comment]
This was related to set_constant and, as far as I can see, it has been fixed in 1.2.190.

**Comment by britzl** [comment]
Correct!

Fixed via https://github.com/defold/defold/pull/6257
