### ISSUE TITLE
Cannot change the Font Size

### ISSUE THREAD

**Issue by realdev04** [defold/defold#6266]
There is no method to Change the Font Size of the Editor, Even for the Code Editor. @defold-services?

**Comment by britzl** [comment]
There's a menu option to change font size:

![Screenshot 2021-12-17 at 08 05 23](https://user-images.githubusercontent.com/1300688/146503639-157c6d85-5c82-45c7-89c5-77ae521c1594.png)

For the rest of the editor you need to apply a custom CSS file:

https://forum.defold.com/t/experiments-with-editor-styling-using-javafx-css/67021
