### ISSUE TITLE
Remove shared libraries for the unsupported desktop platforms

### ISSUE THREAD

**Issue by JCash** [defold/defold#6268]
Currently, we include shared libraries for all 3 desktop platforms in the editor bundle.
E.g. in the macOS editor, I see the .so and .dll files for javafx.

The size for each platform is between 70-110mb.

**Comment by AGulev** [comment]
https://stackoverflow.com/questions/52584519/does-javafx-after-removing-it-from-jdk-cross-platform

**Comment by AGulev** [comment]
it seems like this fix in javafx does that, no? https://github.com/openjdk/jfx/commit/1ebf7a24144b198e62b9b343821fdb155b9d703e
