### ISSUE TITLE
Custom HTTP header to use private repos as dependencies

### ISSUE THREAD

**Issue by aglitchman** [defold/defold#6269]
**Is your feature request related to a problem? Please describe (REQUIRED):**
I want to use private repos as dependencies in my project. 

- **GitHub**: you can make [Personal Access Token](https://github.com/settings/tokens) to access your private repos. Example:
```bash
curl -H "Authorization: token PASTE_TOKEN_HERE" -L https://github.com/indiesoftby/PRIVATE_REPO_NAME/archive/refs/heads/main.zip -o main.zip
```

- **GitLab**: the same, but the header is different, and you should point to the API endpoint instead of a friendly project URL like Github allows.
```bash
curl -v -H "PRIVATE-TOKEN: PASTE_TOKEN_HERE" -L https://gitlab.com/api/v4/projects/PROJECT_ID_HERE/repository/archive.zip -o main.zip
# or
curl -v -H "Authorization: Bearer PASTE_TOKEN_HERE" -L https://gitlab.com/api/v4/projects/PROJECT_ID_HERE/repository/archive.zip -o main.zip
```

Also, GitLab allows to add "?private_token=<your_access_token>" to the URL, and I can use that as an URL for dependency, but it's a bad idea to expose your access tokens in the `game.project` file.

**Describe the solution you'd like (REQUIRED):**
1. Add an option to the Preferences menu of the editor, where a developer can specify any HTTP header needed for authorization.
2. Add the same as an argument of the `bob.jar`.

**Describe alternatives you've considered (REQUIRED):**
I know that there is the `--auth` option of `bob.jar`, but I think it can't help to do that.

**Comment by britzl** [comment]
You can add authorization to the URL like this:

https://username: access-token@github.com/org/repo/archive/main.zip

**Comment by aglitchman** [comment]
> You can add authorization to the URL like this:

Yeah, I used it until yesterday when I accidentally exposed my access token to a colleague when I sent him a screenshot of IDE.

**Comment by britzl** [comment]
> 1. Add an option to the Preferences menu of the editor, where a developer can specify any HTTP header needed for authorization

And what if it's not the same token for all repos? Or if you use both GitHub, Gitlab and Bitbucket in the same project?

Maybe a better solution would be to use some kind of pattern replacement?

```
https://username:%GITHUB_TOKEN1%@github.com/myorg/repo1/archive/main.zip
https://username:%GITHUB_TOKEN2%@github.com/myorg/repo2/archive/main.zip
```

`GITHUB_TOKEN1` and `GITHUB_TOKEN2` could either be read from an environment variable or a settings file of some kind?

**Comment by aglitchman** [comment]
> And what if it's not the same token for all repos?

That's a good question! Personally, we use only private repos on GitLab, but the described situation is possible.

> Maybe a better solution would be to use some kind of pattern replacement?

Any option would work great! 

I'm wondering how it is organized in large organizations like Melsoft. @Insality?
