### ISSUE TITLE
Fixed_fit_projection improvement

### ISSUE THREAD

**Issue by Vultwo** [defold/defold#6270]
**Is your feature request related to a problem? Please describe (REQUIRED):**
Missing useful camera mode/setting. "fixed_fit_projection" only zooms out without an option to make the camera zoom in.
https://forum.defold.com/t/how-to-increase-screen-size/45056/3
My proposed addition would fix this problem.

**Describe the solution you'd like (REQUIRED):**
There is a easy fix / addition to add this functionality in the default render_script
```lua
local function fixed_fit_projection(near, far, zoom_in)
    local width = render.get_width()
    local height = render.get_height()
    local window_width = render.get_window_width()
    local window_height = render.get_window_height()
    -- Changing "local zoom = math.min" to "local zoom = math.max"
    local zoom = (zoom_in and math.max(window_width / width, window_height / height) or math.min(window_width / width, window_height / height))
    return fixed_projection(near, far, zoom)
end
```
In the init function add
```lua
function init(self)
    ...
    self.zoom = false
    ...
end
```
In the on_message function add
```lua
elseif message_id == hash("use_fixed_fit_projection") then
    ...
    self.zoom = message.zoom or false
    ...
end
```

**Describe alternatives you've considered (REQUIRED):**
This is the best and easiest solution, maybe the only solution. (No breaking changes for existing users as far as I can tell)

**Additional context (OPTIONAL):**
The current behavior without the feature. Background color appears under  "ground"

![zoom_out](https://user-images.githubusercontent.com/37175222/146675637-7e8626d6-8a35-4b2b-88ec-729b829ca611.PNG)

The behavior with the feature. Biggest phone/tablet aspect ratio 4:3, "ground" never exceeds size limits of different screens.

![zoom_in](https://user-images.githubusercontent.com/37175222/146675639-c2ff5f20-63d5-4bba-a9ff-c49997a31483.PNG)

**Comment by britzl** [comment]
I'm somewhat confused by this PR. From the screenshots it seems like you want to prevent the camera from zooming out, not zooming in?

I created a sample project to test the different projections and I added your suggestion to a branch here:

https://github.com/defold/sample-projections/tree/dev-test-improved-fixed-fit

Could you please take a look, and possible submit a modified version of the project above where it is clear what kind of outcome you wish to achieve?

**Comment by Vultwo** [comment]
Yeah, depends on how you look at it.

I have edited the branch.

**Comment by britzl** [comment]
Coming back to this suggestion now (sorry about the delay!)

@Vultwo created a branch in the defold/sample-projections repo with his suggested change. I'm still not convinced that this is something we'd like to include in the default render script. To test this I created a scene such as in the screenshot above:

![Screenshot 2022-04-07 at 08 48 50](https://user-images.githubusercontent.com/1300688/162138331-b680ff58-010f-4ace-af11-9646896d8ada.png)

I've placed the ground graphics at the bottom of the screen together with two cactii. I've also placed a Defold logo bottom left and top right. The player is in the middle of the screen.

Making the screen less wide using the standard fixed fit would keep everything on screen and zoom out to reveal things outside of the initial design:

![Screenshot 2022-04-07 at 08 49 23](https://user-images.githubusercontent.com/1300688/162138912-b7f500d1-dc86-4f5d-b317-58c45c4f6a80.png)

Using the projection by @Vultwo on the other hand would guarantee that you never see more than intended. Instead some of the things would no longer be visible:

![Screenshot 2022-04-07 at 08 49 30](https://user-images.githubusercontent.com/1300688/162139150-8e6bd035-b531-4a39-981d-bcff5354c2d0.png)

If we instead make the screen wider using the standard fixed fit we'd still see the ground, cacti etc and some additional content on the sides:

![Screenshot 2022-04-07 at 08 49 45](https://user-images.githubusercontent.com/1300688/162139474-06eed6ec-296d-4005-878e-8807f8a67a4d.png)

Again using the projection by @Vultwo we'd again lose some content outside of the screen, but we will not see more than intended:

![Screenshot 2022-04-07 at 08 49 37](https://user-images.githubusercontent.com/1300688/162139959-cef57e98-5f60-40c2-86ee-622e1860a28a.png)

----

Conclusion: Depending on your use case both projections have their merit and maybe we should include this new projection as a fourth option?

We could add this as a new projection or as an option to fixed_fit:

```
-- default, same as before
msg.post("@render:", "use_fixed_fit_projection", { near = -1, far = 1 })

-- new, never show more
msg.post("@render:", "use_fixed_fit_projection", { near = -1, far = 1, max_zoom = true })
```

Question is what to name this option?

**Comment by britzl** [comment]
I'm now thinking this:

```
msg.post("@render:", "use_fixed_projection", { near = -1, far = 1, zoom_out = true })
msg.post("@render:", "use_fixed_projection", { near = -1, far = 1, zoom_in = true })
msg.post("@render:", "use_fixed_projection", { near = -1, far = 1, zoom = 2 })
```

Or maybe even better to only use a single `zoom` argument:

```
msg.post("@render:", "use_fixed_projection", { near = -1, far = 1, zoom = hash("out") })
msg.post("@render:", "use_fixed_projection", { near = -1, far = 1, zoom = hash("in") })
msg.post("@render:", "use_fixed_projection", { near = -1, far = 1, zoom = 2 })
```

**Comment by britzl** [comment]
We recently merged an improvement to the camera component (https://github.com/defold/defold/pull/6829). I think the above suggested projection possibly should be added as an option to the camera. Added new ticket to cover this:

https://github.com/defold/defold/issues/6849

Closing this one.
