### ISSUE TITLE
Log in editor

### ISSUE THREAD

**Issue by ainonovo** [defold/defold#6271]
Sorry, but maybe in the log a new line should be added at the top of the list and not at the bottom?

or scroll down the list automatically if a new line is added

![1](https://user-images.githubusercontent.com/24792249/146712509-ab0f749c-cdce-4d2e-b9a5-380ac2766677.png)

**Comment by britzl** [comment]
> Sorry, but maybe in the log a new line should be added at the top of the list and not at the bottom?

Most logs/consoles etc add new entries to the bottom of the list.

> or scroll down the list automatically if a new line is added

The log will do this automatically, BUT if you have scrolled the list it will stay at the position you scrolled to even if new lines are added. I believe this is the expected behaviour.
