### ISSUE TITLE
Short style function vmath.vector4() won't build in HTML5

### ISSUE THREAD

**Issue by lost-in-hub** [defold/defold#6275]
On normal builds this : 
`go.property( "color",  vmath.vector4 ( 1 ) )`
works ok.

On HTML5 builds that's an error : 
`/main/player/player.script
	Line 16: Only these types are available: number, hash, msg.url, vmath.vector3, vmath.vector4, vmath.quat, resource.*`

Switching to this :
`go.property( "color",  vmath.vector4 ( 1, 1, 1, 1 ) )`
builds and works ok both in normal builds and HTML5 builds.

Defold version : 1.2.190
Mac OS Big Sur 11.6.1 
Macbook pro 16 inches (intel) 2019

**Comment by britzl** [comment]
This will be fixed in 1.2.191:

https://github.com/defold/defold/issues/6181
