### ISSUE TITLE
AppStore Connect iPad Mini warning

### ISSUE THREAD

**Issue by ghost** [defold/defold#6279]
ITMS-90901: Missing full-screen support for the latest iPad mini display. The “XXX.app” bundle includes UIRequiresFullScreen=YES in the Info.plist or supports only a subset of UISupportedInterfaceOrientations, and is built with the 14.5 SDK. To take advantage of the full screen size, recompile with Xcode 13 and the SDK for iPadOS 15 or later.

**Comment by britzl** [comment]
Thanks. We're in the process of updating our builds to support iOS 15. The new version will be released in January.

**Comment by AGulev** [comment]
it's already possible to test it in beta https://forum.defold.com/t/defold-1-2-191-beta/69997/16
I'm closing this ticket
