### ISSUE TITLE
error when change script on vscode

### ISSUE THREAD

**Issue by reopucino** [defold/defold#6280]
### Expected behaviour
should load script is updated when it change from other code editor

### Actual behaviour
code not loaded and error show "clojure.lang.ExceptionInfo: Duplicate node key `recoil` from :editor.code.script/ScriptPropertyNode"

### Steps to reproduce
- open defold and code editor (vscode)
- script on vscode, then back into defold
- error show "clojure.lang.ExceptionInfo: Duplicate node key `recoil` from :editor.code.script/ScriptPropertyNode"

<hr/>

<table>
<tr><td>Build time</td><td>2021-12-16T14:45:33.859978</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>09da5fbf86f611727c6f533a6078c0d84f6b8da9</td></tr>
<tr><td>Defold engine sha</td><td>d31d6397a72178541a5ef6e7ef2bed090d828f58</td></tr>
<tr><td>Defold version</td><td>1.2.190</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"d266cc3fa98d4cb19febc52728d086ed"'>d266cc3fa98d4cb19febc52728d086ed</a></td></tr>
<tr><td>GPU</td><td>Radeon(TM) RX 580</td></tr>
<tr><td>GPU Driver</td><td>4.5.148201 Compatibility Profile Context 20.50.02.10 27.20.15002.10002</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
Does it matter what kind of change you make to the file? Is it enough to add a single character or does it have to be specific changes?

**Comment by britzl** [comment]
> anyway after I change `recoil` into `recoil_attack` defold editor work properly

Sounds really strange that the name should matter! 🤷
