### ISSUE TITLE
OpenGL crash while deleting GO with mesh

### ISSUE THREAD

**Issue by abadonna** [defold/defold#6281]
### Expected behaviour
GO should be deleted without crashes.

### Actual behaviour
```
ERROR:GRAPHICS: OpenGLFlip(1281): gl error 1281: invalid value

Assertion failed: (0), function OpenGLFlip, file ../src/opengl/graphics_opengl.cpp, line 1281.
INFO:CRASH: Successfully wrote Crashdump to file: /Users/ivan/Library/Application Support/Defold/_crash
ERROR:CRASH: CALL STACK:

# 0 pc     0x30dd7d libxpc.dylib _sigtramp+29

```
### Steps to reproduce
[https://github.com/abadonna/defold-mesh-binary](https://github.com/abadonna/defold-mesh-binary)

run demo and click on menu

workaround - set simple buffers before deleting
<hr/>

<table>
<tr><td>Build time</td><td>2021-12-16T14:45:55.272228</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>09da5fbf86f611727c6f533a6078c0d84f6b8da9</td></tr>
<tr><td>Defold engine sha</td><td>d31d6397a72178541a5ef6e7ef2bed090d828f58</td></tr>
<tr><td>Defold version</td><td>1.2.190</td></tr>
<tr><td>GPU</td><td>Intel(R) Iris(TM) Graphics 540</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-16.1.12</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.16</td></tr>
<table>

**Comment by AGulev** [comment]
hmmm, it looks similar to this issue, could you pls take a look? https://forum.defold.com/t/suddenly-receiving-openglflip-errors-when-building-for-desktop-html5-builds-fine/69974/2?u=agulev

**Comment by abadonna** [comment]
I don't think so, it doesn't connected to any Editor actions, just to content of mesh vertex buffer.

**Comment by aglitchman** [comment]
I ran the project. @abadonna Could you please point me to what should I do to crash the engine?

https://user-images.githubusercontent.com/193258/147365977-52d49221-3ce4-473a-9c79-6d8b5454650c.mp4

**Comment by abadonna** [comment]
It works for you but crashes for  me...

**Comment by britzl** [comment]
Could this be related to the use of DearImGui? What if you do the same without it?

**Comment by abadonna** [comment]
Checked. Everything works fine after removing DearImGui dependency. 
So it's not defold but imgui issue?

**Comment by britzl** [comment]
> Everything works fine after removing DearImGui dependency.
> So it's not defold but imgui issue?

It seems that way. What if you use DearImGUI and delay using.timer.delay() the code you run when checking the checkbox?

**Comment by abadonna** [comment]
Crashes anyway.

**Comment by britzl** [comment]
Added ImGUI issue: https://github.com/britzl/extension-imgui/issues/22
