### ISSUE TITLE
Bob error: "Could not initialize class com.dynamo.bob.TexcLibrary"

### ISSUE THREAD

**Issue by gmantaos** [defold/defold#6282]
**Describe the bug (REQUIRED)**

The build process using `bob` is terminated with the error: `Could not initialize class com.dynamo.bob.TexcLibrary`.

The build environment is this docker image: https://gitlab.com/haath/defold-docker/-/blob/master/Dockerfile

The image is based on the official `openjdk:11-jdk-stretch`, and has been tested and works fine up to bob version `1.2.170`

**To Reproduce (REQUIRED)**

1. Start docker contain from image `openjdk:11-jdk-stretch`
2. Download bob from `d.defold.com`
3. Try to build project

**Expected behavior (REQUIRED)**

Expected bob to complete the build without errors.

**Defold version (REQUIRED):**

  - Version 1.2.190

**Platforms (REQUIRED):**
 - Platforms: Android, Windows, HTML5
 - OS: linux (docker)

**Minimal repro case project (OPTIONAL):**

Try to build anything using this image:
- https://gitlab.com/haath/defold-docker
- https://hub.docker.com/repository/docker/gmantaos/defold

**Logs (OPTIONAL):**

full command:

```
bob --platform x86_64-win32 --bundle-output build/win64/
```

```
Download archive(s)Downloading 1 archive(s)
 0: Downloading https://github.com/britzl/defold-orthographic/archive/refs/tags/3.1.3.zip
 0: Status 200: Stored /builds/haath/dinkyvale/.internal/lib/1a83fec2c96a5ec9a0d97f3732c592a3e15d31c2-IjNhZGZmYTlkNWIxNjVmYmNhOTUwNjVhZGExMDEzMDYyMGRkNzdiYzIzZTcwNDhjMTk1MDExYmFhNTcyZTI2NmMi.zip
 2147483647%Working...Cleaning... 1% ...done!
Cleaning engine... ...done!
Reading classes... 2147483647% ...done!
Reading tasks... ...done!
Building... 2% 4% 6% 7% 9% 11% 12% 14% 16% 18% 19% 21% 23% 24% 26% 28% 30% 31% 33% 35% 36% 38% 40% 41% 43% 45% 47% 48% 50% 52% 53% 55% 57% 59% 60% 62% 64% 65% 67% 69% 70% 72% 74% 76% 77% 79% 81% 82% 84%java.lang.NoClassDefFoundError: Could not initialize class com.dynamo.bob.TexcLibrary
	at com.dynamo.bob.font.Fontc.generateGlyphData(Fontc.java:641)
	at com.dynamo.bob.font.Fontc.compile(Fontc.java:939)
	at com.dynamo.bob.pipeline.FontBuilder.build(FontBuilder.java:65)
	at com.dynamo.bob.Project.runTasks(Project.java:1343)
	at com.dynamo.bob.Project.doBuild(Project.java:1135)
	at com.dynamo.bob.Project.build(Project.java:584)
	at com.dynamo.bob.Bob.mainInternal(Bob.java:708)
	at com.dynamo.bob.Bob.main(Bob.java:757)
 96% ...done!
 100% ...done!
The build failed for the following reasons:
ERROR builtins/fonts/system_font.font:0 Could not initialize class com.dynamo.bob.TexcLibrary
```

**Additional context:**

The work around described here did not fix the issue: https://defold.com/manuals/linux/#q-the-defold-editor-crashes-when-opening-a-collection-or-game-object-and-the-crash-refers-to-libffiso

**Comment by britzl** [comment]
I can't say for sure why this doesn't work. The TexcLibrary class has not undergone that many changes over the years:

https://github.com/defold/defold/commits/dev/com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/TexcLibrary.java

1.2.170 was released in June 2020.

I'm thinking that it is this bit here that fails:

https://github.com/defold/defold/blob/dev/com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/TexcLibrary.java#L44-L57

It could be a permission thing perhaps?

**Comment by gmantaos** [comment]
Hey thanks a lot for the quick response and the tip!

I think the permissions may have played a part, since the downloaded `bob.jar` appears to originally belong to a group called `staff`. But in the end the bigger problem was that my docker image was based on `11-jre-stretch`, which is based on Debian `stretch` which comes with glibc version `2.24`, and now bob apparently requires `2.27`.

I have updated my docker image to now be based on Debian bullseye and now everything works :)
