### ISSUE TITLE
Add bounding box representation for gameobjects

### ISSUE THREAD

**Issue by JCash** [defold/defold#6292]
In order to be able to do culling of game objects, we need a bounding box for our game objects.

First up, we need a design for how to go about this.
E.g. can we create this in the content pipeline?
For instance, we cannot move components at runtime.
However, we can enable components at runtime, how should it affect the bounding box?
etc...

**Comment by AGulev** [comment]
but should we really solve it on GO level? at the moment if I send `disable` message to GO I turn off all the components.
Maybe it should be per component?

do we really need it for components without rendering?

**Comment by Dragosha** [comment]
Other than turning the component on / off there is a mesh component. And we can change the mesh' buffer in real time. How to calculate bounding box for this? Per each mesh vertex * object' transformation matrix?

**Comment by JCash** [comment]
It's a good question. I see two options:
* Either the bounding box is calculated by the mesh after the buffer was updated.
* Or perhaps it's possible for the user to set buffer _and_ bounding box. E.g if it's easy for the user to calculate it while updating the buffer.

**Comment by aglitchman** [comment]
> * Or perhaps it's possible for the user to set buffer _and_ bounding box.

It's an excellent idea! Because the user can use non-float types for vertices positions (i.e. int16, and convert them to floats in a vertex shader) and Defold won't know how to transform it.
