### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by hemanzur** [defold/defold#6294]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2021-12-16T14:45:11.955824</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>09da5fbf86f611727c6f533a6078c0d84f6b8da9</td></tr>
<tr><td>Defold engine sha</td><td>d31d6397a72178541a5ef6e7ef2bed090d828f58</td></tr>
<tr><td>Defold version</td><td>1.2.190</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"93f2ff835cc54fdeb6c1a5d16bd575c4"'>93f2ff835cc54fdeb6c1a5d16bd575c4</a></td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) UHD Graphics 620 (KBL GT2)</td></tr>
<tr><td>GPU Driver</td><td>OpenGL ES-CM 1.1 Mesa 21.2.5</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.15.7-1-MANJARO</td></tr>
<table>

**Comment by britzl** [comment]
```
editor.gl$gl_clear.invokeStatic.class java.lang.ClassCastException: class jogamp.opengl.es1.GLES1Impl cannot be cast to class com.jogamp.opengl.GL2ES2 (jogamp.opengl.es1.GLES1Impl and com.jogamp.opengl.GL2ES2 are in unnamed module of loader 'app')
    at editor.gl$gl_clear.invokeStatic(gl.clj:192)
    at editor.scene$render_BANG_.invokeStatic(scene.clj:273)
    at editor.scene$update_image_view_BANG_$fn.invoke(scene.clj:1158)
    at editor.scene$update_image_view_BANG_.invokeStatic(scene.clj:1155)
```

Please give this solution a try:

* https://defold.com/manuals/linux/#q-the-defold-editor-crashes-when-opening-a-collection-or-game-object-and-the-crash-refers-to-comjogampopengl

Reopen if it doesn't help!
