### ISSUE TITLE
Autocomplete wrong position when console is hidden

### ISSUE THREAD

**Issue by gianmichelemariani** [defold/defold#6305]
**Describe the bug (REQUIRED)**
When the console panel is hidden, the autocomplete position is not where the cursor is.

**To Reproduce (REQUIRED)**
Please see attached video

https://user-images.githubusercontent.com/46694168/148133631-9dd73db4-404d-4671-b6a5-1510e1398146.mov

**Expected behavior (REQUIRED)**
Autocomplete to appear where the cursor is

**Defold version (REQUIRED):**

<img width="465" alt="Screenshot 2022-01-04 at 22 40 24" src="https://user-images.githubusercontent.com/46694168/148133776-a03909b3-3b26-4b5e-970d-dd81bb08394d.png">

**Platforms (REQUIRED):**
 OSX 12.1 
Apple Silicon M1 Pro

**Comment by AGulev** [comment]
@vlaaad fixed it, and it's available in the latest update
