### ISSUE TITLE
Asset explorer refresh (scroll to top) every save in 190

### ISSUE THREAD

**Issue by Vbif** [defold/defold#6315]
**Describe the bug (REQUIRED)**
Asset explorer refresh (scroll to top) every save in 190. The 189 version from github works fine.

**To Reproduce (REQUIRED)**
1. Have a lot of folder/files (expand them), so scrool bar appear in asset explorer
2. Open some file
3. Make change and CTRL+S
4. Asset explorer scroll to top

**Expected behavior (REQUIRED)**
Nothing happen with asset explorer

**Defold version (REQUIRED):**
  - Version 1.2.190

**Platforms (REQUIRED):**
 - macOS 11.5.1

https://user-images.githubusercontent.com/1279849/148696425-f195d4cc-fe6e-45a9-99b9-01909521c91f.mov

**Comment by d954mas** [comment]
+1  very annoying

**Comment by d954mas** [comment]
+1

**Comment by Vbif** [comment]
@britzl maybe this issue related to https://github.com/defold/defold/issues/6558 and can be added to 1.3.4 ?

**Comment by Lampogolovii** [comment]
yeeees, really annoying thing!!!

**Comment by vlaaad** [comment]
The fix is out!
