### ISSUE TITLE
Ability to add your own project templates locally.

### ISSUE THREAD

**Issue by astrochili** [defold/defold#6316]
It would be nice to be able to add custom templates to the editor locally. This will allow faster setup of the startup environment, including settings for VSCode.

I don't know how it would be most convenient, probably just put the template archives somewhere and display them in a separate tab (preferably the first one) when you start the editor.

As a continuation of an obsolete [ticket](https://github.com/defold/editor2-issues/issues/727).

**Comment by britzl** [comment]
Closed via https://github.com/defold/defold/pull/6381
