### ISSUE TITLE
[SUGGESTION] Floating point render target

### ISSUE THREAD

**Issue by abadonna** [defold/defold#6319]
It would be very helpful for a lot of different things to have floating point rendering targets without clamping to [0,1]

**Comment by britzl** [comment]
From forum by @Jhonnyg:

"it’s not universally supported by GL 2.0 spec on all platforms which is the reason it’s not exposed afaik" and "We really need to have it to enable certain effects"

https://stackoverflow.com/a/47134606/1266551

Looking at it from an API perspective:

Would this mean a new `render.FORMAT_FLOATINGPOINT` to `render.render_target(name, params)` and return null if it's not supported?

**Comment by abadonna** [comment]
Sounds good. 
I don't think it should be something too complex, as not much people will need it anyway. 
But maybe it will be useful for compute shaders (if Defold will support it one day) as well.

**Comment by Morgerion** [comment]
Float render-target is needed for many trivial effects such as HDR rendering, volumetric rendering over a height map, and so on.

Yes, as for HDR - i can make do with some fakes, like writing brightness separately in the alpha channel. But all the other goodies of modern rendering remain unavailable.

**Comment by Morgerion** [comment]
It turns out there has been a quick hack on this subject for quite some time.
If you add these lines to the render-script:
```
render.FORMAT_RGB16F = 22
render.FORMAT_RGB32F = 23
render.FORMAT_RGBA16F = 24
render.FORMAT_RGBA32F = 25
render.FORMAT_R16F = 26
render.FORMAT_RG16F = 27
render.FORMAT_R32F = 28
render.FORMAT_RG32F = 29
```
you can get a float render target in this way :) and these formats can be specified when creating the render target:
```
local color_params = {
  format = render.FORMAT_RGBA32F,
```

I know it's not the best solution.
But it will work on GLES3 as long as Defold supports OpenGL. I.e. it's enough for a while.

**Comment by JCash** [comment]
Related issue #https://github.com/defold/defold/issues/3350
