### ISSUE TITLE
Build error while bundle project with cubemap

### ISSUE THREAD

**Issue by abadonna** [defold/defold#6325]
### Actual behaviour
Conflicting output resource 'build/default/assets/clouds.texturec‘ generated by the following input files: [assets/clouds.cubemap, builtins/graphics/default.texture_profiles] <-> [assets/clouds.cubemap, assets/clouds/right.png, assets/clouds/left.png, assets/clouds/top.png, assets/clouds/bottom.png, assets/clouds/front.png, assets/clouds/back.png, builtins/graphics/default.texture_profiles]

### Steps to reproduce
Try to bundle any project with cubemap, e.g.
https://github.com/abadonna/defold-skyquad

<hr/>

<table>
<tr><td>Build time</td><td>2022-01-10T12:21:26.837885</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>d393bae6a361f86cf2263ab312c9b3cea45253ab</td></tr>
<tr><td>Defold engine sha</td><td>d393bae6a361f86cf2263ab312c9b3cea45253ab</td></tr>
<tr><td>Defold version</td><td>1.2.191</td></tr>
<tr><td>GPU</td><td>Intel(R) Iris(TM) Graphics 540</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-16.1.12</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.16</td></tr>
<table>

**Comment by AGulev** [comment]
full test project
[cubemap-full-testcase.zip](https://github.com/defold/defold/files/7872577/cubemap-full-testcase.zip)
