### ISSUE TITLE
Creating tilemaps through factories does not update collision for programmatically changed tiles

### ISSUE THREAD

**Issue by gmantaos** [defold/defold#6327]
**Describe the bug**

Instead of going into detail here I will link to the relative forum post from 2 years ago:

https://forum.defold.com/t/creating-tilemaps-through-factories-does-not-update-collision-for-programmatically-changed-tiles/63988

I encountered the exact same issue again just now, BUT this time I managed to find a workaround.
So I'm posting it here because hopefully it should lead you guys fast to a solution.

**Workaround:**

It turns out, that the issue occurs only when an existing tile in the tilemap is being replaced by another.
The collision remains to that of the original tile.

However when an originally-empty tile is being filled in, the collision on that tile is set correctly.

**Defold version:**
  - Version 1.2.190

**Platforms):**
 - Windows

**Comment by AGulev** [comment]
Could you pls create a minimal case project where problem reproduced?

**Comment by gmantaos** [comment]
I created a minimal example showing the bug here: https://github.com/gmantaos/tilemap_collision_example

### Description

- Object `map.go` contains a simple tilemap and a script.
    - `map.script`: updates the tilemap tiles in the `init()` function
        - trees tile with collision is added at `(4, 6)`
        - rock tile with collision is removed from `(2, 7)`
        - rock tile with collision is added at `(2, 3)`
        - trees tile with collision is added at `(3, 3)`
- Main collection contains:
    - One instance of `map.go` placed directly on the scene
    - One factory for `map.go` prefabs
    - `controller.script`: creates a new instance of `map.go` in the `init()` function


### The bug

- The instance of `map.go` that was directly placed on the collection (on the left) has the expected collision areas.
- The instance of `map.go` that gets created by the factory (on the right) has incorrect collision on tiles that were changed in the `init()` function.
    - I have confirmed that this is not just a display bug in the physics debug viewer.
- The rock that was removed from `(2, 7)` still left behind a static collision area.
- The trees that were added at `(4, 6)` did not get a collision area.
- BUT the tile changes at `(2, 3)` and `(3, 3)`, where the tilemap was originally empty on those layers, did in fact update the collision correctly on the factory-generated map.

![image](https://user-images.githubusercontent.com/29335643/149616491-0f43c52d-444c-4537-ab6e-66d01b0023b4.png)

**Comment by AGulev** [comment]
it seems like priority issue or something like that. 
it I add timer:

```
function init(self)
	timer.delay(0, false, function()
		id = msg.url("#tilemap")

		-- AREA WITH PREEXISTING TILES --
		-- add trees with collision from the ground layer
		tilemap.set_tile(id, "ground", 4, 6, 22)
		-- remove a rock with collision from the fringe layer
		tilemap.set_tile(id, "fringe", 2, 7, 0)

		-- AREA ORIGINALLY EMPTY --
		-- add rocks with collision to the ground layer --
		tilemap.set_tile(id, "fringe", 2, 3, 92)
		-- add trees with collision to the ground layer --
		tilemap.set_tile(id, "fringe", 3, 3, 22)
	end)
	
end
``` 
it works fine.

**Comment by AGulev** [comment]
@gmantaos [Here](http://d.defold.com/alpha/#530177104f9dfb754932eac44b0e8912d394494c) is alpha version of Defold 1.2.192 with fix if this issue. 

I tested it in your test project and also in a couple of my projects with tilemap, but it would be nice if you can take a look at some projects with a lot of tilemaps used in a different way (factories, dynamic changes, and so on) using this alpha version

**Comment by gmantaos** [comment]
I'm still getting the same thing on my example project. Am I doing something wrong?

![image](https://user-images.githubusercontent.com/29335643/149634261-a2be2279-2936-42be-9844-187eadd29e35.png)

On top of that some strange characters now appeared on the window titlebar.

**Comment by AGulev** [comment]
@gmantaos ppbly I sent you a wrong link, let me check everything.

**Comment by AGulev** [comment]
@gmantaos yes, sorry for that (
here is right link:
 https://d.defold.com/archive/dev/530177104f9dfb754932eac44b0e8912d394494c/dev/editor2/Defold-x86_64-win32.zip

**Comment by gmantaos** [comment]
@AGulev no worries! Works now with the second one :)

Thanks for the quick fix!

> it would be nice if you can take a look at some projects with a lot of tilemaps used in a different way

I will be using it now with my current project which generates random tilemaps, and let you know if any other issue comes up. However I'm just a hobbyist so the testing probably won't be very thorough.

**Comment by AGulev** [comment]
@gmantaos thank you!

Do you have this strange symbol in the window titlebar in this version?

**Comment by gmantaos** [comment]
> Do you have this strange symbol in the window titlebar in this version?

Yup. It's two symbols, and different on every run.

![image](https://user-images.githubusercontent.com/29335643/149635518-2de54467-2804-47c6-8f45-0f7dcc5e5ae8.png)
![image](https://user-images.githubusercontent.com/29335643/149635534-d6cb56fc-d95f-4e4f-a6d7-c37ea91280b7.png)

They are there even when bundling the application in release mode.

**Comment by AGulev** [comment]
@gmantaos thx

@britzl could you pls take a look (this is the last `dev` at the moment and  this project https://github.com/gmantaos/tilemap_collision_example )

**Comment by britzl** [comment]
Yes I will take a look!

**Comment by britzl** [comment]
> Yes I will take a look!

Fix here: https://github.com/defold/defold/pull/6331

**Comment by hw762** [comment]
While the example project here still works on the latest version, my own project following a similar setup does not work with factory created tilemaps. I'll see if I can make a minimal example
