### ISSUE TITLE
New system_name

### ISSUE THREAD

**Issue by lecricreator** [defold/defold#6343]
On the iPad, there is a new system name. Before it was "iPhone OS", now it change in "iPadOS"
![image](https://user-images.githubusercontent.com/53663215/150773507-7ccf3da3-5cbb-4da2-b424-339c721b0c1a.png)
![image](https://user-images.githubusercontent.com/53663215/150773534-443cb339-57d2-4bc3-b111-9ec3d2764bee.png)

**To Reproduce**
1. create a label for see on the screen
2.
```lua
local system_name = sys.get_sys_info().system_name
label.set_text("#error", "My system_name is an "..system_name)
```
3. create bundle on ios
4. running bundle on ipad

**Expected behavior**
- Add new system_name on API documentation.
https://defold.com/ref/sys/#sys.get_sys_info:
![image](https://user-images.githubusercontent.com/53663215/150675385-28efa392-6333-486c-9365-3a0d5e03ced0.png)

- If possible add or change function for OS name. Just for the path on OS. Exemple : 
![image](https://user-images.githubusercontent.com/53663215/150675461-c5ae31c7-6013-49b2-9c97-a202eac98589.png)

**Comment by JCash** [comment]
I don't see the actual issue?
Can you clarify what the problem is?

**Comment by lecricreator** [comment]
> I don't see the actual issue? Can you clarify what the problem is?

sorry, I completed it at the beginning and it's not a bug, just an information.

**Comment by britzl** [comment]
> it's not a bug, just an information.

> I don't see the actual issue?

This actually might be a problem. If both iPads and iPhones used to report "iPhone OS" but now iPads report "iPadOS" then perhaps that might break things for users?

I see that we actually have code in place to patch the system name:

https://github.com/defold/defold/blob/dev/engine/dlib/src/dlib/sys_cocoa.mm#L38-L41

Should we also patch iPadOS and convert that to iPhone OS?

**Comment by lecricreator** [comment]
And that I don't know if there are other system names.

**Comment by britzl** [comment]
@lecricreator are you using the standard Info.plist from builtins or do you have a custom Info.plist?

**Comment by lecricreator** [comment]
> @lecricreator are you using the standard Info.plist from builtins or do you have a custom Info.plist? If you have a custom plist would you mind sharing it?

I use the standard Info.plist from builtins.

**Comment by britzl** [comment]
Thanks. And which iPadOS version do you have on your iPad? 15.2.1?

**Comment by lecricreator** [comment]
It's the version 15.2.
