### ISSUE TITLE
Files from .definore are compiled

### ISSUE THREAD

**Issue by MaxBrain** [defold/defold#6345]
Command Project->Bundle->Android Application compiles all project files including those mentioned in .defignore

Simple project in the attached 
1. Create new project
2. Create atlas file with not existed image
![atlas](https://user-images.githubusercontent.com/5093842/150758061-83407976-5c19-4d8a-b8b5-5ee6d9462519.png)
3. Add atlas file to .defignore
![defignore](https://user-images.githubusercontent.com/5093842/150761576-6027aee2-84ea-44e6-930c-d5d0c450e15a.png)
4. Try to Project->Bundle->Android Application
![build_output](https://user-images.githubusercontent.com/5093842/150761442-2e7e0f0c-2df0-440e-9c62-b1f88c0e58c0.png)

**Expected behavior**
Files from .defignore file are not compiled

**Defold version:**
  - Version [e.g. 1.2.191]

**Platforms:**
 - Platforms: Android (May be other bundles gave the same error)
 - OS: Windows 10

**Minimal repro case project:**
[TestDefignore.zip](https://github.com/defold/defold/files/7924383/TestDefignore.zip)

**Comment by britzl** [comment]
Hmm, yes, it seems like the editor correctly ignores the excluded files and folders, but bob doesn't (even though I expected it to). I'll investigate.
