### ISSUE TITLE
Physics and vsync option

### ISSUE THREAD

**Issue by Lampogolovii** [defold/defold#6346]
Describe the bug
If I turn off "vsync" option in game.project then physics works wrong while tab changing in HTML-5 build.

To Reproduce
1. Create static floor and a dynamic box above it.
2. Set ​gravity to -1000 and scale to 0.01
3. Turn off vsync option
4. Build HTML5
5. Tap on any other tabs in your browser
6. Return to the tab with your game

<img width="277" alt="Screenshot 2022-01-24 at 14 08 11" src="https://user-images.githubusercontent.com/23137022/150775003-8dc9084a-7ba6-46f0-b954-57f8fb19ae4f.png">
<img width="326" alt="Screenshot 2022-01-24 at 14 08 18" src="https://user-images.githubusercontent.com/23137022/150775008-972c394e-99f9-4764-ae13-f4f29c1fa56a.png">

Minimal repro case project
Here is the minimal project to reproduce.
[min_repo.zip](https://github.com/defold/defold/files/7925117/min_repo.zip)
Video (https://youtu.be/f25yfMygA4w)

Expected behavior
Physics works identically with vsync turned on or off.

Defold version
1.2.179 -- 1.2.190

Platforms
HTML5 (in browsers on macOS, iOS, Android)

Workaround
If I set framecap to 60, physics works fine with vsync turned on and off.

**Comment by britzl** [comment]
Please help us test! https://forum.defold.com/t/game-physics-time-steps-beta-testing/70539
