### ISSUE TITLE
Error when deleting atlas

### ISSUE THREAD

**Issue by chrisolsen** [defold/defold#6349]
### Steps to reproduce

- create atlas, then delete it

<hr/>

<table>
<tr><td>Build time</td><td>2022-01-24T08:24:22.942366</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>c317904bd98489a5644163ceecad942e8e8bb94b</td></tr>
<tr><td>Defold engine sha</td><td>d393bae6a361f86cf2263ab312c9b3cea45253ab</td></tr>
<tr><td>Defold version</td><td>1.2.191</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"7ffc474eb7864e1588c399c6a5ac0d28"'>7ffc474eb7864e1588c399c6a5ac0d28</a></td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) HD Graphics 520 (SKL GT2)</td></tr>
<tr><td>GPU Driver</td><td>OpenGL ES-CM 1.1 Mesa 21.0.3</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.11.0-46-generic</td></tr>
<table>

**Comment by britzl** [comment]
Error is ClassCastException without any stacktrace in Sentry.

@chrisolsen can you reproduce this reliably?

**Comment by chrisolsen** [comment]
It happened all the time, but when I start defold with the following all works well. It only does this on my laptop.
```
MESA_LOADER_DRIVER_OVERRIDE=i965 ./Defold
```
