### ISSUE TITLE
GUI template with layers is rendered differently inside editor and game

### ISSUE THREAD

**Issue by Insality** [defold/defold#6356]
**Describe the bug (REQUIRED)**
There is the bug, where layers inside templates rendering incorrect inside the Editor. In the game all render as excepted.
See the template (_component.gui_) and their layer setup in example project.

**To Reproduce (REQUIRED)**
1. Have template with layer
2. Use this template inside other GUI, add additional layers on their parent.
3. In some cases (like in example) the layers draw in incorrect way

**Expected behavior (REQUIRED)**
The editor and the game should render layers correctly

**Defold version (REQUIRED):**
On actual version (example created on 185)

**Platforms (REQUIRED):**
Example tested on MacOS.

**Minimal repro case project (OPTIONAL):**
[template_layers_bug.zip](https://github.com/defold/defold/files/7958132/template_layers_bug.zip)

**Workaround (OPTIONAL):**
Currently I have to not use layers for make easier make windows inside the editor

**Screenshots (OPTIONAL):**
Inside Editor:
![Screenshot 2022-01-28 at 13 01 46](https://user-images.githubusercontent.com/3294627/151536281-148d822b-0087-4af2-b930-f33e3e53704c.png)

Inside Game:
![Screenshot 2022-01-28 at 13 01 51](https://user-images.githubusercontent.com/3294627/151536301-76019d6f-70ef-4b55-8c0b-bba79ebced4c.png)

**Comment by AGulev** [comment]
@Insality Is it correct in the engine or in the editor?

**Comment by Insality** [comment]
> @Insality Is it correct in the engine or in the editor?

It's incorrect in editor and correct in the game

**Comment by megalanthus** [comment]
Let me add:
If you add a layer with an arbitrary name to the inner component (inner_component), the main thing is that it is above the text layer, then everything starts to work well. But! If you add another layer to the component and place it above the layer that is used in the internal component (inner_component), then the bug will repeat. Again, if you add a second layer with a custom name to the inner_component above text, then everything will be fine.
