### ISSUE TITLE
Can not open GUI n Editor on Ubuntu 20.04.3 LTS

### ISSUE THREAD

**Issue by paweljarosz** [defold/defold#6359]
### Expected behaviour
Opening GUI component correctly
### Actual behaviour
When opening GUI the error occurs and nothing is opened/visible in the Editor
### Steps to reproduce
Restarting Defold does not resolve the issues. It happens in any project I open. Scripts are opening normally. Only objects with visual components.
<hr/>

<table>
<tr><td>Build time</td><td>2021-10-18T08:40:15.071173</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>6bfeea3b13d7b8920483ea2cba9c181a8650b84d</td></tr>
<tr><td>Defold engine sha</td><td>6bfeea3b13d7b8920483ea2cba9c181a8650b84d</td></tr>
<tr><td>Defold version</td><td>1.2.188</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"c8c22b76ebeb41849fb1ebf6b7079f27"'>c8c22b76ebeb41849fb1ebf6b7079f27</a></td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) UHD Graphics (CML GT2)</td></tr>
<tr><td>GPU Driver</td><td>OpenGL ES-CM 1.1 Mesa 21.0.3</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.11.0-46-generic</td></tr>
<table>

**Comment by britzl** [comment]
Solved by `MESA_GL_VERSION_OVERRIDE=2.1`:

https://forum.defold.com/t/problem-with-displaying-visual-components-on-ubuntu-20-04/70234/3?u=britzl
