### ISSUE TITLE
When I try to create or open a new game object the editor crashes

### ISSUE THREAD

**Issue by arthursiq5** [defold/defold#6362]
When I try to open a game object or create a new game object, the engine crashes and returns this error:

```
(java:10595): Gdk-WARNING **: 23:34:44.746: XSetErrorHandler() called with a GDK error trap pushed. Don't do that.
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f85a5053c0c, pid=10595, tid=10625
#
# JRE version: OpenJDK Runtime Environment (11.0.1+13) (build 11.0.1+13)
# Java VM: OpenJDK 64-Bit Server VM (11.0.1+13, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libdrm_nouveau.so.2+0x4c0c]
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P %E" (or dumping to /home/arthur/Projetos/Defold-x86_64-linux/Defold/core.10595)
#
# An error report file with more information is saved as:
# /home/arthur/Projetos/Defold-x86_64-linux/Defold/hs_err_pid10595.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

How to fix it?

**To Reproduce**

- Create a new game object
- Try to open it

**Expected behavior**
The engine should open the game object, but it just crashes and closes

**Defold version (REQUIRED):**
  - Version [e.g. 1.2.155]
  - version 1.2.191 c317904

**Platforms (REQUIRED):**
 - Platforms: Linux
 - OS: Ubuntu 20.04.03 LTS 64 bits
 - Device: Intel Core i3-4170 15 GB RAM

**Logs:**
[hs_err_pid10047.log](https://github.com/defold/defold/files/7967614/hs_err_pid10047.log)
[hs_err_pid10595.log](https://github.com/defold/defold/files/7967615/hs_err_pid10595.log)

**Comment by britzl** [comment]
@arthursiq5 I would try this solution:

https://github.com/defold/defold/issues/5599#issuecomment-787126477

From FAQ: https://defold.com/manuals/linux/#q-the-defold-editor-crashes-when-opening-a-collection-or-game-object-and-the-crash-refers-to-libffiso

**Comment by arthursiq5** [comment]
> @arthursiq5 I would try this solution:
> 
> [#5599 (comment)](https://github.com/defold/defold/issues/5599#issuecomment-787126477)
> 
> From FAQ: https://defold.com/manuals/linux/#q-the-defold-editor-crashes-when-opening-a-collection-or-game-object-and-the-crash-refers-to-libffiso

The bug is the same now, but with more data:

![Captura de tela de 2022-01-31 21-54-32](https://user-images.githubusercontent.com/43865533/151897127-7069951b-394a-4091-9f1a-186e6150
[hs_err_pid10047.log](https://github.com/defold/defold/files/7975158/hs_err_pid10047.log)
[hs_err_pid10595.log](https://github.com/defold/defold/files/7975159/hs_err_pid10595.log)
[hs_err_pid42223.log](https://github.com/defold/defold/files/7975160/hs_err_pid42223.log)
[hs_err_pid44541.log](https://github.com/defold/defold/files/7975161/hs_err_pid44541.log)
cf47.png)

**Comment by britzl** [comment]
Ok, and what if you try the `MESA_LOADER_DRIVER_OVERRIDE` workaround instead?

```
$ MESA_LOADER_DRIVER_OVERRIDE=i965 ./Defold
```

https://defold.com/manuals/linux/#q-why-am-i-getting-comjogampopenglglexception-graphics-configuration-failed-when-launching-defold

**Comment by arthursiq5** [comment]
It works, thanks
