### ISSUE TITLE
Scaling .convexshapes

### ISSUE THREAD

**Issue by totebo** [defold/defold#6373]
**Describe the bug (REQUIRED)**
Collision objects using .convexshape Collision Shapes are scaled incorrectly.

**To Reproduce (REQUIRED)**
Create a collection containing the collision shape with a collectionfactory with a scale other than 1.0:
`local game_object_ids = collectionfactory.create("/go#collectionfactory", nil, nil, nil, 0.5)`

**Expected behavior (REQUIRED)**
The collision shapes should scale without distorting.

**Defold version (REQUIRED):**
1.2.191

**Platforms (REQUIRED):**
 macOS.

**Minimal repro case project (OPTIONAL):**
[ScalingCustomCollisionShapes.zip](https://github.com/defold/defold/files/7992916/ScalingCustomCollisionShapes.zip)

**Additional context (OPTIONAL):**
The issue only seems to only apply when using collection factories. All these cases work as expected:
- Scale a collection containing the collision shape inside the editor.
- Scale a game object containing the collision shape inside the editor.
- Create a game object containing the collision shape with a factory with a scale other than 1.0.

**Comment by britzl** [comment]
> The issue only seems to only apply when using collection factories. All these cases work as expected:
> 
> * Scale a collection containing the collision shape inside the editor.
> * Scale a game object containing the collision shape inside the editor.
> * Create a game object containing the collision shape with a factory with a scale other than 1.0.

This is a good find and it should help figure out the issue! Thanks.

**Comment by britzl** [comment]
In the shared example the collection looks like this:

```
+--track_part
   +--art
   |  +--model
  +--physics
      +--collisionobject1
      +--collisionobjectn
```

If the model component and collision objects are moved from their respective child game objects to the track_part root object it also works.

**Comment by britzl** [comment]
I understand. It's a finding from my initial testing.
