### ISSUE TITLE
Editor crash, after click on wrong link in logs

### ISSUE THREAD

**Issue by SalavatR** [defold/defold#6382]
I log the time in hh:mm:ss format,
hh:mm is defined as a link, when you click on it the editor freezes 

**To Reproduce (REQUIRED)**
print("10:34:45")

**Defold version (REQUIRED):**
  - Version [1.2.192]

**Platforms (REQUIRED):**
 - OS: [Windows 11]

**Comment by britzl** [comment]
What I believe happens is that the editor is parsing log entries in search of things that might be a reference to a filename and a line number to let users click to open the file and scroll to the line. Example: `my.script:100` which references the file `my.script` and line 100 of that file. This is useful for instance when a stacktrace is printed.

In this case it is obviously not a line number in a file though. There was a similar report perhaps a year ago and I actually thought we solved this issue then, but apparently there's still a problem in the code.

**Comment by vlaaad** [comment]
The issue should be fixed in the latest editor.
