### ISSUE TITLE
Disabling a textured GUI node after being spawned hogs the Gui.Animations count

### ISSUE THREAD

**Issue by dapetcu21** [defold/defold#6384]
**Describe the bug (REQUIRED)**
This started with a pretty complex scene that was hitting the animation cap. I noticed that `Gui.Animations` is always a high constant number (50, even 200-ish, depending on how complex the scene hierarchy is), regardless of the number of active animations.

I narrowed down the issue to the fact that we had some disabled nodes that we were using as "templates" for spawning lists. This is a common pattern: You make a node in the editor for one item, then in script you disable it, then `clone_tree`-it as many times as needed to make the list.

The problem is that, even for nodes that have one-frame flip-book animations, an animation would get created at spawn time which would never resolve (since the node is disabled) and it would contribute to the `Gui.Animations` count. It's quite easy to reach the 1024 GUI animation limit this way for complex scenes.

This is even a problem when not disabling the nodes, especially since the max animations is hardcoded to 1024. Add any actual animations you want to do to that and this puts a hard cap on how many nodes you can spawn in one frame. Even though I set max nodes in the GUI scene to 2048 (which is anyway low for some complex interfaces), I cannot use all of them.

**To Reproduce (REQUIRED)**
1. Add a GUI node with a static texture on it
2. In `init()`: `gui.set_enabled(node, false)`
3. Look at the profiler and see that `Gui.Animations` is 1

**Expected behavior (REQUIRED)**
Setting single-frame textures on GUI nodes shouldn't create an animation.

**Defold version (REQUIRED):**
  - 1.2.192

**Platforms (REQUIRED):**
 - Platforms: All

**Minimal repro case project (OPTIONAL):**
[test-gui-anims.zip](https://github.com/defold/defold/files/8032711/test-gui-anims.zip)

**Comment by britzl** [comment]
I'm thinking that it doesn't make sense to have a lower max animation count than a max node count. The max node count is 8192 (hard cap) but we always set the max animation count to 1024. Why?

https://github.com/defold/defold/blob/dev/engine/gamesys/src/gamesys/components/comp_gui.cpp#L673-L675

We could perhaps set the initial capacity to a lower value (25 or 50% of max) and grow to max animations if needed?

https://github.com/defold/defold/blob/dev/engine/gui/src/gui.cpp#L337

**Comment by britzl** [comment]
> Why should it be the same?  

In theory I could decide to use 8192 animated nodes, for instance if I'm using the GUI to create a game instead of game objects with sprites. In that case it is rather strange that we don't allow all nodes to be animated. 

> It's very strange though that the enable=false creates an animation somehow, and that is the actual bug reported here

Yes, I'll investigate this.

**Comment by dapetcu21** [comment]
Yup. Disabled nodes using up an animation right after they are created (and possibly on play_flipbook too) is the main issue here.

As for increasing the animation cap, I'd suggest a soft cap with no hard cap (the array is preallocated for some number of animations and it grows if it's actually necessary). 

Also, note that the theorethical max number of animations is the max number of nodes times the number of properties on a node (since each prop can be independently animated). So the animation count can grow quite fast.

**Comment by britzl** [comment]
Oh, I thought this was only an issue for flipbook animations and not property animations.

**Comment by dapetcu21** [comment]
The "animation on spawn" problem is just for flipbook animations, but in that same animation budget you want to also do all sorts of other animations.

I guess there's two issues, the first aggravating the second:

1. Flipbook animations on spawn make it easy to hit the anim cap

2. The anim cap is too easy to hit to begin with in a moderately complex scene

**Comment by britzl** [comment]
Some findings will looking into this:

* A 1 frame "animation" will NOT create an animation if it has playback mode set to None. This is something to consider if using a tilesource with 1 frame animations.

* When an atlas is used and you use a single image it seems like this implicit 1 frame "animation" is assigned a playback mode of once forward. Changing this would be a breaking change but I also think it would make sense if these implicit animations were given a playback mode of None.

**Comment by britzl** [comment]
We can't remove the animation when the node is disabled. When a node is disabled the animation is simply paused and will continue when the node is enabled again.

I do not think this is to be considered a bug. We should treat this as a feature request and allow developers more control over the max animations in gui scenes.

Two things to discuss:

1. Increase the max animations
   * Set it to a fixed higher number
       * We can either set it to something "high enough" or to an actual max based on max nodes * number of animatable properties on a node
   * Let it grow dynamically
   * Make it configurable per gui scene
2. Change implicit one frame atlas animations to playback mode None.
   * This is a breaking change.
       * Workaround for users is to actually create an animation in the atlas and set a playback mode
       * This will only mitigate the problem to some extent and not fully fix it
       * Another option is for @dapetcu21 and others to create a one frame animation and set playback mode to None. This is a lot of work though.

**Comment by dapetcu21** [comment]
Regarding the breaking change, I'm thinking the actual impact isn't that big... I think the only behaviour difference is that the animation callback doesn't get called, right? Which isn't really useful anyway in the context of a single-frame animation. I doubt anyone's using it.

**Comment by britzl** [comment]
> Which isn't really useful anyway in the context of a single-frame animation. I doubt anyone's using it.

Probably not very common. But let's say you have an animation system of some kind where you set a busy flag or something while an animation plays and clear it when it is done. And you use this for some character animations. When the player is making a jump and lands you play the "landing" animation and it just so happens that it is a single image (because your artist haven't had the time to create more frames or whatever) and in such a case you'll never get a callback and you're forever stuck in the "landing" animation.

**Comment by britzl** [comment]
Possible special solution/workaround is to immediately play and end one frame animations when box nodes are created. This way they won't take up a slot in the animation list.
