### ISSUE TITLE
tilemap.set_tile(map_id, layer, tile_x, tile_y, 0) can crash under certain circumstances

### ISSUE THREAD

**Issue by greay** [defold/defold#6386]
**Describe the bug (REQUIRED)**
Under certain circumstances, erasing tiles in a tilemap using tilemap.set_tile(map_id, layer, tile_x, tile_y, 0) can cause the game to crash.

**To Reproduce (REQUIRED)**
*Precise* repro steps are unknown, but I've narrowed it down to a pretty small repro case project, included.

**Expected behavior (REQUIRED)**
It should not crash. Worst case, it should log an error, but the error should point to what game code caused the error – as it is, the game doesn't log anything useful.

**Defold version (REQUIRED):**
  - Version 1.2.192

**Platforms (REQUIRED):**
 - Platforms: macOS
 - OS: macOS 11.6.2

**Minimal repro case project (OPTIONAL):**
Please attach a minimal project where the bug is reproduced. This will greatly help the person trying to investigate and fix the bug.
[tiled-test 2.zip](https://github.com/defold/defold/files/8045209/tiled-test.2.zip)

**Logs (OPTIONAL):**
```
ERROR:GAMESYS: SetGridShapeHull: <row,column> out of bounds
Assertion failed: (fixture != 0x0), function GetFixture, file physics_2d.cpp, line 655.
INFO:CRASH: Successfully wrote Crashdump to file: /Users/greay/Library/Application Support/Defold/_crash
ERROR:CRASH: CALL STACK:

# 0 pc      0x91d7d libc++abi.dylib _sigtramp+29
```

**Workaround (OPTIONAL):**
n/a

**Additional context (OPTIONAL):**
While all of the extra logic has been stripped out, the purpose of the code is to replace certain tiles on the map with animated characters or objects.

**Comment by britzl** [comment]
Minimal repro: [Archive.zip](https://github.com/defold/defold/files/8164307/Archive.zip)
