### ISSUE TITLE
The editor takes a very long time to process new assets added using external tools

### ISSUE THREAD

**Issue by AGulev** [defold/defold#6401]
**Describe the bug (REQUIRED)**
Adding the ready for use assets into the project folder in a big project takes too long. Up to a few minutes to read all the changes.

(ready for use assets means a collection with many images which was generated in an external editor, for example)

**To Reproduce (REQUIRED)**
1. Open a big project
2. Switch to an external text editor
3. Paste content into the collection file
4. Return to the editor window
Editor hangs for a few minustes

**Expected behavior (REQUIRED)**
Editor should read changes faster

**Defold version (REQUIRED):**
1.2.188

**Comment by britzl** [comment]
Closed by https://github.com/defold/defold/pull/6659
