### ISSUE TITLE
Iteration through gui nodes doesn't take into account nodes in template

### ISSUE THREAD

**Issue by AGulev** [defold/defold#6403]
**Describe the bug (REQUIRED)**
Editor script doesn't itarate nodes in template.

**To Reproduce (REQUIRED)**
[test.editor_script.zip](https://github.com/defold/defold/files/8056676/test.editor_script.zip)
1. Create a GUI component
2. put another GUI component as a template for the first one
3. Try to run script from the attachment on a node from template

>ERROR:EXT: Print Ids's "run" in /test.editor_script failed:
ERROR:EXT: /test.editor_script:17 BoxNode has no "id" property

**Expected behavior (REQUIRED)**
This field is in protobuf but for some reason editor script can't get access to it. 
It should be possible to get access node from templates

```
nodes {
  position {
    x: 0.0
    y: 0.0
    z: 0.0
    w: 1.0
  }
  rotation {
    x: 0.0
    y: 0.0
    z: 0.0
    w: 1.0
  }
  scale {
    x: 1.0
    y: 1.0
    z: 1.0
    w: 1.0
  }
  size {
    x: 200.0
    y: 100.0
    z: 0.0
    w: 1.0
  }
  color {
    x: 1.0
    y: 1.0
    z: 1.0
    w: 1.0
  }
  type: TYPE_BOX
  blend_mode: BLEND_MODE_ALPHA
  texture: ""
  id: "template/t_box"
  xanchor: XANCHOR_NONE
  yanchor: YANCHOR_NONE
  pivot: PIVOT_CENTER
  adjust_mode: ADJUST_MODE_FIT
  parent: "template"
  layer: ""
  inherit_alpha: true
  slice9 {
    x: 0.0
    y: 0.0
    z: 0.0
    w: 0.0
  }
```

**Comment by vlaaad** [comment]
I'm investigating this issue. In the box node, the `Id` property is available as `generated_id` instead of `id` in the editor scripts (you can see this if you hover over the `id` property). A modified version that prints the id of that node looks like this:

```lua
local M = {}

function M.get_commands()
    return { {
        locations = {"Outline"},
        label = "Print Ids",
        query = {selection = {
            type = "outline", cardinality = "many"
        }},
        active = function(opts)
            return true
        end,
        run = function(opts)
            local ids = opts.selection
            for k, v in pairs(ids) do
                local value = 
                    (editor.can_get(v, 'id') and editor.get(v, 'id')) 
                    or (editor.can_get(v, 'generated_id') and editor.get(v, 'generated_id')) 
                    or '???'
                print(k, value)
            end
            return {}
        end
    }}
end

return M
```
Why it's `generated_id` instead of `id` is to be investigated...

**Comment by britzl** [comment]
@Insality could the above work for you?

**Comment by Insality** [comment]
@britzl @vlaaad 
Yea, it works! 🙃 

sorry for the late reply
