### ISSUE TITLE
Show the bundling steps in Editor logs

### ISSUE THREAD

**Issue by AGulev** [defold/defold#6408]
Bundling progress bar isn't informative. It would be nice to show building process steps in log as well as bob.jar does but in the editor together with a progress bar.

**Comment by britzl** [comment]
Pipe all bob output to editor console.

**Comment by AGulev** [comment]
@ekharkunov-ms could you pls add more details?

**Comment by ekharkunov-ms** [comment]
Sure.
When we build project from Defold editor we don't see any log statements about what currently doing. 
When we build project from command line we see some statements about starting compiling engine, finish compiling engine, building assets, signing ipa and etc.
And also we can turn on more verbose output with '-v' option.

So it will be cool if we have something similar in Defold editor. It could help to understand on what building stage we are.

**Comment by vlaaad** [comment]
Some more notes:
- if the build server specified in the preferences is invalid, there are no build errors shown.
- build errors from bob are lacking.
If these 2 issues were fixed, there would be no need in showing the build log. Although verbose Bob output is sometimes useful.
