### ISSUE TITLE
Add documentation with a simple example about creation of a new extension using extension system.

### ISSUE THREAD

**Issue by AGulev** [defold/defold#6412]
**Is your feature request related to a problem? Please describe (REQUIRED):**
It would be nice to have a simple example and a manual about how to add a simple component in a native extension.

**Describe the solution you'd like (REQUIRED):**
Having of such a manual would help developers to implement their own components like `Click Zone`, `Data component` etc.

**Describe alternatives you've considered (REQUIRED):**
At the moment it possible to take a look how the new spine extension works: https://github.com/defold/extension-spine

**Comment by JCash** [comment]
Added another example and some documentation here:
https://github.com/defold/extension-simpledata
