### ISSUE TITLE
Editor rounds values when moving objects

### ISSUE THREAD

**Issue by aglitchman** [defold/defold#6414]
**Describe the bug (REQUIRED)**
The editor rounds values when moving objects. 

**To Reproduce (REQUIRED)**

https://user-images.githubusercontent.com/193258/154264998-9bf5deec-2e9a-4efb-b978-4c2500fbe067.mp4

**Expected behavior (REQUIRED)**
The editor should not affect the values after the decimal point, i.e.:
- `0.454545 + 1` should be `1.454545`, but not `1.455`.
- `0.454545 - 1` should be `-0.545455`, but not `-0.545`.

**Defold version (REQUIRED):**
  - Version 1.2.192

**Platforms (REQUIRED):**
 - OS: Windows 10

**Comment by d954mas** [comment]
up)

**Comment by d954mas** [comment]
I am working on 2D game. We use z to sort object by it y position. But also some objects consist of multiple sprites with different Z.


https://github.com/defold/defold/assets/2655263/62d47ecb-500d-4972-9690-fbf1a7a5a534


I use 0.0001 z for that sprites.
I use 0.001 z for some special cases, to fix some visual artifacts, when one object should be after another.
All other z i used for movement.

As a workaround i can
1)Always check Z postion after move in editor
2)Changed my z values to bigger value. But for this i need make changes in current logic and check that everything is keep working.

**Comment by matgis** [comment]
A fix has been merged. Hope this helps!
