### ISSUE TITLE
Read editor preferences from a file in the project folder if it exist.

### ISSUE THREAD

**Issue by AGulev** [defold/defold#6415]
**Is your feature request related to a problem? Please describe (REQUIRED):**
Different projects may use different preferences. That would be useful to have a possibility to read preferences from the project folder itself such a file exists in the project folder.
<img width="600" alt="image" src="https://user-images.githubusercontent.com/2209596/154277850-52ab114d-4d4f-415f-934b-2f8ab2974b6c.png">
<img width="597" alt="image" src="https://user-images.githubusercontent.com/2209596/154277883-e4f07982-883c-4cf8-8291-1fb20409e745.png">
<img width="597" alt="image" src="https://user-images.githubusercontent.com/2209596/154277924-4a6db9fe-f836-4511-a0fd-87e00f440892.png">

**Comment by matgis** [comment]
I think it makes sense for projects to control the Build Server setting from a file committed into the project. But all the other preferences are user-preferences in my mind. Although it might be useful to have some of these user-settings per-project, they shouldn't be committed into the project and apply to all users.

**Comment by vlaaad** [comment]
Is this an issue about storing per-user preferences in a file at a known location or is it about making the build server a checked-in per-project setting?

**Comment by AGulev** [comment]
@vlaaad it's about an ability to specify the build serve URL per project. It is possible that so other settings may be specified on per-project basis. 
Feel free to change the ticket and create a new one for the second case if you need it

**Comment by vlaaad** [comment]
Shouldn't Bob be able to pick up this per-project build server setting somehow? Along with headers...

**Comment by AGulev** [comment]
@vlaaad bob used only for bundle creation, and it has a parameter to do so, that means it's up to a Bob user to set this parameter. 
Build (cmd+b) up to the editor. Also the editor sets the parameter for bob when bundle (e.g. `--build-server https://build-stage.defold.com`)

**Comment by vlaaad** [comment]
Yeah but if there is a specially intended checked-in build server for a project, maybe Bob should pick it up automatically? Because it is intended and checked in and exists in a file in the repo...

**Comment by AGulev** [comment]
@vlaaad maybe, but I think it's not so important, since if somebody builds using bob, it's already possible to do. This will be something like a `*.sh` file in your repo where you specify what want. In case with the editor, you can't do that (you have to manually change this value in Preferences)
