### ISSUE TITLE
Flicking with 3d skeleton animation

### ISSUE THREAD

**Issue by Mulderua** [defold/defold#6427]
If T-pose substantially different than animation pose. It flickers before each new iteration.
Problem was found when animation was set to default animation, but reporoduciable also when animation set from scrip.

**To Reproduce**
1. Take a character in T-pose
2. Tilt character body on first frame so It noticeable
3. Made some animation loop
4. Add model to collection
5. Set default animation
6. Build and run game

**Expected behavior**
Seemles animation loop

**Actual behavior**
Animation flicking

**Defold version:**
  - Version 1.2.192

**Platforms (REQUIRED):**
 - Platforms: Windows, HTML5
 - OS: Windows 10

**Minimal repro case project:**
https://github.com/Mulderua/animation-flick-problem-example

**Screenshots:**
https://youtu.be/_GbCoZ1O-Uk

**Additional context (OPTIONAL):**
I included .blend file to repo. Everething in main folder/

**Comment by KorolevSoftware** [comment]
it's actual for me.

**Comment by Morgerion** [comment]
For me, this solution worked - everything is done with Blender:

1. when importing FBX, specify animation offset 0.0
![image](https://user-images.githubusercontent.com/7888071/187268636-f5379da0-3ec6-4a01-84dd-4cbc868ce520.png)

2. directly in Blender, on the animation timeline, specify start from 0.
![image](https://user-images.githubusercontent.com/7888071/187268838-fefd5e6f-7d5a-4030-a9b6-9341468777cd.png)

3. when baking the animation, ensure that the start frame is set to 0.
![image](https://user-images.githubusercontent.com/7888071/187269064-344a07c8-0b3c-48f6-9269-57d7e8973ee7.png)
 
That's the end of it.
I take the animations from Mixamo as separate FBX files. I export to DAE. And all animations work fine.

**Comment by JCash** [comment]
Also, in the upcoming version of our model importer, it seems to be fixed:
https://forum.defold.com/t/new-gltf-model-importer-beta-test/71436

**Comment by AGulev** [comment]
@Mulderua 
is it still an issue? Did you check it using new importer?

**Comment by AGulev** [comment]
outdated
