### ISSUE TITLE
Error while fetching library (extension-spine)

### ISSUE THREAD

**Issue by Palisand** [defold/defold#6435]
I was unsure of posting this here or in https://github.com/defold/extension-spine because I don't know if this is an issue with the extension or with Defold. Please let me know if I should post this in the `extension-spine` repo instead.

### Expected behaviour

Fetching the https://github.com/defold/extension-spine/archive/refs/tags/2.0.1.zip library goes smoothly.

### Actual behaviour

Fetching the library yields an error:

```
clojure.lang.Compiler$CompilerException: Syntax error compiling at (59:37).
java.lang.IllegalStateException: var: gui/validate-required-gui-resource is not public
```

This also appears to cause Defold to crash on startup. I had to manually remove the dependency from the `plugins` directory and from the `game.project` file to get the project to open.

### Steps to reproduce

1. Add https://github.com/defold/extension-spine/archive/refs/tags/2.0.1.zip to `game.project::Dependencies`
2. Run `Project` -> `Fetch Libraries`
3. Observe error

However, I am able to see the `defold-spine` extension in the file hierarchy.

<hr/>

<table>
<tr><td>Build time</td><td>2022-02-16T09:54:22.680586</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>12cd9306bcb9d37dcc5c97674e395266321a9d22</td></tr>
<tr><td>Defold engine sha</td><td>84a9c89dfd5a2c3818c01e7c6777169272d9390b</td></tr>
<tr><td>Defold version</td><td>1.2.192</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"42e19825332f4b8eb2dde3a550cfcf12"'>42e19825332f4b8eb2dde3a550cfcf12</a></td></tr>
<tr><td>GPU</td><td>Intel(R) Iris(TM) Plus Graphics 655</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-18.4.6</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.16</td></tr>
<table>

**Comment by britzl** [comment]
Please update to the latest version of the Spine extension: https://github.com/defold/extension-spine/releases

**Comment by britzl** [comment]
You may also need to run the 1.2.193 beta of Defold (https://forum.defold.com/t/defold-1-2-193-beta/70405).

**Comment by JCash** [comment]
Thanks for the report. That issue is fixed in the beta version of the editor, I suggest you switch to that version, thx.

**Comment by Palisand** [comment]
You all work fast! I'll test this out after work and close this ticket once I confirm the error is no longer being encountered. Thank you!
