### ISSUE TITLE
The editor does not give enough information about why the bundle process fails

### ISSUE THREAD

**Issue by Makoren** [defold/defold#6436]
Edit (by @britzl):

The editor should show more information when the bundle process fails. When bundling with bob.jar you see which file caused a problem and also a full stacktrace. This information is not shown in the editor, only the type of Java exception:

![Screenshot 2022-02-24 at 08 17 45](https://user-images.githubusercontent.com/1300688/155477095-a3b70839-88bf-46a0-809a-b7ee6d68317b.png)

(See comments for actual error)

----

Original report below:

### Expected behaviour
Browser should be running a HTML5 build of the game.

### Actual behaviour
Editor throws an unknown Java error while building.

### Steps to reproduce
Build the [attached project](https://github.com/defold/defold/files/8129985/BrackeysJam2022_1.zip) for HTML5, it is a WIP version of a game jam game due in a few days. It's a snapshot of the first commit with this error, it builds fine with every previous commit I made. The details of this commit are [here](https://github.com/Makoren/BrackeysJam2022_1/commit/1f61b62c5075081781540df89af2a2c509ac08cb).

<hr/>

<table>
<tr><td>Build time</td><td>2022-02-16T09:54:22.680586</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>12cd9306bcb9d37dcc5c97674e395266321a9d22</td></tr>
<tr><td>Defold engine sha</td><td>84a9c89dfd5a2c3818c01e7c6777169272d9390b</td></tr>
<tr><td>Defold version</td><td>1.2.192</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"b7a7376c3089473aac8048a3eefb9400"'>b7a7376c3089473aac8048a3eefb9400</a></td></tr>
<tr><td>GPU</td><td>Apple M1</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 76.3</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.16</td></tr>
<table>

**Comment by britzl** [comment]
Note: I get the same error when I try to bundle for macOS

**Comment by britzl** [comment]
Building with bob.jar tells us why:

```
The build failed for the following reasons:
ERROR screens/playground/playground.collection:0 null
  java.lang.NullPointerException
  java.base/java.lang.String.<init>(String.java:614)
  com.dynamo.bob.pipeline.ProtoUtil.merge(ProtoUtil.java:28)
  com.dynamo.bob.pipeline.CollectionBuilder.countComponentInResource(CollectionBuilder.java:179)
  com.dynamo.bob.pipeline.CollectionBuilder.countComponentsInCollectionRecursively(CollectionBuilder.java:206)
  com.dynamo.bob.pipeline.CollectionBuilder.countAllComponentTypes(CollectionBuilder.java:228)
  com.dynamo.bob.pipeline.CollectionBuilder.transform(CollectionBuilder.java:482)
  com.dynamo.bob.pipeline.CollectionBuilder.transform(CollectionBuilder.java:58)
  com.dynamo.bob.ProtoBuilder.build(ProtoBuilder.java:90)
  com.dynamo.bob.Project.runTasks(Project.java:1343)
  com.dynamo.bob.Project.doBuild(Project.java:1135)
  com.dynamo.bob.Project.build(Project.java:584)
  com.dynamo.bob.Bob.mainInternal(Bob.java:699)
  com.dynamo.bob.Bob.main(Bob.java:748)
```

**Comment by britzl** [comment]
![Screenshot 2022-02-24 at 08 16 25](https://user-images.githubusercontent.com/1300688/155476521-ec60be8c-e452-42fc-9b6b-a9a490d4ac5d.png)

**Comment by AGulev** [comment]
<img width="1505" alt="image" src="https://github.com/defold/defold/assets/2209596/7034f1b6-57ab-4d10-9dda-7a960af63582">
works now
