### ISSUE TITLE
Different behavior for require() and _G.require()

### ISSUE THREAD

**Issue by ze0nni** [defold/defold#6438]
I use haxe and hxdefold for generate loa code.
In haxe I can write external binding like:

```
@:luaRequire("my_module")
extern class MyModule {
}
```
this code translate to:
```
_my_module = _G.require("my_module")
```

But on start I have exception

```
/main/main.script:1: module 'my_module' not found:
```

When I remove `_G` it fix problem

**Comment by britzl** [comment]
Ah, we do not properly detect this when parsing the Lua syntax tree:

https://github.com/defold/defold/blob/dev/com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/DefoldLuaParser.java#L198
