### ISSUE TITLE
Project gets 'ready' but does not run

### ISSUE THREAD

**Issue by AbdulGhaforRahmatzada** [defold/defold#6443]
### Expected behaviour
when I try build my project it builds it successfully but then it remains at 'ready' and doesn't run
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2022-02-16T09:53:28.206075</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>12cd9306bcb9d37dcc5c97674e395266321a9d22</td></tr>
<tr><td>Defold engine sha</td><td>84a9c89dfd5a2c3818c01e7c6777169272d9390b</td></tr>
<tr><td>Defold version</td><td>1.2.192</td></tr>
<tr><td>GPU</td><td>Intel(R) UHD Graphics 600</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 - Build 27.20.100.9171</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by AbdulGhaforRahmatzada** [comment]
error found - there was a syntax error

**Comment by britzl** [comment]
Happy to hear that you found the problem! Although it is strange that you didn't get any indication what was wrong?

**Comment by AbdulGhaforRahmatzada** [comment]
Oh thank you for getting back to me. No because I'm working on a small laptop I tend to drag down the console and error logs (so it's hidden) - so when I was running the code there was a syntax error just the letter 'a' but it was hidden and I couldn't understand why. It was like this for 3 days, but yea I finally managed to work it out.

Thank you so much

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
