### ISSUE TITLE
Editor: add icons to properties fields to differentiate URL/hash

### ISSUE THREAD

**Issue by aglitchman** [defold/defold#6444]
**Is your feature request related to a problem? Please describe (REQUIRED):**
I have to append `_url` or `_id` (or `_hash`) to script properties names to differentiate their types in the editor, i.e.

```lua
go.property("script_url", msg.url(""))
-- or
go.property("script_id", hash(""))
```

Because they look like a field for a string type:
![image](https://user-images.githubusercontent.com/193258/155905525-85194f9b-09ba-4e56-acfb-6bd8196c6061.png)

**Describe the solution you'd like (REQUIRED):**
I would like not to append those suffixes:
```lua
go.property("script", msg.url(""))
```

And see icons like that:
![image](https://user-images.githubusercontent.com/193258/155905746-ee850d76-28a6-47fc-9647-cdf3779dd7e1.png)

**Additional context (OPTIONAL):**
It's just an idea :) 

Plus, you can add "123" for the number fields:
![image](https://user-images.githubusercontent.com/193258/155905885-e3b9678f-d4bf-4a47-9fc1-c8741af71259.png)

**Comment by AGulev** [comment]
related https://github.com/defold/defold/issues/4064
