### ISSUE TITLE
No sound below iOS 15.0

### ISSUE THREAD

**Issue by lecricreator** [defold/defold#6451]
**Below ios 15.0 they're not song, but after it works**
I would like to debug to see where the error is, but I can't. 

**To Reproduce**
You must have an Apple phone before 15.0
To test quickly you can test my game : https://apps.apple.com/us/app/drop-light/id1590493987

I test with all my Apple phone : 
![image](https://user-images.githubusercontent.com/53663215/156649390-53a83458-b687-4328-8ab8-86cd1d023bcf.png)

**Project crash test**
I've create a simple project for debug and understand the problem with one musical loop and if you push, there is a sound play.
 
https://github.com/lecricreator/Defold-no-sound-on-ios
I've test on one phone.
![image](https://user-images.githubusercontent.com/53663215/156650558-b9a75d0f-f5fd-49a8-89c8-5b80b0797b4b.png)

**Defold version (REQUIRED):**
  - Version 1.2.192

**Platforms:**
iOS

**Comment by JCash** [comment]
I've tested the app with 1.2.192 on an iPhone Xs Max, iPhoneOS 14.8, and I didn't notice any issues.

**Comment by lecricreator** [comment]
Yes, it's strange.
I don't know what else to do.

I've other data, but it doesn't resolve the problem.

```
DR0P Light no sound on ios

iphone 7 (2016)     ios 15.3.1         = work
iphone 8 (2017)     ios 14.8           = doesn't work
iPhone Xs Max (2018)ios 14.8           = work
ipad mini 5 (2019)  ios 15.3.1         = work
Iphone SE 2020      ios 15.3.1         = doesn't work
```

**Comment by AGulev** [comment]
@lecricreator could you pls check of you can repo this issue using this alpha build d.defold.com/archive/dev/41e2a689dbf78063a2f342d8e728d4e2b279972e/dev/editor2/Defold-x86_64-darwin.dmg 
?

**Comment by AGulev** [comment]
pls open this ticket again if you'll repo this issue in the future using the latest version of Defold
