### ISSUE TITLE
Using resource.set_texture changes texture of ALL sprites using same atlas

### ISSUE THREAD

**Issue by BitsAtPlayDev** [defold/defold#6468]
**Describe the bug **
Using resource.set_texture on any sprite, changes texture on ALL sprites using same atlas

**To Reproduce **
1. Create an empty project
2. Create two sprites using the same atlas (The sprites can refer to same image within atlas, or different images) 
3. Use example code from 'resource.set_texture()" entry in API docs to update texture of one of the sprites
4. Both sprites have been updated to use new texture

**Expected behavior **
Only sprite referred to in call to 'set_texture' should have it's texture updated.

**Defold version: **
  - Version 1.3.0

**Platforms : **
 - Platforms: Android, MacOS 
 - OS: Android 8.0.0; MacOS Montery 12.1
 - Device: LG G6

**Minimal repro case project: **
There are two attachments: One using custom sprite materials & custom render-script, one using the default sprite materials & default render-script

[SetTextureProblem_customMaterials.zip](https://github.com/defold/defold/files/8247741/SetTextureProblem_customMaterials.zip)
[SetTextureProblem_defaultMaterials.zip](https://github.com/defold/defold/files/8247742/SetTextureProblem_defaultMaterials.zip)

**Comment by JCash** [comment]
That is true, if you replace the texture, you replace the _entire_ texture.

We currently don't have support to update a region of the texture.
