### ISSUE TITLE
Defold Issue on a school computer

### ISSUE THREAD

**Issue by blockboy05** [defold/defold#6469]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2022-01-10T12:21:05.998327</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>d393bae6a361f86cf2263ab312c9b3cea45253ab</td></tr>
<tr><td>Defold engine sha</td><td>d393bae6a361f86cf2263ab312c9b3cea45253ab</td></tr>
<tr><td>Defold version</td><td>1.2.191</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"fc7839d2de5a458f9ef2c9963a72eb2b"'>fc7839d2de5a458f9ef2c9963a72eb2b</a></td></tr>
<tr><td>GPU</td><td>GDI Generic</td></tr>
<tr><td>GPU Driver</td><td>1.1.0</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
```
editor.debugging.mobdebug$connect_BANG_$fn__42995.invoke.class clojure.lang.ExceptionInfo: Failed to connect to debugger on localhost:8172
    at editor.debugging.mobdebug$connect_BANG_$fn.invoke(mobdebug.clj:341)
    at clojure.lang.AFn.run(AFn.java:22)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.lang.Thread.run(Thread.java:834)
```

**Comment by britzl** [comment]
This seems to be a debugger related issue. Does it work if you do Project->Build?

**Comment by blockboy05** [comment]
no clue works at home but it is a school computer with restrictions when we do F5 though the window opens and then closes again without displaying anything on the display.

**Comment by britzl** [comment]
> when we do F5 though the window opens and then closes again without displaying anything on the display

Pressing F5 will launch the game and attach the debugger. And it seems like your school network prevents the editor debugger from connecting to your game (running on the same computer)

Try Project->Build (CTRL+B) instead. This will run your game without starting the debugger.

**Comment by blockboy05** [comment]
![issue](https://user-images.githubusercontent.com/92528950/158799955-9f6ddb6f-41b9-4ace-962a-2b076a869ad5.png)

**Comment by britzl** [comment]
Ah, that is something different. And yes, this is caused by your GPU/driver not supporting OpenGL 3.1.
