### ISSUE TITLE
Issue when adding GUI layout.

### ISSUE THREAD

**Issue by sinh-png** [defold/defold#6475]
### Expected behaviour
Layout added without any error.

### Actual behaviour
Layout added with error and I can't do anything with it like in the attached video.

### Steps to reproduce
Add a layout.

https://user-images.githubusercontent.com/11591738/158977049-0a51777b-a018-4275-a4bb-5bd2bb200daf.mov

<hr/>

<table>
<tr><td>Build time</td><td>2022-03-15T14:41:06.884849</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>cb4cc114221bf2bdabb1dd3c988fb333dc1e836a</td></tr>
<tr><td>Defold engine sha</td><td>0e77ba11ac957ee01878bbde2e6ac0c9fae6dc01</td></tr>
<tr><td>Defold version</td><td>1.3.0<

/td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"63ed1f5a7c984d9ab29152229bb612d7"'>63ed1f5a7c984d9ab29152229bb612d7</a></td></tr>
<tr><td>GPU</td><td>Intel Iris Pro OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-12.10.12</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.14.6</td></tr>
<table>

**Comment by Dahausa** [comment]
Same here. Exception is at least in my defold instance reproducible.

<table>
<tr><td>Build time</td><td>2022-03-15T14:40:05.532720</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>cb4cc114221bf2bdabb1dd3c988fb333dc1e836a</td></tr>
<tr><td>Defold engine sha</td><td>0e77ba11ac957ee01878bbde2e6ac0c9fae6dc01</td></tr>
<tr><td>Defold version</td><td>1.3.0</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"d86eb0960cab48d0be13440a878d4b13"'>d86eb0960cab48d0be13440a878d4b13</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon(TM) Graphics</td></tr>
<tr><td>GPU Driver</td><td>4.5.13587 Compatibility Profile Context 19.40.40 26.20.14040.0</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by wangdong20** [comment]
Same here. https://github.com/defold/defold/issues/6516

**Comment by vlaaad** [comment]
@sinh-png please check if the issue still persists after updating to the latest editor

**Comment by sinh-png** [comment]
> @sinh-png please check if the issue still persists after updating to the latest editor

I still encounter the issue with the latest version, same system as above.

https://user-images.githubusercontent.com/11591738/164956795-bfb12124-ff9f-4df6-ac14-6ccfe258f620.mov

**Comment by sinh-png** [comment]
> @sinh-png please check if the issue still persists after updating to the latest editor

I don't know what changed but the issue stopped now! There was no new update or anything since I captured the video above. Thank you!
