### ISSUE TITLE
Issue when opening game.project file to edit

### ISSUE THREAD

**Issue by joashchee** [defold/defold#6479]
### Expected behaviour
Double-clicked "game.project" in Assets window, file to open for editing

### Actual behaviour
game.project appears as a tab in editor, but no content appears. Error reporting window pops up

### Steps to reproduce
Double-clicking "game.project" in Assets window. also replicated when using File > Open Assets ... 
No issue opening any other file in Assets

<hr/>

<table>
<tr><td>Build time</td><td>2022-03-18T17:42:13.337690</td></tr>
<tr><td>Defold channel</td><td>dev</td></tr>
<tr><td>Defold editor sha</td><td>2acdbabe5eea1e6f89c4ed541450552c44464401</td></tr>
<tr><td>Defold engine sha</td><td>2acdbabe5eea1e6f89c4ed541450552c44464401</td></tr>
<tr><td>Defold version</td><td>1.3.1</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"964809da8dc04f91ad2bc571319f474d"'>964809da8dc04f91ad2bc571319f474d</a></td></tr>
<tr><td>GPU</td><td>Intel(R) Iris(TM) Graphics 6100</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-12.10.31</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.14.6</td></tr>
<table>

**Comment by joashchee** [comment]
Replicated with a blank new project.

Error :

java.lang.IllegalArgumentException: Cannot format given Object as a Number

**Comment by JCash** [comment]
Hi @joashchee !
THanks for the report, I'm looking into it.

In the meantime, I recommend you move to the stable release again (1.3.1 is the dev release):
https://github.com/defold/defold/releases/tag/1.3.0

**Comment by JCash** [comment]
I have now pushed a fix, and the editor should be built within the hour.
