### ISSUE TITLE
Possibility to stop all property animations on an object at the same time

### ISSUE THREAD

**Issue by coderm4ster** [defold/defold#6492]
**Is your feature request related to a problem? Please describe (REQUIRED):**

In my game project, about 50% of the time when property animations running on game objects or gui nodes have to be stopped at the same time. I can currently do this by calling the go.cancel_animations or gui.cancel_animation functions one after the other with the appropriate property names.

For example:
```
go.cancel_animations("#sprite", "position")
go.cancel_animations("#sprite", "euler.z")
go.cancel_animations("#sprite", ...)
```

In optimal cases, I know what property animations are running, but they may not.

**Describe the solution you'd like (REQUIRED):**

For game objects, the second parameter of go.cancel_animations should be optional:
```
go.cancel_animations(url, [property])
```
If the property parameter is not specified, all property animations running on that game object should be stopped.

For gui nodes, since cancel_animation is not in the plural, I would suggest introducing a new cancel_animations function with a single node parameter:
```
gui.cancel_animations(node)
```
This would be stop all property animation running on the gui node.

**Describe alternatives you've considered (REQUIRED):**

An alternative is to create a lua module, but since the engine is likely to have a function that stops all animations, it seems a better solution if this feature is implemented in the engine.

**Comment by JCash** [comment]
Implementation wise, it should be a small fix to allow a `nil` to be passed as the property name.
(and in the C code, to pass 0 as the property id)

**Comment by coderm4ster** [comment]
I've submitted a draft PR for this request, which only includes changes to go.cancel_animations for now. In the same PR, can I implement the new gui.canel_animations function as described? Maybe another idea for the gui.cancel_animation vs gui.cancel_animations problem?

**Comment by JCash** [comment]
I think it might be better to do two PR's.
That way we can describe the changes more clearly.

**Comment by coderm4ster** [comment]
Ok, then I'll open another request for this.
