### ISSUE TITLE
Lines drawn with the "draw_line" message change the color alpha to 1.0 after a single factory.create call

### ISSUE THREAD

**Issue by mosmetro** [defold/defold#6495]
Repro case:
[broken_debug3d.zip](https://github.com/defold/defold/files/8353243/broken_debug3d.zip)

<table>
<tr><td>Build time</td><td>2022-03-19T08:00:46.134016</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>f2d5646b4f363ba0c2ad6c1a8e2ba383aecd9bbe</td></tr>
<tr><td>Defold engine sha</td><td>0e77ba11ac957ee01878bbde2e6ac0c9fae6dc01</td></tr>
<tr><td>Defold version</td><td>1.3.0</td></tr>
<tr><td>GPU</td><td>Intel HD Graphics 4000 OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-14.7.8</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.15.7</td></tr>
<table>

**Comment by AGulev** [comment]
It sounds like this bug, could you pls try the workaround from there? Or I can check myself if you share a repo project 

https://github.com/defold/defold/issues/6179

**Comment by AGulev** [comment]
should be fixed in 1.3.7
https://github.com/defold/defold/issues/6179
