### ISSUE TITLE
Add both bundle formats for Android in Bob builder

### ISSUE THREAD

**Issue by Insality** [defold/defold#6506]
**Is your feature request related to a problem? Please describe (REQUIRED):**
Currently no any way to build both apk and aab bundle with one build. If we build apk file, aab file is created, but it will be deleted after the build process

**Describe the solution you'd like (REQUIRED):**
Add another bundle format: "apk,aab" or don't delete aab format while bundling apk

**Comment by britzl** [comment]
Why not do a build first, then two bundle steps with a copy in between? Like this:

```
# build first
java -jar bob.jar --platform=armv7-android --archive clean build

# bundle apk and copy
java -jar bob.jar --platform=armv7-android --bundle-format=apk bundle
cp build/default/my.apk .

# bundle aab and copy
java -jar bob.jar --platform=armv7-android --bundle-format=aab bundle
cp build/default/my.aab .
```

**Comment by britzl** [comment]
On the other hand, it is much more efficient to create the aab and then immediately generate an apk from the aab. So I do see the value in this feature request!
