### ISSUE TITLE
Error when bundling project

### ISSUE THREAD

**Issue by pinchazumos** [defold/defold#6509]
### Expected behaviour

When trying to bundle a project, I expect to get the complete project folder with all the files when bundling.

### Actual behaviour

The folder is created but only contains an empty report.html file. I get the following exception warning:
![image](https://user-images.githubusercontent.com/79574665/161712510-60f8584e-c14d-4446-97f8-be16f80cfb55.png)

### Steps to reproduce

This happens with any bundling configurations, no matter the target platform or the options selected, but it only happens with this project, others are fine. As to what I did in this one specifically thats causing this issue, nothing weird in particular. Just added a new sprite asset, added it to an atlas and attached it to an object. Can't really think of more clues, its just bundling.

edit: while googling I've found similar issues caused by included extensions, this project doesn't contains any extensions however.
<hr/>

<table>
<tr><td>Build time</td><td>2022-03-19T07:59:45.504001</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>f2d5646b4f363ba0c2ad6c1a8e2ba383aecd9bbe</td></tr>
<tr><td>Defold engine sha</td><td>0e77ba11ac957ee01878bbde2e6ac0c9fae6dc01</td></tr>
<tr><td>Defold version</td><td>1.3.0</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"39f774012a3f47a5a9492497446c3c56"'>39f774012a3f47a5a9492497446c3c56</a></td></tr>
<tr><td>GPU</td><td>Radeon RX 580 Series</td></tr>
<tr><td>GPU Driver</td><td>4.5.14761 Compatibility Profile Context 21.30.23.04 30.0.13023.4001</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by pinchazumos** [comment]
The name hasn't got any weird characters, and the 2º suggestion doesn't fix the problem.
The third requires installing a bunch of stuff that I don't really know how to use and right now I'm busy with other stuff to deal with such a long-winded solution. I might try it when I get back to this project.

Thanks for the response anyway Britzl.

**Comment by britzl** [comment]
Final thing you could do is to zip your project and share it here so I can take a look. But it might be something else completely that is wrong.
