### ISSUE TITLE
First start

### ISSUE THREAD

**Issue by Gremeat** [defold/defold#6512]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2021-10-18T08:40:34.121967</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>6bfeea3b13d7b8920483ea2cba9c181a8650b84d</td></tr>
<tr><td>Defold engine sha</td><td>6bfeea3b13d7b8920483ea2cba9c181a8650b84d</td></tr>
<tr><td>Defold version</td><td>1.2.188</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"3a823d159add48fe86d83532764bd6a5"'>3a823d159add48fe86d83532764bd6a5</a></td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 511.79</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by Gremeat** [comment]
I just downloaded, installed, launched, created a new project for the first time and got an error

**Comment by britzl** [comment]
```
java.lang.ClassLoader.loadLibrary.class java.lang.UnsatisfiedLinkError: no jfxwebkit in java.library.path: [C:\Program Files (x86)\Steam\steamapps\common\Defold\packages\jdk11.0.1-p1\bin, C:\WINDOWS\Sun\Java\bin, C:\WINDOWS\system32, C:\WINDOWS, C:\Program Files (x86)\Steam, C:\Program Files (x86)\Common Files\Oracle\Java\javapath, C:\ProgramData\Oracle\Java\javapath, C:\Program Files (x86)\Python37-32\Scripts\, C:\Program Files (x86)\Python37-32\, C:\WINDOWS\system32, C:\WINDOWS, C:\WINDOWS\System32\Wbem, C:\WINDOWS\System32\WindowsPowerShell\v1.0\, C:\WINDOWS\System32\OpenSSH\, C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR, C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common, C:\WINDOWS\system32, C:\WINDOWS, C:\WINDOWS\System32\Wbem, C:\WINDOWS\System32\WindowsPowerShell\v1.0\, C:\WINDOWS\System32\OpenSSH\, C:\OpenCV\opencv\build\x64\vc15\bin, C:\Program Files\CMake\bin, C:\Program Files\Git\cmd, C:\Program Files\Git\bin\, C:\Program Files\Microsoft SQL Server\130\Tools\Binn\, C:\Program Files\Microsoft SQL Server\150\Tools\Binn\, C:\Program Files\dotnet\, C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\, C:\Users\Евгений\AppData\Local\Programs\Python\Python39\Scripts\, C:\Users\Евгений\AppData\Local\Programs\Python\Python39\, C:\PHP, C:\Users\Евгений\AppData\Local\Microsoft\WindowsApps, C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.3\bin, ., C:\Program Files\JetBrains\PyCharm 2019.1.3\bin, ., C:\Program Files\JetBrains\PhpStorm 2020.3\bin, ., C:\wxWidgets\Folder\lib\vc14x_x64_dll, C:\Qt\Tools\mingw810_64\bin, C:\Program Files\JetBrains\DataGrip 2021.3.2\bin, ., C:\Users\Евгений\.dotnet\tools, C:\ProgramData\dotnet-script\dotnet-script, .]
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2660)
    at java.lang.Runtime.loadLibrary0(Runtime.java:829)
    at java.lang.System.loadLibrary(System.java:1867)
```

**Comment by britzl** [comment]
@Gremeat It seems like Defold when installed from Steam doesn't like the path for some reason.

Would you mind trying the non-Steam version of Defold and see if that one works?

http://d.defold.com/stable/

**Comment by britzl** [comment]
No additional information provided. Closing.
