### ISSUE TITLE
Error when add layout in gui node

### ISSUE THREAD

**Issue by wangdong20** [defold/defold#6516]
### Expected behaviour
Add layout in layouts folder in Gui outlines. A new layout should shows up, but it doesn't show. 

### Actual behaviour
Add layout in layouts folder in Gui outlines. Error prompt shows, created layout has no property.

### Steps to reproduce
Right click layouts to add layout in Gui. Only layout shows, click it. Error prompt shows.

<hr/>

<table>
<tr><td>Build time</td><td>2022-03-19T08:00:46.134016</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>f2d5646b4f363ba0c2ad6c1a8e2ba383aecd9bbe</td></tr>
<tr><td>Defold engine sha</td><td>0e77ba11ac957ee01878bbde2e6ac0c9fae6dc01</td></tr>
<tr><td>Defold version</td><td>1.3.0</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"28608e23ac5c4c13a65fc4428cf21d0f"'>28608e23ac5c4c13a65fc4428cf21d0f</a></td></tr>
<tr><td>GPU</td><td>Intel(R) Iris(TM) Graphics 6100</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-18.3.5</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.16</td></tr>
<table>

**Comment by britzl** [comment]
@wangdong20 Are you using the Spine or Rive extensions in your project?

**Comment by wangdong20** [comment]
> @wangdong20 Are you using the Spine or Rive extensions in your project?

I am new to Defold and just try some tutorial projects. I don't think I will use any extension in the tutorial projects.

**Comment by britzl** [comment]
Thanks. We will look into this problem soon. Sorry for the inconvenience!

**Comment by vlaaad** [comment]
@wangdong20 Please check if the issue still persists in the latest editor version.
