### ISSUE TITLE
Crash after sending a disable message to a sprite

### ISSUE THREAD

**Issue by K-Klear** [defold/defold#6518]
**Describe the bug (REQUIRED)**
The project crashes after a disable message is sent to a specific sprite component, with this message:
Assertion failed: i < Size(), file D:\a\defold\defold\tmp\dynamo_home\sdk\include\dmsdk/dlib/array.h, line 478

**To Reproduce (REQUIRED)**
I was only able to produce this crash in this specific project. The version in crashing_project.zip should crash automatically as soon as the collection main/main_menu.collection is loaded and the script scanner.script is initialised, sending the disable message.

A minimal version in crash_mimimal.zip crashes less often. It can be reliably triggered by clicking away from the project window as it is loading. Removing more things from the project made me unable to reproduce it, but I haven't found a spečcific trigger.

**Expected behavior (REQUIRED)**
The sprite component is disabled as normal.

**Defold version (REQUIRED):**
  - Version 1.3.1

**Platforms (REQUIRED):**
Windows 10 (tested on two different machines)

**Minimal repro case project:**
Full project: [crashing_project.zip](https://github.com/defold/defold/files/8472444/crashing_project.zip)
Minimal version: [crash_mimimal.zip](https://github.com/defold/defold/files/8472447/crash_mimimal.zip)

**Logs (OPTIONAL):**
[_crash.zip](https://github.com/defold/defold/files/8472446/_crash.zip)

**Workaround (OPTIONAL):**
Sending the disable message after a set time stops the project from crashing. So does adding another sprite component or removing the disable message (perhaps I could hide the sprite by setting its Z-level).
I have tried bundling the project for Android and saw no crash there.

**Additional context (OPTIONAL):**
Slightly more detailed info is here:
https://forum.defold.com/t/crash-after-sending-a-disable-message-to-a-sprite/70703

**Comment by britzl** [comment]
> The project crashes after a disable message is sent to a specific sprite component, with this message:
> Assertion failed: i < Size(), file D:\a\defold\defold\tmp\dynamo_home\sdk\include\dmsdk/dlib/array.h, line 478

I'm not getting the exact same issue. I got this assert once, but what I'm getting repeatedly is this:

```
# 0 pc      0x69dfd libc++abi.dylib _sigtramp+29
# 1 pc      0x666ee dmengine _ZN12dmGameSystemL24RenderListFrustumCullingERKN8dmRender26RenderListVisibilityParamsE+206
# 2 pc     0x10f8ca dmengine _ZN8dmRender14DrawRenderListEPNS_13RenderContextEPNS_9PredicateEPNS_19NamedConstantBufferEPKN10Vectormath3Aos7Matrix4E+890
# 3 pc     0x113da2 dmengine _ZN8dmRender13ParseCommandsEPNS_13RenderContextEPNS_7CommandEj+706
# 4 pc     0x118a0a dmengine _ZN8dmRender26UpdateRenderScriptInstanceEPNS_20RenderScriptInstanceEf+170
# 5 pc       0x7f84 dmengine _ZN8dmEngine4StepEPNS_6EngineE+1188
# 6 pc       0x86ea dmengine _Z14dmEngineUpdatePN8dmEngine6EngineE+26
# 7 pc       0x91fd dmengine _ZN8dmEngine7RunLoopEPKNS_13RunLoopParamsE+109
# 8 pc       0x9162 dmengine _Z11engine_mainiPPc+98
```

This happens when I press Login->Zpet

**Comment by britzl** [comment]
Here's the array size callstack:

```
# 0 pc      0x69dfd libc++abi.dylib _sigtramp+29
# 1 pc      0x1e00f libc++abi.dylib __pthread_kill+11
# 2 pc      0x541ff libc++abi.dylib pthread_kill+263
# 3 pc     0x218d24 libxpc.dylib abort+123
# 4 pc     0x2180cb libxpc.dylib err+0
# 5 pc     0x2ba523 dmengine _ZN8dmRender14DrawRenderListEPNS_13RenderContextEPNS_9PredicateEPNS_19NamedConstantBufferEPKN10Vectormath3Aos7Matrix4E.cold.10+35
# 6 pc     0x11046c dmengine _ZN8dmRender14DrawRenderListEPNS_13RenderContextEPNS_9PredicateEPNS_19NamedConstantBufferEPKN10Vectormath3Aos7Matrix4E+3868
# 7 pc     0x113da2 dmengine _ZN8dmRender13ParseCommandsEPNS_13RenderContextEPNS_7CommandEj+706
# 8 pc     0x118a0a dmengine _ZN8dmRender26UpdateRenderScriptInstanceEPNS_20RenderScriptInstanceEf+170
# 9 pc       0x7f84 dmengine _ZN8dmEngine4StepEPNS_6EngineE+1188
#10 pc       0x86ea dmengine _Z14dmEngineUpdatePN8dmEngine6EngineE+26
#11 pc       0x91fd dmengine _ZN8dmEngine7RunLoopEPKNS_13RunLoopParamsE+109
#12 pc       0x9162 dmengine _Z11engine_mainiPPc+98
```

**Comment by britzl** [comment]
I'm able to get it to crash repeatedly with the array assert in this stripped down sample:
[Archive.zip](https://github.com/defold/defold/files/8554432/Archive.zip)
