### ISSUE TITLE
Method vmath.lerp gives incorrect result for some numeric values

### ISSUE THREAD

**Issue by 546342** [defold/defold#6524]
**Describe the bug (REQUIRED)**
Method vmath.lerp gives incorrect result for some numeric values.

**To Reproduce (REQUIRED)**
```
    print(vmath.lerp(1, 999999995, 999999996))
    > 1000000000
    print(vmath.lerp(1, 99999995, 99999996))
    > 100000000
    print(vmath.lerp(1, 9999995, 9999996))
    > 9999996
```

**Defold version (REQUIRED):**
  - Version 1.2.192

**Platforms (REQUIRED):**
 - Platforms: [macOS, HTML5]

**Workaround (OPTIONAL):**
Use own lerp function

**Comment by JCash** [comment]
This has to do with floating point precision.
Our internal vmath library works with 32 bit floats, and your integers are simply too large to be represented properly when doing the lerp operation.

Although, we could technically make this particular operation 64-bit (as it's getting the Lua's `lua_Number` which is 64-bit, I think there's a good point in keeping the same bit-depth for the entire `vmath` namespace.

Also, when doing this type of calculation, I would probably not call into a C-function (which takes more time than necessary), when Lua can do this perfectly on it's own:

```
function lerp(t, a, b)
    return a + t * (b - a)
end
```

I'll also let @britzl to pitch in on this matter.

**Comment by britzl** [comment]
> I think there's a good point in keeping the same bit-depth for the entire `vmath` namespace

I agree. We should not mix 32 and 64 bit in the vmath library.

> I would probably not call into a C-function (which takes more time than necessary), when Lua can do this perfectly on it's own

This is also a good point. @546342 you could provide a Lua based lerp() as a global function or you could monkey patch vmath.lerp() (not sur eit is worth it though):

```
local vmath_lerp = vmath.lerp
vmath.lerp = function(t, a, b)
    if type(a) == "number) then return a + t * (b - a) end
    --forward non-number lerps to native version
    -- or do this in Lua as well!
    return vmath_lerp(t, a, b)
end
```

**Comment by JCash** [comment]
In the case of monkey patching, I think it is better suited for the `math` namespace?

In any case, since we're agreeing on this, I'll close this ticket.

**Comment by britzl** [comment]
> In the case of monkey patching, I think it is better suited for the `math` namespace

Indeed. Good point!

Another option is to put it into a separate math module, like in DefMath:

https://github.com/subsoap/defmath/blob/master/defmath/defmath.lua#L75
