### ISSUE TITLE
java.lang.ClassCastException: Unknown

### ISSUE THREAD

**Issue by kapellan** [defold/defold#6528]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2022-04-05T08:28:53.370645</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>06bc078e490fd7d94ec01e38abac989f6cc351a5</td></tr>
<tr><td>Defold engine sha</td><td>06bc078e490fd7d94ec01e38abac989f6cc351a5</td></tr>
<tr><td>Defold version</td><td>1.3.1</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"c95fab503e124783b0ce43222bd04ae7"'>c95fab503e124783b0ce43222bd04ae7</a></td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) UHD Graphics (CML GT2)</td></tr>
<tr><td>GPU Driver</td><td>OpenGL ES-CM 1.1 Mesa 21.2.6</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.13.0-39-generic</td></tr>
<table>

**Comment by britzl** [comment]
For some reason there's no stacktrace associated with this issue...

@kapellan have you seen the Linux FAQ? https://defold.com/manuals/linux/#faq It might contain a solution to your problem.

**Comment by AGulev** [comment]
not enough info
