### ISSUE TITLE
Black screen on Samsung TV

### ISSUE THREAD

**Issue by aglitchman** [defold/defold#6531]
**Describe the bug (REQUIRED)**
Yandex.Games has added the "TV" platform recently. So, I decided to test our games on my home TV, SAMSUNG UE50NU7400 with Tizen OS.

As expected, the TV's browser is based on an outdated version of WebKit, and it supports WebGL 1.0 only. And it doesn't support WASM.

![Samsung Smart TV PowerVR WebGL Report](https://user-images.githubusercontent.com/193258/163819441-0f9b0390-c306-4233-a54e-a71ed8831032.jpg)

Sad to say that Defold games didn't run on it and the TV displayed only black screen immediately after the loading of the Defold game. Other WebGL games/demos ran well.

Okay, I decided to investigate the problem. At first, I added Sentry.io SDK to check errors but there wasn't any errors at all. Step by step, I found that WebGL canvas turns immediately "black" if Defold requests the `OES_EGL_image_external` extension.

**To Reproduce (REQUIRED)**
Run any Defold game on SAMSUNG UE50NU7400.

**Expected behavior (REQUIRED)**
Defold games should run well on that TV as any WebGL games actually do.

**Defold version (REQUIRED):**
  - Version: 1.2.188 ... 1.3.1
  - It's important to mention that some time ago Defold games were able to run on that TV.

**Platforms (REQUIRED):**
 - Platforms: HTML5
 - OS: Tizen 4
 - Device: Samsung TV

**Workaround (OPTIONAL):**
Add the following code to the head of `engine_template.html`:
```html
<script>
// Fix for Samsung Tizen Smart-TV
// User-Agent is "Mozilla/5.0 (SMART-TV; Linux; Tizen 4.0) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/2.1 Chrome/56.0.2924.0 TV Safari/537.36"
if (navigator.userAgent.indexOf("SMART-TV") > -1) {
    [window.WebGLRenderingContext, window.WebGL2RenderingContext].forEach(function(context) {
        if (!context) return;
        var getSupportedExtensionsOld = context.prototype.getSupportedExtensions;
        context.prototype.getSupportedExtensions = function() {
            var arr = getSupportedExtensionsOld.call(this);
            var index = arr.indexOf("OES_EGL_image_external");
            if (index > -1) {
                arr.splice(index, 1);
            }
            return arr;
        };
    });
}
</script>
```

**Comment by aglitchman** [comment]
Obviously, that Samsung TV has a bug, but there is an another side: why does Defold request all WebGL extensions if Defold doesn't need them?

**Comment by britzl** [comment]
> why does Defold request all WebGL extensions if Defold doesn't need them?

I'm not very familiar with this bit of code so I can't say for sure. I can't find that we are explicitly requesting the extension.

**Comment by aglitchman** [comment]
I found that Emscripten requests almost ALL available extensions by default on WebGL context creation: https://github.com/emscripten-core/emscripten/blob/fb83ec814d4774a0c50601186cd9aee6e680c59f/src/library_webgl.js#L1132

There is an option to disable that behaviour: https://emscripten.org/docs/api_reference/html5.h.html#c.EmscriptenWebGLContextAttributes.enableExtensionsByDefault
(Actually, it's a nice idea to enable all non-destructive non-performance-impacting WebGL extensions by default)


Looks like, it's a bug in Emscripten. I mean it shouldn't request OS-specific WEBGL extensions like `OES_EGL_image_external`.

**Comment by britzl** [comment]
> Looks like it's a bug in Emscripten

Have you found any indication that this has been reported as an issue?

**Comment by JCash** [comment]
If we don't need the extension, then I agree we shouldn't request it.

And as you mention, we should probably do it explicitly using that setting you linked to.

**Comment by Jhonnyg** [comment]
@aglitchman I've done some experiments with turning off the automatic enabling of the WebGL extensions, could you try any of these builds and see if it works on your device?

https://d.defold.com/archive/dev/9dce12af05c3dc91c7dec581079b5f5e4e3622d4/dev/editor2/Defold-x86_64-darwin.zip
https://d.defold.com/archive/dev/9dce12af05c3dc91c7dec581079b5f5e4e3622d4/dev/editor2/Defold-x86_64-linux.zip
https://d.defold.com/archive/dev/9dce12af05c3dc91c7dec581079b5f5e4e3622d4/dev/editor2/Defold-x86_64-win32.zip

**Comment by aglitchman** [comment]
@Jhonnyg Thanks! I'll be back with the results soon.

**Comment by aglitchman** [comment]
**1.3.5 Beta**
![20220808_123914](https://user-images.githubusercontent.com/193258/183392099-f8cc29a4-1d5e-470d-b497-5722bd599201.jpg)

**New build**
![20220808_123757](https://user-images.githubusercontent.com/193258/183392147-d8521bf8-2a9d-47d9-a4dd-7df0fc5a02f0.jpg)

**Comment by aglitchman** [comment]
So, the new build runs well! 👍🏻

**Comment by britzl** [comment]
> So, the new build runs well! 👍🏻

That is great news!

**Comment by AGulev** [comment]
fixed in https://github.com/defold/defold/pull/6854

github understands only these keywords 
<img width="618" alt="image" src="https://user-images.githubusercontent.com/2209596/183937170-21910854-bc75-40ea-a145-f932aa1b3ae7.png">
