### ISSUE TITLE
Visible stutter in proxied collection

### ISSUE THREAD

**Issue by aglitchman** [defold/defold#6535]
**Describe the bug (REQUIRED)**
(The video is slowed down x2 for convenience):

https://user-images.githubusercontent.com/193258/163954439-596c75d2-1faa-464d-9fad-3ef46993b5b6.mp4

Collection proxies have their own update loop or their own time accumulator or something like that. And that update loop causes jittering/stutter.

More information:
* https://forum.defold.com/t/defold-1-3-1-beta/70594/39
* https://forum.defold.com/t/defold-1-3-1-beta/70594/51

**To Reproduce (REQUIRED)**
Run a collection from a collection proxy and update object's position in `fixed_update`.

**Expected behavior (REQUIRED)**
Proxied collection should run smoothly as the bootstrap collection, i.e. without jittering.

**Defold version (REQUIRED):**
  - Version: 1.3.1

**Platforms (REQUIRED):**
 - Platforms: All

**Minimal repro case project (OPTIONAL):**

https://github.com/aglitchman/defold-fixedupdate-131-test

If you run it, you will see three sprites (“anchors”) that infinitely fall from the top to the bottom. Look at the `test2/test.script` to see how they are animated - the script adds fixed step every `fixed_update`.

- Left: it is created from a collection factory and runs on the main timeline.
- Center: it runs from a collection proxy.
- Right: the same as the central sprite, but with interpolation of position and rotation.

**Comment by ufgo** [comment]
Bug is place in my project. I used platypus for create platformer. So wite when fixed.
