### ISSUE TITLE
vmath.quat_from_to returns a nan value when provided a vector3 with a large negative value

### ISSUE THREAD

**Issue by Sandstedt** [defold/defold#6542]
**Describe the bug**
`vmath.quat_from_to` returns a `nan` value when provided a vector3 with a large negative value.

**To Reproduce**
```lua
vmath.quat_from_to(vmath.vector3(-2, 1, 1), vmath.vector3(1, 1, 1))
```
returns `vmath.quat(0, 2.1213202476501, -2.1213202476501, 0.70710676908493)`

while 
```lua
vmath.quat_from_to(vmath.vector3(-3, 1, 1), vmath.vector3(1, 1, 1))
```
returns `vmath.quat(nan, inf, -inf, 0)`

and a large x value like:
```lua
vmath.quat_from_to(vmath.vector3(-4, 1, 1), vmath.vector3(1, 1, 1))
```
returns `vmath.quat(nan, nan, nan, nan)`

**Expected behavior**
Well, I'm the first to confess I don't understand quaternions. But my usecase was a follow:

Take two objects positions, calculate a vector4/quaternion to get a rotation/vector to point one of the object towards the other.

**Defold version:**
  - Version 1.3.1

**Platforms:**
 - Platforms: Editor Build
 - OS: Windows 10
 - Device: Asus ROG G14

**Workaround:**
Normalize the vector before calculating the quaternion
```lua
vmath.quat_from_to(vmath.normalize(vmath.vector3(-4, 1, 1)), vmath.vector3(1, 1, 1))
```
returns `vmath.quat(0, 1.146191239357, -1.146191239357, 0.51409894227982)`

**Comment by JCash** [comment]
The arguments to this function are supposed to be unit vectors.
https://defold.com/ref/stable/vmath/?q=vmath.quat_from_to#vmath.quat_from_to:v1-v2

I suggest you use `vmath.normalize()`:
```
local v1 = vmath.normalize(a)
local v2 = vmath.normalize(b)
local rot = vmath.quat_from_to(v1, v2)
```

**Comment by britzl** [comment]
The documentation for `vmath.quat_from_to ()` mentions that "The two vectors must be unit vectors (of length 1)." which means that you need to normalize the vectors first.

https://defold.com/ref/vmath/#vmath.quat_from_to:v1-v2

**Comment by Sandstedt** [comment]
Documentations! Sorry 🙈
