### ISSUE TITLE
i got some error on this "a game..." sorry!

### ISSUE THREAD

**Issue by ScratcherFirstOne** [defold/defold#6548]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2022-04-21T12:53:01.210447</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>9df2b26c5a6ce8e23b0294d2fecd671f7326c108</td></tr>
<tr><td>Defold engine sha</td><td>06bc078e490fd7d94ec01e38abac989f6cc351a5</td></tr>
<tr><td>Defold version</td><td>1.3.1</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"c23f7ffb5d5948a380dacc8e1bb69948"'>c23f7ffb5d5948a380dacc8e1bb69948</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon(TM) Graphics</td></tr>
<tr><td>GPU Driver</td><td>4.5.13587 Compatibility Profile Context 19.40.38.01 26.20.14038.1003</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
```
java.io.FileOutputStream.open0.class java.io.FileNotFoundException: C:\Users\meaxy\Heroes of the Aura : The lost world\.gitattributes (La syntaxe du nom de fichier, de répertoire ou de volume est incorrecte)
    at java.io.FileOutputStream.open0(FileOutputStream.java)
    at java.io.FileOutputStream.open(FileOutputStream.java:298)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:237)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:187)
```

**Comment by britzl** [comment]
Please update the folder name to not include a semi colon!
