### ISSUE TITLE
Minimize all windows crash

### ISSUE THREAD

**Issue by ainonovo** [defold/defold#6549]
**Describe the bug (REQUIRED)**

```
builtins/render/default.render_script:99: argument #1 contains one or more values which are not numbers: vmath.matrix4(inf, 0, 0, nan, 0, inf, 0, nan, 0, 0, -1, -0, 0, 0, 0, 1)
stack traceback:
  [C]:-1: in function __mul
  builtins/render/default.render_script:99: in function <builtins/render/default.render_script:71>

Assertion failed: size <= Capacity(), file D:\a\defold\defold\tmp\dynamo_home\sdk\include\dmsdk/dlib/array.h, line 505
![1](https://user-images.githubusercontent.com/24792249/164946892-f2b11a47-ee87-4b2f-a1d8-8f16a2d1f1ea.png)
````

**To Reproduce (REQUIRED)**
window lost focus

**Expected behavior (REQUIRED)**

**Defold version (REQUIRED):**
  - Version [e.g. 1.3.1]

**Platforms (REQUIRED):**
 - Platforms: [Windows]
 - OS: [Windows 7]
 - Device: [laptop lenovo a8 with radeon r5 ]

**Comment by JCash** [comment]
I think the error is fairly clear:

```
argument #1 contains one or more values which are not numbers: vmath.matrix4(...
```

It means that you are not passing a `number` to the argument number 1 in you call on line 99.

Instead, you are sending a `vmath.matrix4`.

**Comment by ainonovo** [comment]
I didn't change any settings. I'm using standard render.

![1](https://user-images.githubusercontent.com/24792249/165493947-14a9b728-63cd-4957-a522-a85defb0392d.png)

This version 1.2.190 did not have this error.

**Comment by britzl** [comment]
The error is in the default render script, on this line:

```
    local frustum_gui = proj_gui * view_gui
```

> window lost focus

Could it be that the window gets a size of 0 when focus is lost and this makes the calculation invalid? I recall similar issues with a window size of 0 when focus is lost.

**Comment by ainonovo** [comment]
I found a stable 100% error occurrence. If I click the icon to minimize all windows

**Comment by Sublustris** [comment]
> I found a stable 100% error occurrence. If I click the icon to minimize all windows

So am i.  On "minimize all windows" app crashes on  Win7x64
