### ISSUE TITLE
Posting message to engine

### ISSUE THREAD

**Issue by daniel-onyenwee** [defold/defold#6550]
**Describe the solution you'd like (REQUIRED):**
Please can you make it possible to post a message to the engine which in the return will post the message to every gui and script components in your game. making it possible to handle thing like disabling some game objects when the game is pause

**Comment by britzl** [comment]
We have no plans to add any broadcasting capabilities to the message passing system. If you need to send a message to multiple objects it is recommended that you build such a system yourself using a Lua module. In such a module you can provide functions to register and deregister game objects and one function to send a message to all registered objects.

You can see an example of this here: https://github.com/britzl/ludobits/blob/master/ludobits/m/broadcast.md
