### ISSUE TITLE
gui.get_flipbook() return empty string for box created in editor

### ISSUE THREAD

**Issue by kornyushin** [defold/defold#6551]
**Describe the bug (REQUIRED)**
gui.get_flipbook() return empty string for box created in editor,
but if set sprite with gui.play_flipbook() then gui.get_flipbook() return sprite name

**To Reproduce (REQUIRED)**
1. Create box in gui, set any sprite
2. in code write pprint(gui.get_flipbook(gui.get_node("box")))
3. in console see DEBUG:SCRIPT: hash: []

**Expected behavior (REQUIRED)**
should return name of current animation

**Defold version (REQUIRED):**
  Defold Engine 1.3.1 (06bc078)

**Platforms (REQUIRED):**
 - Platforms:  Windows
 - OS:  Windows 10

**Additional context (OPTIONAL):**
But if in code set up gui.play_flipbook(node, animation) then gui.get_flipbook() return correct animation name

**Comment by AGulev** [comment]
The issue will be fixed in 1.3.2 beta a80d6353b3bffcdd97c91e8371efc89e2724639a
