### ISSUE TITLE
Gui outline refresh (scroll to top) when change value in node

### ISSUE THREAD

**Issue by d954mas** [defold/defold#6558]
### Expected behaviour
Outlile scroll keep same position
### Actual behaviour
Outline scroll refreshed to top
### Steps to reproduce
1)Change value for node in gui
2)Outline scroll refreshed to top

https://user-images.githubusercontent.com/2655263/165705134-62d6c1a6-9e8c-4268-9da6-c14c1d2b0ea7.mp4
<hr/>

<table>
<tr><td>Build time</td><td>2022-03-08T12:35:13.609680</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>c281f9bace40f3d2e6a56d5b515601e92f5ab9ad</td></tr>
<tr><td>Defold engine sha</td><td>0e77ba11ac957ee01878bbde2e6ac0c9fae6dc01</td></tr>
<tr><td>Defold version</td><td>1.3.0</td></tr>
<tr><td>GPU</td><td>AMD Radeon(TM) Graphics</td></tr>
<tr><td>GPU Driver</td><td>4.5.14756 Compatibility Profile Context 20.40.64 27.20.14064.3</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by Dragosha** [comment]
Collection's outline has a similar behaviour. When delete GO it scrolls to the top.
