### ISSUE TITLE
[SUGGESTION] 

### ISSUE THREAD

**Issue by FriskGT** [defold/defold#6581]
I want a way to work on the same game with others!!!!!!!!! PLEASE!!!!!!!!!!!!!

**Comment by vlaaad** [comment]
Is there something preventing you from working on the same game with others? What is it?

**Comment by britzl** [comment]
You can use version control to share the project files and code with team members:

https://defold.com/manuals/project-setup/#adding-the-project-to-github

There's even a rudimentary version control built into the editor (the changed files panel bottom left).
