### ISSUE TITLE
Html5 low performance

### ISSUE THREAD

**Issue by Swarkin** [defold/defold#6583]
**Describe the bug (REQUIRED)**
Bundling and playing a game on html5 results in extremely low performance / fps.

**To Reproduce (REQUIRED)**
- Build any game with a decent amount of things for html5 and play it.

**Defold version (REQUIRED):**
  - Version 1.3.2 (Issue persists on previous versions)

**Platforms (REQUIRED):**
 - Platforms: HTML5
 - OS: Windows 10

**Screenshots (OPTIONAL):**
https://user-images.githubusercontent.com/102416174/167250534-29edbefc-b4de-49df-b52f-e569f08c2a05.mp4

Additional context (OPTIONAL):
When looking at the task manager, the browser seems to only use CPU for rendering when playing the game for some reason. It's usage stays below 50% as well.

**Comment by AGulev** [comment]
@Swarkin please make sure you build release version of the game when test html5 performance

**Comment by Swarkin** [comment]
I've done that, no difference in performance.

**Comment by subsoap** [comment]
Press F12 and look in the console for any errors.

**Comment by aglitchman** [comment]
Could you please post the report from https://webglreport.com/? To be sure that you didn't disable hardware acceleration in your browser.

**Comment by AGulev** [comment]
Also that would be nice if you provide a link (or upload archive of the build) where you  have performance issues to make sure you build in release and so on

**Comment by Swarkin** [comment]
@subsoap There's not really anything in the console.
https://user-images.githubusercontent.com/102416174/168260543-0c3828d9-682a-45ed-b42d-759b9455b975.png
___
@aglitchman Hardware acceleration is turned on in my browser.
https://user-images.githubusercontent.com/102416174/168260983-8de595b3-e281-4c24-8f4f-7243018bd452.png
___
@AGulev I used the game from https://github.com/benjames-171/defold-games/tree/master/Planet%20Zero.

**Comment by AGulev** [comment]
I built this game and it works fine for me, that's why I'm asking for build you made

**Comment by AGulev** [comment]
According to your log you are testing debug build

**Comment by Swarkin** [comment]
I did bundle it earlier and had the same result.

**Comment by subsoap** [comment]
Have you tested in multiple browsers?

**Comment by Swarkin** [comment]
Fix
---
I couldn't find the exact issue, but reinstalling edge fixed it.
