### ISSUE TITLE
android-repack.sh script requires a cert and key file

### ISSUE THREAD

**Issue by JCash** [defold/defold#6588]
In order to quickly iterate on an apk, we need to be able to repack the apk with the local build of the engine.

Due to the recent updates to the script, it's no longer to repack a local build without any certificate.

The script should detect this case and generate the necessary debug files.

**Comment by AGulev** [comment]
is it fixed by https://github.com/defold/defold/pull/6863/files#diff-1f7a71eac176734ae888d25f0a525ba38d30b0101e856887079e6a88d79066f6 ?
