### ISSUE TITLE
Switch to CurveEditor tab

### ISSUE THREAD

**Issue by MasterCybo** [defold/defold#6595]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2022-05-11T11:22:04.516620</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>0d4cec29d936b43320715b78987297244bc29589</td></tr>
<tr><td>Defold engine sha</td><td>287c945fab310c324493e08b191ee1b1538ef973</td></tr>
<tr><td>Defold version</td><td>1.3.2</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"b87ad801a0a74b57bbcc18b121c762b7"'>b87ad801a0a74b57bbcc18b121c762b7</a></td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 512.59</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by MasterCybo** [comment]
java.lang.AssertionError: Assert failed: No such output, input, or property :render-mode exists for node 144115188075855881 of type editor.curve-view/CurveView
In production: #{}
beh

**Comment by vlaaad** [comment]
Thanks for the report, I merged a fix and the update should be available shortly.
