### ISSUE TITLE
Make `image.*` excludable via app manifest

### ISSUE THREAD

**Issue by aglitchman** [defold/defold#6607]
**Is your feature request related to a problem? Please describe (REQUIRED):**
I'm looking for the ways of reducing the minimal possible build of the Defold engine for the [Playable Ads](https://github.com/aglitchman/defold-playable-ads) project and for our HTML5 games.

From my view, the good candidate for exclusion via [app manifest](https://britzl.github.io/manifestation/) are `dmImage::*` functions + the corresponding `image.*` functions. As an example, we have never used that functionality in our games, but the release builds of the games still include it.

I tried to exclude manually `stb_image` from the `dlib/image.cpp` file to find the benefit. So, there are the results for the HTML5 build:

| Defold 1.3.2. Platform / File | Default Build | Without stb_image | Diff |
| - | - | - | - |
| js-web/dmengine.js              | 5186687 | 5065260 | -121427 |
| js-web/dmengine_release.js      | 4537655 | 4416235 | -121420 |
| wasm-web/dmengine.js            | 263121  | 263121  | 0 |
| wasm-web/dmengine.wasm          | 2629743 | 2564722 | -65021 |
| wasm-web/dmengine_release.js    | 263129  | 263129  | 0 |
| wasm-web/dmengine_release.wasm  | 2184800 | 2119884 | -64916 |

It's just like an idea 😀

**Comment by aglitchman** [comment]
> Quick design:
> We should move the functionality into separate libraries `dlib_image.a`/`dlib_image_null.a`.

It's a nice idea! 

Another example (I'm not sure here, actually) is that exclusion of Live Update from the app manifest doesn't remove `dmZip` from the final build. Only Live Update demands on `dmZip` (to unzip resources). 

| Defold 1.3.2. Platform / File | Default Build | Without `dmZip` | Diff |
| - | - | - | - |
| js-web/dmengine.js              | 5186687 | 5115321| -71366|
| js-web/dmengine_release.js      | 4537655 | 4466279| -71376|
| wasm-web/dmengine.js            | 263121  | 263121  | 0 |
| wasm-web/dmengine.wasm          | 2629743 | 2593848| -35895|
| wasm-web/dmengine_release.js    | 263129  | 263129  | 0 |
| wasm-web/dmengine_release.wasm  | 2184800 | 2148909| -35891|

**Comment by aglitchman** [comment]
And another _crazy_ idea: to be able to exclude Mbed-TLS from the build. Yes, Mbed-TLS is required to decrypt data archives, for SSL sockets, for the `crypt.*`/`dmCrypt` functions, right? In fact, there could be an option to disable archives encryption in bob.jar. Because, for example, data archives of an HTML5 playable ad don't need to be encrypted at all and the ad doesn't need to have crypt functions. The outcome is that the game build will load its data a bit faster 😀 

I hard cut Mbed-TLS from the `engine/dlib/src/dlib/crypt.cpp`, `engine/dlib/src/dlib/sslsocket.cpp` files to check the possible size of the engine (after that, it wasn't able to load data from the archives). The results are below.

| Defold 1.3.2. Platform / File | Default Build | Without `Mbed-TLS` | Diff |
| - | - | - | - |
| js-web/dmengine.js              | 5186687 | 4835256| -351431|
| js-web/dmengine_release.js      | 4537655 | 4186659| -350996|
| wasm-web/dmengine.js            | 263121  | 263106  | 15 |
| wasm-web/dmengine.wasm          | 2629743 | 2452623| -177120|
| wasm-web/dmengine_release.js    | 263129  | 263114  | 15 |
| wasm-web/dmengine_release.wasm  | 2184800 | 2008001| -176799|

**Comment by britzl** [comment]
> Yes, Mbed-TLS is required to decrypt data archives, for SSL sockets, for the `crypt.*`/`dmCrypt` functions, right?

Nope, it is Mbed-TLS is used for some of other functions in dmCrypt, such as b64 encode/decode, sha512, sha256 and sha1. The resource encryption uses xtea encryption (see top of crypt.cpp).

**Comment by JCash** [comment]
If you never access a `https://` link, then I guess there's no need to include the mbedtls library, no.

**Comment by britzl** [comment]
> The resource encryption uses xtea encryption (see top of crypt.cpp)

Note that we now have a plugin system which lets you override default encryption with something else. This could be used to disable encryption in your scenario (by leaving the binary data untouched). See RegisterResourceDecryption resource_archive.cpp.

**Comment by JCash** [comment]
> this could be used to disable encryption in your scenario (by leaving the binary data untouched)

However, the original version is still left in the code as the fallback. It isn't optimized away.

**Comment by JCash** [comment]
Another improvement (since you're building the engine yourself), is to use the flag `--ndebug`.
It adds the define `NDEBUG` to the engine which removes all the `assert()` and log strings.
(A [build fix](https://github.com/defold/defold/pull/6614) just landed in dev)

Here's the diff for macOS:

```
default:
  7247600  tmp/dynamo_home/bin/x86_64-darwin/dmengine
  6603840  tmp/dynamo_home/bin/x86_64-darwin/dmengine_headless
  6679416  tmp/dynamo_home/bin/x86_64-darwin/dmengine_release

--ndebug:
  5599168  tmp/dynamo_home/bin/x86_64-darwin/dmengine
  5166368  tmp/dynamo_home/bin/x86_64-darwin/dmengine_headless
  5077512  tmp/dynamo_home/bin/x86_64-darwin/dmengine_release

```

**Comment by JCash** [comment]
A comment on modularity.
The `image`Lua module is registered by  `void ScriptImageRegister(const ScriptLibContext& context)` in script_image.cpp.

We don't have "script extensions", so we should rather just use regular extension for modularity (see script_box2d.cpp):
```
DM_DECLARE_EXTENSION(ScriptBox2DExt, "ScriptBox2d", 0, 0, ScriptBox2DInitialize, 0, 0, ScriptBox2DFinalize)
```

By avoiding including this image script module, there should be no other links to the dmImage library, and thus no need for an dlib_image_null.a. It should theoretically not need the dlib_image.a either, if all link optimizations work.

I say "should" here, as it needs testing. It might be that the linker still keeps it. I believe we're still lacking e.g. the "-flto" flag for some platforms.
It needs testing, and as mentioned earlier the dlib_image_null.a is sure to work, it's jsut more cumbersome approach.
