### ISSUE TITLE
Window flashes multiple times when opening game on Windows

### ISSUE THREAD

**Issue by subsoap** [defold/defold#6608]
See our game Big Klondike built with engine version 1.3.2

https://store.steampowered.com/app/1706340/Big_Klondike__Classic_Solitaire/

It did not used to do this so it is a recent Defold change causing this issue.

**Comment by CocosGames** [comment]
![image](https://user-images.githubusercontent.com/42052366/169268681-a5b8ee40-ac29-49e7-b753-370a7925df08.png)
Tested on Windows 11 with an empty project, no problems.
