### ISSUE TITLE
HTML5 terminate WebAssembly and re-run

### ISSUE THREAD

**Issue by danielcloran** [defold/defold#6617]
When attempting to reuse the same canvas to either run a new game or restart the original game an error is thrown: `Assertion failed: g_BufferContext == 0 && "Buffer context should be null"` I see the message: `INFO:ENGINE: Engine exited with code 0` before attempting to run EngineLoader.runApp again as I call sys.exit(0) within Defold when the game finishes. 

1. Run any HTML5 build: (using EngineLoader.load("canvas", "..."); and ["onRuntimeInitialized"] -> Module.runApp("canvas", extra_params); 
3. Finish the game with sys.exit(0)
4. Attempt to rerun the game with Module.runApp("canvas", extra_params);
6. See error

**Expected behavior**
I expect the WebAssembly script to close cleanly so rerunning the entire setup process results in the game or a different game loading properly.

**Defold version:**
  - Version [Defold 1.3.2]

**Platforms:**
 - Platforms: maxOS (using a chromium browser)
 - OS: Monterey 12.2.1
 - Device: Macbook Pro

**Logs (from Web Console):**
```
exception thrown: RuntimeError: abort(Assertion failed: g_BufferContext == 0 && "Buffer context should be null", at: ../src/dlib/buffer.cpp,77,NewContext). Build with -s ASSERTIONS=1 for more info.,RuntimeError: abort(Assertion failed: g_BufferContext == 0 && "Buffer context should be null", at: ../src/dlib/buffer.cpp,77,NewContext). Build with -s ASSERTIONS=1 for more info.
    at abort (<anonymous>:1:12355)
    at ___assert_fail (<anonymous>:1:18528)
    at https://localhost:4200/dmengine.wasm:wasm-function[4889]:0x1901c1
    at https://localhost:4200/dmengine.wasm:wasm-function[4807]:0x18a7ac
    at https://localhost:4200/dmengine.wasm:wasm-function[4796]:0x1891e9
    at https://localhost:4200/dmengine.wasm:wasm-function[4799]:0x189cf1
    at https://localhost:4200/dmengine.wasm:wasm-function[3179]:0x10aa2f
    at https://localhost:4200/dmengine.wasm:wasm-function[2981]:0xf845f
    at Object.callMain (<anonymous>:1:264229)
    at Object._preloadAndCallMain (https://localhost:4200/main.js:895:24)
```

**Workaround:**
Reloading the page obviously results in proper re-run, however this is not an option for my build.

**Additional context:**
I am not a WebAssembly expert, but I understand that there is no way to forcibly terminate a WebAssembly script, it has to close cleanly. I had assumed that calling sys.exit(0) would do this, but do not think this is happening. I would appreciate any help you could provide, it is entirely possible that I am not cleaning something up properly from the Javascript side and would love if anyone has a working way to make this happen.

**Comment by britzl** [comment]
> `Assertion failed: g_BufferContext == 0 && "Buffer context should be null"` I see the message: `INFO:ENGINE: Engine exited with code 0`

It seems like we're not cleaning everything up as expected.

> 3\. Attempt to rerun the game with Module.runApp("canvas", extra_params);

I don't think anyone has ever attempted something like this before. Perhaps there are things on the JS+Emscripten side that needs to be cleaned up as well.

**Comment by danielcloran** [comment]
Is there an approach you recommend for hot swapping game bundles in HTML5 without reloading the page or has this not been implemented yet?

**Comment by britzl** [comment]
I'm afraid I don't know. Perhaps @AGulev or @aglitchman has some ideas?

**Comment by aglitchman** [comment]
From my view, there is no way of doing that in Defold. There are lots of reasons, and the most important is how Emscripten works by default, i.e. it defines `Module` (and others) on global scope, relies on that and assumes that there will be only one non-reloadable app.

If you want to make a "hot-swappable" Defold game, then Defold should be recompiled with a completely different Emscripten set of options to be a self-contained app (see [MODULARIZE](https://emscripten.org/docs/getting_started/FAQ.html#how-can-i-tell-when-the-page-is-fully-loaded-and-it-is-safe-to-call-compiled-functions)). It requires to change lots of things, and I don't think it's viable to do right now.

IMHO.

@danielcloran What is the point of "hot swapping"? Could you please add more details of what you want to achieve.

**Comment by danielcloran** [comment]
The goal is to load different games to the same page / canvas depending on user input without reloading the page. These games cannot be bundled into the same Defold game.

**Comment by danielcloran** [comment]
That works, I will stick to using that for now. Thanks for the help.

**Comment by britzl** [comment]
Based on the discussion above I'm closing this.
