### ISSUE TITLE
Broken mesh after 6505 fix "Mesh vertex buffers not updating properly" in 1.3.2

### ISSUE THREAD

**Issue by Dragosha** [defold/defold#6624]
I work on 1.3.1 version, and made FoggyFox build for Poki on it. Now  I try to 1.3.3 beta and notice that my mesh is lost.

What I do.
The levels in the editor have lots of simple quad meshes with textures. I combine it to do more complex form like a House or a wagon on screens below. In the code I merge all this simple meshes to the one big mesh with one texture for reducing draw call reason. It works on 1.3.1(-) versions so good. Perhaps my code broken after this fix: https://github.com/defold/defold/pull/6505 not sure, but I can't reach any other mesh changes in releases description after the 1.3.1 engine release.

The same issue with other my a mesh creating example:
https://github.com/Dragosha/defold-things/tree/master/3d-tilemap
It has similar method for make a mesh in realtime:
https://github.com/Dragosha/defold-things/blob/master/3d-tilemap/src/mtool.lua
You may use this example as reprocase.

1.3.1:
![2022-05-23_15-46-35](https://user-images.githubusercontent.com/842807/169803683-f785e004-5842-4c97-9aff-df8dd8afab99.png)
1.3.3:
![2022-05-23_15-45-44](https://user-images.githubusercontent.com/842807/169803721-daa609ff-8ee2-48a7-9b1d-9a3e3817bd07.png)

Foggy Fox issue:
![2022-05-23_15-15-59](https://user-images.githubusercontent.com/842807/169799481-64ea2dd0-c767-4aea-b435-d6459e7124f4.png)
![2022-05-23_15-16-19](https://user-images.githubusercontent.com/842807/169799557-549949e4-76ac-4619-bcd1-142fbc7f260b.png)

<hr/>

<table>
<tr><td>Build time</td><td>2022-05-17T07:34:10.716145</td></tr>
<tr><td>Defold channel</td><td>beta</td></tr>
<tr><td>Defold editor sha</td><td>4ace6be82ab5231ccc3e8d49507b83ace6822783</td></tr>
<tr><td>Defold engine sha</td><td>4ace6be82ab5231ccc3e8d49507b83ace6822783</td></tr>
<tr><td>Defold version</td><td>1.3.3</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 472.39</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by JCash** [comment]
Yes, it seems likely that change is the culprit.
If you have a minimal repro case project, I'll happily use that!

**Comment by Dragosha** [comment]
> Yes, it seems likely that change is the culprit. If you have a minimal repro case project, I'll happily use that!
This opensource project used similar code and it is candidate to repro: https://github.com/Dragosha/defold-things/tree/master/3d-tilemap 
Especialy _mtool.lua_ module and lines from _212_ creating buffer... may be I did something wrong when creating mesh buffer and associated with him arrays.
https://github.com/Dragosha/defold-things/blob/master/3d-tilemap/src/mtool.lua#L212
