### ISSUE TITLE
Bundler copy native libraries for both architectures even if only one arch building

### ISSUE THREAD

**Issue by AGulev** [defold/defold#6642]
**Describe the bug (REQUIRED)**

If android package contains a few architectures both native libraries end up in bundle even if build was for one architecture.

**To Reproduce (REQUIRED)**
1. create fake extension with
```
dependencies {
    implementation 'io.sentry:sentry-android:5.6.1'
}

```
2. build android only for x32 (or only x64)
3. unpack app and check `lib` folder4. 
<img width="540" alt="image" src="https://user-images.githubusercontent.com/2209596/170721846-09a09268-f0bb-4760-8277-e84d6560f21a.png">

**Expected behavior (REQUIRED)**
Include libs only for needed platform

**Defold version (REQUIRED):**
  - Version 1.2.192

**Platforms (REQUIRED):**
 - Platforms: Android
 - OS: Mac

**Comment by britzl** [comment]
The AndroidBundler will generate a "universal APK" from the AAB file. A universal APK is guaranteed to work on all platforms:

https://developer.android.com/studio/command-line/bundletool#generate_apks

This means that the AndroidBundler doesn't respect the platform architecture config of the build. Perhaps this needs to be changed...
