### ISSUE TITLE
gdc tool crashes on Windows 11

### ISSUE THREAD

**Issue by britzl** [defold/defold#6658]
**Describe the bug (REQUIRED)**
The gdc tool crashes on Windows 11

**To Reproduce (REQUIRED)**
1. Try to run gdc.exe tool on Windows 11
2. The application immediately closes

**Expected behavior (REQUIRED)**
The gdc tool should run as expected on Windows 11

**Defold version (REQUIRED):**
  - Version 1.3.2

**Platforms (REQUIRED):**
 - Platforms: Windows
 - OS: Windows 11

**Additional context (OPTIONAL):**
[Add any other context about the problem here.](https://forum.defold.com/t/big-thread-of-gamepad-testing/56032/13?u=britzl)

**Comment by Jhonnyg** [comment]
Fixed by https://github.com/defold/defold/commit/1f35a0be292ff1ab7c7ded49c870ba201c2d5623
