### ISSUE TITLE
iOS bundle failed

### ISSUE THREAD

**Issue by wangdong20** [defold/defold#6672]
**Describe the bug (REQUIRED)**
iOS bundle failed with admob extension

**To Reproduce (REQUIRED)**
after add admob extension, start bundle iOS application

**Expected behavior (REQUIRED)**
iOS bundle should success

**Defold version (REQUIRED):**
  - Version [1.3.2]

**Platforms (REQUIRED):**
 - Platforms: [iOS]
 - OS: [macOS Monterey]

**Minimal repro case project (OPTIONAL):**
Please attach a minimal project where the bug is reproduced. This will greatly help the person trying to investigate and fix the bug.

**Logs (OPTIONAL):**
[log.txt](https://github.com/defold/defold/files/8857586/log.txt)

**Workaround (OPTIONAL):**
If there is a workaround, please describe it here.

**Screenshots (OPTIONAL):**

**Additional context (OPTIONAL):**

**Comment by britzl** [comment]
Forum post: https://forum.defold.com/t/failed-to-bundle-ios-application/71054

**Comment by AGulev** [comment]
isn't it fixed but fixing SSL issue in java ? https://forum.defold.com/t/failed-to-bundle-ios-application/71054/54

**Comment by britzl** [comment]
I think so. And we spent a lot of time to reproduce this issue and failed. Closing.
