### ISSUE TITLE
Issue came up after another crash

### ISSUE THREAD

**Issue by blockboy05** [defold/defold#6674]
Laptop: 
Lenovo ideapad 5-14ARE05 Laptop - Type 81YM 2020 Model
Had it repaired once.

### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2022-03-19T07:59:45.504001</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>f2d5646b4f363ba0c2ad6c1a8e2ba383aecd9bbe</td></tr>
<tr><td>Defold engine sha</td><td>0e77ba11ac957ee01878bbde2e6ac0c9fae6dc01</td></tr>
<tr><td>Defold version</td><td>1.3.0</td></tr>
<tr><td>GPU</td><td>AMD Radeon(TM) Graphics</td></tr>
<tr><td>GPU Driver</td><td>4.5.14800 Compatibility Profile Context 22.5.2 30.0.21017.1000</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
For some reason we have no crash logs attached to this report. @blockboy05 does it happen more than once?

**Comment by AGulev** [comment]
not enough info
the first crash may break something which may be a reason of the second crash.
