### ISSUE TITLE
Allow turning off the visibility of all debug lines in the scene

### ISSUE THREAD

**Issue by vlaaad** [defold/defold#6691]
**Is your feature request related to a problem? Please describe (REQUIRED):**
When developing a GUI scene, it's useful to see how it will look in the game without launching the game. Currently, it's not possible — we can't turn off grey node bounds.

**Describe the solution you'd like (REQUIRED):**
Allow turning off the visibility of node bounds.

**Describe alternatives you've considered (REQUIRED):**
I haven't considered any alternatives

**Comment by matgis** [comment]
Doesn't **View > Toggle Component Guides** do just that? Maybe I'm not fully understanding what you want.

**Comment by vlaaad** [comment]
Hmm. @Insality does **View > Toggle Component Guides** work for you?

**Comment by matgis** [comment]
Let's add these options (Grid, Component Guides) to the Scene View visibility popup!
