### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by TheDandyFellow** [defold/defold#6725]
### Expected behaviour
loading project scene.

### Actual behaviour
Error.

### Steps to reproduce
pressing F5.

<hr/>

<table>
<tr><td>Build time</td><td>2022-05-23T17:41:12.326947</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>766a51fe39df047a249d3efc48ae10f052ca51b7</td></tr>
<tr><td>Defold engine sha</td><td>287c945fab310c324493e08b191ee1b1538ef973</td></tr>
<tr><td>Defold version</td><td>1.3.2</td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 580X OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-4.7.103</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.16</td></tr>
<table>

I'm new to this and have no idea what i'm doing. But i think it has something to do with rendercam.

**Comment by britzl** [comment]
Hmm, there is no error or stacktrace attached to this issue. Does it happen all the time? Does it happen with more than one project?

**Comment by TheDandyFellow** [comment]
every time, and only with one project, and it only happens when i put the player collection in the main collection and try to run the game. I created a separate collection for the player/party. it's just the rendercam plugin and a game object with a collection factory, a script, a camera and a sprite. And again i think this might have something to do with rendercam.

Thank you for your response!

**Comment by britzl** [comment]
@TheDandyFellow what is the error message you are getting?

**Comment by TheDandyFellow** [comment]
java.lang.AssertionError: Assert failed: Cycle detected on node type editor.collection/CollectionNode and output :build-targets
(not (contains? (:in-production evaluation-context) [node-id label]))

looking at this now. it looks like user error 0_0

**Comment by TheDandyFellow** [comment]
"And again i think this might have something to do with rendercam."

NOPE!
It's the collection factory

**Comment by TheDandyFellow** [comment]
it now happens when i try to launch the main scene "and" the player scene

**Comment by britzl** [comment]
> java.lang.AssertionError: Assert failed: Cycle detected on node type editor.collection/CollectionNode and output :build-targets

Ah, there we go. This is a cyclic dependency which means that you for instance have a collection containing a collection proxy or factory which directly or indirectly references itself, thus creating a dependency loop.

**Comment by britzl** [comment]
(We're going to improve on this error message to make it much easier for devs to understand)

**Comment by TheDandyFellow** [comment]
whoops XD. Sorry for wasting your time, i'm still new at this and don't know how to use allot of the components.
I'm just not going to use the CollectionFactory for now.

Again, thank you for your time,  i always appreciate it when people take time out of their day to answer my questions.
