### ISSUE TITLE
Render-target with float format doesn't work

### ISSUE THREAD

**Issue by Morgerion** [defold/defold#6730]
**Render-target with float format doesn't work**
I’ve done a number of experiments with float render-target with different formats.
This is the situation I have at the moment:
1. My build crashes when using ANY format other than R32F with error: ERROR:GRAPHICS: OpenGLSetTexture(2579): gl error 1280
2. R32F format works very strangely - there are no errors, but only if it is set to zero sampler (render.enable_texture(0, self.shadow_buffer).

**Expected behavior**
Here are some screenshots - one for PC, one for mobile. In these, I’ve displayed the contents of the shadow texture on the sprite on the right-hand side of the screen.
In addition, I’ve also displayed the content of the shadow texture also on top of the 3D objects, so that you can see how it’s projected.
This is screenshot for PC (we can see render-target projected on landscape and objects, similar as sprite at right screen side):
![Скриншот 2022-06-19 11 10 11](https://user-images.githubusercontent.com/7888071/174670484-14e36fb2-e6f4-4c56-9003-1b7f47eecc61.jpg)

This is screenshot for Android (we can see empty render-target on land, but correct result on sprite at right screen side):
![Screenshot_20220619-110850](https://user-images.githubusercontent.com/7888071/174670800-b4b4fb44-eed9-4166-9bd3-b0fd302cc1dd.jpg)
Why does render-target on Android look correct on sprite? The point is that zero sampler is used for the sprite, and everything works correctly on it.

This is a screenshot from Android. Here I've set the render-target texture to zero sampler and we can see that everything works correctly:
![new](https://user-images.githubusercontent.com/7888071/174671634-b7a0064b-12be-4c63-9ca3-c7afe6c0c66f.jpg)

**Defold version:**
  - Version 1.3.3

**Platforms:**
 - Platforms: Android

**Minimal repro case project:**
[__SHADOW_TEST.zip](https://github.com/defold/defold/files/8943437/__SHADOW_TEST.zip)
controls:
- touch the left-hand side of the screen for move camera
- touch the right-hand side of the screen for rotate camera

**Comment by Morgerion** [comment]
What about GL ES 3? Is it not supported by Defold?

**Comment by Jhonnyg** [comment]
> What about GL ES 3? Is it not supported by Defold?

Yeah it's supported, we fallback to ES2 if we couldn't get an ES3 context which depends on the device. I'll double check on the android I used what context got created, but it should always prefer ES3 afaik.

**Comment by Morgerion** [comment]
Thing is, I tested the R32F on a 2019 Samsung Galaxy Note 10 android, and it supports GL ES3 as per spec (Adreno 330).
That's why I was surprised to hear you say it's a GL ES2 limitation.

**Comment by Morgerion** [comment]
OK, thank you very much for the information!

**Comment by Morgerion** [comment]
OK, the problem with the R32F is indeed solved this way.

But!
Attempting to use the other formats results in the error+crash I described in the issue.
The manual for float render-targets states that if any format is not supported by the device, it will be nil.
That is, if RGBA32F is not supported, then render.FORMAT_RGBA32F = nil.
But on my Android, ALL float formats produce valid numbers.
However, using them (except for R32F) causes the game to crash.

**Comment by Jhonnyg** [comment]
@Morgerion so to reproduce your issue I should be able to set the format to one of the other float types and it will produce a crash? I'll take a look next week then 👍

**Comment by Jhonnyg** [comment]
Fixed by #6844
