### ISSUE TITLE
Add the geometry bounds visibility filter

### ISSUE THREAD

**Issue by astrochili** [defold/defold#6739]
Sometimes it's hard to figure out and navigate when the whole scene is filled with gray boxes.

![](https://user-images.githubusercontent.com/4752473/174963048-8ff7ff5d-1013-4bd9-99d9-a73b6779ff63.png)

**Comment by TheKing0x9** [comment]
`View->Toggle Component Guides` or `Ctrl+H` should disable the grey boxes.

**Comment by astrochili** [comment]
@TheKing0x9 It really works, I didn't know about this option! Thanks!

Perhaps it would be convenient to move it to the same list as the rest of the filters 🤔

**Comment by AGulev** [comment]
related https://github.com/defold/defold/issues/6691
