### ISSUE TITLE
Ogg file validation failed in Window 10

### ISSUE THREAD

**Issue by kornyushin** [defold/defold#6749]
Can't make html5 build , error Sound file validation failed. Make sure your ogg files are correct using oggz-validate https://www.xiph.org/oggz/ 

When run oggz-validate.exe see

![изображение](https://user-images.githubusercontent.com/1443375/175821383-6b0e15e5-657e-45c7-bb7e-9462e687b61e.png)

**Expected behavior**
Make build

**Defold version :**
  - Version 1.3.3

**Platforms :**
 - Platforms:  HTML5
 - OS:  Windows 10,

**Comment by AGulev** [comment]
Solved by installing https://www.microsoft.com/ru-ru/download/details.aspx?id=30679
maybe it's possible to include this dll somehow..
