### ISSUE TITLE
Bob.jar complains about libogg on Linux and crashes

### ISSUE THREAD

**Issue by dapetcu21** [defold/defold#6756]
**Describe the bug (REQUIRED)**
I just tried to run one of our GH Actions, which bundles a project using bob.jar. It crashed with:

```
java.lang.RuntimeException: /libexec/x86_64-linux/libogg.so could not be found.
```

The `libogg0` package seems to be installed already. The GH Actions runner is Ubuntu Focal.

**Defold version (REQUIRED):**
  - Version c2ab1630e34f1311d8340d81494cf5317d25fe16 (1.3.3)

**Platforms (REQUIRED):**
 - Platforms: x86_64 Linux

**Comment by AGulev** [comment]
this issue fixed in 1.3.4 or in [this branch](https://github.com/defold/defold/tree/hotfix-1.3.3)
sorry for inconvenience
