### ISSUE TITLE
Google Play (Issue found: Invalid Data safety section)

### ISSUE THREAD

**Issue by d954mas** [defold/defold#6764]
**Describe the bug (REQUIRED)**
https://forum.defold.com/t/google-play-issue-found-invalid-data-safety-section/71172

I’m updating my app in Play Market. And get warning from google
SPLIT_BUNDLE 1: Policy Declaration - Data Safety Section: Device Or Other IDs Data Type - Device Or Other IDs (some common examples may include Advertising ID, Android ID, IMEI, BSSID)

**To Reproduce (REQUIRED)**
1. Build aab.
2. Upload it to play market
3. Wait for review(~1-2h) I upload my game to “Open testing” and after review(1-2 hours) get email from google.

**Expected behavior (REQUIRED)**
No warning from google about device_id

**Defold version (REQUIRED):**
1)Defold 1.3.3
2)permissions
```
<uses-permission android:name="android.permission.WAKE_LOCK" />
```
3)Dependencies
```
dependencies#0 = https://github.com/AGulev/jstodef/archive/1.3.0.zip
dependencies#1 = https://github.com/DanEngelbrecht/LuaScriptInstance/archive/master.zip
dependencies#2 = https://github.com/d954mas/defold-box2d/archive/refs/
```

**Platforms (REQUIRED):**
 - Platforms: Android

**Workaround (OPTIONAL):**
https://stackoverflow.com/questions/71199143/action-required-your-app-is-not-compliant-with-google-play-policies-what-is-t/71234298#71234298
Fill in data safety policy that device_id is collected.

**Screenshots (OPTIONAL):**
![2022-06-27_15-12-19](https://user-images.githubusercontent.com/2655263/176767692-afefb037-ab39-4c43-946d-2ce1c6c90cdf.png)

**More info**
It mb because engine always try to get android_id
https://github.com/defold/defold/blob/6b03d6f75afb1411f62d96850cd8d94b1971916e/engine/dlib/src/dlib/sys.cpp#L754

**Comment by britzl** [comment]
I'm thinking that perhaps the `sys.get_sys_info().device_ident` field should be removed? It can as far as I know only be used for tracking, and it feels weird to have it in the engine. Perhaps better to move it to `extension-adinfo`?

**Comment by AGulev** [comment]
I'm not sure about `extension-adinfo` is ADS the only use case?
maybe it should be a separate extension?

**Comment by totebo** [comment]
This value is needed for PlayFabClientApi.LoginWithAndroidDeviceID(), so I'd vote for a separate extension for this. It would make sense for an extension to cover iOS too, for consistency.

Forum thread: https://forum.defold.com/t/authenticating-with-playfab-loginwithandroiddeviceid-solved/71390

**Comment by britzl** [comment]
Yes, perhaps a new extension then? Perhaps `extension-sysinfo` and expose a bunch of system/platform specific information. There's probably more on Android than the `ANDROID_ID` constant that is of interest?

https://developer.android.com/reference/android/provider/Settings.Secure

**Comment by AGulev** [comment]
@d954mas do you call `sys.get_sys_info()` in your game?

**Comment by d954mas** [comment]
Also I am not sure what and where they detect.
android_id is my suggestion

**Comment by britzl** [comment]
> Also I am not sure what and where they detect. android_id is my suggestion

Yes, that is definitely it!
