### ISSUE TITLE
Can't see a name of a long custom game.project settings field

### ISSUE THREAD

**Issue by vlaaad** [defold/defold#6786]
**Is your feature request related to a problem? Please describe (REQUIRED):**
Can't see a name of a custom game.project field if it's too long:
![photo_2022-07-08 11 07 43](https://user-images.githubusercontent.com/732554/177958526-17e8b85e-00b5-41b5-b32a-46f6706d651e.jpeg)

**Describe the solution you'd like (REQUIRED):**
Show full name in the tooltip instead of "unknown setting"

**Describe alternatives you've considered (REQUIRED):**
Allow configuring custom fields in the editor

**Comment by AGulev** [comment]
```
Describe alternatives you've considered (REQUIRED):
Allow configuring custom fields in the editor
```
this Alt way sounds like:
https://github.com/defold/defold/issues/3157
