### ISSUE TITLE
Crash on Defold 1.3.4 on iOS

### ISSUE THREAD

**Issue by akrasnogor-ms** [defold/defold#6791]
**Describe the bug (REQUIRED)**
We have crash in our sentry:
`SIGABRT: 0123456789abcdef > Assertion failed: (key != 0), function rmtHashTable_Insert, file Remotery.c, line 2612.
 > key != 0 > particlefxc > Remotery.c > rmtHashTable_Insert
  File "Remotery.c", line 2612, in rmtHashTable_Insert.cold.1
  File "Remotery.c", line 2612, in rmtHashTable_Insert
  File "Remotery.c", line 2769, in StringTable_Insert
  File "Remotery.c", line 6142, in Remotery_AddToStringTable
  File "Remotery.c", line 6471, in Remotery_ConsumeMessageQueue
...`

Full crash: [crash.txt](https://github.com/defold/defold/files/9091442/crash.txt)

**To Reproduce (REQUIRED)**
We don't have clear steps to reproduce.

**Expected behavior (REQUIRED)**

**Defold version (REQUIRED):**
  - Version 1.3.4 (Engine SHA: 94e5bc29689278d3eae96e9f3ac111004bd62f7c)

**Platforms (REQUIRED):**
 - Platforms: iOS
 - OS: iOS14.6
 - Device: iPhone XR

**Minimal repro case project (OPTIONAL):**
Please attach a minimal project where the bug is reproduced. This will greatly help the person trying to investigate and fix the bug.

**Logs (OPTIONAL):**
[log (1).txt](https://github.com/defold/defold/files/9091382/log.1.txt)

**Workaround (OPTIONAL):**
If there is a workaround, please describe it here.

**Screenshots (OPTIONAL):**

**Additional context (OPTIONAL):**

**Comment by JCash** [comment]
Hi @akrasnogor-ms !

Looking through the code, I'm a bit confused about the call stack.

The latest code in Remotery.c (`94e5bc29689278d3eae96e9f3ac111004bd62f7c`) on your branch doesn't quite match the call stack you report here.
Instead, it seem to match an earlier version matching the commit `0b2264430293197c757153d6de40201c65e9bae3`.

In Remotery.c:
For `0b2264430293197c757153d6de40201c65e9bae3 `, I see:
On line 6471, there is a call to Remotery_AddToStringTable.
On line 6142, there is a call to StringTable_Insert.

For `94e5bc29689278d3eae96e9f3ac111004bd62f7c`, I see:
On line 6472, there is a call to Remotery_AddToStringTable
On line 6143, there is a call to StringTable_Insert

As such, it seems `0b22644` is the version reporting the error, not `94e5bc2 `.

Also, in the submitted log file, which admittedly show version `94e5bc2`, I cannot seem to find any reference to a crash or assert? Doesn't it usually show an assert or callstack there?

**Comment by AGulev** [comment]
@JCash 

here is full log from sentry 
1.3.4 (94e5bc29689278d3eae96e9f3ac111004bd62f7c)
[55ce74afd54d4f2b9b10cc75b965ac10-symbolicated.crash.txt](https://github.com/defold/defold/files/9115279/55ce74afd54d4f2b9b10cc75b965ac10-symbolicated.crash.txt)

**Comment by JCash** [comment]
I'm not talking about the crash.txt, but the [log (1).txt](https://github.com/defold/defold/files/9091382/log.1.txt) as posted above.

**Comment by JCash** [comment]
Looking at the updated crash.txt you posted, then the file+line numbers match up again.

**Comment by AGulev** [comment]
a few more  (difference in assert: collectionproxyc, @libs/flow.lua, spinemodelc, camerac)

[5a6f4036d14c432d9bbc8845e24c4b75-symbolicated.crash.txt](https://github.com/defold/defold/files/9115457/5a6f4036d14c432d9bbc8845e24c4b75-symbolicated.crash.txt)
[8a1f6bb0d7954f95873a4eaa2c0af59d-symbolicated.crash.txt](https://github.com/defold/defold/files/9115458/8a1f6bb0d7954f95873a4eaa2c0af59d-symbolicated.crash.txt)
[55ce74afd54d4f2b9b10cc75b965ac10-symbolicated.crash.txt](https://github.com/defold/defold/files/9115459/55ce74afd54d4f2b9b10cc75b965ac10-symbolicated.crash.txt)

**Comment by akrasnogor-ms** [comment]
Hi @JCash 
Sorry, i was missed your message. 
Maybe i'm wrongly attached log and crash from previous revision of build, sorry for that. I get it from our sentry and there was 100% same issue on **_94e5bc29689278d3eae96e9f3ac111004bd62f7c_** version of engine. 
Do you still need logs and crash for correct revision or you already have enough information?

Thanks for you help and support!

**Comment by AGulev** [comment]
@akrasnogor-ms no worries,
I added right crash logs from Sentry. Now we are waiting for logs from your QA even if there is no crash in new build (i hope so)
