### ISSUE TITLE
DM_COUNTER_DYN doesn't work anymore and components count isn't available in profiler

### ISSUE THREAD

**Issue by AGulev** [defold/defold#6811]
**Describe the bug (REQUIRED)**
Can't see components coun in profiler anymore

**Expected behavior (REQUIRED)**
Components count should be visible as before

**Defold version (REQUIRED):**
  - Version 1.3.5

**Comment by JCash** [comment]
The intention was to replace it with the "properties", which we then added to the library.

I've prepared a branch which demonstrates the work needed (per component type):
https://github.com/defold/defold/pull/6814
