### ISSUE TITLE
Android 13 back button implementation

### ISSUE THREAD

**Issue by ekharkunov-ms** [defold/defold#6821]
**Task (REQUIRED):**
We received a letter from Google Play team:

_We’ve identified that your Android app(s) potentially uses unsupported [KEYCODE_BACK](https://developer.android.com/reference/android/app/Activity#onBackPressed()) APIs, which are no longer supported in Android 13._

_You’ll need to migrate to AndroidX or the new platform API available in Android 13 if your app(s) intercepts back navigation at any level (Activity, Fragment, View, or Dialog)._

**Expected outcome (REQUIRED):**
Defold engine meet described requirement.

**Comment by britzl** [comment]
https://developer.android.com/guide/navigation/predictive-back-gesture#migrate-app
