### ISSUE TITLE
Crash when label buffer is full

### ISSUE THREAD

**Issue by subsoap** [defold/defold#6836]
Try creating some labels above max, try setting max low to do this. Engine hard crashes.

[_crash.zip](https://github.com/defold/defold/files/9207705/_crash.zip)

```
ERROR:GAMESYS: Label could not be created since the label buffer is full (10).
INFO:CRASH: Successfully wrote Crashdump to file: C:\Users\subso\AppData\Roaming\Defold/_crash
ERROR:CRASH: CALL STACK:

ERROR:CRASH:  0 0x7FF7929726E0 dmCrash::GenerateCallstack D:\a\defold\defold\engine\crash\src\backtrace_win32.cpp:144

ERROR:CRASH:  1 0x7FF792A70958 _seh_filter_exe minkernel\crts\ucrt\src\appcrt\misc\exception_filter.cpp:219

ERROR:CRASH:  2 0x7FF792AB6874 `__scrt_common_main_seh'::`1'::filt$0 d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:304

ERROR:CRASH:  3 0x7FF792A03DB4 __C_specific_handler d:\agent\_work\4\s\src\vctools\crt\vcruntime\src\eh\riscchandler.cpp:290

ERROR:CRASH:  4 0x7FFDCC448D80 __chkstk <unknown>:0

ERROR:CRASH:  5 0x7FFDCC3D55F0 RtlRestoreContext <unknown>:0

ERROR:CRASH:  6 0x7FFDCC447E90 KiUserExceptionDispatcher <unknown>:0


ERROR:CRASH:  7 0x7FF7926030B0 dmGameObject::DoDeleteInstance D:\a\defold\defold\engine\gameobject\src\gameobject\gameobject.cpp:1881

ERROR:CRASH:  8 0x7FF792608600 dmGameObject::PostUpdate D:\a\defold\defold\engine\gameobject\src\gameobject\gameobject.cpp:2715

ERROR:CRASH:  9 0x7FF7925F3DF0 dmEngine::StepFrame D:\a\defold\defold\engine\engine\src\engine.cpp:1613

ERROR:CRASH: 10 0x7FF7925F4A70 dmEngineUpdate D:\a\defold\defold\engine\engine\src\engine.cpp:2094

ERROR:CRASH: 11 0x7FF7925F4C90 dmEngine::RunLoop D:\a\defold\defold\engine\engine\src\engine_loop.cpp:83

ERROR:CRASH: 12 0x7FF7925ED480 engine_main D:\a\defold\defold\engine\engine\src\engine_main.cpp:148

ERROR:CRASH: 13 0x7FF7929FEF44 __scrt_common_main_seh d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288

ERROR:CRASH: 14 0x7FFDCC0B54D0 BaseThreadInitThunk <unknown>:0

ERROR:CRASH: 15 0x7FFDCC3A4830 RtlUserThreadStart <unknown>:0

ERROR:CRASH: 
```
<hr/>

<table>
<tr><td>Build time</td><td>2022-07-26T10:22:01.861651</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>0bcffa30741078f7af1759d8a3ce4b01cb9a77f5</td></tr>
<tr><td>Defold engine sha</td><td>80b1b73fd9cdbd4682c2583403fddfbaf0919107</td></tr>
<tr><td>Defold version</td><td>1.3.4</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce RTX 3080 Ti/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 516.59</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 11</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by AGulev** [comment]
Look like [this](https://github.com/defold/defold/issues/6597) crash, but you have a repo case! Thank you for that!!!

**Comment by subsoap** [comment]
> Look like [this](https://github.com/defold/defold/issues/6597) crash, but you have a repo case! Thank you for that!!!

I have a copy of the project in the state where this happens saved if it's needed.

**Comment by AGulev** [comment]
yes, pls.

**Comment by AGulev** [comment]
Solved by https://github.com/defold/defold/pull/6848
Thank you @subsoap for a repo case!
