### ISSUE TITLE
Lua bytecode contains wrong chunknames

### ISSUE THREAD

**Issue by britzl** [defold/defold#6837]
**Describe the bug (REQUIRED)**
When we started generating bytecode also for standard Lua the chunkname was taken from the temporary file created during the compilation process. This is obviously incorrect as the Lua bytecode should use the original filename as the chhunkname.

**To Reproduce (REQUIRED)**
1. Build for HTML5
2. Generate an error or `print(debug.traceback())`
3. Notice that the filename(s) in the stacktrace look like temporary filenames and not the originals

**Expected behavior (REQUIRED)**
The original filenames should be shown in the stacktrace

**Defold version (REQUIRED):**
  - Version 1.3.5

**Platforms (REQUIRED):**
 - Platforms: HTML5

**Comment by AGulev** [comment]
@britzl I changed version to 1.3.5 because `Generate Lua bytecode for HTML5 bundles` is 1.3.5-beta feature
