### ISSUE TITLE
Profiler random crash

### ISSUE THREAD

**Issue by akrasnogor-ms** [defold/defold#6852]
**Describe the bug (REQUIRED)**
We have random crash:
```
2022-08-01 17:29:46.110 4524-7719/com.project.id A/libc: ../src/remotery/lib/Remotery.c:4201: void rmtMessageQueue_CommitMessage(Message *, MessageID): assertion "LoadAcquire((rmtU32*)&message->id) == MsgID_NotReady" failed
2022-08-01 17:29:47.018 4524-9421/com.project.id W/UnityAds: com.unity3d.services.core.connectivity.ConnectivityMonitor.connectionStatusChanged() (line:173) :: Unity Ads was not able to get current network type due to missing permission
2022-08-01 17:29:47.308 4524-7719/com.project.id I/defold: INFO:CRASH: Successfully wrote Crashdump to file: /data/user/0/com.project.id/files/_crash
2022-08-01 17:29:47.308 4524-7719/com.project.id E/defold: ERROR:CRASH: CALL STACK:
    
    # 0 pc        0x664 [vdso] <unknown>+0
    # 1 pc      0x14060 ...oid.runtime/lib64/bionic/libc.so abort+160
```

**To Reproduce (REQUIRED)**
We don't have clear steps to reproduce. Crash is random.

**Expected behavior (REQUIRED)**
No crash

**Defold version (REQUIRED):**
  - Version 1.3.4 (bd56d557d6dca58aa77b12b267ff349306551ff5)

**Platforms (REQUIRED):**
 - Platforms: Android
 - OS: Android 9.0
 - Device: Android a70

**Comment by britzl** [comment]
> We have random crash

No steps to reproduce? How often is it happening? Could it be related to engine reboot for instance (when downloading content and restarting the engine)?

> 2022-08-01 17:29:47.018 4524-9421/com.project.id W/UnityAds: com.unity3d.services.core.connectivity.ConnectivityMonitor.connectionStatusChanged() (line:173) :: Unity Ads was not able to get current network type due to missing permission

The stacktrace is broken and I think we can safely ignore this bit. But the assert in Remotery seems legit. We're investigating!

**Comment by akrasnogor-ms** [comment]
Hi @britzl 
Thanks for the quick response.

It's happening not often, even rare. But we have specific device, when this happen frequently. I describe this device in this issue.
I was talking with our QA, to try better understand steps to reproduce. Unfortunately nothing specific and not any engine reboot.
For case example steps he did, when it was happened:
- Start game
- Wait for fully game loading
- Stop and fully close application
- Start game again
- Did some actions in game gui window
- Close this window
- Did some core game actions
- Crash

Hope it can help.

**Comment by britzl** [comment]
> * Stop and fully close application
> * Start game again

Is this important? Or will the crash occur even if the game isn't stopped and restarted?

Another thing worth pointing out is that the profiler is not present in a release build. I assume this only happens in a debug build?

**Comment by akrasnogor-ms** [comment]
@britzl 
First question we will try to investigate and i response to you when we check this.
Answer on second question is yes, it's debug build.

**Comment by britzl** [comment]
> First question we will try to investigate and i response to you when we check this.

Thanks!

> Answer on second question is yes, it's debug build.

Ok! My assumption is that this problem will not happen in a release build (when the profiler is disabled)

**Comment by akrasnogor-ms** [comment]
@britzl Yes, thanks, we understand, that in release and with disabled profiler this crash won't happen.
