### ISSUE TITLE
Details of 'raw' gamepad input not generated

### ISSUE THREAD

**Issue by 8bitskull** [defold/defold#6857]
**Describe the bug (REQUIRED)**
Raw gamepad input should yield details on hats, axis, etc. 

**To Reproduce (REQUIRED)**
See repro project here:
https://forum.defold.com/uploads/short-url/qbD787eVUx0a4jiKViA7ni6Q6aU.zip

Launch project and connect gamepad. Raw gamepad input is pprint-ed, but does not contain useful information (axis, hats, etc).

**Defold version (REQUIRED):**
1.3.4

**Platforms (REQUIRED):**
Windows 10
Xbox 360 controller

**Minimal repro case project (OPTIONAL):**
See above.

**Comment by britzl** [comment]
It turns out that we do not forward raw input to .gui_scripts. Raw input only works in .script files.

**Comment by britzl** [comment]
Solved in 1.3.6
