### ISSUE TITLE
Html5 Render artifacts. Ios 15.4+

### ISSUE THREAD

**Issue by d954mas** [defold/defold#6862]
**Describe the bug (REQUIRED)**

Render artefacts. Something with atlas trimming. 
Html5 build. 
Ios 15.4+

We have a message from poki,  that on ios 15.4+ game have problems. 
I do not have ios, so please look. 
I share everything I know:) 

"Just wanted to share a bug with you caused by iOS 15.4. Any device on a version newer than 15.4 render all three BoxRob games glitchy like in the attached recording" .

**To Reproduce (REQUIRED)**
1. Enable sprite trim in atlas. 
2. Open on ios 15.4+

**Expected behavior (REQUIRED)**
Correct Render. 

**Defold version (REQUIRED):**
  - 1.2.186

**Platforms (REQUIRED):**
 - Platforms: Html5
 - OS: ios 15.4+

**Minimal repro case project (OPTIONAL):**

**Logs (OPTIONAL):**

**Workaround (OPTIONAL):**
Disable sprite trim in atlas. 
I make a new build,  with disabled trim Mode. Poki says that it fixed issue. 

**Screenshots (OPTIONAL):**

**Additional context (OPTIONAL):**

**Comment by d954mas** [comment]
Uploading boxrob-glitch.mp4…

**Comment by d954mas** [comment]
![Screenshot_20220808_225531_com Slack](https://user-images.githubusercontent.com/2655263/183503083-f0f49388-9626-4f1f-aec2-1fa401674a34.jpg)

**Comment by JCash** [comment]
THe trimming code doesn't really have anything to do with platforms, so I would think the issue should show on your desktop build as well.
Can you confirm @d954mas ?

**Comment by d954mas** [comment]
No. 
On pc, android everything ok.  I can't reproduce it.

**Comment by AGulev** [comment]
We made some changes when 9slice for sprites were implemented. 
I wasn't able to repo your isue using a simple repo case, could you pls build your project using 1.3.7 and provide a link pls (using your custom server or draft on POKI), I'll test it on my phone

**Comment by d954mas** [comment]
136:https://544727.selcdn.ru/boxrob-136/index.html
137:https://544727.selcdn.ru/boxrob-137/index.html

**Comment by AGulev** [comment]
1.3.6
If I update page many times then from time to time I see this (but sometimes it's fine): 
![IMG_A23A176C9232-1](https://user-images.githubusercontent.com/2209596/196932184-58b83dee-7224-4443-8710-cc3686db4eaa.jpeg)

1.3.7 
I tried to update it maybe 100 times, it just fine:
![IMG_8948B39B2D84-1](https://user-images.githubusercontent.com/2209596/196932340-2334c267-aaa5-4e35-8e32-36246286c95a.jpeg)

So, I'm closing ticket as resolved in 1.3.7
