### ISSUE TITLE
Profiler random crash #2

### ISSUE THREAD

**Issue by akrasnogor-ms** [defold/defold#6871]
**Describe the bug (REQUIRED)**
We get random crash:

Exception Type: Unknown (SIGSEGV)

Thread 0 Crashed:
0   game.so              0x725755ae00        GetSampleDigest (Remotery.c:6146)
1   game.so              0x725755aed0        [inlined] GetSampleDigest (Remotery.c:6180)
2   game.so              0x725755aed0        [inlined] GetSampleDigest (Remotery.c:6180)
3   game.so              0x725755aed0        [inlined] GetSampleDigest (Remotery.c:6180)
4   game.so              0x725755aed0        [inlined] GetSampleDigest (Remotery.c:6180)
5   game.so              0x725755aed0        [inlined] GetSampleDigest (Remotery.c:6180)
6   game.so              0x725755aed0        [inlined] GetSampleDigest (Remotery.c:6180)
7   game.so              0x725755aed0        GetSampleDigest (Remotery.c:6180)
8   game.so              0x7257558bb4        [inlined] bin_SampleTree (Remotery.c:6277)
9   game.so              0x7257558bb4        [inlined] Remotery_SendSampleTreeMessage (Remotery.c:6366)
10  game.so              0x7257558bb4        [inlined] Remotery_ConsumeMessageQueue
11  game.so              0x7257558bb4        Remotery_ThreadMain (Remotery.c:6674)
12  game.so              0x725755a400        StartFunc (Remotery.c:2139)
13  libc.so                         0x73a2b58b14        <unknown> + 496651045652
14  libc.so                         0x73a2af535c        <unknown> + 496650638172

**To Reproduce (REQUIRED)**
We don't have specific steps to reproduce.

**Defold version (REQUIRED):**
  - Version 1.3.4 (bd56d557d6dca58aa77b12b267ff349306551ff5)

**Platforms (REQUIRED):**
 - Platforms: Android
 - OS Version: Android 12 (SKQ1.211006.001 test-keys)
 - Device: Brand: POCO, Family: M2012K11AG, Manufacturer: Xiaomi

**Comment by britzl** [comment]
Is there any pattern to these crashes? During startup? Or maybe soon after you've started? Or at any time? Perhaps while loading content? After a reboot?

Can you reproduce it?

**Comment by akrasnogor-ms** [comment]
@britzl 
Hi, thanks for response. As i know, we don't have any specific pattern for this crash. Someone just play game, test his work and get crash. 
But we try to investigate this and find some pattern for this crash.
