### ISSUE TITLE
Profiler and “Drawcalls” value 

### ISSUE THREAD

**Issue by Dragosha** [defold/defold#6872]
Is it possible to pull up “Drawcalls” value from the bottom of profiler screen to the top part?  For now it's impossible to view this value without stretching a game window to the second monitor to see it:
### Actual behaviour
![2022-08-11_15-37-49](https://user-images.githubusercontent.com/842807/184145038-43dcf847-1986-4243-9dd8-5ff399200e3c.png)

### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2022-08-11T06:45:53.284308</td></tr>
<tr><td>Defold channel</td><td>beta</td></tr>
<tr><td>Defold editor sha</td><td>732df13427f20ea673d3f159b26657d3b512b6a0</td></tr>
<tr><td>Defold engine sha</td><td>732df13427f20ea673d3f159b26657d3b512b6a0</td></tr>
<tr><td>Defold version</td><td>1.3.5</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 516.59</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
I think we need to look at some paging system or similar. It's hard to guarantee that everything will fit on a single screen.

Perhaps:

```
-- how to know how many pages?
profiler.set_ui_view_mode(profiler.VIEW_MODE_PAGED, { page = 1 })
-- or maybe multiple calls will step through the pages?
profiler.set_ui_view_mode(profiler.VIEW_MODE_PAGED)

-- or show the Graphics tree of the properties
profiler.set_ui_view_mode(profiler.VIEW_MODE_PROPERTIES, { property = "Graphics" })
profiler.set_ui_view_mode(profiler.VIEW_MODE_FULL, { property = "Graphics" })
```

**Comment by AGulev** [comment]
@britzl what about changing layout ?
<img width="963" alt="image" src="https://user-images.githubusercontent.com/2209596/184226583-62b20048-058a-496b-804c-929c50131b19.png">

**Comment by britzl** [comment]
Change layout how?

**Comment by AGulev** [comment]
@britzl do you see screenshot I posted?

**Comment by AGulev** [comment]
move element from the middle of the screen to the right top corner :
OLD:

![](https://user-images.githubusercontent.com/842807/184145038-43dcf847-1986-4243-9dd8-5ff399200e3c.png)


NEW:
<img width="760" alt="image" src="https://user-images.githubusercontent.com/2209596/184230075-d6a089f6-b04b-47db-a0e1-9e2b90529ba8.png">

**Comment by britzl** [comment]
Ah, yes, that is indeed better! It looks like the line spacing is smaller as well?

**Comment by AGulev** [comment]
yes, smaller line spacing and dedicated zone for the properties
The middle part with frame time graph will change its size dynamically:

https://user-images.githubusercontent.com/2209596/184233898-aa93a12c-cb8b-43c2-8d9e-16395cf76424.mp4
