### ISSUE TITLE
Failed to connect to debugger on localhost

### ISSUE THREAD

**Issue by PrashantVaingankar** [defold/defold#6876]
### Steps to reproduce: Click on Debug -> Start/Attach or press F5.

<hr/>

<table>
<tr><td>Build time</td><td>2022-08-03T15:44:10.402194</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>bf0a1d0c8606d2962364234720f2459f69fd62de</td></tr>
<tr><td>Defold engine sha</td><td>80b1b73fd9cdbd4682c2583403fddfbaf0919107</td></tr>
<tr><td>Defold version</td><td>1.3.4</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"0c73a03c776e443697a899ac18aeda04"'>0c73a03c776e443697a899ac18aeda04</a></td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 512.33</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 11</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
```
editor.debugging.mobdebug$connect_BANG_$fn__43465.invoke.class clojure.lang.ExceptionInfo: Failed to connect to debugger on localhost:8172
    at editor.debugging.mobdebug$connect_BANG_$fn.invoke(mobdebug.clj:341)
    at clojure.lang.AFn.run(AFn.java:22)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.lang.Thread.run(Thread.java:829)
```

**Comment by britzl** [comment]
@PrashantVaingankar Does this happen all the time?

**Comment by PrashantVaingankar** [comment]
Hi,

It did not allow me to debug at all with the latest release 1.3.4. So I
installed the previous version 1.3.3 and it allowed me to debug without
any issues.

Hence using the previous version now.

Regards,
Prashant Vaingankar

**Comment by AGulev** [comment]
@PrashantVaingankar could you pls try 1.3.5 if it works?

**Comment by AGulev** [comment]
no action from the reporter
