### ISSUE TITLE
Breakpoints no longer seen by debugger

### ISSUE THREAD

**Issue by PaStef** [defold/defold#6885]
### Expected behaviour
Toggle breakpoint (by click or F9), and the debugger stops at breakpoint.
### Actual behaviour
Debugger never stops at any breakpoint anymore, on any project, even untouched exemples from Druid and Monarch. Seems to be since last update (on 16/08 late night here). Starting in debug or attaching debugger later makes no difference.
### Steps to reproduce
Toggle breakpoint and run debugger on any project (Druid for example)
<hr/>

<table>
<tr><td>Build time</td><td>2022-08-16T12:09:11.544484</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>8ad212a4b67ab4f7fa82b38f39e9033051104448</td></tr>
<tr><td>Defold engine sha</td><td>28eafea5a8bfedfddc621a7cd00b39f25bd34922</td></tr>
<tr><td>Defold version</td><td>1.3.5</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce RTX 2060 SUPER/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 512.77</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by matgis** [comment]
Fixed in 1.3.6.
