### ISSUE TITLE
Breakpoints do nothing

### ISSUE THREAD

**Issue by JustAPotota** [defold/defold#6888]
**Describe the bug (REQUIRED)**
Breakpoints don't pause the debugger when reached. All of the other debugger features seem to work.

**To Reproduce (REQUIRED)**
1. Place some breakpoints
2. Select `Debug > Start / Attach`

**Defold version (REQUIRED):**
1.3.5 beta
![image](https://user-images.githubusercontent.com/43710172/185253594-84f51289-ce50-4239-9429-76cdf940f66a.png)

**Platforms (REQUIRED):**
Pop!_OS 22.04 LTS

**Screenshots (OPTIONAL):**

https://user-images.githubusercontent.com/43710172/185254346-cee73d6b-8739-496e-84d1-43192cd82538.mov

**Comment by britzl** [comment]
Fixed in https://github.com/defold/defold/pull/6886
