### ISSUE TITLE
Add support for working with arrays in go

### ISSUE THREAD

**Issue by aagafonov-ms** [defold/defold#6890]
**Is your feature request related to a problem? Please describe (REQUIRED):**
We wanna work with data-component https://github.com/defold/extension-simpledata, which could get array for const time. We can get array now only O(N) depends on length of array, because we should get element 1 by 1:
https://github.com/defold/extension-simpledata/blob/main/main/main.script#L11-L13

**Describe the solution you'd like (REQUIRED):**
API for getting array by one call and const time. `go.get_array()` or  that `go.get()` could return arrays

**Describe alternatives you've considered (REQUIRED):**
Alternatives haven't been found

**Comment by britzl** [comment]
An example of getting the entire array in a single function call has been added in the `extension-simpledata` extension: https://github.com/defold/extension-simpledata/pull/6/files
