### ISSUE TITLE
Run engine building in parallel with tasks creation process

### ISSUE THREAD

**Issue by AGulev** [defold/defold#6897]
**Task (REQUIRED):**
Now Bob waits when the engine build finished to start Tasks creation process. That would be more efficient if we do these processes in parallel

(parallelization should be taken into account in the build time report)
<img width="671" alt="image" src="https://user-images.githubusercontent.com/2209596/185561712-044e7bec-6909-4390-bfe5-0a8a0729f249.png">

And then, when both are done continue with building process

**Expected outcome (REQUIRED):**
Faster bundle creation from bob.

**Comment by britzl** [comment]
Related: https://github.com/defold/defold/issues/3953

**Comment by aglitchman** [comment]
It would be really great to build remote engine + create/build tasks in parallel!

It takes half of the time in our project to build the engine (for HTML5 target) - 

![image](https://github.com/defold/defold/assets/193258/5227f346-597c-4c6b-b3a0-bc062a3633ea)
