### ISSUE TITLE
No grid size parameter

### ISSUE THREAD

**Issue by ekkl** [defold/defold#6900]
**Describe the bug (REQUIRED)**
Linux Fedora 64 bit
Is this able to change grid size parameter.
I can't to find this tab.
![Знімок екрану_2022-08-21_20-45-59](https://user-images.githubusercontent.com/5430541/185804109-85862ded-414b-4f5e-986b-c1b021f779e2.png)

**Comment by britzl** [comment]
@ekkl we removed this option a while back. Did you find it mentioned in the documentation?

**Comment by ekkl** [comment]
No.
Obviously I was looking at outdated examples

**Comment by AGulev** [comment]
closed as duplicate of https://github.com/defold/defold/issues/6421
