### ISSUE TITLE
[1.3.6-alpha] breakpoints in lua modules do not display current line

### ISSUE THREAD

**Issue by RealityStop** [defold/defold#6903]
**Describe the bug (REQUIRED)**
It does break on the breakpoint, but there is no visual indicator for the current execution point.

**To Reproduce (REQUIRED)**
1. Create a lua module
2. Place a breakpoint in it
3. Call it from a .script
4. Debug

**Expected behavior (REQUIRED)**
the indicator would be shown, similar to how it is shown for debugging .script files.

**Defold version (REQUIRED):**
1.3.6-alpha (SHA1: a7c5b9f5cb6826c153da6386a6e47adaf52143d3)

**Platforms (REQUIRED):**
 - Editor, in Windows 10, though I suspect any would do

**Screenshots (OPTIONAL):**
As you can see in this screenshot, the editor is actually at the breakpoint (as both the call stack and variables window show), but there is no indication of which line (other than constantly referring to the call stack, of course).

https://i.imgur.com/CX187pL.png

**Comment by britzl** [comment]
Solved in 1.3.6 stable
