### ISSUE TITLE
can't paste in asset browser

### ISSUE THREAD

**Issue by tigerteeth** [defold/defold#6910]
### Expected behaviour
Paste a file I just cut using ctrl + x

### Actual behaviour
error message appears

### Steps to reproduce

ctrl + x then ctrl + z in the asset browser

<hr/>

<table>
<tr><td>Build time</td><td>2022-04-21T12:53:52.515047</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>9df2b26c5a6ce8e23b0294d2fecd671f7326c108</td></tr>
<tr><td>Defold engine sha</td><td>06bc078e490fd7d94ec01e38abac989f6cc351a5</td></tr>
<tr><td>Defold version</td><td>1.3.1</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"c0733630b6cc4907b5ec009a85795ed2"'>c0733630b6cc4907b5ec009a85795ed2</a></td></tr>
<tr><td>GPU</td><td>Apple M1</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 71.6.4</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.16</td></tr>
<table>

**Comment by AGulev** [comment]
can't reproduce
