### ISSUE TITLE
Build error:  Could not initialize class com.dynamo.bob.TexcLibrary

### ISSUE THREAD

**Issue by xanjay** [defold/defold#6917]
### Expected behaviour
Build project
### Actual behaviour
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: Could not initialize class com.dynamo.bob.TexcLibrary
java.lang.NoClassDefFoundError: Could not initialize class com.dynamo.bob.TexcLibrary
### Steps to reproduce
Run Build
<hr/>

<table>
<tr><td>Build time</td><td>2022-08-21T07:04:33.418361</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>28d332c9d67b9c8df35fed1274729322ecfd79f1</td></tr>
<tr><td>Defold engine sha</td><td>c1c0592986a4421f33490422c2af532e533aeca5</td></tr>
<tr><td>Defold version</td><td>1.3.5</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"fe924b441f1b42da94619e8bf579b7ca"'>fe924b441f1b42da94619e8bf579b7ca</a></td></tr>
<tr><td>GPU</td><td>Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2) </td></tr>
<tr><td>GPU Driver</td><td>3.0 Mesa 19.2.8</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>4.15.0-106-generic</td></tr>
<table>

**Comment by britzl** [comment]
@xanjay could you please check which version of glibc you have on your system? Previous issues of a similar kind have been solved by a glibc update to 2.2.9+.

* https://github.com/defold/defold/issues/6745
* https://github.com/defold/defold/issues/6282#issuecomment-1004946204

**Comment by xanjay** [comment]
@britzl below is the current glibc version on my machine.
ldd (Ubuntu GLIBC 2.27-3ubuntu1) 2.27

**Comment by britzl** [comment]
@xanjay could you please try updating glibc to 2.29?

**Comment by AGulev** [comment]
Requested additional info wasn't provided
