### ISSUE TITLE
Problem building Defold from source on Windows 10

### ISSUE THREAD

**Issue by britzl** [defold/defold#6921]
**Describe the bug (REQUIRED)**
From Discord user Oldman_Sam. Post https://discord.com/channels/250018174974689280/817016084208681000/1012933106325520414.

I'm using windows 10 and I'm just using the default CMD with admin access. I open CMD, cd to where defold is and run the following:

`scripts\build.py shell`

This starts up Ubuntu WSL and then I run:

`./scripts/build.py distclean` - Because of how often I try and run these scripts I want to clean it out.

Then I run:

`./scripts/build.py install_ext --platform=win32 --package-path=...`

Which runs fine and gives no error indication as far as I can see. 

`/scripts/build.py build_engine --platform=win32`

which gives the error:

![image](https://user-images.githubusercontent.com/1300688/187297718-26944105-9cf8-4bb5-afa3-fe39e010f47a.png)

**Comment by britzl** [comment]
We need to know more about the packaging of SDKs since it seems like some SDKs are missing.

**Comment by AGulev** [comment]
idk if it's still an issue

**Comment by AGulev** [comment]
It looks like outdated issue.
