### ISSUE TITLE
Arm support

### ISSUE THREAD

**Issue by zai1208** [defold/defold#6922]
Can someone make this engine run on arm chips, like the ones found in chrome books?

**Comment by britzl** [comment]
You mean for the editor or for the engine runtime?

Our current focus is to add engine support for arm64-macos (ie Apple M1). Next step will be the editor. And later possibly also expand to other systems such as Chromebooks, Raspberry Pi etc.

**Comment by zai1208** [comment]
I guess I can wait,
Can i try to manually add support?

**Comment by britzl** [comment]
> Can i try to manually add support?

Absolutely. You need to adapt our build system and all tools so that they are able to produce ARM builds. You can read a bit about the basic setup for building the engine and editor here: https://github.com/defold/defold/blob/dev/README_BUILD.md

**Comment by AGulev** [comment]
We have tasks for that:
https://github.com/defold/defold/issues/7299
https://github.com/defold/defold/issues/7300

When it's done, we will add task for editor support as well.
