### ISSUE TITLE
Acquire input checkbox for collection proxy

### ISSUE THREAD

**Issue by AGulev** [defold/defold#6923]
**Is your feature request related to a problem? Please describe (REQUIRED):**
From time to time developers complains that they can't receive input in loaded collection. The most frequent reason is missing input acquiring. 

**Describe the solution you'd like (REQUIRED):**
Maybe it worth to add such a checkbox for collection proxy component to make it more intuitive and easier?

**Describe alternatives you've considered (REQUIRED):**
We already have a rea WARNING in manual about it, but it seems like it's not enough.

**Comment by britzl** [comment]
What if `acquire_input_focus` from a script on an object inside a loaded collection also set input focus on the proxy itself? Or it was optional in the message (or function call if we ever change it to that).

**Comment by AGulev** [comment]
> What if `acquire_input_focus` from a script on an object inside a loaded collection also set input focus on the proxy itself?

I think it's also a nice option. More "automatic"

**Comment by AGulev** [comment]
This will make understanding of the input stack order even harder: https://forum.defold.com/t/simple-example-for-better-understanding-of-the-input-stack/77053

I'm closing it for now
