### ISSUE TITLE
Error when deleting form entry while editing it

### ISSUE THREAD

**Issue by DeRaNGeR** [defold/defold#6924]
**Describe the bug (REQUIRED)**
When editing a form such as input bindings and adding a new entry but not filling out all data and immediately deleting the entry will cause a crash

**To Reproduce (REQUIRED)**

1. open game.input_binding file
2. add one action
![image](https://user-images.githubusercontent.com/5565814/187947657-51149cbc-1575-4a93-995c-98c5becb7a41.png)
3. when you want to insert the "name" for that action, leave it empty and without blur the textfield click on the minus icon
4. Observe error
![image](https://user-images.githubusercontent.com/5565814/187947723-ef3a92d8-0961-446d-8bf0-3f232a607bf5.png)

**Expected behavior (REQUIRED)**
No crash

**Defold version (REQUIRED):**
  - Version 1.3.4

**Platforms (REQUIRED):**
 - Platforms: any
 - OS: Windows 11
 - Device: Laptop

**Comment by matgis** [comment]
I can't reproduce this. I'm able to copy and paste text from this bug report into the Defold code editor while editing a `.vp` file. Are you sure you had text content in the clipboard? We can only paste simple text data.

**Comment by DeRaNGeR** [comment]
Hi, i made another try and i understand that the problem is not the editor but a bug that happens when you don't delete correctly a value from input handling file.

Try to do these steps:
1. open defold
2. open or create a project with at least one script file and a sprite
3. go to the input_handling file
4. add one voice
5. when you want to insert the "name" for that action, leave it empty and without blur the textfield click on the minus icon
![image](https://user-images.githubusercontent.com/5565814/187947657-51149cbc-1575-4a93-995c-98c5becb7a41.png)
6. at this moment you could have a dialog with a bug alert
6b. if you don't have in that moment, save the file and you got the error
![image](https://user-images.githubusercontent.com/5565814/187947723-ef3a92d8-0961-446d-8bf0-3f232a607bf5.png)


At this moment you cannot close defold, not copy paste or select all the text inside script editors, problem with 2d 3d navigation and other glitch on defold
![image](https://user-images.githubusercontent.com/5565814/187947825-7a824d5a-55e5-4a6f-a412-2f565962a3a4.png)

The problem is the uncorrectly deleting the row from input handling values
