### ISSUE TITLE
32bit engine on Windows fails to decode render script bytecode.

### ISSUE THREAD

**Issue by alex-ac** [defold/defold#6927]
**Describe the bug (REQUIRED)**
Trying to setup testing in CI using headless version of the engine. Found that headless variant on x86-win32 does not work properly.

**To Reproduce (REQUIRED)**
1. Create new empty project.
2. Bundle for x86-win32 in headless variant:
```
java -jar bob.jar --verbose --root . --output build\default resolve
java -jar bob.jar --verbose --root . --output build\default --keep-unused --archive build
java -jar bob.jar --verbose --root . --output build\default --variant headless --bundle-output ./build/x86-win32 --platform x86-win32 --architectures x86-win32 bundle
```
3. Run the bundled game.
```
build\x86-win32\defold-sandbox\defoldsandbox.exe
```

**Expected behavior (REQUIRED)**
Engine should run as usual.

**Defold version (REQUIRED):**
version: `1.3.5`
sha1: `c1c0592986a4421f33490422c2af532e533aeca5`

**Platforms (REQUIRED):**
 - Platforms: Windows 32bit
 - OS: Windows 2022 Datacenter (10.0.20348)

**Minimal repro case project (OPTIONAL):**
Seeing it on https://github.com/alex-ac/defold-sandbox but I'm sure that you can reproduce it on any project.

**Logs (OPTIONAL):**
```
INFO:DLIB: Log server started on port 62295
INFO:ENGINE: Target listening with name: fv-az140-136 - fe80::45e2:8d2e:cd3d:bbd8 - Windows
INFO:ENGINE: Engine service started on port 8001
INFO:GRAPHICS: Initialised graphics device 'null'
INFO:ENGINE: Defold Engine 1.3.5 (c1c0592)
INFO:DLIB: MAWE: Create global Remotery instance!
INFO:DLIB: Initialized Remotery (ws://127.0.0.1:17815/rmt)
INFO:ENGINE: Loading data from: dmanif:build/default/game.dmanifest
INFO:ENGINE: Initialised sound device 'default'
ERROR:RENDER: Error running script: builtins/render/default.render_script: cannot load incompatible bytecode
WARNING:RESOURCE: Unable to create resource: /builtins/render/default.render_scriptc: FORMAT_ERROR
WARNING:RESOURCE: Unable to create resource: /builtins/render/default.renderc: FORMAT_ERROR
ERROR:ENGINE: Unable to load bootstrap data.
```

**Workaround (OPTIONAL):**
 x86_64-win32 works without issues.
~~I think non-headless version works without issues as well.~~ It does not.

**Comment by britzl** [comment]
Thank you for reporting this! We did have an issue with 32 bit bytecode when a project was built for both 32 and 64 bit, but this fix is included in the version you are running. Also in your case it looks like you are building for only 32 bit, so the delta patch for 32 bit is not applied. The 32 bit bytecode is supposed to be stored as is.

**Comment by britzl** [comment]
> I think non-headless version works without issues as well.

I'm also surprised by this. Is that really the case? A 32-bit only windowed build works?

**Comment by alex-ac** [comment]
Re-checked another time. Got the same error for non-headless variant.

**Comment by britzl** [comment]
@alex-ac I don't have a 32-bit Windows install at hand. I have tried on a 32-bit Android device and I do not get an error.

BUT I think I've spotted a problem. In your instructions you run your build in three steps: 1) resolve 2) build and 3) bundle

This is fine if it weren't for the fact that you do not specify a platform and architecture for the build step. If a platform isn't provided when building, the host platform will be used. What this means is that you are building assets (Lua bytecode etc) for the host and then trying to use it on a different system (32-bit windows).

Please add a platform to your build step as well (or do both in one go):

```
java -jar bob.jar --verbose --root . --output build\default resolve
java -jar bob.jar --verbose --root . --output build\default --keep-unused --archive --platform x86-win32 --architectures x86-win32 build
java -jar bob.jar --verbose --root . --output build\default --variant headless --bundle-output ./build/x86-win32 --platform x86-win32 --architectures x86-win32 bundle
```

**Comment by alex-ac** [comment]
> This is fine if it weren't for the fact that you do not specify a platform and architecture for the build step. If a platform isn't provided when building, the host platform will be used. What this means is that you are building assets (Lua bytecode etc) for the host and then trying to use it on a different system (32-bit windows).

Could you clarify that moment in the documentation? Because right now I read it as "you don't need to specify platform when build":

``` -p,--platform <arg>                     Platform (when bundling)```

**Comment by britzl** [comment]
Oh, yes, I've updated the bob manual
