### ISSUE TITLE
Error with Build HTML and URL parameters

### ISSUE THREAD

**Issue by sergeysinyavsky** [defold/defold#6940]
### Actual behaviour

When I run a **Build HTML** and start loading a JS script with parameters, I get an error in the **editor**:

    java.nio.file.InvalidPathException: Illegal char <?> at index 17: data/some_file.js?some_param=some_data

Everything works fine without parameters.
Also with the  bundle everything is fine.

### Expected behaviour

Js script with url parameters loaded successfully

### Steps to reproduce

    html5.run([[
        var script = document.createElement('script');
        script.src = './data/some_file.js?some_param=some_data';
        document.body.appendChild(script);
    ]])
    
Run **Build HTML**

[Bug.zip](https://github.com/defold/defold/files/9477343/Bug.zip)

As far as I understand it is related to these issues:
https://github.com/defold/editor2-issues/issues/2220
https://github.com/defold/editor2-issues/issues/2282

<hr/>

<table>
<tr><td>Build time</td><td>2022-08-21T07:05:23.543939</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>28d332c9d67b9c8df35fed1274729322ecfd79f1</td></tr>
<tr><td>Defold engine sha</td><td>c1c0592986a4421f33490422c2af532e533aeca5</td></tr>
<tr><td>Defold version</td><td>1.3.5</td></tr>
<tr><td>GPU</td><td>Radeon RX 580 Series</td></tr>
<tr><td>GPU Driver</td><td>4.6.14800 Compatibility Profile Context 22.6.1 30.0.21023.1015</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by AGulev** [comment]
it seems like this issue solved in 1.3.7
