### ISSUE TITLE
error to publish for Android

### ISSUE THREAD

**Issue by bdshahab** [defold/defold#6943]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2022-08-21T07:05:23.543939</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>28d332c9d67b9c8df35fed1274729322ecfd79f1</td></tr>
<tr><td>Defold engine sha</td><td>c1c0592986a4421f33490422c2af532e533aeca5</td></tr>
<tr><td>Defold version</td><td>1.3.5</td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 530</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 - Build 26.20.100.7262</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
For some reason there's no link to a Sentry error. @bdshahab what kind of error did you get?

**Comment by britzl** [comment]
No additional information provided. Closing. Please reopen with additional information if it can be provided.
