### ISSUE TITLE
Using the scrollwheel on HTML5 builds causes an error

### ISSUE THREAD

**Issue by scalemaildev** [defold/defold#6964]
When attempting to use the mousewheel on a HTML5 build of Defold, the following error occurs:

![Screenshot_20220908_081805](https://user-images.githubusercontent.com/15042849/189182917-14ceaa7e-0ce1-43f6-825b-30fb956b3a05.png)

Version: 1.3.5
Platform: Linux Manjaro
Browser: Brave Browser

Should be reproducable on any client.

The error links to this url: https://www.chromestatus.com/feature/6662647093133312

**Comment by AGulev** [comment]
related https://github.com/defold/defold/issues/6201
