### ISSUE TITLE
Some way to apply game.project values using the Mustache templates to a custom file (`.cpp`, `.h` etc) in extension

### ISSUE THREAD

**Issue by AGulev** [defold/defold#6966]
**Is your feature request related to a problem? Please describe (REQUIRED):**
To be able to configure a complicated extensions such as an ADS mediation that would be useful to insert values from game.project file into a custom file from the extension.
I see use cases for ADS mediation, improvements for https://github.com/defold/extension-resource-encryption  and the other cases of embedding values from game.project into cpp, for example because of security reasons.

**Describe the solution you'd like (REQUIRED):**
Some way to specify what files should be compiled with the Mustache templater using values from game.project.
Another way is to apply Mustache to files from some specific folder.

**Additional context (OPTIONAL):**
If this will be a universal way to do so for any file, then it may cover https://github.com/defold/defold/issues/6965 as well

**Comment by JCash** [comment]
Practically, I think of this as generating a new header file (which is a common practice).

**Comment by AGulev** [comment]
@JCash but what about `java` for ex, or if we need it in `js`?

**Comment by britzl** [comment]
This feature request has a much too big scope. We need to find a simpler way of applying values from game.project. Running all files through mustache or other templating engine is not a good solution. Closing.
