### ISSUE TITLE
Crashes on debug android build with non default update frequency 

### ISSUE THREAD

**Issue by Sippul** [defold/defold#6989]
**Describe the bug (REQUIRED)**

If we set following settings for project:

vsync = 0
update_frequency = 60

then debug build crashes on android almost with 100% reproduction after several seconds after start

**To Reproduce (REQUIRED)**
1. set 
 vsync = 0 
 update_frequency = 60
2. run debug build on android

**Expected behavior (REQUIRED)**
Do not crash

**Defold version (REQUIRED):**
1.3.4 - 1.3.6

**Platforms (REQUIRED):**
 - Android 9, 10, 11 (Checked on all)

**Minimal repro case project (OPTIONAL):**
[TestCrash.zip](https://github.com/defold/defold/files/9610534/TestCrash.zip)

Crash log from 1.3.4:

* * * * * * * * * * * * * * * *
Build fingerprint: 'Redmi/begonia_ru/begonia:9/PPR1.180610.011/V11.0.5.0.PGGRUXM:user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 26186, tid: 26217, name: Remotery  >>> com.arenum.testcrash <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
Cause: null pointer dereference
    x0  0000000000000000  x1  00000073e7679f0e  x2  00000073ddb39c00  x3  00000073e73f0b58
    x4  00000073e6bfef18  x5  00000073f852b016  x6  000000748ce8c000  x7  00000073e7679f0e
    x8  00000073ffe1bcd0  x9  00000073e7777000  x10 0101010101010101  x11 0000000000000099
    x12 0000000000000018  x13 000000006329f156  x14 00192691564d3f8e  x15 000042e89b13c25c
    x16 00000073e7702228  x17 00000074882a01c0  x18 0000000000000000  x19 00000073ddb39c00
    x20 00000073ffe1bcd0  x21 0000000000000000  x22 00000000000003e8  x23 00000000000002be
    x24 00000073e6cd9108  x25 00000073e7777d60  x26 00000073ffffe3c0  x27 00000073ddb39c00
    x28 00000073e6cd9118  x29 0000000000000000
    sp  00000073e6bfec70  lr  00000073e73f0b8c  pc  00000074882a0248

backtrace:
    #00 pc 000000000001e248  /system/lib64/libc.so (strcmp+136)
    #01 pc 000000000005cb88  /data/app/com.arenum.testcrash-ukhOKitX_ueG4BwDVbj2Rw==/lib/arm64/libTestCrash.so (dmProfiler::SampleTreeCallback(void*, char const*, void*)+48)
    #02 pc 000000000005a0e4  /data/app/com.arenum.testcrash-ukhOKitX_ueG4BwDVbj2Rw==/lib/arm64/libTestCrash.so (Remotery_ThreadMain+12760)
    #03 pc 000000000005b40c  /data/app/com.arenum.testcrash-ukhOKitX_ueG4BwDVbj2Rw==/lib/arm64/libTestCrash.so (StartFunc+16)
    #04 pc 0000000000083344  /system/lib64/libc.so (__pthread_start(void*)+36)
    #05 pc 000000000002348c  /system/lib64/libc.so (__start_thread+68)

Crash log from 1.3.6:

A/libc: ../src/remotery/lib/Remotery.c:4233: void rmtMessageQueue_CommitMessage(Message *, MessageID): assertion "LoadAcquire((rmtU32*)&message->id) == MsgID_NotReady" failed
I/defold: INFO:CRASH: Successfully wrote Crashdump to file: /data/user/0/com.arenum.testcrash/files/_crash
E/defold: ERROR:CRASH: CALL STACK:
    
    # 0 pc     0x22f730 ...YODA==/lib/arm64/libTestCrash.so _ZN7dmCrashL7HandlerEiP7siginfoPv+60
    # 1 pc        0x638 [vdso] <unknown>+0
    # 2 pc      0x21b78 /system/lib64/libc.so abort+120

**Comment by Sippul** [comment]
it does not crashes if exclude profiler with appmanifest

**Comment by britzl** [comment]
@Sippul does this also crash with the stable 1.3.6 release?

**Comment by AGulev** [comment]
Fixed in 1.3.7
