### ISSUE TITLE
Timer - get time remaining until next call

### ISSUE THREAD

**Issue by 8bitskull** [defold/defold#6995]
Would like a function to get the time remaining until the next time a timer.delay() fires.

Example use case: I fire player weapons using timer.delay(). The player obtains a weapon cooldown upgrade, which means I need to restart all weapon timers in a new interval. However, I do not know how near a shot the weapon timers are, so either have to reset them entirely or implement a workaround.

**Comment by d954mas** [comment]
I want to try implement this.

   1)What you think method should return if timer is already cancelled or completed nil, 0?
   2)What you think about returning 2 values m_Remaining and m_Delay.
   It easy to return both and it can be usefull.

**Comment by 8bitskull** [comment]
Maybe one of the Defold guys can pitch in, because I'm not experienced with professional level feature scoping.

1) To me, it feels like 0 means either "timer will fire right now" or "timer has just fired". It doesn't feel right for a cancelled timer, or at least it has the potential to be confusing. So to me, nil feels more appropriate.
2) I only rarely use multiple return values in Lua so am not super familiar with them. So long as I can just get "remaining" easily by default, then getting "delay" as an option is just a bonus.

**Comment by britzl** [comment]
> 1. To me, it feels like 0 means either "timer will fire right now" or "timer has just fired". It doesn't feel right for a cancelled timer, or at least it has the potential to be confusing. So to me, nil feels more appropriate.

I agree. It should not return 0, nil is better in this case.

> What you think about returning 2 values m_Remaining and m_Delay

> I only rarely use multiple return values in Lua so am not super familiar with them. So long as I can just get "remaining" easily by default, then getting "delay" as an option is just a bonus.

My initial thought was to add a `timer.remaining(handle)` or `timer.get_remaining(handle)` that would return the remaining time. This function could potentially also return the delay, but the name of the function isn't really representing what the function actually does. It does more than returning the remaining time. 

Perhaps it is better to add a `timer.get_info(handle)` or `timer.get(handle)` that returns a table:

```
local handle = timer.delay(2, true, function() end)

--after 0.5 seconds we call:

local info = timer.get_info(handle)
print(info.time_remaining) -- 1.5
print(info.delay)     -- 2
print(info.repeating) -- true

-- possibly also
print(timer.time_elapsed)  -- 0.5
print(timer.cancelled)     -- true|false
print(timer.completed)     -- true|false
```

**Comment by d954mas** [comment]
timer.get_info() sounds good.
 This values ok. 
```lua
print(info.time_remaining) -- 1.5
print(info.delay)     -- 2
print(info.repeating) -- true
```

about possibly values
1)time_elapsed can be calculated
2)cancelled and completed.
If I understand right,  when timer completed or cancelled 
It removed. So for cancelled and completed timers I can't get info(delay, time_remaining, repeating) 
I think for that timers is better to return nil

**Comment by britzl** [comment]
> If I understand right, when timer completed or cancelled
> It removed. So for cancelled and completed timers I can't get info(delay, time_remaining, repeating)
> I think for that timers is better to return nil

Ah, yes, you are right. We should return either nil or perhaps even better: `timer.INVALID_TIMER_HANDLE`

**Comment by britzl** [comment]
Now that I think of it returning nil is easier to deal with and check, so I vote for nil.

**Comment by britzl** [comment]
> I fire player weapons using timer.delay(). The player obtains a weapon cooldown upgrade, which means I need to restart all weapon timers in a new interval. However, I do not know how near a shot the weapon timers are, so either have to reset them entirely or implement a workaround.

How would this look in pseudo code? Let's say we provide a timer.get_info(handle) function which returns a table with info about timer interval and remaining time. What would the rest of the code look like?

```
local h = timer.delay(2.5, true, function() end)

...

local info = timer.get_info(h)
print(info.time_remaining) -- the remaining time before the timer triggers next
print(info.delay) -- 2.5 (set above on timer.delay call)
print(info.repeat) -- true (this is a repeating timer)

-- what would you do with this information to achieve the goal mentioned above?
```

**Comment by 8bitskull** [comment]
Here is what I would do:

```
--set up timer
local weapon_timer = timer.delay(2.5, true, fire_weapon)

--recalculate after cooldown change

--get timer info
local info = timer.get_info(weapon_timer)

--calculate a 10% cooldown decrease
local new_cooldown = 2.5 * 0.9

--calculate new time remaining for next shot
local new_time_remaining = (info.time_remaining / 2.5) * new_cooldown

--cancel old timer
timer.cancel(weapon_timer)

--finish current shot, then restart timer with new cooldown
weapon_timer = timer.delay(new_time_remaining, false, function()
    fire_weapon()
    weapon_timer = timer.delay(new_cooldown, true, fire_weapon)
end)
```

This is a good question because it highlights an entirely separate issue that I hadn't considered. I would like to be able to either change the time remaining on an existing timer, or be able to create a new timer with two different times (a first delay and a repeating delay). The pseudocode here might work but it feels a bit messy to wrap a timer on itself to achieve the effect. It might be out of scope for this issue but thought I would raise it anyway - it could warrant opening a separate issue, but it also might inform your design for this issue.

**Comment by britzl** [comment]
> This is a good question because it highlights an entirely separate issue that I hadn't considered

> it feels a bit messy to wrap a timer on itself to achieve the effect

I agree with you that this isn't as straight forward as one might think. A `timer.set_delay(handle, new_delay)` might be more appropriate in your situation actually. The code would then look like this:

```
--set up timer
local weapon_timer = timer.delay(2.5, true, fire_weapon)

--recalculate after cooldown change

--calculate a 10% cooldown decrease
local new_cooldown = 2.5 * 0.9

--update timer with new delay
timer.set_delay(weapon_timer, new_cooldown)
```

**Comment by 8bitskull** [comment]
Yes, however this neglects the time already elapsed. Continuing my specific use case, this might conceivably mean that a weapon with a very long cooldown (e.g. the Tactical Nuke from Void Scrappers) might frequently get reset before firing, if recalculations happen close together.

Can we have both? :)

**Comment by 8bitskull** [comment]
Although, to complicate it further, the basic design of a new function timer.set_delay() presumably restarts the timer entirely which would mean it's not sufficient even with timer.get_info(). If I don't want to be wrapping or cancelling/restarting timers then I would need all of that _plus_ the ability to set the "position" of the timer (kind of like [sprite cursor](https://defold.com/ref/sprite/#cursor)).

So it would be:
timer.get_info() (to get the time elapsed)
timer.set_delay() (to set the new delay)
timer.set_cursor() (bad name, but basically a function to set the time elapsed)

**Comment by britzl** [comment]
> Although, to complicate it further, the basic design of a new function timer.set_delay() presumably restarts the timer entirely

Ah, ok, no I was thinking that the timer would not be reset but keep counting from where it was until the new delay is reached. For a repeating timer it would then use the new delay when it restarts.

**Comment by 8bitskull** [comment]
> Ah, ok, no I was thinking that the timer would not be reset but keep counting from where it was until the new delay is reached. For a repeating timer it would then use the new delay when it restarts.

Please let me know if you want me to raise further issues for timer.set_delay() and/or timer.set_time_remaining()!

I do think there is a use case for the latter function too. For example, in Void Scrappers the default boss spawn cooldown is 45 seconds. If you snagged a 3x boss cooldown upgrade, that would be a 23% decrease in cooldown (about 10 seconds). It would be good to be able to set the new repeating time (i.e. 35 seconds) but also to update the progress of the current iteration (say it was 50% completed at 22.5 seconds remaining, I would set it to 17.5 instead).

Yes, there are workarounds for each of the three functions I am asking for. You can timestamp the last timer call in a table using socket.gettime(), and use that to calculate time remaining. You can always cancel/restart timers and wrap new repeating timers in a one-off timer call. But all of these feel like fighting against what could be in-built functionality.

**Comment by britzl** [comment]
I think we want to try and find a minimal set of changes that gives the most possible freedom. I'm not too keen on having three new methods if we can find a solution which only requires one or two functions. It should also be functions that are easy to reason about and frequently used.

* Having a `timer.get_info()` is generic and the data you get from it can be used to solve several different problems
* Having a `timer.set_delay()` to modify the delay of an active timer without resetting it will solve a specific problem. The question is if this is a common enough problem to warrant its own function?
* Having a `timer.set_time_remaining()` will solve another problem. Is it common enough?

I think both `set_delay` and `set_time_remaining` can be implemented with the data from `timer.get_info()`, but it will be a bit cumbersome...

Another option would be to have a more advanced timer implemented as a native extension...
