### ISSUE TITLE
API documentation and Manual have differing information regarding gameobject transform properties

### ISSUE THREAD

**Issue by Wistpotion** [defold/defold#7003]
**Task:**
Currently the [API documentation](https://defold.com/ref/stable/go/#go.get_rotation:[id]) does not state that setting game object properties via `go.set_position()` and so on is legacy functionality. [The manual](https://defold.com/manuals/properties/) does state that it is legacy functionality. It is unclear if you should use these, or use `go.get()` and `go.set` instead. 

**Expected outcome:**
Clarify the documentation about `go.set_position` and other property setting and getting functions.

**Comment by britzl** [comment]
@Wistpotion you've come across an inconsistency in our documentation. Yes, go.get() and go.set() can be used to manipulate all game object and component properties, but go.get/set_position/rotation/scale will not be deprecated as they are *very* frequently used.

**Comment by Wistpotion** [comment]
Would it be possible to tell that you can use go.set/get as well as use the functions in the API documentation? Because while there is a function for setting the rotation via Quats there are none for Eulers, while there is actually a property for eulers. That's what lead me to be a bit confused to begin with.

**Comment by britzl** [comment]
> Because while there is a function for setting the rotation via Quats there are none for Eulers, while there is actually a property for eulers.

The support for Euler angles are a "hack". Or well, not really, but we do not use Euler internally in the engine, only quaternions. Each frame we calculate the Euler angles from the current rotation as a helper property in the cases when it is more convenient to work with Euler.

> Would it be possible to tell that you can use go.set/get as well as use the functions in the API documentation?

Yes, I will update this manual page you referred to.

**Comment by britzl** [comment]
Updated: https://github.com/defold/doc/commit/f4e37bd55ea3b3e1544e3231568ef304f21c06a6
