### ISSUE TITLE
Failed to connect to debugger

### ISSUE THREAD

**Issue by RevisedJDUDE2** [defold/defold#7013]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2022-09-26T11:31:18.843379</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>e9aea46e5ef75b2f83052942027fcbd5eae5d05e</td></tr>
<tr><td>Defold engine sha</td><td>65e2f79be3b8c99f1999a976399a17eb31a79ff2</td></tr>
<tr><td>Defold version</td><td>1.3.6</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"44b365262dd9411ea7701924fc35eaa9"'>44b365262dd9411ea7701924fc35eaa9</a></td></tr>
<tr><td>GPU</td><td>GDI Generic</td></tr>
<tr><td>GPU Driver</td><td>1.1.0</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
```
editor.debugging.mobdebug$connect_BANG_$fn__43158.invoke.class clojure.lang.ExceptionInfo: Failed to connect to debugger on localhost:8172
    at editor.debugging.mobdebug$connect_BANG_$fn.invoke(mobdebug.clj:339)
    at clojure.lang.AFn.run(AFn.java:22)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.lang.Thread.run(Thread.java:834)
```

**Comment by britzl** [comment]
@RevisedJDUDE2 does this happen all the time or was this a one-off thing? Does it happen both when you start with Debug->Start and when you do Debug->Attach when the game is already running? Are you debugging a game running on your Windows machine or is it a game running on device?

**Comment by AGulev** [comment]
Old issue with `more info` label. Info wasn't provided
