### ISSUE TITLE
Minor inconsistency in API documentation

### ISSUE THREAD

**Issue by Wistpotion** [defold/defold#7015]
**Task:**
Fix a minor inconsistency (that's the best way I can describe it) in the API documentation. Currently in the description for `Lua > Math > Random`:

> This function is an interface to the simple pseudo-random generator function rand provided by ANSI C. (No guarantees can be given for its statistical properties.) When called without arguments, returns a uniform pseudo-random real number in the range **[0,1)**. When called with an integer number m, math.random returns a uniform pseudo-random integer in the range [1, m]. When called with two integer numbers m and n, math.random returns a uniform pseudo-random integer in the range [m, n].

The bold text marks the inconsistency.

**Expected outcome:**
Updating the API docs to remove the inconsistency.

**Comment by britzl** [comment]
I'm not sure I understand which inconsistency you are referring to? The [ vs )? That's the mathematical notation for a closed [ vs an open ) range (https://en.wikipedia.org/wiki/Interval_(mathematics)?oldformat=true).

The documentation is coming from https://www.lua.org/manual/5.1/manual.html#pdf-math.random

Please reopen if I misunderstood what you meant.

**Comment by Wistpotion** [comment]
You're right, I had no idea about there being a difference between using [ and ( to show the value being closed and open, read up about it and now I got it. Thanks!
