### ISSUE TITLE
Profiler step blinking

### ISSUE THREAD

**Issue by d954mas** [defold/defold#7017]
### Expected behaviour
Can see step info every frame.

### Actual behaviour
No step details
Sometimes step info blinking.

### Steps to reproduce
1)toggle profiler by button click
```lua
profiler.enable_ui(self.views.btn_profiler.show_profiler)
```
2)No step details

2.1)If i resize window i see blinking
<hr/>

<table>
<tr><td>Build time</td><td>2022-09-14T09:14:36.712371</td></tr>
<tr><td>Defold channel</td><td>beta</td></tr>
<tr><td>Defold editor sha</td><td>905234d8da2e642f1075c73aaa1bfb72e49199e3</td></tr>
<tr><td>Defold engine sha</td><td>905234d8da2e642f1075c73aaa1bfb72e49199e3</td></tr>
<tr><td>Defold version</td><td>1.3.6</td></tr>
<tr><td>GPU</td><td>AMD Radeon(TM) Graphics</td></tr>
<tr><td>GPU Driver</td><td>4.6.14756 Compatibility Profile Context 20.40.64 27.20.14064.3</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

https://user-images.githubusercontent.com/2655263/192838746-cb0e7451-e7ba-4b1a-ad4b-fdc3c4058bfc.mp4

**Comment by d954mas** [comment]
Forgot update from beta.
Check last release same problem.
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>65e2f79be3b8c99f1999a976399a17eb31a79ff2</td></tr>
<tr><td>Defold engine sha</td><td>65e2f79be3b8c99f1999a976399a17eb31a79ff2</td></tr>
<tr><td>Defold version</td><td>1.3.6</td></tr>

**Comment by britzl** [comment]
Hmm, @AGulev is looking into another profiler issue where we get strange results if we're running with a fixed update. Perhaps that is the case for you as well @d954mas ?

**Comment by AGulev** [comment]
Not fixed update, but "Update frequency" != 0
<img width="878" alt="image" src="https://user-images.githubusercontent.com/2209596/192887734-3d076e49-4069-41fb-a94a-75876a33c237.png">

**Comment by d954mas** [comment]
Yes it is.
Update Frequency 60 have issue
Update Frequency 0 worked as expected

**Comment by AGulev** [comment]
It's a bit tricky issue, it's not even a bug in a sense.
If you set Update Frequency 60 then your game logic do nothing on most of the update calls (because it waits time to limit game update to 60 fps) and this is what you see on the screen most of the time and then when it's time it makes  a call with all the functions which you see as blink on the screen, because this call one of many other "empty" calls.

We think how to improve it
