### ISSUE TITLE
Refactor editor preferences so it's a file managed by us

### ISSUE THREAD

**Issue by vlaaad** [defold/defold#7028]
**Task (REQUIRED):**
Relying on `java.util.prefs.Preferences` is problematic:
- there are limitations on keys and value lengths, this prevents us from storing bigger data structures like a map of the project path to all recent files in that project;
- they are hard to find for our users since they are stored in different places on different OSes.

Therefore, we should make prefs a file in a more easily discoverable location.

**Expected outcome (REQUIRED):**
Prefs are managed by us in a file. Ideally, they are migrated from current storage. Ideally, we should retain the same performance semantics that java prefs give us:
- reads are mostly instant (i.e. don't read from disk in every get)
- writes are mostly instant (i.e. don't write to disk in every set)
- prefs are not corrupted if many editors run in parallel and write/read to file (there are no consistency guarantees in java.util.prefs.Preferences in this scenario).

**Comment by vlaaad** [comment]
We should also consider mentioning prefs file locations in the docs

**Comment by britzl** [comment]
> We should also consider mentioning prefs file locations in the docs

I agree. I can add it. What is the location on macOS, Linux and Windows?

**Comment by vlaaad** [comment]
@britzl, I made this comment as input for a task that isn't done yet :) 

Our current prefs are too confusing — on macOS, this is a file that doesn't even have "defold" in its name and path; on Windows, it's not in a file, but in the registry instead. I thought that we want to move away from using built-in java preferences so it's easier to approach for our users — hence this issue. Once we store user-level prefs in a more reasonable location, then we can document it.

**Comment by britzl** [comment]
> I thought that we want to move away from using built-in java preferences so it's easier to approach for our users — hence this issue. Once we store user-level prefs in a more reasonable location, then we can document it.

Ah, got it. Great. Let's document when we've changed it.

**Comment by AGulev** [comment]
fixed by https://github.com/defold/defold/pull/9613
