### ISSUE TITLE
App crashes when playing sound

### ISSUE THREAD

**Issue by osov** [defold/defold#7050]
**Describe the bug (REQUIRED)**
the android (and windows) application crashes after a few plays of the sound loaded through the resources.

**To Reproduce (REQUIRED)**
press random buttons to play a sound, after a few clicks (10-20+) the application crashes to android.
if you comment out the 7th line in the manager script file (stop the sound), then the application launched in the editor crashes to Windows with a crash too.

**Expected behavior (REQUIRED)**
app won't crash

**Defold version (REQUIRED):**
  - Version 1.3.6

**Platforms (REQUIRED):**
 - Platforms: Android, Windows

**Minimal repro case project (OPTIONAL):**
[SndCrash.zip](https://github.com/defold/defold/files/9751311/SndCrash.zip)

**Logs (OPTIONAL):**
`10-11 10:16:03.904 16564 16586 V threaded_app: New input event: type=2
10-11 10:16:03.921 16564 16588 D defold  : DEBUG:SCRIPT: play   /sounds/15.ogg
10-11 10:16:03.932 16564 16604 W defold  : WARNING:SOUND: Unable to decode file '/sounds/11.oggc'. Result -3
10-11 10:16:03.967 16564 16588 I defold  : INFO:CRASH: Successfully wrote Crashdump to file: /data/user/0/com.example.todo/files/_crash
10-11 10:16:03.967 16564 16588 E defold  : ERROR:CRASH: CALL STACK:
10-11 10:16:03.967 16564 16588 E defold  :
10-11 10:16:03.967 16564 16588 E defold  : # 0 pc     0x236d20 ...iCXXw==/lib/arm64/libSndCrash.so <unknown>+0
10-11 10:16:03.967 16564 16588 E defold  : # 1 pc        0x244 ...android.art/lib64/libsigchain.so _ZN3art11SignalChain7HandlerEiP7siginfoPv+440
10-11 10:16:03.967 16564 16588 E defold  :
10-11 10:16:03.967 16564 16588 E defold  :
10-11 10:16:03.967 16564 16588 F libc    : exiting due to SIG_DFL handler for signal 11, ucontext 0x7505fcfe20
10-11 10:16:03.983 16564 16588 I defold  : INFO:CRASH: Successfully wrote Crashdump to file: /data/user/0/com.example.todo/files/_crash
10-11 10:16:03.983 16564 16588 E defold  : ERROR:CRASH: CALL STACK:
10-11 10:16:03.983 16564 16588 E defold  :
10-11 10:16:03.983 16564 16588 E defold  : # 0 pc     0x236d20 ...iCXXw==/lib/arm64/libSndCrash.so <unknown>+0
10-11 10:16:03.983 16564 16588 E defold  : # 1 pc        0x664 [vdso] <unknown>+0
10-11 10:16:03.983 16564 16588 E defold  : # 2 pc      0x43c44 ...oid.runtime/lib64/bionic/libc.so abort+164
10-11 10:16:03.983 16564 16588 E defold  :
10-11 10:16:03.983 16564 16588 E defold  :
10-11 10:16:04.069  1548  9293 I ActivityManager: Process com.example.todo (pid 16564) has died: fg  TOP`
Crash logs (windows/android)
[crash.zip](https://github.com/defold/defold/files/9751313/crash.zip)

**Comment by britzl** [comment]
Windows crash:

```
 0 0x7FF6207375F0 get_bits D:\\a\\defold\\defold\\engine\\sound\\src\\stb_vorbis\\stb_vorbis.c:1527
 1 0x7FF620740590 vorbis_decode_initial D:\\a\\defold\\defold\\engine\\sound\\src\\stb_vorbis\\stb_vorbis.c:3153
 2 0x7FF62073E7F0 stb_vorbis_get_frame_float D:\\a\\defold\\defold\\engine\\sound\\src\\stb_vorbis\\stb_vorbis.c:4964
 3 0x7FF62073F210 stb_vorbis_get_samples_short_interleaved D:\\a\\defold\\defold\\engine\\sound\\src\\stb_vorbis\\stb_vorbis.c:5251
 4 0x7FF62072A200 dmSoundCodec::StbVorbisDecode D:\\a\\defold\\defold\\engine\\sound\\src\\decoders\\decoder_stb_vorbis.cpp:72
 5 0x7FF620743890 dmSoundCodec::Decode D:\\a\\defold\\defold\\engine\\sound\\src\\sound_codec.cpp:103
 6 0x7FF62072EF10 dmSound::MixInstance D:\\a\\defold\\defold\\engine\\sound\\src\\sound.cpp:1166
 7 0x7FF62072F4A0 dmSound::MixInstances D:\\a\\defold\\defold\\engine\\sound\\src\\sound.cpp:1278
 8 0x7FF6207309A0 dmSound::SoundThread D:\\a\\defold\\defold\\engine\\sound\\src\\sound.cpp:1473
 9 0x7FF874AD7020 BaseThreadInitThunk <unknown>:0
10 0x7FF8757C2630 RtlUserThreadStart <unknown>:0
```

**Comment by AGulev** [comment]
@osov could you pls take a look if you can repo this crash using this version of Defold:
http://d.defold.com/archive/dev/c45daa6a873b373d6e2eb6fcc21bf8097319ad9d/dev/editor2/Defold-x86_64-win32.zip

**Comment by AGulev** [comment]
macOS log:
```

# 0 pc     0x281ad4 dmengine _ZN7dmCrashL7HandlerEiP9__siginfoPv+36
# 1 pc      0x69dfd libc++abi.dylib _sigtramp+29
# 2 pc     0x2be451 dmengine ogg_stream_destroy+33
# 3 pc     0x2c410b dmengine ov_raw_seek+971
# 4 pc     0x2ab3a4 dmengine _ZN12dmSoundCodecL18TremoloResetStreamEPv+20
# 5 pc     0x2a777f dmengine _ZN7dmSound4StopEPNS_13SoundInstanceE+79
# 6 pc      0x5a49f dmengine _ZN12dmGameSystem15CompSoundUpdateERKN12dmGameObject22ComponentsUpdateParamsERNS0_22ComponentsUpdateResultE+127
# 7 pc      0x1cff7 dmengine _ZN12dmGameObject6UpdateEPNS_16CollectionHandleEPKNS_13UpdateContextE+503
# 8 pc       0x7189 dmengine _ZN8dmEngine4StepEPNS_6EngineE+1065
# 9 pc       0x781a dmengine _Z14dmEngineUpdatePN8dmEngine6EngineE+26
#10 pc       0x832d dmengine _ZN8dmEngine7RunLoopEPKNS_13RunLoopParamsE+109
#11 pc       0x8292 dmengine _Z11engine_mainiPPc+98
```
