### ISSUE TITLE
Mesh position ignore scale of go?

### ISSUE THREAD

**Issue by d954mas** [defold/defold#7071]
**Describe the bug (REQUIRED)**
I change mesh component position.
Then i use big scale for go with mesh 0.01. 
Looks like that position of mesh component ignore scale of go.

Blue. Mesh at (0,0,0). Collision box at (-20,150,20)
Red. Mesh at (20,0,-20). Collision box at (0,150,0)

In editor looks ok.
![2022-10-17_19-34-00](https://user-images.githubusercontent.com/2655263/196234085-51eedca8-b8f9-4819-9b2a-a7e8bb8ff6de.png)
In game. Not ok
![2022-10-17_19-34-10](https://user-images.githubusercontent.com/2655263/196234159-efd41188-d612-4439-982a-ec66c5319292.png)

Blue:
![2022-10-17_19-34-41](https://user-images.githubusercontent.com/2655263/196234512-5ec68d6c-2757-481d-93c8-6239d8b57e97.png)

Red:
![2022-10-17_19-34-53](https://user-images.githubusercontent.com/2655263/196234518-ad7ff94e-0b23-452b-8649-42f72a9fcf7a.png)

**To Reproduce (REQUIRED)**
[3dMeshPosition.zip](https://github.com/defold/defold/files/9802798/3dMeshPosition.zip)

**Expected behavior (REQUIRED)**
In game looks like in editor.

**Defold version (REQUIRED):**
  - Version 1.3.6

**Comment by Jhonnyg** [comment]
Yes this seems like an unfortunate old feature/bug/issue related to scaling of z values. Collections have a field called 'scale_along_z' that each game object spawned from that collection inherits. Most components (or all, I don't know exactly) look at this value and uses a normalised z scale if the scale_along_z is 0, which is the default value it seems. So as a workaround for now until we have figured out what to do with this, is to open your collection file in a text editor and set the scale_along_z field to 1 in your collection.

**Comment by d954mas** [comment]
Thanks👍
