### ISSUE TITLE
Instant animation (no smoothness)

### ISSUE THREAD

**Issue by osov** [defold/defold#7086]
**Describe the bug (REQUIRED)**
Animation runs instantly without delay. Before that was a difficult task.
Reproducible in the aggregate timer + animation.
The start time before the animation and in the callback are the same.

**To Reproduce (REQUIRED)**
Start a heavy task and then use a timer (delay) to start the animation.

**Defold version (REQUIRED):**
  - Version 1.3.6

**Platforms (REQUIRED):**
 - Platforms: Windows

 - OS: Windows 10

**Minimal repro case project (OPTIONAL):**
[AnimTest.zip](https://github.com/defold/defold/files/9829907/AnimTest.zip)

**Comment by britzl** [comment]
What do you mean by starting a heavy task? Heavy computations in another program?

**Comment by osov** [comment]
Heavy task in current, example - calculate chechers steps, after do few steps visually

**Comment by britzl** [comment]
Defold is single threaded. If you do a lot of calculations in a single frame no animation code will be running and the animation will advance with a long delta time, possibly even completing it in a single update.

If you have a different scenarios then please share some code so we can get a better understanding of the problem.

**Comment by osov** [comment]
I don't know if you understood me correctly.
First there are heavy calculations, then there are none and I start the timer (small delay) and in it I start the animation.
According to my logic, it should be smooth, because. heavy calculations were up to this site. But it turns out that the animation start time and its execution time (callback) are the same.

**Comment by britzl** [comment]
Oh, ok, that doesn't sound right. And I can test this with the example project you shared? I'll take a look then.

**Comment by britzl** [comment]
Oh, I guess it really depends on how timer.delay() is implemented. If the start time is the frame start time and not the current time then it explains the behaviour in the snippet of code you shared above. I'll check the code.

**Comment by AGulev** [comment]
@britzl I tested it a bit, and it's possible to repo without timer as well (for example in update)

**Comment by britzl** [comment]
> If the start time is the frame start time and not the current time then it explains the behaviour in the snippet of code you shared above. I'll check the code.

Yep, here's how the timer is created:

https://github.com/defold/defold/blob/dev/engine/script/src/script_timer.cpp#L296

As you can see the timer is implemented as a count down with a `timer->m_Remaining` variable tracking how much time is left on the timer. This value is decreased each update:

https://github.com/defold/defold/blob/dev/engine/script/src/script_timer.cpp#L215

What this means is that if you in frame #1 first do calculations taking 0.5 seconds, then start a timer with a delay of 0.5, then frame #2 will have a delta time of ~0.5 (the time of frame #1), which means that when the timer is updated the `timer->m_Remaining` will be decreased by 0.5 and immediately triggered.

I doubt that this is something we will try to fix.

**Comment by britzl** [comment]
> I doubt that this is something we will try to fix.

The solution in this scenario would be to start the timer on the next frame. OR not do heavy calculations over a single frame as it will not only cause problems with timers but also with go.animate() and possibly also with sound playback.

**Comment by osov** [comment]
Okay, got it, thanks.

**Comment by britzl** [comment]
Yet another solution/workaround is to measure the time it takes to perform the calculations and add that to the timer delay.
