### ISSUE TITLE
Images used in multiple animations within an atlas get duplicated

### ISSUE THREAD

**Issue by K-Klear** [defold/defold#7096]
**Describe the bug (REQUIRED)**
Using the same image in multiple animations creates a copy within the atlas instead of reusing it for all animations.

**To Reproduce (REQUIRED)**
1. Create an atlas
2. Add any image
3. Create a new animation
4. Add the same image to the animation

**Expected behavior (REQUIRED)**
One sprite should be used for both.

**Defold version (REQUIRED):**
  - Version 1.3.7

**Platforms (REQUIRED):**
 - Windows 10

**Screenshots (OPTIONAL):**
https://i.imgur.com/j7QJpsR.png

**Comment by K-Klear** [comment]
Tested it on versions 1.3.0, 1.3.6 and 1.3.7 - the bug showed on the two most recent ones but not in 1.3.0.

Worth noting that since it's impossible to add the same image to the top level, it only happens when adding it in an animation. In fact, the easiest way to reproduce this (and how I ran into it) is to make a copy of an existing animation.

**Comment by britzl** [comment]
The bug is not present in Defold 1.3.4 but present in 1.3.5
