### ISSUE TITLE
Editor - sampler / model Bug

### ISSUE THREAD

**Issue by FlexYourBrain** [defold/defold#7099]
**Describe the bug**

When adding more samplers to a material and assigning textures to them in model properties, then if the sampler(s) are removed in the material the data still exists in the model even though the properties do not show it in the editor. If the texture url is removed from the model properties then removing the sampler from the material then creating a bundle an error occurs ("you must specify a texture "). Note : building from the editor does not give this error. 

The problem is assigning textures to model depends on the current assigned material samplers, and if those are removed the assigned texture slots still exists in the model file.

**Expected behavior**

If model texture slots depend on material properties then changing material sampler properties should also clean model data when samplers are removed. Or a cleaner way to handle assigning textures in model properties

**Defold version : 1.3.7**

**Platforms (REQUIRED):**
win10

**Minimal repro case project (OPTIONAL):**

[Samplerbug.zip](https://github.com/defold/defold/files/9874114/Samplerbug.zip)
 If a build is created an error occurs. To fix add a sampler to test.material and assign an image to texture slot in m.model.

**Workaround:**

Remove the sampler slot and open .model file in an editor and remove the texture slot manually.

**Comment by AGulev** [comment]
Should be fixed by https://github.com/defold/defold/pull/8186#issuecomment-1848910164
