### ISSUE TITLE
Mesh diff transform in editor and in game.

### ISSUE THREAD

**Issue by d954mas** [defold/defold#7126]
### Expected behaviour
Mesh look same in editor and game
### Actual behaviour
Mesh not rotated in game
Error in console.
```
 Trying to get stream data outside of input DDF array.
 ```
![2022-11-04_14-18-02](https://user-images.githubusercontent.com/2655263/199960912-20a1eb06-667a-448a-9688-b5e7a23b179f.png)
![2022-11-04_14-18-51](https://user-images.githubusercontent.com/2655263/199960917-b9d190dd-45a7-4e32-bfb8-77afdc98e364.png)

### Steps to reproduce
[bad mesh.zip](https://github.com/defold/defold/files/9937722/bad.mesh.zip)

<hr/>

<table>
<tr><td>Build time</td><td>2022-11-02T11:44:12.649507</td></tr>
<tr><td>Defold channel</td><td>beta</td></tr>
<tr><td>Defold editor sha</td><td>1dbf756283bc3aaa74552b8959569f051023b842</td></tr>
<tr><td>Defold engine sha</td><td>1dbf756283bc3aaa74552b8959569f051023b842</td></tr>
<tr><td>Defold version</td><td>1.4.0</td></tr>
<tr><td>GPU</td><td>AMD Radeon(TM) Graphics</td></tr>
<tr><td>GPU Driver</td><td>4.6.14756 Compatibility Profile Context 20.40.64 27.20.14064.3</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by d954mas** [comment]
Problem when go have rotation.y 180
with rotation.y 179.9 mesh render correct in game

**Comment by Jhonnyg** [comment]
This seems to have been fixed with 1.4.1, could you try with an alpha or beta build from https://d.defold.com/alpha/ or https://d.defold.com/beta/ ?

**Comment by d954mas** [comment]
Update repro case. Looks like camera position was wrong:(
[bad.mesh_2.zip](https://github.com/defold/defold/files/10124995/bad.mesh_2.zip)

<hr/>

<table>
<tr><td>Build time</td><td>2022-11-28T14:37:20.255562</td></tr>
<tr><td>Defold channel</td><td>beta</td></tr>
<tr><td>Defold editor sha</td><td>ba61b10664fb9b96dfae367ba088960601bd8560</td></tr>
<tr><td>Defold engine sha</td><td>ba61b10664fb9b96dfae367ba088960601bd8560</td></tr>
<tr><td>Defold version</td><td>1.4.1</td></tr>
<tr><td>GPU</td><td>AMD Radeon(TM) Graphics</td></tr>
<tr><td>GPU Driver</td><td>4.6.14756 Compatibility Profile Context 20.40.64 27.20.14064.3</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>

<table>

![2022-11-30_19-07-51](https://user-images.githubusercontent.com/2655263/204849308-56720ab5-c912-4cc2-8e2e-c840de1b0b5d.png)

![2022-11-30_19-08-24](https://user-images.githubusercontent.com/2655263/204849299-73940ece-0bd8-4ac2-8858-c46f0c431d7c.png)

**Comment by d954mas** [comment]
Warning in console was not problem.(Fixed it(remove empty second uv from mesh))
```
 Trying to get stream data outside of input DDF array.
```

**Comment by d954mas** [comment]
Last repro case. No warning is console.
Mesh look good in enditor.
Mesh look bad in game:(
[bad.mesh.zip](https://github.com/defold/defold/files/10125048/bad.mesh.zip)

**Comment by Jhonnyg** [comment]
I'm investigating it, and as a workaround it seems that if you rotate it to zero and then rotate it again to 180 on the y axis the problem magically disappears, so until I can find out more you can try that.

**Comment by d954mas** [comment]
Ok, thanks. 
I make that meshes in blender.
https://forum.defold.com/t/building-a-sync-tool-for-blender-to-defold/69920

So rotation is set in file by export plugin, not by editor.

Mb it set some bad value?
And when you rotate object 180 and back editor fixed that value?

**Comment by Jhonnyg** [comment]
I'm not sure to be honest, I think it's something in the editor build pipeline because running bob.jar seems to be working fine. I'll run it by the editor guys and see if they have any ideas.

**Comment by d954mas** [comment]
Test in another project(real game)
1)Mesh was not correcr
2)rotate y to 0. Then rotate y to 180. Mesh correct

Initial value
```
 rotation {
        x:-3.0908623216419e-008
	y:0.70710682868958
	z:0.70710670948029
	w:-3.0908616110992e-008
    }
```
Rotate to y to 0.
Rotate y from 0 to 180.
```
 rotation {
    x: -4.3297803E-17
    y: 0.70710677
    z: 0.70710677
    w: 4.3297803E-17
  }
  ```

**Comment by d954mas** [comment]
UP.
Very annoying in my cases.

-Looks ok in editor
-All ok when bundle.
-Problems when build from editor.

**Comment by d954mas** [comment]
I change rotation from 180 to 0. Then back, from 0 to 180.
It fixed build from editor.
-git not see any  changes in file.
-after editor restart i need to fixed it again

**Comment by d954mas** [comment]
Not sure about changes i write here https://github.com/defold/defold/issues/7126#issuecomment-1333519775

For now i do not see any changes in git.

Editor 1.4.3 (f7eb9172d5e128c2d84a2d6f0890c757d00f08c7)

**Comment by matgis** [comment]
A fix has been merged and your editor should receive an update shortly. Thanks for reporting! ❤️
