### ISSUE TITLE
GUI template editor customization, additional helpers

### ISSUE THREAD

**Issue by Insality** [defold/defold#7127]
**Is your feature request related to a problem? Please describe (REQUIRED):**
We share a lot of GUI components with a team also provided with GUI templates to it. There is an idea to adjust template settings in somehow to add additional notes to template in editor and also forbid/hide GUI several node fields to restrict editing

For example, If we have "Token", I want to nobody, who use it, no able to edit any settings exclude "position", "scale" and several other.
I wanna forbid to editing "size mode", "size" and other unrelated properties to this template in all nodes it included (every node can have their forbid property list)

It probably sounds weird, but I think it can help us have more structured and easy to use GUI templates with less bug issues. What do you think?

It is only editor feature

**Describe the solution you'd like (REQUIRED):**
Not sure about concrete solution, but it will be good even if we able to edit in manually in *.gui file. For example add fields:
- note: "text" for additional info for template/node
- forbid_edit: property_name to remove it from editing in template included place

If property is already overrided - it should be shown with "revert" icon and able to edit

**Describe alternatives you've considered (REQUIRED):**
Keep it as is :)

**Comment by vlaaad** [comment]
### Some more context that describes the underlying issue:
GUI file `icon.gui` might define an auto-sized mode icon of 32x32 size. Another GUI file — e.g. `window.gui` — might use this icon and then increase its size by 2 by switching from auto size to manual size and changing the size to 64x64. Sometime later, an artist changes `icon.gui` icon to another one, e.g. with shadow and a new size: 32x40. Now `window.gui` will show a distorted icon instead of an upscaled one, because the aspect ratio has changed.

**Comment by vlaaad** [comment]
### Alternative solution idea
When the original GUI file is open, in the Properties view, if a property has overrides, we can show a link that will navigate the user to the overriding GUI files. This way, when changing the original GUI file, we can use our judgment to see what overriding GUIs might need updating and easily navigate to them.

Here is a quick mockup of an icon with a popup that shows references to template usages that override the property:
<img width="986" alt="Screenshot 2023-04-06 at 10 59 55" src="https://user-images.githubusercontent.com/732554/230329242-e6e97bbe-8e4e-41e3-9719-8b72aad3c296.png">

**Comment by vlaaad** [comment]
### Another idea

We can create a Defold language server for protobuf types that allows defining rules that various resources need to satisfy. When this language server is used in the editor, it will produce build errors on build.

### Yet another idea

Implement a collaboration tool that allows annotating and discussing files, preferably as an extension.
