### ISSUE TITLE
Many crash logs after migration from 1.2.192

### ISSUE THREAD

**Issue by SalavatR** [defold/defold#7131]
**Describe the bug (REQUIRED)**
Hi! we got many errors in sentry, on html5, suddenly no repro steps, only logs

**Defold version (REQUIRED):**
  - Version 1.3.7

**Platforms (REQUIRED):**
 - Platforms: HTML5
 - OS: all

We move to 1.3.7 from 1.2.192, and changed sentry client to sentiel, also log previous crash with 
        local _, extra_data = pcall(crash.get_extra_data, crash_handle)

**Logs (OPTIONAL):**
1. 
["RuntimeError: abort(Assertion failed: vertex_buffer, at: ../src/opengl/graphics_opengl.cpp,1649,OpenGLEnableVertexDeclarationProgram). Build with -s ASSERTIONS=1 for more info.","abort@<anonymous>:1:12355","___assert_fail@<anonymous>:1:19374","@wasm://wasm/0082dc3e:wasm-function[4190]:0x14d811","@wasm://wasm/0082dc3e:wasm-function[3718]:0x12d518","@wasm://wasm/0082dc3e:wasm-function[1230]:0x41618","@wasm://wasm/0082dc3e:wasm-function[3703]:0x129082","@wasm://wasm/0082dc3e:wasm-function[3643]:0x124282","@wasm://wasm/0082dc3e:wasm-function[4821]:0x180a6d","@wasm://wasm/0082dc3e:wasm-function[4815]:0x180491","@wasm://wasm/0082dc3e:wasm-function[4824]:0x18107f"]

2.
["RuntimeError: abort(Assertion failed: g_Context, at: ../src/opengl/graphics_opengl.cpp,550,OnWindowFocus). Build with -s ASSERTIONS=1 for more info.","abort@<anonymous>:1:12355","___assert_fail@<anonymous>:1:19374","@wasm://wasm/0082dc3e:wasm-function[4214]:0x14e5d1","onFocusChanged@<anonymous>:1:224063","HTMLCanvasElement.onBlur@<anonymous>:1:224149"]

3.
["TypeError: Cannot set properties of null (setting 'name')","_glCreateProgram@<anonymous>:1:204575","@wasm://wasm/0082dc3e:wasm-function[4149]:0x14cb85","@wasm://wasm/0082dc3e:wasm-function[1504]:0x5d4a3","@wasm://wasm/0082dc3e:wasm-function[4355]:0x1558f4","@wasm://wasm/0082dc3e:wasm-function[1957]:0x92e82","@wasm://wasm/0082dc3e:wasm-function[1222]:0x40359","@wasm://wasm/0082dc3e:wasm-function[1950]:0x92106","@wasm://wasm/0082dc3e:wasm-function[1950]:0x9207b","@wasm://wasm/0082dc3e:wasm-function[1950]:0x9207b","@wasm://wasm/0082dc3e:wasm-function[1950]:0x9207b"]

4.
["TypeError: Cannot set properties of null (setting 'name')","_glCreateProgram@<anonymous>:1:202895","@wasm://wasm/007b6fb6:wasm-function[3901]:0x13b87d","@wasm://wasm/007b6fb6:wasm-function[1428]:0x58b6b","@wasm://wasm/007b6fb6:wasm-function[4102]:0x1448fd","@wasm://wasm/007b6fb6:wasm-function[1842]:0x8d9ca","@wasm://wasm/007b6fb6:wasm-function[1162]:0x3da2e","@wasm://wasm/007b6fb6:wasm-function[1835]:0x8cc30","@wasm://wasm/007b6fb6:wasm-function[1835]:0x8cbaa","@wasm://wasm/007b6fb6:wasm-function[1835]:0x8cbaa","@wasm://wasm/007b6fb6:wasm-function[1835]:0x8cbaa"]

**Comment by britzl** [comment]
And you get no crashes with a desktop build? Only HTML5?

Are you using any extensions?

**Comment by SalavatR** [comment]
> And you get no crashes with a desktop build? Only HTML5?
> 
> Are you using any extensions?

Only HTML5

[project]
dependencies#0 = https://github.com/Insality/druid/archive/refs/tags/0.10.1.zip
dependencies#1 = https://github.com/Melsoft-Games/defold-cjson/archive/2e401c9.zip
dependencies#2 = https://github.com/britzl/monarch/archive/refs/tags/3.4.6.zip
dependencies#3 = https://github.com/britzl/ludobits/archive/refs/tags/7.1.0.zip
dependencies#4 = https://github.com/britzl/defold-input/archive/2.8.5.zip
dependencies#5 = https://github.com/britzl/defold-metrics/archive/1.2.1.zip
dependencies#6 = https://github.com/britzl/defold-richtext/archive/refs/tags/5.17.0.zip
dependencies#7 = https://github.com/britzl/defold-orthographic/archive/refs/tags/3.2.0.zip
dependencies#8 = https://github.com/AGulev/jstodef/archive/1.4.0.zip
dependencies#9 = https://github.com/Melsoft-Games/defold-protobuf/archive/0e5d3b2.zip
dependencies#10 = https://github.com/HGPoint/def_native_logger/archive/refs/tags/1.0.0.zip
dependencies#11 = https://github.com/defold/extension-spine/archive/refs/tags/2.4.0.zip
dependencies#12 = https://github.com/indiesoftby/defold-sentinel/archive/refs/tags/1.0.0.zip

**Comment by britzl** [comment]
Are you able to reproduce this issue your self?

` ../src/opengl/graphics_opengl.cpp,550,OnWindowFocus`

Perhaps when switching tab or minimizing the browser?

**Comment by SalavatR** [comment]
unfortunately we cant reproduce this issue

**Comment by britzl** [comment]
Anything in common on the clients where these crashes are registered? Like browser, os, gpu, WebGL version or WbeGL extensions?

**Comment by SalavatR** [comment]
according to the sentry, all kind of devices and os

**Comment by SalavatR** [comment]
I think part of this logs is that problem, after we solved it we got new list on html5 platform, but very few users:

1. In android webview, android <= 9, html5 build:
ERROR:CRASH: ["TypeError: Cannot read properties of undefined (reading 'entries')","@<anonymous>:1:40087","forEach@<anonymous>","reconcile@<anonymous>:1:40031","@<anonymous>:1:36325","IDBTransaction.transaction.onerror@<anonymous>:1:37908"]


2. On any os, html5 build
["RuntimeError: abort(Assertion failed: vertex_buffer, at: ../src/opengl/graphics_opengl.cpp,1649,OpenGLEnableVertexDeclarationProgram). Build with -s ASSERTIONS=1 for more info.","abort@<anonymous>:1:12355","___assert_fail@<anonymous>:1:19381","@wasm-function[4196]:396","@wasm-function[3721]:1129","@wasm-function[1230]:2637","@wasm-function[3706]:652","@wasm-function[3646]:105","@wasm-function[4827]:1034","@wasm-function[4821]:13","@wasm-function[4830]:267"]

3.  On any os, html5 build
ERROR:SCRIPT: Failed to rename '._httptmp' to ''

4. Many users, Android build, sys_info.system_version = 9
# 0 pc      0x19be4 /system/lib/libc.so <unknown>+0
# 1 pc      0x1cf62 /system/lib/libc.so abort+53
# 2 pc      0x754a3 /system/lib/libc.so _ZL15__fortify_fatalPKcz+26
# 3 pc      0x74c31 /system/lib/libc.so _ZL25HandleUsingDestroyedMutexP15pthread_mutex_tPKc+20
# 4 pc      0x74b4b /system/lib/libc.so pthread_mutex_lock+218
# 5 pc     0x210030 ...g==/split_config.armeabi_v7a.apk <unknown>+0
# 6 pc      0xb6668 ...g==/split_config.armeabi_v7a.apk <unknown>+0
# 7 pc      0xb5ee8 ...g==/split_config.armeabi_v7a.apk <unknown>+0
# 8 pc         0x8d ...1NxFyo4W5CZg==/oat/arm/base.odex <unknown>+0

**Comment by britzl** [comment]
1. Ok, so this is a crash in a webview. Are you showing ads?
2. Not entirely sure what the problem is here. How widespread is this issue?
3. Are you using Live Update?
4. Do you have debug symbols so that we can symbolicate this error? It doesn't say much in its current state?

**Comment by SalavatR** [comment]
I think i'll try update logger, and update next release  to new defold version and collect new statistics
Thanks for your help!

**Comment by britzl** [comment]
> I think i'll try update logger, and update next release to new defold version and collect new statistics

Ok, thanks!
