### ISSUE TITLE
Game crash when create game objects with particles

### ISSUE THREAD

**Issue by ufgo** [defold/defold#7142]
**Describe the bug (REQUIRED)**
When i spawn 5 or more bombs game is crashing

**To Reproduce (REQUIRED)**
Run project from repo, spawn bombs with space key, move - WASD

**Defold version (REQUIRED):**
  - Version 1.4.0
  
**Platforms (REQUIRED):**
 - Platforms: Windows, HTML5

**Minimal repro case project (OPTIONAL):**
[acces only for Defold developers](https://github.com/ufgo/bomber-3D)

```
`ERROR:CRASH: CALL STACK:

ERROR:CRASH:  0 0x7FF6B7866BC0 dmCrash::GenerateCallstack D:\a\defold\defold\engine\crash\src\backtrace_win32.cpp:144

ERROR:CRASH:  1 0x7FF6B793F108 _seh_filter_exe minkernel\crts\ucrt\src\appcrt\misc\exception_filter.cpp:219

ERROR:CRASH:  2 0x7FF6B7982B84 `__scrt_common_main_seh'::`1'::filt$0 d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:304

ERROR:CRASH:  3 0x7FF6B78D3754 __C_specific_handler d:\agent\_work\4\s\src\vctools\crt\vcruntime\src\eh\riscchandler.cpp:290

ERROR:CRASH:  4 0x7FF84BD52300 __chkstk <unknown>:0

ERROR:CRASH:  5 0x7FF84BD01070 RtlRaiseException <unknown>:0

ERROR:CRASH:  6 0x7FF84BD50F20 KiUserExceptionDispatcher <unknown>:0

ERROR:CRASH:  7 0x7FF6B76C82E0 lua_gettop <unknown>:0

ERROR:CRASH: 

INFO:CRASH: Successfully wrote Crashdump to file: C:\Users\admin\AppData\Roaming\Defold/_crash
ERROR:CRASH: CALL STACK:

ERROR:CRASH:  0 0x7FF6B76C82E0 lua_gettop <unknown>:0

ERROR:CRASH:  1 0x7FF6B7697960 dmScript::LuaStackCheck::LuaStackCheck D:\a\defold\defold\engine\script\src\script.cpp:1464

ERROR:CRASH:  2 0x7FF6B756A250 dmGameSystem::EmitterStateChangedCallback D:\a\defold\defold\engine\gamesys\src\gamesys\scripts\script_particlefx.cpp:94

ERROR:CRASH:  3 0x7FF6B77755E0 dmParticle::UpdateEmitterState D:\a\defold\defold\engine\particle\src\particle.cpp:834

ERROR:CRASH:  4 0x7FF6B7775100 dmParticle::UpdateEmitter D:\a\defold\defold\engine\particle\src\particle.cpp:610

ERROR:CRASH:  5 0x7FF6B7774A80 dmParticle::Update D:\a\defold\defold\engine\particle\src\particle.cpp:710

ERROR:CRASH:  6 0x7FF6B7567430 dmGameSystem::CompParticleFXUpdate D:\a\defold\defold\engine\gamesys\src\gamesys\components\comp_particlefx.cpp:227

ERROR:CRASH:  7 0x7FF6B7517640 dmGameObject::Update D:\a\defold\defold\engine\gameobject\src\gameobject\gameobject.cpp:2530

ERROR:CRASH:  8 0x7FF6B7560560 dmGameSystem::CompCollectionProxyUpdate D:\a\defold\defold\engine\gamesys\src\gamesys\components\comp_collection_proxy.cpp:299

ERROR:CRASH:  9 0x7FF6B7517640 dmGameObject::Update D:\a\defold\defold\engine\gameobject\src\gameobject\gameobject.cpp:2530

ERROR:CRASH: 10 0x7FF6B74F47E0 dmEngine::StepFrame D:\a\defold\defold\engine\engine\src\engine.cpp:1571

ERROR:CRASH: 11 0x7FF6B74F5480 dmEngineUpdate D:\a\defold\defold\engine\engine\src\engine.cpp:2099

ERROR:CRASH: 12 0x7FF6B74F56C0 dmEngine::RunLoop D:\a\defold\defold\engine\engine\src\engine_loop.cpp:83

ERROR:CRASH: 13 0x7FF6B74EDD80 engine_main D:\a\defold\defold\engine\engine\src\engine_main.cpp:148

ERROR:CRASH: 14 0x7FF6B78CE974 __scrt_common_main_seh d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288

ERROR:CRASH: 15 0x7FF84AF874A0 BaseThreadInitThunk <unknown>:0

ERROR:CRASH: 16 0x7FF84BD02680 RtlUserThreadStart <unknown>:0
`
```

**Comment by britzl** [comment]
A workaround for now is to delete the explosion particle effect when it has transitioned to the EMITTER_STATE_SLEEPING state. Right now you are deleting the particle effect as soon as you get the first emitter state change.

```
	particlefx.play("#explosion_line", function(self, id, emitter, state)
		if state == particlefx.EMITTER_STATE_SLEEPING then
			go.delete(".", true)
		end
	end)
```

**Comment by britzl** [comment]
> It would be good with a repro case :)

I did have a minimal repro, but for some reason I didn't attach it to the issue, and now when I'm trying to recreate the issue from memory I can't. @ufgo are you able to still provide us with a repro case?

**Comment by ufgo** [comment]
@britzl @JCash i added you to [repro case
](https://github.com/ufgo/bomber_particle_bug)

**Comment by britzl** [comment]
Thanks. I've stripped it down to the bare minimum. It's basically just some spawning game objects with particle effects that get deleted on a timer. Sometimes it crashes. Sometimes it freezes.

[repro.zip](https://github.com/defold/defold/files/11711997/repro.zip)

**Comment by Jhonnyg** [comment]
I've done some more investigations, but still no solid resolution except that the actual crash has been fixed.

The problem is very much related to deleting the GO that owns the script that plays the particle fx, what seems to be happening is that the function that prepares the lua state for the callback (dmScript::SetupCallback) when a state change is happening for the PXF, gets an incorrect lua state from the parameters of the callback function and destroys the callback object. This chain of events seems with the broken or incorrect lua state seems to happen after a fair amount of emitters has been played and destroyed inside the callback, which I would assume has something to do with garbage collection.

For now I would advise to go with the solution @britzl suggested, I don't know exactly what the correct behaviour should be - does it make sense to do the callback on an emitter that has been removed? 🤔

**Comment by britzl** [comment]
> no solid resolution except that the actual crash has been fixed.

That is good enough!

> does it make sense to do the callback on an emitter that has been removed?

One can definitely argue that if you care about the callback then don't delete the script!

**Comment by Jhonnyg** [comment]
Yeah hm it's a bit weird so maybe it's not something we should support tbh :)
