### ISSUE TITLE
Archive Location Prefix does not work as expected

### ISSUE THREAD

**Issue by SalavatR** [defold/defold#7147]
**Describe the bug (REQUIRED)**
By default archive_location_prefix= archive, as folder in html5 build, but when I set it custom, folder stays with name "archive"

**To Reproduce (REQUIRED)**
set archive_location_prefix to any new value, and build with bob

**Expected behavior (REQUIRED)**
folder with build files *.arcd and others have same name as archive_location_prefix

**Defold version (REQUIRED):**
  - Version 1.3.7

**Platforms (REQUIRED):**
 - Platform: HTML5

**Comment by britzl** [comment]
It is true that the archive folder will always be named "archive". The idea behind the archive location prefix and suffix is to help developers with custom web server deployments. Example:

Let's say that you need to deploy index.html and js files to one location (.) and the archive files to some other location (../file_store) on your server then you'd set your archive location prefix to `../file_store/archive`. You could perhaps also include a version number in the archive location prefix to support multiple versions, eg `../file_store/v1.0.2/archive`.

Does this make sense? Is there a use-case which we haven't considered?

**Comment by britzl** [comment]
Closing.
