### ISSUE TITLE
Don't run pre-build hook when attach debugger or hot-reload resource

### ISSUE THREAD

**Issue by AGulev** [defold/defold#7149]
**Describe the bug (REQUIRED)**
At the moment the editor runs pre-build hook when attach debugger or hot-reload a resource

**To Reproduce (REQUIRED)**
1. add simple pre-build hook to any project with print()
2.build and run project
3. Attach bebugger or change any file and hot-reload it (cmd+R)
4. pay attention that the hook runs

**Expected behavior (REQUIRED)**
pre-build hook should run only when build the project

**Defold version (REQUIRED):**
  - Version 1.4.0

**Comment by britzl** [comment]
Closed via #7252
