### ISSUE TITLE
Allow collision objects to send collision messages to another object or script component

### ISSUE THREAD

**Issue by 8bitskull** [defold/defold#7151]
A fairly standard performant way of handling multiple objects with similar behaviours is through the use of a single "manager" script. This allows the objects to be controlled centrally, and means they do not need to have individual script components. This leads to a performance gain.

If these objects require a collision object, however, the resulting messages are always directed at the parent game object. This means that each individual object would need, at minimum, a script component with an on_message() function to handle collisions.

I would like to request a feature where a collision object could be set to divert its messages to a named object or script component.

**Comment by Dragosha** [comment]
very agree. Often bullets, objects, etc. need their own script just to get a collision message. It would be great to forward this message to the object manager.

**Comment by britzl** [comment]
I 100% agree on this request too! I'm thinking how it should work. There was a suggestion to set a listener function somehow. Some alternatives:

**physics.set_listener(fn)**
Set a function to call on all physics collisions. I suppose this is per physics world (ie loaded collection proxy or bootstrap collection)

**physics.set_listener(url)**
Same as above but sends messages to the url instead.

**msg.post(url, "set_physics_listener")**
Post to a collection proxy to get all physics collision messages sent to the script sending this message

**"Bubbling physics messages"**
Physics collision messages somehow "bubble" up a child-parent hierarchy. Some alternatives:

Option 1) Game project option.
Option 2) Option on the collision object itself.
Option 3) Only send the collision message to the same game object AND if the object was created by a factory also to the game object with the factory (the creator)

**Comment by JCash** [comment]
I'd vote on option 1, also for consistency witgh our other api's.
