### ISSUE TITLE
game crashes, error in console

### ISSUE THREAD

**Issue by tigerteeth** [defold/defold#7159]
**Describe the bug (REQUIRED)**
Defold game crashes with this console message: 
Assertion failed: (i < Size()), function operator[], file array.h, line 478.
INFO:CRASH: Successfully wrote Crashdump to file: /Users/josh/Library/Application Support/Defold/_crash
ERROR:CRASH: CALL STACK:

**To Reproduce (REQUIRED)**
running this code for a second time gets the error: 

```
local function renderlevel(self) -- this creates all the tiles, dudes, trees, star, and spaces. 
	print(57)
	pprint(self.dudepos)
	pprint(self.dudegos)
	pprint(self.dudestarts)
	self.handle = factory.create("#handle", vmath.vector3(0,0,0))
	go.set_parent(self.handle, ".")
	self.wait = 0
	self.dudepos= {}
	self.dudegos= {}
	self.dudestarts= {}
	self.gridsize = (math.sqrt(#self.level))
	print(68)
	pprint(self.dudepos)
	pprint(self.dudegos)
	pprint(self.dudestarts)
	for k, v in ipairs(self.level) do
		local x = ((k-1)%self.gridsize)
		local y = self.gridsize-(((k-x)/self.gridsize)+1)
		local z = 0
		local pos = vmath.vector3((x*self.tilesize)-(self.tilesize*self.gridsize)/2,(y*self.tilesize)-(self.tilesize*self.gridsize)/2,z)
		if v > 0 then --render tile
			local ids = collectionfactory.create("#tile", pos)
			local map_id = ids[hash("/go")]
			go.set_parent(map_id,self.handle)
			udlr(self,k,map_id)
			if v == 2 then
				pos.z = 0.2
				local ids = collectionfactory.create("#dude", pos)
				local map_id = ids[hash("/go")]
				go.set_parent(map_id, self.handle)
				table.insert(self.dudepos, k)
				table.insert(self.dudegos, map_id)
				table.insert(self.dudestarts, k)
			elseif v == 3 then
				local ids = collectionfactory.create("#tree", pos)
				local map_id = ids[hash("/go")]
				go.set_parent(map_id, self.handle)
			elseif v == 4 then
				local ids = collectionfactory.create("#star", pos)
				local map_id = ids[hash("/go")]
				go.set_parent(map_id, self.handle)
			end
		end 
	end
	print(101)
	pprint(self.dudepos)
	pprint(self.dudegos)
	pprint(self.dudestarts)
end
```

**Expected behavior (REQUIRED)**
collection factory should not cause crash. 

**Defold version (REQUIRED):**
1.3.1

**Platforms (REQUIRED):**
mac OS

**Comment by tigerteeth** [comment]
<img width="979" alt="Screenshot 2022-11-19 at 16 17 25" src="https://user-images.githubusercontent.com/16636952/202857880-870ad63e-2dae-474a-b89e-e4cea31219be.png">

**Comment by britzl** [comment]
> INFO:CRASH: Successfully wrote Crashdump to file: /Users/josh/Library/Application Support/Defold/_crash

Could you please attach this as a file?

**Comment by tigerteeth** [comment]
Hi, Please find attached a .zip file with the game project and the bug report. The bug should be easy to reproduce: build, press play, collect the star, click next level, crash. 

The bug is in the levelrender function in the levelrender script, but it only crashes the second time that function runs. I tried to simplify as much as possible to help with debugging, but the bug appeared to fix itself for some unknown reason, so the project I'm sending is the one where the bug is easy to reproduce. 

[BVaug2021 - bugged.zip](https://github.com/defold/defold/files/10092637/BVaug2021.-.bugged.zip)

[crash.txt](https://github.com/defold/defold/files/10092678/crash.txt)

**Comment by britzl** [comment]
Hmm, I'm not able to get it to crash using the sample project... Is the crash file generated from a release build? If so, could you please try with a debug build and share the _crash file?

**Comment by AGulev** [comment]
1.3.1 is a pretty old version, could you try to repo it using the latest version pls

**Comment by tigerteeth** [comment]
You're right, I didn't realise I was on the old version. I cannot reproduce this bug any more.
