### ISSUE TITLE
Crash on opening project with broken GUI template

### ISSUE THREAD

**Issue by akashpur-ms** [defold/defold#7174]
**Describe the bug (REQUIRED)**

**To Reproduce (REQUIRED)**
1. create empty project
2. add 2 gui files: main.gui and part.gui
3. add part.gui as template into main.gui
4. close defold, open main.gui in text editor, edit line `template: "/main/part.gui"` to be `template: "/main/part1.gui"`
5. save changes, attempt to open project with defold, it will crash on start

**Expected behavior (REQUIRED)**
Defold starts, somehow indicating that there is issue in gui file (for example like when gui node has wrong texture)

**Defold version (REQUIRED):**
  - Version 1.3.7

**Platforms (REQUIRED):**
 Windows 10

**Comment by akashpur-ms** [comment]
[repro_case.zip](https://github.com/defold/defold/files/10093227/repro_case.zip)

**Comment by vlaaad** [comment]
Fixed in #7765
