### ISSUE TITLE
Label.set_text throw error when pass url as first argument

### ISSUE THREAD

**Issue by ekharkunov-ms** [defold/defold#7185]
**Describe the bug (REQUIRED)**
If use url as first argument for label.set_text engine throws an error
```
Failed to send label string as message!
```
According to documentation (https://defold.com/ref/stable/label/#label.set_text:url-text) it allows to use url as first argument.
Example script
```
	local url = msg.url(".", "go", "label")
	label.set_text(url, "1 text")
	label.set_text(msg.url(".", "go", "label"), "2 text")
```

**To Reproduce (REQUIRED)**
1. Open example project
2. Run the project

**Expected behavior (REQUIRED)**
No error is occurred.

**Defold version (REQUIRED):**
  - Version: 1.4.0

**Platforms (REQUIRED):**
 - Platforms: macOS

**Minimal repro case project (OPTIONAL):**
[label_error.zip](https://github.com/defold/defold/files/10099208/label_error.zip)

**Workaround (OPTIONAL):**
Use string as first argument.

**Comment by britzl** [comment]
> msg.url(".", "go", "label")

This URL is not correct. It should be "socket", "path", "component" like this: https://defold.com/manuals/addressing/#urls

You can use `nil` as socket to use the same socket (ie collection) as the script belongs to.

**Comment by ekharkunov-ms** [comment]
Ahhh... Sorry, my fault. Thanks @britzl
