### ISSUE TITLE
Create "release profiler" NE, which allows getting count values in release bundle

### ISSUE THREAD

**Issue by AGulev** [defold/defold#7188]
Create a native extension that collects profiler counters and provides an interface in  Lua to get values from such counters. This extension should work in Release bundle.

**Comment by TursMA** [comment]
Please, consider to add gui nodes counter also.

**Comment by JCash** [comment]
Some implementation details:
dmProfile - namespace/api that collects the profiling data

dmProfiler
    - the "owner" of the dmProfile context, and 
    - implemented as an extension (in the defold repo)

dmProfileRender - helper functionality to render a profile frame (in game)

This task:

    - Collect the profile counter only
    - Not render any stats in game
    - Must work in release mode (since it's for a live game)
    - Not use the Remotery backend
    - Exclude the default profiler backend by using the extension manifest
    - Implement a new profiler library that collects the stats only
    - Create a script module in the new extension, that can provide the Lua table with the counters

**Comment by JCash** [comment]
As a first step, I created an [extension here](https://github.com/defold/extension-profile-counters) (WIP).

The output currently looks like this:
```lua
DEBUG:SCRIPT: Counters,
{ --[[0x110c43860]]
  Script = { --[[0x110c3cf30]]
    LuaRefs = 18,
    LuaMem = 324,
    TimerCount = 0
  },
  Resource = 11,
  TestExt = { --[[0x10e665400]]
    TestExtFrames = 79,
    TestExtRandom = 482997726
  },
  Gui = 0,
  GameObject = { --[[0x110c3a070]]
    GODeleted = 0,
    ComponentsAnim = 0,
    GOInstances = 1,
    ScriptCount = 1
  },
  Components = { --[[0x110c38910]]
    Label = 0,
    Camera = 0,
    Sound = 0,
    Factory = 0,
    CollectionFactory = 0,
    Tilemap = 0
  },
  Particles = { --[[0x110c31430]]
    ParticlesAlive = 0
  }
}
```

The benefit of getting the full table is:
* 1 call between Lua <-> C
* No need to pack/unpack the naming to get the desired counter. E.g. `TestExt.TestExtFrames`
(we don't want to rely on the C symbols being unique)

**Comment by AGulev** [comment]
@JCash as I understand, we can close it? Should we announce it somewhere?

**Comment by JCash** [comment]
Yes,. we should present it in their channel now.
