### ISSUE TITLE
Do not compile *.cpp files from .defignore on bundle creation

### ISSUE THREAD

**Issue by MaxBrain** [defold/defold#7191]
**Describe the bug**
Compiling `*.cpp` files from `.defignore `on bundle creation

**To Reproduce**
- Create new empty project
- Create simple `extention\ext.manifest` for extention
- Create `extention\src\extention.cpp` source file with simple module initialization
- Create `extention\src\bad.cpp` source file with syntax error
- Create `.defignore` with `/extention/src/bad.cpp` line
- Look at the tree - there no `bad.cpp` file
- F5 key - build OK, we have empty window
- Project -> Bundle -> Android Application -> Create Bundle -> Select folder
- Syntax error from `bad.cpp` instead empty application

**Expected behavior**
`.cpp` files from `.defignore` skipped on build, and on bundle

**Defold version:**
  - Version 1.4.0

**Platforms:**
 - Platforms: Android, html5 and maybe other 

**Minimal repro case project:**
[Project.zip](https://github.com/defold/defold/files/10118388/Project.zip)

**Workaround:**
Remove bad sources

**Screenshots:**
![screen01-no-bad-file](https://user-images.githubusercontent.com/5093842/204681351-b73c101b-9505-4548-923c-861a8948d6a4.png)
![screen02-compilation-of-bad-file](https://user-images.githubusercontent.com/5093842/204681354-c13b0180-f140-4b24-a036-4d7dd51500c1.png)

**Comment by JCash** [comment]
I have to ask. What is the purpose of keeping a non working file in the project?
And, why not just rename it to "foo.cpp.bak" or something?
