### ISSUE TITLE
Draw convexshape collision shapes in editor

### ISSUE THREAD

**Issue by d954mas** [defold/defold#7201]
1)Draw convexshape collision when open .convexshape file. Now it show text
2)Draw convexshape collision when set as collision shape in collisionobject

I use a lot of  .convexshape in current project, and it impossible to understand which shape i am edit. For now i have 50+ shapes and i will have more.

![2022-12-02_19-36-20](https://user-images.githubusercontent.com/2655263/205341088-6b66d3a2-f3c6-4f91-b6c7-67eafbb30fb4.png)
![2022-12-02_19-35-57](https://user-images.githubusercontent.com/2655263/205341078-ee1b93a8-4bbe-4d12-a169-f99f34082f32.png)

**Comment by AGulev** [comment]
merged with https://github.com/defold/defold/issues/6072
