### ISSUE TITLE
Defold doesn't launch

### ISSUE THREAD

**Issue by esmo-ts** [defold/defold#7203]
**Describe the bug (REQUIRED)**
When I create a project from a template, let's a a mobile game, it creates the folder and everything, after the project gets created, the editor doesn't relaunch, and when I try to launch it, it simply doesn't launch, I had to restart windows so Defold can launch.

**To Reproduce (REQUIRED)**
1. Create a new project from a mobile game template
2. After it's created, Defold does not launch

**Expected behavior (REQUIRED)**
Defold editor should relaunch after creating the project from a template.

**Defold version (REQUIRED):**
  - Version [1.4.0]

- On Windows 10.

.

**Additional context (OPTIONAL):**
It's simply as that, the editor does not launch after creating a project from a template, and I have to restart Windows, so I can launch the editor again.

**Comment by britzl** [comment]
Do you get any kind of error? One thing you could try so that we get some logs is to start Defold.exe from a command prompt. This will output a lot of logs from the editor. Please try again and share the output from the command prompt here!

**Comment by esmo-ts** [comment]
I tried to run it from a command prompt, it simply logs nothing, like I never run it

**Comment by britzl** [comment]
> I tried to run it from a command prompt, it simply logs nothing, like I never run it

That doesn't sound right. Does it even start?

Where have you "installed" (read unzipped) Defold?

**Comment by britzl** [comment]
> Yes it doesn't even start, I unzipped it where I downloaded it, the download folder

Weird. Ok, let's say my user is `bjornritzl` and I unzipped into a folder named `Defold` in the downloads folder. From a command prompt:

```bash
cd c:\Users\bjornritzlDownloads\Defold
Defold.exe
```

Is this what you are doing? And nothing happens?

> and created a shortcut on desktop

And what if you don't create a shortcut and instead double click on the Defold.exe?

> the only solution in hand that works is to unzip Defold again, but that's not practical

What do you mean by this? Why does this work?

**Comment by britzl** [comment]
Sounds like some anti-virus problem or something. The Defold.exe is since about a month back signed using an EV Code Signing Certificate. That should hopefully shut up any anti virus from now on. Closing.
