### ISSUE TITLE
Bob stuck on building engine

### ISSUE THREAD

**Issue by SalavatR** [defold/defold#7207]
Hi! i'm trying to update applovin max sdk to latest version, with old sdk everything builds well, but when i updated adapters to 
latest verions, bob freezes on Building engine stage

here is new gradle file
```

repositories {
    google()
    mavenCentral()
    maven { url "https://android-sdk.is.com" }
    maven { url "https://imobile-maio.github.io/maven" }
    maven { url "https://dl-maven-android.mintegral.com/repository/mbridge_android_sdk_oversea" }
}

dependencies {
    // https://dash.applovin.com/documentation/mediation/android/getting-started/integration
    // https://search.maven.org/search?q=g:com.applovin.mediation

    implementation 'com.applovin:applovin-sdk:11.6.0' // builds well

    implementation 'com.applovin.mediation:facebook-adapter:6.12.0.1' // builds well

    implementation 'com.applovin.mediation:google-ad-manager-adapter:21.3.0.2' // builds well

    implementation 'com.applovin.mediation:google-adapter:21.3.0.2' // builds well

    implementation 'com.applovin.mediation:ironsource-adapter:7.2.5.0.1' //freezes

    implementation 'com.applovin.mediation:unityads-adapter:4.4.1.0' // builds well

    implementation 'com.applovin.mediation:vungle-adapter:6.12.0.4' // builds well

    implementation 'com.applovin.mediation:mintegral-adapter:16.3.11.0' //freezes

    implementation 'com.applovin.mediation:inmobi-adapter:10.1.2.1' //freezes

    implementation 'com.applovin.mediation:adcolony-adapter:4.8.0.2' //freezes

    implementation 'com.applovin.mediation:maio-adapter:1.1.16.2' //freezes

    implementation 'com.applovin.mediation:mytarget-adapter:5.16.2.0' //freezes

    implementation 'com.applovin.mediation:fyber-adapter:8.2.1.0' //freezes

    
    // mintegral, inmobi
    implementation 'androidx.recyclerview:recyclerview:1.1.0'// builds well
    // inmobi
    implementation 'com.squareup.picasso:picasso:2.71828'// builds well
}

```
**Expected behavior (REQUIRED)**

**Defold version (REQUIRED):**
  - 1.4.0

**Platforms (REQUIRED):**
 - Platforms: Android
 - OS: Windows 11, WSL Ununtu

**Minimal repro case project (OPTIONAL):**
Please attach a minimal project where the bug is reproduced. This will greatly help the person trying to investigate and fix the bug.

**Logs (OPTIONAL):**
Please provide relevant logs from engine, editor or build server. Learn where the logs are stored [here](https://defold.com/manuals/getting-help/#log-files).

**Workaround (OPTIONAL):**
If there is a workaround, please describe it here.

**Screenshots (OPTIONAL):**
![image](https://user-images.githubusercontent.com/11291477/206003862-b94b25d9-aaf9-49b7-b138-253469d69451.png)

**Comment by britzl** [comment]
Can you please attach a minimal project where this can be tested? We need to have a look at what's happening on the build server.

**Comment by SalavatR** [comment]
> Can you please attach a minimal project where this can be tested? We need to have a look at what's happening on the build server.

[mp10.zip](https://github.com/defold/defold/files/10170156/mp10.zip)

**Comment by britzl** [comment]
A bit strange: The first time I tested it failed and got stuck building the engine. I checked the server logs and saw that the manifest merge step failed and complained that "The include path '%s' does not exist:". From here:

https://github.com/defold/extender/blob/dev/server/src/main/java/com/defold/extender/ExtensionManifestValidator.java#L49-L51

I removed some dependencies and then it built successfully. I then added the extensions again and it still worked. Strange.

Could you please try and remove .internal/cache and the build folder and try again?

**Comment by SalavatR** [comment]
I did that, doesn't help, on second windows notebook, same situation

**Comment by SalavatR** [comment]
now same problem on linux, but build works from time to time, withou changing anything, very strange

**Comment by britzl** [comment]
@SalavatR are you still having problems with this?

**Comment by SalavatR** [comment]
I'll check it tomorrow

**Comment by SalavatR** [comment]
@britzl Same problem with 141 version

**Comment by britzl** [comment]
@SalavatR coming back to this issue I'm able to bundle the sample project for Android using Defold 1.4.5. We've updated the Android SDK and NDK which might explain why it is working now.
