### ISSUE TITLE
Cloned node IDs are empty hashes

### ISSUE THREAD

**Issue by totebo** [defold/defold#7209]
**Describe the bug (REQUIRED)**
Nodes cloned with `gui.clone()` or `gui.clone_tree()` return empty hashes when getting their ID with `gui.get_id()`.

**To Reproduce (REQUIRED)**
```
local nodes = gui.clone_tree(node_to_clone)
for node_name, node in pairs(nodes) do
local node_id = gui.get_id(node)
print("node_id", node_id) -- DEBUG:SCRIPT: node_id	hash: []
end
```

**Expected behavior (REQUIRED)**
Each cloned node should be assigned a unique ID returned when using gui.get_id().

**Defold version (REQUIRED):**
1.4.0

**Platforms (REQUIRED):**
macOS, iOS, Android.

**Workaround (OPTIONAL):**
A workaround is to use gui.set_id() on each individual node. This can be time consuming if using gui.clone_tree().

**Additional context (OPTIONAL):**
https://forum.defold.com/t/getting-node-id-to-update-gooey/65744
https://github.com/britzl/defold-input/issues/5

**Comment by Insality** [comment]
In Druid I have some hack to escape this issue, but I should say it's a kind of bug probably:
https://github.com/Insality/druid/blob/develop/druid/component.lua#L118

And this is how it looks:
```lua
-- When we use gui.clone_tree in inner template (template inside other template)
-- this nodes have no id. We have table: hash(correct_id) : hash("")
-- It's wrong and we use this hack to fix this
if nodes then
    for id, node in pairs(nodes) do
        gui.set_id(node, id)
    end
end
```

**Comment by dri-richard** [comment]
This does feel like a bug. For example, if you clone a tree and parent it to another node, and call gui.get_tree() on that node, you don't get the child nodes back unless you set their ID. It's like they don't exist.
