### ISSUE TITLE
The GUI template location is not applied when changing the layout if there has been no change in the position of the parent node.

### ISSUE THREAD

**Issue by megalanthus** [defold/defold#7213]
**Describe the bug (REQUIRED)**
The location of the GUI template is not applied when changing the layout unless there has been a change in the position of the parent node (when running in the editor). In the build it works as expected.

**To Reproduce (REQUIRED)**
1. Create gui template.
2. Move the template to the desired positions for different layouts, and do not change the position of the parent node in the template.
3. Run project (ctrl-b)
4. When the window is resized after switching the layout, the template stays in place in the default position.

**Expected behavior (REQUIRED)**
The template is expected to move to the specified position.

**Defold version (REQUIRED):**
  - Version 1.4.0.

**Platforms (REQUIRED):**
 - Platforms: Windows
 - OS: Windows 10

**Minimal repro case project (OPTIONAL):**
[layout_with_template_bug.zip](https://github.com/defold/defold/files/10183906/layout_with_template_bug.zip)

**Screenshots (OPTIONAL):**
![image](https://user-images.githubusercontent.com/66716124/206407817-a13ec530-0c15-44c4-946c-7e19eee232c9.png)
![image](https://user-images.githubusercontent.com/66716124/206407966-a7e76dbc-e81d-4e89-b015-b3d18eba1af0.png)

**Comment by AGulev** [comment]
If I understand everything right, it is fixed in 1.9.6 

1.9.5
![CleanShot 2024-12-07 at 17 56 57@2x](https://github.com/user-attachments/assets/74d93afe-ae48-467d-a381-6208bd24d092)

1.9.6
![CleanShot 2024-12-07 at 17 57 42@2x](https://github.com/user-attachments/assets/218fa815-efc7-4e3a-aa5c-aef87f726f80)


FYI @matgis

**Comment by megalanthus** [comment]
> If I understand everything right, it is fixed in 1.9.6

Yes, in version 1.9.6 everything works as expected! Thank you!
