### ISSUE TITLE
Multi touch input getting lost on Android

### ISSUE THREAD

**Issue by beginnne** [defold/defold#7216]
This bug seems to have been flagged as fixed several times, however, I am experiencing touch up and touch down event losses on android.

I have two gui boxes which are acting as left and right "paddles". When the user presses the left paddle at the same time as releasing the right paddle, the touch up and touch down events are lost. This happens vise versa also.

As far as I can tell, it happens when the actions are executed on the same frame.

I can't reproduce the problem using arrow keys, it only happens with multi touch.

I am still fairly new to Defold, so I'm sorry if I've missed anything glaringly obvious.

I would love to continue using Defold for my project, but am afraid this will be a show stopper if there is no workaround/fix.

I'm testing by bundling the project and installing on a Samsung A53 5G.

I'm also using Monarch with screen proxies, but can't see that would be a problem.

Defold Version 1.4.0

Many thanks in advance

**Comment by britzl** [comment]
Can you please share a minimal project where this can easily be tested?

**Comment by dmedwaycomputing** [comment]
Please forgive my terrible coding and inexperience. I'm still trying to get my head around lua and the way Defold works.

I've rewritten a very basic example which replicates the problem. It's probably something I'm doing wrong.

It does take some practice to tap the screen in such a way to cause the issue, but it is definitely there.

[Mobile game.zip](https://github.com/defold/defold/files/10207169/Mobile.game.zip)

**Comment by beginnne** [comment]
Okay, so this is very strange. I've stripped it right down to this:

```
function init(self)
	msg.post(".", "acquire_input_focus")
end

function on_input(self, action_id, action)
	if action_id == hash("multitouch") then
		if #action.touch < 2 then
			for i, touchdata in ipairs(action.touch) do
				if touchdata.x < 480 then
					print("moving left")
				end

				if touchdata.x > 480 then
					print("moving right")
				end
			end
		end
	end
end
```

It's literally all that's happening. And still, a whole tap is being missed every now and then.

There's obviously no message passing, and everything is self contained! Am I missing something obvious?

**Comment by britzl** [comment]
Why that check for if number of touch events are less than 2?

**Comment by beginnne** [comment]
@britzl Thank you for the gentle nudge. Apologies for reporting it as a bug.

Just took a bit of extra coding. Apologies for my incompetence.

**Comment by beginnne** [comment]
Sorry to reopen this, but the problem is still there.

I have stripped the example right down to the bare minimum that is possible. We're still losing a whole touch every now and then.

If you watch the printed output and press left and right alternatively, eventually the output will stop while a finger is pressed. This would obviously cause the player to have stopped too, which is undesirable.

I'm afraid this is a problem that will cause me to use a different engine, as guaranteed input is vital to the mechanic of the game.

[Mobile game.zip](https://github.com/defold/defold/files/10227978/Mobile.game.zip)

**Comment by britzl** [comment]
I'll have a look. Which phone have you been testing this on?

**Comment by beginnne** [comment]
Thanks, it's a Galaxy A53

**Comment by britzl** [comment]
I'm unable to reproduce this.... I don't have the exact same device though. Have you tested on other phones? Are you pressing left and right rapidly? Also perhaps where on the screen are you pressing? Just next to the edge or more towards the middle?

**Comment by beginnne** [comment]
I will try on a few other devices. I'm pressing left and right slowly so to catch the missed touch. I'm pressing roughly center left and center right. It happens when one tap is happening at the exact same time the other is being lifted.

As I said, I will try on a few other devices.

**Comment by beginnne** [comment]
Okay. So far I've tried two different phones and also compiled on two different computers and I'm getting the same problem. All four combinations produce the same result. I can only think of doing a video of the problem to prove I'm not just being awkward. Would a youtube video link on here suffice?

**Comment by beginnne** [comment]
I've brushed the dust from my old Allwinner tablet, and it seems to be working fine. So, It's either specific to the Samsung A52s and A53, or a setting, or something. I dunno! I'll play with the settings and report back if I find anything.

**Comment by beginnne** [comment]
@britzl Please could you tell me which version of android you tested on?

**Comment by beginnne** [comment]
After some time, I found it still rears it's head on the Allwinner too. I will post a video of the problem being replicated as soon as I can. Just hope I'm able to post the link here.

**Comment by britzl** [comment]
Ok, yes, please post a link. I'll have a look at our multi touch input handling code and see if I can spot any problems.

**Comment by beginnne** [comment]
Okay. I've made a short video: https://www.youtube.com/watch?v=m5PzTnC8F2M

Hope this explains better than me rambling on.

**Comment by beginnne** [comment]
And here's the exact project used in the video.

[Mobile game.zip](https://github.com/defold/defold/files/10258538/Mobile.game.zip)
