### ISSUE TITLE
Order indifferent local functions for cleaner code

### ISSUE THREAD

**Issue by mikatuo** [defold/defold#7225]
**Is your feature request related to a problem? Please describe (REQUIRED):**
It is cumbersome to write code in a more readable way so that the most important functions are placed at the top of a .script files and the least important ones at the bottom. The goal would be to place local functions in any order the developer wants.
Furthermore, it is easy to place local functions in a wrong order and get runtime errors, like, `attempt to call global 'cap_max_speed' (a nil value)`.

**Describe the solution you'd like (REQUIRED):**
I would like to place all my local functions after the .script lifecycle methods (init, update, on_input, etc), and to place the high level functions at the top and the low level (smaller) ones at the bottom. As a bonus it would eliminate runtime errors, like, `attempt to call global 'cap_max_speed' (a nil value)` when mistakenly local functions are placed in an incorrect order. See "additional context" for a demo.

**Describe alternatives you've considered (REQUIRED):**
As a workaround I define local variables at the top of the .script file and then assign them at the end of the file, which allows to place them in any order. See "additional context" for a demo.

**Additional context (OPTIONAL):**

# Demo

To demonstrate the problem, let's have a look at a refactored https://defold.com/examples/movement/move_forward/ example.
Here is how one might clean up the .script file. Notice that you start reading the code from a low level function (`cap_max_speed`) and generally you will have to read through a mix of low and high level functions till the end of the file. Ideally, I would prefer to glance through the most important ones right after the .script file is opened, and then if I need, to read through the low level local functions.

![current](https://user-images.githubusercontent.com/7230306/208310070-d95075cf-b06b-4863-b3b8-bac43b12ccec.png)

# Workaround

As a workaround I can define all local functions at the top of the file, and then assign them in any order I like. While it works, it requires quite a lot of boilerplate code, adds "junk" variables at the beginning of the file and makes refactoring harder.

![workaround](https://user-images.githubusercontent.com/7230306/208310166-bdf5549b-2b8d-47fe-a3d8-051c99908b87.png)

# Desired Solution

The desired solution would be to place local functions anywhere in the file and in any order without any additional boilerplate code.

![goal](https://user-images.githubusercontent.com/7230306/208310212-6e0d644c-f7c2-49a5-88bd-428ac41bc0c3.png)

**Comment by britzl** [comment]
Thank you for a very well written feature request. 

The problem you are describing is a problem with Lua, not with Defold. We use the LuaJIT or Lua 5.1.5 and both of these and the language itself actually care about the order in which functions are defined, or rather the order of variable definitions. We will not do anything on our end to address this as we do not consider it a problem which we can or should solve.
