### ISSUE TITLE
Undo by ctrl-z shortcut has a strange bug

### ISSUE THREAD

**Issue by DeRaNGeR** [defold/defold#7242]
### Expected behaviour
I want to undo something that i write, ctrl-z as shortcut could be the solution to remove the last edit.
### Actual behaviour
Nothing changed, if i write again after ctrl-z the editor crashes or add text randomly
### Steps to reproduce
1. write a text
2. ctrl-z
3.try to write again
<hr/>

<table>
<tr><td>Build time</td><td>2022-12-27T13:02:45.516943</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>3dbe1d48e60af43bbb258c24e881aadd8062a9e0</td></tr>
<tr><td>Defold engine sha</td><td>8f96e450ddfb006a99aa134fdd373cace3760571</td></tr>
<tr><td>Defold version</td><td>1.4.1</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"3ae4419b794945129b1c359984f2282f"'>3ae4419b794945129b1c359984f2282f</a></td></tr>
<tr><td>GPU</td><td>Intel(R) UHD Graphics</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 - Build 27.20.100.8783</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 11</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by vlaaad** [comment]
Thanks for the report, it's an issue introduced in the commit 3dbe1d48e60af43bbb258c24e881aadd8062a9e0. I reverted it now and will rework it.
