### ISSUE TITLE
Editor crush on multiple items drag in assets tree

### ISSUE THREAD

**Issue by iamursky** [defold/defold#7245]
**Describe the bug (REQUIRED)**
Editor crush on multiple items drag in assets tree

**To Reproduce (REQUIRED)**
1. Open project
2. Select multiple assets
3. Start dragging selected assets

**Expected behavior (REQUIRED)**
Dragging multiple assets in assets tree.

**Defold version (REQUIRED):**
  - Version 1.4.1

**Platforms (REQUIRED):**
 - Platforms: macOS 13.2 (a) Beta (22D7750270d)

**Screenshots (OPTIONAL):**

https://user-images.githubusercontent.com/33891482/210183009-d232f064-6cdb-40f8-bc43-339560e96c5b.mov

**Comment by ekharkunov-ms** [comment]
Same #6738
