### ISSUE TITLE
Support PS4 and other controllers on Windows

### ISSUE THREAD

**Issue by mikatuo** [defold/defold#7246]
**Is your feature request related to a problem? Please describe (REQUIRED):**
There was a discussion on Discord that on Windows only XBox 360 controllers are supported. Some game engines and Steam seems to have found a work around to support more controllers on Windows. Perhaps, there are possibilities to make them work in Defold too?

**Describe the solution you'd like (REQUIRED):**
PS4 and other controllers to work on Windows without asking users/players to install mappers or any other 3rd party tools.

**Describe alternatives you've considered (REQUIRED):**
Try different settings on Steam or ask users/players to use https://ds4-windows.com/

**Additional context (OPTIONAL):**
![image](https://user-images.githubusercontent.com/7230306/210184998-c5f2f841-3ab7-42c7-9399-7cfc685601a5.png)

![image](https://user-images.githubusercontent.com/7230306/210185007-f4304309-2851-4357-974e-f948283b6c3f.png)
![image](https://user-images.githubusercontent.com/7230306/210185012-53edf04a-75c7-4082-a213-774ead01a773.png)

![image](https://user-images.githubusercontent.com/7230306/210185020-b3fbeedf-cb8d-4e43-8688-515c7a11becb.png)

**Comment by aglitchman** [comment]
> Perhaps, there are possibilities to make them work in Defold too?

Looks like the only way is to back-port DirectInput joystick support from GLFW 3 to Defold's custom GLFW - https://github.com/glfw/glfw/blob/master/src/win32_joystick.c

And their mappings database could be a useful source for Defold's mappings - https://github.com/glfw/glfw/blob/master/src/mappings.h

**Comment by subsoap** [comment]
You could do it with a NE too.

**Comment by Jhonnyg** [comment]
I'd rather not put this into our GLFW as we eventually want to move away from GLFW completely. I'd like to see if we can hook this into the HID layer directly, or as an extension perhaps. However I do think it could be considered core functionality since we already support gamepads, so maybe it makes most sense to put it into the engine directly.

**Comment by britzl** [comment]
> maybe it makes most sense to put it into the engine directly

Yes, I think it should go into the engine core!
