### ISSUE TITLE
Animate complete function is called earlier than expected when animating euler property

### ISSUE THREAD

**Issue by dmkondr** [defold/defold#7253]
**Describe the bug (REQUIRED)**
Animate complete function is called earlier than expected when animating euler property

**To Reproduce (REQUIRED)**
```
go.animate(".", "euler.z", go.PLAYBACK_ONCE_FORWARD, 90, go.EASING_LINEAR, 1, 0, function()
	print(go.get(".", "euler.z")) -- prints 88.xxx or 89.xxx

	timer.delay(0.1, false, function()
		print(go.get(".", "euler.z")) -- prints 90
	end)
end)
```

**Expected behavior (REQUIRED)**
I expect the complete function to be called the same frame when euler property reaches its target value

**Defold version (REQUIRED):**
  - Version 1.4.1

**Platforms (REQUIRED):**
 - OS :Windows 11

**Comment by britzl** [comment]
I'm actually not getting 90 degrees when testing your example. I get the same value in both cases (around 89.2). The thing is that the euler property is "fake". We never really use it internally and always convert to from a quaternion rotation. I'm still a bit surprised though that it seems like the precision is fairly low and that you are getting something like 89.2 degrees when rotating to 90.
