### ISSUE TITLE
java.lang.NullPointerException when building HTML5

### ISSUE THREAD

**Issue by Vbif** [defold/defold#7291]
**Describe the bug (REQUIRED)**
"Build HTML5" in editor and "bob build" fails with java.lang.NullPointerException. Editor dont provide any information beside the exception. Bob give this:
```
game % java -jar ~/Downloads/bob.jar build
Working...Reading classes... 1% ...done!
Cleaning engine... ...done!
Reading tasks...java.lang.NullPointerException: Cannot read the array length because "bytes" is null
Cause: java.lang.RuntimeException: java.lang.NullPointerException: Cannot read the array length because "bytes" is null
```
Simple build with "command + B" works fine.

**Expected behavior (REQUIRED)**
Nice error description with infomation about file with error

**Defold version (REQUIRED):**
  - Version  1.4.1

**Platforms (REQUIRED):**
 - Platforms: HTML5
 - OS: MacOs

**Minimal repro case project (OPTIONAL):**
[Archive.zip](https://github.com/defold/defold/files/10449789/Archive.zip)

**Comment by britzl** [comment]
Bob in verbose mode shows:

```
Caused by: java.lang.NullPointerException: Cannot read the array length because "bytes" is null
	at java.base/java.lang.String.<init>(String.java:1435)
	at com.dynamo.bob.pipeline.ProtoUtil.merge(ProtoUtil.java:30)
	at com.dynamo.bob.pipeline.CollectionBuilder.collectSubCollections(CollectionBuilder.java:65)
	at com.dynamo.bob.pipeline.CollectionBuilder.create(CollectionBuilder.java:119)
	at com.dynamo.bob.Project.createTask(Project.java:429)
	... 6 more
```

**Comment by britzl** [comment]
Ok, the problem is that `bootstrap_yandex.collection` referenced a file that doesn't exist, and even if `bootstrap_yandex.collection` isn't used in the actual build it is still parsed during the build process and this error is the encountered.

**Comment by vbif1** [comment]
@britzl, is there an opportunity to show problem file in editor log? The name of missing file or/and name of collection that reference missing file.
Currently it shows "Unknown source - Resource does not exist"

**Comment by britzl** [comment]
> is there an opportunity to show problem file in editor log?

Yeah, we'll look into your suggestion as reported here: https://github.com/defold/defold/issues/7862
