### ISSUE TITLE
Problem with syntax highlighting in the Defold editor

### ISSUE THREAD

**Issue by ReanimatorXP** [defold/defold#7292]
**Describe the bug (REQUIRED)**
With the new update, the syntax highlighting of some keywords (ie, **self**) and function headers is gone 

**Defold version (REQUIRED):**
  - Version 1.4.1 (ab6fbbf)

**Platforms (REQUIRED):**
 - Editor (Windows)

**Screenshots (OPTIONAL):**
![image](https://user-images.githubusercontent.com/24944063/213448876-8ee9385c-31eb-4117-b43b-9c60c3be7008.png)
Arrows point to problem areas where the highlighting was before.

**Comment by vlaaad** [comment]
The fix is committed and should be available as an editor update soon.
