### ISSUE TITLE
IDE: The console doesn't have syntax highlighting

### ISSUE THREAD

**Issue by aglitchman** [defold/defold#7297]
**Describe the bug (REQUIRED)**
[The linting update](https://forum.defold.com/t/linting-in-the-code-editor/72465) disabled highlighting for the console. Look at the screenshots below.

**To Reproduce (REQUIRED)**
Update IDE to the latest version.

**Expected behavior (REQUIRED)**
The console log should be highlighted!

**Defold version (REQUIRED):**
  - Version 1.4.1

**Platforms (REQUIRED):**
 - OS: Windows 10

**Screenshots (OPTIONAL):**
Before the linting update:
![image](https://user-images.githubusercontent.com/193258/213695558-06e6de14-88c9-4eb1-a0db-257a31cc57fc.png)

After the update:
![image](https://user-images.githubusercontent.com/193258/213696360-aa9c8b55-2d9e-4d17-b611-e1548152cfd1.png)

**Comment by vlaaad** [comment]
Do you have an update available? It should be fixed...

**Comment by vlaaad** [comment]
Okay, I think I know what happened. Yesterday I received a notification that the build of a previous commit failed, and I triggered a rebuild. It caused a new editor release of that commit, overwriting the version that fixes console highlighting. I triggered a rebuild of the latest editor commit with a console highlighting fix.

**Comment by vlaaad** [comment]
I triggered rebuild of the latest editor commit, the update should be available in maybe 15 minutes
