### ISSUE TITLE
arm64-macos (Apple Silicon) support for runtime

### ISSUE THREAD

**Issue by AGulev** [defold/defold#7299]
**Task (REQUIRED):**
Add support for `arm64-macos` platform for runtime

**Expected outcome (REQUIRED):**
- a possibility to build (cmd+b) for arm64-macos in the editor if host machine is MacOS with Apple Silicon
- a possibility to bundle for arm64-macos

**Comment by JCash** [comment]
Related PR for engine: https://github.com/defold/defold/pull/6912

**Comment by britzl** [comment]
Done.
