### ISSUE TITLE
arm64-macos (Apple Silicon) support for bob.jar

### ISSUE THREAD

**Issue by AGulev** [defold/defold#7300]
**Task (REQUIRED):**
Add ability to run bob.jar using JDK for arm64

**Expected outcome (REQUIRED):**
- faster build/bundle process on arm64-macos platform

**Comment by JCash** [comment]
Related PR for Bob+Engine: https://github.com/defold/defold/pull/6912

**Comment by britzl** [comment]
Done in https://github.com/defold/defold/pull/6912

**Comment by AGulev** [comment]
these are missing libs/executables:

• zipalign
• strip_android_aarch64
• strip_android
• oggz-validate
• liboggz.dylib
• libogg.dylib
• codesign_allocate

![Image](https://github.com/defold/defold/assets/2209596/4b762dce-73e2-425c-bc8d-54e5bc59e385)
