### ISSUE TITLE
arm64-macos (Apple Silicon) support for extender (ability to run standalone extender on ARM64)

### ISSUE THREAD

**Issue by AGulev** [defold/defold#7302]
**Task (REQUIRED):**
Add a possibility to run standalone extender on Apple Silicon hardware.

**Expected outcome (REQUIRED):**
A possibility to run standalone extender on modern Apple hardware

**Comment by britzl** [comment]
We've now tested a full setup of an extender installed on arm64 macOS instance. Everything works as expected. There's some additional setup required, at least on Ventura):

https://github.com/defold/extender/pull/329/files#diff-70271fe359a329fa40689c899e4953940d47fbf9d702067ee6701baefbef88d8R19-R29
