### ISSUE TITLE
Dependency list contains only blank names

### ISSUE THREAD

**Issue by abadonna** [defold/defold#7306]
### Expected behaviour

Dependency list has blank names

### Actual behaviour

List of assets

### Steps to reproduce

Collection context menu ->  Dependencies

<hr/>

<table>
<tr><td>Build time</td><td>2023-01-19T14:36:29.442121</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>e0ad4769ad5b83c60b185b54ff889f4437b0d128</td></tr>
<tr><td>Defold engine sha</td><td>8f96e450ddfb006a99aa134fdd373cace3760571</td></tr>
<tr><td>Defold version</td><td>1.4.1</td></tr>
<tr><td>GPU</td><td>Intel(R) Iris(TM) Graphics 540</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-18.8.5</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>12.6.2</td></tr>
<table>

**Comment by britzl** [comment]
Hmm, do you have a stack trace or editor log you can share?

**Comment by abadonna** [comment]
[editor2.2023-01-24.log](https://github.com/defold/defold/files/10487690/editor2.2023-01-24.log)

here is video: https://www.dropbox.com/s/ik17j92z2576lpj/dependencies.mov?dl=0
