### ISSUE TITLE
Geometry instance support

### ISSUE THREAD

**Issue by Jhonnyg** [defold/defold#7314]
**Is your feature request related to a problem? Please describe (REQUIRED):**
To increase performance for more advanced 3D features such as foliage, crowds and props (and perhaps even 2D, e.g particles) you typically want to use hardware instancing to avoid issuing unnecessary draw calls as well as passing more vertices to the GPU before rendering.

**Describe the solution you'd like (REQUIRED):**
Control what objects or materials that should be issued as instanced calls.

**Describe alternatives you've considered (REQUIRED):**
Only alternative is what we have now, i.e draw models one-by-one or via the built-in batching that happens per component type.

**Comment by AGulev** [comment]
https://github.com/defold/defold/issues/4818
