### ISSUE TITLE
Bundle Error

### ISSUE THREAD

**Issue by asetsiya** [defold/defold#7327]
Hi. I'm just trying to learn defold. I have very little knowledge. So maybe I'm asking something silly. Maybe the solution is too simple. I don't know. I've searched for this many times but haven't found anything. I read the defold site. I couldn't see anything about this error. So I decided to ask here now.

When I press the "Build" button in any project in Defold, everything works fine. There is no problem.

But whenever I try to use the "Bundle" button I get the same error. I've tried it on all kinds of projects. Also in Defold's own sample and tutorial projects or in the empty project. In this process, Defold has been updated twice, but this has not changed. I even tried the same thing on another computer. The result is still the same.

Android, Mac, Windows, Linux, HTML5, I've tried them all.
Also the "Build HTML5" button shows the same error.
No plugins or anything like that.

### The error:
`No enum constant com.dynamo.bob.util.BobProjectProperties.PropertyType.STRİNG`

### Expected behaviour

If we're going to package it for Windows, create an executable file or something.

### Actual behaviour
![ss1](https://user-images.githubusercontent.com/123804767/215263487-d9f22294-8946-406a-a320-e80881f81042.png)

### Log file
[editor2.2023-01-28.log](https://github.com/defold/defold/files/10527095/editor2.2023-01-28.log)

<hr/>

![ss2](https://user-images.githubusercontent.com/123804767/215263514-145231ae-63c9-4638-ac76-dfadaa701a86.png)

<table>
<tr><td>Build time</td><td>2023-01-26T15:38:46.158998</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>6546a6b2ab4a0adcea3e0ad03b9e2f8dc2e866de</td></tr>
<tr><td>Defold engine sha</td><td>8f96e450ddfb006a99aa134fdd373cace3760571</td></tr>
<tr><td>Defold version</td><td>1.4.1</td></tr>
<tr><td>GPU0</td><td>GPU 0 NVIDIA GeForce RTX 3050</td></tr>
<tr><td>GPU1</td><td>AMD Radeon(TM) Graphics</td></tr>
<tr><td>Java version</td><td>11.0.17+8(x64)</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 11</td></tr>
<tr><td>OS version</td><td>22H2</td></tr>
<table>

**Comment by britzl** [comment]
> STRİNG

This looks strange. We've seen issues with locale when using Java in the past. Where are you from? Or rather what language are you using in your OS?

**Comment by britzl** [comment]
"İ, or i, called dotted I or i-dot, is a letter used in the Latin-script alphabets of Azerbaijani, Crimean Tatar, Gagauz, Kazakh, Tatar, and Turkish"

We actually found and submitted a similar kind of Java toUpper/capitalization issue for the Android bundletool: https://forum.defold.com/t/android-bundle-error/68851/14?u=britzl

**Comment by britzl** [comment]
I think we need to use `value.toUpper(Locale.ENGLISH)` here:

https://github.com/defold/defold/blob/dev/com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/util/BobProjectProperties.java#L91

**Comment by vlaaad** [comment]
Wet usually use Locale.ROOT in the editor for that

**Comment by asetsiya** [comment]
Wow! "STRİNG" I'm surprised I didn't notice that. Thank you so much. The system language was Turkish. Now I did English and it worked. Wonderful! Many thanks again.

**Comment by asetsiya** [comment]
Wow! "STRİNG" I'm surprised I didn't notice that. Thank you so much. The system language was Turkish. Now I did English and it worked. Wonderful! Many thanks again.

**Comment by asetsiya** [comment]
i tested the 1.4.4 alpha and beta versions, thinking that you have solved the error, but bob still shows the same error in turkish system language. i just wanted to let you know.

**Comment by britzl** [comment]
@asetsiya it does? Hmm, that is strange. Ooooh, I see what's happening. I fixed it in bob when used on the command line, but apparently it is not working correctly when running from the editor.

@vlaaad you mentioned that _"We usually use Locale.ROOT in the editor for that."_ but the question is if you are setting `Locale.ROOT` using `Locale.setDefault(Locale.ROOT);` or if you do it per call to `toUpper()`? I'm guessing that this is not done using `setDefault` and as such it will not propagate down to any call you make into bob.jar.

**Comment by vlaaad** [comment]
Yes, we supply it as an argument in `toUpperCase` calls.
