### ISSUE TITLE
Crash windows headless app

### ISSUE THREAD

**Issue by osov** [defold/defold#7339]
**Describe the bug (REQUIRED)**
I create headless assembly for Windows - 32/64 (it doesn't matter).
It almost always crashes on startup. Sometimes it seems to start without a crash (but rarely).

**To Reproduce (REQUIRED)**
I'm creating a headless assembly for Windows.

**Expected behavior (REQUIRED)**
Terminal app.

**Defold version (REQUIRED):**
  - Version 1.4.2

**Platforms (REQUIRED):**
 - Platforms: Windows
 - OS:  Windows 10

**Logs (OPTIONAL):**
```
ERROR:CRASH: CALL STACK:
ERROR:CRASH:  0 0x7FF60A736E00 _snscanf_s <unknown>:0
ERROR:CRASH:  1 0x7FF60A899B80 LZ4MaxCompressedSize <unknown>:0
ERROR:CRASH:  2 0x7FF60A899B80 LZ4MaxCompressedSize <unknown>:0
ERROR:CRASH:  3 0x7FF60A899B80 LZ4MaxCompressedSize <unknown>:0
ERROR:CRASH:  4 0x7FFBDB9911F0 __chkstk <unknown>:0
ERROR:CRASH:  5 0x7FFBDB93B1B0 RtlRaiseException <unknown>:0
ERROR:CRASH:  6 0x7FFBDB98FE10 KiUserExceptionDispatcher <unknown>:0
ERROR:CRASH:  7 0x7FF60A899B80 LZ4MaxCompressedSize <unknown>:0
ERROR:CRASH:  8 0x7FF60A70E7B0 sprintf <unknown>:0
ERROR:CRASH:  9 0x7FF60A744450 dmHashReverseErase64 <unknown>:0
ERROR:CRASH: 10 0x7FF60A744450 dmHashReverseErase64 <unknown>:0
ERROR:CRASH: 11 0x7FF60A899B80 LZ4MaxCompressedSize <unknown>:0
ERROR:CRASH: 12 0x7FF60A8029D0 DecryptXTeaCTR <unknown>:0
ERROR:CRASH: 13 0x7FF60A7BA770 Particle_Hash <unknown>:0
ERROR:CRASH: 14 0x7FF60A7BA770 Particle_Hash <unknown>:0
ERROR:CRASH: 15 0x7FF60A7BA770 Particle_Hash <unknown>:0
ERROR:CRASH: 16 0x7FF60A70E7B0 sprintf <unknown>:0
ERROR:CRASH: 17 0x7FF60A899B80 LZ4MaxCompressedSize <unknown>:0
ERROR:CRASH: 18 0x7FFBDB7D7020 BaseThreadInitThunk <unknown>:0
ERROR:CRASH: 19 0x7FFBDB93D0B0 RtlUserThreadStart <unknown>:0
```
[crash + debug symbols](https://disk.yandex.ru/d/DgEwsVA1kpkjBw)

**Comment by britzl** [comment]
Uploading crash + debug symbols here too: [crash (1).zip](https://github.com/defold/defold/files/10546278/crash.1.zip)

**Comment by britzl** [comment]
@osov can you please share a minimal project where this problem happens?

**Comment by osov** [comment]
Phew, finally able to create a minimal example.
feature in 2 lines of code:
```
 go.set("/fields#sprite", "tint", vmath.vector4(1,1,1, 1))
 factory.create("/prefabs#help", vmath.vector3(1,1,1)) 
```

[CrashHeadless.zip](https://github.com/defold/defold/files/10547396/CrashHeadless.zip)

**Comment by JCash** [comment]
THanks for the repro, I can now reproduce this on macOS using the address sanitizeer which should hopefully be an easy fix.

**Comment by JCash** [comment]
Further investigation shows its the sprite component not reallocating its index buffer when encountering the slice9 sprites.
