### ISSUE TITLE
Using `Initial Stretch` and `Initial Angular Velocity` fields on second emitter on particle effects causes `NullPointerException`

### ISSUE THREAD

**Issue by wookieejedi** [defold/defold#7342]
**Describe the bug (REQUIRED)**
Emitters on particle effects that are not the first emitter have the fields of `Initial Stretch X` or `Initial Stretch Y` or `Initial Angular Velocity` greyed out. Also clicking on those fields and adding a value causes an error `java.lang.NullPointerException: Unknown` (attached below). I have also posted a follow-up comment that inquires about a possible solution, though I am not able to build Defold and the editor to test it myself. 

EDIT: Appears this is a duplicate of #5346.

**To Reproduce (REQUIRED)**
1. Create new blank project.
2. Add new particle effects.
3. Add a second emitter.
4. On that second emitter it is not possible to use the values `Initial Stretch X` or `Initial Stretch Y` or `Initial Angular Velocity`, and putting a value there causes this error. I have attached a simple repo case, too.

**Expected behavior (REQUIRED)**
Expected behaviour is being able to use `Initial Stretch X` or `Initial Stretch Y` or `Initial Angular Velocity` with a second emitter (or third, or fourth, etc) on a particle effect. 

**Defold version (REQUIRED):**
  - Version 1.4.2 beta

**Platforms (REQUIRED):**
 - Platforms: Windows 
 - OS: Windows 11
 - Device: Dell XPS Desktop

**Minimal repro case project (OPTIONAL):**
[Emitter_Bug_Repo.zip](https://github.com/defold/defold/files/10547444/Emitter_Bug_Repo.zip)
<hr/>

**Log (OPTIONAL):**
[editor2.2023-01-31.log](https://github.com/defold/defold/files/10548474/editor2.2023-01-31.log)

<table>
<tr><td>Build time</td><td>2023-01-25T10:42:01.611373</td></tr>
<tr><td>Defold channel</td><td>beta</td></tr>
<tr><td>Defold editor sha</td><td>8cd3a634b13f4db51a37607bf32bf3a3b362c8e6</td></tr>
<tr><td>Defold engine sha</td><td>8cd3a634b13f4db51a37607bf32bf3a3b362c8e6</td></tr>
<tr><td>Defold version</td><td>1.4.2</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"58879f634abd42c2a3e40e0da4e65759"'>58879f634abd42c2a3e40e0da4e65759</a></td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GTX 1660/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 528.24</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 11</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by wookieejedi** [comment]
I'm wondering if this bug is caused by these entires not being present in `template.emitter` 
![image](https://user-images.githubusercontent.com/14077810/215821821-f0fb1926-c0f0-481b-aa3b-68df72249890.png)

**Comment by britzl** [comment]
> I'm wondering if this bug is caused by these entires not being present in `template.emitter`? ![image](https://user-images.githubusercontent.com/14077810/215821821-f0fb1926-c0f0-481b-aa3b-68df72249890.png)

Possibly. What if you manually add them to the created file? Does everything work as expected then?

**Comment by wookieejedi** [comment]
> > I'm wondering if this bug is caused by these entires not being present in `template.emitter`? ![image](https://user-images.githubusercontent.com/14077810/215821821-f0fb1926-c0f0-481b-aa3b-68df72249890.png)
> 
> Possibly. What if you manually add them to the created file? Does everything work as expected then?

That fixed it, thanks! With that confirmation I have made a PR.

**Comment by vlaaad** [comment]
Fixed in #7355
