### ISSUE TITLE
Fonts not rendering correctly when bundling project

### ISSUE THREAD

**Issue by klaytonkowalski** [defold/defold#7346]
**Describe the bug (REQUIRED)**

When bundling a project outside of the editor, the `.` character is not rendered at font size 16 px regardless of anti-aliasing.

Editor build:
![c6fc9f86ecdfce9fe9b9342516d8f81f798dbf37](https://user-images.githubusercontent.com/70988652/215913734-d3e9581f-8337-47e9-aa52-480cf4fb736d.png)

Release or debug build:
![13f380f20e661f8c3a224e08036a186d1e0ac795](https://user-images.githubusercontent.com/70988652/215913756-42fcf0f6-b628-42b1-a645-0a5e99842319.png)

Tested on Windows and HTML. This occurred with two different fonts, so it is not a problem with the fonts themselves. Tested with both [monogram ](https://datagoblin.itch.io/monogram) and [m5x7](https://managore.itch.io/m5x7).

**To Reproduce (REQUIRED)**

1. Download example project.
2. Build for any platform outside of CTRL + B in the editor.
3. View result. The `.` characters are missing.

**Expected behavior (REQUIRED)**

All characters should be rendered at the supported font sizes.

**Defold version (REQUIRED):**

Tested on 1.4.1 and 1.4.2 (current).

**Platforms (REQUIRED):**

* Windows 11
* HTML

**Minimal repro case project (OPTIONAL):**

This project contains two GUI labels, one 32 px and one 16 px. The 16 px font does not render the `.`, but the 32 px font does. Monogram is used in this project.

![Screenshot 2023-01-31 182416](https://user-images.githubusercontent.com/70988652/215914676-e8193faa-0b16-4b95-91a8-cb5a7ba8c4c9.png)

Download: [example.zip](https://github.com/defold/defold/files/10552087/example.zip)

**Comment by vlaaad** [comment]
Not sure it's an editor issue? It seems the editor has expected behavior here.

**Comment by britzl** [comment]
You're right. It is likely an issue in the font compiler used in bob. But we need to investigate it a bit to be sure.

**Comment by klaytonkowalski** [comment]
Would it be possible for this issue to be fixed before February 17? This is the latest date I have to upload a final build to Steam without delaying the release. I understand there are other issues as well, however thought I'd ask anyway.

**Comment by britzl** [comment]
> Would it be possible for this issue to be fixed before February 17?

I'm afraid that is highly unlikely. Not optimal, but are you getting the same problem using a distance field font?

**Comment by klaytonkowalski** [comment]
I will try to test distance field fonts within the next couple days. It is unfortunate the rendering fails at the exact size I need, but that's life. ¯\_(ツ)_/¯

**Comment by klaytonkowalski** [comment]
I converted all of the text nodes to an 11px, 15px line-height font called "Cute Mono", which can be found here: https://takwolf.itch.io/retro-pixel-font?download

After bundling, the `.` character is still missing.

**Comment by klaytonkowalski** [comment]
> Not optimal, but are you getting the same problem using a distance field font?

I tried distance field and the problem is fixed. Of course this is not ideal, but at least it is an alternative. Additionally, my font becomes smeared as a distance field:

![Screenshot 2023-02-11 131424](https://user-images.githubusercontent.com/70988652/218276955-814da61e-68cb-4be3-aaf3-45c6f95291f5.png)

I think this is because of its somewhat small font size... when I increase it by 3x the problem is gone. I suppose distance fields don't work well with small metrics.

**Comment by klaytonkowalski** [comment]
@britzl I edited with width and height of the `.` glyph in the TTF file itself to be 125 x 125 instead of 100 x 100, then edited the whole character size to 625 instead of 600. This solved the issue. The problem might have to do with glyphs that do not meet some minimum size threshold.

![Screenshot 2023-02-14 110302](https://user-images.githubusercontent.com/70988652/218806878-7d8a4cc7-beed-40c6-a5da-52ab97a16558.png)

![Screenshot 2023-02-14 110329](https://user-images.githubusercontent.com/70988652/218806888-df370d08-fbb5-4c91-b4bf-7ac9d32e3b2d.png)

**Comment by britzl** [comment]
I am familiarising myself with our font compiler code in bob. If I generate a preview image and dump it it looks ok (I think). I see the . character:

![Image](https://user-images.githubusercontent.com/1300688/220208441-d2b42cc0-19c6-4003-9381-56da56793125.png)
