### ISSUE TITLE
Double font resource with different materials included to build

### ISSUE THREAD

**Issue by Insality** [defold/defold#7360]
**Describe the bug (REQUIRED)**
For example I have two similar font resource (all .font settings are equal), but they have different materials.

If I will build the game, it will include both of this fonts. Seems it should use only one of them.

My case: I'm using world gui material, so I have to use the font twice. But I don't want to include the resource itself several times

**To Reproduce (REQUIRED)**
- Load the example ([issue-double-font-resource.zip](https://github.com/defold/defold/files/10573770/issue-double-font-resource.zip))
- Build with build report
- See the result

**Expected behavior (REQUIRED)**
The font resources with equal params should be included only once

**Defold version (REQUIRED):**
- Any

**Platforms (REQUIRED):**
- Any

**Minimal repro case project (OPTIONAL):**
[issue-double-font-resource.zip](https://github.com/defold/defold/files/10573770/issue-double-font-resource.zip)

**Screenshots (OPTIONAL):**
<img width="1160" alt="Screenshot 2023-02-02 at 23 53 30" src="https://user-images.githubusercontent.com/3294627/216458082-3dfdf95f-29b1-4aa4-bf28-e791f175fea9.png">

**Comment by Morgerion** [comment]
![image](https://user-images.githubusercontent.com/7888071/227066427-3e99dacc-ec97-414e-b837-2ec4d692ffd0.png)
![image](https://user-images.githubusercontent.com/7888071/227066474-7db6b891-fd81-46b9-8934-fbe4a762e53b.png)
I have the same problem.
I use blur in the GUI.
So I need two predicates - "under_blur" and "over_blur".
So I have to make two fonts for the same font with two different materials with two different predicates. This causes the build size to grow as the fonts are duplicated.

**Comment by matgis** [comment]
Since we do resource merging based on the binary content in the editor, I guess we'd need to restructure the `FontMap` message that is loaded by the engine to separate the `Glyph` data and related properties from the material-related properties?

I think this involves effort in both the engine, Bob and the editor, but at least we shouldn't need to do any project data migration since it is purely a change to the built binaries.
