### ISSUE TITLE
Failed to connect debugger (Android target)

### ISSUE THREAD

**Issue by dri-richard** [defold/defold#7361]
**Describe the bug**
After bundling a minimal application and running it on an Android target, the debugger fails to attach.
NB I'm aware of similar open issues, but this workflow works pretty well for me on 1.3.7 and I can't connect at all with 1.4.2 which we're evaluating.

**To Reproduce**
1. Create a new project
2. Add a game object and minimal script to main.collection
3. Bundle for Android with default options
4. Install on device
5. Run
6. Select the Android device as the target
7. Select Debug->Start/Attach

A window pops up:
Failed to attach debugger to 192.168.86.23:8172.
Check that the game is running and reachable over the network.
Server returned HTTP response code: 400 for URL: http://192.168.86.23:8001/post/@system/run_script

**Expected behavior**
The debugger attaches.

**Defold version (REQUIRED):**
1.4.2
editor 2515f42c78f5914c8e602359d5a8c7fa2262a43d
engine 8cd3a634b13f4db51a37607bf32bf3a3b362c8e6

**Platforms:**
 - Platforms: Android
 - OS: Android 10
 - Device: MI 9

**Minimal repro case project:**
[Debugger_test.zip](https://github.com/defold/defold/files/10578388/Debugger_test.zip)

**Comment by britzl** [comment]
Closed by https://github.com/defold/defold/pull/7363
