### ISSUE TITLE
Random colors from a GLB file are displayed

### ISSUE THREAD

**Issue by aglitchman** [defold/defold#7366]
**Describe the bug (REQUIRED)**
It turned out that Defold can import colors from glTF 3D models. But the feature doesn't work.

![image](https://user-images.githubusercontent.com/193258/216828274-93558af5-9fa0-486b-bc9f-c9cf007bcdc3.png)

Plus, Defold forces to specify a texture for a model to bundle the project. Why?
![image](https://user-images.githubusercontent.com/193258/216827599-575fe450-6213-4cd2-b11b-7d26a502fcc8.png)

**To Reproduce (REQUIRED)**
Take a look at the included project.

**Expected behavior (REQUIRED)**
The 3d model should be colored.

**Defold version (REQUIRED):**
  - Version: 1.4.2

**Platforms (REQUIRED):**
 - Platforms: Windows 10

**Minimal repro case project (OPTIONAL):**
[issue_glb_colors.zip](https://github.com/defold/defold/files/10611393/issue_glb_colors.zip)

The GLB file was exported from Houdini Indie 19.5.

**Screenshots (OPTIONAL):**
The included GLB file is valid (https://github.khronos.org/glTF-Validator/):
![image](https://user-images.githubusercontent.com/193258/216827521-bbfc2c74-eed4-49ff-8b66-fce3b2656451.png)

glb.ee and other online glTF viewers display the model perfectly fine
![image](https://user-images.githubusercontent.com/193258/216827491-d726c182-1589-4fcd-a484-665cc4b1a076.png)

**Comment by JCash** [comment]
Agreed this is a bug.

No real reason why the texture is needed other than old code, since afaik we didn't support vertex colors previously, which made it hard to color the model otherwise.

**Comment by JCash** [comment]
I have a fix for this coming up (we expected rgb4 but got rgb3).
I only have to add a unit test to catch the problem.

@aglitchman Would it be possible for us to use this model in our unit tests?

**Comment by aglitchman** [comment]
> @aglitchman Would it be possible for us to use this model in our unit tests?

Yes! 😊  I designed this model myself, so its license is Public Domain.

**Comment by JCash** [comment]
Thanks! I added attribution in the test_model.cpp as well :)
