### ISSUE TITLE
Black screen in War Battles Tutorial Because of Empty main.collection

### ISSUE THREAD

**Issue by CODESOLE** [defold/defold#7379]
### Expected behaviour
War battles tutorial must run properly.
### Actual behaviour
Gives black screen.

![Screenshot from 2023-02-11 02-48-23](https://user-images.githubusercontent.com/22984206/218224226-77d27a69-e1ef-4587-8949-75f5eff27d39.png)

### Steps to reproduce
Select War Battles Tutorial from the launcher then run Project > Build.

### Notes
This runs from my iGPU, however if i run engine from my Nvidia Geforce 920M same thing happens. Also i have tested on both wayland and Xorg windowing system and gives same issue. I am on Arch Linux GNOME 43.2.

If i run with `LIBGL_ALWAYS_SOFTWARE=1 ./Defold`, nothing changes. I can run Side Scroller Tutorial without any issue so there is something wrong with the War Battles project.

Here is the log if i run on my dedicated GPU.

<table>
<tr><td>Build time</td><td>2023-01-30T09:25:05.414035</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>8cd3a634b13f4db51a37607bf32bf3a3b362c8e6</td></tr>
<tr><td>Defold engine sha</td><td>8cd3a634b13f4db51a37607bf32bf3a3b362c8e6</td></tr>
<tr><td>Defold version</td><td>1.4.2</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce 920MX/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 525.89.02</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>6.1.10-arch1-1</td></tr>
<table>

<hr/>
Integrated GPU.
<table>
<tr><td>Build time</td><td>2023-01-30T09:25:05.414035</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>8cd3a634b13f4db51a37607bf32bf3a3b362c8e6</td></tr>
<tr><td>Defold engine sha</td><td>8cd3a634b13f4db51a37607bf32bf3a3b362c8e6</td></tr>
<tr><td>Defold version</td><td>1.4.2</td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) HD Graphics 520 (SKL GT2)</td></tr>
<tr><td>GPU Driver</td><td>4.6 (Compatibility Profile) Mesa 22.3.4</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>6.1.10-arch1-1</td></tr>
<table>

**Comment by CODESOLE** [comment]
Oh! I have looked a little bit and i noticed that main.collection is empty. Not engine, tutorial itself misconfigured, i guess.

**Comment by britzl** [comment]
> Not engine, tutorial itself misconfigured, i guess

Oh! Nice catch. Could you please point out where in the tutorial there is a problem and we'll make sure to update it!

**Comment by CODESOLE** [comment]
This is Side Scroller Tutorial and main.collection is ready to build and launch.

![image](https://user-images.githubusercontent.com/22984206/218310582-84898698-aaf1-4008-a25e-317be601a76d.png)

However War Battles Tutorial' s main.collection is empty so when try to launch, it gives black screen.

![image](https://user-images.githubusercontent.com/22984206/218310712-47627351-2f37-40e9-9aa1-b3caa3095610.png)

**Comment by britzl** [comment]
The War Battles tutorials is a step by step tutorial where you start with basically an empty project and in the end you have a small game of sorts. This means that the starting point of the tutorial is an empty project and a black screen.
