### ISSUE TITLE
FileNotFoundException builtins/builtins.zip

### ISSUE THREAD

**Issue by khameleonium** [defold/defold#7384]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2023-02-13T10:57:50.606207</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>1060d79b1e896c68a84f51a62f69a28c102bfd12</td></tr>
<tr><td>Defold engine sha</td><td>8cd3a634b13f4db51a37607bf32bf3a3b362c8e6</td></tr>
<tr><td>Defold version</td><td>1.4.2</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"079423f3df164d0eaef8b4116190a250"'>079423f3df164d0eaef8b4116190a250</a></td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GTX 670/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 474.14</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
```
class java.io.FileNotFoundException
/home/daniel/.Defold/unpack/5f92b6941a3d552a64bf69287c51e618d6d45534/builtins/builtins.zip (Nie ma takiego pliku ani katalogu)

java.io.FileInputStream in open0
java.io.FileInputStream in open at line 219
java.io.FileInputStream in <init> at line 157
clojure.java.io$fn in invokeStatic at line 229
clojure.java.io$fn in invoke at line 229
clojure.java.io$fn$G__11372__11386 in invoke at line 69
clojure.java.io$input_stream in invokeStatic at line 136
clojure.java.io$input_stream in doInvoke at line 121
clojure.lang.RestFn in invoke at line 410
editor.resource$load_zip in invokeStatic at line 327
editor.resource$load_zip_resources in invokeStatic at line 347
editor.resource$load_zip_resources in invoke at line 347
editor.resource$load_zip_resources in invokeStatic at line 349
editor.resource_watch$make_builtins_snapshot in invokeStatic at line 93
editor.resource_watch$make_snapshot_info in invokeStatic at line 184
editor.workspace$make_snapshot_info in invokeStatic at line 408
editor.disk$start_reload_job_BANG_$fn in invoke at line 82
clojure.core$binding_conveyor_fn$fn in invoke at line 2030
clojure.lang.AFn in call at line 18
java.util.concurrent.FutureTask in run at line 264
java.util.concurrent.ThreadPoolExecutor in runWorker at line 1128
java.util.concurrent.ThreadPoolExecutor$Worker in run at line 628
java.lang.Thread in run at line 829
```

**Comment by britzl** [comment]
@khameleonium does this happen all the time?

Can you please check in `/home/daniel/.Defold/unpack/LATEST_FOLDER` that there is a builtins/builtins.zip? Also, please check the editor log and share here.

https://defold.com/manuals/editor/#editor-logs

**Comment by AGulev** [comment]
no answer from the reporter
