### ISSUE TITLE
Use files from editor script used as extensions within the editor script

### ISSUE THREAD

**Issue by Jerakin** [defold/defold#7387]
With `action = "shell"` it is common to want to run a `.sh` file but if your editor-script is used as an extension you can not get a usuable path with `editor.get(extension, "path")`. I would like the ability to get and use a file from the extension within the editor script.

**Comment by vlaaad** [comment]
There is a way to make the editor unpack files from the library already, see the last paragraph in [this section of the editor scripting guide](https://defold.com/manuals/editor-scripts/#editor-scripts-in-libraries). The next section about LSP has an example that builds a command that refers to the unpacked file.

**Comment by Jerakin** [comment]
Worked perfectly!
