### ISSUE TITLE
Build server preference should automatically follow editor channel

### ISSUE THREAD

**Issue by dri-richard** [defold/defold#7393]
**Is your feature request related to a problem? Please describe:**
If not running your own build server, https://build.defold.com is used except when using a beta when it should be https://build-stage.defold.com
When evaluating Defold beta versions I'll have the beta installed alongside stable builds. I sometimes forget to change the build server to https://build-stage.defold.com/ and I sometimes forget to change it back again.

**Describe the solution you'd like:**
The build server setting would automatically be set according to the channel in use, and a checkbox would allow it to be overridden.

**Describe alternatives you've considered:**
The suggestion at https://github.com/defold/defold/issues/6415 of having the build server setting in the project could work, but wouldn't be my ideal. It would be an additional step, but I always create a new project branch when evaluating a new Defold version, so I'd be more likely to remember to change the setting at that moment.

**Comment by britzl** [comment]
This has happened to me on more than one occasion too!
