### ISSUE TITLE
Multiple materials on Models

### ISSUE THREAD

**Issue by JCash** [defold/defold#7399]
Each model can have many meshes and each mesh may have a separate material.

Currently our implementation only allows a single material which makes it harder to use.

Design thoughts:
https://docs.google.com/document/d/1NK5CRc7019Q2R1BgSgoDqvvJWwlSXxe8Ke9P-teKTk0/edit?usp=sharing

**Comment by AGulev** [comment]
Isn't it done?

**Comment by AGulev** [comment]
It seems like it's done with https://github.com/defold/defold/pull/7380
