### ISSUE TITLE
IDE: Pass color stream to display 3D models properly

### ISSUE THREAD

**Issue by aglitchman** [defold/defold#7407]
It would be great if IDE passed color stream to be able to preview 3D models with vertex colors properly.

Currently, it doesn't do that and this is how IDE displays models with vertex colors:
![image](https://user-images.githubusercontent.com/193258/220179688-d1b38ef5-e33b-4a15-85dc-29a06f9a97f0.png)

How they look in the game:
![image](https://user-images.githubusercontent.com/193258/220179809-be419f02-5b1c-4c17-aeb4-229ff47935ba.png)

The demo project:
[issue_model_color.zip](https://github.com/defold/defold/files/10787102/issue_model_color.zip)

The same drawback described there - https://forum.defold.com/t/new-gltf-model-importer-beta-test/71436/60?u=aglitchman

**Comment by matgis** [comment]
Related: https://github.com/defold/defold/issues/7427
