### ISSUE TITLE
Crash when playing sound as a component (file)

### ISSUE THREAD

**Issue by osov** [defold/defold#7411]
If you attach a component as a file (sound). Then when you call sound.play in the editor, everything works (Windows).
And if you make an assembly of Android or Html5, then a crash occurs.
Defold 1.4.2

**Comment by AGulev** [comment]
I think this issue fixed in 1.4.3 
>FIX: ([#7320 1](https://github.com/defold/defold/pull/7320)) Fix issue when OGG file added to GO without component doesn’t work in bundle
Now bob converts ogg component (resource based component) into sound component when building.

please check

**Comment by osov** [comment]
Okay, I'll check when version 1.4.3 comes out

**Comment by AGulev** [comment]
> Okay, I'll check when version 1.4.3 comes out

it's better to test in better. That's why Beta exist. If it's broken we will be able to fix it before release. 
But if we release it broken, it will be like that the next month

**Comment by britzl** [comment]
I agree with @AGulev . @osov if you have time, please download the beta and check if the fix solves your problem. It shouldn't take more than a few minutes to confirm and it would help us a lot.

https://d.defold.com/beta/

**Comment by osov** [comment]
Yes, the new version is fine.

**Comment by britzl** [comment]
Thank you!
