### ISSUE TITLE
Call stack show error originating from the wrong source

### ISSUE THREAD

**Issue by Jerakin** [defold/defold#7418]
If I return with a function call that throws an error like `return resource.get_atlas(0)` the error reporting will flag it as the "parent" _caller_ is throwing the error and not that the function at the return is breaking.

In other words with a setup like this

in `example/go.script`

```
function init(self)
  my_library.do_something()
end
```

in `my_library.lua`

```
function M.do_something()
  return resource.get_atlas(0)
end
```
The error will be reported coming from the call in the init instead of do_something which is where it actually originates from.

```
ERROR:SCRIPT: main/example.script:4: bad argument #1 to 'do_something' (hash or string expected expected, got number)
stack traceback:
  [C]:-1: in function do_someting
  main/example.script:4: in function <main/example.script:3>
```

# Repro case
[My Project.zip](https://github.com/defold/defold/files/10825281/My.Project.zip)

**Comment by britzl** [comment]
Tail call optimisations? @AGulev you've looked into tail call optimisations for the memory profiler. I guess what @Jerakin sees is the way tail calls are optimised?

**Comment by AGulev** [comment]
I don't think we can/want to do something with it
