### ISSUE TITLE
Support for gl_ClipDistance

### ISSUE THREAD

**Issue by Caue-Aron** [defold/defold#7433]
I'd like to have support for gl_ClipDistance, I'd use that for refraction and reflection, more specifically, to make water and mirrors like in this tutorial: https://www.youtube.com/watch?v=0NH9k4zTAqk&list=PLRIWtICgwaX23jiqVByUs0bqhnalNTNZh&index=3

I searched about gl_ClipDistance and Defold but I couldn't find anything about. If it is not implemented yet, I don't think it would be that hard to do, maybe a c++ src would do the trick, tho idk much about the engine src. If it is already possible to use this property, please tell me how.

**Comment by Jhonnyg** [comment]
ClipPlanes is not supported on all platforms, and as such requires a bit of thinking to implement. In any case, you can still implement the same thing in shaders by using a dot product with your custom planes, like this:

https://stackoverflow.com/questions/22628186/glclipplane-is-there-an-equivalent-in-webgl
