### ISSUE TITLE
Collection factories are broken in bundled builds

### ISSUE THREAD

**Issue by dapetcu21** [defold/defold#7434]
**Describe the bug (REQUIRED)**
1.4.3 broke collection factories for us. In bundled builds collectionfactory.create() returns an empty table and nothing gets spawned. When running from the editor this doesn’t happen.

**To Reproduce (REQUIRED)**
We don't have a minimal repro case, but our code looks like this:
```lua
  local instance = collectionfactory.create(self.factory_url, nil, nil, {
    [hash("character")] = {
      -- some stuff
    }
  })
  pprint(instance) -- Empty table
```

The collection factory is not loaded dynamically, nor does it have a dyamic prototype

**Defold version (REQUIRED):**
  - Version 1.4.3 (1.4.2 was fine)

**Platforms (REQUIRED):**
 - First noticed this on web, but then managed to repro on macOS too

**Comment by dapetcu21** [comment]
Oh! Here's more info:
```
ERROR:GAMEOBJECT: Could not create script component, out of resources.
ERROR:GAMESYS: Sprite could not be created since the buffer is full (8). Increase the 'sprite.max_count' value in [game.project](defold://open?path=/game.project)
ERROR:GAMESYS: Sprite could not be created since the buffer is full (8). Increase the 'sprite.max_count' value in [game.project](defold://open?path=/game.project)
ERROR:GAMESYS: Sprite could not be created since the buffer is full (8). Increase the 'sprite.max_count' value in [game.project](defold://open?path=/game.project)
ERROR:GAMESYS: Label could not be created since the buffer is full (0). Increase the 'label.max_count' value in [game.project](defold://open?path=/game.project)
```

**Comment by AGulev** [comment]
could you pls show how your setup looks like in the collection's outline?

If you use external cache when build with bob, could you pls try turn it off?

**Comment by dapetcu21** [comment]
Not using any special flags for bob. Actually bundled straight from the editor:
<img width="1508" alt="Screenshot 2023-03-02 at 17 29 30" src="https://user-images.githubusercontent.com/428060/222473233-a02b0af4-8b35-406e-9225-d36404fe1ec4.png">

**Comment by AGulev** [comment]
What is your `game.project` `label.max_count` and `sprite.max_count` ?

**Comment by dapetcu21** [comment]
Definitely not 0 and 8. Lemme check. 

```
[sprite]
max_count = 1024

[label]
max_count = 2048
```

**Comment by AGulev** [comment]
it is definitely a bug with components counter which were fully reworked in 1.4.3 to avoid issues with cache system.
But I can't reproduce it on my side (

**Comment by AGulev** [comment]
what do you use to spawn `level1.collection`? collectionproxy?

**Comment by dapetcu21** [comment]
Yeah, collectionproxy. It's a monarch scene

**Comment by dapetcu21** [comment]
Maybe it's because the collection factory is in characters.collection, which is dropped into level1.collection?

**Comment by AGulev** [comment]
I made the same hierarchy and it works fine for me, it should be something else... 
<img width="286" alt="image" src="https://user-images.githubusercontent.com/2209596/222484064-55567343-d07b-4e23-8714-0957460e4523.png">

**Comment by dapetcu21** [comment]
<img width="2032" alt="Screenshot 2023-03-02 at 18 09 46" src="https://user-images.githubusercontent.com/428060/222484812-d30d9ff0-4bf3-46da-9209-91084d9efdd9.png">

**Comment by AGulev** [comment]
still works for me (

**Comment by dapetcu21** [comment]
Want me to give you the project?

**Comment by AGulev** [comment]
That would be helpful, yes. Because for now I've no idea why it's happening (I understand where and don't understand why). You can share it with me privately here on github or using some other way

**Comment by dapetcu21** [comment]
Yup. Give me a bit to remove some stuff so it's easy to test

**Comment by AGulev** [comment]
Thank you!

**Comment by dapetcu21** [comment]
Sent! https://github.com/critique-gaming/rethink-collections-bug It should boot you straight to the problem area. In the editor it should work fine (after skipping tutorial, it should show a character), but when bundled it soft-locks when the first char should be shown.

**Comment by AGulev** [comment]
Great, thx! I'll take a look

**Comment by AGulev** [comment]
Now I can repo it, thx!
