### ISSUE TITLE
Bind texture to material via sampler name

### ISSUE THREAD

**Issue by Jhonnyg** [defold/defold#7440]
**Is your feature request related to a problem? Please describe (REQUIRED):**
We can right now only bind textures to material texture units, which has issues:

a) not intuitive
b) requires all units and samplers in the predicate to have the same order (and type) when overriding textures. 

**Describe the solution you'd like (REQUIRED):**
either/ and:

a) add support to render.enable_texture to take a sampler name as input 
b) add support to constant buffers for associating texture sampler uniforms with texture objects

**Describe alternatives you've considered (REQUIRED):**

**Additional context (OPTIONAL):**

**Comment by AGulev** [comment]
@Jhonnyg I think it's related to https://github.com/defold/defold/pull/8552 ?

**Comment by Jhonnyg** [comment]
Yes, except for the b) point above
