### ISSUE TITLE
Expose "playback rate" and "offset" to sprite component

### ISSUE THREAD

**Issue by ekharkunov-ms** [defold/defold#7449]
**Is your feature request related to a problem? Please describe (REQUIRED):**
I have a large game scene which contains animated non-interactive objects. I would like to customize playback rate and start offset of each sequence animation to differentiate object with same view.

**Describe the solution you'd like (REQUIRED):**
Expose parameters "playback rate" and "offset" to sprite component. Use values from it as initial values after component was created.
Also checkbox like "random offset" should be useful.

**Describe alternatives you've considered (REQUIRED):**
It's possible to set such parameters via script and `sprite.play_flipbook`

**Comment by AGulev** [comment]
Sounds reasonable, but we are not going to implement "random offset" checkbox (only values you can set using `sprite.play_flipbook`)
