### ISSUE TITLE
Resolving dependencies from GitLab fails with status code 406

### ISSUE THREAD

**Issue by haath** [defold/defold#7459]
**Describe the bug (REQUIRED)**
Resolving dependencies from GitLab fails with status code `406`.

In this context I'm referring to this public repo: https://gitlab.com/haath/dex

**To Reproduce (REQUIRED)**
1. Add the following project dependency: `https://gitlab.com/haath/dex/-/archive/master/dex-master.zip`
2. In the editor:
    1. Press `Fetch Libraries`
    2. Loading message appears on the bottom bar, and after a second or so disappears
    3. Nothing else happens, the dependency is not downloaded (no errors in console either)
3. With bob:
    1. Run `bob resolve`
    2. Get the following output:

```
Download archive(s)Downloading 1 archive(s)
 0: Downloading https://gitlab.com/haath/dex/-/archive/master/dex-master.zip
 0: Status 406: Failed to download https://gitlab.com/haath/dex/-/archive/master/dex-master.zip
 2147483647%Status 406: Failed to download https://gitlab.com/haath/dex/-/archive/master/dex-master.zip
Cause: java.lang.Exception
```

**Expected behavior (REQUIRED)**
The library should have been downloaded.

**Defold version (REQUIRED):**
  - Version 1.4.3

**Platforms (REQUIRED):**
 - Platforms: N/A
 - OS: Linux
 - Device: N/A

**Comment by britzl** [comment]
I've tried setting a User-Agent but it doesn't help. Still a 406.
