### ISSUE TITLE
Cant see code when i enter script file

### ISSUE THREAD

**Issue by MFWeezy** [defold/defold#7468]
Hi, im kind of new to defold and i might have an issue
### Expected behaviour

There should be shown code when i enter the script file.

### Actual behaviour

![image](https://user-images.githubusercontent.com/127887717/225111772-1b370041-ecb3-442b-a6e5-5e57d3b6fe03.png)

<hr/>

<table>
<tr><td>Build time</td><td>2023-03-08T09:11:54.507338</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>4d9c7c9c9ecc9b1849bd8c6352040ff3c723356f</td></tr>
<tr><td>Defold engine sha</td><td>b119e80c392eab4b620dbe9cc9eaea4c01a2da37</td></tr>
<tr><td>Defold version</td><td>1.4.3</td></tr>
<tr><td>GPU</td><td>GeForce GT 520M/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 NVIDIA 376.54</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
This might be a driver issue. What if you open a .collection file or .particlefx? Do these render anything? Could you please also check the editor log, maybe there are relevant warnings or errors (https://defold.com/manuals/editor/#editor-logs)?

**Comment by AGulev** [comment]
no answer from the reporter
