### ISSUE TITLE
Review tutorials and make sure we use all the latest features in tutorials

### ISSUE THREAD

**Issue by AGulev** [defold/defold#7473]
**Task (REQUIRED):**
We have tutorials and sample projects when we start Defold. Most of them are pretty old. We need to review them and make sure we use all the latest features there.

For example, runner tutorial should use fixed update to avoid fail down the floor when change window size etc

**Expected outcome (REQUIRED):**
Better and more modern examples

**Comment by britzl** [comment]
Tall order to go through it all! Do we know of specific things that are outdated?

Log of changes made:

* Change from play_animation message to sprite.play_flipbook() in https://github.com/defold/tutorial-war-battles/commit/90c8f5c07436a11eb2a0479a882d269496f84bb0

**Comment by AGulev** [comment]
> Tall order to go through it all! Do we know of specific things that are outdated?
> 
> Log of changes made:
> 
> * Change from play_animation message to sprite.play_flipbook() in [defold/tutorial-war-battles@90c8f5c](https://github.com/defold/tutorial-war-battles/commit/90c8f5c07436a11eb2a0479a882d269496f84bb0)

From the top of my head:
- fixed_update usage for games with physics
- vsync
