### ISSUE TITLE
Defold OpenJDK issue path change

### ISSUE THREAD

**Issue by ditari** [defold/defold#7476]
### Expected behaviour
Path changed
### Actual behaviour
Hangs
java.lang.OutOfMemoryError
### Steps to reproduce
Doing defold tutorial : Colorslides
Changing level path in main.collection

=
![Untitled1](https://user-images.githubusercontent.com/10735381/225794153-a676aa88-496a-47ad-ad17-876e08a56064.png)

<hr/>

<table>
<tr><td>Build time</td><td>2023-03-15T14:23:06.725137</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>c74fd32e9552d8b441eed52a39d98055d03f7bfe</td></tr>
<tr><td>Defold engine sha</td><td>b119e80c392eab4b620dbe9cc9eaea4c01a2da37</td></tr>
<tr><td>Defold version</td><td>1.4.3</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"c8ff182b435942e1888e49bb1720a44e"'>c8ff182b435942e1888e49bb1720a44e</a></td></tr>
<tr><td>GPU</td><td>Intel(R) UHD Graphics</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 - Build 31.0.101.3413</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 11</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
@ditari Can you reproduce this problem? How much memory do you have?

**Comment by ditari** [comment]
The problem isnt in memory. The only active program is Defold nothing else.

Steps to reproduce
Create new project > tutorial > colorslide
 it happens everytime I try to change path to level (idk forget)

Note that : when I try to run defold first time. windows defender give
warning this app is not safe to run.

Choose run anyways ( as admin)

It also gives notification when i start project if it allows open jdk (i
also tick the box screenshot in defold forum)


--The only solution works : install Defold through steam. No problem at
all.

So I guess windows defender either prohibit openjdk to work properly
because it doesnt register defold as legitimate program?

I try to download defold thrice still the same problem.

Its Windows 11

**Comment by matgis** [comment]
Hi! A fix for this issue was released earlier today. After changing some particular properties, like the Path property of certain types of object, the editor would hang for a long time and eventually produce an Out of Memory error.

Please make sure you're running the latest version of the editor, and feel free to reopen the issue if the problem persist!

**Comment by ditari** [comment]
Thank you!
