### ISSUE TITLE
Error in editor.spineext$SpineModelNode$behavior$spine_scene

### ISSUE THREAD

**Issue by itamarle-ma** [defold/defold#7482]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2023-02-10T13:06:06.593759</td></tr>
<tr><td>Defold channel</td><td>dev</td></tr>
<tr><td>Defold editor sha</td><td>b88a1755826bb9b50ab9066089b0f33e506b5007</td></tr>
<tr><td>Defold engine sha</td><td>b88a1755826bb9b50ab9066089b0f33e506b5007</td></tr>
<tr><td>Defold version</td><td>1.4.2</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"e76e72eda6744bf991cef3ff6f420e2a"'>e76e72eda6744bf991cef3ff6f420e2a</a></td></tr>
<tr><td>GPU</td><td>Apple M1 Max</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 83</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>13.2.1</td></tr>
<table>

**Comment by britzl** [comment]
```
editor.spineext$SpineModelNode$behavior$spine_scene in invokeStatic at line 860
clojure.lang.Var in invoke at line 393
internal.node.NodeImpl in produce_value at line 295
internal.node$pull_first_input_value in invokeStatic at line 1172
editor.game_object$EmbeddedComponent$behavior$build_resource$fn in invoke at line 217
internal.node$trace_expr$fn in invoke at line 38
internal.node$trace_expr in invokeStatic at line 38
editor.game_object$EmbeddedComponent$behavior$build_resource in invokeStatic at line 217
editor.game_object$EmbeddedComponent$behavior$build_resource in invoke at line 217
clojure.lang.Var in invoke at line 393
internal.node.NodeImpl in produce_value at line 295
```

**Comment by britzl** [comment]
This is a Spine related crash. Which version of the Spine extension are you using?

**Comment by AGulev** [comment]
no answer from the reporter
