### ISSUE TITLE
Defold hangs when replacing a link to a script

### ISSUE THREAD

**Issue by khameleonium** [defold/defold#7490]
### Steps to reproduce

- I create a new empty project in Defold
- I copy a folder from another project that contains a script, atlas, sprite and material
- I copy the GO object from another project to main.collection.
- Defold swears that the sprite refers to a non-existent atlas (it's logical, because in another project it was in a different folder).
- I change the link to the atlas - ok.
- Then I change the path to the script and... Everything. Defold freezes up

<hr/>

<table>
<tr><td>Build time</td><td>2023-03-15T14:23:06.725137</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>c74fd32e9552d8b441eed52a39d98055d03f7bfe</td></tr>
<tr><td>Defold engine sha</td><td>b119e80c392eab4b620dbe9cc9eaea4c01a2da37</td></tr>
<tr><td>Defold version</td><td>1.4.3</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GTX 670/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 474.14</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by matgis** [comment]
Thanks for reporting! A fix for this issue was released earlier today. Please make sure you're running the latest version of the editor, and feel free to reopen the issue if the problem persist!
