### ISSUE TITLE
Dragging multiple files in the file browser instantly shuts down Defold

### ISSUE THREAD

**Issue by totebo** [defold/defold#7507]
**Describe the bug (REQUIRED)**
The editor crashes when multiple files are dragged in the file browser.

**To Reproduce (REQUIRED)**
Select more than one file and start dragging them.

**Defold version (REQUIRED):**
1.4.3

**Platforms (REQUIRED):**
macOS Bug Sur 11.6

**Logs (OPTIONAL):**
[crashlog.txt](https://github.com/defold/defold/files/11068832/crashlog.txt)

**Workaround (OPTIONAL):**
Drag one file at a time.

**Screenshots (OPTIONAL):**
Video:
https://drive.google.com/file/d/1LVbDE3fCyJF00mNnz4QTiwaFaytJDCtl/view?usp=sharing

**Comment by AGulev** [comment]
Duplicate https://github.com/defold/defold/issues/6738
