### ISSUE TITLE
Bug with `go.get_world_position()` and game state

### ISSUE THREAD

**Issue by AGulev** [defold/defold#7522]
**Describe the bug (REQUIRED)**
`go.get_world_position()` sometimes return right position in the `init()` function, but sometimes returns local. It makes it hard to understand the logic behind that.

**To Reproduce (REQUIRED)**
1. Open the test project
2. Run
3. See that in the logs world positions are equal to local positions
4. Close the project
5. open `Example_fixed.collection`
6. Move all flags outside of the its objects:
<img width="237" alt="image" src="https://user-images.githubusercontent.com/2209596/229080393-15412f0a-9f26-450a-a728-9ae25640c265.png">

7. run the game and see that world positions are fine now (no equal to the local position)
8. Close the project and open again
9. Run the project and check logs
10. World positions are equal to local positions again

**Expected behavior (REQUIRED)**
Behavior should be consistent.

_Perfect case:_
World position should be available from the `init()` function

But this case is about consistency. User don't understand what's going on and why behavior changes after hierarhy changes and the editor restart.

**Defold version (REQUIRED):**
  - Version 1.4.4

**Platforms (REQUIRED):**
 - Platforms: Mac, Windows

**Minimal repro case project (OPTIONAL):**
[Collection_duplicate 2.zip](https://github.com/defold/defold/files/11120289/Collection_duplicate.2.zip)

**Workaround (OPTIONAL):**
Use timer for getting world position:
```
timer.delay(0.01, false, function()
  -- get world position here
 end)

```

**Comment by Lariay** [comment]
Problem can be resolved partially when you duplicate collection and delete all go that you need and re-create they in duplicated collection.
Then all "go" from this duplicated collection send me right world_position.
