### ISSUE TITLE
Can't hide current window:  M1 Mac Pro 14 MacOS 13.3 Defold 1.4.4

### ISSUE THREAD

**Issue by urmarc443** [defold/defold#7528]
### Expected behavior
Pressing the <command> + h key should hide the current windows to the background.

### Actual behavior
Pressing the <command> + h key launches the Help > About window. 

### Steps to reproduce
Launch defold
create project [in my case the tutorial {example} project "War battles tutorial"]
when the editor finishes launching, press <command> + h
<hr/>

<table>
<tr><td>Build time</td><td>2023-03-31T16:41:03.171182</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>36f9bd22f8a5d442728986d23a96794004ed0640</td></tr>
<tr><td>Defold engine sha</td><td>f5e114aaebe25c5242db5f0066af2f5189c09f99</td></tr>
<tr><td>Defold version</td><td>1.4.4</td></tr>
<tr><td>GPU</td><td>Apple M1 Pro</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 83.1</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>13.3</td></tr>
<table>

**Comment by AGulev** [comment]
should be easy to fix https://stackoverflow.com/questions/55068825/handling-commandh-programmatically-in-mac-os
