### ISSUE TITLE
The shader doesn't compile if it doesn't contain word "varying" (1.4.4)

### ISSUE THREAD

**Issue by Morgerion** [defold/defold#7531]
The any fragment shader doesn't compile if it doesn't contain word "varying":

![image](https://user-images.githubusercontent.com/7888071/229310550-eb1bce33-4016-461f-b4c3-2fc1d808a4b6.png)

**Defold version:**
  - Version 1.4.4

**Platforms:**
 - Platforms: Windows, macOS

**Minimal repro case project:**
[-.zip](https://github.com/defold/defold/files/11130452/-.zip)
Insert this material and shader into any project.

**Comment by Jhonnyg** [comment]
This is not related to varyings. Something goes wrong with the ES3 transform when a fragment shader starts with a comment and no "real" line during post-patching of gl_FragColor. For now I've pushed a quick-fix (https://github.com/defold/defold/commit/4aa65cdc1a98aafc885cc9c1e7cb0ec359ee9b87) that solves this. Closing the issue for now
