### ISSUE TITLE
Improve editor assets unpacking

### ISSUE THREAD

**Issue by vlaaad** [defold/defold#7543]
**Task (REQUIRED):**
Currently, we unpack files on every editor start and then delete them on the editor shutdown. We should only unpack once per editor (engine?) SHA, while also making sure to not pollute the hard drive too much.

**Expected outcome (REQUIRED):**
We generally unpack assets once per editor or engine update.

**Comment by vlaaad** [comment]
This is not very important. Only affects startup time. Hard drive space will become an issue only if we have e.g. a hundred instances of the editor running at the same time.

**Comment by vlaaad** [comment]
This is actually important because macOS clears tmp folders every couple of days, which requires editor restarts!

**Comment by ZimbaMontagne** [comment]
It is also important for a situation I am in where my anti virus keeps deleting files in these temp folders making me unable to build the project.  I have to whitelist these files each time I open the editor or to disable my antivirus.  Which is a huge negative for me when working with defold.

Specifically the /x86_64-win32/bin/luajit-32 file is causing me issues.

**Comment by astrochili** [comment]
Perhaps the reason for the 'Allow incoming connections for dmengine?' message on macOS is the same.

And then there are many rules for dmengine in the system settings:

![](https://github.com/defold/defold/assets/4752473/e5de2b07-2b27-4dde-90ab-8f7291d5861c])

**Comment by fabtjar** [comment]
Many rules for me on Windows too.
![image](https://github.com/defold/defold/assets/42767280/5f85e8e1-0db8-46a6-a180-bc6b52256d66)
