### ISSUE TITLE
Functionality to get texture size of atlases

### ISSUE THREAD

**Issue by Sublustris** [defold/defold#7564]
Is it possible to add some functionality to get texture size of atlas?

The problem is: Sometimes when working with shaders it is necessary to know the exact size of the atlas texture for calculations. For example, to draw outline of the same thickness for sprites located in different atlases. As long as one atlas is used, there are no problems, but if there are several atlases, and they are of different sizes (for example, 2048 * 2048 and 1024 * 1024), the algorithms will draw outline of different thicknesses.

**Comment by britzl** [comment]
Discussed here: https://forum.defold.com/t/texture-size-for-atlas-properties/73077

**Comment by JCash** [comment]
One idea I have is to have it as a uniform one can add to the material (just like matrices etc).
E.g. `TEXTURE_SIZE_0` or something, and it may be something like `vec3(width, height, 1/width, 1/height)` etc.
A proper design may reveal more insightful additions :)

**Comment by AGulev** [comment]
Another way to go: https://github.com/defold/defold/pull/7362 (not sure if we want to go this way)
