### ISSUE TITLE
File -> Synchronize... triggers clojure.lang.ArityException 

### ISSUE THREAD

**Issue by bar-bar-bar-bar-bar** [defold/defold#7574]
### Expected behaviour
_Get remote changes_ window to open without errors
### Actual behaviour
Before the window opening, it shows an error window with the following message:
`clojure.lang.ArityException: Wrong number of args (3) passed to: editor.ui/show-dialog-stage/fn--15185`

### Steps to reproduce
_File_ -> _Synchronize..._
<hr/>

<table>
<tr><td>Build time</td><td>2023-04-14T08:23:51.430579</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>56543226ab58fa31656fd6e5748c2d37c064a0d7</td></tr>
<tr><td>Defold engine sha</td><td>f5e114aaebe25c5242db5f0066af2f5189c09f99</td></tr>
<tr><td>Defold version</td><td>1.4.4</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"71aaa1335ac04aa29ca649d366a02783"'>71aaa1335ac04aa29ca649d366a02783</a></td></tr>
<tr><td>GPU</td><td>Apple M1</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 83</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>13.2.1</td></tr>
<table>

**Comment by britzl** [comment]
Fixed via https://github.com/defold/defold/commit/9819fb3293da0b08227ef01827816866ad6011f3

New build will be available in 30 minutes
