### ISSUE TITLE
error while bundle Android Application

### ISSUE THREAD

**Issue by cinelmada** [defold/defold#7575]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2023-04-14T08:23:51.430579</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>56543226ab58fa31656fd6e5748c2d37c064a0d7</td></tr>
<tr><td>Defold engine sha</td><td>f5e114aaebe25c5242db5f0066af2f5189c09f99</td></tr>
<tr><td>Defold version</td><td>1.4.4</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"a8517e42c34347d7a8dd32acd2202790"'>a8517e42c34347d7a8dd32acd2202790</a></td></tr>
<tr><td>GPU</td><td>Intel(R) UHD Graphics 617</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-20.2.50</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>13.2.1</td></tr>
<table>

**Comment by britzl** [comment]
Fixed via https://github.com/defold/defold/commit/9819fb3293da0b08227ef01827816866ad6011f3

New build will be available in 30 minutes
