### ISSUE TITLE
Error thrown when opening preferences preferences

### ISSUE THREAD

**Issue by bryanrieger** [defold/defold#7577]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2023-04-14T17:22:27.911583</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>635ab96876a26b0eaafbacd25820e59e7a1a1223</td></tr>
<tr><td>Defold engine sha</td><td>f5e114aaebe25c5242db5f0066af2f5189c09f99</td></tr>
<tr><td>Defold version</td><td>1.4.4</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"e6420b5e8d014934965b1d43e39e463d"'>e6420b5e8d014934965b1d43e39e463d</a></td></tr>
<tr><td>GPU</td><td>Apple M1 Pro</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 83.1</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>13.3.1</td></tr>
<table>

**Comment by britzl** [comment]
Fixed via https://github.com/defold/defold/commit/9819fb3293da0b08227ef01827816866ad6011f3

New build will be available in 30 minutes
