### ISSUE TITLE
IDE: Exclude binary files from the search.

### ISSUE THREAD

**Issue by aglitchman** [defold/defold#7586]
**Is your feature request related to a problem? Please describe (REQUIRED):**
We have more and more files in the project (3400 files, 180 megabytes) and the Ctrl/Cmd+F project search function is getting slower and slower. Why? The IDE seems to search through all files, even binary ones.

For example, I entered "IHDR" (PNG header) and the IDE found this text in GLBs:

![image](https://user-images.githubusercontent.com/193258/232795210-0fafaceb-6404-4790-afca-690764b105f0.png)

**Describe the solution you'd like (REQUIRED):**
Improve the detection of binary files or exclude ".glb" from the search.

**Comment by matgis** [comment]
These files are not supposed to be searchable. I suspect we're creating PlaceholderResourceNodes for them but somehow mis-detect the file contents as text-based and they end up as searchable files.
