### ISSUE TITLE
No audio on iPhone 13 mini on HTML5

### ISSUE THREAD

**Issue by subsoap** [defold/defold#7589]
There is no audio on the iPhone 13 mini device in Safari on current engine HTML5 builds / up to date iOS.

Default project playing a simple .ogg

**Comment by subsoap** [comment]
No other reports of not working at the moment just this one. I don't have the device but a user testing something important reported no audio / they were interacting with it / there was nothing special about the test just default project with a sound that plays on action.pressed (which now that I think of it maybe that's related).

**Comment by aglitchman** [comment]
> There is no audio on the iPhone 13 mini device in Safari on current engine HTML5 builds / up to date iOS.

We have an iPhone 13 mini and everything works fine. Could you please send a link to your demo? Or maybe it's related to the issue with iframes? https://github.com/defold/defold/issues/7557

**Comment by subsoap** [comment]
I will get more info from tester to confirm.

**Comment by subsoap** [comment]
After more testing user was unable to reproduce/audio suddenly working.

/shrug
