### ISSUE TITLE
Get a list of all available animations in an atlas

### ISSUE THREAD

**Issue by gianmichelemariani** [defold/defold#7615]
I'm building a point and click adventure framework that has an in-game editor.

At the moment to get a list of available animations I have to either manually create a list or possibly hook up an editor script to parse the file and generate that pre-build.

This feels a bit convoluted for what could probably be a simple api that returns the list of available animations.

**Comment by Jhonnyg** [comment]
I think this does what you want: https://defold.com/ref/beta/resource/#resource.get_atlas:path

**Comment by gianmichelemariani** [comment]
Yes! i completely missed that!
