### ISSUE TITLE
Handle multi material editing for models

### ISSUE THREAD

**Issue by JCash** [defold/defold#7619]
The current model component can only specify one material, but we need to expose all the material names from the model data (e.g. .gltf).

* Edit+Save the "material name":"material resource" mappings
* Migrate old content from one material to many
* Render each sub mesh with the correct assigned material

Required for https://github.com/defold/defold/pull/7380
Design (updated with related info at the bottom): https://docs.google.com/document/d/1NK5CRc7019Q2R1BgSgoDqvvJWwlSXxe8Ke9P-teKTk0/edit?usp=sharing

**Comment by Jhonnyg** [comment]
Feature added by https://github.com/defold/defold/commit/f86b566156667ff15a3c6cced89824771c5d7878
