### ISSUE TITLE
First build for android with a warning

### ISSUE THREAD

**Issue by osov** [defold/defold#7621]
**Describe the bug (REQUIRED)**
when building for android, an error occurs. Reassembly (Rebuild) helps to assemble without error.
Is this a bug or how can I properly avoid this behaviour?
`
warning: [options] bootstrap class path not set in conjunction with -source 8
Note: /tmp/job6088555732725938955/upload/extension-yandex-ads/src/java/com/defold/extension/ExtensionYandexAds.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /tmp/job6088555732725938955/upload/review/src/android/java/com/defold/review/Review.java uses or overrides a deprecated API.
For the full log, see D:\Defold\projects\Spider\app\build\armv7-android\log.txt
`

**To Reproduce (REQUIRED)**
Project -> Bundle -> Android

**Expected behavior (REQUIRED)**
no mistakes

**Defold version (REQUIRED):**
  - 1.4.5

**Platforms (REQUIRED):**
 Windows 10

**Logs 
[log.txt](https://github.com/defold/defold/files/11364036/log.txt)

extension-yandex-ads url:
https://github.com/osov/defold-yandex-easy-monetization/archive/refs/heads/main.zip

**Comment by britzl** [comment]
@osov you should be able to add the `-Xlint:deprecation` flag to the `javaFlags` of your app manifest to get additional info on the deprecated API:

```
platforms:
    android:
        context:
            javaFlags: ['-Xlint:deprecation']
```

**Comment by osov** [comment]
I get an error:
/extension-app-metrica/ext.manifest
	Error in 'extension-app-metrica/ext.manifest': Invalid flag - 'javaFlags': '-Xlint:deprecation'

**Comment by AGulev** [comment]
@osov Con you reproduce it now when we use async-build by default?

**Comment by AGulev** [comment]
@osov 
You didn't answer my question, I'm closing this ticket. Let me know if it's still an issue for you
