### ISSUE TITLE
Small memory leak in json_initialize_config

### ISSUE THREAD

**Issue by AGulev** [defold/defold#7685]
it is leaking 1 Kb for each call
<img width="1638" alt="image" src="https://github.com/defold/defold/assets/2209596/8c9d44ce-8aef-453c-ae4a-98120e2b17f9">

**Comment by vbif1** [comment]
Why engine recreate config on every decode and encode calls? Isn't better to have it always in the memory (1kb looks small)? or maybe initialize once on first call?

**Comment by osov** [comment]
I created a game server and noticed that almost all the RAM was used up in a day :(. I spent the whole day looking for leaks, diagnostic tools say that there are no leaks at the Lua level.
Then I started looking for the problem further and realized that the memory is occupied by the json.decode method, a minimal code example is here:

```
  local str = json.encode({msga = {all = true, text = ""}})
        timer.delay(0.01,  true, function()
                    local i = 0
                    while i < 10000 do
                        json.decode(str)
                        i = i + 1
                    end
            end)
```

**Comment by vbif1** [comment]
Is this one line enough? json_throw_parse_error make long jump and doesnt free cfg buffer (but free json.tmp). And I'm not sure about encode function - is it use the very same buffer for output string? Is this buffer deallocated later by lua?
