### ISSUE TITLE
HTML5: `liveupdate.store_resource` returns "invalid resource" for any resource

### ISSUE THREAD

**Issue by aglitchman** [defold/defold#7688]
**Describe the bug (REQUIRED)**
The `liveupdate.store_resource` function doesn't want to store any resource, i.e. it always returns the error `Verification of liveupdate resource failed for expected hash for resource ...`.

The bug occurs only in the version 1.4.6. The demo project works well in 1.4.5 and older.

**To Reproduce (REQUIRED)**
1. Download or clone https://github.com/indiesoftby/defold-liveupdate-reszip
2. Build the demo `./dev_build_web.sh`.
3. Open the demo in a browser.

**Expected behavior (REQUIRED)**

**Defold version (REQUIRED):**
  - Version: 1.4.6

**Platforms (REQUIRED):**
 - Platforms: HTML5

**Workaround (OPTIONAL):**
The fix is https://github.com/defold/defold/pull/7687

**Comment by JCash** [comment]
Thanks for the report! The fix is now merge into dev!
