### ISSUE TITLE
Editor crashes to desktop when loading a non-editable collection or game object with an embedded spine component referring to an out-of-date spinejson file

### ISSUE THREAD

**Issue by matgis** [defold/defold#7689]
For non-editable collections and game objects, the `:sanitize-fn` decodes embedded strings into map representations of the embedded game objects and components. This process can fail if a plugin such as `extension-spine` throws an exception as it reads the embedded string. In this case, the `:sanitize-fn` gives up and returns the data in its non-sanitized form. Normally this would cause the `:load-fn` to throw an exception, but in the case of non-editable resources, the read protobuf map is simply assigned to a property. This eventually trips an assert at an inopportune time, which in our case terminates the editor process in the middle of loading.

**Comment by AGulev** [comment]
I see that PR has been merged, but the ticket is still opened for some reason.
I close it
