### ISSUE TITLE
Wrong dependency tree with default script properties

### ISSUE THREAD

**Issue by Insality** [defold/defold#7707]
**Describe the bug (REQUIRED)**
If we have the default script property, it always included to the build even the all instances are overridden for other resource.

**To Reproduce (REQUIRED)**
1. Set the default resource script property like `go.property("font", resource.font("/main/cherry_font.font"))`
2. Override it to another one in attached GO script
3. Build project with build report
4. Observe: the first default font also included in build even there is no any links on it

**Expected behavior (REQUIRED)**
The font without links is not included to the build

**Defold version (REQUIRED):**
Tested on Defold 1.4.4

**Platforms (REQUIRED):**
Any

**Minimal repro case project (OPTIONAL):**
[dependency-tree-issue.zip](https://github.com/defold/defold/files/11611674/dependency-tree-issue.zip)

**Workaround (OPTIONAL):**
Set default links to empty string: ``go.property("font", resource.font(""))`

**Screenshots (OPTIONAL):**
<img width="1211" alt="Screenshot 2023-05-31 at 13 03 11" src="https://github.com/defold/defold/assets/3294627/f4ae0df8-1243-4600-9fad-48eb92960927">

**Comment by britzl** [comment]
We talked about this and while we agree that it is slightly confusing, we do not really think it should be considered a bug. It's a fairly specific edge case where the developer might prefer one or the other. 

I'm sure there are use cases where the developer would like to switch back to the default font at runtime. If we do not bundle the default font then that would not be possible.

If you know that you have a property that you will always override then I think your suggestion to set an empty string as default value is a valid workaround.

**Comment by britzl** [comment]
By design.
