### ISSUE TITLE
Add fold and unfold all nodes action in Editor outline

### ISSUE THREAD

**Issue by Insality** [defold/defold#7710]
**Is your feature request related to a problem? Please describe (REQUIRED):**
A lot of time I've spend for manually click fold or unfold parent nodes in GUI outline.

My usecases:
- click through all nodes to set layers
- select all nodes for several editor scripts
- check nodes for attributes

**Describe the solution you'd like (REQUIRED):**
Action in some menu with fold/unfold outline

**Describe alternatives you've considered (REQUIRED):**
Manually do this :D

**Comment by AGulev** [comment]
Do you know that you can use Alt (Option) + Click to the arrow to fold/unfold all?
https://github.com/defold/defold/assets/2209596/9062bfdd-8d2e-411e-99ac-d534a94baa41

**Comment by Insality** [comment]
waaaaaaaa, I didn't know about this one
Amazing, thanks so much :)
