### ISSUE TITLE
Defold crushes on drug and drop

### ISSUE THREAD

**Issue by AlehZakharau** [defold/defold#7718]
### Expected behaviour
I tried to select two GameObjects and drag and drop them into a new folder

### Actual behaviour
when I start to move the objects, the engine crashes.

### Steps to reproduce
1. Select two or more objects.
2. Try to drag and drop them.

One object drag and drop works fine.
<hr/>

<table>
<tr><td>Build time</td><td>2023-05-30T13:44:55.205125</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>b435988787840dbcccd0f4d717fca20d6c1a1a7f</td></tr>
<tr><td>Defold engine sha</td><td>cb8b34230bd42a5e0b68c12441657f06485562a6</td></tr>
<tr><td>Defold version</td><td>1.4.6</td></tr>
<tr><td>GPU</td><td>Apple M2</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 83.1</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>13.3.1</td></tr>
<table>

**Comment by vlaaad** [comment]
Thanks for the report! It is a known issue with our UI framework (JavaFX), you can track our progress here: #6738
