### ISSUE TITLE
Collapse and expand function

### ISSUE THREAD

**Issue by ainonovo** [defold/defold#7730]
please make it possible to collapse and expand the internal code in function in the editor

I have a lot of lines and it's not very convenient to scroll through

**Comment by AGulev** [comment]
duplicate of https://github.com/defold/defold/issues/6207

**Comment by ainonovo** [comment]
Так вы сделаете или нет? очень бы хотелось. много строк. неудобно скролить

**Comment by AGulev** [comment]
> Так вы сделаете или нет? очень бы хотелось. много строк. неудобно скролить

It's not planned at the moment.
But having a few issues about the same do not help here

**Comment by ainonovo** [comment]
very bad (
