### ISSUE TITLE
GUI function to return table of IDs of a node and its children

### ISSUE THREAD

**Issue by dri-richard** [defold/defold#7736]
**Is your feature request related to a problem?**
gui.clone_tree() returns a table in which the keys are node IDs, making it easy to work with those nodes.
Our game does things like this (much code deleted - a pet is more than a head and body), often to display multiple similar items in a grid.

```
function M.draw_pet(pet_type, template)
	local pet_clone = gui.clone_tree(template)

	local pet_head = pet_clone["pet_head"]
	local pet_body = pet_clone["pet_body"]
	-- further code for other body parts omitted

	gui.set_texture(pet_head, "pet_heads")
	gui.set_texture(pet_body, "pet_bodies")
	
	local pieces = pet_data.get_parts(pet_type)

	gui.play_flipbook(pet_head, pieces.head.sprite)
	gui.play_flipbook(pet_body, pieces.body.sprite)

	gui.set_parent(pet_head, pet_clone["pet_spine/Head"])
	gui.set_parent(pet_body, pet_clone["pet_spine/Body"])

	local part_offsets = pet_data.get_part_offsets(pet_type)

	if part_offsets ~= nil then 
		gui.set_position(pet_head, vmath.vector3(part_offsets.head.x, part_offsets.head.y, part_offsets.head.z))
		gui.set_position(pet_body, vmath.vector3(part_offsets.body.x, part_offsets.body.y, part_offsets.body.z))
	end

```
We didn't initially use GUI templates, and instead cloned an embedded node hierarchy, and we have a bit of a mix of usage now, but it's easy enough to add a prefix parameter to deal with how cloned node IDs include the template id:
```
function M.draw_pet(pet_type, template, prefix)
	local pet_clone = gui.clone_tree(template)

	local pet_head = pet_clone[prefix .. "pet_head"]
	local pet_body = pet_clone[prefix .. "pet_body"]
```

The problem is that sometimes we only have one instance, and it isn't necessary to clone the tree, we just want to configure the hierarchy, whether that's a template or embedded, and the code is subtly different:

```
	local pet_head = gui.get_node(prefix .. "/pet_head")
	local pet_body = gui.get_node(prefix .. "/pet_body")

	gui.set_texture(pet_head, "pet_heads")
	gui.set_texture(pet_body, "pet_bodies")

	local pieces = pet_data.get_parts(pet_type)

	gui.play_flipbook(pet_head, pieces.head.sprite)
	gui.play_flipbook(pet_body, pieces.body.sprite)

	gui.set_parent(pet_head, gui.get_node(prefix .. "/adult_pet_spine/Head"))
	gui.set_parent(pet_body, gui.get_node(prefix .. "/adult_pet_spine/Body"))
```

We have code to render many types of object in GUI - pets, seeds , ingredients, collectibles, coins etc. and having two similar code paths is inconvenient to maintain.

**Describe the solution you'd like**
A GUI function that returns information about a node and its children in a table format similar to that of clone_tree().

**Describe alternatives you've considered**
Manually constructing the table.

**Comment by britzl** [comment]
> A GUI function that returns information about a node and its children in a table format similar to that of clone_tree().

It doesn't feel like it would be that complicated to share some code with `clone_tree()` and add a `get_tree()` function.
