### ISSUE TITLE
Editor scripts: Add a function to get a version and SHA of the Defold editor

### ISSUE THREAD

**Issue by Filazapovich** [defold/defold#7741]
**Is your feature request related to a problem? Please describe (REQUIRED):**
Sometimes users may open project in not supported version of the Editor

**Describe the solution you'd like (REQUIRED):**
We want to add check in the editor hook `on_build_started` to compare supported version with already used

**Describe alternatives you've considered (REQUIRED):**
I know no alternatives

**Comment by vlaaad** [comment]
Do you mean the version and SHA of *the engine* used inside this version of the editor?
