### ISSUE TITLE
9-Slice sprites render incorrectly when texture is "sideways" in atlas

### ISSUE THREAD

**Issue by swajj** [defold/defold#7751]
**Describe the bug (REQUIRED)**
When Defold stores an image "sideways" in the atlas AND that image is used for a 9-Slice sprite, the texture is rendered rotated 180 degrees and with visual artifacts.

**To Reproduce (REQUIRED)**
1. Add images to an atlas until one of them is stored sideways in the combined atlas texture.
2. Add a sprite using the "sideways" image.
3. Set the sprite to "manual" sizing and add some appropriate values for the 9-Slice settings.
4. Observe sprite looks correct in editor.
5. Build/run
6. Observe that the sprite is rendered incorrectly in game. (rotated 180 degrees and with visual artifacts)

**Expected behavior (REQUIRED)**
6. Sprite is rendered correctly and matching editor view e.g. 9-Slice settings are respected without causing visual artifacts and incorrect orientation.

**Defold version (REQUIRED):**
  - Version 1.4.6

**Platforms (REQUIRED):**
 - Platforms: In-editor build/run, Windows, HTML5 (did not test further)
 - OS: Windows 11
 - Device: Desktop PC

**Minimal repro case project (OPTIONAL):**
[Sprite9SliceBug.zip](https://github.com/defold/defold/files/11779674/Sprite9SliceBug.zip)

**Workaround (OPTIONAL):**
Add and remove images from atlas or use a new atlas, until the relevant images are stored in their defaut orientation.

**Screenshots (OPTIONAL):**
<img width="559" alt="SidewaysAtlas" src="https://github.com/defold/defold/assets/133168946/f4aff1b5-ba53-4e22-9eee-7a55e46d44d8">
<img width="884" alt="Slice9Sprite" src="https://github.com/defold/defold/assets/133168946/89bb3df6-877d-464d-afcf-cec93e928060">
<img width="749" alt="InvertedCorruptedSprite" src="https://github.com/defold/defold/assets/133168946/4510e57e-1ace-4045-8759-390644e7297e">

**Comment by britzl** [comment]
I'm fairly confident that this issue was resolved as a result of this PR: https://github.com/defold/defold/pull/7694

Please try the 1.4.7 beta: https://forum.defold.com/t/defold-1-4-7-beta/73421
