### ISSUE TITLE
Information about full dependency graph

### ISSUE THREAD

**Issue by ekharkunov-ms** [defold/defold#7753]
**Is your feature request related to a problem? Please describe (REQUIRED):**
Some information about asset's dependencies exist in **liveupdate.game.dmanifest**. But that information exists only for **collectionproxyc** assets. It would be great if full dependency graph can be created.
Use case for example:
We have a bunch of game objects (for example, 10 objects) inside the project. That game objects unite inside one collection (for example, "**special.collection**"). We would like to exclude that collection from main bundle and use collection proxy for that. Also we have factory component with "**dynamic prototype**" checkbox On. After all in the game we need to spawn 3 of 10 objects. So during the client build we need to determine what compiled assets exactly need to download to spawn one game object.

**Describe the solution you'd like (REQUIRED):**
Bob generate separate file with full dependency graph between assets. That file can be used in further build pipeline.

**Describe alternatives you've considered (REQUIRED):**
Hack Bob somehow =)

**Comment by britzl** [comment]
> @britzl Hi! I saw that PR is under review. Is it any chance to include changes in the nearest engine release?

Sure, we're doing a final review now.
