### ISSUE TITLE
"Recent Files" does not display the underscore symbol

### ISSUE THREAD

**Issue by aglitchman** [defold/defold#7759]
**Describe the bug (REQUIRED)**
For some reason, 1 underscore character is missing in each filename in the "Recent Files" menu. For example, "__preview.collection" should have 2 underscores.

![image](https://github.com/defold/defold/assets/193258/e1c0fe4c-01ce-48fa-b822-ffc7e33d923f)

**To Reproduce (REQUIRED)**
1. Create any file with underscore in its name.
2. Open it.
3. Open the Recent Files menu.
4. See the bug.

**Defold version (REQUIRED):**
![image](https://github.com/defold/defold/assets/193258/693a02e7-143d-4036-a75a-09f41835e64f)

**Platforms (REQUIRED):**
 - Platforms: Windows

**Comment by Creperi** [comment]
:filter-fn #(fuzzy-choices/filter-options (comp resource/proj-path first)%1)}))) Maybe this line 85 in recent_files.clj?

**Comment by matgis** [comment]
**Technical notes:**
This happens because JavaFX parses underscore-prefixed characters as Menu mnemonics, and we need to escape them to get them to show up as underscores.

**Comment by quangson91** [comment]
@matgis I tried to fix at #8107
