### ISSUE TITLE
Calculate numeric input in the editor

### ISSUE THREAD

**Issue by fabtjar** [defold/defold#7816]
I'd like to be able to use calculations for numeric input in the editor.

![image](https://github.com/defold/defold/assets/42767280/7b9ef51b-37f9-48b9-8d78-31e0b2d81989)

So with the image above I'd like to input `1920*3/4` and it evaluate to `1440` when I press enter or focus leaves the input box.

It would be great to work with more complicated calculations like `(100-20)*(4+3/5)`.

**Bonus idea:** It would be good if it remembers the calculation so if I click on the input `1440` from my first example then it changes back to the calculation `1920*3/4`. This seems a lot harder to implement but could be super helpful.

**Comment by matgis** [comment]
Note: You can do simple expressions like 1920*3 already, but `1920*3/4` or anything involving multiple terms doesn't work.

**Comment by quangson91** [comment]
@matgis 
Is that ok to use external lib like: https://github.com/fasseg/exp4j

as I checked it support pretty well.
But some unit-test maybe failed.

How do you think?

**Comment by britzl** [comment]
I think it is perfectly fine to use a library, unless it bloats the editor too much. The exp4j jar is 45kb. There is also Javaluator with a jar size of around 25kb.

https://www.baeldung.com/java-evaluate-math-expression-string

Let's see what @matgis thinks.

**Comment by matgis** [comment]
I’m not opposed to using a tiny self-contained library in our `field-expression` module as long as it is compatible with our license.

**Comment by quangson91** [comment]
@britzl @matgis 
I got it.
So I just create a PR which is used exp4j to evaluate.
Now in the input field we can input more complex math string.
