### ISSUE TITLE
The mouse key continues to remain pressed when the focus is lost HTML5

### ISSUE THREAD

**Issue by vokaimoh** [defold/defold#7817]
If you connect the dots in my game and intentionally switch focus, for example through a keyboard shortcut on the windows keyboard (alt + tab), and then release the mouse button, then when you return to the game, the mouse button will continue to remain pressed.

Defold game engine version 1.4.7.
Yandex browser version 23.7.0.2534 (64-bit).
Platform: HTML5, OS: Windows 10, Device: Laptop.

Attached a snippet of the game code:
![image](https://github.com/defold/defold/assets/133861101/7212f3b1-2d51-4ddf-a239-1089e89aea0a)

Uploaded the build to the hosting in order to be able to reproduce the bug: https://buildsettings.ru/vkgames/connect-bug/

Link to Yandex Games: https://yandex.ru/games/app/213758?draft=true&lang=ru

Examples of bug playback (the first video in the Yandex Browser, the second video in Google Chrome):

https://github.com/defold/defold/assets/133861101/202a92e9-a02b-47a9-b759-d3eae297d55e

https://github.com/defold/defold/assets/133861101/37b05a69-d186-4cb4-82db-ee545aebc962

**Comment by britzl** [comment]
I think the problem is that we do not get any events when the focus is lost so we can't know if the mouse button is pressed or not when focus is regained. We could perhaps always clear input when focus is lost?

**Comment by britzl** [comment]
> @britzl maybe we should do the same we did for #3186 ?

Yes, I think we should!

**Comment by britzl** [comment]
I'm testing on macOS and it seems like I'm getting a mouse button release event in Safari, Firefox and Chrome. Perhaps this is a problem only on Windows?

**Comment by Vokaimoh** [comment]
> I'm testing on macOS and it seems like I'm getting a mouse button release event in Safari, Firefox and Chrome. Perhaps this is a problem only on Windows?

Unfortunately, I don't have a macOS device to test this, but the problem is still relevant on Windows. P.S. initially, I learned about the bug from a player using macOS, so maybe the problem can be reproduced there.
