### ISSUE TITLE
1.4.8 App not opening on macOS High Sierra 10.13.6

### ISSUE THREAD

**Issue by usbhell** [defold/defold#7842]
**Describe the bug (REQUIRED)**
launching version 1.4.8 on this older mac results in it closing immediately, 1.4.7 runs with no issue. running from the terminal gives the following output

INFO:TOOLS: Launcher version 504de7800fa81847bfc2e26a21973899db9dd747
DEBUG:TOOLS: arg 0: /Applications/Defold.app/Contents/Resources/packages/jdk-17.0.5+8/bin/java
DEBUG:TOOLS: arg 1: -cp
DEBUG:TOOLS: arg 2: /Applications/Defold.app/Contents/Resources/packages/defold-7a26e44ba65cdefe580af2e199833478fc49472b.jar
DEBUG:TOOLS: arg 3: -Xdock:icon=/Applications/Defold.app/Contents/Resources/logo.icns
DEBUG:TOOLS: arg 4: -Xdock:name=Defold
DEBUG:TOOLS: arg 5: -Dfile.encoding=UTF-8
DEBUG:TOOLS: arg 6: -Djna.nosys=true
DEBUG:TOOLS: arg 7: -Ddefold.launcherpath=/Applications/Defold.app/Contents/MacOS/Defold
DEBUG:TOOLS: arg 8: -Ddefold.resourcespath=/Applications/Defold.app/Contents/Resources
DEBUG:TOOLS: arg 9: -Ddefold.version=1.4.8
DEBUG:TOOLS: arg 10: -Ddefold.editor.sha1=7a26e44ba65cdefe580af2e199833478fc49472b
DEBUG:TOOLS: arg 11: -Ddefold.engine.sha1=504de7800fa81847bfc2e26a21973899db9dd747
DEBUG:TOOLS: arg 12: -Ddefold.buildtime=2023-07-17T16:06:12.143105
DEBUG:TOOLS: arg 13: -Ddefold.channel=editor-alpha
DEBUG:TOOLS: arg 14: -Ddefold.archive.domain=d.defold.com
DEBUG:TOOLS: arg 15: -Djava.net.preferIPv4Stack=true
DEBUG:TOOLS: arg 16: -Dsun.net.client.defaultConnectTimeout=30000
DEBUG:TOOLS: arg 17: -Dsun.net.client.defaultReadTimeout=30000
DEBUG:TOOLS: arg 18: -Djogl.texture.notexrect=true
DEBUG:TOOLS: arg 19: -Dglass.accessible.force=false
DEBUG:TOOLS: arg 20: --illegal-access=warn
DEBUG:TOOLS: arg 21: --add-opens=java.base/java.lang=ALL-UNNAMED
DEBUG:TOOLS: arg 22: --add-opens=java.desktop/sun.awt=ALL-UNNAMED
DEBUG:TOOLS: arg 23: --add-opens=java.desktop/sun.java2d.opengl=ALL-UNNAMED
DEBUG:TOOLS: arg 24: --add-opens=java.xml/com.sun.org.apache.xerces.internal.jaxp=ALL-UNNAMED
DEBUG:TOOLS: arg 25: --add-opens=java.base/sun.nio.fs=ALL-UNNAMED
DEBUG:TOOLS: arg 26: --add-opens=java.desktop/sun.awt.image=ALL-UNNAMED
DEBUG:TOOLS: arg 27: -Xmx9663676416
DEBUG:TOOLS: arg 28: com.defold.editor.Main
DEBUG:TOOLS: arg 29: (null)
Picked up JAVA_TOOL_OPTIONS: 
Picked up _JAVA_OPTIONS: 
OpenJDK 64-Bit Server VM warning: Ignoring option --illegal-access=warn; support was removed in 17.0
2023-07-28 09:58:55.417 WARN  default    javafx - Unsupported JavaFX configuration: classes were loaded from 'unnamed module @29832b43'
dyld: lazy symbol binding failed: Symbol not found: _objc_alloc_init
  Referenced from: /Users/steventhomas/.openjfx/cache/21-ea+23/x86_64/libprism_es2.dylib (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libobjc.A.dylib

dyld: Symbol not found: _objc_alloc_init
  Referenced from: /Users/steventhomas/.openjfx/cache/21-ea+23/x86_64/libprism_es2.dylib (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libobjc.A.dylib

**Expected behavior (REQUIRED)**
App launches

**Defold version (REQUIRED):**
  - Version 1.4.8

**Platforms (REQUIRED):**
 - macOS 10.13.6 High Sierra
 - iMac (27-inch, Mid 2011)
 - 2.7 GHz Intel Core i5
 - 12 GB 1333 MHz DDR3
 - AMD Radeon HD 6770M 512 MB

**Comment by usbhell** [comment]
As sub 11.0 is no longer supported I'm closing this, thanks.

**Comment by britzl** [comment]
https://forum.defold.com/t/defold-not-starting-mac-os-10-14-6-mojave/73768/2?u=britzl
