### ISSUE TITLE
Editor hangs in the second windows

### ISSUE THREAD

**Issue by AGulev** [defold/defold#7845]
### Expected behaviour
The second editor window should work just fine

### Actual behaviour
If I open a new window of the editor using `File->Open Project` and then use Search in this new instance of the editor, it hangs (it's not like immediately, I switch from one editor to another, build in the second editor, and then click cmd+F or cmd+shit+F and it hangs)

<img width="268" alt="image" src="https://github.com/defold/defold/assets/2209596/cfa2a542-ee01-4507-be95-f87142d604d9">

### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2023-07-17T16:06:12.143105</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>7a26e44ba65cdefe580af2e199833478fc49472b</td></tr>
<tr><td>Defold engine sha</td><td>504de7800fa81847bfc2e26a21973899db9dd747</td></tr>
<tr><td>Defold version</td><td>1.4.8</td></tr>
<tr><td>GPU</td><td>Apple M1 Max</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 83.1</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>13.4.1</td></tr>
<table>

**Comment by vlaaad** [comment]
I managed to reproduce it!

**Comment by vlaaad** [comment]
hmmm or not, after closing the other editor the one that got stuck gets unstuck

**Comment by AGulev** [comment]
> hmmm or not, after closing the other editor the one that got stuck gets unstuck

I didn't check it this way, If you want I can check

**Comment by pmaak** [comment]
Encountered the exact same issue on version 1.5.0 for apple silicon.

**Comment by philousoph** [comment]
Yes, this is actually the same bug behaviour that we have on Silicon Macs and is already an open issue. Still unresolved in the latest 1.6.x beta.

**Comment by ufgo** [comment]
Same problem on M1. Defold version 1.6.0 release

**Comment by dri-richard** [comment]
Is it possible to fix this now by updating to JavaFX 22+17 (or later)?

**Comment by vlaaad** [comment]
The problem is there is no 22+17 or later, they accepted the fix, but haven't released a new version yet. Only thing we can do right now is wait. I check for release daily...

**Comment by dri-richard** [comment]
Understood, I'm not familiar with their release process, I saw that https://github.com/openjdk/jfx/releases is empty, but https://github.com/openjdk/jfx/tags is updated frequently.
