### ISSUE TITLE
Defold no longer compatible with Ubuntu Bionic 

### ISSUE THREAD

**Issue by jultan** [defold/defold#7848]
### Expected behaviour
Editing and building projects... 

### Actual behaviour

error when opening a collection window, and when building project : 

editor complaining about glibc_2.29 not found and TexcLibrary Error

### Steps to reproduce
Start Editor on a fresh ubuntu bionic
open a project
click on a collection, or try to build

<hr/>

<table>
<tr><td>Build time</td><td>2023-07-17T16:04:16.008842</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>7a26e44ba65cdefe580af2e199833478fc49472b</td></tr>
<tr><td>Defold engine sha</td><td>504de7800fa81847bfc2e26a21973899db9dd747</td></tr>
<tr><td>Defold version</td><td>1.4.8</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"2a75310bb97e4bc6a6ee9b4f9d7575b7"'>2a75310bb97e4bc6a6ee9b4f9d7575b7</a></td></tr>
<tr><td>GPU</td><td>Mesa DRI Intel(R) UHD Graphics 620 (KBL GT2)</td></tr>
<tr><td>GPU Driver</td><td>3.0 Mesa 20.0.8</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.4.0-150-generic</td></tr>
<table>

**Comment by AGulev** [comment]
close as duplicate https://github.com/defold/defold/issues/7995
