### ISSUE TITLE
collectionproxy.missing_resources() and ...get_resources() always return table with one resource

### ISSUE THREAD

**Issue by maxim-r** [defold/defold#7864]
**Describe the bug (REQUIRED)**
collectionproxy.missing_resources() and collectionproxy.get_resources() always return a table with a single resource when there should be more than one.

**To Reproduce (REQUIRED)**
I've attached a minimal version of the project. You need to bundle the MacOS application and run it. In the console you can see that the table consists of a single missing resource, whereas in version 1.4.6 the table consists of 5 missing resources.

**Expected behavior (REQUIRED)**
collectionproxy.missing_resources() and collectionproxy.get_resources() must return a table with more than one resource.

**Defold version (REQUIRED):**
  - Version Defold 1.5.0 BETA

**Platforms (REQUIRED):**
 - Platforms: macOS
 - OS: Ventura 13.4
 - Device: MacBook Pro

**Minimal repro case project (OPTIONAL):**
[test_resources.zip](https://github.com/defold/defold/files/12269729/test_resources.zip)

**Comment by AGulev** [comment]
The fix on its way.
The update should be available in 40–50 mins
