### ISSUE TITLE
Custom vertex formats - script API support

### ISSUE THREAD

**Issue by Jhonnyg** [defold/defold#7867]
**Is your feature request related to a problem? Please describe (REQUIRED):**
Currently the custom vertex format support is build-time only, but to gain most out of the feature we need a runtime feature that writes data into the streams from scripts (similar to constants)

**Describe the solution you'd like (REQUIRED):**

**Describe alternatives you've considered (REQUIRED):**

**Additional context (OPTIONAL):**

**Comment by Car3man** [comment]
Up, adding script API support for it really would be helpful!
