### ISSUE TITLE
apple builds fails

### ISSUE THREAD

**Issue by SalavatR** [defold/defold#7870]
**Describe the bug (REQUIRED)**
When i'm try to run build on mac, or build with bob for ios got error:

```
clang: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]

/usr/local/extender-stage/platformsdk/XcodeDefault14.2.xctoolchain/usr/bin/ranlib: file: /var/folders/pf/p5g2vb2j0yx1x6vlmxdppc700000gn/T/job15767175670839984700/build/libDefoldImGui_9.a(gl3w.c_1.o) has no symbols

/usr/local/extender-stage/platformsdk/XcodeDefault14.2.xctoolchain/usr/bin/ranlib: file: /var/folders/pf/p5g2vb2j0yx1x6vlmxdppc700000gn/T/job15767175670839984700/build/libDefoldImGui_9.a(imgui_impl_android.cpp_5.o) has no symbols
fatal error: /usr/local/extender-stage/platformsdk/XcodeDefault14.2.xctoolchain/usr/bin/ranlib: can't write to output file (No space left on device)

ar: internal ranlib command failed
```

**To Reproduce (REQUIRED)**
include https://github.com/britzl/extension-imgui/archive/fc1b0cc79d27c71ce28f3a958c19c89f67e072c0.zip to deps list

**Expected behavior (REQUIRED)**

**Defold version (REQUIRED):**
  - Version [e.g. 1.2.155]

**Platforms (REQUIRED):**
 - Platforms: [iOS, macOS]
 - OS: [macOS]

**Comment by britzl** [comment]
> can't write to output file (No space left on device)

We've cleared up some diskspace. It should work now.
