### ISSUE TITLE
Add link to the official site in the github repository

### ISSUE THREAD

**Issue by pkulev** [defold/defold#7881]
**Is your feature request related to a problem? Please describe (REQUIRED):**
As I can see, neither README does not contain any links to official site, nor github "about" section.
<img width="379" alt="изображение" src="https://github.com/defold/defold/assets/1115916/6fc16810-a182-4538-96ea-120ae26882a3">
 

**Describe the solution you'd like (REQUIRED):**
Please, add link to https://defold.com in the repository settings.
For example (Homebrew/homebrew-cask repo):
<img width="389" alt="изображение" src="https://github.com/defold/defold/assets/1115916/b7394d27-a3a4-4a72-9513-ea73e4aea852">

**Describe alternatives you've considered (REQUIRED):**
Link in the readme, maybe in form of clickable image with defold logo.

**Comment by britzl** [comment]
Thanks. I've added a link to defold.com to the About section!
