### ISSUE TITLE
Lua code not compressed in 1.5.0

### ISSUE THREAD

**Issue by d954mas** [defold/defold#7899]
**Describe the bug (REQUIRED)**
Lua code not compressed in 1.5.0 Beta

**To Reproduce (REQUIRED)**
1. Build with bob
```
java -jar bob/bob.jar --settings bob/settings/dev_game.project_settings --archive  --texture-compression true --with-symbols --variant debug --platform=js-web --bo bob/releases/dev/web -brhtml bob/releases/dev/web/report.html clean resolve build bundle 
```

**Expected behavior (REQUIRED)**
Lua code compressed

**Defold version (REQUIRED):**
  - 1.5.0 beta 
    editor sha d0b08c6914b4fccc7d97e99ba228ac4eadaaee09
   engine sha d0b08c6914b4fccc7d97e99ba228ac4eadaaee09

**Platforms (REQUIRED):**
 - Platforms: [Web]

**Screenshots (OPTIONAL):**
1.4.8
![2023-08-18_20-21-18](https://github.com/defold/defold/assets/2655263/5ac5dcdb-cfe7-40bc-beb8-5072fc9da486)
1.5.0
![2023-08-18_20-22-57](https://github.com/defold/defold/assets/2655263/a027ff4c-2c30-4104-bbeb-99a37c211e68)

**Additional context (OPTIONAL):**

**Comment by AGulev** [comment]
We changed the order of encryption and compression
<img width="1386" alt="image" src="https://github.com/defold/defold/assets/2209596/1227a239-bf69-4b88-aaf3-21bd449439ca">
https://github.com/defold/defold/blob/1b22d74c39db25d22eca3a53b3b726893f444be6/com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/archive/ArchiveBuilder.java#L215-L236

and it seems like compression after encryption is extremely inefficient, I made some measurements:
```
Uncompressed and unencrypted:3893
Compressed, before encryption:2393
Encrypted, before compression:3893
Encrypted, after compression:2393
Compressed, after encryption:3910
```
