### ISSUE TITLE
font metrics wrong for monospace font.

### ISSUE THREAD

**Issue by d954mas** [defold/defold#7900]
**Describe the bug (REQUIRED)**
I try to make timer for my game. I try monospace font, but it possition is jittering
https://github.com/defold/defold/assets/2655263/dd34fd9a-8a5e-4c25-8b57-cb4df677796c

I try to make small repro case. Label with same number of symbols in monospace font have different width.
![2023-08-19_13-31-32](https://github.com/defold/defold/assets/2655263/0011a5f2-a44a-4ff1-bedd-ea0990d16d92)

1-2 labels is center
3-4 labels is west

```
DEBUG:SCRIPT: time:00:00 width:188
DEBUG:SCRIPT: time:11:11 width:179
```

Last symbol right border not added to width?

**To Reproduce (REQUIRED)**
Look at repro case.

**Expected behavior (REQUIRED)**
Width should be same

**Defold version (REQUIRED):**
  - Version 1.5.0

**Platforms (REQUIRED):**
  - Windows

**Minimal repro case project (OPTIONAL):**
[FontWidth.zip](https://github.com/defold/defold/files/12385606/FontWidth.zip)

**Comment by AGulev** [comment]
This part doesn't take into account monospaced fonts
https://github.com/defold/defold/blob/17bec1bfcd97fc127f3e78d3b890b505826d8421/engine/render/src/render/font_renderer.cpp#L1207-L1213

![image](https://github.com/defold/defold/assets/2209596/7b006382-881d-4d1c-a657-3ead016ebfab)
![image](https://github.com/defold/defold/assets/2209596/41bc14a1-adf2-40db-a689-dfe8f99eb804)
