### ISSUE TITLE
How do I fix these two errors?

### ISSUE THREAD

**Issue by Antonygamergod** [defold/defold#7901]
1:
```
clojure.lang.ExceptionInfo: handler ':open' in context ':global' failed at ':run' with message 'Cannot run program "C:\Program Files\Microsoft VS Code\Code.exe" (in directory "C:\Users\user\Empty project"): CreateProcess error=2, O sistema não pode encontrar o arquivo especificado'
java.io.IOException: Cannot run program "C:\Program Files\Microsoft VS Code\Code.exe" (in directory "C:\Users\user\Empty project"): CreateProcess error=2, O sistema não pode encontrar o arquivo especificado
java.io.IOException: CreateProcess error=2, O sistema não pode encontrar o arquivo especificado
```

2:
```
cp: cannot stat './build/temp/_unpack/x86_64-win32/bin/OpenAL32.dll': No such file or directory
.vscode/defold.sh: line 341: .exe: command not found
cp: cannot stat './build/temp/_unpack/x86_64-win32/bin/wrap_oal.dll': No such file or directory
```

# Launching
$ ./build/x86_64-win32/dmengine ./build/default/game.projectc

.vscode/defold.sh: line 366: ./build/x86_64-win32/dmengine: No such file or directory

**Comment by Antonygamergod** [comment]
some information when i click on report in defold


### Expected behaviour

### Actual behaviour

### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2023-08-07T11:36:43.216595</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>34db77fa587e44fb60bc0da0192075054def3f72</td></tr>
<tr><td>Defold engine sha</td><td>504de7800fa81847bfc2e26a21973899db9dd747</td></tr>
<tr><td>Defold version</td><td>1.4.8</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"39d9df0eadb04052bd4f3ea0c5b480ee"'>39d9df0eadb04052bd4f3ea0c5b480ee</a></td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 4000</td></tr>
<tr><td>GPU Driver</td><td>4.0.0 - Build 10.18.10.4358</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 11</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
It looks like you are doing some kind of VSCode integration? Which instructions have you followed to set it up? I would recommend that you [join our Discord server](https://discord.gg/cHBde7J) or [the Defold Forum](https://forum.defold.com/) and ask for support there.

**Comment by britzl** [comment]
I see that you also asked on the forum: https://forum.defold.com/t/guide-how-to-turn-vscode-into-defold-ide-with-debugger/68002/29?u=britzl
