### ISSUE TITLE
Setting value on template after error causes another error

### ISSUE THREAD

**Issue by Jerakin** [defold/defold#7920]
Putting a value into a field after error https://github.com/defold/defold/issues/7919

I assume this error doesn't matter much, but may as well report it in cause it shows up in the metrics and you want more info

<hr/>

<table>
<tr><td>Build time</td><td>2023-08-07T11:36:43.216595</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>34db77fa587e44fb60bc0da0192075054def3f72</td></tr>
<tr><td>Defold engine sha</td><td>504de7800fa81847bfc2e26a21973899db9dd747</td></tr>
<tr><td>Defold version</td><td>1.4.8</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"e3aefa1528ea4e6b96d334da55892952"'>e3aefa1528ea4e6b96d334da55892952</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon RX 7900 XT</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 Compatibility Profile Context 23.4.2.230412</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
Thanks. But you are right, I will close it since we need to solve the initial error first.
