### ISSUE TITLE
Fullscreen setting results in blank screen.

### ISSUE THREAD

**Issue by bryanrieger** [defold/defold#7922]
**Describe the bug**
Selecting fullscreen in the game.project Display settings results in a blank screen.

**To Reproduce**
1. Create a simple project with something visible on screen.
2. Select 'fullscreen' in game.project Display settings.
3. Build and run the project.
4. Stare a blank screen.

**Expected behavior**
The game should display as expected.

**Defold version**
  - Versions 1.4.8 and 1.5.0 beta.

**Platforms:**
 - Platforms: macOS
 - OS: Ventura 13.5.1
 - Device: MacBook Pro M1 Pro, 32GB RAM

[Test.zip](https://github.com/defold/defold/files/12448777/Test.zip)

**Comment by JCash** [comment]
Tried this, but it didn't help:
https://github.com/glfw/glfw/commit/d3f22b8a04dd62674b3ed9050c748f4e6a0b626c
