### ISSUE TITLE
Wrong error description if build HTML5 application

### ISSUE THREAD

**Issue by kornyushin** [defold/defold#7929]
if project has erros and try to make build with editor (project->bundle->html5 application) , then you get error 
"cant find file \build\default\game.arci" in Build error console
if make build Project->Build HTML5 , then you get error with fully description

To Reproduce: open attached project and try to build

Expected behavior: Both builds should show same error

  - Version 1.5.0

Platforms HTML5
OS: Windows 10

[mytest.zip](https://github.com/defold/defold/files/12465301/mytest.zip)
<img width="346" alt="err1" src="https://github.com/defold/defold/assets/1443375/f2205284-1120-495c-928e-6a2a91a169c2">
<img width="442" alt="err0" src="https://github.com/defold/defold/assets/1443375/96825c96-29d2-446e-8377-747a89c95217">

**Comment by AGulev** [comment]
it looks like duplicate: https://github.com/defold/defold/issues/7862

**Comment by britzl** [comment]
> it looks like duplicate: #7862

Indeed. @kornyushin I'm closing this one in favour of 7862.
