### ISSUE TITLE
Allow setting material constants on components from editor

### ISSUE THREAD

**Issue by swajj** [defold/defold#7935]
**Is your feature request related to a problem? Please describe (REQUIRED):**
I want to set material constants (such as `tint`) on my components (sprites) in the editor so that when I spawn a GO, it is visually accurate without additional code. This lets me maintain the appearance of my GOs in one place rather split between data (editor) and code (Lua).

**Describe the solution you'd like (REQUIRED):**
I would like to be able to set `tint` and any other material constants directly on sprites in the Defold editor e.g. in the lower-right pane of this view:
<img width="816" alt="image" src="https://github.com/defold/defold/assets/133168946/a7220b0e-2cfd-4c21-be02-0bc478afae9f">

**Describe alternatives you've considered (REQUIRED):**
I can configure this in code after spawning the GO, but that means A) the editor isn't showing the final result and B) I have to do extra work to keep things in sync between the two locations.

**Comment by swajj** [comment]
Of note, my current use cases would all be covered once the (presumed) follow-up work from #5393 is done to allow setting material attributes from Lua.

**Comment by Jhonnyg** [comment]
This is the follow-up i think you are looking for #7867

**Comment by swajj** [comment]
Yup, #7867 is the one, thanks! Not closing this issue since others might want it but that other issue will cover all my concerns.

**Comment by AGulev** [comment]
now it's possible to do using vertex attributes, see https://forum.defold.com/t/defold-1-4-8-has-been-released/73657/8?u=agulev
