### ISSUE TITLE
Android bundle installation fails on Mac if ADB_LIBUSB=1

### ISSUE THREAD

**Issue by dri-richard** [defold/defold#7937]
**Describe the bug**
Certain Mac / macOS / adb versions fail to install APKs unless ADB_LIBUSB is set to 1 (see [Google issue](https://issuetracker.google.com/issues/270205252))

This setting however changes the output of adb devices, which Defold incorrectly parses.
The output format of adb devices is different depending on the value of ADB_LIBUSB:

802KPAE1577008         device 1-1.3 product:taimen model:Pixel_2_XL device:taimen transport_id:1
vs
802KPAE1577008         device usb:18022400X product:taimen model:Pixel_2_XL device:taimen transport_id:1

**To Reproduce**
1. In a terminal window, run:
```
export ADB_LIBUSB=1
adb kill-server 
```
2. In the Defold editor, select Project->Bundle->Android Application
3. Tick the 'Install on connected device' option
4. Click 'Create Bundle...'

**Expected behavior**
The apk is built and installed

**Defold version:**
  1.5.0 (Apple Silicon, but previously seen on Intel builds)

**Platforms :**
 - Platforms: macOS 13.5
 - Device: MacBook Pro M1 2020

**Logs:**

```
Resolving ADB location...
Resolved to '/Users/dri/Library/Android/sdk/platform-tools/adb'
Listing devices...
Vector arg to map conj must be a pair
```

**Comment by vlaaad** [comment]
The fix should be available as an editor update in around 20 minutes.
