### ISSUE TITLE
Building a project when the project is running causes build to fail

### ISSUE THREAD

**Issue by SurfaceToAsh** [defold/defold#7944]
**Describe the bug (REQUIRED)**
When building a game project through Ctrl+B or Project menu, if the game project is already running, the Game window closes but the build does not complete, and various errors appear depending on the project.

**To Reproduce (REQUIRED)**
Precondition: A Defold game project is running
1. Set focus to Defold IDE
2. Press CTRL + B

**Expected behavior (REQUIRED)**
The project builds at its current state, the existing instance of the game closes, and a new window appears

**Defold version (REQUIRED):**
  Version 1.5 (b55f345)

**Platforms (REQUIRED):**
 Platforms: Windows
OS: Windows 10
Device: Desktop PC

**Minimal repro case project (OPTIONAL):**
This can be done on any project. Open Defold > New Project > Empty Project > Ctrl+B > Ctrl+B again 

**Screenshots (OPTIONAL):**
Error running from my current project:
![image](https://github.com/defold/defold/assets/77247869/0329911e-1710-4b85-8225-f323d9efd563)

Error Running from a new project:
![image](https://github.com/defold/defold/assets/77247869/3259f09f-82b1-443a-aa17-1173002b21af)

**Additional context (OPTIONAL):**
If the game instance is closed before another build attempt, the build completes fine, it seems to just be when a build instance is running that this issue occurs.

**Comment by aglitchman** [comment]
Exactly the same problem! On a work project I get the warning about resources, but on an empty project I get the error about FORMAT_ERROR.

Windows 10, Defold 1.5.0.

**Comment by matgis** [comment]
A fix has been merged, and you should receive an editor update shortly. Thanks for reporting! ❤️

**Comment by aglitchman** [comment]
> A fix has been merged, and you should receive an editor update shortly. Thanks for reporting! ❤️

The problem still exists for projects with native extensions, i.e. I made a new project from the "desktop" template, added [clipboard](https://github.com/britzl/defold-clipboard) as extension, build the project, then build it again without closing the game window and got the same problem:

![image](https://github.com/defold/defold/assets/193258/d2c1b968-3758-48ae-a529-71c0d7bce40a)

**Comment by AGulev** [comment]
@aglitchman thanks, it is a nice combo with two separate issues. 
the next one will be fixed in 1.5.1
