### ISSUE TITLE
Error when trying to bundle when having a folder called "state".

### ISSUE THREAD

**Issue by rama0x9** [defold/defold#7951]
**Describe the bug (REQUIRED)**
Cant bundle project with a folder called "state" at root level.

**To Reproduce (REQUIRED)**
Create a new mobile project and change the folder "main" to "state" and try to bundle it.

**Defold version (REQUIRED):**
latest

**Platforms (REQUIRED):**
 - Platforms: Linux

**Comment by britzl** [comment]
What is the error you are getting?

**Comment by rama0x9** [comment]
oh, so you can bundle it without any difficulty?

`unknown source`
`   /.../Mobile game/build/default/state (Is a directory)`

**Comment by britzl** [comment]
> oh, so you can bundle it without any difficulty?

I did not say that. I asked for more information, since your bugreport was incomplete. How did you rename the folder? From within Defold or using terminal or file manager?

**Comment by britzl** [comment]
> How did you rename the folder? From within Defold or using terminal or file manager?

I can conform that there is a bug. I rename from "main" to "state" from within Defold and try to bundle.

**Comment by britzl** [comment]
And it is caused by this operation:

https://github.com/defold/defold/blob/dev/com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/Project.java#L1381-L1382
