### ISSUE TITLE
can't do require("module").function1()

### ISSUE THREAD

**Issue by viindicater** [defold/defold#7963]
**Describe the bug (REQUIRED)**
can't do `require("module").function1()` , have to declare the require as a variable and then call the function through it, i.e. have to do 
```
local m = require("module")
m.function1()
```

**To Reproduce (REQUIRED)**
1. Create or pick a lua script module
2. Attempt to require() it and call one of its functions directly on the require()
3. See error

**Expected behavior (REQUIRED)**
The function should be called

**Defold version (REQUIRED):**
  - Version 1.5.0

**Platforms (REQUIRED):**
 - Platforms: Windows (Editor)
 - OS: Windows 10

**Additional context (OPTIONAL):**
Seems to also work if the module is already loaded i.e. 
```
local m = require("module")
require("module").function1()
```

**Comment by britzl** [comment]
This is surprising. I thought this would work. We'll look into it.

**Comment by AGulev** [comment]
@britzl hmm, I'll take a look into it later this week

**Comment by AGulev** [comment]
Ok, I got it. It's in the editor. `bob.jar` is fine (when you bundle it)
