### ISSUE TITLE
Launcher extends beyond screen

### ISSUE THREAD

**Issue by viindicater** [defold/defold#7965]
**Describe the bug (REQUIRED)**
Launcher is bigger than my screen's size

**To Reproduce (REQUIRED)**
1. Open defold

**Expected behavior (REQUIRED)**
Should fit and/or be resizable

**Defold version (REQUIRED):**
  - Version 1.5.0

**Platforms (REQUIRED):**
 - Platforms: Windows (10)

**Screenshots (OPTIONAL):**
https://github.com/defold/defold/assets/60835390/31ac2234-a050-4894-8c9e-ec6bf518f0ca

**Additional context (OPTIONAL):**
When I first opened defold, launcher's window handle was above offscreen above (had to turn up the resolution and move it down and then change the screen's resolution back for it to work in the current resolution of 1280x720)

**Comment by AGulev** [comment]
@vlaaad is this one fixed by https://github.com/defold/defold/pull/8533/files ?

**Comment by vlaaad** [comment]
Yes
