### ISSUE TITLE
[html5] mouse's position not working properly in fullscreen

### ISSUE THREAD

**Issue by viindicater** [defold/defold#7966]
**Describe the bug (REQUIRED)**
When using defold's fullscreen feature in html5, mouse's position is off

**To Reproduce (REQUIRED)**
1. Run repro in html5
2. Click on screen to see square spawn in the correct position
3. Click fullscreen
4. Click on screen, see the square no longer spawn at mouse's position

**Expected behavior (REQUIRED)**
Square should spawn at mouse's position in fullscreen

**Defold version (REQUIRED):**
  - Version 1.5.0

**Platforms (REQUIRED):**
 - Platforms: HTML5
 - OS: Windows 10

**Minimal repro case project (OPTIONAL):**
[WebBugDefoldFullscreen.zip](https://github.com/defold/defold/files/12532864/WebBugDefoldFullscreen.zip)

**Comment by britzl** [comment]
This is not really a problem only in html5. Resize the window on desktop and you will notice the same problem.

**Comment by britzl** [comment]
And there really is no bug here. You need to take into account the projection used when drawing the gui and the adjust mode of the node that you are spawning. As an example, do this in your gui.gui_script:

```lua
		if action.pressed then
			local action_pos = vmath.vector3(action.x, action.y, 0)
			local node = gui.new_box_node(action_pos, vmath.vector3(50, 50, 0))
			gui.set_adjust_mode(node, gui.ADJUST_STRETCH)
		end
```

This will render the box nodes where you click because the adjust mode of the node is set to stretch, ie it adjusts to and stretches based on the current window size in relation to the original window size.

If you instead want to use `gui.ADJUST_FIT` or `gui.ADJUST_ZOOM` it becomes trickier. This is the full script to spawn a node with a specific adjust mode, taking into account a scaled window:

```lua
			local DISPLAY_WIDTH = sys.get_config_int("display.width")
			local DISPLAY_HEIGHT = sys.get_config_int("display.height")
			local WINDOW_WIDTH,WINDOW_HEIGHT = window.get_size()

			local sx = WINDOW_WIDTH / DISPLAY_WIDTH
			local sy = WINDOW_HEIGHT / DISPLAY_HEIGHT

			local adjust_mode = gui.ADJUST_STRETCH

			-- defaults for gui.ADJUST_STRETCH
			local adjust_sx = 1
			local adjust_sy = 1
			local adjust_ox = 0
			local adjust_oy = 0
			if adjust_mode == gui.ADJUST_FIT then
				local scale = math.min(sx, sy)
				adjust_sx = scale * 1 / sx
				adjust_sy = scale * 1 / sy
				adjust_ox = (WINDOW_WIDTH - DISPLAY_WIDTH * scale) * 0.5 / scale
				adjust_oy = (WINDOW_HEIGHT - DISPLAY_HEIGHT * scale) * 0.5 / scale
			elseif adjust_mode == gui.ADJUST_ZOOM then
				local scale = math.max(sx, sy)
				adjust_sx = scale * 1 / sx
				adjust_sy = scale * 1 / sy
				adjust_ox = (WINDOW_WIDTH - DISPLAY_WIDTH * scale) * 0.5 / scale
				adjust_oy = (WINDOW_HEIGHT - DISPLAY_HEIGHT * scale) * 0.5 / scale
			end
			
			local x = (action.x / adjust_sx) - adjust_ox
			local y = (action.y / adjust_sy) - adjust_oy
			local action_pos = vmath.vector3(x, y, 0)
			local node = gui.new_box_node(action_pos, vmath.vector3(50, 50, 0))
			gui.set_adjust_mode(node, adjust_mode)
```
