### ISSUE TITLE
Migrate to GLFW3

### ISSUE THREAD

**Issue by Jhonnyg** [defold/defold#7970]
**Task (REQUIRED):**
Our current GLFW version is over ten years old and is thus severely outdated. As a first step of refacturing this system, we should upgrade to the latest GLFW3 for desktop platforms and keep modifications out of it. In the long run we should remove building glfw altogether from the core engine and just store it as a package.

**Expected outcome (REQUIRED):**
It's obvious isn't it!

**Comment by ZhenFTW** [comment]
Oh I just noticed that we don't use the GLFW3. Definitely waiting for upgrade, might take some time or idea to restructure the project though. Hope it gets added sooner.
