### ISSUE TITLE
Ability to import spritesheets

### ISSUE THREAD

**Issue by ahmutkadim** [defold/defold#7981]
**Is your feature request related to a problem? Please describe (REQUIRED):**
I want to import spritesheets but there is no way to do it internally in the engine.

**Describe the solution you'd like (REQUIRED):**
A way to import spritesheet, a system could be implemented to slice the spritesheet inside the editor

**Describe alternatives you've considered (REQUIRED):**
Atlas files might be able to support spritesheets 

**Additional context (OPTIONAL):**
This feature is standard in most 2D game engines (Unity, Godot) so seeing it in Defold would be great.

**Comment by britzl** [comment]
> I want to import spritesheets but there is no way to do it internally in the engine.

Can you give an example of such a sprite sheet? I'm thinking that what you describe is a [Defold tilesource](https://defold.com/manuals/tilesource/#tile-source-flip-book-animations), but I'm probably not fully understanding the problem.

**Comment by ahmutkadim** [comment]
Welp off the top of my head, I was able to find this. Also I need to say that tilesources are an inefficient solution since they can only contain a single image.

![GUI](https://github.com/defold/defold/assets/127795356/b42b7425-2a50-4d51-a821-59cc4c6618a9)

This file is a pre-made asset see here: https://mounirtohami.itch.io/pixel-art-gui-elements

**Comment by britzl** [comment]
Ah, ok, I see. Well, Defold does not support such a file. It looks like a mix of UI elements, a bitmap font and some mockup examples.

Defold expects such content to be pre-processed before use. Which in this case means:

* UI elements are split into individual images for import into a [Defold atlas](https://defold.com/manuals/atlas/)
* Font is separated into its own image and imported as a [Defold bitmap font](https://defold.com/manuals/font/#bitmap-bmfonts)

We may at some point support the [TexturePacker file format](https://www.codeandweb.com/texturepacker), but it doesn't look like the example you provided was generated using TexturePacker.

Closing as this is outside the scope of what we want the Defold tools to support.
