### ISSUE TITLE
Find a way to make using system_font clear for new users

### ISSUE THREAD

**Issue by AGulev** [defold/defold#7988]
**Task (REQUIRED):**
![image](https://github.com/defold/defold/assets/2209596/6718cc9d-5a51-42ee-81f3-4ed92a720ce2)

**Expected outcome (REQUIRED):**
Describe the expected outcome of the task (new issue, documentation, code change etc)

**Comment by 8bitskull** [comment]
Another user experiencing this:

https://forum.defold.com/t/something-weird-with-gui-text-node/75578

**Comment by britzl** [comment]
One idea is to hide the system font from the font picker window. This way we can keep the font as-is, but developers can't pick it by mistake for use in a gui.

Another idea is to rename the font to debug.material (breaking change unless we can migrate projects already using the font). And introduce a proper system.font for use as a default font in guis.

**Comment by AGulev** [comment]
@britzl since we introduce breaking changes in the next 1.7.0 version, maybe we can do something here as well?

**Comment by britzl** [comment]
> @britzl since we introduce breaking changes in the next 1.7.0 version, maybe we can do something here as well?

Yes, it would be a good time to make this change in 1.7.0!
