### ISSUE TITLE
Sometimes frustum culling breaks rendering in Safari on iOS 15.7

### ISSUE THREAD

**Issue by vbif1** [defold/defold#8004]
**Describe the bug (REQUIRED)**

There a lot of prerequirements but still it affects some players. And some moderators on yandex platform =)
Its appear on html5 build running in Safary on ios devices with version 15.7. Maybe it affects devices from 15.4+. But on the newest version all works fine. It can run perfectly, but if you try reload page several time you are going to run to this issue. Some guy from our community also runs to this issue, but on desktop safari browser some time ago. He did't fly an issue back then but he found workaround for this. Problem dissapears if you stop sending the frustram matrix to render.

https://github.com/defold/defold/assets/35957639/61486b2b-5215-4932-bd97-b30c87efa514

**To Reproduce (REQUIRED)**
1. Run game on some specific device
2. Reload page several times

**Expected behavior (REQUIRED)**
This glitches would be not happened

**Defold version (REQUIRED):**
  - Version 1.5.0

**Platforms (REQUIRED):**
 - Device: ios devices 15.7 (at least)

**Minimal repro case project (OPTIONAL):**
I can share my project to someone in discord or email

**Workaround (OPTIONAL):**
The problem dissapears when you disable frustrum culling.

**Comment by AGulev** [comment]
Could you pls try to reproduce it using 1.6.4.?

**Comment by AGulev** [comment]
@vbif1 
A lot of fixes were made in 1.6.4-1.7.0 in this area. could you pls take a look if it's still an issue for you using the latest version of Defold?

**Comment by AGulev** [comment]
Additional info wasn't provided. I'm closing it for now. Feel free to reopen if you'll be able to reproduce it using new version of Defold.
