### ISSUE TITLE
Create a build error if a .script file is used as a .gui_script file

### ISSUE THREAD

**Issue by JCash** [defold/defold#8005]
Both editor and bob fail to catch this issue.
Editor built content produces a hard crash, bob built content produces an error related to resources: "Unknown resource type: script"

Repro:
https://forum.defold.com/t/colorslide-tutorial-build-fail/74076

**Comment by AGulev** [comment]
hmm, but It's possible to add script this way only manually using a text editor

**Comment by JCash** [comment]
Sure, but we should still check

**Comment by JCash** [comment]
Also, the user noted that it was done by typing directly into the text field in the editor.
