### ISSUE TITLE
Double-clicking a script file causes an error instead of opening the custom code editor (Rider)

### ISSUE THREAD

**Issue by andreweades** [defold/defold#8013]
### Expected behaviour
Double clicking a script file or Lua file should open the external editor set  in preferences.

### Actual behaviour
An error dialog appears.

### Steps to reproduce
1. Set  a custom editor in File>Preferences>Code.
2. double click a .script or .lua file

<hr/>

<table>
<tr><td>Build time</td><td>2023-09-12T14:40:57.163828</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>b32617a800e88bcf42d70520d07c277e48d2b38a</td></tr>
<tr><td>Defold engine sha</td><td>e0073d0f7156b733e97a53c46924355fbf60dc77</td></tr>
<tr><td>Defold version</td><td>1.5.0</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"38ca9bbacdbc490e9190352a27f2de5e"'>38ca9bbacdbc490e9190352a27f2de5e</a></td></tr>
<tr><td>GPU</td><td>Apple M1 Max</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 86</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>aarch64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>14.0</td></tr>
<table>

**Comment by andreweades** [comment]
The error:

clojure.lang.ExceptionInfo: handler ':open' in context ':global' failed at ':run' with message 'Cannot run program "/Applications/IntelliJ IDEA.app" (in directory "/Users/andy/Web Monetized game"): error=13, Permission denied'
java.io.IOException: Cannot run program "/Applications/IntelliJ IDEA.app" (in directory "/Users/andy/Web Monetized game"): error=13, Permission denied
java.io.IOException: error=13, Permission denied

**Comment by matgis** [comment]
Hi! When specifying a custom code editor on macOS, you have to set the path to the actual executable that resides within the app bundle. Try setting it to `/Applications/IntelliJ IDEA.app/Contents/MacOS/idea`.

**Comment by britzl** [comment]
> Hi! When specifying a custom code editor on macOS, you have to set the path to the actual executable that resides within the app bundle. Try setting it to `/Applications/IntelliJ IDEA.app/Contents/MacOS/idea`.

Also mentioned in the editor preferences manual: https://defold.com/manuals/editor-preferences/#code

@matgis what kind of error message are we showing? It looks like a not so user friendly error.

**Comment by andreweades** [comment]
Thank you. I should have read the manual more closely but it would be better to enhance the editor panel to have a drop down of the most common editors as you have suggested. I even downloaded the source to try to find the code that tries to open the file to see if I could fix it...
