### ISSUE TITLE
Paged atlas compression issue in web build

### ISSUE THREAD

**Issue by Laminariy** [defold/defold#8030]
**Describe the bug (REQUIRED)**
Similar issue: https://github.com/defold/defold/issues/7628
Enabling texture compression breaks the rendering of a multi-paged atlas sprite in web build (black rectangles/random atlas parts).
When builded without texture compression issue doesn't reproduce.
Looks like issue reproduces on android and windows old intel gpu.

**To Reproduce (REQUIRED)**
1. Open example project
2. Bundle for web with and without texture compression
3. Check build on old intel gpu/android
4. Paged version of sprite will be in some way broken

**Expected behavior (REQUIRED)**
Multi-page atlases with texture compression renders correctly.

**Defold version (REQUIRED):**
  - Version 1.4.8 stable https://github.com/defold/defold/commit/504de7800fa81847bfc2e26a21973899db9dd747

**Platforms (REQUIRED):**
 - Platforms: HTML5
 - OS: Android/Windows
 - Device: realme GT Master Edition and other

**Minimal repro case project (OPTIONAL):**
[repo.zip](https://github.com/defold/defold/files/12700418/repo.zip)

**Screenshots (OPTIONAL):**
Repo:
Compressed
![compressed](https://github.com/defold/defold/assets/48628793/31edebb5-96ed-439b-a8ac-5a12e0f4c505)
Uncompressed
![uncompressed](https://github.com/defold/defold/assets/48628793/22a987d1-2715-4a8d-aeab-743926298d75)

Windows player:
![windows_1](https://github.com/defold/defold/assets/48628793/9d645518-df8a-42da-b1af-67c914398095)

Android player:
![android_3](https://github.com/defold/defold/assets/48628793/d7f65821-39fb-4769-890d-f72b01113128)

**Additional context (OPTIONAL):**
We collect some data from our players. Looks like broken sprites reproduces on old intel gpu and black sprites reproduces on android devices.
Here some additional info:
[user_info.txt](https://github.com/defold/defold/files/12700501/user_info.txt)

**Comment by Laminariy** [comment]
Nothing changed, issue still reproduces

**Comment by Jhonnyg** [comment]
So if you use compression the first page still works right? For old devices we split the pages into separate textures that has the same compression settings so if the first one (or any compressed texture) works I don’t see any reason the other pages shouldn’t work. Not sure I have any devices to test with that are that old, but I’ll see if someone else in the team has one

**Comment by afrokick** [comment]
@Laminariy did you try another POT size?

**Comment by AGulev** [comment]
<img width="599" alt="image" src="https://github.com/defold/defold/assets/2209596/7e2e1714-fc42-4085-bb18-c0204cd8991b">

```
[.WebGL-0x44d78d00]GL ERROR :GL_INVALID_VALUE : glCompressedTexImage3D: size is not correct for dimensions
255[.WebGL-0x44d78d00]RENDER WARNING: texture bound to texture unit 0 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
```

**Comment by AGulev** [comment]
I merged a fix for android, but for windows I'll take a look separately. It's not enough info now to fix it.
