### ISSUE TITLE
I left the engine openend and inactie for like 18 hours and then this happened

### ISSUE THREAD

**Issue by FelipeSuarezPlazas** [defold/defold#8034]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2023-09-19T14:42:23.123401</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>bb52dfb7281ef2b03c3462e9a4205abd69fb11b1</td></tr>
<tr><td>Defold engine sha</td><td>00352cc02f24c12e6081245c0d5fb2e0b263d05e</td></tr>
<tr><td>Defold version</td><td>1.5.0</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"1638c892df10452ea1f276c0574b0576"'>1638c892df10452ea1f276c0574b0576</a></td></tr>
<tr><td>GPU</td><td>Apple M1</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 83.1</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>aarch64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>13.4.1</td></tr>
<table>

**Comment by hristo-kanchev** [comment]
What happened?

**Comment by AGulev** [comment]
I think it's related to https://github.com/defold/defold/issues/7709
