### ISSUE TITLE
Bob build engine every time

### ISSUE THREAD

**Issue by ekharkunov-ms** [defold/defold#8041]
**Describe the bug (REQUIRED)**
When project contains native extensions Bob build engine every time when we call `bob.jar build`. However we have already built engine inside `.internal/cache` directory. According to @britzl's answer it's not an expected behaviour.

**To Reproduce (REQUIRED)**
1. Unpack example project
2. Download bob.jar from Releases page https://github.com/defold/defold/releases/download/1.5.0/bob.jar
3. Run command from the project root
```
java -jar bob.jar --verbose --platform arm64-ios --variant debug --use-async-build-server --archive --with-symbols --strip-executable resolve build
```
4. Observe log `Build remote engine`.
5. Finish build. Check that .internal/cache exists.
6. Run command from step 3 one more time.
7. Observe log `Build remote engine`. It indicates that Bob build engine one more time.

**Expected behavior (REQUIRED)**
Bob use cached engine if nothing changed regarding to native extensions.

**Defold version (REQUIRED):**
  - Version 1.5.0

**Platforms (REQUIRED):**
 - Platforms: any
 - OS: any

**Minimal repro case project (OPTIONAL):**
[bob_repro.zip](https://github.com/defold/defold/files/12716889/bob_repro.zip)

**Workaround (OPTIONAL):**
Hack Bob and use custom version.

**Additional context (OPTIONAL):**
Pay attention that appmanifest is used for example project.

**Comment by ekharkunov-ms** [comment]
It was a local issue. Bob works as expected.

**Comment by AGulev** [comment]
@ekharkunov-ms are you sure? I didn't check myself, but pbbly I should anyways

**Comment by ekharkunov-ms** [comment]
Yes. There were several local issue.
First, I didn't move folder structure identically.
Second, `.internal/cache/.buildcache` file stored a full path to engine build and when I moved cache across folder I didn't change pathes in `.buildcache`.
