### ISSUE TITLE
Performance issues on macOS [version 1.6]

### ISSUE THREAD

**Issue by ldust** [defold/defold#8045]
**Describe the bug (REQUIRED)**
In version 1.6, there are lags on macOS. This issue persists in both the preview version and the bundled version. 
The HTML5 version and Editor version 1.5 works fine.

**To Reproduce (REQUIRED)**
1. Create new project from sample "Linker sample game"
2. Click on 'Build'
3. Play it

**Expected behavior (REQUIRED)**
No lags

**Defold version (REQUIRED):**
  - Version 1.6 stable

**Platforms (REQUIRED):**
 - Platforms: mac
 - OS: macos 13.4.1
 - Device: mac book pro 2019, intel

I'm new to this engine, I'm not sure if the problem is with the engine or the example.

**Comment by Jhonnyg** [comment]
I think this is related to the particles issue we had in 1.6.0, a hotfix is on the way!

**Comment by Jhonnyg** [comment]
Fixed by https://github.com/defold/defold/commit/28fce825d51d70b3b70430bdfc6a6f8166d3284b

**Comment by ldust** [comment]
good to know! thanks
