### ISSUE TITLE
HTML5 sys.reboot() problems with sound Defold 1.6

### ISSUE THREAD

**Issue by Mulderua** [defold/defold#8049]
**Describe the bug (REQUIRED)**
Browser hanging on sys.reboot() 

**To Reproduce (REQUIRED)**
1. Any Sound playing
2. Call sys.reboot() 

**Expected behavior (REQUIRED)**
Application rebooted everything fine

**Defold version (REQUIRED):**
  - 1.6

**Platforms (REQUIRED):**
 - Platforms: HTML5
 - Device: Tested on Chrome and Firefox

**Minimal repro case project (OPTIONAL):**
(https://github.com/Mulderua/defold1.6_bug_with_sys_reboot)

**Screenshots (OPTIONAL):**
[If applicable, add screenshots to help explain your problem.](https://forum.defold.com/uploads/default/original/3X/5/3/530cc77dd5c6bd191345625733a74ce2539d06d4.png)

**Comment by JCash** [comment]
Thanks for reporting.
A fix has now been merged and will soon be available in the dev branch.
