### ISSUE TITLE
editor: Game window not automatically focused in 1.6.0 (stable) on Mac OS

### ISSUE THREAD

**Issue by pranavraja** [defold/defold#8066]
**Describe the bug**
When running a game with Cmd+B on Mac, the game window does not focus in 1.6.0
Working as expected in 1.5.0

**To Reproduce**
Download `Defold-arm64-macos.dmg` from 1.6.0 (stable) - https://github.com/defold/defold/releases/tag/1.6.0
Build and run an empty project with Cmd+B.
Observe game window is not focused.

Download `Defold-arm64-macos.dmg` from 1.5.0 (stable) - https://github.com/defold/defold/releases/tag/1.5.0
Build and run an empty project with Cmd+B.
Observe game window is focused as expected.

**Expected behavior**
The game window focuses when run

**Defold version**
1.6.0

**Platforms:**
macOS (arm)

**Comment by AGulev** [comment]
What is your macOS version?

**Comment by pranavraja** [comment]
14.0 (23A344)
Apple M2 chip

**Comment by pranavraja** [comment]
Tested a few different versions and 1.5.1-alpha also doesn't correctly focus the game window, so maybe it's one of [these changes](https://github.com/defold/defold/compare/1.5.0...1.5.1-alpha)?

**Comment by ufgo** [comment]
same problem - mac OS Sanoma. Defold 1.6.0

**Comment by massung** [comment]
Just noting I have the same issue as of 1.6.0 running Sonoma, but I only updated to Sonoma last night and it was happening with Ventura as well.
