### ISSUE TITLE
Fonts: make the ASCII character set optional

### ISSUE THREAD

**Issue by aglitchman** [defold/defold#8070]
**Is your feature request related to a problem? Please describe (REQUIRED):**
Usually we use several fonts in our games to nicely display different numerical information (damage value, speed dial and so on). And Defold includes **all ASCII characters in fonts**. However, for this case, it doesn’t make sense to store unused glyphs in the fonts . Especially if it’s a web game where the download size matters.

**Describe the solution you'd like (REQUIRED):**
Add an option to not include ASCII characters, only those specified in Extra Chars. To avoid using third party tools as in the link below.

**Describe alternatives you've considered (REQUIRED):**
https://forum.defold.com/t/big-list-of-defold-pro-tips/1519/111?u=aglitchman

**Comment by zarkua** [comment]
yeah, sounds kind of usefull

**Comment by Lampogolovii** [comment]
yes! it would be great to have this feature
