### ISSUE TITLE
Functions to identify hash, vector3 and other `userdata` types

### ISSUE THREAD

**Issue by aglitchman** [defold/defold#8071]
**Is your feature request related to a problem? Please describe (REQUIRED):**
Data type checking is often needed for convenient code organisation. Unfortunately, `type(variable)` always returns `userdata` for hash, vector3 and other types built into Defold.

```lua
    assert(type(self.position) == "userdata")
    assert(type(self.body_id) == "userdata")
    assert(type(self.collision_url) == "userdata")
    assert(type(self.rotation) == "userdata")
```

You have to write it that way and guess what's inside the variables.

**Describe the solution you'd like (REQUIRED):**
It would be much more understandable if you could write it like this:

```lua
    assert(types.is_vector3(self.position))
    assert(types.is_hash(self.body_id))
    assert(types.is_url(self.collision_url))
    assert(types.is_quat(self.rotation))
```

**Describe alternatives you've considered (REQUIRED):**
I have added similar features for Scene3D and it has proven to be very handy in game development.
https://github.com/indiesoftby/defold-scene3d/blob/main/scene3d/src/extension.cpp#L12

**Comment by ekharkunov** [comment]
Hi @britzl @AGulev !
I want to implement solution for that task.
Purposed API 
part 1
```
types.is_vector(var)
types.is_matrix4(var)
types.is_vector3(var)
types.is_vector4(var)
types.is_quat(var)
types.is_hash(var)
types.is_url(var)
```

Can be also added to cover all user types that defined in engine:
part 2
```
types.is_go_script(var)
types.is_go_script_instance(var)
types.is_buffer(var)
types_is_buffer_stream(var)
types.is_node_proxy(var)
types.is_gui_script(var)
types.is_gui_script_instance(var)
types.is_render_script(var)
types.is_render_script_instance(var)
types.is_render_script_predicate(var)
types.is_render_constant_buffer(var)
types.is_render_constant_buffer_array(var)
```
Opened questions:
1. Should I implement API from part 2?
2. `types.is_vector()` should return true if type is vector3 or vector4? I think yes.
3. `types.is_url()` should return true if `var` is valid url string like "level1:/observer#main_camera"?
4. `types.is_node_proxy()` should be available only from gui script context?

**Comment by britzl** [comment]
I am concerned with engine size. We are adding a lot of new features now and the engine size is growing (albeit slowly).

I very much like the simplicity of `type("foo") == "string"` and would love to see something similar for the Defold types. 

* Could we monkey patch `_G.type` to add support for Defold types? This would probably break a lot of code relying on type() returning "userdata"...
* Could we introduce a new `_G.dtype` or `_G.defoldtype` which would return the standard types AND alternative types for our known userdata obejcts?

**Comment by ekharkunov** [comment]
What I see from my point of view:
1. It can be implemented as separate extension because almost all APIs from part 1 presented in dmsdk.
2. It can be implemented as engine modules which can be exclude via appmanifest.
3. I also thought about `type()` function. IMHO, I'd prefer to introduce separate global function like `defoldtype`.
