### ISSUE TITLE
Failed to bundle in Linux Ubuntu 22.04.3

### ISSUE THREAD

**Issue by ivanquirino** [defold/defold#8081]
**Describe the bug (REQUIRED)**
Failed to bundle in Linux Ubuntu 22.04.3

Build error:
```
java.lang.IllegalArgumentException: Missing extension in name ''
```

![image](https://github.com/defold/defold/assets/3946025/f0304605-6c86-4b33-978c-88cc8ad3d2dd)

**To Reproduce (REQUIRED)**
Project created on Windows, uploaded to github. Trying to bundle on linux.
Projects > Bundle > Linux Application
Try to bundle, get error above.

**Expected behavior (REQUIRED)**
Bundle correclty

**Defold version (REQUIRED):**
  - Version 1.6.0

**Platforms (REQUIRED):**
 - Platforms: Windows, Linux
 - OS: Ubuntu 22.04.03
 - Device: Editor

**Comment by britzl** [comment]
What does the editor logs say? https://defold.com/manuals/editor/#editor-logs

**Comment by ivanquirino** [comment]
There seems to be no error in the log.

Log:
[editor2.2023-10-04.log](https://github.com/defold/defold/files/12803359/editor2.2023-10-04.log)

Project:
[elementalmasters.zip](https://github.com/defold/defold/files/12803358/elementalmasters.zip)

**Comment by ivanquirino** [comment]
Ok, I figured it out. I had an empty 'test.material' file, not used in any collection. Maybe when bundling it tries to bundle the material and can't find any vertext or shader programs, and then gives the missing extension error
I deleted the file and got it to bundle again.

**Comment by ivanquirino** [comment]
> > Ok, I figured it out. I had an empty 'test.material' file, not used in any collection. Maybe when bundling it tries to bundle the material and can't find any vertext or shader programs, and then gives the missing extension error I deleted the file and got it to bundle again.
> 
> So why does Defold try to bundle a material that is not in use anywhere in a project?

Maybe because you may dinamically change the material?

**Comment by AGulev** [comment]
That's how bundler works now. It bundles everything and then includes only resources were referenced somewhere into the final bundle.

We will change it at some point https://github.com/defold/defold/issues/6293

**Comment by britzl** [comment]
There's some confusion with terminology here, with regard to build vs bundle.

We currently *build* all files but we only *bundle* the files that are actually part of the resource graph.

**Comment by britzl** [comment]
> We currently _build_ all files but we only _bundle_ the files that are actually part of the resource graph.

Or actually not even what I wrote is correct :-)

We first build everything. Then we walk the resource graph of all built files and only include the files which are actually referenced from the bootstrap collection when we build the archive. The resource archive is then included when we bundle the final application.
