### ISSUE TITLE
Easier way to install Linux shortcut

### ISSUE THREAD

**Issue by ivanquirino** [defold/defold#8095]
**Is your feature request related to a problem? Please describe (REQUIRED):**
Users have to create their own .desktop file on Linux to create a desktop shortcut. We could provide that.

**Describe the solution you'd like (REQUIRED):**
Add an entry to the Help menu to create a .desktop file, just like JetBrains does:
![Screenshot from 2023-10-05 15-36-44](https://github.com/defold/defold/assets/3946025/12da9579-1589-4f33-a37f-34d51ddcf584)

**Describe alternatives you've considered (REQUIRED):**
* Add to the package an icon image file,  .desktop file and a shell script to setup this for the user. No editor code changes.

**Additional context (OPTIONAL):**
Related forum posts:
https://forum.defold.com/t/shortcut-for-linux/6035
https://forum.defold.com/t/start-linux-client-with-a-double-click/3691/5

I would love some guidance to get me started to make this happen

**Comment by vlaaad** [comment]
Hi! I think it makes sense to implement it similarly to IDEA's Create Desktop Entry action (see [the implementation](https://github.com/JetBrains/intellij-community/blob/master/platform/platform-impl/src/com/intellij/ide/actions/CreateDesktopEntryAction.java) for inspiration). 

To get started, please see the editor's [README.md](https://github.com/defold/defold/blob/editor-dev/editor/README.md), particularly setup and build/REPL instructions. The editor is written in Clojure, it's a fun language that is easy to start using with the REPL, though it might feel alien at the beginning. We work with the editor by running it and connecting to it using the REPL, you can find some guides to get started in the same readme file (Intellij IDEA+Cursive or Vscode+Calva guides)

**Comment by vlaaad** [comment]
There is also [a small gist](https://gist.github.com/matgis/a94a4b2a8c6ea7865b656018a8253f67) explaining how to start interacting with the editor from code written by @matgis

**Comment by vlaaad** [comment]
If you want some pointers on how to add new commands to the editor: 
- for command definition, search for `handler/defhandler` uses
- for adding commands into the menu bar, search for `handler/register-menu! ::menubar`

**Comment by ivanquirino** [comment]
Thanks @vlaaad! Fortunately, I have some familiarity with Clojure and Java. It could be implemented that way like JetBrains's, or calling a shell/python script from the editor. I think the second option would have some advantages to maintaining it without having to build the editor, customize for different distros, while giving the user the option to run from cmd line. We could add things like showing and opening recent projects and run with discrete graphics card for notebooks, but first just creating the entry would be good.

**Comment by ivanquirino** [comment]
I want to work on this, but first would like to agree on a solution design.

**Comment by britzl** [comment]
> see [the implementation](https://github.com/JetBrains/intellij-community/blob/master/platform/platform-impl/src/com/intellij/ide/actions/CreateDesktopEntryAction.java) for inspiration

> It could be implemented that way like JetBrains's, or calling a shell/python script from the editor

Seems like they're also using a shell script for this: https://github.com/JetBrains/intellij-community/blob/master/platform/platform-impl/src/com/intellij/ide/actions/CreateDesktopEntryAction.java#L147-L164

**Comment by ivanquirino** [comment]
> Seems like they're also using a shell script for this: https://github.com/JetBrains/intellij-community/blob/master/platform/platform-impl/src/com/intellij/ide/actions/CreateDesktopEntryAction.java#L147-L164

That's right. Interesting that they create it on the fly though.

**Comment by britzl** [comment]
Not sure why really. Harder to maintain and test as a stand alone thing...

**Comment by ivanquirino** [comment]
I'm trying to build the editor using an existing engine and tool , but the following command `python ./scripts/build.py install_ext` asks for `--package-path` or `DM_PACKAGES_URL`. Does the `--package-path` refers to my local Defold install (the one I use to develop games)? Or what should be the `DM_PACKAGES_URL` value?

**Comment by ivanquirino** [comment]
I used my current install as the package path and got through the `install_ext`, but when I run `lein init archived-stable` I get this:
```
clojure.lang.ExceptionInfo: Unable to determine engine version sha from version file, was '1.6.1'
{:exit 128, :out "", :err "fatal: ambiguous argument '1.6.1': unknown revision or path not in the working tree.
```

**Comment by vlaaad** [comment]
@ivanquirino IIRC `DM_PACKAGES_URL` is not needed to build and run the editor, though maybe the command line tools might require it to be set to something. To initialize the editor with `lein init archived-stable`, you need to be on the `editor-dev` branch, which is used for editor development. Does it work on that branch?

**Comment by ivanquirino** [comment]
@vlaaad Your tip about the env var worked. Finally got it, I've set `DM_PACKAGES_URL` to `.` and got `lein init archived-stable` to run and could successfuly build and run the editor. I think it would be good to include this information on the readme for people that just want to contribute to the editor.

**Comment by britzl** [comment]
> I think it would be good to include this information on the readme for people that just want to contribute to the editor.

Good point. But now that I look closer I do not see that the package path is even required when running the `install_ext` command. It is needed for `install_sdk` (platform specific SDKs) and `install_ems` (Emscripten). I actually think the check could be dropped from `install_ext`:

https://github.com/defold/defold/blob/dev/scripts/build.py#L446

Perhaps you'd like to clear out your defold/tmp/dynamo_home and remove that line from build.py and verify that `install_ext` still works and that you are able to launch the editor using an archived stable version of the engine? If it still works then we'd appreciate a PR!

**Comment by ivanquirino** [comment]
> > I think it would be good to include this information on the readme for people that just want to contribute to the editor.
> 
> Good point. But now that I look closer I do not see that the package path is even required when running the `install_ext` command. It is needed for `install_sdk` (platform specific SDKs) and `install_ems` (Emscripten). I actually think the check could be dropped from `install_ext`:
> 
> https://github.com/defold/defold/blob/dev/scripts/build.py#L446
> 
> Perhaps you could clear out your defold/tmp/dynamo_home and remove that line from build.py and verify that `install_ext` still works and that you are able to launch the editor using an archived stable version of the engine? If it still works then we'd appreciate a PR!

Sorry for the late reply, but I tested that and it worked.

**Comment by ivanquirino** [comment]
Work In Progress here: https://github.com/defold/defold/pull/8168
