### ISSUE TITLE
Render targets are broken with Vulkan

### ISSUE THREAD

**Issue by davabase** [defold/defold#8102]
### Expected behavior
The same as OpenGL. Drawing to render textures and then drawing a quad to the screen should work.

### Actual behavior
The quad drawn the screen has wonky results, either the texture is completely transparent or when the camera is moved the screen is filled with a single color. This happens in the stable build and the alpha build.

When I try to render the entire tilemap to the render target it looks like this with Vulkan: [vulkan.webm](https://github.com/defold/defold/assets/69365652/c23b6016-a81d-46ed-8e0d-168a1c98b2fe)

With OpenGL it looks as it should:
![opengl](https://github.com/defold/defold/assets/69365652/52c566ef-fd5f-44e1-b927-ef1fb7cbe264)

### Steps to reproduce
I have a minimum reproducible project: [vulkan_render_targets.zip](https://github.com/defold/defold/files/12836815/vulkan_render_targets.zip)

In the project the player sprite renders correctly to the render target when the backend is set to OpenGL and the sprite does not appear when the backend is set to Vulkan.

Steps to create the project from scratch:
Copy the default render script to a custom one and add a render target and predicates to the init function:
```lua
local color_params = { format = render.FORMAT_RGBA, width = render.get_width(), height = render.get_height() }
local target_params = {[render.BUFFER_COLOR_BIT] = color_params }
self.target = render.render_target("target", target_params)

self.render_to_target_pred = render.predicate({"render_to_target"})
self.render_target_pred = render.predicate({"render_target"})
```

Draw to the render target in the draw function:
```lua
render.set_render_target(self.target)
render.clear({[render.BUFFER_COLOR_BIT] = self.clear_color, [render.BUFFER_DEPTH_BIT] = 1, [render.BUFFER_STENCIL_BIT] = 0})
render.draw(self.render_to_target_pred, {frustum = frustum})
render.set_render_target(render.RENDER_TARGET_DEFAULT)
```

Draw the render target quad at the origin with unit projection.
```lua
render.set_view(vmath.matrix4())
render.set_projection(vmath.matrix4())
render.enable_texture(0, self.target, render.BUFFER_COLOR_BIT)
render.draw(self.render_target_pred)
render.disable_texture(0, self.target)
```

Setup a render target Game Object with a model component and the default quad.dae as the model.

Create a new material with passthrough vertex and fragment shaders and a "render_target" tag to draw the quad using the predicate. Make sure the material has a "view_proj" vertex constant and a texture sampler in slot 0. Assign the material to the quad.

Put the game object at 0,0 in the game collection. Scale the x and y by 2.

Copy the default sprite material and edit the tags so that it only has a "render_to_target" tag so it gets rendered with the predicate. Assign it to the player sprite.

Create an app manifest and set the rendering engine to Vulkan.

<hr/>

<table>
<tr><td>Build time</td><td>2023-10-06T10:03:05.754106</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>3584a3360b63a831529a2df7de0cb0c715374cc0</td></tr>
<tr><td>Defold engine sha</td><td>d9e9c49ab946c058f29a8b688c862d70f30e9c43</td></tr>
<tr><td>Defold version</td><td>1.6.0</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce RTX 3090 Ti/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 537.13</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by Jhonnyg** [comment]
There's an issue with the passthrough.fp shader. The "position" varying doesn't bind to anything on the vertex shader which isn't valid for Vulkan. We try to avoid these things as much as possible, but I haven't found a good cure for this yet. In the meantime I'll add error messages when running so users are notified. The workaround for now is to remove the "varying vec4 position" row in that shader. Here's your example running on windows:

<img width="615" alt="image" src="https://github.com/defold/defold/assets/169640/fb2d9a8c-6dbd-4f58-82d9-7f9aab3b3e27">
