### ISSUE TITLE
Remove editor console max height that was added in

### ISSUE THREAD

**Issue by Qwarr** [defold/defold#8111]
**Is your feature request related to a problem? Please describe (REQUIRED):**
Editor use to have no max height for the console. Now I can't drag it to the top of the screen. I prefer to be able to see a lot of data at once so this change slightly disrupts workflow. 

**Describe the solution you'd like (REQUIRED):**
Revert the limit the max height for the console.

**Describe alternatives you've considered (REQUIRED):**
Add an option to remove it

**Additional context (OPTIONAL):**
![editor_window](https://github.com/defold/defold/assets/2577547/78eaed09-d9a7-43e1-8f67-87ff2909c6f4)

**Comment by britzl** [comment]
I think this a side effect of the change @quangson91 did recently.

**Comment by quangson91** [comment]
@britzl  Yup. You are right.
Sorry for the mistake.
I just create a PR to fix this issue: https://github.com/defold/defold/pull/8112

Please take a look!.

Thanks!

**Comment by Qwarr** [comment]
Awesome thanks for the quick replies!
