### ISSUE TITLE
IDE: Autocomplete is too aggressive

### ISSUE THREAD

**Issue by aglitchman** [defold/defold#8113]
**Describe the bug (REQUIRED)**
This appeared literally a week or two ago in the latest version of the IDE. It is impossible to enter number "5.1", for example.
Why? 
How to disable it? 
It's probably a bug, so I opened this issue as a "bug".

The version of the IDE is the latest: `3584a3360b63a831529a2df7de0cb0c715374cc0`
OS: Windows 10.

What happens is shown in the video on the example of an empty project from the Desktop game template:

https://github.com/defold/defold/assets/193258/f7f68923-57bd-4519-b5e1-c2a2c51a7b51

This bug does not exist in the editor version `bb52dfb7281ef2b03c3462e9a4205abd69fb11b1` (Defold 1.5.0).

**Comment by vlaaad** [comment]
It's a bug!
