### ISSUE TITLE
The sound does not play on a mobile device on the HTML platform.

### ISSUE THREAD

**Issue by megalanthus** [defold/defold#8114]
### Expected behaviour
When starting a sound, the sound is not played on a mobile device on the HTML platform.

### Actual behaviour
If the sound starts playing after a click and a pause of 0.5 seconds, then it plays normally.

### Steps to reproduce
Test project attached
[sound_bug.zip](https://github.com/defold/defold/files/12840728/sound_bug.zip)

### Note
![image](https://github.com/defold/defold/assets/66716124/7c435008-a275-482d-ad46-088b73eec7bd)
console:
<img width="763" alt="not_working" src="https://github.com/defold/defold/assets/66716124/1674a444-dc50-471a-9d2f-57410c5628d9">

Workaround:
![image](https://github.com/defold/defold/assets/66716124/1b6844bd-f66b-43a0-8ba1-c66f7ad54afb)
console:
<img width="762" alt="working" src="https://github.com/defold/defold/assets/66716124/f95fcce2-b039-43ba-8976-12884dd465bd">

<hr/>
<table>
<tr><td>Build time</td><td>2023-10-06T10:03:05.754106</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>3584a3360b63a831529a2df7de0cb0c715374cc0</td></tr>
<tr><td>Defold engine sha</td><td>d9e9c49ab946c058f29a8b688c862d70f30e9c43</td></tr>
<tr><td>Defold version</td><td>1.6.0</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GTX 1060 3GB/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 536.23</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
I believe the input has to be fully processed by the engine AND the browser before you are allowed to play sounds.

What if you do it on `action.released`? The only other option is to add a timer, or take a look at defos.on_interaction() / defos.on_click() (https://github.com/subsoap/defos)

**Comment by megalanthus** [comment]
> I believe the input has to be fully processed by the engine AND the browser before you are allowed to play sounds.
> 
> What if you do it on `action.released`? The only other option is to add a timer, or take a look at defos.on_interaction() / defos.on_click() (https://github.com/subsoap/defos)

The thing is that the sound is not played not only that was launched first, but also any other sounds! Absolutely everything in the entire project! Another question arises, why does this not happen on a desktop PC?
Versions 1.5 and below do not have this problem. Yes, there is a click if the sound is started before the user takes action, but the sound is guaranteed to work!

I tried playing the sound after `action.released` and everything works as expected. But there are still some doubts about whether in this case it is guaranteed to work for everyone and everywhere?

**Comment by Insality** [comment]
The same issue

I updated the game from 1.5.0 to the 1.6.0 Defold version and sounds are not playing in mobile HTML
Rollback to 1.5.0 - sounds are good and playing

**Comment by britzl** [comment]
Most likely related to the Emscripten update and use of their OpenAL wrapper. Related:

* https://github.com/emscripten-core/emscripten/issues/19763
* https://github.com/emscripten-core/emscripten/issues/15883

**Comment by AGulev** [comment]
fixed in beta with https://github.com/defold/defold/pull/8140
