### ISSUE TITLE
Scale along Z-axis does not affect the scale tool

### ISSUE THREAD

**Issue by Dragosha** [defold/defold#8116]
### Expected behaviour
Changing the scale of an object along the Z-axis when dragging along the Z-axis in the editor.

### Actual behaviour

Nothing happens.
Setting "scale_along_z: 1" in the collection does not affect the behaviour of the scale tool. 

### Steps to reproduce
Screencast:

https://github.com/defold/defold/assets/842807/91ce745b-10dd-4441-bd28-8653a39edf87

<hr/>

<table>
<tr><td>Build time</td><td>2023-09-21T15:00:20.665256</td></tr>
<tr><td>Defold channel</td><td>dev</td></tr>
<tr><td>Defold editor sha</td><td>143728d6755653a79bac9b151d4d19be0631cf8d</td></tr>
<tr><td>Defold engine sha</td><td>143728d6755653a79bac9b151d4d19be0631cf8d</td></tr>
<tr><td>Defold version</td><td>1.6.0</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 531.30</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by Dragosha** [comment]
@matgis 
A small clarifying question: I have now checked in the editor, the tool works for GOs created inside the collection, but does not work for GOs as a prototype file added from assets.


https://github.com/defold/defold/assets/842807/5e06ffc3-9557-4063-8757-22404d5f1041

**Comment by Dragosha** [comment]
> Perhaps there is something special going on in the vertex shader of that box that makes it not work? If the scale property changes in the property editor, that could be the issue.

No, the scale property does not change in case of the box.

Do I have the correct version of the editor installed?

![2023-10-11_14-03-18](https://github.com/defold/defold/assets/842807/7d2d7b9a-9be4-47ee-9fbd-8828ab7d45f0)



> Could you post a small test project with the issue?

I'll try to do

**Comment by matgis** [comment]
Oh, I see now you're on the `beta` channel. That branch is semi-stable and won't have the fix. It will be in the `1.6.2` beta, or in the `editor-alpha` channel, which is what you get from our download page.
