### ISSUE TITLE
[Linux] Keyboard shortcuts for increasing/decreasing font size are not working

### ISSUE THREAD

**Issue by paweljarosz** [defold/defold#8127]
On my Ubuntu 20.04 the keyboard shortcuts for increasing/decreasing fonts are not working. Other shortcuts are working. On Windows the Ctrl++ and Ctrl+- shortcuts are working. From menu it is working on Windows and Ubuntu.

The Linux keyboard mapping file from [this manual](https://defold.com/manuals/editor-keyboard-shortcuts/) is not having any shortcut for increasing/decreasing font size (nor a Windows file).

**Expected behavior (REQUIRED):**
Shortcuts are working.

**Defold version (REQUIRED):**
  - Defold 1.6.0

**Platforms (REQUIRED):**
 - Linux (Ubuntu 20.04)

**Workaround (OPTIONAL):**
It is possible to increase and decrease font size using options from menus: View->Increase Font Size and View->Decrease Font Size

**Additional context (OPTIONAL):**

<hr/>

<table>
<tr><td>Build time</td><td>2023-10-06T10:00:24.855519</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>3584a3360b63a831529a2df7de0cb0c715374cc0</td></tr>
<tr><td>Defold engine sha</td><td>d9e9c49ab946c058f29a8b688c862d70f30e9c43</td></tr>
<tr><td>Defold version</td><td>1.6.0</td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) UHD Graphics (CML GT2)</td></tr>
<tr><td>GPU Driver</td><td>2.1 Mesa 21.2.6</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.15.0-86-generic</td></tr>
<table>

**Comment by britzl** [comment]
I bet this issue is related to https://github.com/defold/defold/issues/5047

**Comment by AGulev** [comment]
PR for JavaFx to track https://github.com/openjdk/jfx/pull/1373

**Comment by AGulev** [comment]
related https://github.com/defold/defold/issues/5047

**Comment by AGulev** [comment]
fized in javafx https://github.com/openjdk/jfx/commit/c0757a2ea5977c062b350335c09dd59671f88df5
