### ISSUE TITLE
Add more devices to Debug->Simulate Resolution

### ISSUE THREAD

**Issue by britzl** [defold/defold#8130]
**Is your feature request related to a problem? Please describe (REQUIRED):**
It is convenient to be able to simulate the resolution of popular devices. The list of available devices is outdated and in need of an update. One such option is Nintendo Switch in Undocked mode.

**Describe the solution you'd like (REQUIRED):**
I would like to have a Nintendo Switch menu with choice Undocked with size 1280x720.

**Describe alternatives you've considered (REQUIRED):**
There is a Custom Resolution option but it does not persist.

**Additional context (OPTIONAL):**
Discussed on Discord with user Domarius

**Comment by britzl** [comment]
I believe Nintendo is calling it "Handheld" mode and not "Undocked"

**Comment by britzl** [comment]
Other suggestions:

* The option "iPhone X/XS (1125x2436)" should also list "iPhone 11 Pro", ie iPhone "X/XS/11 Pro (1125x2436)".
* The option "iPhone XS Max (1242x2688)" should add "iPhone 11 Pro Max", ie "iPhone XS Max/11 Pro Max (1242x2688)"
* Add "iPhone 12 Pro Max/13 Pro Max/14 Plus (1284x2778)"
* Add "iPhone 14 Pro Max/15 Plus/15 Pro Max (1290x2796)"

**Comment by britzl** [comment]
Perhaps also

* Steam Deck
   * Handheld (1280x800)

**Comment by ViTalityGH** [comment]
It would be nice if the choice was saved between runs

**Comment by gianmichelemariani** [comment]
I feel like this could be opened to the user rather than hard coding these resolutions, considering how fast they change.
A config file, or something in the game.project specifying the resolutions and the menu entry?

**Comment by AGulev** [comment]
note: we should make it work for all the instances currently run
