### ISSUE TITLE
Mac OS bug when building

### ISSUE THREAD

**Issue by tigerteeth** [defold/defold#8131]
I get this in the build errors when trying to build on mac os 11.4
/builtins/fonts/font-df.fp
Compatability issue: Symbol not found: ZTTNSt3 114basic ifstreamIcNS l1char traitsIcEEEE
Referenced from: /var/folders/k2/qj4g9knn4h70g Onpy_f9kz80000gn/T/1172418357436163645/×86_64-macos/glslc (which was built for Mac OS X 12.0
Expected in: /usr/lib/libc++.1.dylib
in /var/folders/k2/qj4g9knn4h70g_Onpy_f9kz80000gn/T/1172418357436163645/x86_64-macos/glslc

Version: 1.6.0

macbook m1 
os 11.4

**Comment by AGulev** [comment]
fixed in 1.6.2

**Comment by AGulev** [comment]
(sorry, I meant 1.6.1 - beta is available on forum) @tigerteeth

**Comment by tigerteeth** [comment]
THANKS SO MUCH AGULEV!
