### ISSUE TITLE
Add Color Picker in Sprite Properties

### ISSUE THREAD

**Issue by SparkT06** [defold/defold#8136]
**Describe the solution you'd like (REQUIRED):**
Description:
As a user of Defold, I'm currently able to change the color of a sprite programmatically using the self.color = vmath.vector4(1, 1, 1, 1)

Alternatively, I can change the color by modifying the sprite.material. However, first method the script has  to run for visualization. Second option is not that useful as its also not having gui picker interface.

I propose the introduction of a color picker in the sprite properties panel within the Defold editor. This would allow users to easily and intuitively change the color of a sprite directly in the editor, without having to write code.

A color picker is easier for designers and developers who prefer a more visual approach. It would be especially useful for quickly prototyping.

The Color picker option is already available in the Label component , same feature can be implemented in the sprite component as well.
<img width="663" alt="image" src="https://github.com/defold/defold/assets/118836956/adeaf702-e882-44a3-87ff-18a5a4e6d7d2">

**Comment by JustAPotota** [comment]
#7935 would include setting the sprite color.

**Comment by ivanquirino** [comment]
> As a user of Defold, I'm currently able to change the color of a sprite programmatically using the self.color = vmath.vector4(1, 1, 1, 1)

Can you do that? That doesn't appear nowhere in the documentation.

**Comment by britzl** [comment]
> Can you do that? That doesn't appear nowhere in the documentation.

No, that is incorrect. You can change the color of a sprite like this:

`go.set("#mysprite", "tint", vmath.vector4(1, 0, 0, 1))`

The above will break batching of draw calls, but it does work. We also have a new feature with custom vertex attributes which I believe can be used to carry color information, and thus not break batching for all sprites using the same material (you will need a material which takes the new color attribute into account). More about this here: https://defold.com/manuals/material/#attributes

**Comment by SparkT06** [comment]
i tought i have copied this one go.set("#mysprite", "tint", vmath.vector4(1, 0, 0, 1)), should have double checked it.

Thanks.

**Comment by britzl** [comment]
> on init for example, breaks the batch for the entire runtime of the engine?

Correct. The batch will break until you reset the tint.

**Comment by AGulev** [comment]
now it's possible to do using vertex attributes, see https://forum.defold.com/t/defold-1-4-8-has-been-released/73657/8?u=agulev
