### ISSUE TITLE
Black screen, game won't start

### ISSUE THREAD

**Issue by osov** [defold/defold#8171]
I rebuilt the project (html5) from version 1.4.7 to version 1.5.0 (due to problems with sound) and began to receive complaints from users about a black screen and the game does not start, installed analytics and saw the most common errors.

**Defold version (REQUIRED):**
  - 1.4.8(not exactly), 1.5.0, 1.6.1 alpha

**Platforms (REQUIRED):**
 - Platforms: HTML5
 - OS: all
 - Device: all

**Logs (OPTIONAL):**
Top errors:

```
1) abort(Assertion failed: g_Context, at: ../src/opengl/graphics_opengl.cpp,570,OnWindowFocus). Build with -s ASSERTIONS=1 for more info.
<anonymous> in abort on line 1:12355
<anonymous> in ___assert_fail on line 1:25136
<anonymous> in Object.onFocusChanged on line 1:231953
<anonymous> in HTMLCanvasElement.onBlur on line 1:232039

2)abort(Assertion failed: g_Context, at: ../src/opengl/graphics_opengl.cpp,570,OnWindowFocus). Build with -s ASSERTIONS=1 for more info.
<anonymous> in abort on line 1:12355
<anonymous> in ___assert_fail on line 1:25136
<anonymous> in Object.onFocusChanged on line 1:231953
<anonymous> in HTMLCanvasElement.onFocus on line 1:231992

3) memory access out of bounds
<anonymous> in browserIterationFunc on line 1:199151
<anonymous> in Object.runIter on line 1:123334
<anonymous> in Browser_mainLoop_runner on line 1:121831
```

Related mentions:
[https://github.com/defold/defold/issues/7131](https://github.com/defold/defold/issues/7131)

**Comment by d954mas** [comment]
Have problem that look same in my project.

When i make dev build. And disable webgl2 in firefox.
I can see a lot of shader errors than i see that crash.

![2023-10-22_11-17-47](https://github.com/defold/defold/assets/2655263/c73d41e5-7eae-4d59-829a-7325967ffe8f)

**Comment by osov** [comment]
The reason turned out to be that I had uploaded version 1.4.7 on the server, then after a while I rebuilt the game on version 1.6.1 and re-uploaded all the files.
It so happened that the old dmengine.wasm was cached in people’s browsers, but the content files from the archive folder were new.
That's why the crashes happened.
