### ISSUE TITLE
Webgl 1 support for float render targets

### ISSUE THREAD

**Issue by d954mas** [defold/defold#8172]
**Is your feature request related to a problem? Please describe (REQUIRED):**
I have i game that use TEXTURE_FORMAT_RGBA16F and TEXTURE_FORMAT_R32F.

If user use WebGL1 TEXTURE_FORMAT_RGBA16F and TEXTURE_FORMAT_R32F is nil, so looks like it not supported.

I see in code that you check is it m_IsGles3Version.
https://github.com/defold/defold/blob/3f886026e2fdb0189c1df909a7f8092bde006ba9/engine/graphics/src/opengl/graphics_opengl.cpp#L1170

What about extensions?
I see that you enable them. Some of them may worked in webgl1?
emscripten_webgl_enable_extension(emscripten_ctx, "WEBGL_color_buffer_float");
emscripten_webgl_enable_extension(emscripten_ctx, "OES_texture_half_float_linear");
emscripten_webgl_enable_extension(emscripten_ctx, "OES_texture_float");

Can you check that float texture support in webgl 1?
Is it possible?

A have 5% of users at poki.com that use webgl 1

**Describe the solution you'd like (REQUIRED):**
Float texture supported in webgl 1

**Describe alternatives you've considered (REQUIRED):**
Replace float texture with rgba.
It possible for shadows. But not worked for mesh binary animations from texture.

**Additional context (OPTIONAL):**

**Comment by d954mas** [comment]
I fixed it for my project.
Move to rgba textures.

Not sure is someone need this)

**Comment by Mulderua** [comment]
Hey @d954mas Did you have this error?

<img width="980" alt="image" src="https://github.com/defold/defold/assets/12249206/433a1bf4-1bc3-4913-86d3-195e26c16c48">

**Comment by d954mas** [comment]
> Hey @d954mas Did you have this error?
> <img alt="image" width="980" src="https://user-images.githubusercontent.com/12249206/280512767-433a1bf4-1bc3-4913-86d3-195e26c16c48.png">

https://github.com/defold/defold/issues/8171

In my case there was shader errors in webgl1.

Other case cache problem. User use old engine version(from cache), with new game content(download new version)
