### ISSUE TITLE
I Saw some error crash when I do some step with factory

### ISSUE THREAD

**Issue by gdducnguyen** [defold/defold#8179]
![Untitled](https://github.com/defold/defold/assets/40927856/3cd17a9b-b714-4280-b835-4501513b4885)
![Untitled](https://github.com/defold/defold/assets/40927856/7a1aecbb-a34a-4a0d-92b0-7803bc3214fe)
_Is it a private platform, and a platform specific issue? (i.e. would it break your NDA?)<br>
Then please report your issue in the corresponding extension repository!_

**Describe the bug (REQUIRED)**

**To Reproduce (REQUIRED)**
1. Create a factory, check Dynamic Prototype
2. Create a Collection_A contain GO
3. In init function, unload factory, set prototype with path. New prototype is GO, it is an element of Collection_A
4. Start Debug and Crash

**Expected behavior (REQUIRED)**
-Still works on version 1.6.0

**Defold version (REQUIRED):**
  - Version [e.g. 1.6.1]

**Platforms (REQUIRED):**
 - Platforms: [Windows]
 - OS: [Windows 10]
 - Device: [PC]

**Minimal repro case project (OPTIONAL):**
Project link: https://drive.google.com/file/d/1B5oFxgjOafLD5lOsg5Om1KffsyoqmluV/view?usp=sharing

**Logs (OPTIONAL):**
Please provide relevant logs from engine, editor or build server. Learn where the logs are stored [here]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2023-10-24T14:29:00.114047</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>b364f346962cf24b6845a52c0c97beb5deb7a8f1</td></tr>
<tr><td>Defold engine sha</td><td>a90c50928623cf23b3687a7eec05972d11427202</td></tr>
<tr><td>Defold version</td><td>1.6.1</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GTX 1650/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 536.23</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Additional context (OPTIONAL):**
![Untitled](https://github.com/defold/defold/assets/40927856/f5608e26-5b67-495e-9729-2f0129958837)
[crash_log.txt](https://github.com/defold/defold/files/13160662/crash_log.txt)

**Comment by AGulev** [comment]
Could you pls add a minimal test project?

**Comment by gdducnguyen** [comment]
Of Cause, this zip file of project on drive https://drive.google.com/file/d/1B5oFxgjOafLD5lOsg5Om1KffsyoqmluV/view?usp=sharing

**Comment by AGulev** [comment]
@gdducnguyen you try to set prototype which doesn't exist `/res/prefab/player/player`
it should be `/res/prefab/player/player.goc`

@JCash I think it's an issue anyways, because game shouldn't crash in such case but show console mesage or something like that. What do you think?
