### ISSUE TITLE
Bug when open older project and start debug

### ISSUE THREAD

**Issue by gdducnguyen** [defold/defold#8205]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2023-10-31T17:14:15.064388</td></tr>
<tr><td>Defold channel</td><td>alpha</td></tr>
<tr><td>Defold editor sha</td><td>5870920def0881cc56164ccc5622eb7f6d3bcbec</td></tr>
<tr><td>Defold engine sha</td><td>5870920def0881cc56164ccc5622eb7f6d3bcbec</td></tr>
<tr><td>Defold version</td><td>1.6.2</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GTX 1650/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 536.23</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

ERROR Log:
Line 1: Cannot create property=platforms for JavaBean=com.defold.extender.Configuration@22483feb
 in 'string', line 1, column 1:
    context:
    ^
Cannot create property=emitSwiftHeaderCmd for JavaBean=com.defold.extender.PlatformConfig@3f832e38
 in 'string', line 116, column 5:
        env:
        ^
Unable to find property 'emitSwiftHeaderCmd' on class: com.defold.extender.PlatformConfig
 in 'string', line 161, column 25:
        emitSwiftHeaderCmd: '{{env.PLATFORMSDK_DIR}}/XcodeDe ... 
                            ^

**Comment by britzl** [comment]
It looks like you are using the 1.6.2 alpha version. Are you also using build-stage.defold.com as build server (check project preferences). Unless you really need a 1.6.2 alpha feature I suggest that you use the 1.6.1 stable and build.defold.com

**Comment by gdducnguyen** [comment]
yes. I have an bug issue of version 1.6.1, and no search issue I was post. So I try new version to continue work if issue was fixed
