### ISSUE TITLE
Editor crash by call stack

### ISSUE THREAD

**Issue by gdducnguyen** [defold/defold#8206]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2023-10-24T14:29:00.114047</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>b364f346962cf24b6845a52c0c97beb5deb7a8f1</td></tr>
<tr><td>Defold engine sha</td><td>a90c50928623cf23b3687a7eec05972d11427202</td></tr>
<tr><td>Defold version</td><td>1.6.1</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GTX 1650/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 536.23</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

### Project link
https://drive.google.com/file/d/1B5oFxgjOafLD5lOsg5Om1KffsyoqmluV/view?usp=drive_link

### Crash Log
ERROR:CRASH: CALL STACK:

ERROR:CRASH:  0 0x7FF6C96A6500 dmCrash::GenerateCallstack D:\a\defold\defold\engine\crash\src\backtrace_win32.cpp:144

ERROR:CRASH:  1 0x7FF6C9A285D8 _seh_filter_exe /tmp/job15883500003591164893/minkernel/crts/ucrt/src/appcrt/misc/exception_filter.cpp:219

ERROR:CRASH:  2 0x7FF6C9A77288 `__scrt_common_main_seh'::`1'::filt$0 d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:304

ERROR:CRASH:  3 0x7FF6C99F1440 __C_specific_handler d:\agent\_work\4\s\src\vctools\crt\vcruntime\src\eh\riscchandler.cpp:290

ERROR:CRASH:  4 0x7FF97E611FB0 __chkstk <unknown>:0

ERROR:CRASH:  5 0x7FF97E5C1020 RtlRaiseException <unknown>:0

ERROR:CRASH:  6 0x7FF97E610BD0 KiUserExceptionDispatcher <unknown>:0

ERROR:CRASH:  7 0x7FF6C98D2B00 dmGameSystem::FactoryComp_SetPrototype D:\a\defold\defold\engine\gamesys\src\gamesys\scripts\script_factory.cpp:424

ERROR:CRASH:  8 0x7FF6C9607CDE lj_BC_FUNCC <unknown>:0

ERROR:CRASH:  9 0x7FF6C969DA80 lua_pcall <unknown>:0

ERROR:CRASH: 10 0x7FF6C96CF480 dmScript::PCallInternal D:\a\defold\defold\engine\script\src\script.cpp:1388

ERROR:CRASH: 11 0x7FF6C96CC210 dmScript::InvokeCallback D:\a\defold\defold\engine\script\src\script.cpp:1780

ERROR:CRASH: 12 0x7FF6C9795B80 dmScript::LuaTimerCallback D:\a\defold\defold\engine\script\src\script_timer.cpp:517

ERROR:CRASH: 13 0x7FF6C97946D0 dmScript::UpdateTimers D:\a\defold\defold\engine\script\src\script_timer.cpp:228

ERROR:CRASH: 14 0x7FF6C9794670 dmScript::TimerUpdateScriptWorld D:\a\defold\defold\engine\script\src\script_timer.cpp:460

ERROR:CRASH: 15 0x7FF6C96CB110 dmScript::UpdateScriptWorld D:\a\defold\defold\engine\script\src\script.cpp:1127

ERROR:CRASH: 16 0x7FF6C972EBA0 dmGameObject::CompScriptUpdate D:\a\defold\defold\engine\gameobject\src\gameobject\comp_script.cpp:254

ERROR:CRASH: 17 0x7FF6C9702AD0 dmGameObject::Update D:\a\defold\defold\engine\gameobject\src\gameobject\gameobject.cpp:2577

ERROR:CRASH: 18 0x7FF6C9773C70 dmEngine::StepFrame D:\a\defold\defold\engine\engine\src\engine.cpp:1564

ERROR:CRASH: 19 0x7FF6C976EE40 dmEngineUpdate D:\a\defold\defold\engine\engine\src\engine.cpp:2099

ERROR:CRASH: 20 0x7FF6C97746B0 dmEngine::RunLoop D:\a\defold\defold\engine\engine\src\engine_loop.cpp:83

ERROR:CRASH: 21 0x7FF6C9694220 engine_main D:\a\defold\defold\engine\engine\src\engine_main.cpp:148

ERROR:CRASH: 22 0x7FF6C99F0FF4 __scrt_common_main_seh d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288

ERROR:CRASH: 23 0x7FF97CFC7020 BaseThreadInitThunk <unknown>:0

ERROR:CRASH: 24 0x7FF97E5C2630 RtlUserThreadStart <unknown>:0

ERROR:CRASH: Lua Callstack:

ERROR:CRASH:   res/code/handle/common/g.lua:85: in function load_prototype

ERROR:CRASH:   res/code/handle/common/main.script:52: in function <res/code/handle/common/main.script:51>

ERROR:CRASH: 

INFO:CRASH: Successfully wrote Crashdump to file: C:\Users\84985\AppData\Roaming\Defold/_crash
ERROR:CRASH: CALL STACK:

ERROR:CRASH:  0 0x7FF6C98D2B00 dmGameSystem::FactoryComp_SetPrototype D:\a\defold\defold\engine\gamesys\src\gamesys\scripts\script_factory.cpp:424

ERROR:CRASH:  1 0x7FF6C9607CDE lj_BC_FUNCC <unknown>:0

ERROR:CRASH:  2 0x7FF6C969DA80 lua_pcall <unknown>:0

ERROR:CRASH:  3 0x7FF6C96CF480 dmScript::PCallInternal D:\a\defold\defold\engine\script\src\script.cpp:1388

ERROR:CRASH:  4 0x7FF6C96CC210 dmScript::InvokeCallback D:\a\defold\defold\engine\script\src\script.cpp:1780

ERROR:CRASH:  5 0x7FF6C9795B80 dmScript::LuaTimerCallback D:\a\defold\defold\engine\script\src\script_timer.cpp:517

ERROR:CRASH:  6 0x7FF6C97946D0 dmScript::UpdateTimers D:\a\defold\defold\engine\script\src\script_timer.cpp:228

ERROR:CRASH:  7 0x7FF6C9794670 dmScript::TimerUpdateScriptWorld D:\a\defold\defold\engine\script\src\script_timer.cpp:460

ERROR:CRASH:  8 0x7FF6C96CB110 dmScript::UpdateScriptWorld D:\a\defold\defold\engine\script\src\script.cpp:1127

ERROR:CRASH:  9 0x7FF6C972EBA0 dmGameObject::CompScriptUpdate D:\a\defold\defold\engine\gameobject\src\gameobject\comp_script.cpp:254

ERROR:CRASH: 10 0x7FF6C9702AD0 dmGameObject::Update D:\a\defold\defold\engine\gameobject\src\gameobject\gameobject.cpp:2577

ERROR:CRASH: 11 0x7FF6C9773C70 dmEngine::StepFrame D:\a\defold\defold\engine\engine\src\engine.cpp:1564

ERROR:CRASH: 12 0x7FF6C976EE40 dmEngineUpdate D:\a\defold\defold\engine\engine\src\engine.cpp:2099

ERROR:CRASH: 13 0x7FF6C97746B0 dmEngine::RunLoop D:\a\defold\defold\engine\engine\src\engine_loop.cpp:83

ERROR:CRASH: 14 0x7FF6C9694220 engine_main D:\a\defold\defold\engine\engine\src\engine_main.cpp:148

ERROR:CRASH: 15 0x7FF6C99F0FF4 __scrt_common_main_seh d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288

ERROR:CRASH: 16 0x7FF97CFC7020 BaseThreadInitThunk <unknown>:0

ERROR:CRASH: 17 0x7FF97E5C2630 RtlUserThreadStart <unknown>:0

ERROR:CRASH: Lua Callstack:

ERROR:CRASH:   res/code/handle/common/g.lua:85: in function load_prototype

ERROR:CRASH:   res/code/handle/common/main.script:52: in function <res/code/handle/common/main.script:51>

ERROR:CRASH: 

INFO:CRASH: Successfully wrote MiniDump to file: C:\Users\84985\AppData\Roaming\Defold/_crash.dmp

**Comment by AGulev** [comment]
I don't understand why did you open the same issue again

you use wrong resource prototype path `/res/prefab/player/player` instead of `/res/prefab/player/player.goc`
you have to fix that. 

The crash itself is already fixed in 1.6.2 (next version) https://github.com/defold/defold/issues/8179
