### ISSUE TITLE
java.lang.OutOfMemoryError: Required array length 2147483639 + 9 is too large

### ISSUE THREAD

**Issue by vradyna-ms** [defold/defold#8219]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2023-10-10T06:48:54.384007</td></tr>
<tr><td>Defold channel</td><td>dev</td></tr>
<tr><td>Defold editor sha</td><td>aa5089a770bba1605be131cf46d32784dc37a597</td></tr>
<tr><td>Defold engine sha</td><td>aa5089a770bba1605be131cf46d32784dc37a597</td></tr>
<tr><td>Defold version</td><td>1.5.0</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"d1dc66bd42534543a18d8c32454bfc5d"'>d1dc66bd42534543a18d8c32454bfc5d</a></td></tr>
<tr><td>GPU</td><td>Apple M2 Max</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 83.1</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>13.6</td></tr>
<table>

**Comment by vradyna-ms** [comment]
I am getting this error randomly: when opening the Defold project or when changing the game.project file, or during other actions. The issue could possibly be connected to the large files generated after working with the lmprof extension (mem.json file) and possibly Defold tries to do some operations with them.

**Comment by AGulev** [comment]
Add path to this file into `.defignore` file.

**Comment by AGulev** [comment]
@vradyna-ms let me know if it helps and we can close the issue

**Comment by vradyna-ms** [comment]
@AGulev  Thank you. Please close it
