### ISSUE TITLE
Add beta and release build server urls in editor

### ISSUE THREAD

**Issue by d954mas** [defold/defold#8224]
**Is your feature request related to a problem? Please describe (REQUIRED):**
I change build server url to beta build server. Now i do not remember release build server url(

https://build.defold.com
https://build-stage.defold.com

**Describe the solution you'd like (REQUIRED):**
Add urls examples in editor. Mb as text, or mb as buttons(beta, release servers)

![2023-11-08_14-53-59](https://github.com/defold/defold/assets/2655263/d7ada22d-2190-4400-87e5-2046a02df2ba)

**Comment by vlaaad** [comment]
Idea: we could use a text-field placeholder like `e.g. https://build-stage.defold.com or https://build.defold.com`

**Comment by dri-richard** [comment]
See also https://github.com/defold/defold/issues/7393

**Comment by AGulev** [comment]
@vlaaad I think we should have a checkbox `Change automatically depends on channel` 

- if it's ON :  
  - The input field isn't editable and shows only current extender
  - if it's `stable` or `editor-alpha` it is `https://build.defold.com/ `
  - for `alpha` and `beta` it is `https://build-stage.defold.com/`
- if it's OFF:
   - the field is editable
   - we just use what user write into this edit field

**Comment by AGulev** [comment]
I think we can close it now, and open a new one if it's not enough
