### ISSUE TITLE
Failed to rename ‘._httptmp’ to ‘’

### ISSUE THREAD

**Issue by d954mas** [defold/defold#8234]
**Describe the bug (REQUIRED)**

https://forum.defold.com/t/error-failed-to-rename-httptmp-to-n/74935

I have this error in poki dashboard.

‘’’
“DEFOLD:ERROR:SCRIPT: Failed to rename ‘._httptmp’ to ‘’\n”
‘’’
_httptmp failed to rename to empty string.

8% of user report error.
This is web build. I can't reproduce it.

https://github.com/defold/defold/blob/dev/engine/script/src/script_http_util.h#L26

Looks like path required. But you not set it value in http js version. What value have m_Path now.

So 8% of user get empty string '' in m_path, and 92% of user have 0 in m_path value.

https://github.com/defold/defold/blob/750368cbae6e010f68f8f4c71c244c59f1e0bda2/engine/script/src/script/http_ddf.proto#L40

I can be wrong but in js version of http.requests you can't use path.

Mb you need set it to 0 here?
https://github.com/defold/defold/blob/750368cbae6e010f68f8f4c71c244c59f1e0bda2/engine/script/src/script_http_js.cpp#L80

**To Reproduce (REQUIRED)**
Can't reproduce

**Expected behavior (REQUIRED)**
http.request not try to save something in path l

**Defold version (REQUIRED):**
  - Version 1.6.1

**Platforms (REQUIRED):**
 - Platforms: HTML5

**Comment by AGulev** [comment]
![CleanShot 2024-02-04 at 23 12 14@2x](https://github.com/defold/defold/assets/2209596/d6a4251e-6e11-40b8-beb2-05189e31e051)
the same
