### ISSUE TITLE
Missing autocomplete for certian functions

### ISSUE THREAD

**Issue by CrazyAmphibian** [defold/defold#8245]
**Describe the bug**
certain functions do not appear in the autocomplete.
the one i've found that is very handy to use is `gui.get_text_metrics_from_node()`, but it just refuses to autocomplete it.
i feel like there's other functions with this issue that i just don't know of yet.

**To Reproduce**
1) go into code editor
2) start typing a function
3) function does not appear

**Expected behavior**
For it to appear as something it can autocomplete to

**Defold version**
  - Version 1.6.1

**Comment by AGulev** [comment]
This function is depricated
see https://forum.defold.com/t/missing-documentation-and-autocomplete-for-certian-functions/75001/3?u=agulev
