### ISSUE TITLE
Improve editor by saving the layouts

### ISSUE THREAD

**Issue by tetrahedronix** [defold/defold#8265]
**Is your feature request related to a problem? Please describe (REQUIRED):**
Defold editor workspace should be saved to file by a menu option . 

Default layout 
![Default layout](https://github.com/defold/defold/assets/5469158/cee737a4-b0c3-4019-95de-f6c7d5cc70e2)

Customized layout
![Customized layout](https://github.com/defold/defold/assets/5469158/7719b955-9a86-4c45-ba7f-07237345def0)

**Describe the solution you'd like (REQUIRED):**
When you open a project, Defold should use the file's screen layout rather than the default one. 

**Describe alternatives you've considered (REQUIRED):**
A custom set of workspaces can be saved as a part of the defaults .

**Comment by AGulev** [comment]
Closed as duplicate of https://github.com/defold/defold/issues/8044
