### ISSUE TITLE
Improve the editor by adding an option to close the project

### ISSUE THREAD

**Issue by tetrahedronix** [defold/defold#8266]
**Is your feature request related to a problem? Please describe (REQUIRED):**
There is currently only one option to open a new project with a new standalone window.

**Describe the solution you'd like (REQUIRED):**
Improve the editor by adding an option to close the current project and return to the project manager.

**Describe alternatives you've considered (REQUIRED):**
Add the menu option: "Close project" to the menu File.

**Comment by AGulev** [comment]
closed as duplicate of https://github.com/defold/defold/issues/5653
