### ISSUE TITLE
New builtin render script renders desktop project template differently

### ISSUE THREAD

**Issue by aglitchman** [defold/defold#8272]
**Describe the bug (REQUIRED)**
Defold 1.6.2 introduced a completely new render script. It turned out that [the desktop project template](https://github.com/defold/template-desktop) looks differently:

![image](https://github.com/defold/defold/assets/193258/50284aaf-5d85-48ba-9fbc-26324a350285)

**Expected behavior (REQUIRED)**
How it should look (1.6.1 and before):
![image](https://github.com/defold/defold/assets/193258/32a82800-4cc2-4193-89e1-a049a914b267)

**Defold version (REQUIRED):**
  - Version: 1.6.2

**Platforms (REQUIRED):**
 - Platforms: All.

**Comment by AGulev** [comment]
hm, but default near was -1 before...

**Comment by AGulev** [comment]
Ah, ok. it's because of STATE_DEPTH_TEST wee need now (because we use `model` predicate)
that means template should be fixed. not the default.render_script
