### ISSUE TITLE
Shader optimisation error "Optimization pass failed"

### ISSUE THREAD

**Issue by Morgerion** [defold/defold#8277]
For work I use an old but powerful laptop Lenovo 700-1718K. Starting from Defold 1.6.0 it stopped working when launching projects from the editor. I have installed all system and driver updates, but it didn't help.
At the same time, everything works on Defold version 1.5.0.

### Expected behaviour
In the Defold editor I start from menu **project->build** and everything works.

### Actual behaviour
The editor shows me errors in optimising the default shaders.
It is impossible to get details about these errors.
![image](https://github.com/defold/defold/assets/7888071/55fd172c-3004-4802-b8ae-1359ccb7984c)

### Steps to reproduce
1. Use a laptop with Windows OS and GeForce integrated graphics (preferably five years old).
2. Open any project in the editor and try to run it.

<hr/>

<table>
<tr><td>Build time</td><td>2023-11-23T08:00:43.283261</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>32c7a7f321c3ed0b1ce848fa9e7b500e09a7d311</td></tr>
<tr><td>Defold engine sha</td><td>4e156b7cf37a380122aada30dacbf2b590ead76b</td></tr>
<tr><td>Defold version</td><td>1.6.2</td></tr>
<tr><td>GPU</td><td>GeForce GTX 950M/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 NVIDIA 385.54</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by AGulev** [comment]
@Morgerion Could you please try this version of Defold (it's from dev, it you use spine you have to update it to the latest version). I'm trying to show more info in logs, not sure if I succeed with it

d.defold.com/archive/dev/c40b29b8d2d18d4dcc2ff1d95c718548c10a8741/dev/editor2/Defold-x86_64-win32.zip

**Comment by AGulev** [comment]
If output is the same, then could you pls test this:
[scripts.zip](https://github.com/defold/defold/files/13515784/scripts.zip)
run python script from the `test` folder:
> python test_compact_ids.py

or manually spirv-opt.exe like:
>spirv-opt.exe  -O spirv_files/graphicsfuzz_001.spv -o ~/tmp/optimized.spv




I wanna know if you see some errors or any other info

**Comment by Morgerion** [comment]
> If output is the same, then could you pls test this: [scripts.zip](https://github.com/defold/defold/files/13515784/scripts.zip) run python script from the `test` folder:
> 
> > python test_compact_ids.py
> 
> or manually spirv-opt.exe like:
> 
> > spirv-opt.exe  -O spirv_files/graphicsfuzz_001.spv -o ~/tmp/optimized.spv
> 
> I wanna know if you see some errors or any other info

![image](https://github.com/defold/defold/assets/7888071/8e41ebab-8352-4ff6-92ac-071e708a8b5d)

**Comment by AGulev** [comment]
@Morgerion for now you can fix it by installing 
https://www.microsoft.com/en-us/download/details.aspx?id=52685
Microsoft Visual C++ 2015 Redistributable

we will fix this requirement in the next version of Defold

**Comment by AGulev** [comment]
as a workaround you can put this file into `C:/Windows/System32/` folder

**Comment by AGulev** [comment]
> It didn't work for me to install the distribution from microsoft.

btw, it requires your computer to restart

**Comment by AGulev** [comment]
it's my bad
you should install Redistributable 2019 (not 2015)

**Comment by AGulev** [comment]
For the future:
The problem is that `spirv-opt.exe` requires `vcruntime140_1.dll` which can be statically linked even with `/MT` flag

Some other tools we use in pipeline are fine because they were build using older compiles or don't use functions from these libs.
But `vcruntime140_1.dll` and `vcruntime140.dll` so we can use it from there to avoid any extra dependencies for Defold.

More info is available here: 
https://devblogs.microsoft.com/cppblog/making-cpp-exception-handling-smaller-x64/
https://developercommunity.visualstudio.com/t/vs-1660-dependency-on-vcruntime140-1dll-despite-sp/1059340
