### ISSUE TITLE
Application loading too slow and debugger can't reconnect

### ISSUE THREAD

**Issue by paweljarosz** [defold/defold#8306]
### Expected behaviour
Possible to run game with debugger.

### Actual behaviour
I run an application on a new laptop Windows 11, but it is noticeably slow. Time from internal initialization to the first call to simple print() in only one init() in only one script in the collection is few seconds (or even more than 10 seconds). I can't attach debugger, because Editor shows an error, before it would load. It's a fresh new gaming tier laptop.

### Steps to reproduce

Create and open an empty Defold project. Add even only one script with:
```
function init(self)
    print("INIT")
end
```
to the game object under main.collection. Run it with Project->Build.

<hr/>

<table>
<tr><td>Build time</td><td>2023-12-07T12:03:10.883984</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>c267bff23ee46e1d7d20cc9c445c30fb24514f6d</td></tr>
<tr><td>Defold engine sha</td><td>4e156b7cf37a380122aada30dacbf2b590ead76b</td></tr>
<tr><td>Defold version</td><td>1.6.2</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"ad622105865d4560ac66693dce393f6b"'>ad622105865d4560ac66693dce393f6b</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon 780M Graphics</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 Compatibility Profile Context 23.9.3.230915</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 11</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
```
editor.debugging.mobdebug$connect_BANG_$fn__60534.invoke.class clojure.lang.ExceptionInfo: Failed to connect to debugger on localhost:8172
    at editor.debugging.mobdebug$connect_BANG_$fn.invoke(mobdebug.clj:159)
    at clojure.lang.AFn.run(AFn.java:22)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.lang.Thread.run(Thread.java:833)
```

**Comment by britzl** [comment]
> I can't attach debugger, because Editor shows an error, before it would load

Hmm, firewall or antivirus? From which location are you running your project? Somewhere in user home?



> I run an application on a new laptop Windows 11, but it is noticeably slow.

This is also strange. It feels like the OS is getting in the way. Possibly blocking a synchronous network connection on startup. Does this also happen in a bundled release build?

**Comment by paweljarosz** [comment]
Yes, thank you! It was Windows Defender that was most probably the issue, because it had default setup. I allowed Defold and dmengine.exe to access networks and now it works as I used to ;)
