### ISSUE TITLE
Defining clear color in game.project has no effect at runtime

### ISSUE THREAD

**Issue by totebo** [defold/defold#8308]
_Is it a private platform, and a platform specific issue? (i.e. would it break your NDA?)<br>
Then please report your issue in the corresponding extension repository!_

**Describe the bug (REQUIRED)**
Setting these values in game.project flashes green, then reverts to black:

```
[render]
clear_color_green = 1.0
```

![Screenshot 2023-12-11 at 09 50 37](https://github.com/defold/defold/assets/4493302/cce6a804-d88d-41e8-a464-908747b46fff)

With this error in the console:
`WARNING:DLIB: Unable to convert '0.99' to int`

**To Reproduce (REQUIRED)**
Run project.

**Expected behavior (REQUIRED)**
Clear color values should work at runtime.

**Defold version (REQUIRED)

1.6.2

![Screenshot 2023-12-11 at 09 52 43](https://github.com/defold/defold/assets/4493302/09453b23-91b7-4d32-9116-ff1dbeaae6bb)
:**

**Platforms (REQUIRED):**
macOS

**Minimal repro case project (OPTIONAL):**
[My Project.zip](https://github.com/defold/defold/files/13633737/My.Project.zip)

**Workaround (OPTIONAL):**
Setting clear color with code.

**Comment by AGulev** [comment]
it's fixed in 1.6.3 (brta today later)

**Comment by totebo** [comment]
That was quick! :)
