### ISSUE TITLE
Linux ARM64 (AArch64) as target platform

### ISSUE THREAD

**Issue by aglitchman** [defold/defold#8311]
**Is your feature request related to a problem? Please describe (REQUIRED):**
ARM processors are becoming more and more common, not only in mobile devices. It would be cool to be able to build a Defold game for Linux ARM64, not just x86_64. 

What kind of target devices are these?
- SBC (single-board computer) devices like RPi and retro handhelds.
- desktop computers. This is probably only Chromebooks on ARM with Linux kernel installed for now?
- servers.

**Describe the solution you'd like (REQUIRED):**
Add the arm64 option to the architectures of the Linux platform.

**Comment by aglitchman** [comment]
Most SBC devices do not use X11, so they will require DRM support for graphics output and keyboard handling. I'll make a separate issue on this and it comes out that it's great that @Jhonnyg is working on isolating all platform code into `dmPlatform`.

**Comment by KnedlikMCPE** [comment]
I'd appreciate this being a thing as a user of Asahi Linux on an M1 MacBook Pro - the OpenGL support is more mature than MacOS at this point.

**Comment by JCash** [comment]
Fyi, I've started adding arm64-linux as a target platform.

**Comment by aglitchman** [comment]
For someone who wants to build a cross-build on x86 on Linux or WSL2, here are tips from me:
1. Build the engine on x86 first, so you know you have the environment set up correctly.
2. `clang` (this one https://github.com/llvm/llvm-project/releases/download/llvmorg-16.0.0/clang+llvm-16.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz) knows how to compile to aarch64, so you just need to install some packages for arm64 to link the binaries. Specifically for Ubuntu 22.04 I did it this way:

```bash
# add new sources
# do that as root, i.e. sudo su
dpkg --add-architecture arm64 && sed -i -E 's/^deb /deb [arch=amd64] /' /etc/apt/sources.list && \
  echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports jammy main restricted universe multiverse" >> /etc/apt/sources.list && \
  echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports jammy-updates main restricted universe multiverse" >> /etc/apt/sources.list && \
  echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports jammy-security main restricted universe multiverse" >> /etc/apt/sources.list

# install required packages
apt install --no-install-recommends libx11-dev:arm64 libxi-dev:arm64 libxext-dev:arm64 libxcb-xkb-dev:arm64 libglu1-mesa-dev:arm64 libgl1-mesa-dev:arm64 mesa-common-dev:arm64 libopenal-dev:arm64 libxrandr-dev:arm64
```

3. Build the engine
```
./scripts/build.py build_engine --platform=arm64-linux --skip-tests --skip-docs -- --skip-build-tests --skip-apidocs
```

4. You can run it locally using qemu, i.e.
```
# install: `apt install qemu-user`
qemu-aarch64 -L /usr/aarch64-linux-gnu ./tmp/dynamo_home/bin/arm64-linux/dmengine_headless
qemu-aarch64 -L /usr/aarch64-linux-gnu ./tmp/dynamo_home/bin/arm64-linux/dmengine
```
