### ISSUE TITLE
1.6.3 beta - `Could not find '@render' socket` error in a new empty project

### ISSUE THREAD

**Issue by ReanimatorXP** [defold/defold#8316]
I don't know how critical this error is. I encountered it on a clean empty project without any dependecies and scripts using 1.6.3 beta. And in the version 1.6.2 there is no such error.

1.6.3 beta
![image](https://github.com/defold/defold/assets/24944063/d80c27bc-7400-4d5e-94aa-687dda0c65f6)

1.6.2 editor-alpha, same project
![image](https://github.com/defold/defold/assets/24944063/81da5454-3244-41bd-af1d-200fbf666245)

<hr/>

<table>
<tr><td>Build time</td><td>2023-12-11T10:43:27.852044</td></tr>
<tr><td>Defold channel</td><td>beta</td></tr>
<tr><td>Defold editor sha</td><td>8e7cc9d35726e91c3cb3f231abdaed2158613183</td></tr>
<tr><td>Defold engine sha</td><td>8e7cc9d35726e91c3cb3f231abdaed2158613183</td></tr>
<tr><td>Defold version</td><td>1.6.3</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GTX 1080/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 536.40</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
Closed via https://github.com/defold/defold/pull/8340
