### ISSUE TITLE
Bob issue with generated lua since 1.6

### ISSUE THREAD

**Issue by haath** [defold/defold#8323]
**Describe the bug**

Since updating Defold to 1.6.0+, bob no longer compiles lua that is generated from Haxe. (using hxdefold)

The same lua code runs fine through the editor, this is only an issue with bob.

Some examples of errors that I'm getting on the corresponding lines of lua:

```lua
Reflect.fields = function(o) 
  local _hx_continue_1 = false;
  while (true) do _hx_do_first_1 = false;
    repeat 
    if (_G.type(o) == "string") then 
      o = String.prototype;
      break;
    else
      do return _hx_field_arr(o) end;
    end;until true -- ERROR main.lua:708 '=' expected near 'true'
    if _hx_continue_1 then 
    _hx_continue_1 = false;
    break;
    end;
    
  end;
end
```

```lua
if (self.cacheEnabled and (result ~= nil)) then 
  local cacheResult = self.pathCache:solve(node.state, goal, result, node.costFromStart, maxCost);
  if (cacheResult) == 0 then 
    do return node end;
  elseif (cacheResult) == 2 then 
    do return nil end;
  elseif (cacheResult) == 3 then 
    result.result = 4;
    do return nil end;else end; -- ERROR main.lua:1050 'end' expected near 'endelse'
end;
```

**To Reproduce**
1. Start with this hxdefold project: [bunnymark#bob_issue](https://github.com/hxdefold/hxdefold-bunnymark/tree/bob_issue)
2. Compile Haxe with: `haxe build.hxml`
    * This generates `main.lua` and the `.script` files
3. Run game through the editor - no issue.
4. Try to build game with bob with: `bob build`
5. Get errors like shown above.

**Expected behavior (REQUIRED)**

**Defold version:**
  - Version 1.6.2

**Platforms:**
 - Platforms: Linux
 - OS: Fedora/Debian
 - Device: PC

**Comment by AGulev** [comment]
@haath could you please upload file you have problems with?

**Comment by AGulev** [comment]
I copy/pasted code snippets you provided into a lua file and tested in 1.6.2 and 1.63 - both work fine.
[one.lua.zip](https://github.com/defold/defold/files/13701960/one.lua.zip)

That would be nice if you can provide full lua file

**Comment by haath** [comment]
Hey, thanks for looking into it!

I am attaching the lua file where I can reproduce the issue.

[main.zip](https://github.com/defold/defold/files/13724734/main.zip)

```sh
$ bob --version
bob.jar version: 1.6.2  sha1: 4e156b7cf37a380122aada30dacbf2b590ead76b  built: 2023-11-22 11:50:30
```

```sh
$ bob build
...
ERROR main.lua:1050 'end' expected near 'endelse'
```

> a full project I can open in defold and build

Just wanna point out again in case it was missed, that this lua file runs fine from the Defold editor.
There is an error only when building with bob...

**Comment by haath** [comment]
Also a small correction to the original issue description. I mentioned that the issue was reproducible with the bunnymark repo but that was not the case. That is because the `Reflect` class was not included in the build due to dead code elimination.

So I created a minimal reproduction case on another branch by forcing the `Reflect` class into the build.
So the minimal reproduction steps are (with Haxe installed):

```haxe
$ git clone -b bob_issue https://github.com/hxdefold/hxdefold-bunnymark.git
$ cd hxdefold-bunnymark
$ haxe build.hxml
$ bob build
```

**Comment by AGulev** [comment]
I was able to reproduce the issue with your Lua file. I prepared a fix (see PR).
I'll talk with the team and try to cherry-pick the fix into the current beta to deliver it as soon as possible.

But I think it's pretty old issue (not 1.6.0+ thing), because code that breaks semicolons were written for a long time ago.

**Comment by haath** [comment]
> but I think it's a pretty old issue (not 1.6.0+ thing), because code that breaks semicolons were written for a long time ago.

Interesting, my build definitely broke from `1.5` to `1.6`, all else being equal.
As you can see in the screenshot from my CI below.

![image](https://github.com/defold/defold/assets/29335643/7b4b198f-20b8-48a3-a609-f1b5f74ca161)

**Comment by AGulev** [comment]
Interesting. Didn't you change haxe version (generated Lua code is the same)?

**Comment by haath** [comment]
Yup, my pipeline looks something like this:

```yml
steps:
- name: haxe
  image: haxe:4.3-bullseye
  commands:
  - haxe build ....

- name: html5
  image: gmantaos/defold:1.4
  commands:
  - bob build html5...
```

So my Haxe version is independent of my Defold version, and I haven't changed that.

And both commits `Update defold version` and `Revert to Defold 1.5` that you see in the screenshot were built today with `haxe:4.3-bullseye`. So I think we can rule out that some other improperly-versioned dependency changed between the builds :smile: 

---

But to be extra sure I downloaded bob version `1.5.0` on my local workspace and tried to build with both bobs without touching the generated lua at all.

```sh
$ bob build
...
ERROR main.lua:611 '=' expected near 'true'

$ java -jar bob_1_5_0.jar build
...
 100% ...done!
```

**Comment by AGulev** [comment]
I've just merged and cherry-picked the fix into beta. I'll let you know when build is done

**Comment by AGulev** [comment]
Now it's available in beta 
1.6.3
beta
4e42322263c8345bc222d71eaedff2b48be50e8e
