### ISSUE TITLE
sys.exists() doesn't exist on defold version 1.4.2 on Windows 11

### ISSUE THREAD

**Issue by Joster1234** [defold/defold#8326]
First time reporting a bug so apologies if I do something wrong. I am storing read only game data in a lua table that will be saved to the players computer, to help prevent bugs I am trying to implement a system that will check to see if the file exists and if not then recreate it using a function. When trying to use sys.exists() (as shown in https://defold.com/ref/sys/#sys.exists:path) the Defold editor doesn't recognise 'exists()' and will return 'attempt to call field 'exists' (a nil value)' error message instead of true or false. I'm still learning Defold so I could be doing something completely wrong so I'll add my code as to help explain what I'm trying to do.
![Screenshot 2023-12-17 151414](https://github.com/defold/defold/assets/154072877/d00c7559-f194-4035-a4e5-27ac74c729f3)
the error message I get:
![Screenshot 2023-12-17 151654](https://github.com/defold/defold/assets/154072877/d631cc87-6636-47ba-8ad5-22e75d590d15)

**Comment by JustAPotota** [comment]
Not a bug, that function was added in 1.6.0.

**Comment by Joster1234** [comment]
@JustAPotota  I'm not stating the feature itself is a bug but instead that as far as I can tell it is no functioning correctly.

**Comment by JustAPotota** [comment]
It’s not functioning correctly because Defold version 1.4.2 doesn’t support it. Use the built-in updater or download the latest version from the [GitHub releases page](https://github.com/defold/defold/releases/tag/1.6.2).

**Comment by Joster1234** [comment]
@JustAPotota  Thanks for your help! I didn't realise I was that many versions behind lol, getting it sorted now.
