### ISSUE TITLE
Project is not built if only 3D physics is in the appmanifest

### ISSUE THREAD

**Issue by aglitchman** [defold/defold#8347]
**Describe the bug (REQUIRED)**
A project can't be built if only 3D physics is in the appmanifest. Steps to reproduce:
1. create appmanifest.
2. leave only 3D physics.
3. try to build the project.

**Defold version (REQUIRED):**
  - Version: 1.6.3 BETA, `e7f5650ebfa0419372015e2091e86e6117f330b0`

**Platforms (REQUIRED):**
 - Platforms: Windows

**Minimal repro case project (OPTIONAL):**
[issue_163_appmanifest.zip](https://github.com/defold/defold/files/13759136/issue_163_appmanifest.zip)

**Logs (OPTIONAL):**
```
lld-link: error: undefined symbol: void __cdecl dmPhysics::GetCollisionShapeRadius2D(void *, float *)
>>> referenced by D:\a\defold\defold\engine\gamesys\src\gamesys\components\comp_collision_object.cpp:1778
>>>               libgamesys.lib(comp_collision_object.cpp.1.o):($LN62)
```
(and other)

Build server is `build-stage.defold.com`, yes.

**Comment by Jhonnyg** [comment]
This is not in beta, the hash is in alpha. Not that it matters :) I’ll take a look in any case, thanks!

**Comment by aglitchman** [comment]
> This is not in beta, the hash is in alpha. Not that it matters :) I’ll take a look in any case, thanks!

I apologise wildly - I miss-clicked when downloading the editor 😬

**Comment by Jhonnyg** [comment]
Haha it’s fine!
