### ISSUE TITLE
Defold on iPad?

### ISSUE THREAD

**Issue by mohfy** [defold/defold#8362]
I see iPads as a very powerful device. For example, the iPad Pro with the M1 chip is powerful due to its integration with Apple's M-series. And since Defold is very lightweight, it'd fit in this portable device.

**Comment by britzl** [comment]
You mean to run the editor on an iPad Pro? This is not in our roadmap. We are not keen on supporting non-desktop platforms such as mobile phones or tablets, for multiple reasons:

* New methods of interaction (eg touch)
* New means of distribution (AppStore, Google Play etc)
* New underlying OS with different IO etc
* The editor is built on Java and JavaFX, and these are not supported on iPad/iPhone OS

**Comment by mohfy** [comment]
What about defold in browser? I feel like it'd be good because many devices will be supported

**Comment by britzl** [comment]
The editor is built using Java, Closure and Javafx, languages and frameworks primarily designed for desktop systems. There is no way these can be run in a browser.
