### ISSUE TITLE
Include an Apple Privacy Manifest

### ISSUE THREAD

**Issue by britzl** [defold/defold#8378]
Apple will require SDKs and tools to include a Privacy Manifest when certain APIs are used

* https://developer.apple.com/documentation/bundleresources/privacy_manifest_files?language=objc
* https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api?language=objc

First step is to identify APIs in Defold which require a Privacy Manifest.

**Comment by britzl** [comment]
We use `fstat()` to find out the size of a file (for instance to memory map the game archive)

**Comment by britzl** [comment]
Remotery uses `mach_absolute_time()`

* https://github.com/defold/defold/blob/dev/engine/dlib/src/remotery/lib/Remotery.c#L383
* https://github.com/defold/defold/blob/dev/engine/dlib/src/remotery/lib/Remotery.c#L407

**Comment by vradyna-ms** [comment]
Hi.
Could you please clarify will Defold merge Privacy Manifests from SDKs and game into one privacy manifest? Or how it will work? 
Thank you in advance

**Comment by britzl** [comment]
We do not yet know how this will work. It seems reasonable that the build pipeline collects all PrivacyInfo.xcprivacy files from extensions and the engine manifest and possibly also a game specific manifest into a single file.

[Apple mentions](https://developer.apple.com/support/third-party-SDK-requirements/) _"when you prepare to distribute your app, Xcode will combine the privacy manifests across all the third-party SDKs used by your app into a single, easy-to-use report. With one comprehensive report that summarizes all the third-party SDKs found in an app, it will be even easier for you to create more accurate Privacy Nutrition Labels."_

Based on the above description it seems more like a convenience function to merge them into one rather than a requirement, especially since it seems like it is the developer's responsibility to use it to set Privacy Nutrition Labels.

**Comment by AGulev** [comment]
https://developer.apple.com/news/?id=3d8a9yyh

https://developer.apple.com/support/third-party-SDK-requirements/

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

**Comment by britzl** [comment]
PR to copy manifest from extender to build output: https://github.com/defold/extender/pull/355
