### ISSUE TITLE
Slice 9 sprites render bug

### ISSUE THREAD

**Issue by rigo128** [defold/defold#8401]
The render of slice 9 sprite does not work correctly.
Version 1.6.3
![image](https://github.com/defold/defold/assets/851731/23f73f3f-3f7e-47c3-89f7-7ec8167d4182)

Test project:
[slice_9_test.zip](https://github.com/defold/defold/files/13929306/slice_9_test.zip)

**Comment by Jhonnyg** [comment]
This has been fixed by https://github.com/defold/defold/pull/8403
