### ISSUE TITLE
Lua compatibility broken. ; in table not worked

### ISSUE THREAD

**Issue by d954mas** [defold/defold#8455]
### Expected behaviour
Lua code worked
### Actual behaviour
https://forum.defold.com/t/defold-1-6-3-has-been-released/75639/34

 http://tpcg.io/_NRFM3D 
Lua code with ; as delimeter in table not worked.

This happened in 1.6.3 in 1.6.2 all worked.
Not reproduced in windows build. Reproduced in web build(luajit worked, lua not ?)

test.script
```
function init(self)
	local t = { a = 1, b = 2, c = 3; d = 4 } print(t.a, t.b, t.c, t.d)
end
```
test.scriptc
```

в
Мfunction init(self)
	local t = { a = 1, b = 2, c = 3  d = 4 } print(t.a, t.b, t.c, t.d)
end

```

```
ERROR:GAMEOBJECT: Error running script: main/test.script:2: '}' expected near 'd'
```

### Steps to reproduce

[lua_163.zip](https://github.com/defold/defold/files/14075859/lua_163.zip)

<hr/>

<table>
<tr><td>Build time</td><td>2024-01-22T12:55:18.742464</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>8b7587e515af2059a5ff40bdd6eea6b08763ff44</td></tr>
<tr><td>Defold engine sha</td><td>37a4a8548850a7243055bb820e45580cfdae5f32</td></tr>
<tr><td>Defold version</td><td>1.6.3</td></tr>
<tr><td>GPU</td><td>AMD Radeon(TM) Graphics</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 Compatibility Profile Context 23.5.2.230523</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by AGulev** [comment]
the issue fixed in 1.6.4  https://github.com/defold/defold/pull/8408
you can test it in alpha https://github.com/defold/defold/releases/tag/1.6.4-alpha
