### ISSUE TITLE
Add API for retrieving the time at the start of the current frame

### ISSUE THREAD

**Issue by redoak** [defold/defold#8470]
**Is your feature request related to a problem? Please describe (REQUIRED):**
In `on_input` it's not possible to get the frame's delta time or the time at the start of the current frame. If I want to calculate the length of time a button was held down, I will need to use `os.time()` or `socket.gettime()`. I would like to retrieve the frame's time since that's what the game logic updates on.

**Describe the solution you'd like (REQUIRED):**
Introduce "engine time", which is the elapsed time since engine start. In C++ I believe this would be calculated from the time retrieved in `m_PreviousFrameTime = dmTime::GetTime()` at the end of `Init(HEngine engine...)`.

_Add API functions_
- `engine.unscaled_time()`: returns the engine time at the start of the current frame, derived from the time produced by `dmTime::GetTime()` in `CalcTimeStep`.
- `engine.time()`: same as above, but as modified by the time step of the current collection proxy. Time needs to be tracked per proxy since the effect of time step will accumulate over time.

Edit: I now prefer a slightly different API, `collectionproxy.time()`, described at the end of my next message below.

**Describe alternatives you've considered (REQUIRED):**
1. Instead of adding new API functions, each input action's data table could have a field with the time (probably epoch time rather than engine time). In case exact input timestamps for input events were to ever be added (as in sub-frame device polling, desired in some rhythm, fighting and shooter games), this solution would fit well.

2. Instead of added multiple new API functions, add a single `engine.get_frame_info()` which returns a table with the desired values. This would more easily accommodate additional values. I describe which values would be useful in **Additional context** below.

3. If the suggested API expansion above is undesired, instead allow native extensions to read the engine start time and current frame's time, allowing a native extension to provide the described functionality.

**Additional context (OPTIONAL):**
In general, it's useful to be able to get the engine time, since we can't accurately calculate it ourselves by accumulating delta time (because of float precision). With it, we can accurately calculate `my_delta = end_time - start_time` etc.

Since delta time is only passed to `update`, it's a hassle to save it for access in `on_message` or `final`, and impossible to access from `on_input` since that's called before `update`.

There are other related values that would be great to have easy access to. Here's a full list, including the ones already described above:
- _engine start time_: needed to convert engine time to epoch time
- _engine time_: as described above.
- _engine delta time_: the dt value that will be or was passed to `update` this frame. For convenience.
- _engine frame count_: the current frame's index (first frame is 1). Useful for debugging and profiling. E.g. if the profiler or another tool were to save frame snapshots, and number them by this value, it would be easy to match them with console log messages, game state frame data etc. Also nice to have when debug-printing, since knowing if two events happened on the same frame or not is often relevant.
- _fixed time_: this would be the engine time of the last `fixed_update`. Allows you to calculate the delta between the last `update` and `fixed_update`. For games that mostly use `fixed_update`, they would generally want to use this value over regular engine time.
- _fixed delta time_: the dt value of `fixed_update`. For convenience.
- _fixed frame count_: useful for the same reasons as engine frame count.

I looked at how Unity exposes time values: https://docs.unity3d.com/ScriptReference/Time.html

**Comment by redoak** [comment]
> > engine start time: needed to convert engine time to epoch time
> 
> So, you want the current time since epoch.

No, I want a time that corresponds to the start of the current frame (rather than the time of the function call). It doesn't matter for my issues if it's measured from engine start or epoch start.

I suggested *engine time* since it can also answer "how much time has passed in the main collection?".

I mentioned *engine start time* since otherwise there's no way to convert between or compare engine time and epoch time, as returned by `dmTime::GetTime()`(however, it appears that there's no Lua function that returns the result of `dmTime::GetTime()`). This would be useful in logs where it might be preferable to write all timestamps in the same epoch, e.g.:
```
[2024.01.29 21:03.111222] new frame; engine time in epoch
[2024.01.29 21:03.333666] handled message foobar; 0.222444s has passed since frame start
```

> Have you considered using [os.clock()](https://www.lua.org/manual/5.1/manual.html#pdf-os.clock) or [socket.gettime()](https://defold.com/ref/socket/#socket.gettime:), and if so, what was the issue with it?

For the "button press duration" scenario I mentioned, these are good enough. But they are of limited usefulness more broadly, since they are only approximately the same as the frame's time, and differs with each call. If I want to write input actions, messages and other events to a table indexed by the frame on which they occurred, using an approximate time becomes cumbersome and error-prone.

For indexing, I can instead implement my own *frame count*: an integer that (ideally) is the same from the first input of the frame to the last post-update message. But the ideal case is impossible since there's no way to run code at the very start or end of a frame. As a result, my frame count will need to have a special condition like "when retrieved from `on_input` you must manually add 1 to the value", and I must organize my collections such that one script is guaranteed to update before all others so that it can increment the frame count.

> Are enough users going to use it, to warrant the extra code incurred to the engine size?

**The smallest possible implementation** I see is to add a single C++ API function that returns `Engine::m_PreviousFrameTime`. Using it I can write a native extension with a function for getting it from Lua, and another function for producing a frame count based on it.

*Something I realized regarding engine time and proxy collections:*

To answer "how much time has passed in this proxy collection?" we would need a *collection time* rather than *engine time*. If we ever change time step, we can no longer answer this by comparing `os.time()`, `socket.gettime()` or engine time at collection init and now.

We can instead accumulate delta time. Letting a single script in the collection handle this is difficult since we can't guarantee `update` order without complicating our collection structure (we can accumulate delta time in every script that needs it though). Regardless, in `on_input` we cannot get the current frame's accumulated delta time. Additionally, the accumulated time will also slowly drift away from the theoretical collection time, and thus other proxies' collection times, because of float precision of dt (unlikely to matter for any user though).

For this reason, perhaps instead of `engine.time()` something like a `collectionproxy.time()` would be more appropriate, if we imagine it can be called on the main collection even though it's not actually a proxy, to get what's essentially engine time.

> My personal feeling is that it's not so much a hassle to store such info in a lua module to allow yourself to access it from anywhere/anytime.

I hope the above explains why it's currently troublesome to achieve all what I want to do.

**Comment by AGulev** [comment]
I re-read everything, I understand what you want, but I don't understand why you want it. 
For the input case, it's easy to solve using:
```
if action.pressed then
  self.pressed_time = socket.gettime()
elseif action.released then
  local held_down_time = self.pressed_time  - socket.gettime()
  -- do something
end
```

What exactly you are going to do with the rest of data you are asking for at `-- do something` place?

**Comment by redoak** [comment]
Here are two use cases, one for *frame count* and the other for *engine time*:
```
function on_input(self, action_id, action)
	-- Save all input actions, indexed by frame count, so that I can replay them
	-- later on (this obviously require the action handling below to be moved to
	-- a separate function etc.)
	input_recorder.add_for_frame(new_api.frame_count(), action_id, action)

	if action.pressed then
		self.pressed_time = socket.gettime()
	elseif action.released then
		local held_down_time = self.pressed_time  - socket.gettime()
		local charged_weapon_damage = held_down_time * 100
		msg.post(enemy, 'hurt', {damage = charged_weapon_damage})
		-- If I were to calculate this damage based on delta time in update or
		-- fixed_update, I would get a slightly different result. In cases where
		-- this matters, having to move the calculation to update adds work and
		-- complicates the code.
	end
end
```

All the values I listed at the end of the original post are not all necessary. I only wrote them down to show all the values that may be of interest or may make up a full API.

The only one that is required to solve my issues the way I prefer and have described, is *engine time*. From it you can produce the frame count, and from that you can produce the fixed engine time.

**Comment by redoak** [comment]
> I don't see enough use for this to warrant new functions in the engine core. You can keep track of most of this using a script and a Lua module or using your own native extension and Lua API.

I prototyped a native extension, incrementing a counter in the extension's `update` callback. It works since it's called before any script's `on_input` is called. I didn't find a way to retrieve the delta time, e.g. from `Engine::m_Stats::m_TotalTime`, to expose it to `on_input`. But as mentioned, calculations needing dt can always be delayed until `update` to work around this.

Feel free to close this issue since I can solve my problem.
