### ISSUE TITLE
Add `editor.delete_directory` function

### ISSUE THREAD

**Issue by astrochili** [defold/defold#8472]
**Context:**
Our users want to be able to delete a folder using the editor script API. Currently, the only way to do it is by returning a shell action. Related to https://github.com/defold/defold/issues/6810 and https://github.com/defold/defold/issues/8425.

**Task:**
Add the `editor.delete_directory(resource_path)` function.

**Expected outcome:**
The users can clean temporary or outdated folders in editor script command without using shell.

**Comment by AGulev** [comment]
please clode this ticket if it's done

**Comment by astrochili** [comment]
I don’t know the workflow. May you have some QA step or something else. If it’s okay I can close the ticket 👍.
