### ISSUE TITLE
Add QuatToEuler and EulerToQuat in dmVMath

### ISSUE THREAD

**Issue by d954mas** [defold/defold#8478]
I spend a lot of time trying to impelemt quat->euler and euler->quat convertion in lua.
My functions worked but not always)

My cases:
1)For BlockyUniverse i use quat->euler convertion to make hp bar in gui always look in camera.(gui only worked with euler)
2) For Blocky Fighting i try to remove roll from quaterion. So i need to convert euler in quat, remove roll, convert euler to quat back.
( try to fix how items look in player hand, this not worked but i try that)

You already have that function in engine:
https://github.com/defold/defold/blob/a11256553ef4bce0f534c227769f6eacd1583ea3/engine/dlib/src/dlib/vmath.h#L82
https://github.com/defold/defold/blob/a11256553ef4bce0f534c227769f6eacd1583ea3/engine/dlib/src/dlib/vmath.h#L142

My suggestions:
1)Add QuatToEuler and EulerToQuat in native api <[dmsdk/dlib/vmath.h](https://github.com/defold/defold/blob/dev/engine/dlib/src/dmsdk/dlib/vmath.h)>
2)Add quat_to_euler and euler_to_quat in vmath(lua)

Workaround
copy QuatToEuler and EulerToQuat in native library

**Comment by britzl** [comment]
Sure, this makes sense! Would you like to create a PR @d954mas ?

**Comment by d954mas** [comment]
I can.
What is the best way to include?

This functions inline in vmath.h with other includes and function.

If I include vmath.h in public api it will be add unnecessary lines

**Comment by britzl** [comment]
> What is the best way to include?

Good question! Let's get some feedback from @JCash

**Comment by Jeroto** [comment]
+1 on this, wanted to get the global z Euler rotation for a game object and using the engine's existing functions for it would be a great help.
I'm also willing to look into making them public-facing in Lua if desired, although my C++ is a little shaky.
