### ISSUE TITLE
HTML5: game crashes if the page isn't allowed to use Gamepad API

### ISSUE THREAD

**Issue by aglitchman** [defold/defold#8479]
**Describe the bug (REQUIRED)**
HTML5 build doesn't run at all if the page is not allowed to use Gamepad API:

```
exception thrown: SecurityError: Failed to execute 'getGamepads' on 'Navigator': Access to the feature "gamepad" is disallowed by permissions policy.,Error: Failed to execute 'getGamepads' on 'Navigator': Access to the feature "gamepad" is disallowed by permissions policy.
    at Object.refreshJoysticks (<anonymous>:1:227193)
    at _glfwSetGamepadCallback (<anonymous>:1:235002)
    at wasm://wasm/006c51a6:wasm-function[3437]:0x110017
    at wasm://wasm/006c51a6:wasm-function[3429]:0x10fc51
    at wasm://wasm/006c51a6:wasm-function[4409]:0x15bdc5
    at wasm://wasm/006c51a6:wasm-function[4398]:0x159e17
    at wasm://wasm/006c51a6:wasm-function[4401]:0x15a6cb
    at wasm://wasm/006c51a6:wasm-function[2859]:0xe2189
    at wasm://wasm/006c51a6:wasm-function[2660]:0xd092c
    at Module._main (<anonymous>:1:264167)
```

More details - https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy/gamepad

It turned out that [FB Playable Preview tool](https://developers.facebook.com/tools/playable-preview/) doesn't allow gamepads and, therefore, any Defold game isn't able to run.

**To Reproduce (REQUIRED)**
Run the game build in an iframe where the Gamepad API is not allowed. 

**Expected behavior (REQUIRED)**
The game should run well.

**Defold version (REQUIRED):**
  - Version: 1.6.3

**Platforms (REQUIRED):**
 - Platforms: HTML5

**Comment by AGulev** [comment]
https://github.com/emscripten-core/emscripten/pull/20890/files
