### ISSUE TITLE
Support delete key shortcut on macOS

### ISSUE THREAD

**Issue by ChuckMayo** [defold/defold#8485]
quick and hopefully easy feature request for yall

**Problem**: on macOS machines, most keyboards have a "delete" key but not a "backspace" key. This means that the backspace key shortcut to delete something in defold doesn't work on macOS

**Propsed Solution**: on macOS machines, support pressing "delete" as an alternative to "backspace"

**Comment by britzl** [comment]
There's an option to specify a custom keymap file. Could you please try this and map "Delete" to "delete-backward" and see if that works as expected on such a keyboard?

https://defold.com/manuals/editor-keyboard-shortcuts/#customizing-shortcuts

**Comment by ChuckMayo** [comment]
> There's an option to specify a custom keymap file. Could you please try this and map "Delete" to "delete-backward" and see if that works as expected on such a keyboard?
> 
> https://defold.com/manuals/editor-keyboard-shortcuts/#customizing-shortcuts

I downloaded and modified the keymap file, set it up in the defold preferences, restarted, but it's not deleting assets in asset browser, or anything from object/collection outline view

**Comment by vlaaad** [comment]
You probably want to do the opposite, i.e. change `:delete` command's shortcut to `Backspace`, which is the key code used by JavaFX when the user presses a button that says "delete" on it...

**Comment by ChuckMayo** [comment]
I got a fresh keymap file, and changed the `:delete` command's shortcut to `Backspace`, but it wasn't working for me.

`Fn` + `delete` also wasn't working, so I tried removing the keymap file from my preferences.

Without the keymap file, `Fn` + `delete` works great in both the asset panel and object outline view.

**Comment by vlaaad** [comment]
Cool, glad you could solve the problem!

**Comment by astrochili** [comment]
To be honest, I'd like to reopen it.

Pressing `Backspace` (now on modern macs it's **Delete** on the keycap, but by code and function it's still **Backspase**) on mac deletes the object in all native apps, if we aren't taklking about text editing.

So this would be great to have out of the box, `Fn + Backspace` is not such a nice way to do it :D
