### ISSUE TITLE
Defold gui file editor crash

### ISSUE THREAD

**Issue by ghost** [defold/defold#8488]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2023-10-10T06:48:54.384007</td></tr>
<tr><td>Defold channel</td><td>dev</td></tr>
<tr><td>Defold editor sha</td><td>aa5089a770bba1605be131cf46d32784dc37a597</td></tr>
<tr><td>Defold engine sha</td><td>aa5089a770bba1605be131cf46d32784dc37a597</td></tr>
<tr><td>Defold version</td><td>1.5.0</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"2cc0e5cb4d324716ac6428ab2385f9ac"'>2cc0e5cb4d324716ac6428ab2385f9ac</a></td></tr>
<tr><td>GPU</td><td>Apple M1 Max</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 83.1</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>13.6.4</td></tr>
<table>

**Comment by jmakanin-ms** [comment]
If gui file opened after game is built, ALWAYS get this error, and cant navigate gui files

**Comment by AGulev** [comment]
If you are able to reproduce this issue, please provide more info or repro case.

**Comment by AGulev** [comment]
requested info wasn't provided
