### ISSUE TITLE
Texture bleeding at runtime created texture & atlas

### ISSUE THREAD

**Issue by Insality** [defold/defold#8489]
_Is it a private platform, and a platform specific issue? (i.e. would it break your NDA?)<br>
No platform specific

**Describe the bug (REQUIRED)**
When create a atlas at runtime, the images after I use `gui.play_flipbook()` sometimes has a texture bleeding at the edges. It relative to image padding when pack images at atlas, but even with 2+ pixel padding it happens.

**To Reproduce (REQUIRED)**
1. Load the example project
2. Press buttons: `Load` -> `Create Atlas` -> `Create Images`
3. Maximize the window (more artifacts will appear)
4. Press several times `Create Atlas` to recreate atlas

**Expected behavior (REQUIRED)**
No texture bleeding or information what am I doing wrong here

**Defold version (REQUIRED):**
Tested on Defold 162, 164

**Platforms (REQUIRED):**
Tested on MacOS

**Minimal repro case project (OPTIONAL):**
Repro: 
[test_atlas_create_texture_bleeding.zip](https://github.com/defold/defold/files/14138697/test_atlas_create_texture_bleeding.zip)

**Logs (OPTIONAL):**
Please provide relevant logs from engine, editor or build server. Learn where the logs are stored [here](https://defold.com/manuals/getting-help/#log-files).

**Workaround (OPTIONAL):**
Increasing the padding don't guarantee the absence of texture bleeding

**Screenshots (OPTIONAL):**
Screenshot:
![Screenshot 2024-02-02 at 12 25 45](https://github.com/defold/defold/assets/3294627/926d050b-f9ba-4e3b-b357-feea63b56264)

Video from example:
https://github.com/defold/defold/assets/3294627/420ed587-f069-4f2a-a3bf-f1a37e6806c7

Video from Panthera:

https://github.com/defold/defold/assets/3294627/fc40d20e-afdf-4bd0-b255-30002045bfe6

**Additional context (OPTIONAL):**

**Comment by Jhonnyg** [comment]
I don't see any padding in the atlas you create:
<img width="496" alt="image" src="https://github.com/defold/defold/assets/169640/d905221a-0607-4d31-b56c-42f880ff6b97">

This means there will be bleeding at the edges.
Another thing I noticed is that in the example you provided, you use a RGBA16F format but upload with RGBA. Not sure if this was intended or not, but we don't support format conversion like that :)

**Comment by Insality** [comment]
Yeah, the example `row_packing.lua` contains xPadding = 0 and yPadding = 0

Discussed and solved issue by explicit buffer on `resource.create_texture`

Instead of 
```
local texture_id = resource.create_texture(texture_name, atlas_creation_params)
```

To escape the bleeding the passing the explicit buffer is works:

```lua
local function get_empty_buffer(width, height, image_type, color)
	color = color or vmath.vector4(0, 0, 0, 0)
	local bytes_per_pixel = image_type == hash("rgba") and 4 or 3

	local data = buffer.create(width * height, { {name = image_type, type = buffer.VALUE_TYPE_UINT8, count = bytes_per_pixel } })
	local stream = buffer.get_stream(data, image_type)

	for y= 0, height - 1 do
		for x = 0, width - 1 do
			local index = y * width * bytes_per_pixel + x * bytes_per_pixel + 1
			stream[index + 0] = color.x * 255
			stream[index + 1] = color.y * 255
			stream[index + 2] = color.z * 255
			if bytes_per_pixel == 4 then
				stream[index + 3] = color.w * 255
			end
		end
	 end

	return data
end


local empty_buffer = get_empty_buffer(width, height, hash("rgba"))
local texture_id = resource.create_texture(texture_name, atlas_creation_params, empty_buffer)
```
