### ISSUE TITLE
it just stopped working

### ISSUE THREAD

**Issue by NKZalan** [defold/defold#8499]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2023-11-03T14:05:43.267696</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>36a0c9ec890ce4d1a12239163a1b44a9bb80de3c</td></tr>
<tr><td>Defold engine sha</td><td>a90c50928623cf23b3687a7eec05972d11427202</td></tr>
<tr><td>Defold version</td><td>1.6.1</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"cf6d7bb3289a481eb11f0c91fe00a4a6"'>cf6d7bb3289a481eb11f0c91fe00a4a6</a></td></tr>
<tr><td>GPU</td><td>Apple M2</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 88</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>aarch64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>14.1</td></tr>
<table>

**Comment by vlaaad** [comment]
class java.io.FileNotFoundException

/var/folders/ds/t52clxb93s97mt7hysyk804w0000gn/T/defold-unpack-36a0c9ec890ce4d1a12239163a1b44a9bb80de3c9157647629115598727/builtins/builtins.zip (No such file or directory)

**Comment by vlaaad** [comment]
IIRC we fixed the issue you are likely getting, so updating the editor to a newer version should help
