### ISSUE TITLE
Mesh problem with new tag after changing materials

### ISSUE THREAD

**Issue by d954mas** [defold/defold#8515]
**Describe the bug (REQUIRED)**
For my game i need to draw 3d model in render target to use it in gui.

I have 2 materials.
-player.material(in game)
-player_3drt.material(for rt)

Material same but i tags differents.
![2024-02-07_16-30-38](https://github.com/defold/defold/assets/2655263/ed0a8474-2dc1-4361-9eb9-19f2bf5d11c8)
![2024-02-07_16-31-02](https://github.com/defold/defold/assets/2655263/2cb50b24-c8c1-4723-91af-a7890aac3e2a)

1)I register material

2)change material for mesh
```
go.set(mesh_comp_url, "material", MATERIALS.materials["3drt_mesh"])
```

But it not worked(

If i add add tag to player.material it worked.
![2024-02-07_16-31-15](https://github.com/defold/defold/assets/2655263/e866066d-951f-4794-a70f-36cb830f67a3)

So if all materials have player_rt tag.
-i see player(game) and player(rt) in rt target
-if player material not have player_rt. I do not see player and player(rt) in rt target.
-if i do not change material. I see player and player(rt) in game

removing for tag worked when i change material? but new tag player_rt not added?

https://github.com/defold/defold/assets/2655263/02b19e1e-6e02-4a33-923a-7cfc523b1583

https://github.com/defold/defold/blob/00ff9d39c3f3829423e48becc2a3be1574d44eed/engine/gamesys/src/gamesys/components/comp_mesh.cpp#L898

```
write_ptr->m_TagListKey = dmRender::GetMaterialTagListKey(component.m_Resource->m_Material->m_Material);

//Mb you need to use getMaterial Here?
write_ptr->m_TagListKey = dmRender::GetMaterialTagListKey(GetMaterial(component, component->m_Resource);
```

**To Reproduce (REQUIRED)**

**Expected behavior (REQUIRED)**
After changing material for mesh tags is correct

**Defold version (REQUIRED):**
  - 1.6.4 beta

**Platforms (REQUIRED):**
 - Platforms: [e.g. iOS, Android, Windows, macOS, Linux, HTML5]
 - OS: [e.g. iOS8.1, Windows 10, High Sierra]

**Minimal repro case project (OPTIONAL):**

**Logs (OPTIONAL):**
Please provide relevant logs from engine, editor or build server. Learn where the logs are stored [here](https://defold.com/manuals/getting-help/#log-files).

**Workaround (OPTIONAL):**
In my case i can create a factories with new material for every skin

**Screenshots (OPTIONAL):**

**Additional context (OPTIONAL):**

**Comment by d954mas** [comment]
Same logic worked for model(boxed gloves)

**Comment by Jhonnyg** [comment]
Do you have a repro or a project or something where I can look at this? I don't fully understand what the issue is here 🤔

**Comment by d954mas** [comment]
I have project. I think mesh tags not changed if i change material for mesh?

https://github.com/d954mas/game-blocky-fighting/blob/master/world/game/ecs/systems/draw_player_3drt_system.lua

Here is system where i draw player(mesh) and boxer gloves(model) in rt.

The main idea that i use same model and mesh as in game but change material.
New material have another tag.

This worked for model but not worked for mesh.

But if i use another factory with same mesh but new material it worked.


```lua
if (e.player_3d_rt_go.model.root == nil) then
			local skin_def = assert(DEFS.SKINS.SKINS_BY_ID[e.player_3d_rt_go.config.skin])
			local urls = collectionfactory.create(skin_def.factory, nil, nil, nil,
					skin_def.scale)
			--this factory_gui have same factory but another material
			urls = collectionfactory.create(skin_def.factory_gui, nil, nil, nil,
					skin_def.scale)
			local go_url = msg.url(urls[PARTS.ROOT])
			local mesh_url = msg.url(urls[PARTS.MESH])
			local mesh_origin = msg.url(urls[PARTS.ORIGIN])
			local mesh_comp_url = COMMON.LUME.url_component_from_url(mesh_origin, COMMON.HASHES.MESH)
			go.set_parent(go_url, e.player_3d_rt_go.root, false)
			e.player_3d_rt_go.model.root = go_url
			e.player_3d_rt_go.model.mesh_root = mesh_url
			e.player_3d_rt_go.model.mesh_origin = mesh_origin
			e.player_3d_rt_go.model.mesh = GAME_MESH_READER.get_mesh(skin_def.mesh)
			go.set(mesh_comp_url, "material", MATERIALS.materials["3drt_mesh"])
			e.player_3d_rt_go.model.mesh:set_mesh_component(mesh_comp_url)

			e.player_3d_rt_go.model.mesh_animator = MeshAnimator(e.player_3d_rt_go.model.mesh)
			e.player_3d_rt_go.model.mesh.tracks[2].bone_weights = DEFS.ANIMATIONS.BONES_WEIGHS.ARM_ATTACK
			e.player_3d_rt_go.model.mesh.tracks[2].enabled = true

			e.player_3d_rt_go.model.mesh_animator:play(skin_def.animations.LOOK_AROUND[1].id, BASE_NO_BLEND_ONCE)

		end
```

If you comment this line. It will not worked
```
--this factory_gui have same factory but another material
urls = collectionfactory.create(skin_def.factory_gui, nil, nil, nil,
skin_def.scale)
```
![2024-02-08_13-24-11](https://github.com/defold/defold/assets/2655263/36a25709-28bb-4044-84bc-8614bc507b14)

![2024-02-08_13-23-40](https://github.com/defold/defold/assets/2655263/b62484e5-d225-431c-9b45-8e82d72f7e68)

**Comment by d954mas** [comment]
I look at code. This is how you find taglist for model and for mesh

https://github.com/defold/defold/blob/00ff9d39c3f3829423e48becc2a3be1574d44eed/engine/gamesys/src/gamesys/components/comp_mesh.cpp#L898

https://github.com/defold/defold/blob/e429a6618059f06112a9166240acea00ebedec57/engine/gamesys/src/gamesys/components/comp_model.cpp#L1271

```
write_ptr->m_TagListKey = dmRender::GetMaterialTagListKey(component.m_Resource->m_Material->m_Material);

//Mb you need to use getMaterial Here?
write_ptr->m_TagListKey = dmRender::GetMaterialTagListKey(GetMaterial(component, component->m_Resource);
```

**Comment by d954mas** [comment]
i can create small repro case if it will help understand)
Need repro case?

**Comment by d954mas** [comment]
@britzl @Jhonnyg 

REPRO CASE.
[change_material_problem.zip](https://github.com/defold/defold/files/14332003/change_material_problem.zip)


Problem:
mesh number 3 is not draw.

Case.
I use same materials for mesh and models.
After i change material for mesh it not draw.
First line is models.
Second line meshes

![2024-02-19_16-58-33](https://github.com/defold/defold/assets/2655263/f958c390-6d9d-4f65-83fc-9eaa6f040c4e)
![2024-02-19_16-58-43](https://github.com/defold/defold/assets/2655263/49649a70-40eb-4a35-9a7e-02da14fffd2a)


More details.
COLUMN 1.
material1(tag model1)
COLUMN 2.
material2(tag model2)
COLUMN 3.
material1(tag model1)
change in runtime to material2(tag model2)
Model draw. Mesh disappeared.
COLUMN 4.
material1_2(tag model1, model2)
change in runtime to material2(tag model2)
Model draw. Mesh draw.

```
go.property("material2", resource.material("/assets/models/model2.material"))

function init(self)
	msg.post(".", "acquire_input_focus")
	msg.post("@render:", "use_camera_projection")
	msg.post("camera", "acquire_camera_focus")

	print(self.material2)
	go.set("#model3", "material", self.material2)
	go.set("#mesh3", "material", self.material2)
	go.set("#model4", "material", self.material2)
	go.set("#mesh4", "material", self.material2)
end
```
