### ISSUE TITLE
sprite.set_hflip() seems to not flip correctly

### ISSUE THREAD

**Issue by JCash** [defold/defold#8516]
https://forum.defold.com/t/defold-1-6-4-beta/75834/35?u=mathias_westerdahl

_Is it a private platform, and a platform specific issue? (i.e. would it break your NDA?)<br>
Then please report your issue in the corresponding extension repository!_

**Describe the bug (REQUIRED)**

**To Reproduce (REQUIRED)**

**Expected behavior (REQUIRED)**

**Defold version (REQUIRED):**
  - Version [e.g. 1.2.155]

**Platforms (REQUIRED):**
 - Platforms: [e.g. iOS, Android, Windows, macOS, Linux, HTML5]
 - OS: [e.g. iOS8.1, Windows 10, High Sierra]

**Minimal repro case project (OPTIONAL):**
Please attach a minimal project where the bug is reproduced. This will greatly help the person trying to investigate and fix the bug.

**Logs (OPTIONAL):**
Please provide relevant logs from engine, editor or build server. Learn where the logs are stored [here](https://defold.com/manuals/getting-help/#log-files).

**Workaround (OPTIONAL):**
If there is a workaround, please describe it here.

**Screenshots (OPTIONAL):**

**Additional context (OPTIONAL):**

**Comment by AGulev** [comment]
fixed by https://github.com/defold/defold/pull/8518 ?
