### ISSUE TITLE
Shader discard unused textures. sampler2D  is not correct (mobile web)

### ISSUE THREAD

**Issue by d954mas** [defold/defold#8535]
**Describe the bug (REQUIRED)**
I need to use render target in gui(draw 3d model to box node)
This worked in windows and web but i have problems in mobile web.

Shader discard unused textures and texture index for others textures is changed.

```
if self.gui_3d_rt then
		render.enable_state(render.STATE_STENCIL_TEST)
		render.enable_texture(1, self.gui_3d_rt)
	end
	render.draw(self.predicates.gui)
	if self.gui_3d_rt then
		render.disable_texture(1)
		render.disable_state(render.STATE_STENCIL_TEST)
	end
```

gui_3d_rt.fp
```
varying mediump vec2 var_texcoord0;
varying lowp vec4 var_color;

uniform lowp sampler2D texture_sampler;
uniform lowp sampler2D rt_target;

void main()
{
    lowp vec4 tex0 = texture2D(texture_sampler, var_texcoord0.xy);
    lowp vec4 tex1 = texture2D(rt_target, var_texcoord0.xy);
    //not worked texture_sampler unused and will be discard
    //rt_target now is texture 0. Shoud be texture 1
    //gl_FragColor = tex1;

    //use texture_sampler so texture index not changed.
    gl_FragColor = tex0 * 0.00 + tex1;
}

```

**To Reproduce (REQUIRED)**

**Expected behavior (REQUIRED)**
If i don't use texture in shader. Texture sampler use correct texture.

**Defold version (REQUIRED):**
  - Version 1.6.4

**Platforms (REQUIRED):**
 - Platforms: HTML5(only mobile)

**Minimal repro case project (OPTIONAL):**
Please attach a minimal project where the bug is reproduced. This will greatly help the person trying to investigate and fix the bug.

**Logs (OPTIONAL):**
Please provide relevant logs from engine, editor or build server. Learn where the logs are stored [here](https://defold.com/manuals/getting-help/#log-files).

**Workaround (OPTIONAL):**
If there is a workaround, please describe it here.

**Screenshots (OPTIONAL):**
![photo_2024-02-13_20-22-52 (2)](https://github.com/defold/defold/assets/2655263/314ff984-e6fa-4d51-9e59-bb9b45e69f53)
![photo_2024-02-13_20-22-52](https://github.com/defold/defold/assets/2655263/8e8d95ac-c69a-4839-8aa3-5bd1501ddaf2)

**Additional context (OPTIONAL):**

**Comment by Jhonnyg** [comment]
Yes, this is an unfortunate side-effect of OpenGL drivers optimizing the shaders. There is no way for us to rely on the fact that an index will match if a sampler if it is removed. We discussed this recently, and I think we will add support for enabling textures by sampler name as well as this indexing parameter.
