### ISSUE TITLE
Assigning atlas created by resource.create_atlas to sprite component causes a crash.

### ISSUE THREAD

**Issue by Pharnem** [defold/defold#8573]
**Describe the bug**
In Defold Version 1.6.4, assigning dynamically created atlas (using function `resource.create_atlas`) to a sprite component causes the engine to crash. The crash does not occur if either:
1. Sprite component is disabled.
2. Image of sprite is immediately reassigned.
Leading me to believe the error is thrown when trying to draw the sprite with assigned atlas.

**To Reproduce**
1. Open the attached project in Defold.
2. Run it.
3. The game should run as normal, with nothing visible.
4. Press LMB to enable the sprite component.
5. The game crashes due to assertion failure.

Without the attached project:
1. Create new empty project.
2. Create a new game object in collection main.collection.
3. Add a sprite component with id `sprite` to the created game object.
4. Create a valid atlas and assign it to the field `image` of sprite.
5. Create new script `created_atlas.script`.
6. Replace contents of above script with example for resource.create_atlas on Defold's [API Reference website](https://defold.com/ref/beta/resource/#resource.create_atlas:path-table).
7. Add a `created_atlas.script` component to the game object.
8. Run the project.
9. The game crashes due to assertion failure.

**Expected behavior (REQUIRED)**
After step 4., the sprite should be enabled and the texture (possibly fully transparent) should be drawn to the screen.

**Defold version:**
  - Version 1.6.4
 
**Platforms (REQUIRED):**
 - Platforms: Windows, Linux
 - OS: Windows 11, Kubuntu 23.10
 - Device: Lenovo Thinkpad T430

**Minimal repro case project:**
[Project.zip](https://github.com/defold/defold/files/14363075/Project.zip)

**Logs:**
[ConsoleLog.txt](https://github.com/defold/defold/files/14363045/ConsoleLog.txt)
[_crash.txt](https://github.com/defold/defold/files/14363057/_crash.txt)

**Workaround:**
Creating all atlases beforehand removes this problem and is probably a better solution overall when applicable, however there are scenarios where runtime manipulation of atlases is necessary.

**Additional context:**
I've tried the same tests with Defold Version 1.6.2 (this version tested only on Linux), and the error did not occur, meaning the change most likely occurred either in 1.6.3 or 1.6.4.

**Comment by margaris23** [comment]
Good morning. Same thing happens on 1.7 (Linux Mint - 5.15.0-100-generic #110-Ubuntu SMP Wed Feb 7 13:27:48 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux) even using the suggested examples from here https://defold.com/manuals/atlas/#creating-an-atlas-at-runtime
