### ISSUE TITLE
Sprite Atlas "Margin" setting is only applied between sprites, not at atlas edges.

### ISSUE THREAD

**Issue by j-h-a** [defold/defold#8584]
**Describe the bug (REQUIRED)**

When setting a `margin` value in a sprite atlas, the margin is not applied at the edges of the atlas.

**To Reproduce (REQUIRED)**

1. Create a sprite atlas with some rectangular images of anything where a straight edge is right up against the edge of the sprite-image (boxes/crates for example).
2. In the atlas settings, set `Margin: 1`, `Inner Padding: 0`, `Extrude Borders: 0`

**Expected behavior (REQUIRED)**

Each sprite in the atlas should be separated from each other by 1px, and also from the edge of the atlas by 1px.

**Actual behavior**

Each sprite in the atlas is correctly separated from each other by 1px, but they are arranged such that some are right up against the edge of the atlas without a 1px margin. In these cases the hard edges of the sprite quad are visible as aliased edges when the sprite is rotated.

**Defold version (REQUIRED):**
  - 1.6.4

**Platforms (REQUIRED):**
 - Platforms: All (editor issue)

**Comment by matgis** [comment]
The Margin property only affects the separation between the images, not the borders. It sounds like what you want is covered by the Inner Padding property? This property is typically used to solve issues like the one you're describing.

https://defold.com/manuals/atlas/#atlas-properties

**Comment by AGulev** [comment]
@j-h-a did you try `Inner Padding` Mats suggested?

**Comment by j-h-a** [comment]
Using inner padding is a work-around to this problem, but not really a solution as it causes some additional complexity and coupling between the editor and your game code.

For example if you have a 32x32 sprite, the size will be 34x34 in the editor, and the quad will include the transparent border pixels. If you are getting or setting the size from code you now need to take this padding into account, introducing both complexity and coupling (i.e. the code needs to know that you're using padding and its size).

If you want the sprite size to be the same as the actual size of your image, and the quad would align with your pixels, you can still get bleeding from the sampler which for foreground sprites that are rotated can be desirable if the sampler brings in some transparency. In this case you want a 1px border **outside** of the sprite quad, and the "size" property will be correct when you access it from code.

The second description is the use-case for margin. You want to ensure there is a 1px border of transparent pixels all the way around your image. However, when the image is pushed right up against the edge of the atlas, the sampler will try to bring in colours from outside the texture and they will most sensibly CLAMP, so you lose the smoothing effect.

**Comment by AGulev** [comment]
I think you right here, I'll take a look into this issue

**Comment by AGulev** [comment]
> If you want the sprite size to be the same as the actual size of your image, and the quad would align with your pixels, you can still get bleeding from the sampler which for foreground sprites that are rotated can be desirable if the sampler brings in some transparency. In this case you want a 1px border **outside** of the sprite quad, and the "size" property will be correct when you access it from code.

Bleeding issue usually solved by `Extrude Borders`:
>Extrude Borders
The number of edge pixels that should be repeatedly padded around each image. When the fragment shader samples pixels at the edge of an image, pixels of a neighbor image (on the same atlas texture) may bleed over. Extruding the border solves this problem.
https://defold.com/manuals/atlas/#atlas-properties

But margin still looks inconsistent, since it adds space between images and for left and bottom edge, but not top and left edge

**Comment by AGulev** [comment]
Margin issue will be fixed in 1.7.1
