### ISSUE TITLE
Mesh component must specify texture warning & error

### ISSUE THREAD

**Issue by FlexYourBrain** [defold/defold#8610]
For the mesh component a texture must be assigned to the texture slot and the texture must also be in power of 2 format for html5 build/bundle. PC builds do not throw these errors or give a warning until bundling.  

**To Reproduce**
Create mesh component with valid properties, then for the texture slot keep it unassigned and build/bundle for html5 or bundle for PC.

**Expected behavior**
1. For the mesh component's texture slot, if it must be assigned and be power of 2 in format give warning and/or error for all build/bundle platforms. 
 
2. Update the manual information for the mesh component's texture slot requirements.

**Defold version**
  - Version 1.6.4 and above

**Platforms**
 - Platforms:[ iOS, Android, Windows, macOS, Linux, HTML5 ]

**Logs**
```lua
 /assets/mesh_system/mesh/lazer.mesh
	you must specify a texture 
```
```lua
Build Remote Engine...

ERROR: assets/mesh_system/mesh/lazer.mesh:0: 'com.dynamo.bob.CompileExceptionError: you must specify a texture'
```
**Workaround:**
Assign power of 2 size texture to mesh component texture slot then build/bundle

**Comment by JCash** [comment]
Regarding any solution, I think it should be allowed to have no texture. E.g. what if you wish to use only vertex attributes and shaders to generate the look.

**Comment by FlexYourBrain** [comment]
> Regarding any solution, I think it should be allowed to have no texture. E.g. what if you wish to use only vertex attributes and shaders to generate the look.

I agree, allowing no texture to be assigned would be the correct thing to do here.

**Comment by FlexYourBrain** [comment]
That is a good point, and clarifies the issue. In my case I created a render target and assigned a sampler for it and then used the work around and assigned a dummy texture after receiving the errors. It was my naivety thinking that creating the render target and assigning sampler name would occupy the slot at runtime and overlooked the editor side. My question now is what happens with the dummy assigned texture when the render target is built. When multiple render targets are created should the developer use a single dummy texture or multiple, one for each render target?

**Comment by Jhonnyg** [comment]
So if I understand correctly, you created it as a _resource_ and assigned it via the editor to a sampler slot?
That shouldn't produce a build error 🤔

**Comment by FlexYourBrain** [comment]
No, pre - 1.7.0  I created a render target via render script and assigned a sampler slot to the material and empty texture slot in the mesh component.

The new 1.7.0 rt resource does not have this issue. I just now tested the new rt resource and assigned it to a mesh component texture slot. It is working as intended. However using [render.render_target()](https://defold.com/ref/render/#render.render_target:name-parameters) to create the rt and then assigning a sampler slot to material etc. still would have this issue and just need to assign a dummy texture as previously mentioned.

**Comment by AGulev** [comment]
I think it's not an issue.
I mean, this is designed this way:
- if you want to use RT, just assign it as resource;
- or use texture (dummy texture in case you are going to replace it with RT in runtime).

Am I right here, @Jhonnyg ?
If so, should we close this issue then?
