### ISSUE TITLE
Dynamic resizing of collision shapes changes position

### ISSUE THREAD

**Issue by jcbk101** [defold/defold#8622]
Dynamic resizing of collision shapes using `physics.set_shape()` resets the position of the collider's shape to 0, 0, 0.

Also, set_shape returns an error when using:
```lua
local data = physics.get_shape("#collider", "box")
-- data = { dimension = vmath.vector3(), type = 1 }
```
Although type is declared, `physics.set_shape()` still says argument 6 is nil.

**Comment by AGulev** [comment]
Not enough info.
What version of defold it is?
Do you use 2d or 3d physics?

**Comment by AGulev** [comment]
Some of these issues were fixed in 1.7.0 already. So I need more info to know if it's something new, or something which was fixed
It would be nice if you test it in 1.7.0 https://github.com/defold/defold/releases/tag/1.7.0-beta

**Comment by crustygiant** [comment]
This appears to be a legitimate issue. 

I’m using version 1.8.0. 

Create a new project from the platformer game template. Give the character collision object shape a name. Add the following code to the top of the init function in the character script:

local data = {}
data.diameter = 10
physics.set_shape("#collisionobject", "<your shape name here>", data)

I get the error:

“bad argument #6 to set_shape …”

Let me know if you need more information.

**Comment by britzl** [comment]
> ```lua
> ```lua
> local data = {}
> data.diameter = 10
> physics.set_shape("#collisionobject", "your shape name here", data)
> ```
>       
> I get the error:
> “bad argument #6 to set_shape …”
> ```

The API reference for 1.8.0 is unfortunately not accurate. The docs have been fixed for the next release:

https://defold.com/ref/alpha/physics/#physics.set_shape:url-shape-table

You need to also specify the shape type in the data table.

**Comment by crustygiant** [comment]
Setting the shape type works.
