### ISSUE TITLE
Defold editor markdown file: can't see selected text

### ISSUE THREAD

**Issue by cypaol** [defold/defold#8629]
Since Defold 1.6.3 if I open an .MD file in the editor and try to select a word, a line or a paragraph dragging the mouse I can't see the selection that I made, the text  became highlighted only if I then scroll the page. 

1. Open a tutorial (e.g. RPG map sample)
2. Open README.md
3. Try to select some text with the mouse
4. You can't see the highlighted selection
5. If you then scroll the page up or down with keyboard arrows or with mouse wheel the highlighted selection is visible

Selection of text in markdown file was fine in 1.6.2 release

Defold version 
  - Version 1.6.3 - 1.6.4

 - OS: Linux Mint 21.3 Cinnamon, kernel 5.15.0-97-generic
 - Nvidia Driver 535.161.07

**Comment by cypaol** [comment]
The bug persist in the 1.7.0 release

**Comment by public-prosecutor** [comment]
I've got exactly the same issue running Defold 1.7.0 on windows 11: Selected text is not highlighted until I scroll up or down the markdown file

**Comment by cypaol** [comment]
1.8 beta the problem persist

**Comment by britzl** [comment]
To be clear, it only happens in the markdown reader and not in the text editor right?

**Comment by britzl** [comment]
We should try to update commonmark from 0.21.0 to 0.22.0 to see if that helps:

https://github.com/defold/defold/blob/dev/editor/project.clj#L66-L67

https://github.com/commonmark/commonmark-java/blob/main/CHANGELOG.md

**Comment by cypaol** [comment]
> To be clear, it only happens in the markdown reader and not in the text editor right?

Yes, only in the markdown reader. I tried the Windows version (1.7 and 1.8 beta) and the problem is the same as on linux.

**Comment by vlaaad** [comment]
This is a problem with JavaFX web view that we use for displaying markdown, not with markdown per se.

**Comment by vlaaad** [comment]
We should try updating the JavaFX to see if that helps :P

**Comment by AGulev** [comment]
> We should try updating the JavaFX to see if that helps :P

? https://github.com/openjdk/jfx/commit/64af987576214fc5483520ce8131895be74a641d

**Comment by AGulev** [comment]
but https://github.com/openjdk/jfx/commit/afa206b546a580a784d830712be174bb84f09ee9

**Comment by vlaaad** [comment]
@AGulev I'm looking at your first link, and it seems the fix was backported to older release branches, so maybe there is a JDK-17 compatible JavaFX release with the fix
