### ISSUE TITLE
Double click doesn't work for "The file `image.png` could not be found"

### ISSUE THREAD

**Issue by AGulev** [defold/defold#8633]
**Describe the bug (REQUIRED)**
If I get an issue, the file could not be found like this
![CleanShot 2024-03-07 at 10 33 54@2x](https://github.com/defold/defold/assets/2209596/87459fa3-3f68-4358-b6c1-536541a5b9d3)
then double-click on the message doesn't open related atlas anymore.

**To Reproduce (REQUIRED)**
1. Create an atlas with an image
2. Use this atlas in the main scene
3. Remove the image from disk
4. Try to build the project
5. See the error and double click it - nothing happens

**Expected behavior (REQUIRED)**
Atlas with missed image opened

**Defold version (REQUIRED):**
  - Version 1.7.0 Beta

**Comment by matgis** [comment]
This issue was also found to be present in 1.6.4. It may have existed for some time.

**Comment by AGulev** [comment]
> This issue was also found to be present in 1.6.4. It may have existed for some time.

Is it possible that it was introduced in one of the patch updates? I'm sure I tested it yesterday when I had two versions of the editor opened, and one worked fine, another one - didn't work (I was about to show you)
Now when I test it in 1.6.4 it doesn't work, but I updated 1.6.4 to the latest version

**Comment by AGulev** [comment]
> > This issue was also found to be present in 1.6.4. It may have existed for some time.
> 
> Is it possible that it was introduced in one of the patch updates? I'm sure I tested it yesterday when I had two versions of the editor opened, and one worked fine, another one - didn't work (I was about to show you) Now when I test it in 1.6.4 it doesn't work, but I updated 1.6.4 to the latest version

Now I understand why I thought it's 1.7.0 only bug:
- If I open working project and break it - the double click doesn't work
- If I open already broken project - the double click works

**Comment by matgis** [comment]
Yeah, I discovered this while looking into it. If the image is not there when you open the project, it gets correctly flagged as missing, but not when an image is removed while the project is open. I suspect the issue has been there for some time. Nice find!
