### ISSUE TITLE
Editor Script dialog(s)

### ISSUE THREAD

**Issue by Jerakin** [defold/defold#8658]
**Is your feature request related to a problem? Please describe (REQUIRED):**
Ask users for input when running an Editor Script

**Describe the solution you'd like (REQUIRED):**
Usage of the "Generic dialogs", that the editor can use.

* New File (e.g. any new file type)
* Select/Multi Select (e.g. Open Asset, Add Image, Select Resource)
* "OK/Cancel" (e.g. Delete)
* String Input (e.g. rename with and without the Preview).

**Comment by AGulev** [comment]
related https://github.com/defold/defold/issues/8062

**Comment by AGulev** [comment]
I think related as well https://github.com/defold/defold/issues/4503

**Comment by Jerakin** [comment]
## New [RESOURCE] (e.g. any new file type)
![image](https://github.com/defold/defold/assets/5273682/5401274e-6e3d-499c-bd7e-59c6cc534910)

Some editor scripts creates new files, editor-script-atlas, creates atlas files from selected images. However currently the name of the atlas file will be a generated name like `ATLAS20240311XXXXXX` I would like it if I could bring up a new resource window, let the user pick the name and use that.


## String input (e.g. rename with and without the Preview).
![image](https://github.com/defold/defold/assets/5273682/a2ec160c-2c8c-489c-83b3-ac96ef1adb9a)

The editor-script-atlas can add your images into an existing atlas as an animation. Right now the animation name is generated the same way as the atlas in the example above. I would like a dialog (like the Rename one) that only contains a String input as well as OK/Cancel, so that the user can pick their animation name directly without having to open the atlas and rename it.

## Select/Multi Select (e.g. Open Asset, Add Image, Select Resource)
I was contemplating creating an add-on that could import parts of file into the existing one. Think [editor-script-template](https://github.com/Jerakin/editor-script-templates) but instead of the templates being files you can copy paste. I was thinking of importing parts of a file into an existing file. That addon would need a way to select the resource to be imported into the opened scene.

**Comment by AGulev** [comment]
@vlaaad I think this feature request is implemented in your PR, right? https://github.com/defold/defold/pull/9421

**Comment by vlaaad** [comment]
Hmm, looks like it is, yes!
