### ISSUE TITLE
Not rendering models with built-in material in bundle (bob migration issue)

### ISSUE THREAD

**Issue by paweljarosz** [defold/defold#8681]
Everything I know regarding this is described in this forum thread:

https://forum.defold.com/t/3d-models-not-rendering-in-bundle-solved/76316

**Describe the bug (REQUIRED)**
3D models in my project using all same built-in materials were not rendered in Windows/HTML5 bundle.

**To Reproduce (REQUIRED)**
A lot of 3D models with same materials assigned?

**Expected behavior (REQUIRED)**
Models are displayed corectly in bundle.

**Defold version (REQUIRED):**
1.7.0
Editor SHA1: bf4dc66ab5fbbafd4294d32c2797c08b630c0be5
Engine SHA1: bf4dc66ab5fbbafd4294d32c2797c08b630c0be5

**Platforms (REQUIRED):**
 - Windows, HTML5

**Workaround (OPTIONAL):**
Copy the built-in material into project and assign it separately to each model.

**Screenshots (OPTIONAL):**
In the forum post.

**Comment by AGulev** [comment]
1. We forgot to migrate builtins model material to a new format
![CleanShot 2024-03-18 at 10 04 32@2x](https://github.com/defold/defold/assets/2209596/f85fb93e-df72-482b-8a3e-b9968f0ed1a2)

2. Editor doesn't do any migration. If I copy/paste material from builtins it will stay in old format until I do changes there (for example change a shader, or some other change), is it right behaviour @matgis ?

**Comment by matgis** [comment]
The editor not resaving the file in the updated file format is the correct behaviour if Bob can read and build the old file format. If it cannot, the editor should force a resave in the new file format.

Traditionally, we've made sure Bob can read the old file formats. We've only force-resaved in the new file format before in cases where the migration was particularly difficult to handle for Bob, such as moving a property from one file to another.

I think we should still update the file format in builtins, but also attempt to make Bob read the old file format. If it provides to difficult to make the change in Bob, let me know and I can make the editor force-save in the new format.

**Comment by AGulev** [comment]
I updated builtins materials 
https://github.com/defold/defold/tree/update-builtins-materials but didn't know how should we move on on this
