### ISSUE TITLE
Version 1.7.0 | error 'system_font.font not found'

### ISSUE THREAD

**Issue by betweendrafts** [defold/defold#8683]
**Describe the bug (REQUIRED)**
My builds no longer run, the following error message is displayed:

Render error: system_font.font: The file '/builtins/fonts/system_font.font/ could not be found

**To Reproduce (REQUIRED)**

**Expected behavior (REQUIRED)**
My builds should run fine like the previous version I used, i.e., Defold 1.6.4

**Defold version (REQUIRED):**
  - Version 1.7.0

**Platforms (REQUIRED):**
 - Platforms: macOS
 - OS: Sonoma 14.3.1
 - Mac mini 2023 w/ Apple M2 Silicon

**Comment by AGulev** [comment]
Please, check 1.7.0 release notes: https://forum.defold.com/t/defold-1-7-0-has-been-released/76266/21
Update font in your project :

>BREAKING CHANGE: ([#8559 3](https://github.com/defold/defold/pull/8559)) Removed system_font.font from builtins
>This breaking change was implemented to clarify the usage of predefined fonts in builtins. The old system_font.font has been completely removed from the builtins, and two new fonts have been introduced:
>
>builtins/fonts/default.font, which uses the default df material and can serve as a font for the development process.
builtins/fonts/debug/always_on_top.font, which utilizes a special material builtins/fonts/debug/always_on_top_font.material with the debug_text tag. This font is intended to be drawn on top of other elements and is used for debugging purposes (such as the profiler and the draw_debug_text message) as replacement of old system_font.font. Additionally, changes are required in default.render_script, where the old text predicate has been replaced with the debug_text predicate for clarity.

**Comment by 8bitskull** [comment]
This is the result of a breaking change in 1.7.0.

See here for explanation and resolution:
https://github.com/defold/defold/pull/8559
