### ISSUE TITLE
when i press command + b game window does not come up

### ISSUE THREAD

**Issue by NKZalan** [defold/defold#8690]
### Expected behaviour
game window should be coming up 
### Actual behaviour
when i press command + b game window does not come up
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2024-03-12T10:37:46.553378</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>9ad2d7834a6adfaedcd902a8e6f9997ed5cbb507</td></tr>
<tr><td>Defold engine sha</td><td>bf4dc66ab5fbbafd4294d32c2797c08b630c0be5</td></tr>
<tr><td>Defold version</td><td>1.7.0</td></tr>
<tr><td>GPU</td><td>Apple M2</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 88</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>aarch64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>14.1</td></tr>
<table>

**Comment by britzl** [comment]
Is the window not showing up at all or showing up behind the editor?

**Comment by NKZalan** [comment]
i press command b and now a window with an error message saying "defold quit unexpectedly" when defold is still actually open.

**Comment by AGulev** [comment]
not enough info
