### ISSUE TITLE
Timer LuaRef leak

### ISSUE THREAD

**Issue by dri-richard** [defold/defold#8700]
**Describe the bug**
The LuaRef count seen in the profiler does not go down when a game object that started a timer is deleted

**To Reproduce**
Steps to reproduce the behaviour:
1. Open the [Defold examples project](https://github.com/defold/examples/commits/master/)
2. Run the project
3. Start web profiler
4. Observe the LuaRefs count in the profiler Global Properties view
5. Repeatedly select and exit the repeating timer example
6. See how the LuaRef count goes up by 1 each time
7. Stop execution
8. Comment out the code in repeating_timer.gui_script that creates the timer
9. Run again and compare

**Expected behaviour**
The LuaRef count should go up when running the timer example, but return to its previous value when returning to the menu, as the proxy is unloaded and the timer is automatically cancelled/deleted

**Defold version**
Seen in 1.6.4 and 1.7.0, both on M1 Macbook Pro

**Additional context**
See #4590 which might be related.

**Comment by AGulev** [comment]
https://github.com/defold/defold/issues/8123 might be related as well

**Comment by AGulev** [comment]
Repro: 

[timers.zip](https://github.com/user-attachments/files/15875454/timers.zip)
