### ISSUE TITLE
Inconsistency in sprite attribute go.set() and go.animate() api (1.7.0)

### ISSUE THREAD

**Issue by Laminariy** [defold/defold#8717]
**Describe the bug (REQUIRED)**
I have a material with two attributes. First is one-float saturation attribute and second is vec4 tint attribute.
![изображение](https://github.com/defold/defold/assets/48628793/f5aee66a-bba9-405a-8f97-0fc943d4d711)
There is inconsistency in how I can control these attributes.

### One-float saturation go.set() issues:
If I call `go.set(url, "saturation", value)` it always sets the value to zero. I expect this value to be set correctly.
If I call `go.set(url, "saturation", vec4)` it works correctly.

### One-float saturation go.animate() issues:
If I call `go.animate(url, "saturation", value)` the sprite starts fllickering instead of proper animation.
If I call `go.animate(url, "saturation", vec4)` it causes a "The property 'saturation' has incorrect type" error.
So there is no way to animate one-float attribute at all.

### vec4 tint go.set() issues:
If I call `go.set(url, "tint.w", value)`  it always sets the value to zero. I expect this value to be set correctly.
If I call `go.set(url, "tint", vec4)` it works correctly.

### vec4 tint go.animate() issues:
If I call `go.animate(url, "tint.w", value)` it sets the value to zero, but sometimes it animates the wrong property (like tint.x for example).
If I call `go.animate(url, "tint", vec4)` it works correctly.

**To Reproduce (REQUIRED)**
1. Open example project
2. See error

**Expected behavior (REQUIRED)**
All different api calls works correctly and consistently.

**Defold version (REQUIRED):**
  - Version 1.7.0

**Platforms (REQUIRED):**
 - Windows 11
 - Any other, I guess

**Minimal repro case project (OPTIONAL):**
[vattributes_issue.zip](https://github.com/defold/defold/files/14757743/vattributes_issue.zip)

**Screenshots (OPTIONAL):**
Flickering when trying to animate saturation value.
![flickering](https://github.com/defold/defold/assets/48628793/a9ccd47d-5b97-4a9e-9fb0-8c97c2dab718)

**Comment by Jhonnyg** [comment]
excellent repro case, I'll take a look 👍

**Comment by Dragosha** [comment]
small repro from video:
[example.zip](https://github.com/defold/defold/files/14758294/example.zip)

upd:
error happens if the sprite vertex attribute has been overwritten in the editor.

**Comment by Jhonnyg** [comment]
Ok, I think I cover all these cases now:

https://github.com/defold/defold/assets/169640/ba78dbf6-3e3f-44f5-bc46-2f55868bd720

Issue will be closed by a PR so leaving open for now.

**Comment by Jhonnyg** [comment]
@Dragosha - your issue seems fine in the latest alpha (at least on mac), which version are you on?

**Comment by Dragosha** [comment]
> your issue seems fine in the latest alpha (at least on mac), which version are you on?
> update: tested on windows + alpha, seems fine there also.

Hey, I prepared small test branch with two materials: one (left) uses uniforms, second uses vertex attributes
https://github.com/Dragosha/defold-sprite-repeat/tree/attributes_test
How it works on my PC:

https://github.com/defold/defold/assets/842807/5164090f-9fb6-4adf-bf24-b09a6e664a32


Defold version:
<table>
<tr><td>Build time</td><td>2024-03-27T13:04:35.655564</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>d0338d13ad7c5ccd2be3208788805ef5010bf00b</td></tr>
<tr><td>Defold engine sha</td><td>bf4dc66ab5fbbafd4294d32c2797c08b630c0be5</td></tr>
<tr><td>Defold version</td><td>1.7.0</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 551.23</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

I prepared
