### ISSUE TITLE
Some buttons stop responding in the game if you change the keyboard layout to another language

### ISSUE THREAD

**Issue by Devyatyi9** [defold/defold#8739]
**Describe the bug (REQUIRED)**
If you specify a Semicolon, Comma or other non-letter keyboard button in Input Bindings, then when changing the English layout to another one, the game simply does not respond to pressing this button.

**Defold version (REQUIRED):**
  - Version 1.7.0

**Platforms (REQUIRED):**
 - Platforms: Windows
 - OS: Windows 10
 - Device: PC

**Additional context (OPTIONAL):**
In the game.input_binding file, the button name is written as KEY_SEMICOLON, so does the engine use virtual key codes instead of physical ones?

**Comment by Devyatyi9** [comment]
Found the same issue
https://github.com/defold/defold/issues/4855

**Comment by Devyatyi9** [comment]
Fixed in 1.9.2 beta https://github.com/defold/defold/commit/bedb9de52d298c50db06329523bec00779b6ad90 (`bedb9de52d298c50db06329523bec00779b6ad90`)
Related #9228

**Comment by AGulev** [comment]
@Devyatyi9 thank you for testing!
