### ISSUE TITLE
Vulkan crash on Fullscreen

### ISSUE THREAD

**Issue by selimanac** [defold/defold#8747]
It doesn't crash with default 'Basic 3D project' when it is set to full screen, but crashes at my project.It doesn't crash if I set full screen from MacOS Toolbar and it doesn't crash when using OpenGL. 
Somehow camera projection matrix or view matrix fails and Vulkan crashes. 

I know build-in full screen is very problematic and not useful but I just want to share... I hope we will use the default full screen when we got glfw 3.4

Minimal Repo: https://github.com/selimanac/look-at-my-mouse
Please set `display.fullscreen = 1` from `game.project `

- Crashdump: [_crash.zip](https://github.com/defold/defold/files/14823106/_crash.zip)
- MacOS 14.4
- Defold v1.7.0
- Editor: d0338d13ad7c5ccd2be3208788805ef5010bf00b
- Engine: bf4dc66ab5fbbafd4294d32c2797c08b630c0be5

```
ERROR:SCRIPT: builtins/render/default.render_script:71: argument #1 contains one or more values which are not numbers: vmath.matrix4(nan, 0, 0, 0, 0, 3.9163181781769, 0, 0, 0, 0, -1.0020020008087, -0.20020020008087, 0, 0, -1, 0)
stack traceback:
  [C]:-1: in function __mul
  builtins/render/default.render_script:71: in function update_camera
  builtins/render/default.render_script:222: in function <builtins/render/default.render_script:212>

2024-04-01 14:58:31.977 Defold[4138:226551] CAMetalLayer ignoring invalid setDrawableSize width=0.000000 height=0.000000
[mvk-info] Created 3 swapchain images with initial size (0, 0) and contents scale 1.0 for screen Main Screen.
WARNING:GRAPHICS: Vulkan swapchain is out of date, reason: VK_SUBOPTIMAL_KHR.
ERROR:GRAPHICS: Vulkan Error (../src/vulkan/graphics_vulkan.cpp:1345) VK_SUBOPTIMAL_KHR
Assertion failed: (0), function VulkanFlip, file graphics_vulkan.cpp, line 1345.

```

**Comment by Jhonnyg** [comment]
Could you try with the latest alpha? I couldn't repro it locally

**Comment by selimanac** [comment]
Yes, it is not crashing with latest 1.7.1.  Not related, but I can also confirm that [this flickering issue](https://forum.defold.com/t/light-and-shadows-example/71713/17?u=selimanac) is gone now.

Still there is a error(Vulkan &OpenGL) about camera projection matrix or view matrix when fullscreen is on, but who cares :) Nobody is going to use it as it is anyway.

Thank you

**Comment by Jhonnyg** [comment]
Interesting, I didn't get any issues with the projection matrix. But hopefully we can move into a proper fullscreen when glfw is upgraded
