### ISSUE TITLE
Can't rename any files in projects

### ISSUE THREAD

**Issue by Zephyre3777** [defold/defold#8761]
### Expected behaviour
Rename file from previous to literally anything
### Actual behaviour
error
java.lang.AssertionError: Assert failed: (rename? resources)
### Steps to reproduce
Current file i'm working in can't rename
new file I created can't rename 
other project I have can't rename
So reproduce by making blank file and trying to rename anything such as folder or any other file
<hr/>

<table>
<tr><td>Build time</td><td>2024-03-27T13:02:44.527672</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>d0338d13ad7c5ccd2be3208788805ef5010bf00b</td></tr>
<tr><td>Defold engine sha</td><td>bf4dc66ab5fbbafd4294d32c2797c08b630c0be5</td></tr>
<tr><td>Defold version</td><td>1.7.0</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"b3f17e9c19b14d88b5aecd59c58ee004"'>b3f17e9c19b14d88b5aecd59c58ee004</a></td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) UHD Graphics 600 (GLK 2)</td></tr>
<tr><td>GPU Driver</td><td>4.6 (Compatibility Profile) Mesa 23.2.1-1ubuntu3.1~22.04.2</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.15.0-101-generic</td></tr>
<table>

**Comment by vlaaad** [comment]
Can you show a screen recording of how are you trying to rename a file?

**Comment by Zephyre3777** [comment]
https://github.com/defold/defold/assets/113444425/9ce453b0-19c0-47ee-a6b1-96294a391a65

**Comment by vlaaad** [comment]
Hmm yes, I'll try reproducing and debugging it on Linux, thanks!

**Comment by AGulev** [comment]
duplicate https://github.com/defold/defold/issues/9173

**Comment by vlaaad** [comment]
Hi, please check the editor for update, the issue is most probably resolved. Feel free to reopen if the issue returns :)

**Comment by Zephyre3777** [comment]
Yup it's working on my end, thank you.
