### ISSUE TITLE
[1.7.1 Beta] The gui.animate over "euler" property is not working

### ISSUE THREAD

**Issue by Insality** [defold/defold#8791]
**Describe the bug (REQUIRED)**
The new property euler in gui can't be animated with gui.animate() function

**To Reproduce (REQUIRED)**
1. Create node
2. Run gui.animate(node, "euler.z", 90, gui.EASING_OUTSINE, 1)
3. Nothing happen

**Expected behavior (REQUIRED)**
The same as with rotation before 1.7.1

**Defold version (REQUIRED):**
Defold 1.7.1

**Platforms (REQUIRED):**
Tested on MacOS

**Comment by AGulev** [comment]
fixed with https://github.com/defold/defold/pull/8793
(we will merge it into beta tomorrow)
