### ISSUE TITLE
2D Physics engine gravity is broken

### ISSUE THREAD

**Issue by schlista** [defold/defold#8795]
_Is it a private platform, and a platform specific issue? (i.e. would it break your NDA?)<br>
Then please report your issue in the corresponding extension repository!_

**Describe the bug (REQUIRED)**
When using 2D dynamic physics velocity on gravity goes slower than it should.  Where as if I change it to 3d physics the objects accelerate as expected.

**To Reproduce (REQUIRED)**
Create a static object at the bottom of the screen.  Then create a dynamic object above that platform.  Run the code.  The object will slow down as it falls.  Change the physics to 3D and it falls as expected.

**Expected behavior (REQUIRED)**
Gravity should increase the speed of an object as it falls not slow it down.

**Defold version (REQUIRED):**
It has been in defold 1.6.x as I wrote a game with it and it kind of sucks due to the gravity being janky.  Now I'm on 1.7.x and it still does it.  I figured out if moving to the 3D physics it fixed the gravity issue so I know it's not me but the engine.

**Platforms (REQUIRED):**
- windows 11

**Minimal repro case project (OPTIONAL):**
[2d-3dgravity.zip](https://github.com/defold/defold/files/14969712/2d-3dgravity.zip)

**Screenshots (OPTIONAL):**

https://github.com/defold/defold/assets/52429019/0f807846-0b44-48e5-8e65-1f682a9fa6fd

https://github.com/defold/defold/assets/52429019/0b09eff2-8653-4543-8f40-599a1b129d7c

**Comment by britzl** [comment]
Not a bug: https://forum.defold.com/t/physic-issues-again/76582/13?u=britzl
