### ISSUE TITLE
hash value in error log is not correct (release version)

### ISSUE THREAD

**Issue by d954mas** [defold/defold#8804]
**Describe the bug (REQUIRED)**
I have error in poki console
```
DEFOLD:ERROR:GAMEOBJECT: Component ‘<unknown:4875305475194650161>#<unknown:4875305475194650161>’ could not be found when dispatching message ‘<unknown:4875305475194650161>’ sent from game_scene:<unknown:4875305475194650161>#<unknown:4875305475194650161>\n”
```
https://github.com/defold/defold/blob/520861f3edf18d2c89a7dc5fa479b8cb5cc70172/engine/gameobject/src/gameobject/gameobject.cpp#L2283

I can't understand it. It is strange that in log all hash values are the same.

I make repro case. In debug you will see this:

```
"ERROR:GAMEOBJECT: Component '/go#unknown_component' could not be found when dispatching message 'my message' sent from main:/go#init"
```
In release on web build(i add console.log with error in web build) you will see this:
```
Component '<unknown:7303218731325906595>#<unknown:7303218731325906595>' could not be found when dispatching message '<unknown:7303218731325906595>' sent from main:<unknown:7303218731325906595>#<unknown:7303218731325906595>
```

```lua
function init(self)
	msg.post("main:/go#unknown_component", "my message")
	local print_web = function(str)
		if html5 then html5.run("console.log(\"" ..str .. "\")") end
	end
	print_web(hash("main:"))
	print_web(hash("/go"))
	print(hash("unknown_component"))
	print_web(hash("my message"))
end
```

```
[17280348633309717095 (unknown)]
[2403139543084994936 (unknown)]
[7303218731325906595 (unknown)]

DEFOLD:ERROR:GAMEOBJECT: Component '<unknown:7303218731325906595>#<unknown:7303218731325906595>' could not be found when dispatching message '<unknown:7303218731325906595>' sent from main:<unknown:7303218731325906595>#<unknown:7303218731325906595>
```

**To Reproduce (REQUIRED)**
1. Open reprocase
2. Bundle web application in release mode
3.In console you will see
```

```

**Expected behavior (REQUIRED)**
Every hash value will show correct different values

**Defold version (REQUIRED):**
  - Version 1.7.0

**Platforms (REQUIRED):**
 - Platforms:HTML5
 -Only in release build

**Minimal repro case project (OPTIONAL):**

[hash_unknown.zip](https://github.com/defold/defold/files/14997528/hash_unknown.zip)

**Comment by JCash** [comment]
I agree, that printout looks off.
I recently did a change to the output, ro make it thread safe, and must have messed something up somehow 🤔 
I'll have a look tomorrow.

**Comment by d954mas** [comment]
I will test in beta later.
This happened for me in 1.7.0

**Comment by d954mas** [comment]
DEFOLD:ERROR:GAMEOBJECT: Component '<unknown:2403139543084994936>#<unknown:11740452024393856384>' could not be found when dispatching message '<unknown:7303218731325906595>' sent from main:<unknown:2403139543084994936>#<unknown:1484653112899155046>

Worked correctly in 1.8.0
