### ISSUE TITLE
Load and use fonts at runtime

### ISSUE THREAD

**Issue by CrazyAmphibian** [defold/defold#8808]
**Is your feature request related to a problem? Please describe (REQUIRED):**
The engine lacks this feature. This feature would improve my experience as a developer (less fonts to juggle), as well as the experience for users (fonts can be tailored to the screen size to avoid fuzziness or accessibility settings to use a bigger font for easier reading)

**Describe the solution you'd like (REQUIRED):**
The ability to generate and assign a font to a gui with a font file (.ttf or ect.) via code during runtime

**Describe alternatives you've considered (REQUIRED):**
I've considered just bundling a bunch of fonts that one might need, but the problem this results in is a massive amount of .font files, which causes compile times to be really long

**Additional context (OPTIONAL):**
![TOO MANY FONTS PLEASE HELP ME AAAAAAAAAAA](https://github.com/defold/defold/assets/68451232/86e2849f-8cd1-4d96-8529-c52c1fbbd732)

**Comment by AGulev** [comment]
This issue fixed in 1.9.4  https://forum.defold.com/t/defold-1-9-4-has-been-released/78534

with https://github.com/defold/extension-fontgen
