### ISSUE TITLE
Does not apply size property to node in manual size mode. (rotated sprite in atlas)

### ISSUE THREAD

**Issue by Dragosha** [defold/defold#8826]
The issue is that in some cases the manual size mode is not applied to gui node in the editor.  But it works absolutely correctly in runtime. I caught the issue by chance, in version 1.7.0. In beta 1.8.0 it is still there.

In the video I apply to node in the first case atlas with rotated atlas packing picture, in the second case with normal position. The picture is the same. The node is the same. The difference, as far as I can see, is how the editor packed the resource into the atlas.

https://github.com/defold/defold/assets/842807/4bf8c139-2932-40a2-bb2f-93beeaa4ec0a

The first atlas (rotated sprite):
![2024-04-22_15-36-50](https://github.com/defold/defold/assets/842807/9c1ecd09-4273-41a8-bcd3-570f244828c9)

The second.
![2024-04-22_16-12-08](https://github.com/defold/defold/assets/842807/992a35e8-ddf5-4242-9b22-e2d73ada6045)

<hr/>

<table>
<tr><td>Build time</td><td>2024-04-22T08:34:17.916817</td></tr>
<tr><td>Defold channel</td><td>beta</td></tr>
<tr><td>Defold editor sha</td><td>bf9b9ff94ee975a4f0301c1f870bf5e328a90334</td></tr>
<tr><td>Defold engine sha</td><td>bf9b9ff94ee975a4f0301c1f870bf5e328a90334</td></tr>
<tr><td>Defold version</td><td>1.8.0</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 551.23</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by AGulev** [comment]
repro 
[test.zip](https://github.com/defold/defold/files/15062158/test.zip)
