### ISSUE TITLE
On the html5 platform, luaL_checkinteger and lua_pushinteger return a 32-bit number instead of a 64-bit number.

### ISSUE THREAD

**Issue by megalanthus** [defold/defold#8859]
### Expected behaviour
When writing a native extension, luaL_checkinteger and lua_pushinteger are expected to return 64-bit numbers

### Actual behaviour
On the html5 platform, luaL_checkinteger and lua_pushinteger return 32 bit.

### Steps to reproduce
Open a test project and run it on the html5 platform.

<hr/>
Test project:

[lua_integer.zip](https://github.com/defold/defold/files/15137050/lua_integer.zip)

Log from the HTML5 platform:
<img width="201" alt="html5" src="https://github.com/defold/defold/assets/66716124/412ce147-3fbd-46e4-9dac-18f366630d15">
Log from the Windows platform:
<img width="242" alt="windows" src="https://github.com/defold/defold/assets/66716124/2c49250c-4a77-4a16-a409-fe27600dec62">

<table>
<tr><td>Build time</td><td>2024-04-25T16:28:41.309201</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>6ff357fdf05b853e628ba6200e076fa87b0f8318</td></tr>
<tr><td>Defold engine sha</td><td>fd3b8c652df601220d8651f581fa2fada8205237</td></tr>
<tr><td>Defold version</td><td>1.8.0</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GTX 1060 3GB/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 536.23</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by redoak** [comment]
HTML5 builds are 32-bit. Lua's `lua_Integer` type is an alias for `ptrdiff_t`, which is why it's 32b in this case.

I would like to have the option to make 64-bit HTML5 builds, simplifying extension development.

In your case, you might be able to work with `lua_Number` (alias for `double`) to get around this issue, e.g. `lua_pushnumber`. Lua works on doubles, and the functions for pushing and retrieving `lua_Integer` are only convenient interfaces for converting between integer and double.

**Comment by megalanthus** [comment]
> In your case, you might be able to work with `lua_Number` (alias for `double`) to get around this issue, e.g. `lua_pushnumber`. Lua works on doubles, and the functions for pushing and retrieving `lua_Integer` are only convenient interfaces for converting between integer and double.

Yes, that’s what I did for now, but I wanted to be 100% sure that it would be an integer, because the data is sent to the server.

**Comment by redoak** [comment]
> I wanted to be 100% sure that it would be an integer, because the data is sent to the server.

It's worth noting that `luaL_checkinteger` only checks if the value is a number — it doesn't check if it has a non-zero decimal part.

When I expect the number to fit in a certain type, I do something this, where I verify that the value "is" a 16b unsigned integer:

```lua
const lua_Number arg = luaL_checknumber(L, index);
assert(arg >= 0. && arg <= 65535.);
assert(fmod(arg, 1.) == 0.);
-- you may want to raise a lua_error rather than asserting.
```

**Comment by megalanthus** [comment]
> It's worth noting that `luaL_checkinteger` only checks if the value is a number — it doesn't check if it has a non-zero decimal part.

Well, actually, I asked myself this question because I’m interested in numbers larger than 32 bits, and I understand that there will only be 52 integers (if I’m not mistaken), but still this is much more than a 32 bit number.

From the lua documentation:
lua_Integer luaL_checkinteger (lua_State *L, int narg);
Checks whether the function argument narg is a number and returns this number cast to a lua_Integer.

In any case, the difference in behavior between platforms looks like a bug. Moreover, all mathematics (with values greater than a 32-bit number) purely on the Lua side works fine on all platforms.

**Comment by JCash** [comment]
"In any case, the difference in behavior between platforms looks like a bug"

I don't agree. As redoak mentioned, it's based off of `ptrdiff_t`, and we wish to do as few modifications to the library (vanilla Lua 5.1 in this case). While we could, we would have to do it for other 32-bit platforms as well. I think it's much better to stay within the intended/documented limitations of the library.

We do use double, as the number type, so perhaps you can use that instead? It will be integer accurate to quite high numbers.
But also, if you are already limited by 52-bits, then I would probably still limit myself to 32-bit, for better ease-of-use. 
E.g. I'd use `dmHashString32()` for any hashes. Perhaps you could do something similar? Or keep 2 uint32_t`


All in all, I think a better option would be to move to a 64 bit html5 platform, but that's still experimental in Emscripten, so we'll have to wait a bit longer.
