### ISSUE TITLE
CTRL- shortcut for IDE text size crashes

### ISSUE THREAD

**Issue by hippocoder** [defold/defold#8860]
### Expected behaviour
Text gets smaller or hits minimum text size
### Actual behaviour
Defold crashes
### Steps to reproduce
Press CTRL -  a few times.
<hr/>

<table>
<tr><td>Build time</td><td>2024-04-25T16:28:41.309201</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>6ff357fdf05b853e628ba6200e076fa87b0f8318</td></tr>
<tr><td>Defold engine sha</td><td>fd3b8c652df601220d8651f581fa2fada8205237</td></tr>
<tr><td>Defold version</td><td>1.8.0</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 552.22</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 11</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by hippocoder** [comment]
This doesn't always crash though.  I believe it was after I added linting, but that may be unrelated

**Comment by britzl** [comment]
Did you get a stack trace? Can you reproduce it?

**Comment by AGulev** [comment]
Requested additional info wasn't provided
