### ISSUE TITLE
.luacheckrc file is ignored with defold linting (lua language server asset)

### ISSUE THREAD

**Issue by hippocoder** [defold/defold#8861]
### Expected behaviour
Added .luacheckrc with unused_args = false in project root
and expected it to ignore function arguments that are unused
### Actual behaviour
ignored file 
### Steps to reproduce
as above. To work around, I rename all variables unused to _ 
<hr/>

<table>
<tr><td>Build time</td><td>2024-04-25T16:28:41.309201</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>6ff357fdf05b853e628ba6200e076fa87b0f8318</td></tr>
<tr><td>Defold engine sha</td><td>fd3b8c652df601220d8651f581fa2fada8205237</td></tr>
<tr><td>Defold version</td><td>1.8.0</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 552.22</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 11</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
This is working for me on macOS at least. Remember that if you make a change to the .luacheckrc file you also need to make a change in the linted file before the code editor updates.

**Comment by vlaaad** [comment]
In my experience it does not work on Windows, but works on mac

**Comment by britzl** [comment]
> In my experience it does not work on Windows, but works on mac

Do we know why? Because it is a . file?

**Comment by vlaaad** [comment]
Don't know... Maybe somehow related to this line here https://github.com/defold/lua-language-server/blob/fc0b6da79648013f5cd88ac01fcf44f1e1d78358/script/core/diagnostics/luacheck.lua#L36 ? Could be something about `\` and `/`...

**Comment by britzl** [comment]
Ok, could we perhaps print the rootUri and path to see what they resolve to? I suppose such prints will end up in stdout?

```lua
        local rootUri = (workspace.rootUri or ""):gsub("file://", "")
        local path = fs.join(rootUri, ".luacheckrc")
        print(rootUri, path)
```

**Comment by vlaaad** [comment]
Fixed in the latest editor
