### ISSUE TITLE
GO/SPRITE Tint access in editor

### ISSUE THREAD

**Issue by jcbk101** [defold/defold#8872]
Wanted to know if it is possible to get access to `tint` property in the editor for GO/Sprites. Access where it is visually updated in the editor. Testing in Material is okay, but setting as a `go.property` I think would be beneficial to us.

**Comment by ivanquirino** [comment]
Always check the examples, manuals and API: https://defold.com/examples/sprite/tint/

**Comment by AGulev** [comment]
I think in this case this example fits better https://defold.com/examples/material/vertexcolor/

it is possible to use vertex colors instead of constant, then it will be possible to specify it from the editor

**Comment by jcbk101** [comment]
I thought of using the vertex version, but I was not sure if it would cause batch breaking.


________________________________

**Comment by AGulev** [comment]
no, it's oposite. tint breaks batch.
