### ISSUE TITLE
collectionproxy.get_resources() returns empty table

### ISSUE THREAD

**Issue by JustAPotota** [defold/defold#8909]
**Describe the bug (REQUIRED)**
The return value of `collectionproxy.get_resources()` is always an empty table.

**Expected behavior (REQUIRED)**
It should return the hashes of the resources used by the proxied collection.

**Defold version (REQUIRED):**
1.8.0

**Platforms (REQUIRED):**
Fedora Silverblue 40

**Minimal repro case project (OPTIONAL):**
[collectionproxyresources.zip](https://github.com/defold/defold/files/15283803/collectionproxyresources.zip)

**Comment by britzl** [comment]
> collectionproxy.get_resources()

This function will only ever return something if the collection was excluded (ie for Live Update).

**Comment by JustAPotota** [comment]
That should be stated in the docs or a warning when calling it.
