### ISSUE TITLE
Unexpected object id created by factory in release build

### ISSUE THREAD

**Issue by trinhccao** [defold/defold#8916]
_Is it a private platform, and a platform specific issue? (i.e. would it break your NDA?)<br>
Then please report your issue in the corresponding extension repository!_

**Describe the bug (REQUIRED)**
The game object id created by `factory.create()` is in the unexpected format in release build.
I try to use game object id created by `factory.create()`. In debug build, the returned id is ok with this format `/instance1`, but in the release build, the factory return id with this format `<unknown:82734872abed3298>` that is unusable.

**To Reproduce (REQUIRED)**
Project -> Bundle -> Choose any platform -> Choose release variant

**Expected behavior (REQUIRED)**
The same id format as debug build

**Defold version (REQUIRED):**
  - 1.8.0

**Platforms (REQUIRED):**
 - Any platform

**Example Code**
```lua
function spawn(self)
	local spawn = utils.get_spawn()
	local pos = vmath.vector3(spawn.position, -78, 0.1)
	local id = factory.create("#factory", pos)
	local bug_sprite = id .. "#sprite"
	sprite.set_hflip(bug_sprite, spawn.flip)
	self.last_spawn = self.now
	msg.post("gui#gameinfo", "debug", { data = bug_sprite })
end
```

**Screenshots (OPTIONAL):**

![release-build](https://github.com/defold/defold/assets/53936904/9c977220-5289-4c6c-b50c-31e8638919f2)
![debug-build](https://github.com/defold/defold/assets/53936904/fd01663c-33ec-40fd-94f6-646554bcb904)

**Comment by JustAPotota** [comment]
Converting a hash (which an ID is) to its original string is a debug feature and shouldn't be relied on. This is the proper way to access the sprite of a spawned game object:
```lua
local id = factory.create("#factory", pos)
local sprite_url = msg.url(nil, id, "sprite")
sprite.set_hflip(sprite_url, spawn.flip)
```

**Comment by AGulev** [comment]
`id`  isn't a string
You can't use it the way you use it

if you want to get access to sprite component use like this:

```lua
local id = factory.create("#factory", pos)
local my_comp_url = msg.url(nil, id, "sprite")
sprite.set_hflip(my_comp_url, spawn.flip)
```
