### ISSUE TITLE
Previously-supported string escape sequences no longer supported

### ISSUE THREAD

**Issue by greay** [defold/defold#8923]
**Describe the bug (REQUIRED)**
Prior to the latest version of Defold, this code was supported:

```
local emotes = {
	["\xF0\x9F\x99\x81"] = "slight frown", -- 🙁
	["\xE2\x98\xB9\xEF\xB8\x8F"] = "sad",  -- ☹️
	["\xF0\x9F\x98\xAE"] = "surprised",    -- 😮
	["\xF0\x9F\x99\x82"] = "slight smile", -- 🙂
	["\xF0\x9F\x98\x84"] = "smiling eyes", -- 😄
	["\xF0\x9F\x98\x86"] = "laughing",     -- 😆
	["\xF0\x9F\x98\xA0"] = "angry",        -- 😠
	["\xF0\x9F\x98\xA1"] = "very angry",   -- 😡
	["\xF0\x9F\xA4\xAC"] = "angry",        -- 🤬
}
```

**To Reproduce (REQUIRED)**
simply include the above code, and build

**Expected behavior (REQUIRED)**
builds without error

**Defold version (REQUIRED):**
  - Version 1.8.0 (e590e9384643a24d7b664bdd83b249e365221afe)

**Platforms (REQUIRED):**
macOS

**Minimal repro case project (OPTIONAL):**
Please attach a minimal project where the bug is reproduced. This will greatly help the person trying to investigate and fix the bug.

**Logs (OPTIONAL):**

> /main/portraits.lua
>	Line 50: Invalid escape sequence.(Supported in Lua 5.2/Lua 5.3/Lua 5.4/LuaJIT, current is Lua 5.1.)

**Comment by britzl** [comment]
I actually don't think those escape sequences will work in Lua 5.1.5, ie if you build for HTML5. BUT with that said, if you don't care about HTML5 then this is an annoying error preventing you from building.

A quick workaround is to use string.char() instead:

```lua
local emotes = {
	[string.char(0xF0, 0x9F, 0x99, 0x81)] = "slight frown", -- 🙁
	[string.char(0xE2, 0x98, 0xB9, 0xEF, 0xB8, 0x8F)] = "sad",  -- ☹️
	[string.char(0xF0, 0x9F, 0x98, 0xAE)] = "surprised",    -- 😮
	[string.char(0xF0, 0x9F, 0x99, 0x82)] = "slight smile", -- 🙂
	[string.char(0xF0, 0x9F, 0x98, 0x84)] = "smiling eyes", -- 😄
	[string.char(0xF0, 0x9F, 0x98, 0x86)] = "laughing",     -- 😆
	[string.char(0xF0, 0x9F, 0x98, 0xA0)] = "angry",        -- 😠
	[string.char(0xF0, 0x9F, 0x98, 0xA1)] = "very angry",   -- 😡
	[string.char(0xF0, 0x9F, 0xA4, 0xAC)] = "angry",        -- 🤬
}
```
