### ISSUE TITLE
Editor exit confirmation

### ISSUE THREAD

**Issue by zendorx** [defold/defold#8933]
On mac OS game window and editor windows looks similar and often I close editor instead of game window by clicking (X). After that I need to reopen all tabs in editor.

It would be nice to have some popup of exit confirmation.

**Comment by j-h-a** [comment]
If this is implemented, please put it on a setting so the default is to keep the existing behaviour.

**Comment by vlaaad** [comment]
Hi @zendorx! Thank you for your suggestion. We discussed it and decided not to do it for now. Usually you can press <kbd>Esc</kbd> to close the game window. Also, if you accidentally closed the editor, you can use the <kbd>Cmd Shift T</kbd> shortcut after re-opening it the editor to bring back the previously closed tabs.
