### ISSUE TITLE
mac m1 can't build on 1.8.1 beta

### ISSUE THREAD

**Issue by SalavatR** [defold/defold#8936]
**Describe the bug (REQUIRED)**
try to build from editor and got error

```
com.defold.extender.ExtenderException: /usr/local/extender-production/sdk/67a1a88a6fa8ecabbcd252e3d052d153db549ade/defoldsdk/extender/build.yml:1: error: Cannot create property=platforms for JavaBean=com.defold.extender.Configuration@5d714b93
 in 'string', line 1, column 1:
    context:
    ^
Cannot create property=bitcodeStripCmd for JavaBean=com.defold.extender.PlatformConfig@57be4f62
 in 'string', line 115, column 5:
        env:
        ^
Unable to find property 'bitcodeStripCmd' on class: com.defold.extender.PlatformConfig
 in 'string', line 164, column 25:
        bitcodeStripCmd:    '{{env.PLATFORMSDK_DIR}}/XcodeDe ... 
```
                            ^

deps list:
dependencies#0 = https://github.com/Insality/druid/archive/refs/tags/0.10.3.zip
dependencies#1 = https://github.com/britzl/monarch/archive/refs/tags/5.1.1.zip
dependencies#2 = https://github.com/britzl/ludobits/archive/refs/tags/7.4.0.zip
dependencies#3 = https://github.com/britzl/defold-input/archive/refs/tags/4.6.2.zip
dependencies#4 = https://github.com/britzl/defold-metrics/archive/refs/tags/1.2.1.zip
dependencies#5 = https://github.com/britzl/defold-orthographic/archive/refs/tags/3.3.1.zip
dependencies#6 = https://github.com/britzl/defold-clipboard/archive/refs/tags/1.24.0.zip
dependencies#7 = https://github.com/AGulev/defold-extension-uptime/archive/refs/tags/1.2.0.zip
dependencies#8 = https://github.com/Melsoft-Games/defold-protobuf/archive/0e5d3b2.zip
dependencies#9 = https://github.com/defold/extension-spine/archive/7e8fd9f6bcc2bdf8fe28cbd1db136fce18f28b1d.zip
dependencies#10 = https://github.com/defold/extension-iap/archive/refs/tags/6.0.0.zip
dependencies#11 = https://github.com/indiesoftby/defold-sentinel/archive/refs/tags/1.2.0.zip
dependencies#12 = https://github.com/defold/extension-safearea/archive/refs/tags/1.4.0.zip
dependencies#13 = https://github.com/britzl/extension-imgui/archive/refs/tags/1.3.4.zip
dependencies#15 = https://github.com/HGPoint/def_platform_uuid/archive/refs/tags/1.0.0.zip

**To Reproduce (REQUIRED)**
try build project from editor

**Defold version (REQUIRED):**
  - Version 1.8.1 - beta

**Platforms (REQUIRED):**
 - Platforms: [macOS 14.4.1]

**Comment by AGulev** [comment]
use right extender with beta version: https://build-stage.defold.com
