### ISSUE TITLE
Viewport controls for perspective and view filters only get highlighted when the mouse is over the bright pixels

### ISSUE THREAD

**Issue by f2l2pe** [defold/defold#8941]
**Describe the bug (REQUIRED)**
Viewport controls for perspective and filters only get highlighted when the mouse is over the bright pixels

**To Reproduce (REQUIRED)**
1. Go to the viewport
2. Put the mouse close to the perspective toggle or view filters

**Expected behavior (REQUIRED)**
The icons should be highlighted like the move, rotate, and scale icons, when the mouse is near the icon and not only when it's over the bright pixels

**Defold version (REQUIRED):**
  - 1.8.1

**Platforms (REQUIRED):**
 - Platforms: Any

**Screenshots (OPTIONAL):**

https://github.com/defold/defold/assets/6012227/8b59a747-6522-4118-8724-6f7e98a97dde

**Comment by matgis** [comment]
Regression from #8855. Before, these icons did not highlight on hover.

**Comment by britzl** [comment]
Fixed by https://github.com/defold/defold/commit/1a074c21277d3355b68c3fe12538a3b32fc86eac
