### ISSUE TITLE
Editor autocomplete suggests global variable _G

### ISSUE THREAD

**Issue by dri-richard** [defold/defold#8946]
**Describe the bug**
In some situations, the editor suggests the global variable _G (and other items) when it would be better to suggest nothing.

**To Reproduce**
1. In the code editor type an opening curly brace or comma
2. Notice that a list of suggestions is given, with _G at the top
3. Hit return
4. _G has been inserted

**Expected behavior**
No autocomplete occurs. I can imagine the autocomplete might be more useful after a comma in other situations, maybe a function call.

**Defold version:**
 1.8.0 / 1.8.1 beta

**Platforms:**
 - Platforms: macOS
 - Device: Macbook Pro

**Screenshots :**

![image](https://github.com/defold/defold/assets/26457985/94b397e2-234d-4e09-b296-3d3f94620c33)
![image](https://github.com/defold/defold/assets/26457985/ed981e82-bc0b-4798-98f8-d077469ed75c)
<img width="293" alt="image" src="https://github.com/defold/defold/assets/26457985/6006f4b2-e77d-455d-8cb1-c6da430e77e9">

**Comment by subsoap** [comment]
related https://github.com/defold/defold/issues/8940

**Comment by vlaaad** [comment]
Fixed
