### ISSUE TITLE
Issue with factory inside a collectionfactory 

### ISSUE THREAD

**Issue by trinhccao** [defold/defold#8964]
_Is it a private platform, and a platform specific issue? (i.e. would it break your NDA?)<br>
Then please report your issue in the corresponding extension repository!_

**Describe the bug (REQUIRED)**
My game hierarchy is as follow:
- main.collection
  - level
    - collectionfactory - level.collection as prototype
  - main
    - main.script - used to call collectionfactory.create() to create level.collection instance
- level.collection
  - go
  - player
    - factory - player.go as prototype
- player.go
    - player.script

The problem is that, I'm trying to post message from `player.script` to go using this code `msg.post("go", "message")` but this will fail. With message `Instance '/go' could not be found when dispatching message 'message' sent from main:/instance0#player`.
If the player is created directly inside editor (without factory), the script is able to `msg.post("go", "message")` normally.

**To Reproduce (REQUIRED)**
1. Run example file

**Expected behavior (REQUIRED)**
The `player.script` able to call `msg.post("go", "message")` successfully

**Defold version (REQUIRED):**
  - Version 1.8.0

**Platforms (REQUIRED):**
 - Platforms: Windows
 - OS: Windows 11

**Minimal repro case project (OPTIONAL):**
[Example.zip](https://github.com/defold/defold/files/15380350/Example.zip)

**Logs (OPTIONAL):**
Please provide relevant logs from engine, editor or build server. Learn where the logs are stored [here](https://defold.com/manuals/getting-help/#log-files).

**Workaround (OPTIONAL):**
If there is a workaround, please describe it here.

**Screenshots (OPTIONAL):**

**Additional context (OPTIONAL):**

**Comment by britzl** [comment]
This is working as designed.
