### ISSUE TITLE
Debugger will not run on Android device

### ISSUE THREAD

**Issue by jcbk101** [defold/defold#8981]
### Expected behaviour
Game runs in debug mode on real device.

### Actual behaviour
Nothing happens. Game compiles and goes back to `Ready`. Then a crash window appears shortly there after.

### Steps to reproduce
Connect a real device, click `Start/Attach`.
<hr/>

<table>
<tr><td>Build time</td><td>2024-04-24T10:38:45.841880</td></tr>
<tr><td>Defold channel</td><td>beta</td></tr>
<tr><td>Defold editor sha</td><td>ef07c036b8f7d34f4b1d7fcc355ce46a92d2dcc8</td></tr>
<tr><td>Defold engine sha</td><td>ef07c036b8f7d34f4b1d7fcc355ce46a92d2dcc8</td></tr>
<tr><td>Defold version</td><td>1.8.0</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"004013920f374f2a80f27b98224ada8f"'>004013920f374f2a80f27b98224ada8f</a></td></tr>
<tr><td>GPU</td><td>GeForce GT 730/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 456.71</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by AGulev** [comment]
```
editor.debugging.mobdebug$connect_BANG_$fn__61098.invoke.class clojure.lang.ExceptionInfo: Failed to connect to debugger on 192.168.42.129:8172
    at editor.debugging.mobdebug$connect_BANG_$fn.invoke(mobdebug.clj:159)
    at clojure.lang.AFn.run(AFn.java:22)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.lang.Thread.run(Thread.java:833)
    ```

**Comment by jcbk101** [comment]
Hello @AGulev, is there anything else needed from me? Thanks.

**Comment by britzl** [comment]
@jcbk101 does this happen in all projects or just the one? Do you have a log from the device that you could share?

**Comment by britzl** [comment]
Note: We should surface this as a nice user error in a popup with some likely reasons for the connection problem.

**Comment by britzl** [comment]
@jcbk101 I noticed that we have an ongoing discussion about this exact problem in a different issue which you created a year ago :-)

https://github.com/defold/defold/issues/8981

Closing this issue as a duplicate

**Comment by jcbk101** [comment]
Thank you. It is strange as I recall the debugger working at least once a twice on a device before. Or maybe I am seeing things. 😂


________________________________
