### ISSUE TITLE
Support 'flat' interpolation qualifier for shaders

### ISSUE THREAD

**Issue by Wolfe2x7** [defold/defold#9008]
**Is your feature request related to a problem?:**
When I try to assign a varying as `flat` so it will not be interpolated, Defold throws the error, "interpolation qualifiers must appear before storage and precision qualifiers". In spite of the wording of the error, the declaration order is irrelevant. `flat` isn't accepted at all.

I'd like to program effects that are uniform across each triangle, and this limitation makes it challenging.

**Describe the solution you'd like:**
Support the `flat` interpolation qualifier and make it available to users.

**Describe alternatives you've considered:**
I can use orthogonal vectors to try to avoid the visual artifacts I am trying to eliminate, but the final effect is inferior.

**Comment by nanaktaev** [comment]
This is a highly desirable feature for me also. I render a lot of quads and I want to make certain calculations once for every vertex of the quad in vertex shader and interpolate between them in fragment shader. For that I need "flat".

**Comment by Wolfe2x7** [comment]
>In spite of the wording of the error, the declaration order is irrelevant. flat isn't accepted at all.

My mistake! I thought I tried it all, but this declaration works as desired, at least as of Defold version 1.9.1. 🤔
```
flat varying vec4 my_varying;
```
I thought putting `flat` first was invalid. I consider this issue closed now. 👍

**Comment by Jhonnyg** [comment]
Nice! I didn't get around to test this yet, but thanks for letting us know 👍
