### ISSUE TITLE
b2d.body.set_angular_velocity() is missing

### ISSUE THREAD

**Issue by Lampogolovii** [defold/defold#9010]
**Requested feature**
It would be great to have b2d.body.set_angular_velocity() function

**The problem**
There are some cases when I need to set angular velocity to a body:
- I use pool for physics based bullets in my game. On spawn - I need to set angular velocity to 0
- I have physics obstacles in my game. I use dynamic type for them. And I need to control these objects by linear and angular velocities as well
- When player throws an object with parabolae path - I want to spin this object a bit for visual beauty. Setting an angular velocity is most obvious way to do it

**Additional context**
There are set- and get- functions for linear velocity:
b2d.body.set_linear_velocity()
b2d.body.get_linear_velocity()

But there is only get- function for angular velocity:
b2d.body.get_angular_velocity()

**Comment by AGulev** [comment]
this function exist, but there is a mistake in documentation

please check:
```
/*# Set the angular velocity.
 * @name b2d.body.set_angular_velocity
 * @param body [type: b2Body] body
 * @param omega [type: number] the new angular velocity in radians/second.
 */
 ```

**Comment by Lampogolovii** [comment]
woooow! thanks a lot! my mistake!
I didn't think to type and check this function just by the name.
sorry for that!

**Comment by AGulev** [comment]
no it's not your mistake at all, it's typo in our documentation. 
I prepared a fix https://github.com/defold/defold/pull/9011
