### ISSUE TITLE
Vulkan doesn't take into account swap interval (vsync)

### ISSUE THREAD

**Issue by aglitchman** [defold/defold#9014]
**Describe the bug (REQUIRED)**
Vulkan renderer always waits for vsync, i.e. it's impossible to run the game as fast as possible.

**To Reproduce (REQUIRED)**
1. Switch on the Vulkan, i.e. `--graphics-adapter=vulkan`
2. Turn off the vsync, i.e. set swap interval to 0.
3. `dt` will be the same, i.e. 1/60 (depends on your display).

**Expected behavior (REQUIRED)**
Without vsync on, the game should run as fast as possible.

**Defold version (REQUIRED):**
  - Version: 1.8.1

**Platforms (REQUIRED):**
 - OS: Windows 10/11

**Minimal repro case project (OPTIONAL):**
[test_vsync_dt.zip](https://github.com/user-attachments/files/15519198/test_vsync_dt.zip)

**Screenshots (OPTIONAL):**
Vulkan:
![image](https://github.com/defold/defold/assets/193258/bb4662db-578d-48f2-a62e-4940d4422b10)

OpenGL:
![image](https://github.com/defold/defold/assets/193258/febaffbb-1abe-4ca9-ac24-0e782f2e2642)

**Comment by wojtossfm** [comment]
Cannot say this is 100% the only place that needs updating but it does seem relevant that wanting vsync is hard-coded to true (at least assuming sane variable names and if the present mode is respect afterwards)

https://github.com/defold/defold/blob/0197f9deefa45cdc7ddf8830eb031f2bb7e10c54/engine/graphics/src/vulkan/graphics_vulkan.cpp#L755
