### ISSUE TITLE
Bundling for MacOS generates file in .app dirrectory

### ISSUE THREAD

**Issue by ivolff** [defold/defold#9024]
When bundling for MacOS, defold generates ```PrivacyInfo.xcprivacy``` file on .app dirrectory

And than application cant be notarized. (.app dirrectory can contain only Content folder)

### Steps to reproduce
Just create bundle for MacOS with editor either bob.
Check up .app folder

<hr/>

<table>
<tr><td>Build time</td><td>2024-05-28T14:20:53.141474</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>7247f038fba6f40cda23c5ea2e38e9fde69a2ea6</td></tr>
<tr><td>Defold engine sha</td><td>fd1ad4c17bfdcd890ea7176f2672c35102384419</td></tr>
<tr><td>Defold version</td><td>1.8.1</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce RTX 3070 Laptop GPU/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 551.61</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 11</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by Insality** [comment]
As a current workaround you can delete this file before notarize step
