### ISSUE TITLE
Equivalent embedded data in editable and non-editable resource cause exception on build

### ISSUE THREAD

**Issue by matgis** [defold/defold#9025]
**Describe the bug (REQUIRED)**
If an embedded game object or component inside a game object or collection located below a directory marked non-editable matches an equivalent embedded object in a regular game object or collection, building the project throws an exception.

**To Reproduce (REQUIRED)**
1. Create a game object file and add an embedded component to it.
2. Make a copy of the game object file below a directory marked non-editable in `game.project`.
3. Reference both game objects from the main collection.
4. Build the project.

**Expected behavior (REQUIRED)**
The project builds successfully. In the build output, the embedded component becomes a single binary referenced by both game objects.

**Defold version (REQUIRED):**
1.8.1

**Comment by AGulev** [comment]
As I understand this one fixed?
