### ISSUE TITLE
Extrude Borders Brake sampler alpha

### ISSUE THREAD

**Issue by zendorx** [defold/defold#9036]
I want to set different atlases for sprite for tex0 and tex1. One of the atlases has extrude borders. If extrude borders are different in that atlasses than alpha channel in shader will return wrong values.

Expected behaviour: chaning extrude borders for atlas wont change shader behaviour.

Sample project
[SampleProblem.zip](https://github.com/user-attachments/files/15594626/SampleProblem.zip)

I made sample project to reproduce the problem. In this project shader draw alpha for sprite
Expected behaviour:
<img width="1626" alt="Снимок экрана 2024-06-05 в 20 54 33" src="https://github.com/defold/defold/assets/909905/2a77a82f-7a3b-467d-8b8f-3ec0d58ded33">

After chaning extrude borders second sprite will corrupted
<img width="1579" alt="Снимок экрана 2024-06-05 в 20 54 41" src="https://github.com/defold/defold/assets/909905/487da3aa-e60f-4a8f-8f00-9e0ecc085402">

<hr/>

<table>
<tr><td>Build time</td><td>2024-06-04T09:08:39.626965</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>4c7dbc52fd44cb584c4cada8328c58a64dc3028d</td></tr>
<tr><td>Defold engine sha</td><td>fd1ad4c17bfdcd890ea7176f2672c35102384419</td></tr>
<tr><td>Defold version</td><td>1.8.1</td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 560X OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-4.9.48</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>13.0</td></tr>
<table>

**Comment by zendorx** [comment]
Note: I dont want to use extrude borders for it. But it took a lot of time to figure out where is the problem

**Comment by AGulev** [comment]
I'm not sure if I get it. Atlas getting bigger because of extrude borders, and now your size dependent shader shows a piece of your image

**Comment by zendorx** [comment]
> I'm not sure if I get it. Atlas getting bigger because of extrude borders, and now your size dependent shader shows a piece of your image

Is that mean that UV became more than 1? It is not clear

Also extruder border is 2. It can change final image probably for 2x2 pixels by sides. But it looks like two times bigger

**Comment by zendorx** [comment]
Also it affetcs only alpha. RGA values of sampler is ok

**Comment by AGulev** [comment]
> > I'm not sure if I get it. Atlas getting bigger because of extrude borders, and now your size dependent shader shows a piece of your image
> 
> Is that mean that UV became more than 1? It is not clear

https://github.com/defold/defold/issues/7045

**Comment by AGulev** [comment]
> Also it affetcs only alpha. RGA values of sampler is ok

it doesn't affect alpha, If I turn off extrude borders it's the same
![CleanShot 2024-06-05 at 21 13 56@2x](https://github.com/defold/defold/assets/2209596/7b3113c8-8a65-4878-b819-804d89aac007)

**Comment by zendorx** [comment]
> > Also it affetcs only alpha. RGA values of sampler is ok
> 
> it doesn't affect alpha, If I turn off extrude borders it's the same ![CleanShot 2024-06-05 at 21 13 56@2x](https://private-user-images.githubusercontent.com/2209596/336977312-7b3113c8-8a65-4878-b819-804d89aac007.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2MTYzMjksIm5iZiI6MTcxNzYxNjAyOSwicGF0aCI6Ii8yMjA5NTk2LzMzNjk3NzMxMi03YjMxMTNjOC04YTY1LTQ4NzgtYjgxOS04MDRkODlhYWMwMDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDVUMTkzMzQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2U3MDYyN2JiNDNhYTZhNzM3MzZjYTUwNWI4ZDMwYWE0ZGYzZmQ5MTg2NjdjMmU4ZWE2NTRiMWNlNmY1ZDAzMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.blmV4p1ijL2RWchk0ffE-QA2m-YRT6l8uNQypWFrLho)

Yea, this behaviour I described in the first message. The problem appears when extrude borders set for one of the atlases. It is some kind of unexpected behavior

**Comment by AGulev** [comment]
> Yea, this behaviour I described in the first message. The problem appears when extrude borders set for one of the atlases. It is some kind of unexpected behavior

No, it's not. On my screenshot, I have no extrude borders in both atlases. 
Please carefully check your fragment shader. And read the issue I posted above about UV coordinates: https://github.com/defold/defold/issues/7045 

There is no extrude border related issue in your example.
No extrude border:
![CleanShot 2024-06-05 at 21 53 35@2x](https://github.com/defold/defold/assets/2209596/45ef32a7-502e-4d9c-bce8-1622f1cfb6c8)

with extrude border:
![CleanShot 2024-06-05 at 21 54 13@2x](https://github.com/defold/defold/assets/2209596/8932537f-dd18-49ce-985a-50ccba7b393c)


alpha is fine. The effect you see is because atlas size != image size, and UV coordinates aren't relative (see https://github.com/defold/defold/issues/7045 )

I hope it's clear now. I'm closing this issue.

**Comment by zendorx** [comment]
So, it means that second texture should be only exact size as the main texture? Is it expected behaviour?

**Comment by AGulev** [comment]
No. You can pass UV into your shader if you want, just read task I suggested you to read
