### ISSUE TITLE
Add more info if can't compile shader

### ISSUE THREAD

**Issue by d954mas** [defold/defold#9041]
**Is your feature request related to a problem? Please describe (REQUIRED):**
In my new game I see errors in poki dashboard. This is my top error, about 5% of users affected.

DEFOLD:ERROR:GRAPHICS: Unable to compile fragment shader.\n

I have no idea  what shader, or line is problem shader. It is impossible for me to fix its

**Describe the solution you'd like (REQUIRED):**
Can you please add more info?
1)Shader name. "model.fp"
2)Error log
You post error log only for debug build?

https://github.com/defold/defold/blob/f9328b98a5b6870d8ff2c8bf952c1d59118a7257/engine/graphics/src/opengl/graphics_opengl.cpp#L1734
  

**Describe alternatives you've considered (REQUIRED):**

**Additional context (OPTIONAL):**

**Comment by AGulev** [comment]
related https://github.com/defold/defold/issues/8233
