### ISSUE TITLE
Input from keyboard not working

### ISSUE THREAD

**Issue by ekharkunov** [defold/defold#9068]
_Is it a private platform, and a platform specific issue? (i.e. would it break your NDA?)<br>
No

**Describe the bug (REQUIRED)**
If use arrows on keyboard to generate input action - action not arrived.

**To Reproduce (REQUIRED)**
1. Create project from RPG sample.
2. Build and run.
3. Use arrows to control character.
4. Nothing happened.

**Expected behavior (REQUIRED)**
Input actions arrived to .script and hero responds to it.

**Defold version (REQUIRED):**
  - 1.9.0 Beta

**Platforms (REQUIRED):**
 - Platforms: macOS, HTML5, other not tested
 - OS: 14.4.1 (23E224)

**Minimal repro case project (OPTIONAL):**
Use RPG sample https://github.com/defold/sample-rpgmap

**Additional context (OPTIONAL):**
Pay attention that it also not working in HTML5 build.

**Comment by JCash** [comment]
Fixed last week by Jhonny
