### ISSUE TITLE
Physics generates only for part of the tilemap.

### ISSUE THREAD

**Issue by AGulev** [defold/defold#9089]
> You explained many things at the same time, which makes it extremely hard to track.
> 
> It would be easier to understand and much easier and faster to fix if you made one bug report per problem with a small repro project per problem.
> 
> Because now I lost the track and don't really know what we are talking about here.

Sorry. I am good at confusion as my mind moves in 6 different ways. Please forgive me.
Allow me to explain the main issue that might affect others more without a fix.

Here is an image of one of my maps. The red line indicates pretty much where the collision shapes for my tiles stop producing collider shapes and there is no collision data. Note, this map uses 64x64px tiles and is 360x224 in size.
![image](https://github.com/defold/defold/assets/75145117/d404cd8e-19a7-4095-a03c-9bb8ec13a9b5)

Here are my level settings
![image](https://github.com/defold/defold/assets/75145117/7f3a9b5c-18ab-4804-80f5-641c0c2f1758)

Here is are two videos showing what happens when the game start IF my level GO's collider object does not have a group set to `ground`. One of the videos you will see when the player stops, but you will also see enemies falling from above.
https://github.com/defold/defold/assets/75145117/b0b7f100-fbe5-4cd5-86ab-8a6963448398
https://github.com/defold/defold/assets/75145117/8883ca9e-bd16-46b3-be35-c3598869a2b8

If the group is set to `ground` on the level collider, then all tiles in the tilesource set to `ground` will collide on the complete map. If group is NOT set to `ground` on the level collider, then only tiles below the red line will have colliders and will collide if the tilesource has a group set to `ground`.

The issue here is some tiles that are NOT set to ground or basically set to nothing also collide. :(
Thus you end up with this image of tree leaves that are not collider tiles.
![image](https://github.com/defold/defold/assets/75145117/d6e180be-a25f-4c96-a4fc-9f3e64c71348)

I believe the tilemap colliders are overkill for large maps. You gave us an alternative with sizeable physics at run time which I have decided to utilize since I already support it. Thank you for that. Again, I really am looking forward to tilemap culling to help with my large maps. :)

_Originally posted by @jcbk101 in https://github.com/defold/defold/issues/9076#issuecomment-2171777775_

**Comment by AGulev** [comment]
```
INFO:DLIB: Log server started on port 52430
INFO:ENGINE: Target listening with name: DESKTOP-GJEEMLE - fe80::c27e:1f89:9563:6999 - Windows
INFO:ENGINE: Engine service started on port 52431
INFO:GRAPHICS: Installed graphics device 'ADAPTER_FAMILY_OPENGL'
INFO:ENGINE: Defold Engine 1.8.0 (ef07c03)
INFO:DLIB: Initialized Remotery (ws://127.0.0.1:17815/rmt)
INFO:ENGINE: Loading data from: build/default
INFO:DEFSAVEEXTENSION: Registered defsave_ext Extension

INFO:ENGINE: Initialised sound device 'default'
DEBUG:SCRIPT: DefSave: The file 'skrilla' was successfully loaded
DEBUG:SCRIPT: DefSave: Warning when attempting to get a key 'shuriken.max' of file 'skrilla' the key was nil
DEBUG:SCRIPT: DefSave: Warning when attempting to get a key 'coin.max' of file 'skrilla' the key was nil
DEBUG:SCRIPT: DefSave: Warning when attempting to get a key 'time.max' of file 'skrilla' the key was nil
DEBUG:SCRIPT: DefSave: Warning when attempting to get a key 'score.max' of file 'skrilla' the key was nil
DEBUG:SCRIPT: DefSave: Warning when attempting to get a key 'heart.max' of file 'skrilla' the key was nil
DEBUG:SCRIPT: DefSave: Warning when attempting to get a key 'hard_mode' of file 'skrilla' the key was nil
INFO:DLIB: SSDP: Started on address 192.168.1.66
ERROR:GAMESYS: The collection /game/gui/intro/intro.collectionc could not be disabled since it is not enabled. Message 'disable' sent from main:/main_engine#main_handler to main:/main_engine#intro.
```

**Comment by AGulev** [comment]
I tried to reproduce it, but I can't

It would be nice if you @ jcbk101 can create a new empty project and reproduce the issue there and then share it with me - so I can investigate it

**Comment by AGulev** [comment]
I re-read your message - you have to use group on your collision object, if you want it to interact with something

**Comment by AGulev** [comment]
you can split your tilesource into separate collision groups and use for collision only needed like in this manual https://defold.com/manuals/tilesource/#tile-source-collision-shapes but not using of collision group won't work

**Comment by jcbk101** [comment]
> you can split your tilesource into separate collision groups and use for collision only needed like in this manual https://defold.com/manuals/tilesource/#tile-source-collision-shapes but not using of collision group won't work

Yes, I understand this. I have developed that game since the beginning with the collision group on my level GO's collision object this whole time. But when my character began to stop on tree leaves that aren't part of a collision group or a group at all, then I started investigating. I went back to the tilemap info and saw that it stated that I did not need a group on my level's collider. This was seen in the defold demo / example as well. At this point is when I discovered the partial coverage of collision shapes on tilemaps.

**Comment by jcbk101** [comment]
> I tried to reproduce it, but I can't
> 
> It would be nice if you @jcbk101 can create a new empty project and reproduce the issue there and then share it with me - so I can investigate it

Find attached a empty-ish project. I added on to the pixel line platformer example.
Sorry for the delay. It took a while to get it to this point.
[TilemapTest.zip](https://github.com/user-attachments/files/15878695/TilemapTest.zip)

1) Current state shows enemies falling and half the map with colliders. But just to your left, you can jump and pass through the leaves
2) Change the level's collider group to `ground`, and no more falling thru the floors. But you also can no longer pass thru the leaves at this spot.

**Comment by AGulev** [comment]
Now I see

**Comment by AGulev** [comment]
@jcbk101 It's happening because the tilemap you fill with values is too big

When I reduce size to needed for your map :
```
  cell {
    x: 0
    y: 0
    tile: 0
    h_flip: 0
    v_flip: 0
    rotate90: 0
  }
  cell {
    x: 360
    y: 0
    tile: 0
    h_flip: 0
    v_flip: 0
    rotate90: 0
  }
  cell {
    x: 0
    y: 224
    tile: 0
    h_flip: 0
    v_flip: 0
    rotate90: 0
  }
  cell {
    x: 360
    y: 224
    tile: 0
    h_flip: 0
    v_flip: 0
    rotate90: 0
  }
  ```
  
  it works fine, so you can use it as a workaround for now, I'll try to find where this limitation comes from and check if it makes sence (it is probably is, because you have size 639 x 511 = 326 529 tiles)

**Comment by jcbk101** [comment]
> @jcbk101 It's happening because the tilemap you fill with values is too big
> 
> When I reduce size to needed for your map :
> 
> ```
>   cell {
>     x: 0
>     y: 0
>     tile: 0
>     h_flip: 0
>     v_flip: 0
>     rotate90: 0
>   }
>   cell {
>     x: 360
>     y: 0
>     tile: 0
>     h_flip: 0
>     v_flip: 0
>     rotate90: 0
>   }
>   cell {
>     x: 0
>     y: 224
>     tile: 0
>     h_flip: 0
>     v_flip: 0
>     rotate90: 0
>   }
>   cell {
>     x: 360
>     y: 224
>     tile: 0
>     h_flip: 0
>     v_flip: 0
>     rotate90: 0
>   }
> ```
> 
> i didn't test it well but it seems like if works fine, so you can use it as a workaround for now, I'll try to find where this limitation comes from and check if it makes sence (it probably is, because you have size 639 x 511 = 326 529 tiles)

Yes, I believe this is true. I recall trying this and it worked. I thought I inquired about having the ability to size the tilemap at runtime then build it. But I think I was told that defold has to have a static map. Thus why I made the static map just a bit bigger than my largest map and then I fill from there. Possible to revisit dynamic tilemap for folks who build maps at runtime? :)

Thanks for all of your hard work. It is greatly appreciated.

**Comment by AGulev** [comment]
@jcbk101 
I think I found what the issue is, I'm about to provide a link with a build for tests

**Comment by AGulev** [comment]
Could you please test this build, it's not merged yet, but if this build works for you, I'll make PR, it works in the example you provided (remember that we are testing this particular issue reported here): 
https://d.defold.com/archive/dev/1a91f0be4cef609bccfce05b4d22841a6cd5869e/dev/editor2/Defold-x86_64-win32.zip

**Comment by jcbk101** [comment]
> @jcbk101 Could you please test this build, it's not merged yet, but if this build works for you, I'll make PR, it works in the example you provided (remember that we are testing this particular issue reported here): https://d.defold.com/archive/dev/1a91f0be4cef609bccfce05b4d22841a6cd5869e/dev/editor2/Defold-x86_64-win32.zip

I am trying to test, but 1.9.0 is so slow for me. Since D/L around 8:33 a.m. local time, I have been able to run my project 3 times. Linting takes so long now that my system ask if I want to wait or close the app. It is 9:33 am and run 4 just popped up. 

The three times I have been able to run it, my character warps to lord know where when I jump on a moving platform. I parent the player to the platform with world transform = true. This used to work with no issue. I am trying to test now, but it's taking too long. I will have to try again after work.

**Comment by AGulev** [comment]
oh gosh. It sounds terrible, I need to ping @vlaaad here

**Comment by AGulev** [comment]
> I am trying to test, but 1.9.0 is so slow for me. Since D/L around 8:33 a.m. local time, I have been able to run my project 3 times. Linting takes so long now that my system ask if I want to wait or close the app. It is 9:33 am and run 4 just popped up.
> 
> The three times I have been able to run it, my character warps to lord know where when I jump on a moving platform. I parent the player to the platform with world transform = true. This used to work with no issue. I am trying to test now, but it's taking too long. I will have to try again after work.
> 
> Can't debug with this copy of the app either. I get an error pop up and a dmengine freeze.

Please open a separate ticket for that (if you haven't, I don't remember)

**Comment by vlaaad** [comment]
Hi @jcbk101! We have a known issue that for some projects build-time linting takes too much time, you might be interested in following this: #8974

We now implemented a preference to turn-off build-time Lua linter: `File` -> `Preferences` -> Uncheck the `Line Code on Build` checkbox.

**Comment by jcbk101** [comment]
> Hi @jcbk101! We have a known issue that for some projects build-time linting takes too much time, you might be interested in following this: #8974
> 
> We now implemented a preference to turn-off build-time Lua linter: `File` -> `Preferences` -> Uncheck the `Line Code on Build` checkbox.

Thank you very much. You all are great.
