### ISSUE TITLE
Unable to open VS Code as external code editor

### ISSUE THREAD

**Issue by acmbtt** [defold/defold#9104]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2024-05-28T14:20:53.141474</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>7247f038fba6f40cda23c5ea2e38e9fde69a2ea6</td></tr>
<tr><td>Defold engine sha</td><td>fd1ad4c17bfdcd890ea7176f2672c35102384419</td></tr>
<tr><td>Defold version</td><td>1.8.1</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"bdb8add0bca5456bb3da8fa78c412029"'>bdb8add0bca5456bb3da8fa78c412029</a></td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics</td></tr>
<tr><td>GPU Driver</td><td>4.3.0 - Build 20.19.15.4531</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by AGulev** [comment]
```
handler ':open' in context ':global' failed at ':run' with message 'Cannot run program "C:\Program Files\Microsoft VS Code\Code.exe" (in directory "C:\Defold_Exemplos\sample-pixel-line-platformer-main"): CreateProcess error=2, O sistema não pode encontrar o arquivo especificado'
```

**Comment by vlaaad** [comment]
Hi @acmbtt! Just checking, do you have a `Code.exe` file in the `C:\Program Files\Microsoft VS Code\` folder? 

Also, it might be possible that Windows does not allow the Defold app to access the `C:\Program Files` folder. I wonder if you can specify the vscode path as just `code` (which I assume exists on the PATH and should be available everywhere)...

**Comment by AGulev** [comment]
The requested additional information wasn't provided. We are closing the issue for now, as it cannot be fixed without further context. 

Feel free to reopen the issue when you are able to provide the requested information.
