### ISSUE TITLE
an error

### ISSUE THREAD

**Issue by acmbtt** [defold/defold#9106]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2024-05-28T14:20:53.141474</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>7247f038fba6f40cda23c5ea2e38e9fde69a2ea6</td></tr>
<tr><td>Defold engine sha</td><td>fd1ad4c17bfdcd890ea7176f2672c35102384419</td></tr>
<tr><td>Defold version</td><td>1.8.1</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"37bcba469e8d4e018169ec0d4bf5555c"'>37bcba469e8d4e018169ec0d4bf5555c</a></td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics</td></tr>
<tr><td>GPU Driver</td><td>4.3.0 - Build 20.19.15.4531</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by AGulev** [comment]
```
handler ':open' in context ':global' failed at ':run' with message 'Cannot run program "C:\Program Files\Microsoft VS Code\Code.exe" (in directory "C:\Defold_Exemplos\sample-pixel-line-platformer-main"): CreateProcess error=2, O sistema não pode encontrar o arquivo especificado'
```
