### ISSUE TITLE
New build from Editor can't close previous started build

### ISSUE THREAD

**Issue by Insality** [defold/defold#9128]
**Describe the bug (REQUIRED)**
In Defold 1.9.0 on MacOS if game build from editor is started, the new build can't close previous started build. In Defold 1.8.1 this works correctly

**To Reproduce (REQUIRED)**
1. Make Empty Project
2. Run Build
3. Switch to the Editor
4. Run Build again

**Expected behavior (REQUIRED)**
New Build will start correctly

**Defold version (REQUIRED):**
Bug on 1.9.0
Ok on 1.8.1

**Platforms (REQUIRED):**
- MacOS

**Minimal repro case project (OPTIONAL):**
Empty Project from templates is ok

**Workaround (OPTIONAL):**
Manually close started build every time

**Screenshots (OPTIONAL):**
https://github.com/defold/defold/assets/3294627/412d7936-89b8-4564-a52a-54fa426cd3e4

**Comment by selimanac** [comment]
Also, now the ESCAPE key has stopped working (Preferences -> Escape Quits Game is selected) for me. I have to close the build window every time using the window's close button. This looks like a simple bug, but it is very annoying while developing.
SHA: bbf4920e70c6b451042b6279361da3c46ddcb150
