### ISSUE TITLE
Can't set y and z properties to 0.0 on Editor

### ISSUE THREAD

**Issue by selimanac** [defold/defold#9147]
Latest **1.9.1**

Position, rotation and scale values can't set to 0.0 also scale value return 0.000001

### Steps to reproduce

- Creat new GameObject
- Set position/rotation y or z to 3
- Try to set it back to 0  (Works for X )
- Returns to 3
------
- Set scale y or z to 3
- Set again to 0 -> 0.000001
- Set again to 1 -> 0.000001 (it works if you set it > 2)

https://github.com/defold/defold/assets/1324635/ff8fe608-9501-4777-8421-5b22d383f8d3

<hr/>

<table>
<tr><td>Build time</td><td>2024-06-29T07:36:54.365170</td></tr>
<tr><td>Defold channel</td><td>alpha</td></tr>
<tr><td>Defold editor sha</td><td>605867c347e5dc4b2d8ebf6871c61018133fa69e</td></tr>
<tr><td>Defold engine sha</td><td>605867c347e5dc4b2d8ebf6871c61018133fa69e</td></tr>
<tr><td>Defold version</td><td>1.9.1</td></tr>
<tr><td>GPU</td><td>Apple M2 Pro</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 88.1</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>aarch64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>14.5</td></tr>
<table>

**Comment by selimanac** [comment]
It is broken everywhere, so it's not related to GO only. I believe this is a general editor bug with input fields. I can't set up a correct value in the GUI either.

**Comment by AGulev** [comment]
It's not clear on video what do you press

**Comment by selimanac** [comment]
Same for pressing enter and mouse click outside the field.
