### ISSUE TITLE
"Magnifying" when long tap. HTML5 iOS

### ISSUE THREAD

**Issue by serj1024** [defold/defold#9148]
(Defold 1.9.0) If in an HTML5 build on iOS, you long tap outside the container with the game, on the <body> (Scale mode - fit), the following will happen:
![image](https://github.com/defold/defold/assets/34648793/5bc5edae-9119-424b-974d-dfc1ee2a5a26)

Potential Fix:
It's likely that you can fix this bug by replacing the div with * in default CSS. However, in my case, i replaced the body with * in engine_template.html:
* {
		-webkit-tap-highlight-color: rgba(0,0,0,0);
		-webkit-touch-callout: none;
		-webkit-user-select: none;
		-khtml-user-select: none;
		-moz-user-select: none;
		-ms-user-select: none;
		user-select: none;
		
		--s: 80px; /* control the size */
		--c: #8cc3f6;

		--_l: #0000 46%,var(--c) 47% 53%,#0000 54%;
		background:
		radial-gradient(100% 100% at 100% 100%,var(--_l)) var(--s) var(--s),
		radial-gradient(100% 100% at 0    0   ,var(--_l)) var(--s) var(--s),
		radial-gradient(100% 100%,#0000 22%,var(--c) 23% 29%, #0000 30% 34%,var(--c) 35% 41%,#0000 42%)
		#98c7ff;
		background-size: calc(var(--s)*2) calc(var(--s)*2);
	}

**Comment by aglitchman** [comment]
I'm pretty sure that this CSS rule is enough to apply on `body, div`.
