### ISSUE TITLE
Simple project crashes on android.

### ISSUE THREAD

**Issue by goodiesohhi** [defold/defold#9149]
Hey just started experimenting around with defold, have just a basic screens and ui setup with monarch and druid but when apk is bundled and loaded onto my real device, it immediately crashes with this error
06-27 00:02:28.822  1652  1851 W WindowManager: Failed to deliver inset control state change to w=Window{2e8f6c1 u0 com.package.name/com.dynamo.android.DefoldActivity EXITING}

it works fine running in the editor.
a mod on discord recommended me to file a bug report with a zip file
[crashes.zip](https://github.com/user-attachments/files/16046602/crashes.zip)

Platform:
Windows 64bit (editor)
Google Pixel 6a Android14 (build)
my phone is rooted if that matters.

**Comment by britzl** [comment]
Your project crashes since it has Android Target SDK Version set to 34 (Android 14) which is incompatible with the version of extension-iap that you are using. I recommend that you upgrade to this recently released version of extension-iap: https://github.com/defold/extension-iap/releases/tag/6.2.0
