### ISSUE TITLE
Display -> Fullscreen has no effect 

### ISSUE THREAD

**Issue by selimanac** [defold/defold#9150]
I know Defold has a problematic history with the built-in `game.project -> Display -> Fullscreen` setting. 
Since GLFW is updated for MacOS, I would like to give it a try, but it has no effect when building with Vulkan or OpenGL. 
I guess this is a [known issue](https://github.com/defold/defold/issues/8100#issuecomment-1751112437), but as a friendly reminder, I want to open an issue. 

<hr/>

<table>
<tr><td>Build time</td><td>2024-06-29T07:36:54.365170</td></tr>
<tr><td>Defold channel</td><td>alpha</td></tr>
<tr><td>Defold editor sha</td><td>605867c347e5dc4b2d8ebf6871c61018133fa69e</td></tr>
<tr><td>Defold engine sha</td><td>605867c347e5dc4b2d8ebf6871c61018133fa69e</td></tr>
<tr><td>Defold version</td><td>1.9.1</td></tr>
<tr><td>GPU</td><td>Apple M2 Pro</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 88.1</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>aarch64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>14.5</td></tr>
<table>

**Comment by selimanac** [comment]
Wow, after many many years finally we got a functional full screen settings, thank you  🤘

**Comment by AGulev** [comment]
When we finish migration to glfw3 we will make it fully functional on all platforms (currently it's only mac) and with API for that.
