### ISSUE TITLE
ESCAPE key has stopped working

### ISSUE THREAD

**Issue by AGulev** [defold/defold#9160]
Also, now the ESCAPE key has stopped working (Preferences -> Escape Quits Game is selected) for me. I have to close the build window every time using the window's close button. This looks like a simple bug, but it is very annoying while developing.
SHA: bbf4920e70c6b451042b6279361da3c46ddcb150

_Originally posted by @selimanac in https://github.com/defold/defold/issues/9128#issuecomment-2205208153_

**Comment by AGulev** [comment]
@selimanac could you please provide more info about your OS etc?  (the info from help->report issue)
Because I'm testing it on my mac, and it works for me.

**Comment by selimanac** [comment]
@AGulev I just updated to 5627038e48711ee6f148b32fea72d6d9781770d5 and seems to ESC works again. 
I did close and open editor a few times and test it over and over and  I'm pretty sure it wasn't working before. :)  
I have no idea, sorry if this is only on my side. 

<hr/>

<table>
<tr><td>Build time</td><td>2024-07-03T06:10:19.654069</td></tr>
<tr><td>Defold channel</td><td>alpha</td></tr>
<tr><td>Defold editor sha</td><td>5627038e48711ee6f148b32fea72d6d9781770d5</td></tr>
<tr><td>Defold engine sha</td><td>5627038e48711ee6f148b32fea72d6d9781770d5</td></tr>
<tr><td>Defold version</td><td>1.9.1</td></tr>
<tr><td>GPU</td><td>Apple M2 Pro</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 88.1</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>aarch64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>14.5</td></tr>
<table>

**Comment by AGulev** [comment]
I'm closing it for now, but feel free to reopen it if you catch it again

**Comment by selimanac** [comment]
@AGulev thank you, sorry about that. I was quite sure, don't know what went wrong/different :(

**Comment by AGulev** [comment]
no-no, it's possible, that something is really wrong, but we need to figure out in what conditions. It's hard to do if everything works, but maybe there are some special conditions when it happens. If you catch it and pay attention what did you do different this time, I'll take a look
