### ISSUE TITLE
Number and Hash script properties do not accept single character input directly after reset

### ISSUE THREAD

**Issue by HyperAlch** [defold/defold#9182]
### Expected behaviour
Registration of ANY valid value given to a Number or Hash `Script Property`
### Actual behaviour
Failure to register any Number or Hash value given directly after a `Script Property` reset if the value given is exactly 1 character 

### Steps to reproduce
**Video of this issue**
https://streamable.com/ia9ucf

**Video of what happens when typing more than 1 character**
https://streamable.com/f7s4vz
<hr/>

<table>
<tr><td>Build time</td><td>2024-07-06T16:52:39.732983</td></tr>
<tr><td>Defold channel</td><td>alpha</td></tr>
<tr><td>Defold editor sha</td><td>a4a62def6f1cf7bb000f331c03c38820db50b8d7</td></tr>
<tr><td>Defold engine sha</td><td>a4a62def6f1cf7bb000f331c03c38820db50b8d7</td></tr>
<tr><td>Defold version</td><td>1.9.1</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GTX 1070 Ti/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 555.85</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by AGulev** [comment]
Could you pls explain what I see on video? Because I don't understand what's going on there and I can't reproduce anything strange doing so:

https://github.com/defold/defold/assets/2209596/6b754ef5-2135-4217-90d6-aa4bded9690b

Also, what is your keyboard layout?

**Comment by AGulev** [comment]
Not sure but maybe it's related to this isuse: https://github.com/defold/defold/issues/8921

**Comment by AGulev** [comment]
Now I can reproduce it! Thank you for that detailed explanation 👍

**Comment by AGulev** [comment]
Fixed in 1.9.1 Beta (built will take about an hour)
