### ISSUE TITLE
Editor code view doesn't show the cursor position and text at end-of-line

### ISSUE THREAD

**Issue by JCash** [defold/defold#9190]
I opened up the `main.script` in the Desktop Game template, and jumped to the end of the longest line, but the editor doesn't scroll the view to show the text at the cursor location.

This is on my macOS M1, with current beta editor (546f0be5995db44a7c072d53b09a747d62f6a763)

Here, the cursor is at the end of the line 3, but it is not show, nor is the text at the end of the line.
<img width="891" alt="Screenshot 2024-07-09 at 15 39 26" src="https://github.com/defold/defold/assets/1349334/8112d288-e5a0-4d2e-b7c9-b6b511fe22bb">

**Comment by AGulev** [comment]
Can't reproduce using latest editor (with the latest jdk and javafx)
