### ISSUE TITLE
Changing the size of a GUI node doesn't affect the Editor's viewport

### ISSUE THREAD

**Issue by selimanac** [defold/defold#9192]
Changing the size of a GUI node doesn't affect the editor's viewport, but it works in the build. 
As you can see in the video, I change the size of the box node from 20 to 40 and vice versa, but the editor view of the node stays the same size(always 20). The project is newly opened and didn't have any editor errors before this video. 
Also, if I close and re-open the project, the editor shows the correct size until I change it again.

I don't have a repo case yet; this is a complex project, so if needed, I can try to prepare one. 
Additionally, after recent editor/engine updates, my GUI pivots seem to have changed (I need to investigate this).

https://github.com/defold/defold/assets/1324635/25d868dc-67a2-4bc4-b650-f4832fa6e3f1

<hr/>

<table>
<tr><td>Build time</td><td>2024-07-09T11:49:37.921972</td></tr>
<tr><td>Defold channel</td><td>alpha</td></tr>
<tr><td>Defold editor sha</td><td>2a0915824143eccfea015e28c2421e3d69fbef16</td></tr>
<tr><td>Defold engine sha</td><td>2a0915824143eccfea015e28c2421e3d69fbef16</td></tr>
<tr><td>Defold version</td><td>1.9.1</td></tr>
<tr><td>GPU</td><td>Apple M2 Pro</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 88.1</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>aarch64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>14.5</td></tr>
<table>

**Comment by AGulev** [comment]
it looks like this issue: https://github.com/defold/defold/issues/8826

**Comment by selimanac** [comment]
I forgot to mention, I'm using Slice-9. It seems like another issue is also using it (not sure if this matters or is related...)

**Comment by selimanac** [comment]
Seems like lots of things broken on Editor related to GUI. 

These were looks good on Editor because I created them a few days ago.

9scale button on Editor:

![Screenshot 2024-07-10 at 16 40 16](https://github.com/defold/defold/assets/1324635/8894d95d-968e-49cd-96f3-465e83b6fc5a)

Build:

![Screenshot 2024-07-10 at 16 41 42](https://github.com/defold/defold/assets/1324635/9d68b316-c0ac-453c-afb7-b1fd3bb243b7)

Pivots on Editor (looks centered to 0,0):

![Screenshot 2024-07-10 at 16 41 55](https://github.com/defold/defold/assets/1324635/d2330951-98ca-4dfb-8fe4-ecbf1e1e5895)

Build (bottom left 0,0):



![Screenshot 2024-07-10 at 16 41 50](https://github.com/defold/defold/assets/1324635/52f50218-d136-4528-8ef3-dec7728bc1ea)

I download the [1.9.0](https://github.com/defold/defold/releases/tag/1.9.0)  and try to open same project with it but this time I can't even see the GUI elements on Editor...

**Comment by AGulev** [comment]
> I download the [1.9.0](https://github.com/defold/defold/releases/tag/1.9.0) and try to open same project with it but this time I can't even see the GUI elements on Editor...

You can't use 1.9.0 after 1.9.1. Versions aren't forward compatible. 



> Pivots on Editor (looks centered to 0,0):

Please open a separate ticket for pivots. it would be nice if you can provide a small repro case (for example by removing everything which isn't related to the bug)

**Comment by selimanac** [comment]
@AGulev  I think I found the issue. If a GUI texture (atlas) contains any sprite with Sprite Trim Mode set to anything other than "off" (4,5...), it fails to show the size and pivot correctly in the Editor. 
Since these issues seem related, I'm not going to open another issue yet.

These three box nodes are the same size and have the same pivots. The middle one has a texture from an atlas which contains a sprite with Sprite Trim Mode set to 4. Basically, sprite trim mode messes up the Editor view :)

![Screenshot 2024-07-10 at 19 02 23](https://github.com/defold/defold/assets/1324635/40f96737-c6b8-405e-b187-4d8394a346da)

Here is the repo case:
[gui-atlas-sprite-trim.zip](https://github.com/user-attachments/files/16164848/gui-atlas-sprite-trim.zip)
