### ISSUE TITLE
`Cannot use long-running editor function in immediate context` - isn't clear error message

### ISSUE THREAD

**Issue by AGulev** [defold/defold#9195]
I got an error:
```
ERROR:EXT: Auto save's "active" in /target_system/main.editor_script failed: /target_system/main.editor_script:51 Cannot use long-running editor function in immediate context
```

It's not clear from the message (or from manuals) what should I do with it. How to fix or avoid it.

Script:

[main.editor_script.zip](https://github.com/user-attachments/files/16178580/main.editor_script.zip)

**Comment by vlaaad** [comment]
Fixed in https://github.com/defold/doc/commit/8ba5b0c1ccde543c16344aecf3b46ed0a0c7b164
