### ISSUE TITLE
Hot-reloading shaders two times in a row crashes the engine

### ISSUE THREAD

**Issue by Jhonnyg** [defold/defold#9206]
**Describe the bug (REQUIRED)**
As the title says, hot-reloading any shader resource will crash the engine the second time its issued.

**To Reproduce (REQUIRED)**
1. Open (or create) any project
2. Run the game
3. Open any shader that is being used in the game
4. Make modifications and press hot-reload (cmd-r)
5. Do step 4 again - game crashes

**Expected behavior (REQUIRED)**

**Defold version (REQUIRED):**
  - Version 1.9.1

**Platforms (REQUIRED):**
 - Platforms: macOS (only tested)

**Comment by AGulev** [comment]
maybe related but I'm not sure https://github.com/defold/defold/issues/3686
