### ISSUE TITLE
Update LuaJit to the latest version

### ISSUE THREAD

**Issue by AGulev** [defold/defold#9219]
**Is your feature request related to a problem? Please describe (REQUIRED):**
LuaJit generates non-deterministic byte code https://github.com/LuaJIT/LuaJIT/issues/1008
Which maybe a reason of issues for Live Update when the same code generates different output file. 
This is critical for us because, as a result, packages containing such files will constantly have new checksums and will be re-downloaded.

**Describe the solution you'd like (REQUIRED):**
This issue has been fixed in the latest version of LuaJit, so it should be updated in the engine as well

**Describe alternatives you've considered (REQUIRED):**
The only way for now is using of vanilla Lua instead

**Additional context (OPTIONAL):**

**Comment by ekharkunov** [comment]
Also can be interested https://github.com/LuaJIT/LuaJIT/issues/1220

**Comment by AGulev** [comment]
btw https://github.com/JCash/LuaJIT

**Comment by britzl** [comment]
> btw maybe it will be helpful as well https://github.com/JCash/LuaJIT

Yes, the Defold specific changes are in that fork. I decided that it makes more sense to have a Defold fork instead:

https://github.com/Defold/LuaJIT/
