### ISSUE TITLE
Could not find gl function 'glMemoryBarrier'. error after update on 1.9.1

### ISSUE THREAD

**Issue by Sublustris** [defold/defold#9221]
**Describe the bug (REQUIRED)**

When trying to build an empty project, get the following error
**Could not find gl function 'glMemoryBarrier'** 

  on 1.8.1 everything works fine.

**To Reproduce (REQUIRED)**
1. Creare a new project from  "desktop" project template
2. Click "build"

**Defold version (REQUIRED):**
  - Version 1.9.1,   1.9.2

**Platforms (REQUIRED):**
 - Platforms: Window
 - OS:  Windows 7x64
 - Device: 
    Processor: Intel(R) Core(TM) i5-2300 CPU @ 2.80GHz (4 CPUs), ~2.8GHz
    Memory: 16384MB RAM
    Page File: 6010MB used, 26716MB available
    DirectX Version: DirectX 11
    Card name: NVIDIA GeForce 210 (OpenGL v3.3)
    Display Memory: 4050 MB
    Current Mode: 1920 x 1080 (32 bit) (60Hz)

**Screenshots (OPTIONAL):**
![изображение](https://github.com/user-attachments/assets/708dec08-8d9c-4f67-b538-556dce405852)

**Comment by Jhonnyg** [comment]
Hi there, thanks for reporting this! 
Would you mind testing out this build to see if it resolves your issue?
https://d.defold.com/archive/dev/fdd727989c68c099ccfb3a628bb18ff31bb59b17/dev/editor2/Defold-x86_64-win32.zip

**Comment by Sublustris** [comment]
> Hi there, thanks for reporting this! Would you mind testing out this build to see if it resolves your issue? https://d.defold.com/archive/dev/fdd727989c68c099ccfb3a628bb18ff31bb59b17/dev/editor2/Defold-x86_64-win32.zip

Everything works great! Thank you!

![изображение](https://github.com/user-attachments/assets/dbcd59e4-3da6-4e7b-9085-5acad83e1b5b)

**Comment by Jhonnyg** [comment]
Excellent, thank you!
