### ISSUE TITLE
Creating new scripts cause java.lang.NullPointerException

### ISSUE THREAD

**Issue by moheb2000** [defold/defold#9229]
**Describe the bug (REQUIRED)**
When creating a new script in src directory in defold after updating to new version, it creates the script successfully but gives this error:
```
java.lang.NullPointerException: Cannot read field "dropped_line_count" because "layout" is null
```

**To Reproduce (REQUIRED)**
1. Create a new script

**Expected behavior (REQUIRED)**
Don't show the error message

**Defold version (REQUIRED):**
  - Version 1.9.1

**Platforms (REQUIRED):**
 - Platforms: -
 - OS: Linux
 - Device: -

**Comment by AGulev** [comment]
the same as https://github.com/defold/defold/issues/9238

**Comment by vlaaad** [comment]
Closing as duplicate

**Comment by vlaaad** [comment]
@moheb2000 would be cool if you could provide a way to reproduce the issue. Also, what linux distro are you using?
