### ISSUE TITLE
Creating game object file does not update project directory tree

### ISSUE THREAD

**Issue by moheb2000** [defold/defold#9230]
**Describe the bug (REQUIRED)**
After updating to new version of defold, creating game object file does not update project directory tree but the game object is already created.

**To Reproduce (REQUIRED)**
1. Create a new game object file

**Expected behavior (REQUIRED)**
Update project tree after creating a new file like hello.go

**Defold version (REQUIRED):**
  - Version 1.9.1

**Platforms (REQUIRED):**
 - Platforms: -
 - OS: Linux
 - Device: -

**Screenshots (OPTIONAL):**

hello.go is created and is showing in os file explorer but doesn't show in defold:

![Screenshot from 2024-07-26 08-44-11](https://github.com/user-attachments/assets/3d286653-ad32-44a5-bb17-76748313a3ff)

**Additional context (OPTIONAL):**

**Comment by vlaaad** [comment]
I can't reproduce the issue on Linux. I tried both creating it outside of Defold and then switching to Defold, and creating it inside Defold: in both cases the file was created and shown in the Assets pane

**Comment by vlaaad** [comment]
Hi, please check the editor for update, the issue is most probably resolved. Feel free to reopen if the issue returns :)
