### ISSUE TITLE
Create a lua module in the war battles tutorial and this happened

### ISSUE THREAD

**Issue by EsdrasCaleb** [defold/defold#9238]
### Expected behaviour
Create a lua module
### Actual behaviour
Propts a error sceen and creates the module
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2024-07-22T13:12:02.990812</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>c0a3bfcc2f85877ab9f46a3d71d38b1667ef59bc</td></tr>
<tr><td>Defold engine sha</td><td>3be87d89fd5a93a63f527351fbedb84f8a875812</td></tr>
<tr><td>Defold version</td><td>1.9.1</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"99b73dce488d462294ffa1994f892b6b"'>99b73dce488d462294ffa1994f892b6b</a></td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) Xe Graphics (TGL GT2)</td></tr>
<tr><td>GPU Driver</td><td>4.6 (Compatibility Profile) Mesa 24.1.4</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>6.9.9-200.fc40.x86_64</td></tr>
<table>

**Comment by AGulev** [comment]
```
editor.code.data$last_visible_row.invokeStatic.class java.lang.NullPointerException: Cannot read field "dropped_line_count" because "layout" is null
    at editor.code.data$last_visible_row.invokeStatic(data.clj:1188)
    at editor.code.view$repaint_view_BANG_.invokeStatic(view.clj:3078)
    at editor.code.view$make_view_BANG_$fn.invoke(view.clj:3660)
    at clojure.lang.AFn.run(AFn.java:22)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
    at java.security.AccessController.doPrivileged(AccessController.java:399)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(GtkApplication.java)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(GtkApplication.java:264)
    at java.lang.Thread.run(Thread.java:833)

**Comment by vlaaad** [comment]
Weird. I can't reproduce it (on Linux), and when I look at the code the error seems impossible.
> Cannot read field "dropped_line_count" because "layout" is null

This means layout is `null` when we pass it to `data/last-visible-row` here: https://github.com/defold/defold/blob/af134c74877dfdf0f70f6d7d144b077f274704eb/editor/src/clj/editor/code/view.clj#L3078
We access it from `canvas-repaint-info`, which is an output that simply aggregates some other outputs (including `layout`), and `layout` output never returns `null`...

Also, we access `layout` output in the same function a few lines above: https://github.com/defold/defold/blob/af134c74877dfdf0f70f6d7d144b077f274704eb/editor/src/clj/editor/code/view.clj#L3049-L3051

`data/tick` would also throw NPE if layout was `null` there... Would be good to find a way to repro the issue.

**Comment by EsdrasCaleb** [comment]
thx vlaaad i wil check it for now I will close this ticket

**Comment by vlaaad** [comment]
Hey sorry we need the ticket so we don't forget about the issue. 

You can unsubscribe from notifications here if you don't want to follow it:
<img width="388" alt="Screenshot 2024-07-29 at 14 25 11" src="https://github.com/user-attachments/assets/9ec2b8c0-31eb-4bdf-80c9-0d3f35b54741">

**Comment by EsdrasCaleb** [comment]
okay I will try to reproduce it the problem is that my actual pc is not the same linux. I can try reproduce in it or do it tomorrow...

**Comment by EsdrasCaleb** [comment]
Open a blank project create a lua module (fedora linux steam defold version):

### Expected behaviour

### Actual behaviour

### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2024-07-22T13:12:02.990812</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>c0a3bfcc2f85877ab9f46a3d71d38b1667ef59bc</td></tr>
<tr><td>Defold engine sha</td><td>3be87d89fd5a93a63f527351fbedb84f8a875812</td></tr>
<tr><td>Defold version</td><td>1.9.1</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"3f045bf629514ecd991ebea81d296607"'>3f045bf629514ecd991ebea81d296607</a></td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) Xe Graphics (TGL GT2)</td></tr>
<tr><td>GPU Driver</td><td>4.6 (Compatibility Profile) Mesa 24.1.4</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>6.9.9-200.fc40.x86_64</td></tr>
<table>

**Comment by EsdrasCaleb** [comment]
[errortest.zip](https://github.com/user-attachments/files/16418177/errortest.zip)
Project used to test

**Comment by vlaaad** [comment]
@EsdrasCaleb have you tried on Ubuntu? We don't support Fedora.

**Comment by EsdrasCaleb** [comment]
okay you can close the issue

**Comment by ClubEdNZ** [comment]
I'm getting this error on Debian (11).
"java.lang.NullPointerException: Cannot read field "dropped_line_count" because "layout" is null"



### Expected behaviour
create a new script

### Actual behaviour
created a new script, but with error message.

### Steps to reproduce
as above. 

<hr/>

<table>
<tr><td>Build time</td><td>2024-07-30T08:29:00.978889</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>075b790f01b4b3d2074a7fd9dcf04b20af309eb0</td></tr>
<tr><td>Defold engine sha</td><td>691478c02875b80e76da65d2f5756394e7a906b1</td></tr>
<tr><td>Defold version</td><td>1.9.1</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"33b30691005644c6aa8a8ced3a02cdd4"'>33b30691005644c6aa8a8ced3a02cdd4</a></td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) UHD Graphics 620 (KBL GT2)</td></tr>
<tr><td>GPU Driver</td><td>4.6 (Compatibility Profile) Mesa 20.3.5</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.10.0-31-amd64</td></tr>
<table>

**Comment by vlaaad** [comment]
@ClubEdNZ what graphics shell / window manager do you use?

**Comment by ClubEdNZ** [comment]
some more info:

OS: Debian GNU/Linux 11 (bullseye) x86_64 
ThinkPad X280 
Kernel: 5.10.0-31-amd64 
DE: Cinnamon 4.8.6 
WM: Mutter (Muffin) 
Terminal: gnome-terminal 
GPU: Intel UHD Graphics 620
