### ISSUE TITLE
Crash on start (ctrl+b)

### ISSUE THREAD

**Issue by rom1ka** [defold/defold#9248]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2024-07-30T08:31:09.154106</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>075b790f01b4b3d2074a7fd9dcf04b20af309eb0</td></tr>
<tr><td>Defold engine sha</td><td>691478c02875b80e76da65d2f5756394e7a906b1</td></tr>
<tr><td>Defold version</td><td>1.9.1</td></tr>
<tr><td>GPU</td><td>NVS 4200M/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 NVIDIA 353.62</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by rom1ka** [comment]
[_crash.dmp](https://github.com/user-attachments/files/16446590/_crash.dmp)





INFO:CRASH: Successfully wrote Crashdump to file: C:\Users\User.DESKTOP-BHLF31K\AppData\Roaming\Defold/_crash
ERROR:CRASH: CALL STACK:

ERROR:CRASH:  0 0x7FF7BFD2DF70 dmCrash::GenerateCallstack D:\a\defold\defold\engine\crash\src\backtrace_win32.cpp:144
ERROR:CRASH:  1 0x7FF7BFE26B4C _seh_filter_exe minkernel\crts\ucrt\src\appcrt\misc\exception_filter.cpp:219
ERROR:CRASH:  2 0x7FF7BFE6BB34 `__scrt_common_main_seh'::`1'::filt$0 D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:304
ERROR:CRASH:  3 0x7FF7BFDA7DAC __C_specific_handler D:\a\_work\1\s\src\vctools\crt\vcruntime\src\eh\riscchandler.cpp:389
ERROR:CRASH:  4 0x7FF8FBB31FB0 __chkstk <unknown>:0
ERROR:CRASH:  5 0x7FF8FBAE1020 RtlRaiseException <unknown>:0
ERROR:CRASH:  6 0x7FF8FBB30BD0 KiUserExceptionDispatcher <unknown>:0
ERROR:CRASH:  7 0x7FF7BFC19240 dmHID::Final D:\a\defold\defold\engine\hid\src\native\hid_native.cpp:206
ERROR:CRASH:  8 0x7FF7BF96A580 dmEngine::Delete D:\a\defold\defold\engine\engine\src\engine.cpp:337
ERROR:CRASH:  9 0x7FF7BF970E70 dmEngineCreate D:\a\defold\defold\engine\engine\src\engine.cpp:2196
ERROR:CRASH: 10 0x7FF7BF971400 dmEngine::RunLoop D:\a\defold\defold\engine\engine\src\engine_loop.cpp:68
ERROR:CRASH: 11 0x7FF7BF969560 engine_main D:\a\defold\defold\engine\engine\src\engine_main.cpp:152
ERROR:CRASH: 12 0x7FF7BFD9C1B4 __scrt_common_main_seh D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
ERROR:CRASH: 13 0x7FF8FA197020 BaseThreadInitThunk <unknown>:0
ERROR:CRASH: 14 0x7FF8FBAE2630 RtlUserThreadStart <unknown>:0
ERROR:CRASH: 

INFO:CRASH: Successfully wrote Crashdump to file: C:\Users\User.DESKTOP-BHLF31K\AppData\Roaming\Defold/_crash
ERROR:CRASH: CALL STACK:

ERROR:CRASH:  0 0x7FF7BFC19240 dmHID::Final D:\a\defold\defold\engine\hid\src\native\hid_native.cpp:206
ERROR:CRASH:  1 0x7FF7BF96A580 dmEngine::Delete D:\a\defold\defold\engine\engine\src\engine.cpp:337
ERROR:CRASH:  2 0x7FF7BF970E70 dmEngineCreate D:\a\defold\defold\engine\engine\src\engine.cpp:2196
ERROR:CRASH:  3 0x7FF7BF971400 dmEngine::RunLoop D:\a\defold\defold\engine\engine\src\engine_loop.cpp:68
ERROR:CRASH:  4 0x7FF7BF969560 engine_main D:\a\defold\defold\engine\engine\src\engine_main.cpp:152
ERROR:CRASH:  5 0x7FF7BFD9C1B4 __scrt_common_main_seh D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
ERROR:CRASH:  6 0x7FF8FA197020 BaseThreadInitThunk <unknown>:0
ERROR:CRASH:  7 0x7FF8FBAE2630 RtlUserThreadStart <unknown>:0
ERROR:CRASH: 

INFO:CRASH: Successfully wrote MiniDump to file: C:\Users\User.DESKTOP-BHLF31K\AppData\Roaming\Defold/_crash.dmp

**Comment by rom1ka** [comment]
INFO:DLIB: Log server started on port 52078
INFO:ENGINE: Target listening with name: DESKTOP-BHLF31K - fe80::6186:65a3:9c3a:8963 - Windows
INFO:ENGINE: Engine service started on port 52079
INFO:GRAPHICS: Installed graphics device 'ADAPTER_FAMILY_OPENGL'
INFO:ENGINE: Defold Engine 1.9.1 (691478c)
INFO:DLIB: Initialized Remotery (ws://127.0.0.1:17815/rmt)
Unable to create OpenGL context
Unable to re-create GLFW window
FATAL:ENGINE: Could not open window (-1).
INFO:CRASH: Successfully wrote Crashdump to file: C:\Users\User.DESKTOP-BHLF31K\AppData\Roaming\Defold/_crash
ERROR:CRASH: CALL STACK:

ERROR:CRASH:  0 0x7FF7D8FFDF70 dmCrash::GenerateCallstack D:\a\defold\defold\engine\crash\src\backtrace_win32.cpp:144
ERROR:CRASH:  1 0x7FF7D90F6B4C _seh_filter_exe minkernel\crts\ucrt\src\appcrt\misc\exception_filter.cpp:219
ERROR:CRASH:  2 0x7FF7D913BB34 `__scrt_common_main_seh'::`1'::filt$0 D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:304
ERROR:CRASH:  3 0x7FF7D9077DAC __C_specific_handler D:\a\_work\1\s\src\vctools\crt\vcruntime\src\eh\riscchandler.cpp:389
ERROR:CRASH:  4 0x7FFED0AD1FB0 __chkstk <unknown>:0
ERROR:CRASH:  5 0x7FFED0A81020 RtlRaiseException <unknown>:0
ERROR:CRASH:  6 0x7FFED0AD0BD0 KiUserExceptionDispatcher <unknown>:0
ERROR:CRASH:  7 0x7FF7D8EE9240 dmHID::Final D:\a\defold\defold\engine\hid\src\native\hid_native.cpp:206
ERROR:CRASH:  8 0x7FF7D8C3A580 dmEngine::Delete D:\a\defold\defold\engine\engine\src\engine.cpp:337
ERROR:CRASH:  9 0x7FF7D8C40E70 dmEngineCreate D:\a\defold\defold\engine\engine\src\engine.cpp:2196
ERROR:CRASH: 10 0x7FF7D8C41400 dmEngine::RunLoop D:\a\defold\defold\engine\engine\src\engine_loop.cpp:68
ERROR:CRASH: 11 0x7FF7D8C39560 engine_main D:\a\defold\defold\engine\engine\src\engine_main.cpp:152
ERROR:CRASH: 12 0x7FF7D906C1B4 __scrt_common_main_seh D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
ERROR:CRASH: 13 0x7FFED0097020 BaseThreadInitThunk <unknown>:0
ERROR:CRASH: 14 0x7FFED0A82630 RtlUserThreadStart <unknown>:0
ERROR:CRASH: 

INFO:CRASH: Successfully wrote Crashdump to file: C:\Users\User.DESKTOP-BHLF31K\AppData\Roaming\Defold/_crash
ERROR:CRASH: CALL STACK:

ERROR:CRASH:  0 0x7FF7D8EE9240 dmHID::Final D:\a\defold\defold\engine\hid\src\native\hid_native.cpp:206
ERROR:CRASH:  1 0x7FF7D8C3A580 dmEngine::Delete D:\a\defold\defold\engine\engine\src\engine.cpp:337
ERROR:CRASH:  2 0x7FF7D8C40E70 dmEngineCreate D:\a\defold\defold\engine\engine\src\engine.cpp:2196
ERROR:CRASH:  3 0x7FF7D8C41400 dmEngine::RunLoop D:\a\defold\defold\engine\engine\src\engine_loop.cpp:68
ERROR:CRASH:  4 0x7FF7D8C39560 engine_main D:\a\defold\defold\engine\engine\src\engine_main.cpp:152
ERROR:CRASH:  5 0x7FF7D906C1B4 __scrt_common_main_seh D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
ERROR:CRASH:  6 0x7FFED0097020 BaseThreadInitThunk <unknown>:0
ERROR:CRASH:  7 0x7FFED0A82630 RtlUserThreadStart <unknown>:0
ERROR:CRASH: 

INFO:CRASH: Successfully wrote MiniDump to file: C:\Users\User.DESKTOP-BHLF31K\AppData\Roaming\Defold/_crash.dmp

**Comment by AGulev** [comment]
>Unable to create OpenGL context

It would be nice to know more about your GPU, could you please turn this option on and then share your log
![telegram-cloud-photo-size-2-5287484601624814042-y](https://github.com/user-attachments/assets/7d877605-5e5d-4663-90c8-3ccc04faa024)


Also, could you test this build? https://d.defold.com/archive/dev/fdd727989c68c099ccfb3a628bb18ff31bb59b17/dev/editor2/Defold-x86_64-win32.zip

**Comment by AGulev** [comment]
Feel free to reopen ticket if you get it again and will be able to provide requested additional info
