### ISSUE TITLE
Backup Defold-Projects

### ISSUE THREAD

**Issue by Dolbaeb777K** [defold/defold#9255]
**Is your feature request related to a problem? Please describe (REQUIRED):**
Once when I saved the my project and start (F5), It gave an error. Then I found that `*.gui`file just disappeared, This is not the only problem that has happened to the project... I decided not to save the project, because it's easier in my case.
Now I developing my game with created new project, I put saved scripts, fonts and images to this new project.

**Describe the solution you'd like (REQUIRED):**
Just backup
Backup every launch or exit out of project, or every time, etc.

**Describe alternatives you've considered (REQUIRED):**
I considered copy/past my project every time, but It's not very convenient...

**Comment by britzl** [comment]
Which OS are you using? If you have unsaved files when you close Defold it will ask if you wish to save.



> Once when I saved the my project and start (F5), It gave an error. Then I found that `*.gui`file just disappeared, This is not the only problem that has happened to the project... I decided not to save the project, because it's easier in my case.

Can you give clear steps to reproduce this problem please?

**Comment by Dolbaeb777K** [comment]
> Can you give clear steps to reproduce this problem please?

I can say only that my project was on NTFS disk.
I didn't do anything on purpose or beyond Defold.

**Comment by britzl** [comment]
Ok, so this feature request was created due to the following two issues?

* https://github.com/defold/defold/issues/9250
* https://github.com/defold/defold/issues/9251

> NTFS
> Linux Opensuse and Linux Mint

I'm not sure if it matters, but using NTFS on Linux is not really standard is it?

We have many Linux users and they are usually able to use Defold without the kind of problems you describe.

**Comment by Dolbaeb777K** [comment]
> I'm not sure if it matters, but using NTFS on Linux is not really standard is it?

Yes it is. _But amazingly Arch linux can be install on NTFS disk..._ 
_I never used Arch because my linux level hasn't reached that yet_

> We have many Linux users and they are usually able to use Defold without the kind of problems you describe.

They're lucky or just works without NTFS disks

**Comment by Dolbaeb777K** [comment]
Now when I works on Linux I will save my project only on Linux file systems

**Comment by britzl** [comment]
> Now when I works on Linux I will save my project only on Linux file systems

Yes, please try this and reopen this ticket if you still have problems.
