### ISSUE TITLE
Editor. Can't click on last line in console. Scroll bar is take input

### ISSUE THREAD

**Issue by d954mas** [defold/defold#9257]
### Expected behaviour
Scroll bar is lower than all text in console
### Actual behaviour
Scroll bar blocked me from click on value in console
### Steps to reproduce
1)print long text in console. 
2)You will see bottom scroll bar.
3)Try to click on last line
![2024-08-02_15-49-13](https://github.com/user-attachments/assets/880e9cb8-7a2a-4392-a13c-05dc4d52eff8)

<table>
<tr><td>Build time</td><td>2024-07-30T08:31:09.154106</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>075b790f01b4b3d2074a7fd9dcf04b20af309eb0</td></tr>
<tr><td>Defold engine sha</td><td>691478c02875b80e76da65d2f5756394e7a906b1</td></tr>
<tr><td>Defold version</td><td>1.9.1</td></tr>
<tr><td>GPU</td><td>Intel(R) RaptorLake-S Mobile Graphics Controller</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 - Build 31.0.101.5186</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 11</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by AGulev** [comment]
related https://github.com/defold/defold/issues/5219

**Comment by AGulev** [comment]
Fixed https://github.com/defold/defold/pull/9559
