### ISSUE TITLE
Unable to type accents on Ubuntu.

### ISSUE THREAD

**Issue by padreputativo** [defold/defold#9259]
**Describe the bug (REQUIRED)**
Apparently, there is a known issue with JavaFX that prevents using accents (and probably many other non-ASCII characters) on Ubuntu Linux. This happens both in the code editor and when typing text in the text node of the GUI.

**To Reproduce (REQUIRED)**
Trying to type accents in any text box or the code editor.

**Expected behavior (REQUIRED)**
Special characters should be typed.

**Defold version (REQUIRED):**
  - Version 1.9.1
 
**Platforms (REQUIRED):**
 - Platforms: Linux
 - OS: Ubuntu
 - Device: Desktop

**Workaround (OPTIONAL):**
You can work around the issue by typing elsewhere, copying the text, and pasting it into the editor. It will work without any problems.

**Screenshots (OPTIONAL):**
![Screenshot from 2024-08-03 22-27-50](https://github.com/user-attachments/assets/cf305b51-bd3b-4352-a069-c89110cd56dd)

**Comment by JustAPotota** [comment]
Same issue on Fedora Silverblue 40 using the [compose key](https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9/html/customizing_the_gnome_desktop_environment/special-characters-in-gnome_customizing-the-gnome-desktop-environment) to type accented characters. This bug doesn't happen when running the Windows version of the editor on the same system via Wine/Proton.

**Comment by padreputativo** [comment]
The issue is resolved in the alpha version.
