### ISSUE TITLE
Update non-intended Editor Assets panel scroll behaviour

### ISSUE THREAD

**Issue by Insality** [defold/defold#9282]
**Is your feature request related to a problem? Please describe (REQUIRED):**
I'm always frustrated when asset list view always scrolled to non-intended file in a some actions, interrupting my work.

For example:
- Rename assets will scroll back to the currently open file, not a file which was renamed
- Delete assets will scroll back to the currently open file, not a folder, where file was removed
- Copy assets also scrolls the view, but the folder where action is was, currently in visible

**Describe the solution you'd like (REQUIRED):**
Don't scroll elements, if a elements/folder where action is was currently visible

**Describe alternatives you've considered (REQUIRED):**
Open a file which will be modified, but it's also will scroll the view even it's not required

**Additional context (OPTIONAL):**

https://github.com/user-attachments/assets/452c81bc-b559-41d3-b496-42cc674d9a17

Most annoying usecase when I copy the window template, which contains three files: collection gui and gui_script and renaming all of these files kind of hell if I forgot to open one of this files

**Comment by AGulev** [comment]
Please provide more info about your OS, because I can't reproduce it in my case 

https://github.com/user-attachments/assets/6dbdf5fa-c9ce-4d08-a8eb-5708e97d96e4

**Comment by britzl** [comment]
@Insality do you have the "Track Active Tab in asset browser" prefernce on or off?

**Comment by Insality** [comment]
@britzl yes! it is! oh it solves a bunch of problems
