### ISSUE TITLE
Animation preview in atlas not working anymore

### ISSUE THREAD

**Issue by 8bitskull** [defold/defold#9304]
When you select an animation in an atlas Outline and press space, the animation normally previews in the main pane. This does not happen anymore.

<hr/>

<table>
<tr><td>Build time</td><td>2024-08-12T13:14:23.195847</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>7e106914636fe4f22c967d7e297f4e24a26e0198</td></tr>
<tr><td>Defold engine sha</td><td>691478c02875b80e76da65d2f5756394e7a906b1</td></tr>
<tr><td>Defold version</td><td>1.9.1</td></tr>
<table>

**Comment by koalachef** [comment]
I was starting to think I couldn't follow the instructions lol
