### ISSUE TITLE
HTML5 crashes on every browser after updating

### ISSUE THREAD

**Issue by 0xbeefbeef** [defold/defold#9308]
Building and running on linux and android works fine, but when it comes to html5, i get the following errors (in the development console of my google chrome or firefox browser):

> Custom script for back button handling is loaded.
> dmloader.js:722 Running...
> dmloader.js:722 
> dmloader.js:719 INFO:DLIB: Log server started on port 0
> 
> dmloader.js:719 INFO:GRAPHICS: Installed graphics device 'ADAPTER_FAMILY_OPENGL'
> 
> dmloader.js:719 INFO:ENGINE: Defold Engine 1.9.1 (691478c)
> 
> dmloader.js:719 INFO:ENGINE: Loading data from: archive:game.dmanifest
> 
> dmloader.js:719 Registered pb Extension
> dmloader.js:719 INFO:WEBSOCKET: Registered websocket extension
> 
> dmloader.js:719 INFO:SPINEC: Registered spine extension
> 
> 
> dmloader.js:719 INFO:GpgsExt: Registered extension Gpgs (null)
> 
> dmloader.js:719 INFO:DEFSAVEEXTENSION: Registered defsave_ext Extension
> 
> 
> dmloader.js:719 INFO:CRASH: Successfully wrote Crashdump to file: /data/.Defold/_crash
> 
> dmloader.js:720 ERROR:CRASH: CALL STACK:
> ["TypeError: Cannot read properties of undefined (reading 'apply')","runEmAsmFunction@<anonymous>:5002:27","_emscripten_asm_const_int@<anonymous>:5005:10","@wasm://wasm/010fc142:wasm-function[7823]:0x2fab5c","@wasm://wasm/010fc142:wasm-function[5689]:0x21d048","@wasm://wasm/010fc142:wasm-function[1944]:0x8ebf8","@wasm://wasm/010fc142:wasm-function[6776]:0x28c5d8","@wasm://wasm/010fc142:wasm-function[5316]:0x1ffbb8","Module._main@<anonymous>:10217:55","callMain@<anonymous>:10422:15","_callMain@http://localhost:39459/html5/dmloader.js:977:20"]
> CALL STACK END
> 
> printErr @ dmloader.js:720
> dmloader.js:722 Exception thrown, see JavaScript console
> VM35:30 Uncaught TypeError: Cannot read properties of undefined (reading 'apply')
>     at runEmAsmFunction (<anonymous>:5002:27)
>     at _emscripten_asm_const_int (<anonymous>:5005:10)
>     at 010fc142:0x2fab5c
>     at 010fc142:0x21d048
>     at 010fc142:0x8ebf8
>     at 010fc142:0x28c5d8
>     at 010fc142:0x1ffbb8
>     at Module._main (<anonymous>:10217:55)
>     at Object.callMain (<anonymous>:10422:15)
>     at Object._callMain (dmloader.js:977:20)
> index.html:1 Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
> index.html:1 Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
> dmloader.js:719 INFO:CRASH: Successfully wrote Crashdump to file: /data/.Defold/_crash

It worked for me when I was running an older version of defold (1.7.1).

What I have changed was:

1. Update defold to 1.9.1
2. Updated dependencies:
  a. Spine (to 3.5.0)
  b. Websocket (to master or 4.0.0 - was 3.0.0 before)

Defold version (REQUIRED):
  - Version 1.9.1

Platforms (REQUIRED):
 - Platforms: HTML5
 - OS: Ubuntu linux

I have no idea what causes this error. I had compile errors when I used websocket 3.0.0 on the 1.9.1 Defold version, so I upgraded to 4.0.0. Then it compiled smoothely, but raised the errors. Any ideas how to dig deeper into this? 

![Screenshot from 2024-08-16 11-04-34](https://github.com/user-attachments/assets/5fd52ef3-81fe-4522-807c-6860538f4439)

**Comment by britzl** [comment]
Can you please provide a zip with a project where this issue happens?

**Comment by 0xbeefbeef** [comment]
Bjoern, thanks for your reply. In the meanwhile, I could narrow the problem down to the situation where FMOD is added as a project dependency. Seems to be exactly this issue:

[Defold project doesnt load when building for HTML5 when using fmod ](https://github.com/dapetcu21/defold-fmod/issues/32)

However, this seems an open issue (since June 24).

**Comment by 0xbeefbeef** [comment]
@britzl:
Since this issue isn't fixed for half a year now, maybe it would be a good idea to mark the FMOD asset as incompatible (with HTML5 builds) with recent Defold versions to avoid having users run into these problems? It would be great having this very useful extension working again. I would like to help, but honestly, I don't really know where to start with that.

**Comment by britzl** [comment]
> It would be great having this very useful extension working again. I would like to help, but honestly, I don't really know where to start with that.

We are looking into this actively right now. I can't promise anything in terms of dates as we are almost fully booked with other planned work, but we want a working FMOD integration again.
