### ISSUE TITLE
Disabling render.clear does not work in the HTML5 build

### ISSUE THREAD

**Issue by Al-V-U** [defold/defold#9313]
I want to make it so that the previous frame is not erased, and the new one is drawn on top. I commented out 
--render.set_depth_mask(true)
--render.set_stencil_mask(0xff)
--render.clear(state.clear_buffers)
in my own render_script - and it works when I run ctrl+b, but when I build the HTML5 version, it doesn’t work.
### Expected behaviour
<img width="960" alt="Снимок экрана 2024-08-17 в 16 40 40" src="https://github.com/user-attachments/assets/b0f191e8-09ab-434a-bf9d-00c9709c8356">
### Actual behaviour
<img width="854" alt="Снимок экрана 2024-08-17 в 16 44 40" src="https://github.com/user-attachments/assets/424e469b-f4cb-43bf-98d4-3c1008e978a5">
### Steps to reproduce
open test project in defold
[render_clear_bug.zip](https://github.com/user-attachments/files/16645115/render_clear_bug.zip)

build command+b - the frames overlap one another - it's ok!
build HTML5 - the frame is erased with black
<hr/>

<table>
<tr><td>Build time</td><td>2024-08-12T13:18:00.851544</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>7e106914636fe4f22c967d7e297f4e24a26e0198</td></tr>
<tr><td>Defold engine sha</td><td>691478c02875b80e76da65d2f5756394e7a906b1</td></tr>
<tr><td>Defold version</td><td>1.9.1</td></tr>
<tr><td>GPU</td><td>Apple M1</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 88.1</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>aarch64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>14.5</td></tr>
<table>

**Comment by aglitchman** [comment]
Isn't render target suitable and designed for this? Because with your approach you can't add any post effects and without render target it's a way to nowhere. IMHO

PS In WebGL the Defold engine does not enable `preserveDrawingBuffer` for performance, so the buffer is always cleared.
