### ISSUE TITLE
Reduce the possibility of error when naming things in the editor

### ISSUE THREAD

**Issue by f2l2pe** [defold/defold#9321]
**Is your feature request related to a problem? Please describe (REQUIRED):**
I was implementing a collision feature using tilemaps when I accidentally set the name ` walls`. It took me hours to fix it, and I couldn't fix it until someone from Discord mentioned that I had a space in the beginning.

**Describe the solution you'd like (REQUIRED):**
The BEST option would be defining project-wide constants that can be used in text fields, but I don't know how much work this would require.
The most feasible and fast solution would be to sanitize editor text input fields, such as by removing dangling spaces and other such elements.
With this, I mean stuff like ` walls` or `walls ` and not ALL spaces. `big walls` are ok

**Describe alternatives you've considered (REQUIRED):**
Changing the text box font to a monospace font maybe would also help visualizing those kinds of mistakes

**Additional context (OPTIONAL):**
![image](https://github.com/user-attachments/assets/ff28bf83-9b15-4a2d-a92a-1e1b5dab1299)
![image](https://github.com/user-attachments/assets/de11aa8b-0290-4f36-91cb-871e9fbeb3a6)

**Comment by britzl** [comment]
This should either be highlighted as a warning (yellow) or perhaps even an error (red).
