### ISSUE TITLE
Displacement of a Game Object with a model shifted along the z coordinate when scaling.

### ISSUE THREAD

**Issue by seel1ch** [defold/defold#9328]
**Describe the bug**
If you set the scale of the Game Object in which the model is located with an offset along the z coordinate, in runtime the offset is not correct.

**To Reproduce**
1. Create a project from the Basic 3D Template.
2. Create a Game Object and add a model component.
3. Move the model inside the Game Object along the z coordinate.
4. Add a Game Object to the scene and scale it in the editor.
5. Build the project. At runtime the position will be different.

**Expected behavior**
The position should not be shifted.

**Defold version:**
  - Version 1.9.0
  - Version 1.9.2

**Platforms:**
 - Platforms: [Windows, HTML5]
 - OS: [Windows 11]

**Screenshots:**
In Editor
![In Editor](https://github.com/user-attachments/assets/2da5815c-b4c3-43b3-b11d-27d3f37f2132)

In Runtime
![In Runtime](https://github.com/user-attachments/assets/a707d630-6ffa-493a-8fb3-28285f5df1ea)

Game Object
![GameObject](https://github.com/user-attachments/assets/5e9c9dc4-7121-454b-b2fa-e190d86d5378)

**Additional context (OPTIONAL):**
If the model is offset along the x or y coordinate, then this problem does not arise.
If you try to animate the scale property, or set it via go.set_scale, the problem will be the same

![X Offset](https://github.com/user-attachments/assets/0db8d481-29c8-4b9f-8367-79851d8ab889)

**Comment by AGulev** [comment]
I know it will sound strange, but  try to open your collection as text in a text editor and modify value `scale_along_z` to make it 
>scale_along_z: 1

**Comment by seel1ch** [comment]
Yep, it worked. In general, when working with 3D you should always modify scale_along_z as I understand it. Thanks

**Comment by britzl** [comment]
Duplicate. Closing.
