### ISSUE TITLE
Enrich the go.animate function or create a go.fanimate one

### ISSUE THREAD

**Issue by leclercf13** [defold/defold#9329]
_Is it a private platform specific feature? (i.e. would it break your NDA?)<br>

No it's not a private feature!

**Is your feature request related to a problem? Please describe (REQUIRED):**

Not a problem per say but could help with performance as I understand it in Defold. 
In short, what I suggest is to add to the go.animate function to avoid having to use the update method in scripts for some animations and use go.animate instead.

For example, suppose you would like to animate the position of an object. What you would like is that its motion is that of a circle. You would like the object to do 3 complete cycles using some radius. Say its initial position is 0. It should end at 0 too. There are no ways to do this with go.animate I think. Go.animate is the most efficient way to animate in Defold as I understand it. 

**Describe the solution you'd like (REQUIRED):**

Here is go.animate signature:

go.animate(url,property,playback,to,easing,duration,[delay],[complete_function])

What I am interested in is the "to" parameter. Instead of it being a value (vector, quaternion, etc..) why not give the possibility to use a function? The function would take a value between 0 and 1 as computed by the interpolation and easing code and pass it to the "to" function, which would compute its thing; the result would then be fetched into the property as its new value. For this to work, the interpolation and easing code in the engine would have to use 1 as its internal end value. OR we add another parameter to go.animate for the function. This last solution is probably more flexible. So we would have:

go.animate(url,property,playback,to,easing,duration,[delay],[complete_function], [post_processing_function])

and then the engine would use the post_processing_function passing it the interpolated value to get the final value used to update the game object property.

In my circular movement scenario, It means I could go from 0 to 6PI and my post_processing_function would simply compute a vector [x, y, z] with the different coordinates, [cos(v), sin(v), 0] for example, assuming a radius of one and a position of zero. What's cool is that we could use closures too, say to keep the radius handy in the function. Th engine then takes the computed vector and updates the position of the object.

We thus unleash all the power (duration, delay, playback, easing methods, complete function) of go.animate into new uses cases! This would work for all properties currently supported by the game engine. 

BUT: if all of this happens in the C++ code in the engine then my suggestion doesn't work probably. I mean performance wise it might not help that much. At least it would help write more concise code.

**Describe alternatives you've considered (REQUIRED):**

We can use the update method in a script. The less we put there the better.

**Comment by britzl** [comment]
Forum post: https://forum.defold.com/t/enrich-the-go-animate-function-to-unleash-hidden-potential/77856

**Comment by britzl** [comment]
Not planned. Closing. Use a custom animation or some library such as https://github.com/Insality/defold-tweener
