### ISSUE TITLE
Add a function to get the actual size of the node gui

### ISSUE THREAD

**Issue by Fossean1** [defold/defold#9331]
**Is your feature request related to a problem? Please describe (REQUIRED):**
Sometimes it is necessary to know the actual size of a node to interact with html elements on the web or to interact with the game world.

**Describe the solution you'd like (REQUIRED):**
Add a function that implements this functionality. For example gui.get_actual_size(my_node) or gui.get_screen_size(my_node).

**Describe alternatives you've considered (REQUIRED):**
I have to calculate the size manually using formulas I found on the forum: https://forum.defold.com/t/get-real-size-of-gui-node/167/6?u=tinte.

**Comment by britzl** [comment]
This is not functionality we plan to implement. There is a workaround which we recommend you use.
