### ISSUE TITLE
Crash due to shader when upgrading to 1.9.3 beta

### ISSUE THREAD

**Issue by Morgerion** [defold/defold#9344]
I have a project that runs on all versions of the engine, but when i upgrade to version 1.9.2 when preloading a collection it crashes because the collection uses a complex shader.

Here's the repo case: 
[__TT.zip](https://github.com/user-attachments/files/16762809/__TT.zip)

My config: Windows 10, AMD Ryzen + Radeon R9 200, Defold 1.9.2

More information:

1. You need to pay attention to the gamefield collection. 
![image](https://github.com/user-attachments/assets/34e8f15d-ba0d-4053-b1b5-76add63e209f)

2. There is a fullscreen quad with a complex shader on it. 
![image](https://github.com/user-attachments/assets/581f8acf-72a4-4330-956f-bca25bffb2df)

3. If you delete this fullscreen quad, the project stops crashing.

**Comment by Morgerion** [comment]
Important details i forgot to report:
1. In the editor this shader works without problems and is displayed correctly (when viewing the mesh in the collection).
2. The project crash is not related to the shader, but to some errors in the c++ files. I associate it with the shader only because removing it removes the crash.
3. This shader works correctly on engine version 1.9.1.

**Comment by Morgerion** [comment]
On the 1.9.3 beta version, the same crash.

**Comment by Jhonnyg** [comment]
In you manifest you have selected this option:
![image](https://github.com/user-attachments/assets/09d82042-1e40-41f3-890f-ede42d059b94)

Meaning, you are removing models from the engine while you are using a model to display the content, which is what is crashing the engine 👍 

Changing the option to include models will not crash the engine
