### ISSUE TITLE
Make right click default to deleting when editing a tilemap layer

### ISSUE THREAD

**Issue by subsoap** [defold/defold#9364]
Left click and right click do the same thing, right click would be much more convenient to set tiles to 0

**Comment by matgis** [comment]
We'd like to reserve the right mouse button for a future context menu, but I believe you can already hold down Shift+Alt while drawing to erase.

Ideally we'd change the mouse cursor to reflect this when the user holds down the modifiers, but currently the keydown event doesn't get processed by the view without moving the mouse. I've created a ticket for this here: #9366.

**Comment by subsoap** [comment]
> We'd like to reserve the right mouse button for a future context menu 

What kind of context menu would you want for drawing on tilemaps right click? You're already using right click to also draw tiles, what's harm in using it now to delete and later add a context menu?

> but I believe you can already hold down Shift+Alt while drawing to erase.

Maybe add a tooltip when holding spacebar (or above a tilemap as text... this shortcut is not obvious at all) to show that the shift+alt shortcut exists in text above the palette? 

Tiled doesn't use right click to delete, instead it lets you select a rectangle of tiles to use as your brush. But it also has obvious buttons to select different tools too.

![2024-09-03 01_54_57](https://github.com/user-attachments/assets/0a104160-58e9-4e07-9227-d0c43e27717a)

https://github.com/user-attachments/assets/cd257fc5-1cd4-4207-a920-df9a5e3a0ebe

Tiled is gold standard so it should be reference. https://www.mapeditor.org/

Right click context menu is severely needed elsewhere in viewport editor stuff. But I don't know how right click context menu helps here.

**Comment by JCash** [comment]
> You're already using right click to also draw tiles, what's harm in using it now to delete and later add a context menu?

I'm not sure that drawing with the right mouse was "by design"

> What kind of context menu would you want for drawing on tilemaps right click?

Not sure, but it certainly isn't unlikely that we'll add editor script support to that context menu, so that you can more easily run tools on the tilemap.

> Maybe add a tooltip when holding spacebar (or above a tilemap as text... this shortcut is not obvious at all) to show that the shift+alt shortcut exists in text above the palette?

We totally agree that the discoverability of shortcuts is a problem, and we want to do something about it.

I agree Tiled is a good tool, and we eventually want to do what they can do (a lot of it anyways).
But we also need to acknowledge that we're a different tool, with different requirements (and thus different choices)

**Comment by britzl** [comment]
> I agree Tiled is a good tool, and we eventually want to do what they can do (a lot of it anyways).

I would like to see Defold support for .tmx and possibly also .tls files as an extension, much in the same way as we now support TexturePacker through an extension.

This would also allow us to surface additional metadata from the tmx file to Lua through the extension.
