### ISSUE TITLE
New hexDigest in atlas

### ISSUE THREAD

**Issue by tdobrodey-ms** [defold/defold#9370]
Defold generates a new hexDigest for an atlas with multiple icons during each new build. This results in different checksums when in fact no changes have been made. Atlases with just one icon don't have this issue.

1. Create atlas with more than 1 images
2. Build with bob
3. Build again without any changes
4. Look at texturesetc hexDigest in game.graph of both builds

Expected behavior: hexDigest must be the same

Defold version: 1.6.2 (0dccda8a4b9d85d0e2f9a564e2cd326615028b4e)

Platform: Android, iOS

**Information from game.graph in the first build:**
{
  "path" : "/main/generated/_split_group_specific/23188_arcade/spine/A_decal_moon_03.a.texturesetc",
  "hexDigest" : "a9fec432ffc9a720bc653816ef7c61f3fafaeddd",
  "isInMainBundle" : false,
  "children" : [ "/main/generated/_split_group_specific/23188_arcade/spine/A_decal_moon_03.texturec" ]
}, {
  "path" : "/main/generated/_split_group_specific/23188_arcade/spine/A_decal_moon_03.texturec",
  "hexDigest" : "2f837b98c0dd212bdf6c2740d53b1e3af21b0f25",
  "isInMainBundle" : false,
  "children" : [ ]
}

**Information from game.graph in the second build:**
{
  "path" : "/main/generated/_split_group_specific/23188_arcade/spine/A_decal_moon_03.a.texturesetc",
  "hexDigest" : "20e7c16b765cecf8a1dffc81d5919c65e3fdbfe9",
  "isInMainBundle" : false,
  "children" : [ "/main/generated/_split_group_specific/23188_arcade/spine/A_decal_moon_03.texturec" ]
}, {
  "path" : "/main/generated/_split_group_specific/23188_arcade/spine/A_decal_moon_03.texturec",
  "hexDigest" : "2f837b98c0dd212bdf6c2740d53b1e3af21b0f25",
  "isInMainBundle" : false,
  "children" : [ ]
}

**Comment by AGulev** [comment]
@tdobrodey-ms Could you pls provide all the atlas settings you use?
also the command line with argument you use for bob
