### ISSUE TITLE
Assertion failed: (mutex), function Lock, file mutex_posix.cpp, line 62.

### ISSUE THREAD

**Issue by selimanac** [defold/defold#9380]
I have no idea why this is started to happen and it start today. It happens only when I add a native extension and build it a few times.

Just building empty project with extension:

https://github.com/user-attachments/assets/fb6447fd-6e97-40f1-b80d-eb5d0d7300d7

![Screenshot 2024-09-04 at 12 47 18](https://github.com/user-attachments/assets/196772ea-868e-42e6-b91d-ec563dfa5350)

Crash log
[_crash.zip](https://github.com/user-attachments/files/16869655/_crash.zip)

New project just with daabbcc extension
[empty_project.zip](https://github.com/user-attachments/files/16869659/empty_project.zip)

1.9.3 -> 0bdf7176cd4d8955518784f79091d5a5c2f024f6
MacOS Arm
Build server: https://build-stage.defold.com/

**Comment by selimanac** [comment]
When I remove the profiler using appmanifest, start to work as expected. I guess this is related to profiler(Remotery I guess)

**Comment by pixelpusherninja** [comment]
Getting the same error

INFO:ENGINE: Defold Engine 1.9.3 (e4aaff1)

Platform:
MacOS M2 - Sequioa 15.0

<img width="909" alt="Screenshot 2024-09-28 at 11 41 01 PM" src="https://github.com/user-attachments/assets/2176ae3c-c248-459a-9001-7abcd80b5cbf">
