### ISSUE TITLE
Error caused if Vertex Attribute Count is too high, followed by UX failures

### ISSUE THREAD

**Issue by swajj** [defold/defold#9398]
### Expected behaviour
Entering an invalid "Count" for a Vertex Attribute should not crash the material editor/outline

### Actual behaviour
Entering "5" for a Vertex Attribute "count" will cause an error, followed by missing UX elements e.g. stuff in the Outline fails to load until Defold is restarted.

### Steps to reproduce
![image](https://github.com/user-attachments/assets/469b7eae-570d-49aa-ac1a-c996d6195446)

<hr/>

<table>
<tr><td>Build time</td><td>2024-06-25T16:26:09.046426</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>3642fa5b700b8d6e74e3f0595e75cd50eff54459</td></tr>
<tr><td>Defold engine sha</td><td>d6882f432beca85d460ec42497888157c356d058</td></tr>
<tr><td>Defold version</td><td>1.9.0</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"56940ccba26842a394f346fd2b4b6a7c"'>56940ccba26842a394f346fd2b4b6a7c</a></td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce RTX 3060/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 535.98</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 11</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by Jhonnyg** [comment]
This will be fixed by #8743
