### ISSUE TITLE
Callbacks Crash

### ISSUE THREAD

**Issue by sergeysinyavsky** [defold/defold#9407]
Sometimes I can get a crash. It looks like some callback has already been removed, and they are trying to remove it again.

I use the [**flow**](https://github.com/britzl/ludobits/blob/master/ludobits/m/flow.lua) module.
This happens when you click the button to go to another collection. If you call **collectgarbage**, there is no crash.

    collectgarbage()
    monarch.show(msgs.SCREEN, nil, {})

Also, the crash does not occur every time. If you wait 5-10 seconds, everything will be fine

Crash:

    INFO:CRASH: Successfully wrote Crashdump to file: C:\Users\Sergey\AppData\Roaming\Defold/_crash
    ERROR:CRASH: CALL STACK:
    
    ERROR:CRASH:  0 0x7FF7921E1220 dmCrash::GenerateCallstack D:\a\defold\defold\engine\crash\src\backtrace_win32.cpp:144
    ERROR:CRASH:  1 0x7FF792494004 _seh_filter_exe /tmp/job337407127158997133/minkernel/crts/ucrt/src/appcrt/misc/exception_filter.cpp:219
    ERROR:CRASH:  2 0x7FF7924E7411 `__scrt_common_main_seh'::`1'::filt$0 D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:304
    ERROR:CRASH:  3 0x7FF792452228 __C_specific_handler D:\a\_work\1\s\src\vctools\crt\vcruntime\src\eh\riscchandler.cpp:389
    ERROR:CRASH:  4 0x7FFC330B2810 __chkstk <unknown>:0
    ERROR:CRASH:  5 0x7FFC330620D0 RtlRaiseException <unknown>:0
    ERROR:CRASH:  6 0x7FFC330B1410 KiUserExceptionDispatcher <unknown>:0
    ERROR:CRASH:  7 0x7FF7921D6C60 lua_gettop <unknown>:0
    ERROR:CRASH: 
    
    INFO:CRASH: Successfully wrote Crashdump to file: C:\Users\Sergey\AppData\Roaming\Defold/_crash
    ERROR:CRASH: CALL STACK:
    
    ERROR:CRASH:  0 0x7FF7921D6C60 lua_gettop <unknown>:0
    ERROR:CRASH:  1 0x7FF792202470 dmScript::DestroyCallback D:\a\defold\defold\engine\script\src\script.cpp:1644
    ERROR:CRASH:  2 0x7FF7922DCFA0 dmScript::FreeTimer D:\a\defold\defold\engine\script\src\script_timer.cpp:176
    ERROR:CRASH:  3 0x7FF7922DC100 dmScript::UpdateTimers D:\a\defold\defold\engine\script\src\script_timer.cpp:271
    ERROR:CRASH:  4 0x7FF7922DC0A0 dmScript::TimerUpdateScriptWorld D:\a\defold\defold\engine\script\src\script_timer.cpp:466
    ERROR:CRASH:  5 0x7FF792203C70 dmScript::UpdateScriptWorld D:\a\defold\defold\engine\script\src\script.cpp:1139
    ERROR:CRASH:  6 0x7FF7921C03C0 dmGameSystem::CompGuiUpdate D:\a\defold\defold\engine\gamesys\src\gamesys\components\comp_gui.cpp:2438
    ERROR:CRASH:  7 0x7FF7922395B0 dmGameObject::Update D:\a\defold\defold\engine\gameobject\src\gameobject\gameobject.cpp:2617
    ERROR:CRASH:  8 0x7FF79234DB50 dmGameSystem::CompCollectionProxyUpdate D:\a\defold\defold\engine\gamesys\src\gamesys\components\comp_collection_proxy.cpp:381
    ERROR:CRASH:  9 0x7FF7922395B0 dmGameObject::Update D:\a\defold\defold\engine\gameobject\src\gameobject\gameobject.cpp:2617
    ERROR:CRASH: 10 0x7FF7922C5740 dmEngine::StepFrame D:\a\defold\defold\engine\engine\src\engine.cpp:1710
    ERROR:CRASH: 11 0x7FF7922C0510 dmEngineUpdate D:\a\defold\defold\engine\engine\src\engine.cpp:2245
    ERROR:CRASH: 12 0x7FF7922C61E0 dmEngine::RunLoop D:\a\defold\defold\engine\engine\src\engine_loop.cpp:83
    ERROR:CRASH: 13 0x7FF7921CE660 engine_main D:\a\defold\defold\engine\engine\src\engine_main.cpp:152
    ERROR:CRASH: 14 0x7FF792451DD4 __scrt_common_main_seh D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    ERROR:CRASH: 15 0x7FFC31437360 BaseThreadInitThunk <unknown>:0
    ERROR:CRASH: 16 0x7FFC3305CC70 RtlUserThreadStart <unknown>:0
    ERROR:CRASH: 
 
    INFO:CRASH: Successfully wrote MiniDump to file: C:\Users\Sergey\AppData\Roaming\Defold/_crash.dmp

[crash.zip](https://github.com/user-attachments/files/16943678/crash.zip)

<hr/>

<table>
<tr><td>Build time</td><td>2024-09-09T09:58:13.383911</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>7b332ee8234aa1a5a7e4a54f36c4eae5c623d3d7</td></tr>
<tr><td>Defold engine sha</td><td>3251ca82359cf238a1074e383281e3126547d50b</td></tr>
<tr><td>Defold version</td><td>1.9.2</td></tr>
<tr><td>GPU</td><td>Radeon RX 580 Series</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 Compatibility Profile Context 23.11.1.231017</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by AGulev** [comment]
maybe related https://github.com/defold/defold/issues/8046
