### ISSUE TITLE
Merge instead of override key bindings

### ISSUE THREAD

**Issue by britzl** [defold/defold#9433]
**Is your feature request related to a problem? Please describe (REQUIRED):**
The custom key bindings completely replace the default keybindings. When new default keybindings are added to the editor users with custom keybindings can't make use of the new default keybindings without first updating their custom keybindings

**Describe the solution you'd like (REQUIRED):**
The custom keybindings should not have to be a full list of keybindings but instead only the overrides-

**Comment by AGulev** [comment]
isn't it merged?

**Comment by britzl** [comment]
Yes. I wonder why this didn't close automatically?

**Comment by AGulev** [comment]
It closes only when it is merge into 'dev' (e.g. editor-dev merged into dev)
