### ISSUE TITLE
Option for `Build HTML5` to build only selected architecture

### ISSUE THREAD

**Issue by aglitchman** [defold/defold#9439]
**Is your feature request related to a problem? Please describe (REQUIRED):**
When building the release version, you can choose the HTML5 build architecture - asmjs, wasm or both. It turns out that the ‘Build HTML5’ command still builds the game for both architectures:
![image](https://github.com/user-attachments/assets/edc2866c-dfd4-423f-909b-195d2d01b3f8)

If the project has native extensions, the build takes a huge amount of time. But if you only build for 1 architecture, the build time is almost halved.

**Describe the solution you'd like (REQUIRED):**
I want there to be an option to build only one architecture in the "Build HTML5" command.

**Defold version (REQUIRED):**
  - Version: 1.9.3

**Comment by AGulev** [comment]
I think `Build HTML5` should build only wasm, what do you think @aglitchman @britzl ?

**Comment by aglitchman** [comment]
> I think `Build HTML5` should build only wasm, what do you think @aglitchman @britzl ?

I agree! Defold users run the debug build on local computer and all have a modern browser. If you want asmjs, build it manually.

**Comment by AGulev** [comment]
> Defold users run the debug build on local computer and all have a modern browser. If you want asmjs, build it manually.

yes, that what I think about as well. wasm supported in 100% modern browsers, if somebody wants to test some specific setup, it's easy enough to bundle html5 with asm

**Comment by britzl** [comment]
> I think `Build HTML5` should build only wasm, what do you think @aglitchman @britzl ?

I agree!
