### ISSUE TITLE
Custom script templates

### ISSUE THREAD

**Issue by ufgo** [defold/defold#9443]
Currently by default scripts are created with a standard template. It would not be bad if the developers could also create their own template.
For example, I have a game uses many different screens with druid and monarch and I every time I create a new script has to prescribe their dependencies, as well as functions. And also I do not need the function on_reload(self).
I think it would be better if all dependencies and functions were predefined in advance.

**Comment by AGulev** [comment]
duplicate of https://github.com/defold/defold/issues/6694
