### ISSUE TITLE
Game Analytics have stoped work in HTML5 editor build after 1.9.3

### ISSUE THREAD

**Issue by Mulderua** [defold/defold#9452]
**Describe the bug (REQUIRED)**

Game Analytics has stoped work in HTML5 editor build after 1.9.3
They include GameAnalytics.js via manifest

<html>
<body>
    <script type='text/javascript' src="GameAnalytics.js"></script>
</body>
</html>

It used to work, but now GameAnalylitics.js returns 404 on request

**To Reproduce (REQUIRED)**
1. Use clean Defold
2. Install GameAnalytics.js or I suppose any other JS lib
3. Make HTML5 build

**Expected behavior (REQUIRED)**
GameAnalytics.js downloaded and works

**Defold version (REQUIRED):**
  - 1.9.2

**Platforms (REQUIRED):**
 - Platforms: HTML5

**Workaround (OPTIONAL):**
Include GameAnalytics script directly to custom template

**Additional context (OPTIONAL):**
It works fine when I do Html5 bundle
Also, It works on 1.9.2

**Comment by AGulev** [comment]
I've just tested using this project:
[issue-9452.zip](https://github.com/user-attachments/files/17078970/issue-9452.zip)
![CleanShot 2024-09-20 at 19 57 54@2x](https://github.com/user-attachments/assets/8ae0b3a0-58e9-4f84-8e71-e62a3de210cc)

Also after "Build HTML5" if I open build folder I see that file was copied: 
![CleanShot 2024-09-20 at 19 58 34@2x](https://github.com/user-attachments/assets/ec4eeaaf-5aec-4382-b9cc-5efb476aef6d)

Could you verify if my project works for you? If so, could you provide a repro project where it doesn't work for you
Also more info about your OS etc

**Comment by Mulderua** [comment]
@AGulev you project works for me and I got why. I use the lates version latest tagged version [4.2.6] that doesn't have this fix

https://github.com/GameAnalytics/GA-SDK-DEFOLD/commit/ac9be0952962942fc319a10fcdeca1eb7c587373

Thank you for your help.
