### ISSUE TITLE
Complement contact_point_event by including the contact position

### ISSUE THREAD

**Issue by totebo** [defold/defold#9454]
**Is your feature request related to a problem? Please describe (REQUIRED):**
When using `physics.set_listener()`, the `contact_point_event` doesn't return the contact position. The `contact_point_response` message does return it, but requires a .script file to be added to each game object with a collision object attached.

I'd prefer to use `physics.set_listener()` as it can be more performant when using many game objects, as well as keeping all collision code in one place.

**Describe the solution you'd like (REQUIRED):**
The current data structure returned by `contact_point_event` looks like this:

```
{
    applied_impulse = n,
    distance = n,
    a = {},
    b = {},
}
```

It would make sense to include the contact position, too:

```
{
    position = vector3,
    applied_impulse = number,
    distance = number,
    a = {},
    b = {},
} 
```

**Describe alternatives you've considered (REQUIRED):**
Using the game object position, rather than the contact position.

**Comment by JCash** [comment]
Repro project:
https://forum.defold.com/t/contact-point-event-vs-contact-point-response/78170
