### ISSUE TITLE
Incorrect error for sprite tint property with vec3 parameter

### ISSUE THREAD

**Issue by Domarius** [defold/defold#9463]
**Describe the bug (REQUIRED)**
Providing a vec3 for sprite property "tint" displays a misleading error.

**To Reproduce (REQUIRED)**
If you provide a vec3 value for "colour_value" in this line;
```lua
go.set("#sprite", "tint", colour_value)
```
You get the error:
```
ERROR:SCRIPT: tank.script:39: '#sprite' does not have any property called 'tint'
```
This is misleading, because sprite does indeed have a property called "tint".

**Expected behavior (REQUIRED)**
The error should've been something like "tint requires a vec4"

**Defold version (REQUIRED):**
  - Version 1.9.1

**Platforms (REQUIRED):**
Probably happens on all platforms. I can produce this when building on Linux.

**Comment by Jhonnyg** [comment]
Related: https://github.com/defold/defold/issues/9241
