### ISSUE TITLE
Display Profile qualifiers not working

### ISSUE THREAD

**Issue by britzl** [defold/defold#9468]
From https://forum.defold.com/t/display-profile-qualifiers-not-working/78257

I was trying to see how Defold could handle different resolutions on different devices. But it seems that the engine picks only the top qualifier on the list?

I setup a simple test project to show this, here is the compressed file:

[Mobile game.zip](https://github.com/user-attachments/files/17129844/Mobile.game.zip)

I deployed and tested on an iPhone 14 and iPad Air 4.

On the iPhone the portrait/landscape layouts look like this:

![IMG_3425 PNG](https://github.com/user-attachments/assets/989daaec-d357-4399-89c3-4571163076eb)
![IMG_3426 PNG](https://github.com/user-attachments/assets/a74457f6-95ce-4caa-b119-b48446450533)

On the iPad like this:

![IMG_0356 PNG](https://github.com/user-attachments/assets/dc0da64b-1222-4736-9fe4-eea7d89c96a9)
![IMG_0357 PNG](https://github.com/user-attachments/assets/aebb7989-12ec-42a6-9fa2-b97e1d6c57f8)

So from my point of view on the iPad the portrait layout is wrong and on the iPhone the landscape layout is wrong.

Any thoughts?

**Comment by AGulev** [comment]
I tried to explain what's going on here https://forum.defold.com/t/display-profile-qualifiers-not-working/78257/6?u=agulev
I don't see any issue here
