### ISSUE TITLE
Syntax error in buffer file(editor)

### ISSUE THREAD

**Issue by d954mas** [defold/defold#9469]
### Expected behaviour
After today update of editor. 25.09.2024

Build from editor not worked.
Build html worked.
Bundle for html worked
Bundle for windows worked

Last version of editor was 1.9.3.

@britzl 
@AGulev 
```
[
  {
    "name": "position",
    "type": "float32",
    "count": 3,
    "data": [0,0,0]
  },
  {
    "name": "normal",
    "type": "float32",
    "count": 3,
    "data": [0,0,0]
  },
  {
    "name": "texcoord0",
    "type": "float32",
    "count": 2,
    "data": [0,0]
  }
]
```

![2024-09-25_16-37-25](https://github.com/user-attachments/assets/987f24a2-08b2-4b2f-9258-269f4df33bb0)
[editor2.2024-09-25.log](https://github.com/user-attachments/files/17130211/editor2.2024-09-25.log)

### Actual behaviour

Build from editor worked.

### Steps to reproduce
I am not sure, i don't have time now to create repro case.
I will try to create later, after work or tomorrow

But i add all information that i have now.
<hr/>

<table>
<tr><td>Build time</td><td>2024-09-25T09:04:44.630840</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>0bb763ce72e99aaecbc49158d12644b239f11dfe</td></tr>
<tr><td>Defold engine sha</td><td>e4aaff11f49c941fde1dd93883cf69c6b8abebe4</td></tr>
<tr><td>Defold version</td><td>1.9.3</td></tr>
<tr><td>GPU</td><td>Intel(R) RaptorLake-S Mobile Graphics Controller</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 - Build 31.0.101.5186</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 11</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by AGulev** [comment]
https://github.com/defold/defold/pull/9470
