### ISSUE TITLE
Render Targets being used as texture bindings break if used as a more complex setup

### ISSUE THREAD

**Issue by gyxos-logan** [defold/defold#9476]
**Describe the bug**
When enabling textures in a certain combination for render pipeline materials, there seems to be a 50/50 chance that the rendering gets broken in some way.

**To Reproduce**
Repro: [defold-texture-bind-render-target-issue.zip](https://github.com/user-attachments/files/17144351/defold-texture-bind-render-target-issue.zip)

Run the repro project multiple times. Sometimes it will work, sometimes it will not.
- White box - working
- Red screen - broken

You can try resizing the window - which deletes and recreates the render targets - this doesn't solve the issue.

**Expected behavior**
Should always start up and show a white box.

**Defold version:** 
  - Tested and broken on: 1.8.1, 1.9.2, 1.9.3, 1.9.4 alpha

**Platforms:**
 - Platforms: Windows (Unable to test other platforms)
 - OS: Windows 11
 - Device: Happens on both my desktop (AMD CPU with RTX GPU) and my laptop (Intel with IGPU)

**Workaround:**
No workaround, found if one of the texture bindings is not set, then it works fine. Line 182 in main.render_script has details.

**Screenshots:**
![image](https://github.com/user-attachments/assets/bd75c217-c3fa-4518-9c21-a278cb3074b5)
![image](https://github.com/user-attachments/assets/9fea7c6b-6b33-4ca8-a5f0-f8bb12651c75)

**Comment by Jhonnyg** [comment]
Thanks, I'll take a look!

**Comment by Jhonnyg** [comment]
This is an issue in your example code.
The textures is a table with <sampler-name,RT> and when you iterate them in your pass function with the "pairs" function the order is not guaranteed. Instead if you put the sampler name in the table it will work:

```
textures = {
          {
              sampler = "tex0",
              render_target = render_target_red,
              buffer_type = graphics.BUFFER_TYPE_COLOR0_BIT,
          },
          {
              sampler = "tex1",
              render_target = render_target_main,
              buffer_type = graphics.BUFFER_TYPE_COLOR0_BIT,
          },
      },
```

**Comment by gyxos-logan** [comment]
Thanks for looking so quickly and yes that definitely works!

I'm unsure if there is still an issue here though, I'm enabling and disabling by their name "tex0", "tex1", not by their index/unit number.

e.g. your example reliably works, reversing them reliably breaks, but I don't think it should?

```
    for _, sampler in pairs(textures) do
        render.enable_texture(sampler.sampler, sampler.render_target, sampler.buffer_type)
    end

....

        textures = {
            {
                sampler = "tex1",
                render_target = render_target_main,
                buffer_type = render.BUFFER_COLOR0_BIT,
            },
            {
                sampler = "tex0",
                render_target = render_target_red,
                buffer_type = render.BUFFER_COLOR0_BIT,
            },
```
