### ISSUE TITLE
Maximised Defold editor shrinks when dialog boxes are shown (possible Wayland issue)

### ISSUE THREAD

**Issue by DestyNova** [defold/defold#9486]
**Describe the bug (REQUIRED)**
If Defold is run in a maximised window, it shrinks to its previous non-maximised size whenever a dialog box is shown.

**To Reproduce (REQUIRED)**
1. Resize the editor window to take up half the screen.
2. Click the maximise button.
3. Right click somewhere in the assets list and select "New file".

**Expected behavior (REQUIRED)**
A dialog appears asking you to name the new file.

**Actual behaviour**

1. The dialog appears, as expected
2. The main Defold editor window returns to its previous size (although the maximise button still indicates that it's maximised, so you have to click it twice to actually "remaximise").

**Defold version (REQUIRED):**
  - 1.9.3

**Platforms (REQUIRED):**
 - Platforms: Linux
 - OS: Pop!_OS 22.04 LTS, running KDE Plasma on Wayland
 - Device: Lenovo laptop with AMD Ryzen/Radeon

**Workarounds:**
Don't maximise the editor window; just drag it to fill the screen and leave it that way.

**Additional context (OPTIONAL):**
I suspect it may be a compatibility issue with Wayland. At various times, messages like the following appear in the terminal (although nothing is printed when I repeatedly trigger the behaviour):
```
(java:501337): Gdk-WARNING **: 18:36:39.757: XSetErrorHandler() called with a GDK error trap pushed. Don't do that.
```

**Comment by AGulev** [comment]
duplicate of https://github.com/defold/defold/issues/9303

**Comment by DestyNova** [comment]
Closing as duplicate.
