### ISSUE TITLE
Figure out the use of `--input` in bob.

### ISSUE THREAD

**Issue by vlaaad** [defold/defold#9495]
**Task (REQUIRED):**
We have an `-i`/`--input` command line argument in Bob. This commit removed the only use of this argument: https://github.com/defold/defold/commit/608c26c797492781c9f4162dfd3ac76d6e523912#diff-ea0d2982212f1d66d942bc5b6fe2aa39bf5f8e04a598c033fde540ecad14d6e3L613-L616 (in `Bob.java`). So it seems, previously, we had the "input" directory separately from the "root" directory (it seems this is the dir where we load the `game.project` and its deps from now on).

**Expected outcome (REQUIRED):**
We should figure out what to do with this. Deprecate/remove `--input` argument? Start using it again?

**Comment by britzl** [comment]
> We should figure out what to do with this. Deprecate/remove `--input` argument? Start using it again?

I don't think I've ever used the input argument to be honest! I can't think of a usecase for it.

**Comment by AGulev** [comment]
I'll take a look into it and report here (or in PR if it's needed)

**Comment by AGulev** [comment]
> I don't think I've ever used the input argument to be honest! I can't think of a usecase for it.

With new dependency building, this option is outdated. We can put effort to make it work again, but I think it doesn't worth it. 

My suggestion, mark option as depricated and exit bob if it is used.
