### ISSUE TITLE
Building Docs Fails on Windows

### ISSUE THREAD

**Issue by VowSoftware** [defold/defold#9500]
**Describe the bug (REQUIRED)**

I'm trying to build the engine and editor on Windows 11. The editor requires the docs to be successfully built. The docs are built as the last step while building the engine, or they can be built standalone.

While the engine itself was built successfully, I'm unable to build the docs, and therefore also unable to build the editor.

**To Reproduce (REQUIRED)**

The instructions I'm using to build the editor can be found here:
https://github.com/defold/defold/blob/dev/editor/README_BUILD.md#build-using-local-engine-and-tools

@vlaaad and I had a back-and-forth on Discord, but we didn't finish solving the issue:
https://discord.com/channels/250018174974689280/817015161737969705/1289292280204628100

Calling `$ ./scripts/build.py build_docs` results in an error:
[error_1.txt](https://github.com/user-attachments/files/17170661/error_1.txt)

This error is described by the line: `OSError: [WinError 193] %1 is not a valid Win32 application`.

Potential fix was posted on Discord:
https://discord.com/channels/250018174974689280/817015161737969705/1289312746013200478

After changing `./script/lein` to `./script/lein.bat` (but its absolute path instead of its relative path), it complained that the `LEIN_JAR` environment variable was not pointing to a valid location, despite it being defined in my $PATH. To fix this, I manually typed `export LEIN_JAR=<path_to_lein_jar>`, which solved that error.

The build process now pushes through the previous errors, but trips on a unicode error:
[error_2.txt](https://github.com/user-attachments/files/17170793/error_2.txt)

The description here is: `UnicodeEncodeError: 'charmap' codec can't encode characters in position 9703-9704: character maps to <undefined>`, which hasn't yet been solved.

Once the docs are able to be built, I should be able to successfully build the editor.

**Defold version (REQUIRED):**

1.9.4 `dev` branch

**Platforms (REQUIRED):**

Windows 11

**Comment by JCash** [comment]
For Vlad: You should setup a LEIN env variable in waf, that can change for various setups. 
See e.g. `conf.find_program('signtool', var='SIGNTOOL', mandatory = True, path_list = bindirs)`
The, in the build use that variable instead. It make the missing tool more apparent and gets a nice error.

Also, I think the install instructions of Lein should probably change to use HOmebrew, Chocolatey etc, so that the paths will be working more easily when setting it up.

**Comment by britzl** [comment]
CLosed via https://github.com/defold/defold/pull/9511
