### ISSUE TITLE
Add a "Fetch Libraries" button in the Dependencies section of game.project

### ISSUE THREAD

**Issue by Al-V-U** [defold/defold#9501]
It would be nice to add a "Fetch Libraries" button in the Dependencies section of game.project.”
![fetch fr](https://github.com/user-attachments/assets/6174f964-ec43-4e20-900a-0472f465d06e)

**Comment by vlaaad** [comment]
Hi! I think it's a great idea to ease fetching libraries when updating the dependencies. We already have an issue record to implement this feature (using the notification system): #6557

I'm closing the issue because it's a duplicate (but we still intend to implement it!)
