### ISSUE TITLE
Spine extension issue

### ISSUE THREAD

**Issue by vnavaselski-ms** [defold/defold#9519]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2024-07-29T18:23:25.696563</td></tr>
<tr><td>Defold channel</td><td>dev</td></tr>
<tr><td>Defold editor sha</td><td>d4994b939edd128407b3808160dd2decd9d31377</td></tr>
<tr><td>Defold engine sha</td><td>d4994b939edd128407b3808160dd2decd9d31377</td></tr>
<tr><td>Defold version</td><td>1.6.2</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"c241d95be2af48009259056e795a7672"'>c241d95be2af48009259056e795a7672</a></td></tr>
<tr><td>GPU</td><td>Apple M1 Max</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 88.1</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>aarch64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>14.6.1</td></tr>
<table>

**Comment by AGulev** [comment]
Please provide editor logs

**Comment by vlaaad** [comment]
Fixed in [hotfix-1.6.2](https://github.com/defold/defold/commits/hotfix-1.6.2/) with 4683d8f280b78b0b14479e4576a5cadb03df6d55
