### ISSUE TITLE
HTML5 build reuses old cached files

### ISSUE THREAD

**Issue by aglitchman** [defold/defold#9548]
**Describe the bug (REQUIRED)**
HTML5 build seems to reuse old cached files, because once an HTML5 build is created, it no longer changes when you click on ‘Build HTML5’. Tested only on scripts and models.

On the left as in HTML5 and unchanged when clicking on ‘Build HTML5’, and on the right as it should be after changes in the project:
![image](https://github.com/user-attachments/assets/879e7dc6-9053-4690-84ac-b872d76d3d00)

**To Reproduce (REQUIRED)**
1. `Build HTML5`.
2. Edit any script, save it.
3. `Build HTML5`.

**Defold version (REQUIRED):**
  - Version 1.9.4 `4aeae3d0faad01ccb8f8eb495e2f50896e35ec62`

**Platforms (REQUIRED):**
 - Platforms: HTML5
 - OS: Windows 10

**Comment by AGulev** [comment]
Thanks, I'll take a look
