### ISSUE TITLE
Unexpected scale effect on rotation animation

### ISSUE THREAD

**Issue by iustin-ghe** [defold/defold#9597]
### Expected behaviour
Same rotation animation should look identical running on different machines and OS versions.

### Actual behaviour
On a second laptop, the rotation affects the scale also.

### Steps to reproduce

The lines:

```
self.replay_button = gui.get_node('replay_button')
gui.animate(self.replay_button, "rotation.z", -360, gui.EASING_INOUTSINE, 1, 0.25) 
```

which target the green replay arrow button render the following:

https://github.com/user-attachments/assets/20bab0d1-40ac-4135-8e9b-b68975825172

### Bugged setup
<hr/>

<table>
<tr><td>Build time</td><td>2024-10-04T11:57:31.373490</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>ef2ce600e47a7840cca1342ab3653b25a8b0f5fe</td></tr>
<tr><td>Defold engine sha</td><td>e4aaff11f49c941fde1dd93883cf69c6b8abebe4</td></tr>
<tr><td>Defold version</td><td>1.9.3</td></tr>
<tr><td>GPU</td><td>Apple M1 Pro</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 89.3</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>aarch64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>15.0.1</td></tr>
<table>

### Working setup

On an older laptop, the exact same project version works as expected:

https://github.com/user-attachments/assets/c372f9a8-f836-46f1-918d-544766fdb6f3

### Working setup
<hr/>
<table>
<tr><td>Build time</td><td>2023-09-04T08:35:39.230379</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>3dc2224fcf3af8f69cd4369ee34979db0977c6dc</td></tr>
<tr><td>Defold engine sha</td><td>57b34efdf44a922acc6f21d285b207029b53927d</td></tr>
<tr><td>Defold version</td><td>1.5.0</td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 5300M OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-5.1.35</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>14.1.2</td></tr>
<table>

**Comment by AGulev** [comment]
This is a breaking change introduced in 1.8.0 https://forum.defold.com/t/defold-1-8-0-has-been-released/76792
`rotation` property is quaternion now
use `euler` instead

**Comment by iustin-ghe** [comment]
That did the trick. Thanks for the quick response @AGulev!
