### ISSUE TITLE
Improve project templates `game.project` settings

### ISSUE THREAD

**Issue by aglitchman** [defold/defold#9619]
**Is your feature request related to a problem? Please describe (REQUIRED):**
I've noticed that in Discord people often ask the same questions, which can be avoided by tweaking the defaults in the project templates. 

These are the ones you can definitely enable by default:
- HTML5: scale mode = `stretch`, so that the HTML5 version has the same behavior as the desktop / mobile versions, when the game occupies all the canvas space available to it.
- High DPI = `on`, so that the game defaults to using all available display pixels.

**Describe the solution you'd like (REQUIRED):**
Tweak the game.project.

**Comment by aglitchman** [comment]
Example of the improvement - https://github.com/defold/template-empty/pull/6

**Comment by aglitchman** [comment]
As an example of the scale mode question (I've seen the same questions numerous times!)
![image](https://github.com/user-attachments/assets/1e0dad94-b4c9-4c81-a160-f18d7894b54a)

The answer:
![image](https://github.com/user-attachments/assets/cb0153e3-9f5b-4957-b300-d02173c502d1)

"Downscale Fit" is the default mode now.

**Comment by britzl** [comment]
@aglitchman are there any templates left to fix?

**Comment by aglitchman** [comment]
> @aglitchman are there any templates left to fix?

All templates have been updated. The issue can be closed!
