### ISSUE TITLE
Model with 2 or more root bones crash editor

### ISSUE THREAD

**Issue by Mulderua** [defold/defold#9632]
**Describe the bug (REQUIRED)**
After the update to 1.9.4 two of my projects crush when I am making a build or trying an open model with 2 or more root bones

**To Reproduce (REQUIRED)**
Add a model to the main collection with 1 or more roots bones
Another way is an open model with multiple roots 

**Expected behavior (REQUIRED)**
1. At least an error message that Defold doesn't support multiple roots

**Defold version (REQUIRED):**
1.9.4

**Platforms (REQUIRED):**
 - Platforms: Tested on Windows

**Minimal repro case project (OPTIONAL):**
I have shared a model that crushes editor on the forum:
https://forum.defold.com/uploads/short-url/c0Sambdxm5r0aEAdBFc22yDmHXW.zip

**Workaround (OPTIONAL):**
Recreate models that have one root

**Comment by JCash** [comment]
Thanks for the test file!
What is the license of this file? Would it be possible for us to add it to our unit tests, to help ensure future stability of the tools?

**Comment by Mulderua** [comment]
> Thanks for the test file! What is the license of this file? Would it be possible for us to add it to our unit tests, to help ensure future stability of the tools?

Here is just a cube I believe it is a better fit for unit test 

https://forum.defold.com/uploads/short-url/e9Abz3juFY0XNktOUhm8paqxM7z.zip
