### ISSUE TITLE
Multi-threading for Archive builder

### ISSUE THREAD

**Issue by AGulev** [defold/defold#9655]
**Task (REQUIRED):**
When building process is done. All the resources being packed into archive using `ArchiveBuilder`. I think this process can be multithreaded and significantly faster.

**Expected outcome (REQUIRED):**
Much faster `createArchive` step
![CleanShot 2024-10-25 at 17 20 20@2x](https://github.com/user-attachments/assets/7e6e2287-0d0d-408b-88f2-0437b2956dae)

**Comment by britzl** [comment]
Fixed via:

* https://github.com/defold/defold/commit/b0919ea1e8f92a33a38fbf9f343c30580df63b24
* https://github.com/defold/defold/commit/68392f3ba96a430db95700b1f93de9c8c4b149da
