### ISSUE TITLE
Backface culling not working in webgl

### ISSUE THREAD

**Issue by Asterosaur** [defold/defold#9684]
**Describe the bug (REQUIRED)**
I've set backface culling in the render script, it works as intended in the build, but when built in html5 both sides of polygons are shown

**To Reproduce (REQUIRED)**

Sample project is on the github repo https://github.com/Asterosaur/pairs

1. Build the project and see only front sides of the card showing up
2. Make html5 build
3. Both sides are shown

**Expected behavior (REQUIRED)**
Back faces of the polygon shouldn't be visible

**Defold version (REQUIRED):**
1.9.4

**Platforms (REQUIRED):**
HTML5

**Minimal repro case project (OPTIONAL):**
https://github.com/Asterosaur/pairs

**Workaround (OPTIONAL):**
Might try to make custom shader for it

**Comment by Jhonnyg** [comment]
Hi, I can't access the project via the link.

**Comment by Asterosaur** [comment]
> Hi, I can't access the project via the link.

Yeah sorry, Made it public right now
