### ISSUE TITLE
Search in File throws error after a file have been moved

### ISSUE THREAD

**Issue by Jerakin** [defold/defold#9690]
### Steps to reproduce
Unsure. The file have been moved. Through drag and drop within Defold

<hr/>

<table>
<tr><td>Build time</td><td>2024-10-04T11:53:41.364164</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>ef2ce600e47a7840cca1342ab3653b25a8b0f5fe</td></tr>
<tr><td>Defold engine sha</td><td>e4aaff11f49c941fde1dd93883cf69c6b8abebe4</td></tr>
<tr><td>Defold version</td><td>1.9.3</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"0a7095abb5e44a9fa2d27dc5d63c9549"'>0a7095abb5e44a9fa2d27dc5d63c9549</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon RX 7900 XT</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 Compatibility Profile Context 24.10.27.01.240827</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by AGulev** [comment]
Duplicate https://github.com/defold/defold/issues/9449
