### ISSUE TITLE
Feature Request: Expose HTML5 Canvas options: Alpha and Anti-Aliasing

### ISSUE THREAD

**Issue by britzl** [defold/defold#9707]
Looking at the xxx_wasm.js these are set statically and have to be changed after bundle time if we want these enabled:
![Image](https://github.com/user-attachments/assets/b36c3ea9-cef8-42a8-b8eb-56a9079d1dc0)

**Comment by ekharkunov** [comment]
Here is a full piece of code from Emscripten https://github.com/emscripten-core/emscripten/blob/main/src/library_browser.js#L194-L217. When call `Browser.createContext` last argument contains contextAttributes that can be defined inside our code.
Here is how it's defined in our part: https://github.com/defold/defold/blob/dev/external/glfw/js/library_glfw.js#L738-L761.

**Comment by ekharkunov** [comment]
`alpha` attribute added in #9721 . To enable `antialias` go to game.project and set `display.samples` to non-zero value.
