### ISSUE TITLE
Erroneous error when model count set to 0

### ISSUE THREAD

**Issue by benjames-171** [defold/defold#9715]
**Describe the bug (REQUIRED)**
When the model count is set to 0 in game.project, the following error is displayed when running project:
Model could not be created since the buffer is full (0). Increase the 'model.max_count' value in [game.project](defold://open?path=/game.project)

**To Reproduce (REQUIRED)**
1. Set model count to 0 (zero) in game.project
2. Build and run project
3. Error should be displayed in console

**Expected behavior (REQUIRED)**
Project should run as normal

**Defold version (REQUIRED):**
1.9.4

**Platforms (REQUIRED):**
Windows

**Minimal repro case project (OPTIONAL):**
Please attach a minimal project where the bug is reproduced. This will greatly help the person trying to investigate and fix the bug.

**Logs (OPTIONAL):**
Please provide relevant logs from engine, editor or build server. Learn where the logs are stored [here](https://defold.com/manuals/getting-help/#log-files).

**Workaround (OPTIONAL):**
Set model count to 1 or more.

**Screenshots (OPTIONAL):**

**Additional context (OPTIONAL):**

**Comment by Jhonnyg** [comment]
Hm, that error will only be shown if you are actually using a model component:
https://github.com/defold/defold/blob/564fd9d3a1349f33d87715a426f44554b35caba7/engine/gamesys/src/gamesys/components/comp_model.cpp#L859

Are you _sure_ you aren't using any models in your game? To me it looks like this the error is actually showing what's wrong 🤔

**Comment by benjames-171** [comment]
Yes you are right! I am using a single quad. My mistake.
