### ISSUE TITLE
java.lang.IllegalStateException: Invalid use of BasicClientConnManager: connection still allocated.

### ISSUE THREAD

**Issue by SalavatR** [defold/defold#9723]
**Describe the bug (REQUIRED)**
Build with bob:

ERROR: unspecified:-1: 'com.dynamo.bob.CompileExceptionError: 'wasm-web' could not be built. Sdk version: '3251ca82359cf238a1074e383281e3126547d50b'
Log: '<failed reading log>''

'wasm-web' could not be built. Sdk version: '3251ca82359cf238a1074e383281e3126547d50b'
Log: '<failed reading log>'
Cause: java.lang.IllegalStateException: Invalid use of BasicClientConnManager: connection still allocated.
Make sure to release the connection before allocating another one.
2024-11-12 11:14:51 SEVERE  'wasm-web' could not be built. Sdk version: '3251ca82359cf238a1074e383281e3126547d50b'
Log: '<failed reading log>' 

**To Reproduce (REQUIRED)**

```
@java -jar $(BOB_FILE) \
    --settings game.project \
    --bundle-output dist \
    --build-report-html build/report.html \
    --variant release \
    --archive \
    --platform js-web \
    --use-async-build-server \
    --liveupdate yes \
    resolve clean distclean build bundle
```

**Defold version (REQUIRED):**
  - Version 1.9.2

**Comment by britzl** [comment]
@SalavatR why was this closed?

**Comment by britzl** [comment]
Ah, the build server was down during the period when you tried building. 👍
