### ISSUE TITLE
Double-click the appmanifest file in Defold to open it in text mode.

### ISSUE THREAD

**Issue by CodeLazier** [defold/defold#9727]
![2024-11-12_210930](https://github.com/user-attachments/assets/06fe7b67-e340-4bee-aa8a-3b04a17ce3a3)

win 10 x64

**Comment by AGulev** [comment]
what the issue?

**Comment by AGulev** [comment]
that's how this file works:
it opens in the text editor mode with an ability to fast edit some of the properties using "properties" view
![CleanShot 2024-11-12 at 14 29 23@2x](https://github.com/user-attachments/assets/ece4fa3f-8649-4807-82b8-dced94e7f7b9)

**Comment by CodeLazier** [comment]
It seems I misunderstood. I had the impression that the properties window would appear in the code editor, like game.project.

**Comment by AGulev** [comment]
no, not in this case. 
This window may have a lot of custom settings in many different combinations. So texts editing is more like `pro-view` and "properties" for easier setup
