### ISSUE TITLE
Html5 liveupdate mount issue after page reload

### ISSUE THREAD

**Issue by maningame** [defold/defold#9745]
**Describe the bug (REQUIRED)**
Before html5 game starts, i download a bunch of liveupdate archives from server. Archives mounted via liveupdate.add_mount. After all archives are loaded, the game works fine. But if u reload page, there are only 3 entries in liveupdate.get_mounts() (_base, and two first zip archives), all others archives downloading again. After each page reload, two archives are added to liveupdate.get_mounts() until all are added.

In browser console i have this warning when downloading zip-archive:
```
dmloader.js?v=59:996 Unable to synchronize mounted file systems: [object Object]
```
Warning thrown by this code in dmloader.js:
```
    _startSyncFS: function() {
        Module._syncInProgress = true;

        if (Module._syncMaxTries > Module._syncTries) {
            FS.syncfs(false, function(err) {
                Module._syncInProgress = false;

                if (err) {
                    console.warn("Unable to synchronize mounted file systems: " + err);
                    Module._syncTries += 1;
                }

                if (Module._syncNeeded) {
                    Module._syncNeeded = false;
                    Module._startSyncFS();
                }

            });
        }
    },
```
The problem is with (Module._syncMaxTries > Module._syncTries). Every thrown error increments Module._syncTries += 1. Module._syncMaxTries is set to 3, so its obviously is the answer why only two zip-archives put to FS per page reload. If i replace 
Module._syncTries += 1 to Module._syncTries = 0; all zip archives are loaded to persistent storage. But its dirty hack.

if we fix console.warn to see the err, because err is object (console.warn("Unable to synchronize mounted file systems: ", err) we will see this:
```
Unable to synchronize mounted file systems:  ErrnoError {name: 'ErrnoError', errno: 44, stack: '<generic error, no stack>'}
```

**To Reproduce (REQUIRED)**
1. Download and mount zip-archive liveupdate.add_mount;
2. See warning in browser console;
3. Download extra 3 archive and mount them;
4. Reload page;
5. Look pprint of liveupdate.get_mounts().

**Expected behavior (REQUIRED)**
All liveupdate zip-archives stored in persistent storage.

**Defold version (REQUIRED):**
  - Version 1.9.4, 1.9.1, (also saw this in old game build from 8 jul, but i dont remember defold version)

**Platforms (REQUIRED):**
 - Platforms: html5 (Chrome, Firefox)
 - OS: Windows 7 - 11, Ubuntu 22.04, macOS Sequoia 15.0.1
 - Device: PC

**Screenshots (OPTIONAL):**
![Screenshot from 2024-11-13 14-17-43](https://github.com/user-attachments/assets/defa3e04-67f8-481c-9123-5e074b52ee75)
![Screenshot from 2024-11-13 14-18-09](https://github.com/user-attachments/assets/e60a391f-8909-4f8f-9c23-b54f10d442ba)

**Workaround (OPTIONAL):**
To download and mount all archives replace Module._syncTries += 1 to Module._syncTries = 0 in _startSyncFS: function() {.

**Comment by maningame** [comment]
I have found the source of warning "Unable to synchronize mounted file systems". I download and save zip-archives with http.request (with option path):
```
  http.request(url, "GET", function (self, id, response)
    ...
  end, nil, nil, { path = download_path, report_progress = true, })
```
If i dont use this option and save file with io.* all works as expected and no warning arise.

**Comment by ekharkunov** [comment]
> I have found the source of warning "Unable to synchronize mounted file systems". I download and save zip-archives with http.request (with option path):
> 
> ```
>   http.request(url, "GET", function (self, id, response)
>     ...
>   end, nil, nil, { path = download_path, report_progress = true, })
> ```
> 
> If i dont use this option and save file with io.* all works as expected and no warning arise.

@maningame Can you provide an example of how `download_path` looks like?
And example of how you save downloaded result via `io.*` module.
Thanks!
