### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by Ussy295** [defold/defold#9760]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2024-11-14T15:59:51.767190</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>2020211ad2932369e5764c1ea6251b10ff584666</td></tr>
<tr><td>Defold engine sha</td><td>edfdbe31830c1f8aa4d96644569ae87a8ea32672</td></tr>
<tr><td>Defold version</td><td>1.9.4</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"8ab4fa4886eb4a0bab0752d1f91efc2d"'>8ab4fa4886eb4a0bab0752d1f91efc2d</a></td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GTX 960/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 566.03</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by Ussy295** [comment]
![image](https://github.com/user-attachments/assets/49e0cf83-8663-4e65-87c6-b262fe4aa864)

**Comment by vlaaad** [comment]
Deleting `~/AppData/Roaming/Defold/prefs.editor_settings` should help as a workaround.
