### ISSUE TITLE
Inconsistent Behavior of GUI Templates and Layouts Between Linux and HTML5 Builds

### ISSUE THREAD

**Issue by 0xbeefbeef** [defold/defold#9787]
Describe the bug (REQUIRED)
GUI templates and layouts do not work consistently across different platforms (e.g., Linux vs HTML5). Using GUI templates is intended to avoid redundant code and design, but when supporting different layouts, this functionality breaks:

On Linux builds, GUI templates always use the Default layout, completely ignoring other defined layouts.
On HTML5 builds, the layout functionality works better, but overriding text node content in a GUI template is ignored. On Linux, text overrides work in the Default layout.

To Reproduce (REQUIRED)

Create a GUI template with multiple layouts (e.g., Default and an additional layout).
Use the GUI template in a scene.
On Linux: Attempt to use a layout other than Default.
On HTML5: Override a text node's content in the GUI template.
Build and observe the behavior differences.

Expected behavior (REQUIRED)
On Linux, the GUI template should respect the selected layout and not default to the Default layout.
On HTML5, overriding text node content in a GUI template should function as expected.

Defold version (REQUIRED):
Version 1.7.0 (unable to use newer versions due to FMOD asset compatibility issues).

Platforms: Linux, HTML5
OS: Linux Mint, HTML5 browser (tested in Chrome)

Logs (OPTIONAL):
No specific logs show errors; the issue is with inconsistent runtime behavior.

Workaround (OPTIONAL):
Currently, no viable workaround exists to ensure consistent behavior across platforms.

Screenshots (OPTIONAL):
Add screenshots of your setup, showcasing the layout behavior differences if helpful.

Additional context (OPTIONAL):
This bug limits the practicality of using GUI templates for cross-platform projects and undermines the concept of reusable and adaptable GUI components.

**Comment by AGulev** [comment]
Please provide an example project where the issue you reported is reproducible.

**Comment by 0xbeefbeef** [comment]
[template_layout_problem.zip](https://github.com/user-attachments/files/17815570/template_layout_problem.zip)

Here is a minimal example:
- Overriding nodes doesn't work in HTML5 builds, but the layouts are applied to the parent as well as the template
- Overriding nodes seems to work in Linux build (at least in the Default layout), but layouts are only applied to the parent gui, not the template.

**Comment by AGulev** [comment]
I think this issue fixed in 1.9.6 

here screenshot from 1.9.5 
![CleanShot 2024-12-07 at 18 01 48@2x](https://github.com/user-attachments/assets/43e9bb5f-b8a0-4a59-87d3-e7680bd872f5)


from 1.9.6
![CleanShot 2024-12-07 at 18 02 37@2x](https://github.com/user-attachments/assets/fb039b56-9306-4c20-b483-f4a82383cc5c)

Could you please verify @0xbeefbeef ?

FYI @matgis

**Comment by 0xbeefbeef** [comment]
Hi Alexey,
thank you for that info. You might be right and this is already fixed in 1.9.6. Unfortunately, my project is based on FMOD as audio engine, and there is an issue with the FMOD asset which makes FMOD working on HTML5 builds only up to version 1.7.0. So I am somehow stuck there (see this [issue](https://github.com/defold/defold/issues/9308) and [this](https://github.com/dapetcu21/defold-fmod/issues/32)).

I could try it on the newest Defold version, however, it will not help me right now ;) But anyway, it's good this is solved in newer versions! Thanks alot!
