### ISSUE TITLE
Camera component(s) should have precedence in the render script by default

### ISSUE THREAD

**Issue by Jhonnyg** [defold/defold#9842]
**Task (REQUIRED):**
To use a camera component in Defold, you need to send a message to the renderer:
`msg.post("@render:", "use_camera_projection")`

This will set the projection and view matrices from the _last_ camera in the camera stack. It's a really hidden workflow (especially for 3D) and really confusing for beginners coming from other engines where a camera component would work immediately. I see no reason at all why we have this UX.

We currently have a few ways of working with "cameras":
* actual camera components
* set view/proj from messages
* set view/proj function from message
* set view/proj manually in render script

My suggestion to improve this situation is that if there is a camera component, it should have precedence over the other projection modes. To use the custom "fixed", "fixed_fit" and "stretch" modes, the users should disable the camera component or modify the render script. In the long(er) run, we should consider adding add these projection modes to the camera component itself. 

**Expected outcome (REQUIRED):**
If I add a camera to the scene, it should be used without any further setup.

**Comment by britzl** [comment]
> My suggestion to improve this situation is that if there is a camera component, it should have precedence over the other projection modes. To use the custom "fixed", "fixed_fit" and "stretch" modes, the users should disable the camera component or modify the render script. In the long(er) run, we should consider adding add these projection modes to the camera component itself.

Totally! Great suggestion!
