### ISSUE TITLE
Failed to create vertex program '/_generated_3ae06e28.vpc': Unable to compile vertex shader.

### ISSUE THREAD

**Issue by selimanac** [defold/defold#9850]
This started happening after the latest update (5cffdac91340aa8e50f0c139ad483f8ab35d8dc2). It was working before. I haven't changed anything in game.render_script, game.render, or shadow_pass.material for a long time.

Using: https://build-stage.defold.com/

The engine crashes with the following error:

```

ERROR:GAMESYS: Failed to create vertex program '/_generated_3ae06e28.vpc': Unable to compile vertex shader.
Error: ERROR: 0:6: Unknown identifier 'binding' in layout
ERROR: 0:20: Use of undeclared identifier '_13'

WARNING:RESOURCE: Unable to create resource: /_generated_3ae06e28.vpc: FORMAT_ERROR
WARNING:RESOURCE: Unable to create resource: /components/materials/shadow/shadow_pass.materialc: FORMAT_ERROR
WARNING:RESOURCE: Unable to create resource: /render/game.renderc: FORMAT_ERROR
ERROR:ENGINE: Unable to load bootstrap data.

```

### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2024-11-27T18:24:54.004054</td></tr>
<tr><td>Defold channel</td><td>alpha</td></tr>
<tr><td>Defold editor sha</td><td>5cffdac91340aa8e50f0c139ad483f8ab35d8dc2</td></tr>
<tr><td>Defold engine sha</td><td>5cffdac91340aa8e50f0c139ad483f8ab35d8dc2</td></tr>
<tr><td>Defold version</td><td>1.9.6</td></tr>
<tr><td>GPU</td><td>Apple M2 Pro</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 88.1</td></tr>
<tr><td>Java version</td><td>21.0.5+11-LTS</td></tr>
<tr><td>OS arch</td><td>aarch64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>14.7.1</td></tr>
<table>

**Comment by Jhonnyg** [comment]
Can you update your editor and try again? I did a hotfix for this just now.

**Comment by selimanac** [comment]
> Can you update your editor and try again? I did a hotfix for this just now.

Fixed. Thank you :)
