### ISSUE TITLE
Collection Game Object breaks down if multiple scripts are added to it

### ISSUE THREAD

**Issue by SurfaceToAsh** [defold/defold#9866]
### Expected behaviour
When adding multiple scripts to a game object in a collection, it's expected that the game object is still able to load and function properly
### Actual behaviour
After adding multiple scripts to a game object in a collection, functionality and the ability to load begins to break down
### Steps to reproduce
Precondition: at least 3 scripts exist in the project
In any project, locate the main collection
right click collection
click "Add Game Object"
right click game object
click "Add component file"
in the filter type ".script"
select 3 secripts to add to the go
click "OK"
bundle the package
run the .exe
Observe the error/crash
<hr/>

<table>
<tr><td>Build time</td><td>2024-11-26T11:59:29.579428</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>e7b40fc66aa80d1ec6a67c86172c50d802532d5b</td></tr>
<tr><td>Defold engine sha</td><td>d01194cf0fb576b516a1dca6af6f643e9e590051</td></tr>
<tr><td>Defold version</td><td>1.9.5</td></tr>
<tr><td>GPU</td><td>AMD Radeon(TM) Graphics</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 Compatibility Profile Context 24.10.27.01.240827</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 11</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by AGulev** [comment]
https://forum.defold.com/t/error-could-not-create-script-component-out-of-resources/79023/6
