### ISSUE TITLE
Bitdefender has locked moddebug.luac after trying to build Android package

### ISSUE THREAD

**Issue by jokeane** [defold/defold#9967]
### Expected behaviour
run with debugger

### Actual behaviour
crashes due to Bitdefender locking this file
java.io.FileNotFoundException: C:\projects\over_the_rainbow\Defold\build\default\builtins\scripts\mobdebug.luac (Access is denied)

### Steps to reproduce
Windows 10, Bitdefender installed. I've tried re-installing Defold 1.9.0 and re-fetching libraries but nothing fixes it.

<hr/>

<table>
<tr><td>Build time</td><td>2024-06-25T16:26:09.046426</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>3642fa5b700b8d6e74e3f0595e75cd50eff54459</td></tr>
<tr><td>Defold engine sha</td><td>d6882f432beca85d460ec42497888157c356d058</td></tr>
<tr><td>Defold version</td><td>1.9.0</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"f86b5a47b5fb42af84847082b1af2d88"'>f86b5a47b5fb42af84847082b1af2d88</a></td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce RTX 4070/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 560.94</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by jokeane** [comment]
Bitdefender message:

Infected file detected
15 minutes ago

Feature:
Antivirus

The file C:\projects\over_the_rainbow\Defold\build\default\builtins\scripts\mobdebug.luac is infected with Generic.Lua.Stealer.A.3F6F2705 and was moved to quarantine. It is recommended that you run a System Scan to make sure your system is clean.

**Comment by JCash** [comment]
I'd recommend you reporting the issue to your antivirus provider, as there is no good way for us to handle this scernario.
Or, if you have a suggestion on how to fix this (e.g. PR), we can take a look.
In the meantime, we'll close this as won't fix.

**Comment by jokeane** [comment]
So you are saying it isn't infected? Did you verify this?On Dec 22, 2024 11:15 AM, Mathias Westerdahl ***@***.***> wrote:
I'd recommend you reporting the issue to your antivirus provider, as there is no good way for us to handle this scernario.
Or, if you have a suggestion on how to fix this (e.g. PR), we can take a look.
In the meantime, we'll close this as won't fix.

**Comment by jimokeane** [comment]
Can you please verify that moddebug.luac is clean and without virus / malware? I cannot validate it myself since it is a compiled file.

**Comment by britzl** [comment]
> Can you please verify that moddebug.luac is clean and without virus / malware? I cannot validate it myself since it is a compiled file.

Here is mobdebug.lua:

https://github.com/defold/defold/blob/dev/engine/engine/content/builtins/scripts/mobdebug.lua

It is compiled using LuaJIT 2.1.0 sha1: 04dca79:

https://github.com/defold/defold/blob/dev/packages/luajit-2.1.0-04dca79-x86_64-win32.tar.gz

Compilation is done in our command line tool here:

https://github.com/defold/defold/blob/dev/com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/LuaBuilder.java#L362-L397

And from the editor here:

https://github.com/defold/defold/blob/dev/editor/src/clj/editor/luajit.clj#L71-L101

You will have to judge for yourself if this is good enough and code that you can trust or not. We have thousands of users on Windows and I've never heard of anything other than false positives from anti virus software.
